### PR TITLE
CrashReporter: Implement `Save Backtrace` button

### LINKED ISSUE #13472: CrashReporter: Save report as text file
Co-authored: @ADKaster

### PR DESCRIPTION
**Pull request by alichraghi**
a button to save backtrace as a file
Fixes #13472

### CODE REVIEW

**Review by kleinesfilmroellchen — APPROVED** [review]

**Comment by alichraghi** [comment]
Probably a small problem. But because of removing `Build/` it takes a little longer

**Review by kleinesfilmroellchen — APPROVED** [review]

File: Userland/Applications/CrashReporter/main.cpp [hunk 1]
```diff
@@ -301,6 +324,7 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
                 backtrace_text_editor->set_text(backtrace.text);
                 backtrace_text_editor->set_mode(GUI::TextEditor::Mode::ReadOnly);
                 backtrace_text_editor->set_should_hide_unnecessary_scrollbars(true);
+                full_backtrace.append(backtrace.text);
```
Comment (timschumi) [inline Userland/Applications/CrashReporter/main.cpp:327]: How does this look with multiple threads? Should we delimit the different threads by using the backtrace title somehow?

**Review by timschumi — CHANGES_REQUESTED** [review]

File: Userland/Applications/CrashReporter/main.cpp (hunk 1 above)
Comment (timschumi) [reply Userland/Applications/CrashReporter/main.cpp]: Could use a space between the `====` and the title (just to avoid it looking a bit cramped), after that it will presumably look quite OK.

Comment (alichraghi) [reply Userland/Applications/CrashReporter/main.cpp]: done!

**Review by kleinesfilmroellchen — APPROVED** [review]

**Review by timschumi — APPROVED** [review]

File: Userland/Applications/CrashReporter/main.cpp [hunk 2]
```diff
@@ -301,6 +324,7 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
                 backtrace_text_editor->set_text(backtrace.text);
                 backtrace_text_editor->set_mode(GUI::TextEditor::Mode::ReadOnly);
                 backtrace_text_editor->set_should_hide_unnecessary_scrollbars(true);
+                full_backtrace.append(String::formatted("==== {} ====\n{}\n", backtrace.title, backtrace.text));
```
Comment (linusg) [inline Userland/Applications/CrashReporter/main.cpp:327]:
```suggestion
                full_backtrace.appendff("==== {} ====\n{}\n", backtrace.title, backtrace.text);
```

**Review by linusg — CHANGES_REQUESTED** [review]
Commit message says "Save as"

File: Userland/Applications/CrashReporter/main.cpp [hunk 3]
```diff
@@ -301,6 +324,7 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
                 backtrace_text_editor->set_text(backtrace.text);
                 backtrace_text_editor->set_mode(GUI::TextEditor::Mode::ReadOnly);
                 backtrace_text_editor->set_should_hide_unnecessary_scrollbars(true);
+                full_backtrace.appendff(String::formatted("==== {} ====\n{}\n", backtrace.title, backtrace.text));
```
Comment (linusg) [inline Userland/Applications/CrashReporter/main.cpp:327]: Look at my suggestion again, appendff doesn't need String::formatted :)

**Review by linusg — APPROVED** [review]
