### PR TITLE
Kernel: Ensure jailed processes can be reaped by a jailed parent process

### LINKED ISSUE #17810: SystemMonitor: Crashes when creating and attaching another program to a jail
```
12.653 SystemMonitor(53:53): ASSERTION FAILED: is_within_range(index)
./Userland/Applications/SystemMonitor/ProcessModel.cpp:145
12.653 [#0 SystemMonitor(53:53)]: Terminating SystemMonitor(53) due to signal 6
12.662 [#0 Finalizer Task(5:5)]: Backtrace:
0x00000000deadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x383
12.662 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 53
12.693 CrashDaemon(42:42): New coredump file: /tmp/coredump/SystemMonitor_53_1678560768
13.022 CrashReporter(57:57): Started Thread "Background Thread"(58)
16.371 CrashReporter(57:58): Generating backtrace took 3291 ms
16.371 CrashReporter(57:58): --- Backtrace for thread #0 (TID 53) ---
16.371 CrashReporter(57:58): 0x00000006340d402b: [/usr/lib/libsystem.so] syscall2 +0xb (syscall.cpp:25 => syscall.cpp:24)
16.375 CrashReporter(57:58): 0x00000005d1aaf48d: [/usr/lib/libc.so] abort +0x26 (stdlib.cpp:386)
16.375 CrashReporter(57:58): 0x00000005d1ab5855: [/usr/lib/libc.so] __assertion_failed.localalias +0x85 (assert.cpp:34)
16.375 CrashReporter(57:58): 0x00000008afb7227b: [/bin/SystemMonitor] ProcessModel::data(GUI::ModelIndex const&, GUI::ModelRole) const [clone .localalias] +0xcb (ProcessModel.cpp:145)
16.379 CrashReporter(57:58): 0x0000000db7c383b5: [/usr/lib/libgui.so.serenity] GUI::SortingProxyModel::data(GUI::ModelIndex const&, GUI::ModelRole) const [clone .localalias] +0x55 (SortingProxyModel.cpp:116)
16.379 CrashReporter(57:58): 0x0000000db7c0e4ff: [/usr/lib/libgui.so.serenity] GUI::ModelIndex::data(GUI::ModelRole) const +0x3f (ModelIndex.cpp:19)
16.379 CrashReporter(57:58): 0x0000000db7c83064: [/usr/lib/libgui.so.serenity] AK::Function<AK::IterationDecision (GUI::ModelIndex const&)>::CallableWrapper<GUI::TreeView::traverse_in_paint_order<GUI::TreeView::item_count() const::{lambda(GUI::ModelIndex const&, Gfx::Rect<int> const&, Gfx::Rect<int> const&, int)#1}>(GUI::TreeView::item_count() const::{lambda(GUI::ModelIndex const&, Gfx::Rect<int> const&, Gfx::Rect<int> const&, int)#1}) const::{lambda(GUI::ModelIndex const&)#1}>::call(GUI::ModelIndex const&) +0x94 (TreeView.cpp:188 => Function.h:173)
16.384 CrashReporter(57:58): 0x0000000db7c7da77: [/usr/lib/libgui.so.serenity] GUI::TreeView::item_count() const +0x1c7 (Function.h:111)
16.384 CrashReporter(57:58): 0x0000000db7af1c3c: [/usr/lib/libgui.so.serenity] GUI::AbstractTableView::update_content_size() [clone .localalias] +0x27c (AbstractTableView.cpp:148)
16.384 CrashReporter(57:58): 0x0000000db7af1cb0: [/usr/lib/libgui.so.serenity] GUI::AbstractTableView::header_did_change_section_size(AK::Badge<GUI::HeaderView>, Gfx::Orientation, int, int) +0x10 (AbstractTableView.cpp:370)
16.388 CrashReporter(57:58): 0x0000000db7be3b35: [/usr/lib/libgui.so.serenity] GUI::HeaderView::set_section_size(int, int) +0x55 (HeaderView.cpp:42)
16.388 CrashReporter(57:58): 0x0000000db7aef2be: [/usr/lib/libgui.so.serenity] GUI::AbstractTableView::update_row_sizes() [clone .localalias] +0xde (AbstractTableView.cpp:132)
16.388 CrashReporter(57:58): 0x0000000db7af213d: [/usr/lib/libgui.so.serenity] GUI::AbstractTableView::model_did_update(unsigned int) +0x1d (AbstractTableView.cpp:354)
16.388 CrashReporter(57:58): 0x0000000db7c07817: [/usr/lib/libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) [clone .localalias] +0x87 (Function.h:111)
16.388 CrashReporter(57:58): 0x0000000db7c0793b: [/usr/lib/libgui.so.serenity] GUI::Model::did_update(unsigned int) [clone .localalias] +0x4b (Model.cpp:51)
16.392 CrashReporter(57:58): 0x0000000db7c07817: [/usr/lib/libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) [clone .localalias] +0x87 (Function.h:111)
16.392 CrashReporter(57:58): 0x0000000db7c0793b: [/usr/lib/libgui.so.serenity] GUI::Model::did_update(unsigned int) [clone .localalias] +0x4b (Model.cpp:51)
16.396 CrashReporter(57:58): 0x00000008afb751bd: [/bin/SystemMonitor] ProcessModel::update() +0x1bad (ProcessModel.cpp:569)
16.396 CrashReporter(57:58): 0x00000008afb537dc: [/bin/SystemMonitor] serenity_main(Main::Arguments)::{lambda()#2}::operator()() const +0xdc (main.cpp:320)
16.396 CrashReporter(57:58): 0x0000001841714ab9: [/usr/lib/libcore.so.serenity] Core::Timer::timer_event(Core::TimerEvent&) [clone .localalias] +0x69 (Function.h:111)
16.396 CrashReporter(57:58): 0x00000018416fd13a: [/usr/lib/libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7a (Object.cpp:220)
16.400 CrashReporter(57:58): 0x00000018416ef199: [/usr/lib/libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x159 (EventLoop.cpp:487)
16.400 CrashReporter(57:58): 0x00000018416efb89: [/usr/lib/libcore.so.serenity] Core::EventLoop::exec() +0x139 (EventLoop.cpp:444)
16.400 CrashReporter(57:58): 0x00000008afb56aa4: [/bin/SystemMonitor] serenity_main(Main::Arguments) +0x25f4 (main.cpp:509)
16.400 CrashReporter(57:58): 0x00000008afb4f56a: [/bin/SystemMonitor] main +0x14a (Main.cpp:43)
16.400 CrashReporter(57:58): 0x00000008afb4f6f8: [/bin/SystemMonitor] _entry +0x48 (crt0.cpp:4
```

How to reproduce:
1. Open `SystemMonitor`
2. In a terminal session, invoke `jail-attach -nTest /bin/Shell`
3. `SystemMonitor` should crash now

Even if you don't open `SystemMonitor` beforehand, trying to open it when the jail is alive will make it crashing too.

Found while working on #16980.

### PR DESCRIPTION
**Pull request by supercomputer7**
We were detaching from the jail process list too early. To ensure we detach properly, leverage the remove_from_secondary_lists method so the possibly jailed parent process can still see the dying process and therefore clean it properly.

Partially fixes #17810 (really we have 2 problems, so this will sufficiently close the first problem where we had zombie processes after they were jailed).

### CODE REVIEW

File: Kernel/Process.cpp [hunk 1]
```diff
@@ -820,6 +813,17 @@ void Process::unblock_waiters(Thread::WaitBlocker::UnblockFlags flags, u8 signal
         waiter_process->m_wait_blocker_set.unblock(*this, flags, signal);
 }
 
+void Process::remove_from_secondary_lists()
```
Comment (konradekk) [inline Kernel/Process.cpp:816]: why not name it explicitly, using a name that would describe what is being done at this very moment? (i.e. removing from jail process list)

Comment (konradekk) [inline Kernel/Process.cpp:816]: this method usage is nowhere to be found…? 🤔

Comment (supercomputer7) [reply Kernel/Process.cpp:816]: This is called here so I rather keep this way:
https://github.com/SerenityOS/serenity/blob/2b6c44852c6cb8127d870ec72b5d4c82df7825e0/Kernel/Library/ListedRefCounted.h#L37-L39

Comment (konradekk) [reply Kernel/Process.cpp:816]: oh! missed that (just read the code from your changes! 🙇🏻‍♂️)

**Review by GMTA — APPROVED** [review]
