### PR TITLE
 Kernel: Send SIGBUS to threads that use after valid Inode mmaped range (attempt #2)

### LINKED ISSUE #15332: Kernel: deadlock with SMP on
Hello,

i'm seeing a full hang or a crash with smp on that I've bisected to https://github.com/SerenityOS/serenity/commit/0c675192c91999cc2b60cbbea708dbf7b5637897#diff-8044716dd9983c8293d583c39148d26ec7427cfde6f75ffcb6862a684fbd481bR478-R484

The following diff fixes it and passes the js test suite, but I'm still new to Serenity.

```
diff --git a/Kernel/Memory/Region.cpp b/Kernel/Memory/Region.cpp
index 0a794e2e16..483a8021d9 100644
--- a/Kernel/Memory/Region.cpp
+++ b/Kernel/Memory/Region.cpp
@@ -472,23 +472,12 @@ PageFaultResponse Region::handle_inode_fault(size_t page_index_in_region, size_t
     auto page_index_in_vmobject = translate_to_vmobject_page(page_index_in_region);
     auto& vmobject_physical_page_slot = inode_vmobject.physical_pages()[page_index_in_vmobject];
 
-    {
-        // NOTE: The VMObject lock is required when manipulating the VMObject's physical page slot.
-        SpinlockLocker locker(inode_vmobject.m_lock);
-        if (inode_vmobject.inode().size() == 0)
-            return PageFaultResponse::BusError;
-        auto fault_vaddr = vaddr_from_page_index(page_index_in_vmobject).offset(offset_in_page_in_region);
-        auto inode_last_valid_address = vaddr().offset(inode_vmobject.inode().size());
-        if (inode_last_valid_address < fault_vaddr)
-            return PageFaultResponse::BusError;
-
-        if (!vmobject_physical_page_slot.is_null()) {
-            dbgln_if(PAGE_FAULT_DEBUG, "handle_inode_fault: Page faulted in by someone else before reading, remapping.");
-            if (!remap_vmobject_page(page_index_in_vmobject, *vmobject_physical_page_slot))
-                return PageFaultResponse::OutOfMemory;
-            return PageFaultResponse::Continue;
-        }
-    }
+    if (inode_vmobject.inode().size() == 0)
+        return PageFaultResponse::BusError;
+    auto fault_vaddr = vaddr_from_page_index(page_index_in_vmobject).offset(offset_in_page_in_region);
+    auto inode_last_valid_address = vaddr().offset(inode_vmobject.inode().size());
+    if (inode_last_valid_address < fault_vaddr)
+        return PageFaultResponse::BusError;
 
     dbgln_if(PAGE_FAULT_DEBUG, "Inode fault in {} page index: {}", name(), page_index_in_region);
 
@@ -538,14 +527,13 @@ PageFaultResponse Region::handle_inode_fault(size_t page_index_in_region, size_t
             if (!remap_vmobject_page(page_index_in_vmobject, *vmobject_physical_page_slot))
                 return PageFaultResponse::OutOfMemory;
             return PageFaultResponse::Continue;
+        } else {
+            vmobject_physical_page_slot = new_physical_page;
+            if (!remap_vmobject_page(page_index_in_vmobject, *vmobject_physical_page_slot))
+                return PageFaultResponse::OutOfMemory;
         }
-
-        vmobject_physical_page_slot = new_physical_page;
     }
 
-    if (!remap_vmobject_page(page_index_in_vmobject, *vmobject_physical_page_slot))
-        return PageFaultResponse::OutOfMemory;
-
     return PageFaultResponse::Continue;
 }
 ```

### PR DESCRIPTION
**Pull request by supercomputer7**
I broke SMP with #14785. After a couple of hours of debugging, splitting spinlocks and what not (even reverting my changes in #15336), I managed to find a conclusion what is wrong with my patch - we locked a spinlock and then a Mutex, thus, easily creating a deadlock situation.
I added a paragraph near the lock site to explain why we don't use that subset of my patch under the InodeVMObject spinlock.
Hopefully this will be enough, sorry for the inconvenience and the trouble.

#15336 fixed #15332 by reverting my changes, but this PR fixes #15332 completely.

### CODE REVIEW

File: Kernel/Arch/x86/common/Interrupts.cpp [hunk 1]
```diff
@@ -341,36 +341,40 @@ void page_fault_handler(TrapFrame* trap)
...
-            } else if ((fault_address & 0xffff0000) == (nonnullownptr_scrub_pattern & 0xffff0000)) {
-                dbgln("Note: Address {} looks like it may be a recently destroyed NonnullOwnPtr", VirtualAddress(fault_address));
-            } else if ((fault_address & 0xffff0000) == (lockrefptr_scrub_pattern & 0xffff0000)) {
-                dbgln("Note: Address {} looks like it may be a recently destroyed LockRefPtr", VirtualAddress(fault_address));
-            } else if ((fault_address & 0xffff0000) == (nonnulllockrefptr_scrub_pattern & 0xffff0000)) {
-                dbgln("Note: Address {} looks like it may be a recently destroyed NonnullLockRefPtr", VirtualAddress(fault_address));
+        if (response == PageFaultResponse::BusError) {
+            dbgln("Note: Address {} is an access to undefined memory range of a Inode-backed VMObject", VirtualAddress(fault_address));
+        } else {
+            if ((fault_address & 0xffff0000) == (malloc_scrub_pattern & 0xffff0000)) {
```
Comment (IdanHo) [inline Kernel/Arch/x86/common/Interrupts.cpp:347]: hmm, why are we indenting the whole block and not just using an `else if`?

File: Kernel/Memory/Region.cpp [hunk 2]
```diff
@@ -472,6 +472,27 @@ PageFaultResponse Region::handle_inode_fault(size_t page_index_in_region)
...
+        // 2. Calling inode_vmobject.inode().size() might require acquiring a mutex
+        //  of that inode. The Ext2FSInode::metadata() does that, for example.
+        //  Holding that lock while we try to lock this Spinlock will lead to
+        //  deadlocks as other processes might need to lock it, but we will not be able
+        //  to preempt under this Spinlock being held.
+        //
+        // Instead, we hold the Inode mutex of the InodeVMObject, to ensure
+        // we get the correct size, in both calls to inode_vmobject.inode().size(),
+        // so the Inode cannot change its size in that time.
+        MutexLocker locker(inode_vmobject.inode().inode_lock());
```
Comment (IdanHo) [inline Kernel/Memory/Region.cpp:487]: instead of doing that, can't we just fetch the size once instead of twice and use that?

File: Kernel/Arch/x86/common/Interrupts.cpp [hunk 3]
```diff
@@ -317,7 +317,7 @@ void page_fault_handler(TrapFrame* trap)
     PageFault fault { regs.exception_code, VirtualAddress { fault_address } };
     auto response = MM.handle_page_fault(fault);
 
-    if (response == PageFaultResponse::ShouldCrash || response == PageFaultResponse::OutOfMemory) {
+    if (response == PageFaultResponse::ShouldCrash || response == PageFaultResponse::OutOfMemory || response == PageFaultResponse::BusError) {
         if (faulted_in_kernel && handle_safe_access_fault(regs, fault_address)) {
             // If this would be a ring0 (kernel) fault and the fault was triggered by
             // safe_memcpy, safe_strnlen, or safe_memset then we resume execution at
```
Comment (IdanHo) [inline Kernel/Arch/x86/common/Interrupts.cpp:323]: lines 329/330 need to be updated for the BusError case (looks like that got lost in the updates?)

File: Kernel/Arch/x86/common/Interrupts.cpp [hunk 4]
```diff
@@ -341,7 +341,9 @@ void page_fault_handler(TrapFrame* trap)
         constexpr FlatPtr free_scrub_pattern = explode_byte(FREE_SCRUB_BYTE);
         constexpr FlatPtr kmalloc_scrub_pattern = explode_byte(KMALLOC_SCRUB_BYTE);
         constexpr FlatPtr kfree_scrub_pattern = explode_byte(KFREE_SCRUB_BYTE);
-        if ((fault_address & 0xffff0000) == (malloc_scrub_pattern & 0xffff0000)) {
+        if (response == PageFaultResponse::BusError) {
+            dbgln("Note: Address {} is an access to undefined memory range of a Inode-backed VMObject", VirtualAddress(fault_address));
```
Comment (IdanHo) [inline Kernel/Arch/x86/common/Interrupts.cpp:345]:
```suggestion
            dbgln("Note: Address {} is an access to an undefined memory range of an Inode-backed VMObject", VirtualAddress(fault_address));
```
