### PR TITLE
Browser: Scope bookmark actions so that they don't block the delete key 

### LINKED ISSUE #10940: Browser (LibGUI?): Can't press delete in address bar
Steps to reproduce:

1. Open Browser
2. Click twice in the middle of the address bar so that nothing is selected
3. Press [Delete] and notice that nothing happens
4. Select some of the text and press [Delete], still nothing happens

[Backspace] works fine, as does [Ctrl+Delete].

[Delete] works fine in the Terminal, TextEditor and HackStudio. 

I imagine this is related to the changes in #10880 but I have not yet confirmed this.

### PR DESCRIPTION
**Pull request by AtkinsSJ**
This fixes #10940.

Previously, all presses of the Delete key without a modifier in Browser
were uselessly consumed by the "Delete" action in the bookmark context
menu.

### CODE REVIEW

File: Userland/Applications/Browser/BookmarksBarWidget.cpp [hunk 1]
```diff
@@ -140,7 +140,8 @@ BookmarksBarWidget::BookmarksBarWidget(const String& bookmarks_file, bool enable
     }));
     m_context_menu->add_action(GUI::CommonActions::make_delete_action([this](auto&) {
         remove_bookmark(m_context_menu_url);
-    }));
+    },
+        nullptr, true));
```
Comment (AtkinsSJ) [inline Userland/Applications/Browser/BookmarksBarWidget.cpp:144]: This alignment is :acid2: but that's how Clang-format likes it apparently!

Comment (alimpfard) [reply Userland/Applications/Browser/BookmarksBarWidget.cpp:144]: You can move the first lambda to a new line, the formatting will be much nicer with that.

Comment (AtkinsSJ) [reply Userland/Applications/Browser/BookmarksBarWidget.cpp]: :+1: Thanks, it's a little better!

**Comment by AtkinsSJ** [comment]
Now featuring an actual solution instead of a nasty hack! :^)
