### PR TITLE
LibWeb: Unbreak `help://` and launch links in the Help app (v2)

### LINKED ISSUE #25288: Help: Clicking "See also" links doesn't work
It hits the `dbgln("(FIXME) Don't know how to navigate to {}", params.url);` in Userland/Libraries/LibWeb/HTML/Navigable.cpp.

That particular line hasn't changed in a while. Maybe it's an old regression, or a caller of it changed recently.

### PR DESCRIPTION
**Pull request by MacDue**
See commits for details. 

This is an alternative solution to #25288 (rather than #25662). This instead fleshes out the "attempt to create a non-fetch scheme document" steps a little, and adds a new hook to allow web view clients to handle custom URL schemes. 

Using this we can fix `help://` URLs (and launch links) in the Help app, along with `spreadsheet://` URLs (in Spreadsheet).

Note: URL schemes that LibWeb knows about are a bit wonky (e.g. normal `http://` or `file://`) as it attempts to handle them itself without informing the client. So in help man pages, `file://` URLs have been replaced with `launch://`, which is a custom scheme the Help app can handle.   

Fixes #25288 
Closes #25662

### CODE REVIEW

File: Userland/Libraries/LibWeb/HTML/Navigable.cpp [hunk 1]
```diff
@@ -1143,13 +1143,12 @@ WebIDL::ExceptionOr<void> Navigable::populate_session_history_entry_document(
             // 2. Set saveExtraDocumentState to false.
             saveExtraDocumentState = false;
         }
-
```
Comment (nico) [inline Userland/Libraries/LibWeb/HTML/Navigable.cpp:1146]: ?

**Review by nico — APPROVED** [review]
Looks great, thanks!

I'll let this sit for a day or so in case @trflynn89 has thoughts on this approach. But I think this is nice :)

File: Userland/Libraries/LibWeb/HTML/Navigable.cpp (hunk 1 above)
Comment (MacDue) [reply Userland/Libraries/LibWeb/HTML/Navigable.cpp:1146]: The other "otherwise" `else if` blocks did not have a newline between them, so this is just for consistency
