### PR TITLE
SystemMonitor: Fix incorrect disk size for disks > 4GiB

### LINKED ISSUE #7288: SystemMonitor: Support large file systems
Right now SystemMonitor shows "0 B" for my 64GB test volume:

![Screenshot from 2021-05-19 21-21-48](https://user-images.githubusercontent.com/388571/118871856-42f1d300-b8e8-11eb-8a94-1a37da69edd0.png

### PR DESCRIPTION
**Pull request by Quaker762**
Fixes #7288.

This was being caused by the `LibGUI::Variant` returning a `u32`, which was overflowed when the disk volume was larger than 4GiB in size.

### CODE REVIEW

File: Userland/Libraries/LibGUI/Variant.h [hunk 1]
```diff
@@ -118,10 +123,16 @@ class Variant {
...
-    unsigned as_uint() const
+    unsigned as_u32() const
     {
-        VERIFY(type() == Type::UnsignedInt);
-        return m_value.as_uint;
+        VERIFY(type() == Type::UnsignedInt32);
+        return m_value.as_u32;
+    }
+
+    unsigned as_u64() const
```
Comment (linusg) [inline Userland/Libraries/LibGUI/Variant.h:132]: unsigned for both u32 and u64... This doesn't seem right?

File: Userland/Libraries/LibGUI/Variant.h [hunk 2]
```diff
@@ -256,7 +271,8 @@ class Variant {
         bool as_bool;
         i32 as_i32;
         i64 as_i64;
-        unsigned as_uint;
+        unsigned as_u32;
```
Comment (linusg) [inline Userland/Libraries/LibGUI/Variant.h:274]: Let's use u32 here for consistency

File: Userland/Libraries/LibGUI/Variant.h (hunk 1 above)
Comment (Quaker762) [reply Userland/Libraries/LibGUI/Variant.h:132]: Whoops, must've missed that one....

File: Userland/Libraries/LibGUI/Variant.h [hunk 3]
```diff
@@ -135,9 +146,13 @@ class Variant {
...
-        if (is_uint()) {
-            VERIFY(as_uint() <= INT32_MAX);
-            return (int)as_uint();
+        if (is_u32()) {
+            VERIFY(as_u32() <= INT32_MAX);
+            return (int)as_u32();
+        }
+        if (is_u64()) {
+            VERIFY(as_u64() <= INT64_MAX);
+            return (int)as_u32();
```
Comment (gunnarbeutner) [inline Userland/Libraries/LibGUI/Variant.h:155]:
```suggestion
            return (int)as_u64();
```

File: Userland/Libraries/LibGUI/Variant.h [hunk 4]
```diff
@@ -135,9 +146,13 @@ class Variant {
             return as_bool() ? 1 : 0;
         if (is_float())
             return (int)as_float();
-        if (is_uint()) {
-            VERIFY(as_uint() <= INT32_MAX);
-            return (int)as_uint();
+        if (is_u32()) {
+            VERIFY(as_u32() <= INT32_MAX);
+            return (int)as_u32();
```
Comment (gunnarbeutner) [inline Userland/Libraries/LibGUI/Variant.h:151]:
```suggestion
            return (T)as_u32();
```

File: Userland/Libraries/LibGUI/Variant.h [hunk 5]
```diff
@@ -135,9 +146,13 @@ class Variant {
             return as_bool() ? 1 : 0;
         if (is_float())
             return (int)as_float();
```
Comment (gunnarbeutner) [inline Userland/Libraries/LibGUI/Variant.h:148]:
```suggestion
            return (T)as_float();
```

**Comment by gunnarbeutner** [comment]
Copied from Discord (thanks to laziness):

```
[5:12 PM] shroud: to_integer seems like a weird method name for something that returns a signed int. Technically even an unsigned int is an integer.
[5:12 PM] shroud: But that's obviously not your fault. :P
[5:13 PM] Quaker: Hrrm now that I think about it yeah it does. I think back in the day it was appropriate for our use case
[5:14 PM] Quaker: Might get that one in another PR. I'm off to bed now but we can discuss tomorrow if you'd like
[5:14 PM] Quaker: Might be good to comb through this file
```

Not necessarily relevant for _this_ PR.

File: Userland/Libraries/LibGUI/Variant.h [hunk 6]
```diff
@@ -135,9 +146,13 @@ class Variant {
...
-        if (is_uint()) {
-            VERIFY(as_uint() <= INT32_MAX);
-            return (int)as_uint();
+        if (is_u32()) {
+            VERIFY(as_u32() <= INT32_MAX);
+            return (i32)as_u32();
+        }
+        if (is_u64()) {
+            VERIFY(as_u64() <= INT64_MAX);
+            return (i64)as_u32();
```
Comment (linusg) [inline Userland/Libraries/LibGUI/Variant.h:155]:
```suggestion
            return (i64)as_u64();
```

**Review by linusg — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibGUI/Variant.h (hunk 6 above)
Comment (Quaker762) [reply Userland/Libraries/LibGUI/Variant.h:155]: Okay, I just double checked the diff and this seems like the last typo :sweat_smile:

**Review by gunnarbeutner — APPROVED** [review]
