### PR TITLE
LibWeb: Let Document have a direct GCPtr to its containing Web::Page

### LINKED ISSUE #22290: LibWeb: Creating the initial current request for HTMLImageElement assumes the document's page exists
https://github.com/SerenityOS/serenity/blob/b61e4e7cd9a8f3ecdf495c80ca5b8e645f4bf1e9/Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp#L60
This assumes the document's page exists, but it can be null, for example with the temporary document of innerHTML:
```
VERIFICATION FAILED: document().page() at /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp:60
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/bin/WebContent(__interceptor_backtrace+0x5b) [0x5563d7de3d0b]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-core.so.0(ak_verification_failed+0x47b) [0x7f0626e618bb]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLImageElement::initialize(JS::Realm&) 0x7a2) [0x7f06384d3052]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0(+0x88ed529) [0x7f06378ed529]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0(+0x88c89dc) [0x7f06378c89dc]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::DOM::create_element(Web::DOM::Document&, AK::FlyString, AK::Optional<AK::FlyString>, AK::Optional<AK::FlyString>, AK::Optional<AK::String>, bool) 0x324a) [0x7f06378bfc2a]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::create_element_for(Web::HTML::HTMLToken const&, AK::Optional<AK::FlyString> const&, Web::DOM::Node&) 0x1bd9) [0x7f0638a2c3f9]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::insert_foreign_element(Web::HTML::HTMLToken const&, AK::Optional<AK::FlyString> const&) 0x572) [0x7f0638a31a62]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::insert_html_element(Web::HTML::HTMLToken const&) 0x355) [0x7f0638a33355]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::handle_in_body(Web::HTML::HTMLToken&) 0x1a134) [0x7f06389f7484]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::process_using_the_rules_for(Web::HTML::HTMLParser::InsertionMode, Web::HTML::HTMLToken&) 0x624) [0x7f06389bff24]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run() 0x1009) [0x7f06389bea69]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(AK::URL const&) 0x7e6) [0x7f06389c9b16]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::HTML::HTMLParser::parse_html_fragment(Web::DOM::Element&, AK::StringView) 0x468d) [0x7f0638a7d93d]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::DOMParsing::parse_fragment(AK::StringView, Web::DOM::Element&) 0x554) [0x7f0637bf2db4]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::DOMParsing::inner_html_setter(JS::NonnullGCPtr<Web::DOM::Node>, AK::StringView) 0xc95) [0x7f0637bf4ce5]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::DOM::Element::set_inner_html(AK::StringView) 0x3a6) [0x7f06377c55f6]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0(+0xbb3341b) [0x7f063ab3341b]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0(+0xbaf8337) [0x7f063aaf8337]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Bindings::ElementPrototype::inner_html_setter(JS::VM&) 0x10e0) [0x7f063aa85700
```
Example: https://serenityos.social/public/local

### PR DESCRIPTION
**Pull request by awesomekling**
With this change, `Document` now always has a Web::Page. This means we no
longer rely on the breakable link between `Document` and `BrowsingContext`
to find a relevant `Web::Page`.
    
Fixes #22290

### CODE REVIEW

File: Userland/Libraries/LibWeb/CSS/StyleComputer.cpp [hunk 1]
```diff
@@ -2335,10 +2335,8 @@ NonnullOwnPtr<StyleComputer::RuleCache> StyleComputer::make_rule_cache_for_casca
 void StyleComputer::build_rule_cache()
 {
     // FIXME: How are we sometimes calculating style before the Document has a Page?
```
Comment (Lubrsi) [inline Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:2337]: Looks like this FIXME can be removed?

**Review by Lubrsi — COMMENTED** [review]
Very nice :catdog:

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 2]
```diff
@@ -321,6 +322,7 @@ JS::NonnullGCPtr<Document> Document::create(JS::Realm& realm, AK::URL const& url
 
 Document::Document(JS::Realm& realm, const AK::URL& url)
     : ParentNode(realm, *this, NodeType::DOCUMENT_NODE)
+    , m_page(static_cast<Web::Bindings::HostDefined&>(*realm.host_defined()).page)
```
Comment (ADKaster) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:325]: we have helpers for the other members of host_defined() like `Bindings::host_defined_environment_settings_object` and `Bindings::host_defined_intrinsics`. can we add one for `host_defined_page` ?
