### PR TITLE
TreeView: Don't try to move cursor with invalid index

### LINKED ISSUE #7740: Profiler/LibGUI: Crash while navigating tree view
Steps to reproduce:

1. Record a system-wide profile.
2. Open the profile in Profiler.
3. Click on one of the processes in the list at the bottom.
4. Select one of the processes in the timeline view on the top.
5. Focus the treeview at the bottom by clicking on it (not on the process though).
6. Hit the cursor up key.

```
ASSERTION FAILED: i < m_size
../.././AK/Vector.h:183

0x5be1b1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
0x13f16135: [libc.so] raise +0x25 (signal.cpp:21)
0x13eff2a6: [libc.so] abort +0x2a (stdlib.cpp:233)
0x13effe0b: [libc.so] __assertion_failed +0xeb (Format.h:236)
0x3b3b199f: [/bin/Profiler] Profiler::ProfileModel::index(int, int, GUI::ModelIndex const&) const [clone .localalias] +0xff (Vector.h:183)
0xb985aa6d: [libgui.so] GUI::TreeView::move_cursor(GUI::AbstractView::CursorMovement, GUI::AbstractView::SelectionUpdate)::{lambda(GUI::ModelIndex)#2}::operator()(GUI::ModelIndex) const +0xfd (TreeView.cpp:512)
0xb985d9d3: [libgui.so] .L1831 +0x23 (ModelIndex.h:22)
0xb973e63e: [libgui.so] .L1246 +0x2e (AbstractView.cpp:524)
0xb973a200: [libgui.so] GUI::AbstractTableView::keydown_event(GUI::KeyEvent&) [clone .localalias] +0x40 (AbstractTableView.cpp:419)
0xb985e6cd: [libgui.so] GUI::TreeView::keydown_event(GUI::KeyEvent&) [clone .localalias] +0xad (TreeView.cpp:476)
0xb986ac3f: [libgui.so] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) [clone .localalias] +0x2f (Widget.cpp:267)
0x93801bce: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
0xb987b8bd: [libgui.so] GUI::Window::handle_key_event(GUI::KeyEvent&) +0xcd (Window.cpp:429)
0xb988484a: [libgui.so] GUI::Window::event(Core::Event&) +0xfa (Window.cpp:550)
0x93801bce: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
0x937e8693: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x4f3 (Atomic.h:246)
0x937e8e7b: [libcore.so] Core::EventLoop::exec() +0x5b (EventLoop.cpp:362)
0xb974bf08: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:106)
0x3b39a904: [/bin/Profiler] main +0x2414 (NonnullRefPtr.h:276)
0x3b39acd8: [/bin/Profiler] _start +0x58 (crt0.cpp:39)
```

### PR DESCRIPTION
**Pull request by metmo**
When clicking on the TreeView in profiler without selecting a node and then pressing up or pgup, cursor_index was in an invalid state.

Fixes #7740

### CODE REVIEW

**Comment by GMTA** [comment]
When the TreeView is in focus, wouldn't we want some cursor movements to actually result in an action? E.g. pressing the down key when the widget is focused (but no selection is active) results in the first or second item being selected.

**Comment by awesomekling** [comment]
> When the TreeView is in focus, wouldn't we want some cursor movements to actually result in a selection? E.g. pressing the down key when the widget is focused (but no selection is active) results in the first or second item being selected. We could achieve this by checking if `cursor_index().is_valid()` and if it's not, default to the first index.

Yes, we definitely want this. 👍🏻

File: Userland/Libraries/LibGUI/TreeView.cpp [hunk 1]
```diff
@@ -480,6 +480,11 @@ void TreeView::move_cursor(CursorMovement movement, SelectionUpdate selection_up
 {
     auto& model = *this->model();
 
+    if (!cursor_index().is_valid()) {
+        set_cursor(model.index(0, model.tree_column(), cursor_index()), SelectionUpdate::Set);
+        return;
+    }
```
Comment (metmo) [inline Userland/Libraries/LibGUI/TreeView.cpp:486]: This worked nicely, the return might seem excessive but it felt more natural. Now the first keypress selects the first row.

Comment (GMTA) [reply Userland/Libraries/LibGUI/TreeView.cpp:486]: This is already an improvement! If you press `[end]` you will still end up with the first item selected. If you'd also like to solve that, you would need to replace occurrences of `cursor_index()` in this method with a variable that you define here.

Comment (metmo) [reply Userland/Libraries/LibGUI/TreeView.cpp]: In that case, let's remove the return statement and let it act on the first keypress :)
