### PR TITLE
Kernel: Dont try to register ephemeral TCP ports twice

### LINKED ISSUE #7620: Network: Trying to listen on an ephemeral port fails
This is for TCPSockets, not sure if the same applies to UDPSockets.
`listen` calls `allocate_local_port_if_needed`
`allocate_local_port_if_needed` calls `protocol_allocate_local_port`
`protocol_allocate_local_port` finds a free port, and adds it to `sockets_by_tuple()`, and returns with the new port number
`allocate_local_port_if_needed` stores this free port on the socket and returns
`listen` then returns the value from `protocol_listen`
`protocol_listen` checks if that socket is in use by looking at `sockets_by_tuple()`
Since it was added earlier in the callstack, its there, and `protocol_listen` then returns with `EADDRINUSE`

### PR DESCRIPTION
**Pull request by stelar7**
TCPSocket::listen with an ephemeral port would register the socket when finding a free port, then try to register the socket again to ensure its free. This will fail, as it has just been registered.

This PR introduces `PortAllocationResult`, it returns information about if the port was just allocated.

Fixes #7620

### CODE REVIEW

File: Kernel/Net/IPv4Socket.h [hunk 1]
```diff
@@ -21,6 +22,8 @@ class NetworkAdapter;
 class TCPPacket;
 class TCPSocket;
 
+using PortAllocationResult = Tuple<KResultOr<u16>, bool>;
```
Comment (alimpfard) [inline Kernel/Net/IPv4Socket.h:25]: Can we please not use `Tuple` in normal code?
It makes reading the code much harder than it would otherwise be.

Comment (alimpfard) [reply Kernel/Net/IPv4Socket.h:25]: I originally added `Tuple` to help with metaprogramming tasks, and I remain of the opinion that it shouldn't be used in non-generic code, and definitely not as part of the API of something.

Comment (stelar7) [reply Kernel/Net/IPv4Socket.h:25]: Do you have an alternative to it? Or should I use a struct?

Comment (alimpfard) [reply Kernel/Net/IPv4Socket.h:25]: A struct is the best alternative, I think.

Comment (stelar7) [reply Kernel/Net/IPv4Socket.h]: Adjusted with https://github.com/SerenityOS/serenity/pull/7650/commits/005176e4328438256179690c191c15d16bd9ebcc
