### PR TITLE
Ports: Exclude non-working utilities from the coreutils installation

### LINKED ISSUE #13690: Ports: Some utilities don't work in the GNU core utilities package
After #13333 was merged, I tested the package and found that some utilities are not working.
The ones are (for now) `df`, `who` and `users`. For `who` and `users` it seems like we don't have `/etc/utmp` file. `df` is obviously expecting a procfs node in a certain format (i.e. not JSON-formatted output). So it might be that some utils will never function correctly on SerenityOS from the GNU core utils package.

cc @timschumi

### PR DESCRIPTION
**Pull request by timschumi**
I didn't intend for coreutils to actually be used productively, but if someone does, now they will at least not find any utilities that are immediately obvious to be broken.

Fixes #13690.

### CODE REVIEW

File: Ports/coreutils/package.sh [hunk 1]
```diff
@@ -9,3 +9,11 @@ https://ftpmirror.gnu.org/gnu/coreutils/coreutils-${version}.tar.gz.sig coreutil
 https://ftpmirror.gnu.org/gnu/gnu-keyring.gpg gnu-keyring.gpg"
 auth_type="sig"
 auth_opts=("--keyring" "./gnu-keyring.gpg" "coreutils-${version}.tar.gz.sig")
+
+# Exclude some non-working utilities:
+#  - arch, coreutils, and hostname are the default setting
```
Comment (linusg) [inline Ports/coreutils/package.sh:14]: Not sure what that means, could you elaborate?

Comment (timschumi) [reply Ports/coreutils/package.sh:14]: coreutils excludes the commands `arch`, `coreutils`, and `hostname` by default when using the default configuration.
