### PR TITLE
Utilities: Allow filenames containing '=' in dd

### LINKED ISSUE #8746: Utilities: dd fails to write files with = in their name
```
$ dd if=/dev/zero of=b=a
Unable to parse of=b=a
```

Instead of the error message I would expect `dd` to create an output file with the name `b=a`.

### PR DESCRIPTION
**Pull request by DMaroo**
Now, `dd` just takes the whole substring after <kbd>=</kbd>, and uses it as the filename,

Fixes #8746.

### CODE REVIEW

File: Userland/Utilities/dd.cpp [hunk 1]
```diff
@@ -40,11 +40,11 @@ static String split_at_equals(const char* argument)
     String string_value(argument);
 
     auto values = string_value.split('=');
```
Comment (alimpfard) [inline Userland/Utilities/dd.cpp:42]: You can use `string_value.split_limit('=', 1);` to get at most one split :)

Comment (DMaroo) [reply Userland/Utilities/dd.cpp]: Thanks! This looks much simpler and comprehensible. I have made the changes.

**Comment by alimpfard** [comment]
Please squash the fixup commit into the commit that fixes it, and we're good to go :)
