### PR TITLE
HackStudio: Fix update modified document on tab widget

### LINKED ISSUE #14297: HackStudio: Each tab's "modified" status only updates when it is switched to
To reproduce:

1. Open HackStudio
2. Double click to open README.md inside it
3. Use `View > Add New Editor` from the menu
4. Open a different file in the second editor
5. Type in that file. Notice that the window title gets the `(*)` but the tab doesn't.
6. Switch to the other tab. Modify that. Same thing.
7. Switch back to the second tab. Now the tab title *does* update.

The tab "modified" status should update as soon as its file becomes modified, or unmodified (by saving it), instead of only when switching to it.

### PR DESCRIPTION
**Pull request by guerinoni**
Closes #14297

### CODE REVIEW

**Comment by guerinoni** [comment]
I invoke @itamar8910 :)

File: Userland/DevTools/HackStudio/main.cpp [hunk 1]
```diff
@@ -185,6 +185,11 @@ void set_current_editor_wrapper(RefPtr<EditorWrapper> wrapper)
     s_hack_studio_widget->set_current_editor_wrapper(wrapper);
 }
 
+void show_file_title_modified()
+{
+    s_hack_studio_widget->update_file_title_after_modified();
```
Comment (itamar8910) [inline Userland/DevTools/HackStudio/main.cpp:190]: Let's just call `update_current_editor_title()` and `update_window_title()`, I don't see a need for a wrapper function

File: Userland/DevTools/HackStudio/main.cpp [hunk 2]
```diff
@@ -185,6 +185,11 @@ void set_current_editor_wrapper(RefPtr<EditorWrapper> wrapper)
     s_hack_studio_widget->set_current_editor_wrapper(wrapper);
 }
 
+void show_file_title_modified()
```
Comment (itamar8910) [inline Userland/DevTools/HackStudio/main.cpp:188]: Can you choose a better name? This name makes it seem like this function also sets the 'modified state'

**Review by itamar8910 — APPROVED** [review]
