### PR TITLE
Kernel+LibCore: Fixes to file type attribute handling

### LINKED ISSUE #22533: Shell: `cd` tab completion does not work in /sys
To reproduce:

1. `cd /sys`
2. `cd <tab>` or `cd k<tab>`

Nothing happens :^(

### PR DESCRIPTION
**Pull request by implicitfield**
Currently, we treat extended Ext2 attributes as if they are always available, which may not be the case for all Ext2 filesystems, such as those generated by `genext2fs`. With this PR, we avoid exposing extended attributes when the filesystem doesn't explicitly claim to support them.

`DirIterator::advance_next()` was also missing checks for valid file type attributes, so that has also been addressed.

Fixes #22533, though we should still store/expose file type attributes when possible for other filesystems.

cc @alimpfard

### CODE REVIEW

File: Userland/Libraries/LibCore/DirIterator.cpp [hunk 1]
```diff
@@ -60,6 +61,13 @@ bool DirIterator::advance_next()
         m_next = DirectoryEntry::from_stat(m_dir, *de);
 #else
         m_next = DirectoryEntry::from_dirent(*de);
+
+        // dirent structures from readdir aren't guaranteed to contain valid file types,
+        // as it is possible that the underlying filesystem doesn't keep track of those.
+        if (m_next->type == DirectoryEntry::Type::Unknown) {
+            auto stat = MUST(Core::System::fstat(dirfd(m_dir)));
+            m_next->type = DirectoryEntry::directory_entry_type_from_stat(stat.st_mode);
```
Comment (alimpfard) [inline Userland/Libraries/LibCore/DirIterator.cpp:69]: :thinking: is this really a sane assumption to make? why should the child's type be the same as the parent's type?
or am I reading this wrong?
