### PR TITLE
LibSQL: Parse INSERT statement without column names and check data types of input tuples (and a small `sql` fix)

### LINKED ISSUE #10028: SQLServer: crash on insertion into a newly-created table
Screenshot from 2021-09-14 13-15-09

Serial console log:

```
SQLServer(34:34): ASSERTION FAILED: i < m_size
../.././AK/Vector.h:141
[#0 SQLServer(34:34)]: Terminating SQLServer(34) due to signal 6
[#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x572
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x40e
0xdeadc0de  Kernel::Scheduler::pick_next() [clone .localalias] + 0x137
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x214
0xdeadc0de  Kernel::Thread::die_if_needed() [clone .localalias] + 0x1bb
0xdeadc0de  syscall_handler + 0x2372
0xdeadc0de  syscall_asm_entry + 0x31
0xb6eadde0  libc.so: .text + 0x17de0
0xb6e9777a  libc.so: .text + 0x177a
0xb6e982c9  libc.so: .text + 0x22c9
0x75223e52  libsql.so: .text + 0x4e52
0x27ab7539  /bin/SQLServer: .text + 0xd539
0xb300d195  libcore.so: .text + 0x33195
0xb2ff28f9  libcore.so: .text + 0x188f9
0xb2ff2dbe  libcore.so: .text + 0x18dbe
0x27aaa6f1  /bin/SQLServer: .text + 0x6f1
0x27aaa8c6  /bin/SQLServer: .text + 0x8c6

[#0 FinalizerTask(4:4)]: Generating coredump for pid: 34
CrashDaemon(22:22): New coredump file: /tmp/coredump/SQLServer_34_1631618084
SystemServer(6:6): Service SQLServer has exited with exit code 6
CrashDaemon(22:22): --- Backtrace for thread #0 (TID 34) ---
CrashDaemon(22:22): 0x20f5d02e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashDaemon(22:22): 0xb6eadddf: [libc.so] raise +0x2f (syscall.h:35 => signal.cpp:21)
CrashDaemon(22:22): 0xb6e97779: [libc.so] abort +0x29 (stdlib.cpp:230)
CrashDaemon(22:22): 0xb6e982c8: [libc.so] __assertion_failed +0xc8 (assert.cpp:31)
CrashDaemon(22:22): 0x75223e51: [libsql.so] SQL::AST::Insert::execute(SQL::AST::ExecutionContext&) const [clone .localalias] +0x641 (Vector.h:141)
CrashDaemon(22:22): 0x27ab7538: [/bin/SQLServer] SQLServer::SQLStatement::execute()::{lambda()#1}::operator()() const +0x988 (SQLStatement.cpp:71)
CrashDaemon(22:22): 0xb300d194: [libcore.so] AK::Function<void ()>::CallableWrapper<Core::Object::deferred_invoke(AK::Function<void ()>)::{lambda()#1}>::call() +0x284 (Function.h:91)
CrashDaemon(22:22): 0xb2ff28f8: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x598 (Function.h:91)
CrashDaemon(22:22): 0xb2ff2dbd: [libcore.so] Core::EventLoop::exec() +0x5d (EventLoop.cpp:364)
CrashDaemon(22:22): 0x27aaa6f0: [/bin/SQLServer] main +0x190 (main.cpp:51)
CrashDaemon(22:22): 0x27aaa8c5: [/bin/SQLServer] _entry +0x65 (crt0.cpp:45)
```

### PR DESCRIPTION
**Pull request by i3abghany**
This adds the ability to parse SQL INSERT statements in the following
form:

    INSERT INTO schema.tablename VALUES (column1, column2, ...),
                                        (column1, column2, ...), ...

Implements tests for the implemented statement.

Fixes a small syntax-highlighting issue in the `sql` utility.

Resolves #10028

### CODE REVIEW

**Comment by i3abghany** [comment]
Recently pushed:

Checked data types of the input tuples, and only insert rows if and only if all inserted row data is correct.

**Comment by i3abghany** [comment]
Added some tests for the newly-implemented things :-)

File: Tests/LibSQL/TestSqlStatementExecution.cpp [hunk 1]
```diff
@@ -82,18 +84,52 @@ TEST_CASE(insert_into_table)
...
+
+TEST_CASE(insert_wrong_number_of_values)
+{
+    ScopeGuard guard([]() { unlink(db_name); });
+    auto database = SQL::Database::construct(db_name);
+    create_table(database);
+    auto result = execute(database, "INSERT INTO TestSchema.TestTable VALUES ( 42 );");
+    EXPECT(result->error().code == SQL::SQLErrorCode::InvalidNumberOfValues);
+    EXPECT(result->inserted() == 0);
+}
```
Comment (davidot) [inline Tests/LibSQL/TestSqlStatementExecution.cpp:115]: Great you added some failing tests.
But is this not missing a passing test? Perhaps I'm misunderstanding your PR but something like:
`INSERT INTO TestSchema.TestTable VALUES ( 'Test_1', 42 );`

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 2]
```diff
@@ -11,6 +12,19 @@
 
 namespace SQL::AST {
 
+static bool does_value_data_type_match(const SQLType expected, const SQLType actual)
+{
+    if (actual == SQLType::Null) {
+        return false;
+    }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:19]:
```suggestion
    if (actual == SQLType::Null)
        return false;
```

The style in SerenityOS is to not add braces for single line statements.
Although I would like to point to https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md it is actually not mentioned there (perhaps it should?).

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 3]
```diff
@@ -11,6 +12,19 @@
...
+
+    if (expected == SQLType::Integer) {
+        return actual == SQLType::Integer || actual == SQLType::Float;
+    }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:23]: Again no braces.

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 4]
```diff
@@ -37,12 +53,43 @@ RefPtr<SQLResult> Insert::execute(ExecutionContext& context) const
...
+                row[ix] = values[ix];
+            }
         }
-        context.database->insert(row);
+        inserted_rows.append(row);
+    }
+
+    for (auto& inserted_row : inserted_rows) {
+        context.database->insert(inserted_row);
     }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:91]: Also here remove the braces
```suggestion
    for (auto& inserted_row : inserted_rows)
        context.database->insert(inserted_row);
```

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 5]
```diff
@@ -37,12 +53,43 @@ RefPtr<SQLResult> Insert::execute(ExecutionContext& context) const
...
+                if (!does_value_data_type_match(element_type, input_value_type)) {
+                    return SQLResult::construct(SQLCommand::Insert, SQLErrorCode::InvalidValueType, table_def->columns()[element_index].name());
+                }
+
+                row[element_index] = values[ix];
+            }
+        } else {
+            if (values.size() != row.size()) {
+                return SQLResult::construct(SQLCommand::Insert, SQLErrorCode::InvalidNumberOfValues, "");
+            }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:76]: Same as above (braces)

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 6]
```diff
@@ -37,12 +53,43 @@ RefPtr<SQLResult> Insert::execute(ExecutionContext& context) const
...
+                auto input_value_type = values[ix].type();
+
+                auto& tuple_descriptor = *row.descriptor();
+                // This must succeed since we checked for every column name for existence in the table.
+                auto element_index = tuple_descriptor.find_if([&](auto element) { return element.name == column_name; }).index();
+                auto element_type = (*row.descriptor())[element_index].type;
+
+                if (!does_value_data_type_match(element_type, input_value_type)) {
+                    return SQLResult::construct(SQLCommand::Insert, SQLErrorCode::InvalidValueType, table_def->columns()[element_index].name());
+                }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:69]: Same as above (braces)

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 7]
```diff
@@ -37,12 +53,43 @@ RefPtr<SQLResult> Insert::execute(ExecutionContext& context) const
...
+        } else {
+            if (values.size() != row.size()) {
+                return SQLResult::construct(SQLCommand::Insert, SQLErrorCode::InvalidNumberOfValues, "");
+            }
+            for (auto ix = 0u; ix < values.size(); ix++) {
+                auto element_type = (*row.descriptor())[ix].type;
+                auto input_value_type = values[ix].type();
+                if (!does_value_data_type_match(element_type, input_value_type)) {
+                    return SQLResult::construct(SQLCommand::Insert, SQLErrorCode::InvalidValueType, table_def->columns()[ix].name());
+                }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:82]: Same as above (braces)

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 8]
```diff
@@ -37,12 +53,43 @@ RefPtr<SQLResult> Insert::execute(ExecutionContext& context) const
...
+                row[ix] = values[ix];
+            }
         }
-        context.database->insert(row);
+        inserted_rows.append(row);
+    }
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:87]: Both sides of this if statement contain quite a bit of duplicated logic. 
Would it be possible to merge parts of this?
Note: this is not necessary two copies directly underneath each other are fine, just something to think about to simplify the reading of this code.

File: Userland/Libraries/LibSQL/AST/Insert.cpp [hunk 9]
```diff
@@ -11,6 +12,19 @@
 
 namespace SQL::AST {
 
+static bool does_value_data_type_match(const SQLType expected, const SQLType actual)
```
Comment (davidot) [inline Userland/Libraries/LibSQL/AST/Insert.cpp:15]: Is there any need for these types to be const here? Since you are taking them by value it does not really matter so just remove `const`. Alternatively you can take by const reference if the objects are large.

**IF** you keep them:
Please use east const see https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md.

```suggestion
static bool does_value_data_type_match(SQLType const expected, SQLType const actual)
```

**Review by davidot — COMMENTED** [review]
I mostly found some style issues.
And maybe add a passing test?

File: Userland/Libraries/LibSQL/AST/Insert.cpp (hunk 2 above)
Comment (davidot) [reply Userland/Libraries/LibSQL/AST/Insert.cpp:19]: Apparently this is not as strict as I thought you can leave them as long as the code is consistent (so the whole file either does or doesn't)

**Comment by davidot** [comment]
Feel free to ignore the braces comments, the file is already in that style so matching it is fine.
If you change them please also change all the other occurrences in the file.

Sorry for the confusion.

File: Userland/Libraries/LibSQL/AST/Insert.cpp (hunk 2 above)
Comment (i3abghany) [reply Userland/Libraries/LibSQL/AST/Insert.cpp:19]: @davidot Alright, I guess I'll leave my braces on since the original commit of the file had braces.

**Review by davidot — APPROVED** [review]

**Comment by i3abghany** [comment]
Re-pushed to reinforce CI restart, the already-reviewed code did not change.

File: Userland/Utilities/sql.cpp [hunk 10]
```diff
@@ -112,9 +112,8 @@ int main()
 
         bool indenters_starting_line = true;
         for (SQL::AST::Token token = lexer.next(); token.type() != SQL::AST::TokenType::Eof; token = lexer.next()) {
-            auto length = token.value().length();
             auto start = token.start_position().column - 1;
-            auto end = start + length;
+            auto end = token.end_position().column - 1;
```
Comment (JanDeVisser) [inline Userland/Utilities/sql.cpp:116]: lol thanks for this. I've been wanting to fix this for a while but too lazy haha

**Review by JanDeVisser — CHANGES_REQUESTED** [review]
Can you squash the three commits dealing with typechecking into a single one? And while you're at it, I believe the existing code path (``INSERT INTO foo ( bar, quux ) VALUES ...``) isn't checked yet. Can you fix that to?

**Review by JanDeVisser — COMMENTED** [review]
Good catch

**Comment by JanDeVisser** [comment]
Thanks for working on this. It's a big undertaking and the work ahead seems daunting at times. It's good to know there are other people interested as well.

If you do want to work on this more. we should maybe briefly discuss what you're interested in so we don't duplicate  work.

**Comment by i3abghany** [comment]
> Can you squash the three commits dealing with typechecking into a single one? And while you're at it, I believe the existing code path (`INSERT INTO foo ( bar, quux ) VALUES ...`) isn't checked yet. Can you fix that to?

OK, I will squash the type-checking commits.
Can you please elaborate some more on the example you gave? a statement of the following structure:
    INSERT INTO TableName (attr1, attr2) VALUES (X, Y), (Y, Z), ...;
works in the sense that it's parsed correctly and also data types are checked.

Have I missed your point?
Screenshot from 2021-09-24 19-20-01

**Comment by i3abghany** [comment]
> Thanks for working on this. It's a big undertaking and the work ahead seems daunting at times. It's good to know there are other people interested as well.
> 
> If you do want to work on this more. we should maybe briefly discuss what you're interested in so we don't duplicate work.

That would be great. Yes, I'm interested in working on LibSQL. If you're on discord, please drop your username! Mine is `NRG-500`

**Comment by JanDeVisser** [comment]
> Have I missed your point?

I don't think so. I just didn't properly parse your PR.

File: Tests/LibSQL/TestSqlStatementExecution.cpp [hunk 11]
```diff
@@ -114,6 +114,19 @@ TEST_CASE(insert_wrong_number_of_values)
     EXPECT(result->inserted() == 0);
```
Comment (trflynn89) [inline Tests/LibSQL/TestSqlStatementExecution.cpp:114]: (Commenting on the commit message here)
Commits should be written in an imperative mood, see: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
So instead of `LibSQL: Added an INSERT without column names test`, should be more like `LibSQL: Add a test for INSERT statements without column names`.

**Review by trflynn89 — COMMENTED** [review]
LGTM, just one comment on a commit message

File: Tests/LibSQL/TestSqlStatementExecution.cpp (hunk 11 above)
Comment (i3abghany) [reply Tests/LibSQL/TestSqlStatementExecution.cpp:114]: Thanks for the notice... fixed that!
