### PR TITLE
Kernel: Fix crash when opening GPU3DDevice without creating a context

### LINKED ISSUE #13105: Kernel: Detaching VirtIO GPU3DDevice leads to assertion failed
How to reproduce:
1. Run QEMU with the following parameters:
`SERENITY_GL=1 SERENITY_QEMU_DISPLAY_BACKEND=gtk,gl=on SERENITY_RUN= ninja setup-and-run`
2. do `cat /dev/gpu0`.

Crash dump:
```
[FinalizerTask(4:4)]: ASSERTION FAILED: old_ref_count > 0
[FinalizerTask(4:4)]: ././Kernel/Library/ThreadSafeRefCounted.h:29 in void AK::RefCountedBase::ref() const
[FinalizerTask(4:4)]: KERNEL PANIC! :^(
[FinalizerTask(4:4)]: Aborted
[FinalizerTask(4:4)]: at ./Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[FinalizerTask(4:4)]: Kernel + 0x00c93181  Kernel::__panic(char const*, unsigned int, char const*) +0xf1
[FinalizerTask(4:4)]: Kernel + 0x01036d69  abort.localalias +0x245
[FinalizerTask(4:4)]: Kernel + 0x01036b24  abort.localalias +0x0
[FinalizerTask(4:4)]: Kernel + 0x0065d306  Kernel::Graphics::VirtIOGPU::GPU3DDevice::detach(Kernel::OpenFileDescription&) [clone .localalias] +0xa16
[FinalizerTask(4:4)]: Kernel + 0x008f6e1a  Kernel::OpenFileDescription::~OpenFileDescription() [clone .localalias] +0xfa
[FinalizerTask(4:4)]: Kernel + 0x00cdec65  Kernel::Process::finalize() +0x2215
[FinalizerTask(4:4)]: Kernel + 0x00f91382  Kernel::Thread::finalize() [clone .localalias] +0x4d2
[FinalizerTask(4:4)]: Kernel + 0x00f9227f  Kernel::Thread::finalize_dying_threads() +0xa1f
[FinalizerTask(4:4)]: Kernel + 0x00f5c4a1  Kernel::finalizer_task(void*) +0x111
[FinalizerTask(4:4)]: Kernel + 0x0103f4e0  exit_kernel_thread +0x0
```
I saw this while I worked on #12181. One solution I tried was to take the detach call outside the destructor of the `OpenFileDescription` class, but it was not working correctly. Another solution is to not use an HashMap of key with `RefPtr` in the `GPU3DDevice` class.

cc @ccapitalK

### PR DESCRIPTION
**Pull request by ccapitalK**
Fixes #13105

### CODE REVIEW

**Review by supercomputer7 — APPROVED** [review]
Looks good to me :)

File: Kernel/Graphics/VirtIOGPU/GPU3DDevice.h [hunk 1]
```diff
@@ -127,7 +127,7 @@ class GPU3DDevice : public CharacterDevice {
     Kernel::Graphics::VirtIOGPU::GraphicsAdapter& m_graphics_adapter;
     // Context used for kernel operations (e.g. flushing resources to scanout)
     ContextID m_kernel_context_id;
-    HashMap<RefPtr<OpenFileDescription>, RefPtr<PerContextState>> m_context_state_lookup;
+    HashMap<OpenFileDescription *, RefPtr<PerContextState>> m_context_state_lookup;
```
Comment (supercomputer7) [inline Kernel/Graphics/VirtIOGPU/GPU3DDevice.h:130]: Please put the * sign near the pointed object type :)
We might want to find a better solution in general to this in the future but this is good enough for now.

Comment (ccapitalK) [reply Kernel/Graphics/VirtIOGPU/GPU3DDevice.h]: Fixed.
