### PR TITLE
DHCPClient: Don't crash if DHCP options contain no gateway

### LINKED ISSUE #13879: DHCPClient crashes with -netdev restrict option enabled
When running the qemu netdev with the `restrict=on` option, DHCPClient keeps crashing.

### Why do you need this?

I would like to make progress adding serenity support to a a system call fuzzer named syzkaller (https://github.com/SerenityOS/serenity/issues/1025). I have a POC, [but it requires a few hacks that aren't upstreamable](https://github.com/HerrSpace/syzkaller/commit/799fbf7fc9ce3c034e77cbd1a9b2fd98f05c8a50).

[Syzkaller launches the netdev qemu option with `restrict=on`](https://github.com/google/syzkaller/blob/master/vm/qemu/qemu.go#L422). This is to prevent the fuzzer from figuring out how to send packets to the internet. 

### Patch for testing:
```patch
diff --git a/Meta/run.sh b/Meta/run.sh
index 01de203542..8cf755a988 100755
--- a/Meta/run.sh
+++ b/Meta/run.sh
@@ -239,7 +239,7 @@ if [ "$SERENITY_ARCH" = "aarch64" ]; then
     SERENITY_NETFLAGS=
     SERENITY_NETFLAGS_WITH_DEFAULT_DEVICE=
 else
-    SERENITY_NETFLAGS="-netdev user,id=breh,hostfwd=tcp:${SERENITY_HOST_IP}:8888-10.0.2.15:8888,hostfwd=tcp:${SERENITY_HOST_IP}:8823-10.0.2.15:23,hostfwd=tcp:${SERENITY_HOST_IP}:8000-10.0.2.15:8000,hostfwd=tcp:${SERENITY_HOST_IP}:2222-10.0.2.15:22"
+    SERENITY_NETFLAGS="-netdev user,id=breh,restrict=on,hostfwd=tcp:${SERENITY_HOST_IP}:8888-10.0.2.15:8888,hostfwd=tcp:${SERENITY_HOST_IP}:8823-10.0.2.15:23,hostfwd=tcp:${SERENITY_HOST_IP}:8000-10.0.2.15:8000,hostfwd=tcp:${SERENITY_HOST_IP}:2222-10.0.2.15:22"
     SERENITY_NETFLAGS_WITH_DEFAULT_DEVICE="
     $SERENITY_NETFLAGS
     -device $SERENITY_ETHERNET_DEVICE_TYPE,netdev=breh
```

### Log Output
```
9.468 SystemServer(6:6): Service DHCPClient has exited with exit code 6
9.472 SystemServer(6:6): Third time's the charm?
9.777 DHCPClient(25:25): We were offered 10.0.2.15 for 2152792320
9.798 DHCPClient(25:25): Leasing the IP 10.0.2.15 for adapter ep0s8
9.808 DHCPClient(25:25): ASSERTION FAILED: i < m_size
././AK/Vector.h:149
9.812 [#0 DHCPClient(25:25)]: Terminating DHCPClient(25) due to signal 6
9.816 [#0 FinalizerTask(4:4)]: Backtrace:
0xc908697e  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x31e
0xc8daecb2  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x1f2
0xc8daf31e  Kernel::Scheduler::pick_next() [clone .localalias] + 0xfe
0xc90a8985  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x175
0xc8fd269d  Kernel::Thread::die_if_needed() [clone .localalias] + 0x32d
0xc8dbc8dc  syscall_handler + 0x13ac
0xc8dbb521  syscall_asm_entry + 0x31
0x24dd0e43  libc.so: .text + 0x1ae43
0x24db7c3a  libc.so: .text + 0x1c3a
0x24dbd80d  libc.so: .text + 0x780d
0x5aa2f8c5  /bin/DHCPClient: .text + 0x18c5
0x5aa3228d  /bin/DHCPClient: .text + 0x428d
0x5aa32378  /bin/DHCPClient: .text + 0x4378
0x2a63cc86  libcore.so.serenity: .text + 0x53c86
0x2a620eea  libcore.so.serenity: .text + 0x37eea
0x2a622bf1  libcore.so.serenity: .text + 0x39bf1
0x2a60b0c5  libcore.so.serenity: .text + 0x220c5
0x2a60ba2b  libcore.so.serenity: .text + 0x22a2b
0x5aa3b914  /bin/DHCPClient: .text + 0xd914
0x5aa2e5a8  /bin/DHCPClient: .text + 0x5a8
0x5aa2e7d6  /bin/DHCPClient: .text + 0x7d6
9.868 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 25
9.934 CrashDaemon(12:12): New coredump file: /tmp/coredump/DHCPClient_25_1651441070
9.938 SystemServer(6:6): Service DHCPClient has exited with exit code 6
9.943 SystemServer(6:6): Giving up on DHCPClient. Good luck!
9.961 CrashDaemon(12:12): Unable to map coredump /tmp/coredump/DHCPClient_25_1651441070: open: Permission denied (errno=13)
```

### PR DESCRIPTION
**Pull request by HerrSpace**
Fixes #13879

### CODE REVIEW

File: Userland/Services/DHCPClient/DHCPv4Client.cpp [hunk 1]
```diff
@@ -251,7 +254,12 @@ void DHCPv4Client::handle_ack(DHCPv4Packet const& packet, ParsedDHCPv4Options co
             dhcp_discover(interface);
         },
         this);
-    set_params(transaction->interface, new_ip, options.get<IPv4Address>(DHCPOption::SubnetMask).value(), options.get_many<IPv4Address>(DHCPOption::Router, 1).first());
+
+    Optional<IPv4Address> gateway;
+    if (!options.get_many<IPv4Address>(DHCPOption::Router, 1).is_empty())
+        gateway = options.get_many<IPv4Address>(DHCPOption::Router, 1).first();
```
Comment (alimpfard) [inline Userland/Services/DHCPClient/DHCPv4Client.cpp:260]:
```suggestion
    if (auto routers = options.get_many<...>(...); !routers.is_empty())
        gateway = routers.first();
```

Comment (HerrSpace) [reply Userland/Services/DHCPClient/DHCPv4Client.cpp]: ack. ty.
