### PR TITLE
CrashReporter: Don't crash when "Generating..." Window gets closed

### LINKED ISSUE #10264: CrashReporter: `m_window_id` assertion failure when closing the "generating" window
When you try to close the "Generating crash report" window, CrashReporter will crash with:
```
CrashReporter(41:41): ASSERTION FAILED: m_window_id
../../Userland/Libraries/LibGUI/Window.cpp:1132
CrashReporter(43:43): --- Backtrace for thread #0 (TID 41) ---
CrashReporter(43:43): 0x1e6db02e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashReporter(43:43): 0x6122727f: [libc.so] raise +0x2f (syscall.h:35 => signal.cpp:21 => signal.cpp:34)
CrashReporter(43:43): 0x61210759: [libc.so] abort +0x29 (stdlib.cpp:227)
CrashReporter(43:43): 0x61211251: [libc.so] __assertion_failed +0x71 (assert.cpp:33)
CrashReporter(43:43): 0x23d0a3fd: [libgui.so] GUI::Window::set_progress(AK::Optional<int>) +0x10d (Window.cpp:1132)
CrashReporter(43:43): 0x045bcdb7: [/bin/CrashReporter] AK::Function<void (unsigned long, unsigned long)>::CallableWrapper<build_backtrace(Coredump::Reader const&, ELF::Core::ThreadInfo const&, unsigned long)::{lambda(unsigned long, unsigned long)#1}>::call(unsigned long, unsigned long) +0x87 (main.cpp:71 => Function.h:151)
CrashReporter(43:43): 0x5f091739: [libCoredump.so] Coredump::Backtrace::Backtrace(Coredump::Reader const&, ELF::Core::ThreadInfo const&, AK::Function<void (unsigned long, unsigned long)>) +0x189 (Function.h:91)
CrashReporter(43:43): 0x045be925: [/bin/CrashReporter] build_backtrace(Coredump::Reader const&, ELF::Core::ThreadInfo const&, unsigned long) +0x545 (main.cpp:75)
CrashReporter(43:43): 0x045baa53: [/bin/CrashReporter] main +0x353 (main.cpp:185 => Reader.h:112 => main.cpp:184)
CrashReporter(43:43): 0x045bc835: [/bin/CrashReporter] _entry +0x65 (crt0.cpp:45)
```

### PR DESCRIPTION
**Pull request by sw1tchbl4d3r**
Previously, if you closed the "Generating..." Window before it finished, CrashReporter would still try to push progress updates to the closed window, encountering a VERIFY().
This PR checks if the window still exists before pushing updates, and closes the whole application when the "Generating..." Window gets closed by the user.

Closes #10264

### CODE REVIEW

File: Userland/Applications/CrashReporter/main.cpp [hunk 1]
```diff
@@ -41,19 +41,30 @@ struct TitleAndText {
...
     window->set_title("CrashReporter");
     window->set_resizable(false);
     window->resize(240, 64);
     window->center_on_screen();
+
+    window->on_close = [&]() {
+        auto& progressbar = *window->main_widget()->find_descendant_of_type_named<GUI::Progressbar>("progressbar");
+        if (progressbar.value() != progressbar.max())
+            exit(0);
+    };
```
Comment (awesomekling) [inline Userland/Applications/CrashReporter/main.cpp:54]: If you move this block of code below the creation of `progressbar`, you can use `progressbar` directly in the lambda instead of having to `find_descendant_of_type_named` :)

File: Userland/Applications/CrashReporter/main.cpp [hunk 2]
```diff
@@ -68,6 +79,8 @@ static TitleAndText build_backtrace(Coredump::Reader const& coredump, ELF::Core:
 
     auto timer = Core::ElapsedTimer::start_new();
     Coredump::Backtrace backtrace(coredump, thread_info, [&](size_t frame_index, size_t frame_count) {
+        if (!progress_window->window_id())
+            return;
```
Comment (awesomekling) [inline Userland/Applications/CrashReporter/main.cpp:83]: A more expressive check here would be `if (!progress_window->is_visible())`

That said, do we actually need this check if we exit the program on progress window close?

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Userland/Applications/CrashReporter/main.cpp (hunk 2 above)
Comment (sw1tchbl4d3r) [reply Userland/Applications/CrashReporter/main.cpp:83]: I thought of some sort of race, where we're inside of the on_close function, but another thread tries to still push the update before we exit()'ed, or are both of those things in the same thread?

Comment (BenWiederhake) [inline Userland/Applications/CrashReporter/main.cpp:83]: Question: When does this trigger? If the above `on_close -> exit()` triggers, then this code doesn't run anymore. If it doesn't trigger, then this code doesn't need to check whether `progress_window` still exists.

If this `if` does make sense (and I just overlooked something), would a `if (!progress_window.is_visible())` make sense? It gets updated at basically the same time as `m_window_id`, and is a bit nicer to read. :bike:

Comment (sw1tchbl4d3r) [reply Userland/Applications/CrashReporter/main.cpp:83]: See my comment above

Comment (BenWiederhake) [reply Userland/Applications/CrashReporter/main.cpp]: We only set `m_window_id = 0` long after `on_close` has returned. So if your `on_close` calls `exit`, that never happens, and `if (!progress_window->window_id())` never triggers.

Also: Yes, most GUI things are on the EventLoop, so they can't execute in parallel.

Suggestion: Just remove it, `exit` shouldn't be able to have any race conditions with this.

Comment (BenWiederhake) [reply Userland/Applications/CrashReporter/main.cpp]: Ha, a real-life race condition :D

Comment (sw1tchbl4d3r) [reply Userland/Applications/CrashReporter/main.cpp]: That does make sense, I removed it.

**Comment by awesomekling** [comment]
I would normally discourage the adding of random extra whitespace, but since it's in close proximity to your real change, it's fine for this time.
