### PR TITLE
LibGUI: Add MoveLineUpOrDownCommand

### LINKED ISSUE #8071: LibGUI/TextEditor: Moving a line up/down to an empty line causes assertion failure
Trying to move a line with ctrl+shift+up or ctrl+shift+down when the target line is empty will cause an assertion failure while trying to create a Utf32View with no code point and the length of the previous line.

Can be reproduced in for example HackStudio and TextEditor.

Dump
```
TextEditor(30:30): USERSPACE(30) ASSERTION FAILED: code_points || length == 0
../.././AK/Utf32View.h:71
[#0 TextEditor(30:30)]: Terminating TextEditor(30) due to signal 6
[#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +1537
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +1038
0xdeadc0de  Kernel::Scheduler::pick_next() +1174
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +537
0xdeadc0de  Kernel::Thread::die_if_needed() +565
0xdeadc0de  syscall_handler +11325
0xdeadc0de  Kernel::syscall_asm_entry_dummy() +49
0x35997165
0x359802c6
0x35980e2b
0x416b1d7f
0x416b1f1d
0x416b2116
0x416b7439
0x41624040
0x41625d54
0x416882d0
0x416b63c2
0x416d57bf
0x7be78401
0x416e68fd
0x416eed0a
0x7be78401
0x7be5df83
0x7be5e7ab
0x415cadf8
0xa7878456
0xa7878808
0x15b211ae
0x15af0505

[#0 FinalizerTask(4:4)]: Generating coredump for pid: 30
[FinalizerTask(4:4)]: RTC: Year: 2021, month: 6, day: 15, hour: 17, minute: 33, second: 59
WindowServer(22:22): ClientConnection(0x00d99228)::post_message: Disconnected from peer
CrashDaemon(20:20): New coredump file: /tmp/coredump/TextEditor_30_1623778439
[#0 CrashDaemon(20:20)]: kmalloc: Adding even more memory to heap at V0xc5ed7000, bytes: 2105344
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 30) ---
CrashDaemon(20:20): 0x19f231ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(20:20): 0x35997165: [libc.so] raise +0x25 (signal.cpp:21)
CrashDaemon(20:20): 0x359802c6: [libc.so] abort +0x2a (stdlib.cpp:233)
CrashDaemon(20:20): 0x35980e2b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(20:20): 0x416b1d7f: [libgui.so] GUI::TextEditor::content_x_for_position(GUI::TextPosition const&) const [clone .localalias] +0x2af (Utf32View.h:71)
CrashDaemon(20:20): 0x416b1f1d: [libgui.so] GUI::TextEditor::line_content_rect(unsigned long) const [clone .localalias] +0xcd (TextEditor.cpp:1089)
CrashDaemon(20:20): 0x416b2116: [libgui.so] GUI::TextEditor::line_widget_rect(unsigned long) const +0x36 (Frame.h:19)
CrashDaemon(20:20): 0x416b7439: [libgui.so] GUI::TextEditor::set_cursor(GUI::TextPosition const&) +0x359 (TextEditor.cpp:1138)
CrashDaemon(20:20): 0x41624040: [libgui.so] GUI::EditingEngine::move_selected_lines_up() [clone .localalias] +0x230 (EditingEngine.cpp:641)
CrashDaemon(20:20): 0x41625d54: [libgui.so] .L2166 +0xb4 (EditingEngine.cpp:98)
CrashDaemon(20:20): 0x416882d0: [libgui.so] GUI::RegularEditingEngine::on_key(GUI::KeyEvent const&) [clone .localalias] +0x20 (RegularEditingEngine.cpp:20)
CrashDaemon(20:20): 0x416b63c2: [libgui.so] GUI::TextEditor::keydown_event(GUI::KeyEvent&) +0x152 (TextEditor.cpp:821)
CrashDaemon(20:20): 0x416d57bf: [libgui.so] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) [clone .localalias] +0x2f (Widget.cpp:267)
CrashDaemon(20:20): 0x7be78401: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb1 (Object.h:113)
CrashDaemon(20:20): 0x416e68fd: [libgui.so] GUI::Window::handle_key_event(GUI::KeyEvent&) +0xcd (Window.cpp:434)
CrashDaemon(20:20): 0x416eed0a: [libgui.so] GUI::Window::event(Core::Event&) [clone .localalias] +0xfa (Window.cpp:555)
CrashDaemon(20:20): 0x7be78401: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb1 (Object.h:113)
CrashDaemon(20:20): 0x7be5df83: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x573 (Atomic.h:246)
CrashDaemon(20:20): 0x7be5e7ab: [libcore.so] Core::EventLoop::exec() +0x5b (EventLoop.cpp:360)
CrashDaemon(20:20): 0x415cadf8: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:106)
CrashDaemon(20:20): 0xa7878456: [/bin/TextEditor] main +0x536 (main.cpp:81)
CrashDaemon(20:20): 0xa7878808: [/bin/TextEditor] _start +0x58 (crt0.cpp:39)
```

### PR DESCRIPTION
**Pull request by LucasChollet**
This allows lines moved by Ctrl+Shift+[Up, Down] to be registered as a command, i.e. cancellable by Ctrl+Z.

This patch also introduces the usage of TextDocument::[take,insert]_line. Those functions forward changes to the visual lines and
then avoid some data mismatch.

~~Needs #14058 to be merged first (both PR share their 3 first commits)~~, and closes #8071.

### CODE REVIEW

**Comment by LucasChollet** [comment]
Rebased after #14058 got merged.

File: Userland/Libraries/LibGUI/EditingEngine.h [hunk 1]
```diff
@@ -45,6 +47,8 @@ class EditingEngine {
     bool is_regular() const { return engine_type() == EngineType::Regular; }
     bool is_vim() const { return engine_type() == EngineType::Vim; }
 
+    void get_selection_line_boundaries(Badge<MoveLineUpOrDownCommand>, size_t& first_line, size_t& last_line);
```
Comment (linusg) [inline Userland/Libraries/LibGUI/EditingEngine.h:50]: Out-parameters :acid2kiss:
