### PR TITLE
Kernel: Fix panic when switching to out-of-bounds console

### LINKED ISSUE #19034: Kernel panic: switching to non-existing console with ALT+7 or ALT+8
panic-1

Done on commit: 6ab660b62f451a

Explanation: 
'KeyboardDevice::handle_scan_code_input_event' line 256, has logical errors in the condition which allows values from 0 to 7 to be passed to 'ConsoleManagement::switch_to' (on keyboard input: ALT+1 to ALT+8). `VERIFY(index < m_consoles.size());`  in 'switch_to' catches if the value is greater than 5, and causes a kernel panic.

Code:

https://github.com/SerenityOS/serenity/blob/8f16d37f00019ebd5ffc732c3735fc9e7d3a9e02/Kernel/Devices/HID/KeyboardDevice.cpp#L256

https://github.com/SerenityOS/serenity/blob/8f16d37f00019ebd5ffc732c3735fc9e7d3a9e02/Kernel/TTY/ConsoleManagement.cpp#L74

### PR DESCRIPTION
**Pull request by tcl3**
This resurrects #19069. I was about to fix this before I noticed someone else already did it! 

I've taken the commit from @hojelse and reformatted the commit message.

Fixes #19034

### CODE REVIEW

File: Kernel/Devices/HID/KeyboardDevice.cpp [hunk 1]
```diff
@@ -253,7 +253,7 @@ void KeyboardDevice::handle_scan_code_input_event(ScanCodeEvent event)
         Scheduler::dump_scheduler_state(m_modifiers == (Mod_Ctrl | Mod_Alt | Mod_Shift));
     }
 
-    if ((m_modifiers & Mod_Alt) != 0 && key >= Key_1 && key <= Key_1 + ConsoleManagement::s_max_virtual_consoles + 1) {
+    if ((m_modifiers & Mod_Alt) != 0 && key >= Key_1 && key <= Key_1 + ConsoleManagement::s_max_virtual_consoles - 1) {
```
Comment (MacDue) [inline Kernel/Devices/HID/KeyboardDevice.cpp:256]: Nit: You could just do `<` rather than `<=` and `-1`

Comment (tcl3) [reply Kernel/Devices/HID/KeyboardDevice.cpp]: Changed :^)

**Review by gmta — APPROVED** [review]
