### PR TITLE
LibWeb: Support ordered lists as well as different list-style-types for unordered lists

### LINKED ISSUE #2059: LibWeb: Ordered list is rendered as unordered list
HTML ordered list `<ol>` is rendered incorrectly as unordered list `<ul>`.
This naturally affects the Markdown ordered list, which wants to be rendered as `<ol>`.
```html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <ol>
            <li>This is first list item</li>
            <li>This is second list item</li>
            <li>This is third list item</li>
        </ol>
    </body>
</html>
```
Expected behavior:
image

Actual behavior:
image

### PR DESCRIPTION
**Pull request by TobyAsE**
This PR implements the display of ordered lists in the web browser (just decimal counting for now).
There is a pretty old issue #2059 discussing the matter but it seems it never got anywhere.

While I was at it, it was easy to also support the different list-style-types for unordered lists:
image

There are a lot more list-style-types out there, but they aren't supported by the parser yet.

Fixes #2059

### CODE REVIEW

File: Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.cpp [hunk 1]
```diff
@@ -44,11 +44,40 @@ void ListItemMarkerBox::paint(PaintContext& context, PaintPhase phase)
...
+        break;
+    case CSS::ListStyleType::Decimal:
+        context.painter().draw_text(enclosing, String::formatted("{}.", m_index), Gfx::TextAlignment::Center);
+        break;
+    case CSS::ListStyleType::Disc:
+        context.painter().fill_ellipse(marker_rect, color);
+        break;
+    case CSS::ListStyleType::None:
+        return;
+        break;
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.cpp:76]: No need for both `return` and `break` :)

**Comment by IdanHo** [comment]
You should add "Fixes #2059" to your PR message, so once this is merged that issue will be automatically closed :)

**Comment by linusg** [comment]
@IdanHo it's in the third commit :)

File: Userland/Libraries/LibWeb/TreeNode.h [hunk 2]
```diff
@@ -97,6 +97,33 @@ class TreeNode : public Weakable<T> {
         return const_cast<TreeNode*>(this)->child_at_index(index);
     }
 
+    int child_index(const T& search_child)
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/TreeNode.h:100]: Please return `Optional<size_t>` instead of `int` with a magic `-1` value.
And let's call it `index_of_child()` to emphasize "index" a little extra.
And also, maybe we can `VERIFY(search_child.parent() == this);` while we're here :)

**Comment by IdanHo** [comment]
> @IdanHo it's in the third commit :)

ah i see! the "no linked issues" on the sidebar tricked me :^)

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.cpp (hunk 1 above)
Comment (TobyAsE) [reply Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.cpp:76]: Good point ;)

File: Userland/Libraries/LibWeb/TreeNode.h [hunk 3]
```diff
@@ -97,6 +97,33 @@ class TreeNode : public Weakable<T> {
...
+    {
+        int index = 0;
+        auto* child = first_child();
```
Comment (Lubrsi) [inline Userland/Libraries/LibWeb/TreeNode.h:103]: There may not be any children, which will cause first_child to return nullptr and cause a null deref when trying to get the next sibling in the while loop.

File: Userland/Libraries/LibWeb/TreeNode.h [hunk 4]
```diff
@@ -97,6 +97,33 @@ class TreeNode : public Weakable<T> {
...
+            index++;
+        } while ((child = child->next_sibling()));
+        return -1;
+    }
+
+    template<typename ChildType>
+    int child_index(const T& search_child)
+    {
+        int index = 0;
+        auto* child = first_child();
```
Comment (Lubrsi) [inline Userland/Libraries/LibWeb/TreeNode.h:116]: Ditto

**Review by Lubrsi — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibWeb/TreeNode.h (hunk 3 above)
Comment (TobyAsE) [reply Userland/Libraries/LibWeb/TreeNode.h:103]: Using Kling's `VERIFY(search_child.parent() == this)` from above would mitigate this as we check whether we are the parent of the given node and therefore we have at least one child.
But in case something fishy is going on, we can still check for child being null in the while ;)

Comment (Lubrsi) [reply Userland/Libraries/LibWeb/TreeNode.h:104]: If we're asserting that, we could also assert that child isn't null, since like you said that assertion means we have at least one child.

Comment (TobyAsE) [reply Userland/Libraries/LibWeb/TreeNode.h:104]: Thats probably a good idea too!

File: Userland/Libraries/LibWeb/TreeNode.h [hunk 5]
```diff
@@ -97,6 +97,39 @@ class TreeNode : public Weakable<T> {
         return const_cast<TreeNode*>(this)->child_at_index(index);
     }
 
+    Optional<size_t> index_of_child(const T& search_child)
+    {
+        VERIFY(search_child.parent() == this);
+        int index = 0;
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/TreeNode.h:103]: s/int/size_t/

File: Userland/Libraries/LibWeb/TreeNode.h [hunk 6]
```diff
@@ -97,6 +97,39 @@ class TreeNode : public Weakable<T> {
...
+            index++;
+        } while (child && (child = child->next_sibling()));
+        return {};
+    }
+
+    template<typename ChildType>
+    Optional<size_t> index_of_child(const T& search_child)
+    {
+        VERIFY(search_child.parent() == this);
+        int index = 0;
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/TreeNode.h:119]: s/int/size_t/

**Comment by TobyAsE** [comment]
@awesomekling While we are at it, let me also bump this :^)
