### PR TITLE
LibGfx/JPEG: Add support for 12 bits JPEGs

### LINKED ISSUE #18720: LibGfx: Can't decode Spongebob weekend spotlight image from Steam
This image from the Steam store's weekend spotlight promo currently fails to display in our browser:

spotlight_image_english

cc @LucasChollet

### PR DESCRIPTION
**Pull request by LucasChollet**
Why do we need that?
To make Ladybird be the first browser to display [yo.jpg](https://github.com/nico/jpegfiles/blob/main/12-bit-progressive.jpg) of course!

It also fixes #18720 as it brings support for `SOF2` images with 4 Huffman tables.

### CODE REVIEW

File: Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp [hunk 1]
```diff
@@ -486,7 +486,11 @@ static ErrorOr<void> add_dc(JPEGLoadingContext& context, Macroblock& macroblock,
 
     // For DC coefficients, symbol encodes the length of the coefficient.
     auto dc_length = TRY(scan.huffman_stream.next_symbol(dc_table));
```
Comment (GMTA) [inline Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:488]: Commit message: allow -> allows

File: Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp [hunk 2]
```diff
@@ -1463,18 +1470,28 @@ static void inverse_dct(JPEGLoadingContext const& context, Vector<Macroblock>& m
...
-                            macroblocks[mb_index].b[i * 8 + j] = clamp(macroblocks[mb_index].b[i * 8 + j] + 128, 0, 255);
-                            macroblocks[mb_index].k[i * 8 + j] = clamp(macroblocks[mb_index].b[i * 8 + j] + 128, 0, 255);
+
+                            // FIXME: This just truncate all coefficients, it's an easy way to support (read hack)
+                            //        12 bits JPEGs without rewriting all color transformations.
+                            auto const clamp_to_8_bits = [&](u16 color) -> u8 {
+                                if (context.frame.precision == 8)
+                                    return static_cast<u8>(color);
+                                return static_cast<u8>(255 * color / 4096);
+                            };
```
Comment (GMTA) [inline Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:1489]: You can put the `clamp` in here as well for some more code deduplication

**Comment by LucasChollet** [comment]
Hold on! The second commit is bugged!

File: Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp [hunk 3]
```diff
@@ -1124,6 +1129,24 @@ static inline void set_macroblock_metadata(JPEGLoadingContext& context)
...
+    // Table B.2 - Frame header parameter sizes and values
+
+    if (frame.type == StartOfFrame::FrameType::Baseline_DCT && frame.precision == 8)
+        return {};
+
+    if (frame.type == StartOfFrame::FrameType::Extended_Sequential_DCT && frame.precision == 8)
+        return {};
+
+    if (frame.type == StartOfFrame::FrameType::Progressive_DCT && frame.precision == 8)
+        return {};
```
Comment (nico) [inline Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:1151]: Is `if (frame.precision == 8) return {};` not always correct? (Instead of the first 3 explicit case.)

File: Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp [hunk 4]
```diff
@@ -1457,18 +1470,28 @@ static void inverse_dct(JPEGLoadingContext const& context, Vector<Macroblock>& m
...
-                            macroblocks[mb_index].g[i * 8 + j] = clamp(macroblocks[mb_index].g[i * 8 + j] + 128, 0, 255);
-                            macroblocks[mb_index].b[i * 8 + j] = clamp(macroblocks[mb_index].b[i * 8 + j] + 128, 0, 255);
-                            macroblocks[mb_index].k[i * 8 + j] = clamp(macroblocks[mb_index].k[i * 8 + j] + 128, 0, 255);
+
+                            // FIXME: This just truncate all coefficients, it's an easy way to support (read hack)
+                            //        12 bits JPEGs without rewriting all color transformations.
+                            auto const clamp_to_8_bits = [&](u16 color) -> u8 {
+                                if (context.frame.precision == 8)
+                                    return static_cast<u8>(color);
+                                return static_cast<u8>(255 * color / 4096);
```
Comment (nico) [inline Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:1488]: How did you come up with this line? From a distance it feels off.

The naive thing to do is `color >> 4`. That's uniform (there's 16 buckets in the high-res space mapped to 1 in the low-res space).

I can also see the argument that you'd want to multiply by 255 / 4095, since you want a linear map that maps 0 to 0 and 4095 (the max 12-bit value) to 255 (the max 8-bit value) (this mathy derivation ignores narrowing effects though). This would be for (morally) calling `round()` on the result, and we'd map just the first 8 values to 0, then 16 to 1, ..., and only the last 8 to 1.

But the `>> 4` evenly distributes input ranges to output ranges, so that's probably the thing to go with?

Comment (LucasChollet) [reply Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:1488]: My brain is more on the mathy side of things I guess.

But yes, `color >> 4` is probably better as it:

1. Avoids narrowing effects
2. Avoids off by one issue 4096 vs 4095 :eyes:

Let's use that instead

File: Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp [hunk 5]
```diff
@@ -1137,6 +1144,12 @@ static ErrorOr<void> ensure_standard_precision(StartOfFrame const& frame)
     if (frame.precision == 8)
         return {};
 
+    if (frame.type == StartOfFrame::FrameType::Extended_Sequential_DCT && frame.precision == 12)
```
Comment (nico) [inline Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp:1147]: very nit: I'd probably

```
if (frame.precision == 12 && (frame.type == Extended_Sequential || frame.type == Progressive)
    return {};
```

**Review by nico — APPROVED** [review]
Nice!

File: Tests/LibGfx/TestImageDecoder.cpp [hunk 6]
```diff
@@ -156,6 +156,28 @@ TEST_CASE(test_jpeg_sof2_successive_aproximation)
     EXPECT_EQ(frame.image->size(), Gfx::IntSize(600, 800));
 }
 
+TEST_CASE(test_jpeg_sof1_12bits)
+{
+    auto file = MUST(Core::MappedFile::map(TEST_INPUT("12-bit.jpg"sv)));
```
Comment (nico) [inline Tests/LibGfx/TestImageDecoder.cpp:161]: Zombie comment: Do you remember how you created the files added in this commit?

Comment (LucasChollet) [reply Tests/LibGfx/TestImageDecoder.cpp:161]: Look, there is [this](https://github.com/nico/jpegfiles/blob/4f868c7a6f8f07098548115d7de3dcd46fea1f8b/README.md#yojpg) neat explanation on how it was done. You're very lucky to work with people that meticulous.
Joke aside, I should have put in the commit description.

Comment (nico) [reply Tests/LibGfx/TestImageDecoder.cpp:161]: Hahaha 😃 In my memory I had created that file, but then when I looked in git history it was you and I was like "oh, false memory, huh". Thanks for remembering this for me.
