### PR TITLE
LibGUI+LibGfx: Fix emoji scaling

### LINKED ISSUE #12001: Scaling of emojis
I do not know if this is intended behavior, a bug or just not implemented yet.

Monospace fonts scales emojis.
Proportional fonts does not scale emojis.

With current emojis:
**Proportional font**
proportional-up-1

**Monospace font**
monospace-up-1

It would be nice to have larger images that's scaled down, it works in monospace fonts:

monospace-3

monospace-2

monospace-1

But not in proportional fonts:

proportional-font-1

And it messes up in Font Editor & Character map

font-editor

What's up with that? :^)

### PR DESCRIPTION
**Pull request by sppmacd**
Fixes #12001.
This still have issues for fixed-width fonts (and in FontEditor) when emoji is bigger than glyph width. I'm not sure how it should be handled.

This PR doesn't touch any of the emojis itself (they are not upscaled)

image
image

**LibGfx: Always scale emojis to fit font height**

**LibGUI: Use Font::glyph_or_emoji_width() in TextEditor**

This fixes selection of text containing emoji when variable-width font
is set.

**LibGfx: Fix stylistic issues in BitmapFont**

* Apply some clang-tidy suggestions
* Convert to east-const

### CODE REVIEW

File: Userland/Libraries/LibGfx/Painter.cpp [hunk 1]
```diff
@@ -1248,7 +1244,7 @@ void Painter::draw_glyph_or_emoji(IntPoint const& point, u32 code_point, Font co
 
     // Perhaps it's an emoji?
     auto* emoji = Emoji::emoji_for_code_point(code_point);
-    if (emoji == nullptr) {
+    if (!emoji) {
```
Comment (linusg) [inline Userland/Libraries/LibGfx/Painter.cpp:1247]: This change seems unnecessary. In fact, clang-tidy recommends explicit nullptr checks.

Comment (sppmacd) [reply Userland/Libraries/LibGfx/Painter.cpp]: Fixed.
