### PR TITLE
CrashReporter: Don't update window progress if window has been closed

### LINKED ISSUE #23748: CrashReporter has crashed - Segmentation violation signal 11
Environment: Serenity OS

Steps to reproduce:
- Let an application e.g. Ladybird crash
- While crashreporter is collecting data, close crashreporter

```
2093.322 WebContent(131): VERIFICATION FAILED: m_ptr at ./Userland/Libraries/LibJS/Heap/GCPtr.h:168
2093.326 [WebContent(131:131)]: CRASH: CPU #0 Illegal instruction in userspace
2093.326 [#0 WebContent(131:131)]: Exception code: 0000 (isr: 0000)
2093.326 [#0 WebContent(131:131)]:     pc=0x0023:0x000000198cc46ea8 rflags=0x0000000000010206
2093.326 [#0 WebContent(131:131)]:  stack=0x00000014f8940f10  fs=0x000000146be84000  gs=0x000000202251b120
2093.326 [#0 WebContent(131:131)]:    rax=0x0000000000000000 rbx=0x0000001c3b4fe040 rcx=0x0000001c10d7902b rdx=0x00000014f8940db8
2093.326 [#0 WebContent(131:131)]:    rbp=0x00000014f8940f50 rsp=0x00000020110cbf60 rsi=0x00000014f8940db8 rdi=0x000000000000007a
2093.326 [#0 WebContent(131:131)]:     r8=0x0000000000000079  r9=0x0000000000000000 r10=0x0000000ba85f4448 r11=0x0000000000000212
2093.326 [#0 WebContent(131:131)]:    r12=0x0000000bc48bb040 r13=0x00000014f89410c0 r14=0x00000014f8941cd0 r15=0x0000000000000000
2093.326 [#0 WebContent(131:131)]:    cr0=0x0000000080010013 cr2=0x00000001abdf4050 cr3=0x000000006b9aa000 cr4=0x0000000000000ee0
2093.326 [#0 WebContent(131:131)]: 0x000000198cc46ea8  (?)

2093.326 [#0 WebContent(131:131)]: Kernel backtrace:
2093.326 [#0 WebContent(131:131)]: Kernel + 0x000000000139dc45  Kernel::Process::crash(int, AK::Optional<Kernel::RegisterState const&>, bool) +0x2c5
2093.326 [#0 WebContent(131:131)]: Kernel + 0x0000000001322b36  Kernel::handle_crash(Kernel::RegisterState const&, char const*, int, bool) +0x7e6
2093.326 [#0 WebContent(131:131)]: Kernel + 0x0000000001553de0  illegal_instruction_asm_entry +0x30
2093.353 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 131
2093.362 WindowServer(12): Can't keep up! Skipping approximately 1 iteration(s) of a reloading timer (delayed by 12ms).
2093.362 CrashDaemon(33): New coredump file: /tmp/coredump/WebContent_131_1711568420
2093.951 WindowServer(12): Can't keep up! Skipping approximately 1 iteration(s) of a reloading timer (delayed by 14ms).
2094.003 ConfigServer(28): Syncing 1 dirty domains to disk
2094.328 CrashReporter(134): Started Thread "Background Thread"(135)
2094.935 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 14 blocks to disk
2096.408 RequestServer(137): Loaded 145 of 145 (100%) provided CA Certificates
2097.410 RequestServer(139): Loaded 145 of 145 (100%) provided CA Certificates
2098.324 WebContent(138): Proxy mappings updated: proxies: [  ]
2099.011 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 2 blocks to disk
2099.674 WebContent(138): ResourceLoader: Refusing to prefetch DNS for 'https://stats.wp.com/': URL was filtered
2099.678 RequestServer(139): EnsureConnection: DNS-preload for secure.gravatar.com
2101.454 [#0 WebContent(138:138)]: Terminating WebContent(138) due to signal 13
2101.490 [#0 Network Task(9:9)]: handle_tcp: unexpected flags in FinWait2 state (18)
2101.495 [#0 Network Task(9:9)]: handle_tcp: No TCP socket for tuple {10.0.2.15:42310 -> 85.13.157.150:443}. Sending RST.
2101.674 [CrashReporter(134:135)]: Ext2FSInode[1:106876]::read_bytes(): Failed to read block 119003 (index 22747)
2101.683 [CrashReporter(134:135)]: handle_inode_fault: Error (Error(errno=4)) while reading from inode
2101.683 [#0 CrashReporter(134:135)]: Unrecoverable page fault, read from address V0x0000000014a61000
2101.694 [CrashReporter(134:135)]: CRASH: CPU #0 Page Fault in userspace
2101.694 [#0 CrashReporter(134:135)]: Exception code: 0004 (isr: 0000)
2101.694 [#0 CrashReporter(134:135)]:     pc=0x0023:0x0000000f147f2d6c rflags=0x0000000000010246
2101.694 [#0 CrashReporter(134:135)]:  stack=0x0000000000f25ad0  fs=0x00000011788df000  gs=0x000000202251b120
2101.699 [#0 CrashReporter(134:135)]:    rax=0x000000000121413d rbx=0x0000000000000001 rcx=0x0000000000000001 rdx=0x0000000000000001
2101.699 [#0 CrashReporter(134:135)]:    rbp=0x0000000000f25b10 rsp=0x0000002000a98e80 rsi=0x0000000014a61000 rdi=0x0000000000f25ba7
2101.710 [#0 CrashReporter(134:135)]:     r8=0x0000000000000013  r9=0x0000000000000001 r10=0x0000000000007ff0 r11=0x0000000000000246
2101.710 [#0 CrashReporter(134:135)]:    r12=0x0000000000f25d60 r13=0x0000000000f25b80 r14=0x0000000d74ed0130 r15=0x0000000d74ed0130
2101.710 [#0 CrashReporter(134:135)]:    cr0=0x0000000080010013 cr2=0x0000000e79590bca cr3=0x000000001c98f000 cr4=0x0000000000000ee0
2101.723 [#0 CrashReporter(134:135)]: 0x0000000f147f2d6c  (?)

2101.723 [#0 CrashReporter(134:135)]: Kernel backtrace:
2101.736 [#0 CrashReporter(134:135)]: Kernel + 0x000000000139dc45  Kernel::Process::crash(int, AK::Optional<Kernel::RegisterState const&>, bool) +0x2c5
2101.738 [#0 CrashReporter(134:135)]: Kernel + 0x0000000001322b36  Kernel::handle_crash(Kernel::RegisterState const&, char const*, int, bool) +0x7e6
2101.738 [#0 CrashReporter(134:135)]: Kernel + 0x0000000000019883  Kernel::PageFault::handle(Kernel::RegisterState&) +0xbb3
2101.746 [#0 CrashReporter(134:135)]: Kernel + 0x00000000015560e0  page_fault_handler +0x110
2101.746 [#0 CrashReporter(134:135)]: Kernel + 0x0000000001553ef6  page_fault_asm_entry +0x36
2101.746 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 134
2101.754 CrashDaemon(33): New coredump file: /tmp/coredump/CrashReporter_134_1711568428
2102.851 WindowServer(12): Can't keep up! Skipping approximately 2 iteration(s) of a reloading timer (delayed by 25ms).
2103.079 CrashReporter(140): Started Thread "Background Thread"(141)
2104.081 CrashReporter(140:141): Generating backtrace took 1003 ms
2104.081 CrashReporter(140:141): --- Backtrace for thread #0 (TID 134) ---
2104.081 CrashReporter(140:141): 0x0000000604e14017: [/usr/lib/libsystem.so] syscall1 +0x7 (syscall.cpp:20 => syscall.cpp:19)
2104.097 CrashReporter(140:141): 0x0000000f147af823: [/usr/lib/libc.so] exit +0x43 (stdlib.cpp:364)
2104.097 CrashReporter(140:141): 0x000000055e1f4c3b: [/bin/CrashReporter] _entry +0x2b (crt0.cpp:50)
2104.412 RequestServer(143): Loaded 145 of 145 (100%) provided CA Certificates
2105.156 WindowServer(12): Can't keep up! Skipping approximately 1 iteration(s) of a reloading timer (delayed by 6ms).
2105.355 RequestServer(145): Loaded 145 of 145 (100%) provided CA Certificates
2105.511 CrashReporter(140:141): Generating backtrace took 1359 ms
2105.514 CrashReporter(140:141): --- Backtrace for thread #1 (TID 135) ---
2105.514 CrashReporter(140:141): 0x0000000f147f2d6c: [/usr/lib/libc.so] AK::FixedMemoryStream::read_until_filled(AK::Span<unsigned char>) [clone .localalias] +0x5c (TypedTransfer.h:41 => TypedTransfer.h:34 => Span.h:202 => MemoryStream.cpp:63)
2105.527 CrashReporter(140:141): 0x00000002b6405103: [/usr/lib/libdebug.so.serenity] Debug::Dwarf::LineProgram::run_program() +0xb3 (Stream.h:62 => LineProgram.cpp:291)
2105.527 CrashReporter(140:141): 0x00000002b64056ca: [/usr/lib/libdebug.so.serenity] Debug::Dwarf::LineProgram::create(Debug::Dwarf::DwarfInfo&, AK::SeekableStream&) +0x14a (LineProgram.cpp:30)
2105.533 CrashReporter(140:141): 0x00000002b63ffabc: [/usr/lib/libdebug.so.serenity] Debug::Dwarf::DwarfInfo::populate_compilation_units() +0x13c (DwarfInfo.cpp:62)
2105.542 CrashReporter(140:141): 0x00000002b64000bb: [/usr/lib/libdebug.so.serenity] Debug::Dwarf::DwarfInfo::DwarfInfo(ELF::Image const&) +0x24b (DwarfInfo.cpp:32)
2105.542 CrashReporter(140:141): 0x00000002b63f17c1: [/usr/lib/libdebug.so.serenity] Debug::DebugInfo::DebugInfo(ELF::Image const&, AK::ByteString, unsigned long) +0x91 (DebugInfo.cpp:20)
2105.548 CrashReporter(140:141): 0x0000001fdebb30c8: [/usr/lib/libcoredump.so.serenity] Coredump::Backtrace::object_info_for_region(Coredump::Reader const&, Coredump::MemoryRegionInfo const&) [clone .localalias] +0x178 (NonnullOwnPtr.h:150 => Backtrace.cpp:38)
2105.558 CrashReporter(140:141): 0x0000001fdebb37d8: [/usr/lib/libcoredump.so.serenity] Coredump::Backtrace::add_entry(Coredump::Reader const&, unsigned long) [clone .localalias] +0x2b8 (Backtrace.cpp:119)
2105.562 CrashReporter(140:141): 0x0000001fdebb4203: [/usr/lib/libcoredump.so.serenity] Coredump::Backtrace::Backtrace(Coredump::Reader const&, ELF::Core::ThreadInfo const&, AK::Function<void (unsigned long, unsigned long)>) +0x1c3 (Backtrace.cpp:87)
2105.562 CrashReporter(140:141): 0x000000055e1fdeed: [/bin/CrashReporter] AK::Function<AK::ErrorOr<ThreadBacktracesAndCpuRegisters, AK::Error> (Threading::BackgroundAction<ThreadBacktracesAndCpuRegisters>&)>::CallableWrapper<serenity_main(Main::Arguments)::{lambda(auto:1&)#2}>::call(Threading::BackgroundAction<ThreadBacktracesAndCpuRegisters>&) +0x35d (main.cpp:59)
2105.582 WebContent(144): Proxy mappings updated: proxies: [  ]
2105.586 CrashReporter(140:141): 0x000000055e2033bb: [/bin/CrashReporter] Threading::BackgroundAction<ThreadBacktracesAndCpuRegisters>::BackgroundAction(AK::Function<AK::ErrorOr<ThreadBacktracesAndCpuRegisters, AK::Error> (Threading::BackgroundAction<ThreadBacktracesAndCpuRegisters>&)>, AK::Function<AK::ErrorOr<void, AK::Error> (ThreadBacktracesAndCpuRegisters)>, AK::Optional<AK::Function<void (AK::Error)> >)::{lambda()#1}::operator()() const +0x8b (Function.h:115)
2105.596 CrashReporter(140:141): 0x00000006d8b04d15: [/usr/lib/libthreading.so.serenity] background_thread_func() +0x6e5 (Function.h:115)
2105.606 CrashReporter(140:141): 0x00000006d8b05800: [/usr/lib/libthreading.so.serenity] Threading::Thread::start()::{lambda(void*)#1}::_FUN(void*) +0x70 (Function.h:115)
2105.611 CrashReporter(140:141): 0x0000000f1478c0a1: [/usr/lib/libc.so] pthread_create_helper +0x41 (pthread.cpp:74)

```

### PR DESCRIPTION
**Pull request by tcl3**
This prevents a crash that could happen if crash reporter was closed while generating a crash report.

Fixes #23748

### CODE REVIEW

File: Userland/Applications/CrashReporter/main.cpp [hunk 1]
```diff
@@ -317,12 +317,15 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
...
 
     (void)Threading::BackgroundAction<ThreadBacktracesAndCpuRegisters>::construct(
-        [&, coredump = move(coredump)](auto&) {
+        [&, window = window->make_weak_ptr<GUI::Window>(), coredump = move(coredump)](auto&) {
             ThreadBacktracesAndCpuRegisters results;
             size_t thread_index = 0;
             coredump->for_each_thread_info([&](auto& thread_info) {
                 results.thread_backtraces.append(build_backtrace(*coredump, thread_info, thread_index, [&](size_t frame_index, size_t frame_count) {
                     app->event_loop().deferred_invoke([&, frame_index, frame_count] {
+                        if (!window || !window->is_visible())
```
Comment (AtkinsSJ) [inline Userland/Applications/CrashReporter/main.cpp:326]: This seems like a TOCTOU issue. IIRC there's a way to get a strong reference, which we should probably use here
