### PR TITLE
SystemServer: Change group ownership on all framebuffer devices 

### LINKED ISSUE #8402: SystemServer+WindowServer: multiple VGA compatible devices setup doesn't work
How to reproduce:
1. Add to `run.sh` after the line of `-device $SERENITY_QEMU_DISPLAY_DEVICE`:
```sh
-device secondary-vga
-device VGA,vgamem_mb=64
```
2. Run.

To ease working with this setup, use the gtk backend.

The first two devices simply don't work (they're not initialized), the third device is initialized but nothing happens - only a black screen can be seen.
I suspect it's a bug both in the Kernel and in `WindowServer`.

cc @tomuta

### PR DESCRIPTION
**Pull request by supercomputer7**
Fixes #8402.

### CODE REVIEW

File: Userland/Services/SystemServer/main.cpp [hunk 1]
```diff
@@ -82,6 +83,31 @@ static void chown_wrapper(const char* path, uid_t uid, gid_t gid)
     }
 }
 
+static void chown_all_framebuffer_devices(group* phys_group)
+{
+    VERIFY(phys_group);
+    struct stat cur_file_stat;
+
+    DIR* dev_dir = opendir("/dev/");
```
Comment (awesomekling) [inline Userland/Services/SystemServer/main.cpp:91]: Please use `Core::DirIterator` instead :)

File: Userland/Services/SystemServer/main.cpp [hunk 2]
```diff
@@ -82,6 +83,28 @@ static void chown_wrapper(const char* path, uid_t uid, gid_t gid)
...
+static void chown_all_framebuffer_devices(group* phys_group)
+{
+    VERIFY(phys_group);
+    struct stat cur_file_stat;
+
+    Core::DirIterator di("/dev/", Core::DirIterator::SkipParentAndBaseDir);
+    if (di.has_error())
+        VERIFY_NOT_REACHED();
+    while (di.has_next()) {
+        auto entry_name = String::formatted("/dev/{}", di.next_path());
```
Comment (gunnarbeutner) [inline Userland/Services/SystemServer/main.cpp:95]: `Core::DirIterator` has `next_full_path()` for that.
