### PR TITLE
Utilities: Print arbitrary bytes in `ls` by fixing for loop in `print_escaped`

### LINKED ISSUE #16678: Utilities: `ls` crashes when attempting to print certain (non-Unicode) byte sequences
When attempting to print non-Unicode file names that consist of arbitrary bytes, `ls` will often crash due to a failed assertion. This can be reproduced by created a file with the following command:
```
$ touch $(head -c 10 /dev/random)
```
Occasionally this works, but other times it causes a crash with the following backtrace:
```
0x0000001162ff602b: [/usr/lib/libsystem.so] syscall2 +0xb (syscall.cpp:25 => syscall.cpp:24)
0x00000011e7c9616d: [/usr/lib/libc.so] abort +0x26 (stdlib.cpp:387)
0x00000011e7c9c38e: [/usr/lib/libc.so] __assertion_failed.localalias +0x7e (assert.cpp:33)
0x0000001c11a359d4: [/bin/ls] print_escaped(AK::StringView) +0xe4 (StringView.h:77 => ls.cpp:210)
0x0000001c11a35ce2: [/bin/ls] print_name(stat const&, AK::DeprecatedString const&, char const*, char const*) +0x182 (ls.cpp:270)
0x0000001c11a36541: [/bin/ls] print_filesystem_object_short(char const*, char const*, unsigned long*) +0x71 (ls.cpp:452)
0x0000001c11a38e0a: [/bin/ls] serenity_main(Main::Arguments) +0x1e1a (ls.cpp:466 => ls.cpp:546 => ls.cpp:139 => ls.cpp:189)
0x0000001c11a355f8: [/bin/ls] main +0x128 (Main.cpp:39)
0x0000001c11a35798: [/bin/ls] _entry +0x48 (crt0.cpp:48)
```
It appears the indexing operating in `StringView` is trying to access an out-of-bounds index.

### PR DESCRIPTION
**Pull request by Tyrubias**
Currently, `ls` crashes when printing certain byte sequences. This is likely due to an out-of-bounds error when iterating through the `StringView` representing the file name to be printed. We switch to using an index-based for loop to a range-based for loop. This fixes #16678.

### CODE REVIEW

**Comment by MacDue** [comment]
Just an FYI you don't need to make issues for things you intend to fix :^)

File: Userland/Utilities/ls.cpp [hunk 1]
```diff
@@ -207,12 +207,12 @@ static int print_escaped(StringView name)
         return utf8_name.length();
     }
 
-    for (int i = 0; name[i] != '\0'; i++) {
-        if (isprint(name[i])) {
-            putchar(name[i]);
+    for (auto const& c : name) {
```
Comment (LucasChollet) [inline Userland/Utilities/ls.cpp:210]: Don't take a `const&` for small types
