### PR TITLE
 Kernel: Retry mmap if MAP_FIXED is not in flags and addr is not 0 

### LINKED ISSUE #884: mmap fails when given non-null address.
`mmap` typically fails when passed a non-null pointer as its first parameter.
I believe that this is because `sys$mmap` calls this:
https://github.com/SerenityOS/serenity/blob/ac20919b13f82ea9f8d59fe1f34054b7060a96df/Kernel/VM/RangeAllocator.cpp#L94
which fails when given a virtual address that is not in `m_available_ranges`. This is an issue because a pointer obtained via malloc or a global variable will, to my understanding, not be in `m_available_ranges`. Also, if we are unable to create the mapping at the given address we should instead try to create it at a more suitable address.

### PR DESCRIPTION
**Pull request by ADKaster**
If an mmap fails to allocate a region, but the addr passed in was
non-zero, non-fixed mmaps should attempt to allocate at any available
virtual address.

Also includes adding a move-assign operator to KResultOr because you couldn't re-use the same "optional" before.

Closes #884

### CODE REVIEW

File: Kernel/KResult.h [hunk 1]
```diff
@@ -62,6 +62,18 @@ class alignas(T) KResultOr {
...
 
+    KResultOr& operator=(KResultOr&& other)
+    {
+        m_is_error = other.m_is_error;
+        if (m_is_error)
+            m_error = other.m_error;
+        else
+            new (&m_storage) T(move(other.value()));
+        other.m_is_error = true;
+        other.m_error = KSuccess;
```
Comment (awesomekling) [inline Kernel/KResult.h]: We're forgetting to call the destructor on `value()` here. I don't think we should delay that until `~KResultOr()` unless we have a reason?

Also let's stick to the convention where a moved-from object looks as if it were just default-constructed.
A default-constructed `KResultOr` has `m_is_error = false` and `m_error = {}`.

Comment (ADKaster) [reply Kernel/KResult.h]: Hmm this was copy pasted from the move constructor, which leaves the moved-from object as is_error: yes, error = 0. It doesn't seem to make much sense to leave it in is_error = no, with a maybe constructed maybe not constructed T in the buffer to me? At least if is_error is true with an empty error the value is "defined". Though yeah, if 'this' has value it should probably be destroyed before we move construct a new T into the buffer.

Comment (ADKaster) [reply Kernel/KResult.h]: Also I'm not sure what you mean by "default constructed"? There isn't a default constructor for KResultOr, there's an error constructor, a T moving constructor, and a convert-U-to-T moving constructor. Seems reasonable to me that a moved-from object should be an error.

Comment (awesomekling) [reply Kernel/KResult.h]: Oh yeah duh. That's my bad, clearly `KResultOr` has no default constructor.
However, the way the move constructor and the new move assignment operator are written, we will neglect to invoke `~T()` on the moved-from object's `value()` after moving from it into our own `value()`.

Comment (ADKaster) [reply Kernel/KResult.h]: Oh yeah, because we tell the moved-from object that it's now an error and the ~T() won't get called ever. Wonder if any of the other containers have the same oversight :)

File: Kernel/Process.cpp [hunk 2]
```diff
@@ -288,6 +293,9 @@ void* Process::sys$mmap(const Syscall::SC_mmap_params* params)
         if (!description)
             return (void*)-EBADF;
         auto region_or_error = description->mmap(*this, VirtualAddress((u32)addr), static_cast<size_t>(offset), size, prot);
+        if (region_or_error.is_error() && (map_fixed || addr == 0))
+            return (void*)(int)region_or_error.error();
+        region_or_error = description->mmap(*this, {}, static_cast<size_t>(offset), size, prot);
```
Comment (ADKaster) [inline Kernel/Process.cpp]: Wait this totally isn't right

**Comment by awesomekling** [comment]
Great! Thanks for fixing this up :D
