### PR TITLE
Kernel: Ensure non-pseudo file systems are backed by a file

### LINKED ISSUE #1351: Filesystem implementation
This is not really a bug as such but its just a suggestion, I also haven't studied this code very long so I could be wrong.

I noticed some of your filesystems extend the disk backed operating system class. I assume this means a filesystem that is on disk?

My suggestion is wouldn't it make more sense to abstract that out entirely rather than extend the disk backed operating system. You may want EXT to be mounted to a file in the future, or a loop back device like Linux does.

Making the filesystem only work on disk is a limitation in my eyes.

Just a suggestion.

**As stated I haven't looked at the code very long so I could have misunderstood the way you implemented this**

I also noticed you don't have FAT32 yet, if I get some time wouldn't mind giving it a go at implementing it I've implemented FAT32 before and in my old job used to develop filesystem drivers for Linux for a living. Would be pretty interested just want to check this is allowed or if you have enough contributors

Many thanks

### PR DESCRIPTION
**Pull request by supercomputer7**
Fixes #1351.

cc @bugaevc for this PR :)

### CODE REVIEW

File: Kernel/FileSystem/Ext2FileSystem.cpp [hunk 1]
```diff
@@ -64,13 +64,33 @@ static u8 to_ext2_file_type(mode_t mode)
...
+{
+}
+
+Ext2FS::Ext2FS(NonnullRefPtr<FileDescription> file_description)
+    : FileBackedFS(file_description)
+{
+}
+
+Ext2FS::Ext2FS(NonnullRefPtr<File> file)
+    : FileBackedFS(file)
```
Comment (bugaevc) [inline Kernel/FileSystem/Ext2FileSystem.cpp]: Do we really need all the different constructors?..

File: Kernel/FileSystem/FileBackedFileSystem.cpp [hunk 2]
```diff
@@ -107,115 +107,139 @@ class DiskCache {
...
+FileBackedFS::FileBackedFS(NonnullRefPtr<FileDescription> file_description)
+    : m_file(file_description->file())
+    , m_file_description(file_description)
 {
 }
 
-DiskBackedFS::~DiskBackedFS()
+FileBackedFS::FileBackedFS(NonnullRefPtr<File> file)
+    : m_file(file)
+    , m_file_description(FileDescription::create(*m_file))
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.cpp]: We should just always take a `File&` and make a file description from it.

File: Kernel/FileSystem/FileBackedFileSystem.cpp [hunk 3]
```diff
@@ -107,115 +107,139 @@ class DiskCache {
...
 }
 
-bool DiskBackedFS::write_block(unsigned index, const u8* data, FileDescription* description)
+FileBackedFS::~FileBackedFS()
 {
-#ifdef DBFS_DEBUG
-    klog() << "DiskBackedFileSystem::write_block " << index << ", size=" << data.size();
+}
+
+bool FileBackedFS::write_block(unsigned index, const u8* data, FileDescription* description, bool use_logical_block_size)
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.cpp]: Is `file_description` the parameter ever used?

Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: Ah, I see it is, for `allow_cache`

File: Kernel/FileSystem/FileBackedFileSystem.h [hunk 4]
```diff
@@ -31,33 +31,42 @@
...
 
-    virtual bool is_disk_backed() const override { return true; }
+    virtual bool is_file_backed() const override { return true; }
 
-    BlockDevice& device() { return *m_device; }
-    const BlockDevice& device() const { return *m_device; }
+    File& file() { return *m_file; }
+    FileDescription& file_description() { return *m_file_description; }
+    const File& file() const { return *m_file; }
+    const FileDescription& file_description() const { return *m_file_description; }
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.h]: Can't we get the file from the file description, instead of storing it explicitly?

File: Kernel/FileSystem/ProcFS.cpp [hunk 5]
```diff
@@ -746,8 +746,8 @@ Optional<KBuffer> procfs$df(InodeIdentifier)
         fs_object.add("readonly", fs.is_readonly());
         fs_object.add("mount_flags", mount.flags());
 
-        if (fs.is_disk_backed())
-            fs_object.add("device", static_cast<const DiskBackedFS&>(fs).device().absolute_path());
+        if (fs.is_file_backed())
+            fs_object.add("file", static_cast<const FileBackedFS&>(fs).file().absolute_path(static_cast<const FileBackedFS&>(fs).file_description()));
```
Comment (bugaevc) [inline Kernel/FileSystem/ProcFS.cpp]: You can just call `absolute_path()` on the FD.

File: Kernel/FileSystem/VirtualFileSystem.cpp [hunk 6]
```diff
@@ -38,6 +38,8 @@
 
 //#define VFS_DEBUG
 
+#define FILENAME_MAX 4096
```
Comment (bugaevc) [inline Kernel/FileSystem/VirtualFileSystem.cpp]: 😭

File: Kernel/FileSystem/VirtualFileSystem.cpp [hunk 7]
```diff
@@ -126,14 +128,14 @@ bool VFS::mount_root(FS& file_system)
...
+    char filename[FILENAME_MAX];
+    if (m_root_inode->fs().is_file_backed()) {
+        auto& file = static_cast<FileBackedFS&>(m_root_inode->fs()).file();
+        sprintf(filename, "%s", file.absolute_path(static_cast<FileBackedFS&>(m_root_inode->fs()).file_description()).characters());
     } else {
-        sprintf(device_name, "not-a-disk");
+        sprintf(filename, "not-a-disk");
     }
-    klog() << "VFS: mounted root on " << m_root_inode->fs().class_name() << " (" << device_name << ")";
+    klog() << "VFS: mounted root on " << m_root_inode->fs().class_name() << " (" << filename << ")";
```
Comment (bugaevc) [inline Kernel/FileSystem/VirtualFileSystem.cpp]: And you don't even need it; just use the string returned by `static_cast<FileBackedFS&>(m_root_inode->fs()).file_description().absolute_description()` directly.

File: Kernel/Process.cpp [hunk 8]
```diff
@@ -4060,16 +4060,16 @@ int Process::sys$mount(const Syscall::SC_mount_params* user_params)
...
             return source_or_error.error();
 
-        auto* device = source_or_error.value()->device();
-        if (!device || !device->is_block_device()) {
-            dbg() << "mount: this is not a BlockDevice";
+        auto file_description = source_or_error.value();
+        auto& file = file_description->file();
+        if (!file.is_seekable()) {
+            dbg() << "mount: this is not a seekable file";
             return -ENODEV;
```
Comment (bugaevc) [inline Kernel/Process.cpp]: You better change `sys$mount()` to accept an FD directly.

**Comment by bugaevc** [comment]
👍

File: Kernel/Process.cpp [hunk 9]
```diff
@@ -4045,31 +4045,26 @@ int Process::sys$mount(const Syscall::SC_mount_params* user_params)
     auto& target_custody = custody_or_error.value();
 
     RefPtr<FS> fs;
+    auto fd = file_description(source_fd);
+    if (fd.is_null())
+        return -EFAULT;
```
Comment (bugaevc) [inline Kernel/Process.cpp]: `EBADF`

File: Kernel/Syscall.h [hunk 10]
```diff
@@ -395,7 +395,7 @@ struct SC_rename_params {
 };
 
 struct SC_mount_params {
-    StringArgument source;
+    int source;
```
Comment (bugaevc) [inline Kernel/Syscall.h]:
```suggestion
    int source_fd;
```

File: Libraries/LibC/unistd.cpp [hunk 11]
```diff
@@ -588,14 +588,14 @@ int reboot()
     __RETURN_WITH_ERRNO(rc, rc, -1);
 }
 
-int mount(const char* source, const char* target, const char* fs_type, int flags)
+int mount(int fd, const char* target, const char* fs_type, int flags)
```
Comment (bugaevc) [inline Libraries/LibC/unistd.cpp]:
```suggestion
int mount(int source_fd, const char* target, const char* fs_type, int flags)
```

File: Libraries/LibC/unistd.cpp [hunk 12]
```diff
@@ -588,14 +588,14 @@ int reboot()
...
 {
-    if (!source || !target || !fs_type) {
+    if (fd < 0 || !target || !fs_type) {
         errno = EFAULT;
```
Comment (bugaevc) [inline Libraries/LibC/unistd.cpp]: Same here, don't return `EFAULT` for bad fds.

File: Kernel/Process.cpp (hunk 9 above)
Comment (supercomputer7) [reply Kernel/Process.cpp]: or maybe we should have `EBADFD`? I don't see it in errno_numbers.h, but I do see it in other file in my system.

File: Userland/mount.cpp [hunk 13]
```diff
@@ -96,11 +96,18 @@ bool mount_all()
             continue;
         }
 
-        dbg() << "Mounting " << devname << "(" << fstype << ")"
+        const char* filename = parts[0].characters();
+        int fd = open(filename, O_RDONLY);
+        if (fd < 0) {
+            fprintf(stderr, "Failed to open : %s\n", filename);
```
Comment (bugaevc) [inline Userland/mount.cpp]: Don't forget to print the error itself. Use `perror` or something (except string formatting can change errno, so stach it like this:
```suggestion
            int saved_errno = errno;
            auto message = String::format("Failed to open %s", filename);
            errno = saved_errno;
            perror(message.characters());
```

File: Kernel/FileSystem/Ext2FileSystem.cpp [hunk 14]
```diff
@@ -64,13 +64,23 @@ static u8 to_ext2_file_type(mode_t mode)
...
+    return adopt(*new Ext2FS(file_description));
+}
+
+Ext2FS::Ext2FS(File& file)
+    : FileBackedFS(file)
+{
+}
+
+Ext2FS::Ext2FS(NonnullRefPtr<FileDescription> file_description)
+    : FileBackedFS(file_description)
```
Comment (bugaevc) [inline Kernel/FileSystem/Ext2FileSystem.cpp]: Again, let's just decide whether we want to take a file or a file description, and always accept that, and make the callers (are there many? :slightly_smiling_face:) get the right one themselves. Also, no need to pass `NonnullRefPtr<FileDescription>` when you can just pass a `FileDescription&`

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 3 above)
Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: A question though: how should the callers decide whether they should `use_logical_block_size` or not?

File: Kernel/FileSystem/FileBackedFileSystem.cpp [hunk 15]
```diff
@@ -107,115 +107,131 @@ class DiskCache {
...
 {
-#ifdef DBFS_DEBUG
-    klog() << "DiskBackedFileSystem::write_block " << index << ", size=" << data.size();
+    ASSERT(m_logical_block_size);
+#ifdef FBFS_DEBUG
+    klog() << "FileBackedFileSystem::write_block " << index << ", size=" << data.size();
 #endif
 
     bool allow_cache = !description || !description->is_direct();
+    auto selected_block_size = use_logical_block_size ? m_logical_block_size : block_size();
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.cpp]: Naming suggestion: `effective_block_size` (but I'm not sure, English is not my first language, yada yada, all standard disclaimers apply)

File: Kernel/FileSystem/FileBackedFileSystem.cpp [hunk 16]
```diff
@@ -225,23 +241,24 @@ void DiskBackedFS::flush_writes_impl()
         if (!entry.is_dirty)
             return;
         u32 base_offset = static_cast<u32>(entry.block_index) * static_cast<u32>(block_size());
-        device().write_raw(base_offset, block_size(), entry.data);
+        m_file_description->seek(base_offset, SEEK_SET);
+        file().write(*m_file_description, entry.data, block_size());
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.cpp]: Can't you call `FileDescription::write()` directly? And don't forget to check the write succeeded (and wrote this many bytes). Also, we should check that the file is seekable upfront (when constructing ourselves) — you cannot, for example, mount Ext2FS from a pipe :slightly_smiling_face:

File: Kernel/FileSystem/VirtualFileSystem.cpp [hunk 17]
```diff
@@ -126,14 +126,7 @@ bool VFS::mount_root(FS& file_system)
...
     m_root_inode = move(root_inode);
-    char device_name[32];
-    if (m_root_inode->fs().is_disk_backed()) {
-        auto& device = static_cast<DiskBackedFS&>(m_root_inode->fs()).device();
-        sprintf(device_name, "%d,%d", device.major(), device.minor());
-    } else {
-        sprintf(device_name, "not-a-disk");
-    }
-    klog() << "VFS: mounted root on " << m_root_inode->fs().class_name() << " (" << device_name << ")";
+    klog() << "VFS: mounted root on " << m_root_inode->fs().class_name() << " (" << static_cast<FileBackedFS&>(m_root_inode->fs()).file_description().absolute_path() << ")";
```
Comment (bugaevc) [inline Kernel/FileSystem/VirtualFileSystem.cpp]: The message should actually read "mounted root _from_ /dev/s.." — it's mounted from there onto `/`. Let's fix that too :slightly_smiling_face:

File: Kernel/Makefile [hunk 18]
```diff
@@ -57,7 +57,7 @@ OBJS = \
     DoubleBuffer.o \
     FileSystem/Custody.o \
     FileSystem/DevPtsFS.o \
-    FileSystem/DiskBackedFileSystem.o \
+    FileSystem/FileBackedFileSystem.o \
```
Comment (bugaevc) [inline Kernel/Makefile]: Nitpick: A, B, C, D, F, E, F :slightly_smiling_face:

File: Kernel/Process.cpp [hunk 19]
```diff
@@ -4048,28 +4052,24 @@ int Process::sys$mount(const Syscall::SC_mount_params* user_params)
...
-            return source_or_error.error();
-
-        auto* device = source_or_error.value()->device();
-        if (!device || !device->is_block_device()) {
-            dbg() << "mount: this is not a BlockDevice";
+        if (fd.is_null())
+            return -EBADF;
+        ASSERT(fd->custody());
+        if (!fd->file().is_seekable()) {
+            dbg() << "mount: this is not a seekable file";
```
Comment (bugaevc) [inline Kernel/Process.cpp]: Great; that's what i meant by checking upfront. But let's also add an assertion in the `FBFS` constructor.

File: Libraries/LibC/unistd.cpp [hunk 20]
```diff
@@ -588,14 +588,14 @@ int reboot()
     __RETURN_WITH_ERRNO(rc, rc, -1);
 }
 
-int mount(const char* source, const char* target, const char* fs_type, int flags)
+int mount(int source_fd, const char* target, const char* fs_type, int flags)
 {
-    if (!source || !target || !fs_type) {
-        errno = EFAULT;
+    if (source_fd <= 0 && (!target || !fs_type)) {
+        errno = EBADF;
```
Comment (bugaevc) [inline Libraries/LibC/unistd.cpp]: No no no, don't return `EBADF` for null strings either. Just check them separately :slightly_smiling_face:

Comment (bugaevc) [reply Libraries/LibC/unistd.cpp]: Actually don't check `source_fd` at all, let the kernel handle it and return `EBADF` if it wants a valid fd for that FS.

File: Userland/mount.cpp [hunk 21]
```diff
@@ -96,11 +96,20 @@ bool mount_all()
             continue;
         }
 
-        dbg() << "Mounting " << devname << "(" << fstype << ")"
+        const char* filename = parts[0].characters();
+        int fd = open(filename, O_RDONLY);
+        if (fd < 0) {
+            int saved_errno = errno;
+            auto message = String::format("Failed to open : %s", filename);
```
Comment (bugaevc) [inline Userland/mount.cpp]: Space before the colon, not cool :slightly_frowning_face:

File: Userland/mount.cpp [hunk 22]
```diff
@@ -96,11 +96,20 @@ bool mount_all()
             continue;
         }
 
-        dbg() << "Mounting " << devname << "(" << fstype << ")"
+        const char* filename = parts[0].characters();
+        int fd = open(filename, O_RDONLY);
```
Comment (bugaevc) [inline Userland/mount.cpp]: Will the kernel like readonly descriptors though? Wouldn't it return an error when you try to write a block?

**Comment by bugaevc** [comment]
Please don't forget the `mount(2)` man page

File: Userland/mount.cpp (hunk 21 above)
Comment (supercomputer7) [reply Userland/mount.cpp]: Oops, my bad!

File: Kernel/FileSystem/FileBackedFileSystem.cpp [hunk 23]
```diff
@@ -107,115 +107,129 @@ class DiskCache {
...
     bool allow_cache = !description || !description->is_direct();
+    auto selected_block_size = use_logical_block_size ? m_logical_block_size : block_size();
 
     if (!allow_cache) {
         flush_specific_block_if_needed(index);
-        u32 base_offset = static_cast<u32>(index) * static_cast<u32>(block_size());
-        device().write_raw(base_offset, block_size(), data);
+        u32 base_offset = static_cast<u32>(index) * static_cast<u32>(selected_block_size);
+        m_file_description->seek(base_offset, SEEK_SET);
+        auto write_size = m_file_description->write(data, selected_block_size);
```
Comment (bugaevc) [inline Kernel/FileSystem/FileBackedFileSystem.cpp]: This variable is by convention named `nwritten` (`nread` if you're reading).

File: Userland/mount.cpp [hunk 24]
```diff
@@ -96,11 +96,23 @@ bool mount_all()
             continue;
         }
 
-        dbg() << "Mounting " << devname << "(" << fstype << ")"
+        const char* filename = parts[0].characters();
+        int fd = open(filename, O_RDWR);
+        if (fd < 0)
+            fd = open(filename, O_DIRECTORY);
```
Comment (supercomputer7) [inline Userland/mount.cpp]: @bugaevc what do you think about this pattern? is it a good thing to try to open a path with other flag if the first attempt failed?

Comment (bugaevc) [reply Userland/mount.cpp]: The pattern is fine, but the specific code is sadly wrong.
* You should always pass either `O_RDONLY`, `O_WRONLY`, `O_EXEC`, `O_RDWR` (or a combination of them). You can add other flags, but one of those two should always be present.
* `O_DIRECTORY`, unlike the mode flags I listed above, is not a special mode to open directories, it's a special flag that modifies `open()` behavior. Specifically, it asks `open()` to fail if the thing you're opening turns out not to be a directory. This is *not* what you want here.

Comment (supercomputer7) [reply Userland/mount.cpp]: `fd = open(filename, O_RDONLY | O_DIRECTORY);` - can I do that in the second attempt?

Comment (bugaevc) [reply Userland/mount.cpp]: That would fix my point number 1, but not my point number 2 🙂.
Just `open(filename, O_RDONLY)`

Comment (supercomputer7) [reply Userland/mount.cpp]: but then we could have a problem with read-only file descriptors, so if you try to write to it, it will fail in the kernel, right?

Comment (bugaevc) [reply Userland/mount.cpp]: Yeah, you pass a r/o fd to `mount()` and that may fail (in `sys$mount()` or later), or it may be fine (r/o should be enough for bind-mounts). But it's not like passing `O_DIRECTORY` was going to make your fd read-write :slightly_smiling_face: — we'd be hitting this code path exactly when we cannot open the file as read-write, so we try read-only as a fallback.

Comment (supercomputer7) [reply Userland/mount.cpp]: OK, thanks for the help :)

**Comment by supercomputer7** [comment]
Screenshot_2020-03-29_00-38-05
Screenshot_2020-03-29_00-38-24
Successful mounting when invoking `mount` as superuser. Seems like mounting from fstab doesn't work, maybe due to wrong formatting...

**Comment by supercomputer7** [comment]
@bugaevc do you have other suggestions for this patch? let me know if there are :)

File: Base/usr/share/man/man2/mount.md [hunk 25]
```diff
@@ -21,9 +21,9 @@ int mount(const char* source, const char* target, const char* fs_type, int flags
 * `DevPtsFS` (or `devpts`): The pseudoterminal pseudo-filesystem (normally mounted at `/dev/pts`).
 * `TmpFS` (or `tmp`): A non-persistent filesystem that stores all its data in RAM. An instance of this filesystem is normally mounted at `/tmp`.
 
-For Ext2FS, `source` must be a path to a block device storing the filesystem contents. All
-the other filesystems ignore the `source` argument (by convention, it should have the same
-value as `fs_type`).
+For Ext2FS, `source_fd` must be a file descriptor of a file which stores the
+filesystem contents. All the other filesystems ignore the `source` argument (by
+convention, it should have the same value as `fs_type`).
```
Comment (bugaevc) [inline Base/usr/share/man/man2/mount.md]: "For Ext2FS, `source_fd` must refer to an open file descriptor to a file containing the filesystem image. This may be a device file or any other seekable file. All the other filesystems ignore the `source_fd` — you can even pass an invalid file descriptor such as -1."

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 3 above)
Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: The question still stands.

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 16 above)
Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: Bump

File: Kernel/FileSystem/FileDescription.cpp [hunk 26]
```diff
@@ -98,11 +98,7 @@ off_t FileDescription::seek(off_t offset, int whence)
     if (!m_file->is_seekable())
         return -EINVAL;
 
-    auto metadata = this->metadata();
-    if (!metadata.is_valid())
-        return -EIO;
-
-    if (metadata.is_socket() || metadata.is_fifo())
+    if (m_file->is_socket() || m_file->is_fifo())
```
Comment (bugaevc) [inline Kernel/FileSystem/FileDescription.cpp]: Why do we check this if we've already checked that it's seekable?

File: Userland/mount.cpp [hunk 27]
```diff
@@ -96,11 +96,23 @@ bool mount_all()
             continue;
         }
 
-        dbg() << "Mounting " << devname << "(" << fstype << ")"
+        const char* filename = parts[0].characters();
+        // FIXME: Find a better way to check if we handle a psuedo file system...
+        int fd = open(filename, O_RDWR);
+        if (fd < 0)
+            fd = open(filename, O_RDONLY);
+        if (fd <= 0 && !strcmp(fstype, "ext2")) {
```
Comment (bugaevc) [inline Userland/mount.cpp]: Why check for `<=` (and not `<`) here?

File: Userland/mount.cpp [hunk 28]
```diff
@@ -179,7 +191,17 @@ int main(int argc, char** argv)
             fs_type = "ext2";
         int flags = options ? parse_options(options) : 0;
 
-        if (mount(source, mountpoint, fs_type, flags) < 0) {
+        // FIXME: Find a better way to check if we handle a psuedo file system...
+
+        int fd = open(source, O_RDWR);
+        if (fd < 0)
+            fd = open(source, O_RDONLY);
+        if (fd <= 0 && !strcmp(fs_type, "ext2")) {
```
Comment (bugaevc) [inline Userland/mount.cpp]: And here. Maybe this should be a helper function?

File: Base/usr/share/man/man2/mount.md (hunk 25 above)
Comment (bugaevc) [reply Base/usr/share/man/man2/mount.md]: Also, don't forget to update the "Bind mounts" and "Errors" sections below.

**Comment by bugaevc** [comment]
And please fix the second commit message to be imperative case :smile:

File: Kernel/FileSystem/ProcFS.cpp [hunk 29]
```diff
@@ -746,8 +746,8 @@ Optional<KBuffer> procfs$df(InodeIdentifier)
         fs_object.add("readonly", fs.is_readonly());
         fs_object.add("mount_flags", mount.flags());
 
-        if (fs.is_disk_backed())
-            fs_object.add("device", static_cast<const DiskBackedFS&>(fs).device().absolute_path());
+        if (fs.is_file_backed())
+            fs_object.add("file", static_cast<const FileBackedFS&>(fs).file_description().absolute_path());
```
Comment (supercomputer7) [inline Kernel/FileSystem/ProcFS.cpp]: Either `device` or `file` too specific, so we might want to use a more general key name here.

Comment (bugaevc) [reply Kernel/FileSystem/ProcFS.cpp]: "File" sounds fine to me; but we might want to say "source" or "image".

Comment (supercomputer7) [reply Kernel/FileSystem/ProcFS.cpp]: I thought about "source", since we provide a `source_fd` parameter to `mount()`.

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 16 above)
Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: Another bump? 🙂

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 3 above)
Comment (bugaevc) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: Another bump here, too

**Comment by supercomputer7** [comment]
@bugaevc After the conversation in the IRC, I resolved the problems that were raised in your comments. I could miss some suggestions if I already mark the comments as "resolved", and if that happens, let me know about it :)

File: Kernel/FileSystem/FileBackedFileSystem.cpp (hunk 3 above)
Comment (supercomputer7) [reply Kernel/FileSystem/FileBackedFileSystem.cpp]: As I mentioned in the IRC channel, we need to distinguish between "virtual disk reads" and "file system reads". Previously, when we read the ext2 superblock, we called `device().read_raw()` to fetch the superblock. Now we can't use that call anymore because we are not backed by a `BlockDevice`, so the block size for reading the superblock is still 512 bytes like when we used `device().read_raw()`, but we need to do implement in the `FileBackedFileSystem` layer instead. 

Not only that this is necessary for fetching "pure blocks" from the disk, it will allow us to easily implement reading & writing from other types of media, like CD-ROM (with 2048 bytes per sector), or for new modern harddrives (with 4K sectors). 

In addition to that flexibility, some harddrives today have 4k sectors internally (in ATA IDENTIFY structure, the physical sector size value is 4096 bytes), and the logical sector size is 512 bytes, to stay compatible with old software that assumes 512 bytes per sector for all harddrives. It's important to know what is the physical sector size, to allow writing on 4K boundaries for optimization purposes.
You can read more about that here:
https://ata.wiki.kernel.org/index.php/ATA_4_KiB_sector_issues

**Comment by bugaevc** [comment]
Just a few more minor nits...

File: Base/usr/share/man/man2/mount.md [hunk 30]
```diff
@@ -21,9 +21,10 @@ int mount(const char* source, const char* target, const char* fs_type, int flags
 * `DevPtsFS` (or `devpts`): The pseudoterminal pseudo-filesystem (normally mounted at `/dev/pts`).
 * `TmpFS` (or `tmp`): A non-persistent filesystem that stores all its data in RAM. An instance of this filesystem is normally mounted at `/tmp`.
 
-For Ext2FS, `source` must be a path to a block device storing the filesystem contents. All
-the other filesystems ignore the `source` argument (by convention, it should have the same
-value as `fs_type`).
+For Ext2FS, source_fd must refer to an open file descriptor to a file containing
+the filesystem image. This may be a device file or any other seekable file. All
+the other filesystems ignore the source_fd — you can even pass an invalid file
```
Comment (bugaevc) [inline Base/usr/share/man/man2/mount.md]: `source_fd` in monospace...

File: Base/usr/share/man/man2/mount.md [hunk 31]
```diff
@@ -37,14 +38,21 @@ mounted file system.
 
 ### Bind mounts
 
-If `MS_BIND` is specified in `flags`, `fs_type` is ignored and a bind mount is performed
-instead. In this case `source` is treated as a path to a file or directory whose contents
-are overlayed over `target`. This can be used  as an alternative to symlinks or hardlinks.
+If `MS_BIND` is specified in `flags`, `fs_type` is ignored and a bind mount is
+performed instead. In this case `source_fd` is treated as a file descriptor to a
+file or directory whose contents are overlayed over `target`. This can be used
```
Comment (bugaevc) [inline Base/usr/share/man/man2/mount.md]: I'd rather say it a bit differently: "in this case, the file or directory specified by `source_fd` is overlayed over `target` — the target appears to be replaced by a copy of the source."

File: Base/usr/share/man/man2/mount.md [hunk 32]
```diff
@@ -37,14 +38,21 @@ mounted file system.
...
 
+* `EFAULT`: The `fs_type` or `target` are invalid strings.
 * `EPERM`: The current process does not have superuser privileges.
-* `ENODEV`: The `fs_type` is unrecognized, or the device is not found, or the device doesn't contain a valid filesystem image.
+* `ENODEV`: The `fs_type` is unrecognized, or the file descriptor to source is
+  not found, or the source doesn't contain a valid filesystem image. Also, this
+  error occurs if `fs_type` is valid, but the file descriptor from `source_fd`
+  is not seekable.
+* `EBADF`: The `fs_type` is specified for non-psuedo filesystem, or if `MS_BIND`
+  is specified in `flags`, and `source_fd` is not valid.
```
Comment (bugaevc) [inline Base/usr/share/man/man2/mount.md]: This reads like `!pseudo || (bind && !valid)`, while we need to make it read as `(!pseudo || bind) && !valid`.

How about: "if the `source_fd` is not valid, and either `fs_type` specifies a file-backed filesystem (and not a pseudo filesystem), or `MS_BIND` is specified in `flags`.

File: Kernel/Process.cpp [hunk 33]
```diff
@@ -4011,14 +4011,18 @@ int Process::sys$mount(const Syscall::SC_mount_params* user_params)
...
+    auto source_fd = params.source_fd;
     auto target = validate_and_copy_string_from_user(params.target);
     auto fs_type = validate_and_copy_string_from_user(params.fs_type);
 
-    if (source.is_null() || target.is_null() || fs_type.is_null())
+    if (target.is_null() || fs_type.is_null())
         return -EFAULT;
 
-    dbg() << "mount " << fs_type << ": source " << source << " @ " << target;
+    auto fd = file_description(source_fd);
```
Comment (awesomekling) [inline Kernel/Process.cpp:4021]: These variables are conventionally called `description` whereas `fd` is used for file *descriptors* (`int`)

File: Userland/mount.cpp [hunk 34]
```diff
@@ -179,7 +199,9 @@ int main(int argc, char** argv)
             fs_type = "ext2";
         int flags = options ? parse_options(options) : 0;
 
-        if (mount(source, mountpoint, fs_type, flags) < 0) {
+        int fd = get_source_fd(source);
```
Comment (awesomekling) [inline Userland/mount.cpp:202]: Missing an error check here.

Comment (bugaevc) [reply Userland/mount.cpp:202]: There's not supposed to be an error check: if we get `-1`, we pass just that to the kernel.

File: Kernel/FileSystem/FileDescription.cpp [hunk 35]
```diff
@@ -98,11 +98,7 @@ off_t FileDescription::seek(off_t offset, int whence)
...
         return -ESPIPE;
```
[the remark this answers is not in the document]
Comment (supercomputer7) [reply Kernel/FileSystem/FileDescription.cpp]: Yes. There's no valid metadata when you mount the first harddrive in the stage2 of kernel initialization, because we directly sent a `BlockDevice` that isn't tied to any filesystem.

[the remark this answers is not in the document]
Comment (awesomekling) [reply Kernel/FileSystem/FileDescription.cpp]: Ok great.

File: Userland/mount.cpp (hunk 34 above)
Comment (awesomekling) [reply Userland/mount.cpp:202]: Okydoky!

Comment (bugaevc) [reply Userland/mount.cpp:202]: Maybe we should print an error message inside `get_source_fd()` if we fail to open the file though, just for diagnostics.
