### PR TITLE
Audio+LibCore: Replace the many Audio::Buffers by a single small-scale circular buffer

### LINKED ISSUE #11882: SoundPlayer: crashes and lockups when new files are dragged over
When new files to play are dragged over SoundPlayer while it is still playing audio, several weird things happen. The first is something I probably caused myself in 168f27760ebc4703f2e4891a4e81a9e8b33bda1e (#11290), a crash from verifying that buffers are played in order:
```
758.227 SoundPlayer(71:71): ASSERTION FAILED: last_buffer_in_queue == finished_buffer
../../Userland/Applications/SoundPlayer/PlaybackManager.cpp:22
759.260 CrashReporter(73:74): --- Backtrace for thread #0 (TID 71) ---
759.268 CrashReporter(73:74): 0x00000017c6b4502b: [libsystem.so] syscall2 +0xb (syscall.cpp:25 => syscall.cpp:24)
759.275 CrashReporter(73:74): 0x0000000a62e74a07: [libc.so] abort +0x27 (stdlib.cpp:221)
759.292 CrashReporter(73:74): 0x0000000a62e753be: [libc.so] __assertion_failed +0x7e (assert.cpp:33)
759.301 CrashReporter(73:74): 0x0000001ce58cf063: [/bin/SoundPlayer] AK::Function<void (int)>::CallableWrapper<PlaybackManager::PlaybackManager(AK:
:NonnullRefPtr<Audio::ClientConnection>)::{lambda(auto:1)#2}>::call(int) +0x173 (PlaybackManager.cpp:22 => Function.h:151)
759.322 CrashReporter(73:74): 0x000000186d220c91: [libaudio.so.serenity] Audio::ClientConnection::finished_playing_buffer(int) +0x51 (Function.h:91)
759.336 CrashReporter(73:74): 0x000000186d2256ab: [libaudio.so.serenity] AudioClientStub::handle(IPC::Message const&) +0xcb (AudioClientEndpoint.h:365)
759.353 CrashReporter(73:74): 0x000000143e735bb6: [libipc.so.serenity] IPC::ConnectionBase::handle_messages() [clone .localalias] +0xc6 (Connection.cpp:91)
759.370 CrashReporter(73:74): 0x000000186d224ad0: [libaudio.so.serenity] AK::Function<void ()>::CallableWrapper<IPC::Connection<AudioClientEndpoint
, AudioServerEndpoint>::Connection(IPC::Stub&, AK::NonnullRefPtr<Core::LocalSocket>)::{lambda()#1}>::call() +0x50 (Connection.h:80 => Function.h:151)
759.390 CrashReporter(73:74): 0x0000000c4150d1e8: [libcore.so.serenity] Core::Notifier::event(Core::Event&) [clone .localalias] +0x88 (Function.h:91)
759.396 CrashReporter(73:74): 0x0000000c4150e199: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x99 (Object.cpp:219)
759.405 CrashReporter(73:74): 0x0000000c414fa50b: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x14b (EventLoop.cpp:413)
759.412 CrashReporter(73:74): 0x0000000c414fb089: [libcore.so.serenity] Core::EventLoop::exec() +0x69 (EventLoop.cpp:370)
759.428 CrashReporter(73:74): 0x0000001ce58c8576: [/bin/SoundPlayer] serenity_main(Main::Arguments) +0x19e6 (main.cpp:137)
759.436 CrashReporter(73:74): 0x000000022f5e81cf: [libmain.so.serenity] main +0x8f (Main.cpp:20)
759.440 CrashReporter(73:74): 0x0000001ce58c5dd5: [/bin/SoundPlayer] _entry +0x65 (crt0.cpp:46)
```

This could be well-fixed by removing the playing buffers from the AudioServer or waiting till they finish.

Possibly related are frequent lockups that may happen in the same circumstances. They're not easily debuggable as SoundPlayer just "softlocks", not doing anything useful, not reacting to GUI input but also not spinning.

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
## The old audio system, the new audio system, and progress towards real-time audio.

Previously, we were sending Buffers to the server whenever we had new audio data for it. This meant that for every audio enqueue action, we needed to create a new shared memory anonymous buffer, send that buffer's file descriptor over IPC (+recfd on the other side) and then map the buffer into the audio server's memory to be able to play it. This was fine for sending large chunks of audio data, like when playing existing audio files. However, in the future we want to move to real-time audio in some applications like Piano. This means that the size of buffers that are sent need to be very small, as just the size of a buffer itself is part of the audio latency. If we were to try real-time audio with the existing system, we would run into problems really quickly. Dealing with a continuous stream of new anonymous files like the current audio system is rather expensive, as we need Kernel help in multiple places. Additionally, every enqueue incurs an IPC call, which are not optimized for >1000 calls/second (which would be needed for real-time audio with buffer sizes of ~40 samples). So a fundamental change in how we handle audio sending in userspace is necessary.

This PR moves the audio sending system onto a shared single producer circular queue (SSPCQ) (introduced with one of the previous commits). This queue is intended to live in shared memory and be accessed by multiple processes at the same time. It was specifically written to support the audio sending case, so e.g. it only supports a single producer (the audio client). Now, audio sending follows these general steps:
- The audio client connects to the audio server.
- The audio client creates a SSPCQ in shared memory.
- The audio client sends the SSPCQ's file descriptor to the audio server with the set_buffer() IPC call.
- The audio server receives the SSPCQ and maps it.
- The audio client signals start of playback with start_playback().
- At the same time:
  - The audio client writes its audio data into the shared-memory queue.
  - The audio server reads audio data from the shared-memory queue(s).
  Both sides have additional before-queue/after-queue buffers, depending on the exact application.
- Pausing playback is just an IPC call, nothing happens to the buffer except that the server stops reading from it until playback is  resumed.
- Muting has nothing to do with whether audio data is read or not.
- When the connection closes, the queues are unmapped on both sides.

### Implementation & commit notes:
- **Introduce SharedSingleProducerCircularQueue** & **Allow transporting SSPCQ over IPC**
- **Support FixedArray in DisjointChunks** #12733 
- **Split up Buffer.h** #12734 
- **Rename Buffer->LegacyBuffer**
- Audio loaders don't create LegacyBuffers anymore. LegacyBuffer is kept for WavLoader, see previous commit message.
- Most intra-process audio data passing is done with FixedArray<Sample> or Vector<Sample>.
- Improvements to most audio-enqueuing applications. (If necessary I can try to extract some of the aplay improvements.)
- New APIs on LibAudio/ClientConnection which allows non-realtime applications to enqueue audio in big chunks like before.
- Removal of status APIs from the audio server connection for information that can be directly obtained from the shared queue.
- Split the pause playback API into two APIs with more intuitive names.
- **Make new audio clients paused by default**

:yakring:

## What do you get for free?
- The generic SSPCQ which can be used elsewhere without trouble.
- Very smooth Piano.
- Less buggy SoundPlayer (I think I fixed #11882 "accidentally" but haven't confirmed that)
- Improved playback responsiveness in both sound player applications.
- Audio is OOM-hardened: it should take less memory overall to stream around audio.

## Known issues + TODOs - All fixed!
- [x] Hang in AS after changing sample rate. (No repro yet after merge of #12785 )
- [x] Two playbacks at the same time overwhelm the scheduler with constant yield(). Battle plan: estimate the time until further data can be inserted and nanosleep() until then.
- [x] Piano assert-crashes on startup.
- [x] End-of-playback ~~crash~~ endless loop in SoundPlayer. Battle plan: Don't append audio data in SoundPlayer while it's not playing; actually put the enqueuer thread to sleep.
- [x] BarsViz is black when first starting up. #12850

### CODE REVIEW

File: Userland/Libraries/LibAudio/Resampler.h [hunk 1]
```diff
@@ -6,6 +6,7 @@
 
 #pragma once
 
+#include <AK/Concepts.h>
 #include <AK/Types.h>
 #include <AK/Vector.h>
```
Comment (Hendiadyoin1) [inline Userland/Libraries/LibAudio/Resampler.h:12]: This commit seems weirdly empty

**Review by Hendiadyoin1 — COMMENTED** [review]
Haven't checked the conversion commit, but this one stuck out to me

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+#include <LibCore/AnonymousBuffer.h>
+#include <LibCore/System.h>
+#include <errno.h>
+#include <fcntl.h>
+#include <sched.h>
+#include <sys/mman.h>
+
+namespace Core {
+
+// A circular lock-free queue (or a buffer) with a single producer,
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:32]: This is something that really needs tests :smile:.

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 3]
```diff
@@ -0,0 +1,239 @@
...
+// residing in shared memory and designed to be accessible to multiple processes.
+// This implementation makes use of the fact that any producer-related code can be sure that
+// it's the only producer-related code that is running, which simplifies a bunch of the synchronization code.
+// The exclusivity and liveliness for critical sections in this class is proven to be correct
+// under the assumption of correct synchronization primitives, i.e. atomics.
+// In many circumstances, this is enough for cross-process queues.
+// This class is designed to be transferred over IPC and mmap()ed into multiple processes' memory.
+// It is a synthetic pointer to the actual shared memory, which is abstracted away from the user.
+// clang-format off
```
Comment (kleinesfilmroellchen) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:41]: this kills formatting in whole file, oops

File: Userland/Libraries/LibIPC/Decoder.h [hunk 4]
```diff
@@ -99,6 +102,19 @@ class Decoder {
...
 
+    template<typename T, size_t Size>
+    ErrorOr<void> decode(Core::SharedSingleProducerCircularQueue<T, Size>& queue)
+    {
+        // FIXME: We don't support receiving invalid queues.
+        VERIFY(!queue.is_valid());
+
+        IPC::File anon_file;
+        TRY(decode(anon_file));
+        // FIXME: Does this leak a refcount?
```
Comment (kleinesfilmroellchen) [inline Userland/Libraries/LibIPC/Decoder.h:113]: no it doesn't

File: Userland/Applications/Piano/AudioPlayerLoop.cpp [hunk 5]
```diff
@@ -9,8 +9,8 @@
```
Comment (kleinesfilmroellchen) [inline Userland/Applications/Piano/AudioPlayerLoop.cpp:9]: fix rename on new files in SP

File: Userland/Applications/Piano/AudioPlayerLoop.cpp [hunk 6]
```diff
@@ -8,18 +8,20 @@
...
 {
-    Vector<Audio::Sample, sample_count> frames;
-    frames.ensure_capacity(sample_count);
-    for (auto sample : samples) {
-        Audio::Sample frame = { sample.left / (double)NumericLimits<i16>::max(), sample.right / (double)NumericLimits<i16>::max() };
-        frames.unchecked_append(frame);
+    FixedArray<Audio::Sample> samples = MUST(FixedArray<Audio::Sample>::try_create(music_samples.size()));
+    for (size_t i = 0; i < music_samples.size(); ++i) {
+        samples[i] = { static_cast<double>(music_samples[i].left) / AK::NumericLimits<i16>::max(), static_cast<double>(music_samples[i].right) / AK::NumericLimits<i16>::max() };
     }
```
Comment (kleinesfilmroellchen) [inline Userland/Applications/Piano/AudioPlayerLoop.cpp:23]: loop curlies

File: Userland/Applications/Piano/main.cpp [hunk 7]
```diff
@@ -39,7 +39,6 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
 
     auto audio_loop = AudioPlayerLoop::construct(track_manager, need_to_write_wav, wav_writer);
     audio_loop->enqueue_audio();
```
Comment (kleinesfilmroellchen) [inline Userland/Applications/Piano/main.cpp:41]: unneeded

File: Userland/Applications/SoundPlayer/Player.cpp [hunk 8]
```diff
@@ -12,7 +12,7 @@ Player::Player(Audio::ConnectionFromClient& audio_client_connection)
     , m_playback_manager(audio_client_connection)
 {
     m_playback_manager.on_update = [&]() {
-        auto samples_played = m_audio_client_connection.get_played_samples();
+        auto samples_played = m_audio_client_connection.total_played_samples();
```
Comment (kleinesfilmroellchen) [inline Userland/Applications/SoundPlayer/Player.cpp:15]: oh god no, this is very incorrect as soon as we play another file. we should get this from the loader instead. why is this code here in the first place, wtf?

File: Userland/Libraries/LibAudio/ConnectionFromClient.h [hunk 9]
```diff
@@ -1,40 +1,102 @@
...
+    ErrorOr<void> enqueue(Samples& samples)
+    {
+        TRY(async_enqueue(samples));
+
+        while (remaining_samples() > 0)
+            // FIXME: better solution needed
+            sched_yield();
+
+        return {};
+    }
```
Comment (kleinesfilmroellchen) [inline Userland/Libraries/LibAudio/ConnectionFromClient.h:54]: this is unused anyways, sync enqueue is a bad idea and only caused issues in Piano & others. ill remove it

File: Userland/Utilities/asctl.cpp [hunk 10]
```diff
@@ -162,6 +163,8 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
             }
         }
     }
+    // FIXME: This shouldn't be necessary.
+    audio_client->shutdown();
```
Comment (kleinesfilmroellchen) [inline Userland/Utilities/asctl.cpp:167]: i should check this, die() had some bugs that maybe caused this

**Review by kleinesfilmroellchen — COMMENTED** [review]
notes to future self

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 11]
```diff
@@ -0,0 +1,239 @@
...
+        // Invariant: head and tail are monotonically increasing
+        // Invariant: tail always points to the next free location where an enqueue can happen.
+        // Invariant: head always points to the element to be dequeued next.
+        // Invariant: tail is only modified by enqueue functions.
+        // Invariant: head is only modified by dequeue functions.
+        // An empty queue is signalled with:  tail = head
+        // A full queue is signalled with:  head - 1 mod size = tail mod size  (i.e. head and tail point to the same index in the data array)
+        // FIXME: These invariants aren't proven to be correct after each successful completion of each operation where it is relevant.
+        //        The work could be put in but for now I think the algorithmic correctness proofs of the functions are enough.
+        Atomic<size_t, AK::MemoryOrder::memory_order_seq_cst> m_tail { 0 };
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:184]: You will likely want to align these to cache line size for the target architecture, so they sit on separate cache lines otherwise performance will likely suffer significantly due to [false sharing](https://en.wikipedia.org/wiki/False_sharing).

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 2 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:32]: abso-freaking-lutely.

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 12]
```diff
@@ -0,0 +1,239 @@
...
+        {
+        }
+
+    };
+
+    static ErrorOr<SharedSingleProducerCircularQueue<T, Size>> try_create_internal(int fd, bool is_new)
+    {
+        auto name = String::formatted("SharedSingleProducerCircularQueue@{:x}", fd);
+        auto* raw_mapping = TRY(System::mmap(nullptr, sizeof(SharedMemorySPCQ), PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0, 0, name));
+        dbgln("successfully mmapped {} at {:p}", name, raw_mapping);
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:218]: These `dbgln(..)`'s should be under a macro?

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 13]
```diff
@@ -0,0 +1,239 @@
...
+// residing in shared memory and designed to be accessible to multiple processes.
+// This implementation makes use of the fact that any producer-related code can be sure that
+// it's the only producer-related code that is running, which simplifies a bunch of the synchronization code.
+// The exclusivity and liveliness for critical sections in this class is proven to be correct
+// under the assumption of correct synchronization primitives, i.e. atomics.
+// In many circumstances, this is enough for cross-process queues.
+// This class is designed to be transferred over IPC and mmap()ed into multiple processes' memory.
+// It is a synthetic pointer to the actual shared memory, which is abstracted away from the user.
+// clang-format off
+template<typename T, size_t Size = 32>
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:42]: `Size` here seems like what we call `Capacity` in other containers? Should we rename that for clarity?

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 14]
```diff
@@ -0,0 +1,239 @@
...
+    using ValueType = T;
+
+    enum class QueueStatus : u8 {
+        Invalid = 0,
+        Full,
+        Empty,
+    };
+
+    SharedSingleProducerCircularQueue() = default;
+    // We need copy and move constructors because at the IPC boundary we can't throw around smart pointers.
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:57]: I'm having trouble following what this comment is suggesting.
Why/how would a `SharedSingleProducerCircularQueue` ever be passed over IPC?

Wouldn't you just need access to the `fd` and then create it on the other side via `SharedSingleProducerCircularQueue::try_create(..)`.

(Still have only looked at this early commit, not the follow ups yet.)

Comment (bgianfo) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:57]: 3923e0f5a13382cce2f17c6c83cabe24cd5928ba seems to confirm my understanding. So I'm confused why this need to be copyable / movable then, and why the inner queue is a `RefPtr<..>`?

File: Userland/Applications/SoundPlayer/PlaybackManager.cpp [hunk 15]
```diff
@@ -6,23 +6,17 @@
  */
 
 #include "PlaybackManager.h"
+#include <LibThreading/Thread.h>
```
Comment (bgianfo) [inline Userland/Applications/SoundPlayer/PlaybackManager.cpp:9]: Is this left over from a change that didn't make it into this PR?

File: Userland/Applications/SoundPlayer/PlaybackManager.h [hunk 16]
```diff
@@ -7,12 +7,15 @@
...
 
+#include <AK/FixedArray.h>
 #include <AK/Queue.h>
 #include <AK/Vector.h>
 #include <LibAudio/Buffer.h>
 #include <LibAudio/ConnectionFromClient.h>
 #include <LibAudio/Loader.h>
+#include <LibAudio/Sample.h>
 #include <LibCore/Timer.h>
+#include <LibThreading/Thread.h>
```
Comment (bgianfo) [inline Userland/Applications/SoundPlayer/PlaybackManager.h:18]: Not seeing where this would be used?

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 13 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:42]: No, because there's no size-capacity split as in resizeable containers like Vector. For this class size = capacity, and as with Array and FixedArray, we should call it size.

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 17]
```diff
@@ -1,48 +1,123 @@
...
+        auto available_samples = min(AUDIO_BUFFER_SIZE, m_user_queue->size());
+        for (size_t i = 0; i < available_samples; ++i) {
+            next_chunk[i] = (*m_user_queue)[i];
+        }
+
+        m_user_queue->slice(available_samples);
+
+        auto result = m_buffer->try_blocking_enqueue(next_chunk, [this]() {
+            timespec const sleep_time {
+                .tv_sec = m_good_sleep_time / 1'000'000'000,
```
Comment (bgianfo) [inline Userland/Libraries/LibAudio/ConnectionFromClient.cpp:92]: `AK::Time` should really be used to do time conversions. 
Also, why not just store the time you want to sleep as a `timespec` so you don't need to convert on every sleep?

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 14 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:57]: I discussed this with Ali and we settled on this solution: The outer class is mostly a wrapper around a RefPtr to the inner container that "owns" the shared memory. This is necessary specifically because of IPC, as the IPC encoding, decoding and transferring methods expects classes to be copyable and movable. So when we copy this outer class, we simply increment the refcount on the inner container. And yes, over IPC we only send the fd. The entire reference handling prodedure happens inside one process, it doesn't interact with the shared memory itself.

Looking at the comment again, it's from an old revision that didn't have this desing. I think I'll just remove it.

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 11 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:184]: That is an extremely smart observation, will do.

File: Userland/Libraries/LibAudio/ConnectionFromClient.h [hunk 18]
```diff
@@ -1,40 +1,102 @@
...
+
+    // Spinlocks if the buffer is full; use in conjunction with remaining_buffers to get low latency.
```
Comment (bgianfo) [inline Userland/Libraries/LibAudio/ConnectionFromClient.h:56]: This comment doesn't match the implementation as far as I can tell. The implementation calls `try_enqueue(samples)` which bails out immediately if the buffer is full.

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 13 above)
Comment (bgianfo) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:42]: Then you should rename your `capacity()` member to `size()`? :thinking:

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 19]
```diff
@@ -0,0 +1,239 @@
...
+// The exclusivity and liveliness for critical sections in this class is proven to be correct
+// under the assumption of correct synchronization primitives, i.e. atomics.
+// In many circumstances, this is enough for cross-process queues.
+// This class is designed to be transferred over IPC and mmap()ed into multiple processes' memory.
+// It is a synthetic pointer to the actual shared memory, which is abstracted away from the user.
+// clang-format off
+template<typename T, size_t Size = 32>
+// Size must be a power of two, which speeds up the modulus operations for indexing.
+requires(popcount(Size) == 1)
+class SharedSingleProducerCircularQueue final {
```
Comment (bgianfo) [inline Userland/Libraries/LibCore/SharedCircularQueue.h:45]: Data structures don't usually go in `LibCore`? I'm assuming there was a good reason you didn't put this in `AK`?

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 12 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:218]: They could be, but they're not very spammy so I think it's fine to leave them.

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 13 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:42]: :facepalm:

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 19 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:45]: Yep, it's because it's not very "agnostic" in that using it requires a bunch of operating system interaction. Just take a look at the includes; we shouldn't (and probably can't) have AK include other libraries' headers.

File: Userland/Applications/SoundPlayer/PlaybackManager.cpp (hunk 15 above)
Comment (kleinesfilmroellchen) [reply Userland/Applications/SoundPlayer/PlaybackManager.cpp:9]: Probably helpful clangd, yeah (I don't recall ever trying explicit multi-threading in SP...)

File: Userland/Libraries/LibAudio/ConnectionFromClient.h (hunk 18 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibAudio/ConnectionFromClient.h:56]: Yeah, I wrote that comment before I implemented the thing. The current behavior is what I want anyways, so I'll just change the comment.

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 20]
```diff
@@ -1,48 +1,120 @@
...
+        }
+
+        auto available_samples = min(AUDIO_BUFFER_SIZE, m_user_queue->size());
+        for (size_t i = 0; i < available_samples; ++i) {
+            next_chunk[i] = (*m_user_queue)[i];
+        }
+
+        m_user_queue->slice(available_samples);
+
+        auto result = m_buffer->try_blocking_enqueue(next_chunk, [this]() {
```
Comment (ADKaster) [inline Userland/Libraries/LibAudio/ConnectionFromClient.cpp:91]: Because of the use of the wait_function here in try_blocking_enqueue, the comment in the commit description about yield() should be removed.

Comment (ADKaster) [reply Userland/Libraries/LibAudio/ConnectionFromClient.cpp:91]: That being said, I think a FIXME is in order to add a non-sleepy blocking mechanism. For example, a hardware FIFO often has a "fill level" interrupt it sends to a bare metal/kernel application. When the queue fills up all the way, the next time the queue drains to e.g. 2/3 full, it will send an interrupt to say "ok, try sending some more data if you have any".

For example for Reals, [this hardware FIFO](https://www.xilinx.com/support/documentation/ip_documentation/axi_fifo_mm_s/v4_1/pg080-axi-fifo-mm-s.pdf) generates a `Transmit FIFO Programmable Empty` interrupt "[...] when the difference between the read and write pointers of the transmit FIFO reaches the programmable EMPTY threshold value when the FIFO is being emptied." I'm sure realtime audio subsystems have some kind of similar notification they use for this case :)

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 19 above)
Comment (bgianfo) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:45]: You could theoretically write the data structure to not require interaction with any of those things directly so it could be used in Kernel mode or usermode though?

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp (hunk 20 above)
Comment (bgianfo) [reply Userland/Libraries/LibAudio/ConnectionFromClient.cpp:91]: > That being said, I think a FIXME is in order to add a non-sleepy blocking mechanism.
+1

File: Userland/Libraries/LibCore/SharedCircularQueue.h (hunk 19 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:45]: I don't think that's necessary right now, as I intended it for userland specifically. I'll add a FIXME though.

File: AK/Platform.h [hunk 21]
```diff
@@ -110,3 +110,16 @@ extern "C" {
 #    define CLOCK_MONOTONIC_COARSE CLOCK_MONOTONIC
 #    define CLOCK_REALTIME_COARSE CLOCK_REALTIME
 #endif
+
+#ifndef SYSTEM_CACHE_ALIGNMENT_SIZE
+#    if defined(_AMD64_) || defined(_X86_)
```
Comment (linusg) [inline AK/Platform.h:115]: Please stick to using the `ARCH` macro?!

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 22]
```diff
@@ -1,48 +1,126 @@
...
 }
 
-void ConnectionFromClient::enqueue(Buffer const& buffer)
+void ConnectionFromClient::die()
 {
-    for (;;) {
-        auto success = enqueue_buffer(buffer.anonymous_buffer(), buffer.id(), buffer.sample_count());
-        if (success)
+    // We're sometimes getting here after the other thread has already exited and its event loop does no longer exist.
+    if (m_enqueuer_loop != nullptr) {
```
Comment (bgianfo) [inline Userland/Libraries/LibAudio/ConnectionFromClient.cpp:45]: This check for `m_enqueuer_loop` is racy, as it happens on the background thread.
That could lead us to corrupting memory by calling methods on a stack object, for a thread that is no longer present.

**Review by bgianfo — CHANGES_REQUESTED** [review]
Havne't finished reading through everything again, but this is as much as I have time for today.

File: Userland/Libraries/LibAudio/Buffer.h [hunk 23]
```diff
@@ -22,29 +22,36 @@
 #include <LibAudio/Sample.h>
 #include <LibAudio/SampleFormats.h>
 #include <LibCore/AnonymousBuffer.h>
+#include <LibCore/SharedCircularQueue.h>
 #include <string.h>
 
 namespace Audio {
+
+static constexpr size_t AUDIO_BUFFERS_COUNT = 128;
+// about 1/1000th of a second
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibAudio/Buffer.h:31]: How long an audio buffer is; I think the comment is in the right place.

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibAudio/ConnectionFromClient.cpp:45]: Yep, that's correct. I kind of hacked that and will make the loop properly RefPtr'd.

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 24]
```diff
@@ -1,48 +1,126 @@
...
+
+// Non-realtime audio writing loop
+void ConnectionFromClient::custom_event(Core::CustomEvent&)
+{
+    while (true) {
+        m_audio_enqueuer_active.store(true);
+        Array<Sample, AUDIO_BUFFER_SIZE> next_chunk;
+
+        if (m_user_queue->is_empty()) {
+            dbgln("Reached end of provided audio data, going to sleep");
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibAudio/ConnectionFromClient.cpp:85]: No, that's actually useful. If you're using the non-realtime system, this dbgln almost always incides with audio glitches, because you're not enqueuing fast enough. So it's super useful to find that, and in a properly written audio app it should never / only on purpose appear.

File: Tests/LibCore/TestSharedSingleProducerCircularQueue.cpp [hunk 25]
```diff
@@ -0,0 +1,194 @@
...
+            } while (result.is_error() && result.error() == TestQueue::QueueStatus::Empty);
+
+            if (result.is_error())
+                FAIL("Unexpected error while dequeueing.");
+        }
+        return 0;
+    });
+    second_thread->start();
+
+    for (size_t i = 0; i < test_count; ++i) {
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Tests/LibCore/TestSharedSingleProducerCircularQueue.cpp:97]: If you're saying cause more concurrency so that we catch more bugs, cool.

File: Userland/Applications/Piano/AudioPlayerLoop.cpp [hunk 26]
```diff
@@ -28,24 +30,31 @@ AudioPlayerLoop::AudioPlayerLoop(TrackManager& track_manager, bool& need_to_writ
...
     auto target_sample_rate = m_audio_client->get_sample_rate();
     if (target_sample_rate == 0)
         target_sample_rate = Music::sample_rate;
-    m_resampler = Audio::ResampleHelper<double>(Music::sample_rate, target_sample_rate);
+    m_resampler = Audio::ResampleHelper<Sample>(Music::sample_rate, target_sample_rate);
+
+    // FIXME: I said I would never write such a hack again, but here we are.
+    // This code should die as soon as possible anyways, so it doesn't matter.
+    // Please don't use this as an example to write good audio code; it's just here as a temporary hack.
+    Core::EventLoop::register_timer(*this, 10, true, Core::TimerShouldFireWhenNotVisible::Yes);
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Applications/Piano/AudioPlayerLoop.cpp:42]: Technically yes; though the loop never gets destructed anyways and after this is merged I plan on ripping out AudioPlayerLoop.

File: Userland/Applications/Piano/AudioPlayerLoop.cpp [hunk 27]
```diff
@@ -28,24 +30,31 @@ AudioPlayerLoop::AudioPlayerLoop(TrackManager& track_manager, bool& need_to_writ
...
-    };
 
     auto target_sample_rate = m_audio_client->get_sample_rate();
     if (target_sample_rate == 0)
         target_sample_rate = Music::sample_rate;
-    m_resampler = Audio::ResampleHelper<double>(Music::sample_rate, target_sample_rate);
+    m_resampler = Audio::ResampleHelper<Sample>(Music::sample_rate, target_sample_rate);
+
+    // FIXME: I said I would never write such a hack again, but here we are.
+    // This code should die as soon as possible anyways, so it doesn't matter.
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Applications/Piano/AudioPlayerLoop.cpp:40]: #11170, or its continuation

File: Userland/Applications/Piano/AudioPlayerLoop.cpp [hunk 28]
```diff
@@ -28,24 +30,31 @@ AudioPlayerLoop::AudioPlayerLoop(TrackManager& track_manager, bool& need_to_writ
...
 
 void AudioPlayerLoop::enqueue_audio()
 {
     m_track_manager.fill_buffer(m_buffer);
-    NonnullRefPtr<Audio::Buffer> audio_buffer = music_samples_to_buffer(m_buffer);
     // FIXME: Handle OOM better.
-    audio_buffer = MUST(Audio::resample_buffer(m_resampler.value(), *audio_buffer));
-    m_audio_client->async_enqueue(audio_buffer);
+    auto audio_buffer = m_resampler->resample(m_buffer);
+    auto real_buffer = music_samples_to_buffer(audio_buffer);
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Applications/Piano/AudioPlayerLoop.cpp:56]: That's old code but yes, it is a bit wasteful. As I'm saying, there's no purpose of me fixing code that is to be removed as quickly as possible.

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 29]
```diff
@@ -1,48 +1,126 @@
...
+        }
+
+        m_user_queue->slice(available_samples);
+
+        // FIXME: Could we recieve interrupts in a good non-IPC way instead?
+        auto result = m_buffer->try_blocking_enqueue(next_chunk, [this]() {
+            nanosleep(&m_good_sleep_time, nullptr);
+        });
+        if (result.is_error())
+            dbgln("Error while writing samples to shared buffer: {}", result.error());
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibAudio/ConnectionFromClient.cpp:101]: Looking at the underlying code, we can't ever return anything except a full queue error. So that's perfectly fine to ignore and try again. The audio server also does this, but in reverse.

File: Userland/Libraries/LibAudio/Buffer.h (hunk 23 above)
[the remark this answers is not in the document]
Comment (bgianfo) [reply Userland/Libraries/LibAudio/Buffer.h:31]: Please reword it then.

**Comment by Hendiadyoin1** [comment]
It seems you are failing your own tests:
> CRASHED LibCore/TestSharedSingleProducerCircularQueue (1.019247s)
         Test:   TestSharedSingleProducerCircularQueue (crashed)
Running test 'simple_enqueue'.
FAIL: ./Tests/LibCore/TestSharedSingleProducerCircularQueue.cpp:21: VERIFY(!_temporary_result.is_error()) failed
ASSERTION FAILED: has<T>()
././AK/Variant.h:366

[here](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=13329&view=logs&j=85a3409c-8a2a-5c59-a399-3144c1987667&t=50aae06d-3a0d-5656-8e04-ba50f41df426&l=338)

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 30]
```diff
@@ -1,48 +1,131 @@
...
-// FIXME: We don't know what is a good value for this.
-// Real-time audio may be improved with a lower value.
-static timespec g_enqueue_wait_time { 0, 10'000'000 };
-
 ConnectionFromClient::ConnectionFromClient(NonnullOwnPtr<Core::Stream::LocalSocket> socket)
     : IPC::ConnectionToServer<AudioClientEndpoint, AudioServerEndpoint>(*this, move(socket))
+    , m_buffer(make<AudioQueue>(MUST(AudioQueue::try_create())))
+    , m_user_queue(make<UserSampleQueue>())
+    , m_background_audio_enqueuer(Threading::Thread::construct([this]() {
+        // All the background thread does is run an event loop
```
Comment (linusg) [inline Userland/Libraries/LibAudio/ConnectionFromClient.cpp:26]:
```suggestion
        // All the background thread does is run an event loop.
```

File: Userland/Libraries/LibAudio/ConnectionFromClient.cpp [hunk 31]
```diff
@@ -1,48 +1,131 @@
...
+        if (m_user_queue->is_empty()) {
+            dbgln("Reached end of provided audio data, going to sleep");
             break;
-        nanosleep(&g_enqueue_wait_time, nullptr);
+        }
+
+        auto available_samples = min(AUDIO_BUFFER_SIZE, m_user_queue->size());
+        for (size_t i = 0; i < available_samples; ++i) {
+            next_chunk[i] = (*m_user_queue)[i];
+        }
```
Comment (linusg) [inline Userland/Libraries/LibAudio/ConnectionFromClient.cpp:97]: No curly braces needed here

File: Userland/Libraries/LibAudio/UserSampleQueue.h [hunk 32]
```diff
@@ -0,0 +1,50 @@
...
+
+#include <AK/DisjointChunks.h>
+#include <AK/FixedArray.h>
+#include <AK/Format.h>
+#include <AK/Noncopyable.h>
+#include <AK/Vector.h>
+#include <LibAudio/Sample.h>
+#include <LibThreading/Mutex.h>
+
+namespace Audio {
```
Comment (linusg) [inline Userland/Libraries/LibAudio/UserSampleQueue.h:17]: nit: please add a newline around namespaces :)

**Review by linusg — COMMENTED** [review]
Looks nice to my audio-noob eyes, some small comments :^)

File: Userland/Libraries/LibCore/SharedCircularQueue.h [hunk 33]
```diff
@@ -0,0 +1,235 @@
...
+    ALWAYS_INLINE constexpr int fd() const { return m_queue->m_fd; }
+    ALWAYS_INLINE constexpr bool is_valid() const { return !m_queue.is_null(); }
+
+    ALWAYS_INLINE constexpr size_t weak_head() const { return m_queue->m_queue->m_head.load(AK::MemoryOrder::memory_order_relaxed); }
+    ALWAYS_INLINE constexpr size_t weak_tail() const { return m_queue->m_queue->m_tail.load(AK::MemoryOrder::memory_order_relaxed); }
+
+    ErrorOr<void, QueueStatus> try_enqueue(ValueType to_insert)
+    {
+        VERIFY(!m_queue.is_null());
+        // (1)
```
[the remark this answers is not in the document]
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/SharedCircularQueue.h:98]: Ah, they are left over from when I had proper proofs for the functions. Those are gone now so it's not necessary anymore.
