### PR TITLE
LibGUI: Fix debug line causing crash when drag event has no mime data

### LINKED ISSUE #10618: FileManager: Crash upon drag of invalid mime data
Reproduce:

1. Start a drag event with the following code then move the mouse cursor over the desktop.

```cpp
#include <AK/StringBuilder.h>
#include <LibCore/MimeData.h>
#include <LibGUI/Action.h>
#include <LibGUI/Application.h>
#include <LibGUI/BoxLayout.h>
#include <LibGUI/Button.h>
#include <LibGUI/Event.h>
#include <LibGUI/Icon.h>
#include <LibGUI/Label.h>
#include <LibGUI/MessageBox.h>
#include <LibGUI/Menu.h>
#include <LibGUI/Widget.h>
#include <LibGUI/Window.h>
#include <LibGUI/WindowServerConnection.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <ctype.h>

int main([[maybe_unused]] int argc, [[maybe_unused]] char** argv)
{
    auto app = GUI::Application::construct(argc, argv);

    auto window = GUI::Window::construct();

    window->set_title("TestWindowServer");
    window->set_resizable(true);
    window->set_background_color(Color::White);

    window->set_window_type(GUI::WindowType::Normal);
    window->set_fullscreen(false);

    auto& main_widget = window->set_main_widget<GUI::Widget>();
    main_widget.set_fill_with_background_color(true);

    auto& layout = main_widget.set_layout<GUI::VerticalBoxLayout>();
    layout.set_margins({ 4, 4, 4, 4 });

    auto& label = main_widget.add<GUI::Label>();
    label.set_text("Hello friends");

    window->show();

    GUI::WindowServerConnection::the().start_drag("hello friends!", {}, {});  // <-- crash

    return app->exec();
}

```

Comparatively, `FileManager` does not crash with the following valid mime data:

```cpp
    auto m_mime_data = Core::MimeData::construct();
    const AK::Detail::ByteBuffer<32> buf = {};
    m_mime_data->set_data({"text/plain"}, buf);

    GUI::WindowServerConnection::the().start_drag("hello friends!", m_mime_data->all_data(), {});
```

Log:

```
test-windowserver(35:35): Label 0x054a1e20 DRAG ENTER @ [10,78], 
test-windowserver(35:35): Widget 0x054a1a20 DRAG ENTER @ [10,78], 
test-windowserver(35:35): Label 0x054a1e20 DRAG LEAVE
test-windowserver(35:35): Widget 0x054a1a20 DRAG ENTER @ [8,138], 
FileManager (Desktop)(23:23): ASSERTION FAILED: i < m_size
../.././AK/Vector.h:129
[#0 FileManager (Desktop)(23:23)]: Terminating FileManager (Desktop)(23) due to signal 6
test-windowserver(35:35): Widget 0x054a1a20 DRAG LEAVE
[#0 FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x572
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) [clone .localalias] + 0x40e
0xdeadc0de  Kernel::Scheduler::pick_next() [clone .localalias] + 0x12f
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() [clone .localalias] + 0x214
0xdeadc0de  Kernel::Thread::die_if_needed() [clone .localalias] + 0x1bb
0xdeadc0de  syscall_handler + 0x2347
0xdeadc0de  syscall_asm_entry + 0x31
0x9d251345  libc.so: .text + 0x15345
0x9d23d74a  libc.so: .text + 0x174a
0x9d23e1ad  libc.so: .text + 0x21ad
0x26ab7c7f  libgui.so: .text + 0x12c7f
0x2a362531  libcore.so: .text + 0x2a531
0x26ac5f2b  libgui.so: .text + 0x20f2b
0x26bd15b7  libgui.so: .text + 0x12c5b7
0x26bd672c  libgui.so: .text + 0x13172c
0x2a362531  libcore.so: .text + 0x2a531
0x2a34db01  libcore.so: .text + 0x15b01
0x2a34e5ab  libcore.so: .text + 0x165ab
0x26ac4648  libgui.so: .text + 0x1f648
0x37329a13  /bin/FileManager: .text + 0x2a13
0x37329dd8  /bin/FileManager: .text + 0x2dd8

[#0 FinalizerTask(4:4)]: Generating coredump for pid: 23
CrashDaemon(16:16): New coredump file: /tmp/coredump/FileManager (Desktop)_23_1635072180
SystemServer(22:22): Service Desktop has exited with exit code 6
CrashReporter(36:36): Generating backtrace took 5482 ms
CrashReporter(36:36): --- Backtrace for thread #0 (TID 23) ---
CrashReporter(36:36): 0x0ad4e02e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashReporter(36:36): 0x9d251344: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:21 => signal.cpp:34)
CrashReporter(36:36): 0x9d23d749: [libc.so] abort +0x29 (stdlib.cpp:228)
CrashReporter(36:36): 0x9d23e1ac: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
CrashReporter(36:36): 0x26ab7c7e: [libgui.so] GUI::AbstractView::drag_enter_event(GUI::DragEvent&) +0x9e (Vector.h:129 => Vector.h:148 => AbstractView.cpp:757 => AbstractView.cpp:748)
CrashReporter(36:36): 0x2a362530: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashReporter(36:36): 0x26ac5f2a: [libgui.so] GUI::Application::set_drag_hovered_widget_impl(GUI::Widget*, Gfx::Point<int> const&, AK::Vector<AK::String, 0ul>) +0x32a (Application.cpp:282)
CrashReporter(36:36): 0x26bd15b6: [libgui.so] GUI::Window::handle_drag_move_event(GUI::DragEvent&) [clone .localalias] +0x216 (Application.h:77 => Window.cpp:565)
CrashReporter(36:36): 0x26bd672b: [libgui.so] .L5057 +0x9 (Window.cpp:637)
CrashReporter(36:36): 0x2a362530: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashReporter(36:36): 0x2a34db00: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x180 (EventLoop.cpp:412)
CrashReporter(36:36): 0x2a34e5aa: [libcore.so] Core::EventLoop::exec() +0x4a (EventLoop.cpp:369)
CrashReporter(36:36): 0x26ac4647: [libgui.so] GUI::Application::exec() +0x27 (Application.cpp:111)
CrashReporter(36:36): 0x37329a12: [/bin/FileManager] main +0x17e2 (main.cpp:459)
CrashReporter(36:36): 0x37329dd7: [/bin/FileManager] _entry +0x57 (crt0.cpp:45)

```

### PR DESCRIPTION
**Pull request by kemzeb**
Resolves #10618.

Simply put, this is caused by a debug line that calls `Vector::first()` which fails a `VERIFY()` check when its provided an empty vector.

Because of how old this issue is, I had to do the following:

1. Rewrite the reproducible that was provided to the following modern version:
```cpp
#include "LibGUI/ConnectionToWindowServer.h"
#include <AK/StringBuilder.h>
#include <LibCore/MimeData.h>
#include <LibGUI/Action.h>
#include <LibGUI/Application.h>
#include <LibGUI/BoxLayout.h>
#include <LibGUI/Button.h>
#include <LibGUI/Event.h>
#include <LibGUI/Icon.h>
#include <LibGUI/Label.h>
#include <LibGUI/Menu.h>
#include <LibGUI/MessageBox.h>
#include <LibGUI/Widget.h>
#include <LibGUI/Window.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

ErrorOr<int> serenity_main(Main::Arguments args)
{
    auto app = TRY(GUI::Application::create(args));

    auto window = GUI::Window::construct();

    window->set_title("TestWindowServer");
    window->set_resizable(true);
    window->set_window_type(GUI::WindowType::Normal);
    window->set_fullscreen(false);

    auto main_widget = window->set_main_widget<GUI::Widget>();
    main_widget->set_fill_with_background_color(true);

    main_widget->set_layout<GUI::VerticalBoxLayout>();
    auto* layout = main_widget->layout();
    layout->set_margins({ 4, 4, 4, 4 });

    auto& label = main_widget->add<GUI::Label>();
    label.set_text("Hello friends"_string);

    window->show();

    GUI::ConnectionToWindowServer::the().start_drag("hello friends!", {}, {}); // <-- crash

    return app->exec();
}
```
2. Include a `#define DRAG_DEBUG 1` above the `#include`s in `LibGUI/AbstractView.cpp` so that the debug lines can be executed.

3. Modify the following if-statement removing the "is holding primary mouse button" check that was added long after this issue was made:
https://github.com/SerenityOS/serenity/blob/41a3c19cfecd490fb2a14a8365d8ad051c604669/Userland/Services/WindowServer/ConnectionFromClient.cpp#L874-L878

And by doing the above I was able to see the same assertion failure:
```console
. . .
5.322 ClipboardHistory.Applet(39): Unable to load clipboard history: open: No such file or directory (errno=2)
5.816 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 15 blocks to disk
9.536 FileManager (Desktop)(32): VERIFICATION FAILED: i < m_size at ././AK/Vector.h:139
9.538 [FileManager (Desktop)(32:32)]: CRASH: CPU #0 Illegal instruction in userspace
9.538 [#0 FileManager (Desktop)(32:32)]: Exception code: 0000 (isr: 0000)
9.538 [#0 FileManager (Desktop)(32:32)]:     pc=0x0023:0x00000006bd7bac28 rflags=0x0000000000010206
9.538 [#0 FileManager (Desktop)(32:32)]:  stack=0x0000001199b99260
9.538 [#0 FileManager (Desktop)(32:32)]:    rax=0x0000000000000000 rbx=0x00000006bd8992e8 rcx=0x0000001b50ae202b rdx=0x0000001199b99108
9.538 [#0 FileManager (Desktop)(32:32)]:    rbp=0x0000001199b992a0 rsp=0x00000020142dfef0 rsi=0x0000001199b99108 rdi=0x000000000000006e
9.538 [#0 FileManager (Desktop)(32:32)]:     r8=0x000000000000006d  r9=0x0000000000000000 r10=0x000000062735fe78 r11=0x0000000000000212
9.538 [#0 FileManager (Desktop)(32:32)]:    r12=0x0000001199b99380 r13=0x00000006273dee38 r14=0x0000000d198d0830 r15=0x0000000b8da70be0
9.538 [#0 FileManager (Desktop)(32:32)]:    cr0=0x0000000080010013 cr2=0x00000020130a1000 cr3=0x000000000b288000 cr4=0x0000000000340ee0
9.538 [#0 FileManager (Desktop)(32:32)]: 0x00000006bd7bac28  (?)
. . .
```

### CODE REVIEW

File: Userland/Libraries/LibGUI/AbstractView.cpp [hunk 1]
```diff
@@ -791,7 +791,10 @@ void AbstractView::drag_enter_event(DragEvent& event)
     //       We might be able to reduce event traffic by communicating the set of drag-accepting
     //       rects in this widget to the windowing system somehow.
     event.accept();
-    dbgln_if(DRAG_DEBUG, "accepting drag of {}", event.mime_types().first());
+
+    StringBuilder builder;
+    builder.join(',', event.mime_types());
+    dbgln_if(DRAG_DEBUG, "accepting drag of {}", builder.string_view());
```
Comment (trflynn89) [inline Userland/Libraries/LibGUI/AbstractView.cpp:797]: Building this string is wasted effort when `DRAG_DEBUG` is disabled. Since you're just concatenating the mime types, you can instead just pass the whole vector to the `dbgln` call:
```c++
dbgln_if(DRAG_DEBUG, "accepting drag of {}", event.mime_types());
```

Comment (kemzeb) [reply Userland/Libraries/LibGUI/AbstractView.cpp]: I felt icky doing this too, but was not aware printouts can accept data structures. Thanks for the review!

Comment (AtkinsSJ) [reply Userland/Libraries/LibGUI/AbstractView.cpp]: Anything that has a `Formatter<T>` defined can be passed directly to printf-like functions like this.

Alternatively, you can wrap any extra code like this, and it'll be skipped if the debug flag isn't set:
```c++
if constexpr (DRAG_DEBUG) {
    do_this();
    do_that();
    dbgln("accepting drag");
}
```

Comment (kemzeb) [reply Userland/Libraries/LibGUI/AbstractView.cpp]: Makes perfect sense to me; thanks for your insight!
