### PR TITLE
Kernel+Meta: Ignore suboptimal VirtIO configuration type, use longer timeouts for sync VirtIO GPU commands, use non-VGA VirtIO GPU variants when running on macOS

### LINKED ISSUE #17613: Unable to get VirtIO working with QEMU on macOS
Hi, I'm trying to get VirtIO working, however using normal script (with SERENITY_GL=1 SERENITY_SCREENS=1 flags) doesn't work.
QEMU complains about `virtio-vga-gl` not being a valid device name, I tried some other ones like `virtio-gpu-pci` and also changed `SERENITY_QEMU_DISPLAY_DEVICE="virtio-vga,max_outputs=$SERENITY_SCREENS "` to `SERENITY_QEMU_DISPLAY_DEVICE="virtio-gpu,max_outputs=$SERENITY_SCREENS "`, however the best I was able to get is this panic when booting.

```
[init_stage2(1:1)]: ASSERTION FAILED: !is_error()
[init_stage2(1:1)]: ././AK/Error.h:188 in T AK::ErrorOr<T, ErrorType>::release_value_but_fixme_should_propagate_errors() [with T = AK::NonnullOwnPtr<Kernel::IOWindow>; E = AK::Error]
[init_stage2(1:1)]: KERNEL PANIC! :^(
[init_stage2(1:1)]: Aborted
[init_stage2(1:1)]: at ./Kernel/Arch/x86_64/CPU.cpp:35 in void abort()
[init_stage2(1:1)]: Kernel + 0x00000000015c763f  Kernel::__panic(char const*, unsigned int, char const*) +0x16f
[init_stage2(1:1)]: Kernel + 0x00000000015c8b21  abort.localalias +0x38a
[init_stage2(1:1)]: Kernel + 0x00000000015c8797  abort.localalias +0x0
[init_stage2(1:1)]: Kernel + 0x0000000001841aad  Kernel::VirtIO::Device::initialize() [clone .localalias] +0x285d
[init_stage2(1:1)]: Kernel + 0x00000000003ac689  Kernel::VirtIOGraphicsAdapter::initialize() +0x89
[init_stage2(1:1)]: Kernel + 0x00000000003e02ed  Kernel::VirtIOGraphicsAdapter::create(Kernel::PCI::DeviceIdentifier const&) +0x43d
[init_stage2(1:1)]: Kernel + 0x0000000001881632  Kernel::GraphicsManagement::determine_and_initialize_graphics_device(Kernel::PCI::DeviceIdentifier const&) [clone .localalias] +0x712
[init_stage2(1:1)]: Kernel + 0x00000000002f43b2  AK::Function<void (Kernel::PCI::DeviceIdentifier const&)>::CallableWrapper<Kernel::GraphicsManagement::initialize()::{lambda(Kernel::PCI::DeviceIdentifier const&)#2}>::call(Kernel::PCI::DeviceIdentifier const&) +0x2c2
[init_stage2(1:1)]: Kernel + 0x00000000000298ee  Kernel::PCI::Access::fast_enumerate(AK::Function<void (Kernel::PCI::DeviceIdentifier const&)>&) const +0x9ce
[init_stage2(1:1)]: Kernel + 0x0000000000040a21  Kernel::PCI::enumerate(AK::Function<void (Kernel::PCI::DeviceIdentifier const&)>) +0x71
[init_stage2(1:1)]: Kernel + 0x0000000001884606  Kernel::GraphicsManagement::initialize() +0x666
[init_stage2(1:1)]: Kernel + 0x00000000015065f0  Kernel::init_stage2(void*) +0xa40
```

### PR DESCRIPTION
**Pull request by supercomputer7**
It appears that QEMU doesn't have the VirtIO GPU variants that support VGA functionality for macOS. Those variants are not especially important to us, because we don't use any kind of VGA functionality in our kernel anyway. Therefore, for macOS, we could decide to use virtio-gpu-gl-pci and virtio-gpu-pci devices instead.

Fixes #17613.

### CODE REVIEW

File: Kernel/Bus/VirtIO/Device.cpp [hunk 1]
```diff
@@ -113,9 +127,11 @@ UNMAP_AFTER_INIT void Device::initialize()
...
             config.offset = capability.read32(0x8);
             config.length = capability.read32(0xc);
-            // NOTE: Configuration length of zero is an invalid configuration that should be ignored.
-            if (config.length == 0)
-                continue;
+            // NOTE: Configuration length of zero is an invalid configuration.
+            // The VIRTIO_PCI_CAP_PCI_CFG configuration structure has length of 0
+            // but because we ignore that type and all other types should have a length
+            // greater than 0, we should assert in case this condition is not met.
+            VERIFY(config.length != 0);
```
Comment (ADKaster) [inline Kernel/Bus/VirtIO/Device.cpp:134]: This looks like a "bad hardware can panic the kernel" check. I don't think we want this pattern right? What if it's copied somewhere where we can hotplug random devices? I would expect us to be tolerant of bad hardware and reject it rather than panicing.

**Comment by ADKaster** [comment]
Did you test the configuration on macOS, or do you need someone to try it out for you?

**Comment by supercomputer7** [comment]
> Did you test the configuration on macOS, or do you need someone to try it out for you?

I didn't test the configuration on macOS, but I assume that the `virtio-gpu-pci` device exists so there should be no problem. It will be nice if someone can test it for me, but please let's not block this PR for too long until that happens.

File: Kernel/Bus/VirtIO/Device.cpp (hunk 1 above)
Comment (supercomputer7) [reply Kernel/Bus/VirtIO/Device.cpp:134]: Mostly I agree with this, but this is VirtIO hardware so we can fully expect this length to be non-0. If the check fails it's either a new device we try to attach (which means, a developer is writing a new device driver) with a special configuration type we don't know about (which doesn't matter because the developer will need to implement a dozen more things so they will likely see kernel panics in other places), or someone touched this code and did something bad so we get zero-length. Hypervisors that implement VirtIO should technically always specify a valid length except for the VIRTIO_PCI_CAP_PCI_CFG apparently.

For hardware that is not VirtIO, handling edge cases like this is of course required. If people do a blind copy-and-paste of code snippets, we simply should not merge those patches.

I still need to investigate a little bit in the QEMU code so I can come up with a certain conclusion.

**Comment by karolba** [comment]
Tested on ARM macOS:

- Setting `SERENITY_SCREENS` to use `virtio-gpu-pci` devices works correctly, for up to about **6** screens - after that crashes in random places can be observed.
- Setting `SERENITY_GL` doesn't work, but that's as expected, as ARM macOS qemu doesn't have `virtio-gpu-gl-pci`, or any other virtio graphics accellerated output.

**Review by karolba — APPROVED** [review]
