### PR TITLE
Kernel: Fix race causing modifying a Process to fail with a panic

### LINKED ISSUE #8512: Kernel: Panic in Thread::try_create
I noticed this happen while testing #8507. Usually happens after a while of running `loop { test-pthread }`:

```
[#0 test-pthread(50125:50125)]: PV(error) fault in Region(0xc1029f80)[177] at V0xc20b2050
[#0 test-pthread(50125:50125)]: Unrecoverable page fault, write to address V0xc20b2050
[test-pthread(50125:50125)]: CRASH: CPU #0 Page Fault in ring 0
[#0 test-pthread(50125:50125)]: Exception code: 0003 (isr: 0000)
[#0 test-pthread(50125:50125)]:     pc=0008:c04ee4f2 eflags=00010046
[#0 test-pthread(50125:50125)]:  stack=0010:c70999c4
[#0 test-pthread(50125:50125)]:     ds=0010 es=0010 fs=0023 gs=0030
[#0 test-pthread(50125:50125)]:    eax=c20ccaf0 ebx=c0ce6bfc ecx=c20ccaf0 edx=c7099901
[#0 test-pthread(50125:50125)]:    ebp=c7099a2c esp=c70999c4 esi=c20b2000 edi=c20b204c
[#0 test-pthread(50125:50125)]:    cr0=80010013 cr2=c20b2050 cr3=16e98000 cr4=00340ee4
[test-pthread(50125:50125)]: KERNEL PANIC! :^(
[test-pthread(50125:50125)]: Crash in ring 0
[test-pthread(50125:50125)]: at ../../Kernel/Arch/x86/common/Interrupts.cpp:226 in void Kernel::handle_crash(Kernel::RegisterState&, const char*, int, bool)
[#0 test-pthread(50125:50125)]: 0xc04df4dc  Kernel::__panic(char const*, unsigned int, char const*) +0xb0
[#0 test-pthread(50125:50125)]: 0xc0718990  Kernel::handle_crash(Kernel::RegisterState&, char const*, int, bool) +0x250
[#0 test-pthread(50125:50125)]: 0xc0719550  page_fault_handler +0xa1f
[#0 test-pthread(50125:50125)]: 0xc07167d2  page_fault_asm_entry +0x26
[#0 test-pthread(50125:50125)]: 0xc06642cb  Kernel::Thread::Thread(AK::NonnullRefPtr<Kernel::Process>, AK::NonnullOwnPtr<Kernel::Region>, AK::NonnullRefPtr<Kernel::Timer>, Kernel::FPUState*) +0x1c13
[#0 test-pthread(50125:50125)]: 0xc0665b16  Kernel::Thread::try_create(AK::NonnullRefPtr<Kernel::Process>) +0x70a
[#0 test-pthread(50125:50125)]: 0xc0614b18  Kernel::Process::sys$create_thread(void* (*)(void*), AK::Userspace<Kernel::Syscall::SC_create_thread_params const*>) +0x81c
[#0 test-pthread(50125:50125)]: 0xc053a09f  syscall_handler +0x1df2
[#0 test-pthread(50125:50125)]: 0xc05382a3  syscall_asm_entry +0x31
```

### PR DESCRIPTION
**Pull request by tomuta**
The ProtectedDataMutationScope cannot blindly assume that there is only
exactly one thread at a time that may want to unprotect the Process.
Most of the time the big lock guaranteed this, but there are some cases
such as finalization (among others) where this is not necessarily
guaranteed.

This fixes random panics due to access violations when the
ProtectedDataMutationScope protects the Process instance while another
is still modifying it.

Fixes #8512

### CODE REVIEW

File: Kernel/Process.cpp [hunk 1]
```diff
@@ -205,12 +205,59 @@ RefPtr<Process> Process::create_kernel_process(RefPtr<Thread>& first_thread, Str
...
+    u32 desired = (1 << 1) | 1;
+    // Least significant bit indicates we're busy protecting/unprotecting
+    for (;;) {
+        if (m_protected_data_refs.compare_exchange_strong(expected, desired, AK::memory_order_relaxed))
+            break;
+
+        Processor::wait_check();
+
+        expected &= ~1;
+        VERIFY(expected != 0); // Someone should always have at least on reference
```
Comment (gunnarbeutner) [inline Kernel/Process.cpp:218]:
```suggestion
        VERIFY(expected != 0); // Someone should always have at least one reference
```

**Review by gunnarbeutner — CHANGES_REQUESTED** [review]

File: Kernel/Process.cpp [hunk 2]
```diff
@@ -205,12 +205,59 @@ RefPtr<Process> Process::create_kernel_process(RefPtr<Thread>& first_thread, Str
...
+
+        if (expected == 1 << 1)
+            desired = (1 << 1) | 1;
+        else
+            desired = expected - (1 << 1);
+    }
+
+    AK::atomic_thread_fence(AK::memory_order_release);
+
+    if (expected == 1 << 1) {
```
Comment (awesomekling) [inline Kernel/Process.cpp:228]: Can we find a suitable synchronization primitive to do this with some kind of RAII one-liner instead of having to have this huge chunk of code here?

Comment (tomuta) [reply Kernel/Process.cpp:228]: I thought about this too, but couldn't really think of anything. Do you have any suggestions? `RefCountedSpinLockOnFirstRef`? ;-)

**Review by gunnarbeutner — APPROVED** [review]
