### PR TITLE
LibGUI: Fix crash when trying to get selected text after full line and multiline deletes

### LINKED ISSUE #5875: TextEditor: Deleting a selected text line results in a crash
Steps to reproduce:

1. Open a blank document in TextEditor
2. Enter some text (multi line)
3. Select an arbitrary line where the start and end of the selection is on the same line.
4. Delete the text

Cannot reproduce in HackStudio.

image
image

### PR DESCRIPTION
**Pull request by ngc6302h**
Fixes #5875

### CODE REVIEW

File: Userland/Libraries/LibGUI/TextDocument.cpp [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2018-2020, Andreas Kling <kling@serenityos.org>
+ * Copyright (c) 2018-2021, Andreas Kling <kling@serenityos.org>
```
Comment (awesomekling) [inline Userland/Libraries/LibGUI/TextDocument.cpp:2]: Please don't change other people's copyrights. You can add your own instead :)
