### PR TITLE
LibGUI: Fix GDirectoryModel lifetime bug.

### LINKED ISSUE #619: PaintBrush: Open Dialog crashes applications as soon as you leave the dialog.
The open dialog on ~~both TextEditor and~~ PaintBrush crashes the application as soon as you leave the dialog. It doesn't matter if you select OK or Cancel.

```
GFilePicker: quit event loop with result 0
PaintBrush(17): CEventLoop::quit(0)
GFilePicker: event loop returned with result 0
WindowServer(9): Event type 3012 with no receiver :(
PaintBrush(17) Couldn't find user region for V0xedededed
NP(error) fault at invalid address V0xedededed
PaintBrush(17:0) Unrecoverable page fault, read from address 0xedededed
Note: Address 0xedededed looks like it may be recently free()'d memory
CRASH: Page Fault Process: PaintBrush(17)
exception code: 0004
  pc=001b:08059728 ds=0023 es=0023 fs=0023 gs=07d3
 stk=0023:0114fa1c
kstk=0010:c0ab5000, base=c0aa5000
eax=edededed ebx=01155136 ecx=0150ccfe edx=01273112
ebp=0114fa38 esp=0114fa1c esi=0114fa2c edi=0114fa5c
code: 8b 08 ff b2 90 00 00 00
0x08059728  _ZNK2AK8FunctionIFvNS_6RefPtrI14GraphicsBitmapEEEE15CallableWrapperIZN15GDirectoryModel19fetch_thumbnail_forERKNS7_5EntryEEUlT_E0_E4callES3_ +66
0x00020c8b  Process::crash(int, unsigned int) +153
0x0001a4cb  exception_13_handler +0
0x0001a5ca  exception_14_handler +239
0x00019909  exception_14_entry +38
0x0805a815  _ZNK2AK8FunctionIFvR7CObjectEE15CallableWrapperIZZN9LibThread16BackgroundActionINS_6RefPtrI14GraphicsBitmapEEEC4ENS0_IFSA_vEEENS0_IFvSA_EEEENKUlvE_clEvEUlS2_E_E4callES2_ +87
0x0807fe86  _ZN10CEventLoop4pumpENS_8WaitModeE +418
0x08080045  _ZN10CEventLoop4execEv +43
0x0805282d  _ZN12GApplication4execEv +29
0x08048745  main +1040
0x08048aa9  _start +94
Process PaintBrush(17) regions:
BEGIN       END         SIZE        ACCESS  NAME
01001000 -- 0113afff    0013a000    R       /bin/PaintBrush
08048000 -- 080d9fff    00092000    R X     elf-map-rx
080da000 -- 080dcfff    00003000    RW      elf-alloc-rw
0113c000 -- 0113cfff    00001000    RW      (null)
0113e000 -- 0113efff    00001000    RW      Thread-specific
01140000 -- 0114ffff    00010000    RW      Stack (Main thread)
01151000 -- 01151fff    00001000    RW      malloc: BigAllocationBlock
01153000 -- 01153fff    00001000    RW      malloc: ChunkedBlock(1016)
01155000 -- 01155fff    00001000    RW      malloc: ChunkedBlock(16)
01157000 -- 01157fff    00001000    RW      malloc: ChunkedBlock(32)
01159000 -- 01159fff    00001000    RW      malloc: ChunkedBlock(128)
0115b000 -- 0115bfff    00001000    RW      malloc: ChunkedBlock(64)
0115d000 -- 0115dfff    00001000    RW      malloc: ChunkedBlock(8)
0115f000 -- 0115ffff    00001000    RW      malloc: ChunkedBlock(252)
01161000 -- 01161fff    00001000    RW      malloc: BigAllocationBlock
01165000 -- 01165fff    00001000    RW      malloc: ChunkedBlock(508)
01163000 -- 01163fff    00001000    R       SharedBuffer
0116b000 -- 0116dfff    00003000    R       /res/fonts/Katica10.font
0116f000 -- 0116ffff    00001000    RW      GraphicsBitmap [26x26] - Decoded PNG: /res/icons/paintbrush/pen.png
01175000 -- 01175fff    00001000    RW      GraphicsBitmap [26x26] - Decoded PNG: /res/icons/paintbrush/bucket.png
01177000 -- 01177fff    00001000    RW      GraphicsBitmap [26x26] - Decoded PNG: /res/icons/paintbrush/spray.png
0117d000 -- 0117dfff    00001000    RW      GraphicsBitmap [26x26] - Decoded PNG: /res/icons/paintbrush/picker.png
0117f000 -- 0117ffff    00001000    RW      GraphicsBitmap [26x26] - Decoded PNG: /res/icons/paintbrush/eraser.png
0126d000 -- 0126dfff    00001000    RW      malloc: ChunkedBlock(252)
0126f000 -- 0126ffff    00001000    RW      malloc: ChunkedBlock(252)
01277000 -- 01277fff    00001000    R       SharedBuffer
01279000 -- 013a4fff    0012c000    RW      SharedBuffer
013a6000 -- 014d1fff    0012c000    RW      SharedBuffer
01271000 -- 01271fff    00001000    RW      malloc: ChunkedBlock(1016)
01273000 -- 01273fff    00001000    RW      malloc: ChunkedBlock(252)
014d3000 -- 014d3fff    00001000    RW      malloc: ChunkedBlock(2036)
0150c000 -- 0150cfff    00001000    RW      malloc: ChunkedBlock(64)
0152d000 -- 0152dfff    00001000    RW      malloc: ChunkedBlock(32)
01537000 -- 01537fff    00001000    RW      malloc: ChunkedBlock(252)
01555000 -- 01557fff    00003000    R       /res/fonts/KaticaBold10.font
01559000 -- 01559fff    00001000    RW      malloc: BigAllocationBlock
0155b000 -- 0155bfff    00001000    RW      malloc: ChunkedBlock(1016)
01783000 -- 01792fff    00010000    RW      Stack (Thread 1)
01794000 -- 01794fff    00001000    RW      Thread-specific
01796000 -- 01796fff    00001000    RW      malloc: ChunkedBlock(128)
01798000 -- 01798fff    00001000    RW      malloc: ChunkedBlock(64)
0179c000 -- 0179cfff    00001000    RW      malloc: BigAllocationBlock
0179a000 -- 0179afff    00001000    RW      GraphicsBitmap [32x32]
019b1000 -- 019b1fff    00001000    RW      malloc: BigAllocationBlock
019b6000 -- 019b6fff    00001000    RW      malloc: ChunkedBlock(16)
019b8000 -- 019b8fff    00001000    RW      malloc: ChunkedBlock(16)
0179e000 -- 0179efff    00001000    RW      GraphicsBitmap [32x32]
017a0000 -- 017a0fff    00001000    RW      GraphicsBitmap [32x32]
017a2000 -- 017a2fff    00001000    RW      GraphicsBitmap [32x32]
017af000 -- 017affff    00001000    RW      malloc: ChunkedBlock(16)
017b1000 -- 017b1fff    00001000    RW      malloc: ChunkedBlock(16)
017a4000 -- 017a4fff    00001000    RW      GraphicsBitmap [32x32]
017a6000 -- 017a6fff    00001000    RW      GraphicsBitmap [32x32]
017a8000 -- 017a8fff    00001000    RW      GraphicsBitmap [32x32]
017aa000 -- 017aafff    00001000    RW      GraphicsBitmap [32x32]
0150e000 -- 01511fff    00004000    RW      GraphicsBitmap [64x64] - Decoded PNG: /home/anon/png/serenity.png
Finalizing Thread 1 in PaintBrush(17)
~Thread{0x003426a8}
Finalizing Thread 0 in PaintBrush(17)
Finalizing Process PaintBrush(17)
signal: PaintBrush(17) sent 17 to Launcher(13)
Unblock Launcher(13) due to signal
Connection: Client disconnected: 4
WindowServer(9): Event type 3012 with no receiver :(
Launcher(13) Got SIGCHLD
sys$waitpid(-1, 0x00000000, 0)
reap: PaintBrush(17) {Dead}
~Process{0x00331ab8} name=PaintBrush pid=17, m_fds=0
~Thread{0x00334340}
Launcher(13) waitpid() returned 17
CSafeSyscall: -1 (4: Interrupted syscall)
```

### PR DESCRIPTION
**Pull request by xeons**
Thumbnail generation callbacks were getting called after the class was already being disposed of causing a crash to occur.

Let me know if there's a more elegant way to solve this problem.

This should fix #619.

### CODE REVIEW

File: Libraries/LibGUI/GDirectoryModel.cpp [hunk 1]
```diff
@@ -132,6 +134,10 @@ bool GDirectoryModel::fetch_thumbnail_for(const Entry& entry)
         },
 
         [this, path](auto thumbnail) {
+            // this class is disposing, we shouldn't attempt anything.
+            if (m_disposing)
```
Comment (awesomekling) [inline Libraries/LibGUI/GDirectoryModel.cpp]: This is still buggy, since the object the captured `this` points to may have been deleted entirely and so it's not safe to read from `m_disposing`.
Perhaps we could make the destructor of `GDirectoryView` proactively orphan any pending thumbnailing jobs it has scheduled. That way, when they eventually finish, they'll still go into the thumbnail cache, but we'll know not to invoke any callbacks.

Comment (xeons) [reply Libraries/LibGUI/GDirectoryModel.cpp]: I'm not sure how to go about doing that.  Would I need to extend BackgroundAction in some way?

**Comment by bugaevc** [comment]
It's not really a threading bug, it's a lifetime issue.

The way you work around this is you make `GDirectoryModel` weakable and then have the action capture a weak ref to it, then when you want to use it see if it still exists and exit otherwise.

**Comment by xeons** [comment]
> It's not really a threading bug, it's a lifetime issue.
> 
> The way you work around this is you make `GDirectoryModel` weakable and then have the action capture a weak ref to it, then when you want to use it see if it still exists and exit otherwise.

I'll try doing this when I get home, I think i see what to do.

**Comment by xeons** [comment]
Making GDirectoryModel weakable and feeding that into the action worked. I also allow it to still populate the thumbnail cache.

**Comment by awesomekling** [comment]
Nice!
