### PR TITLE
LibGUI: Improve responseiveness when generating lots of thumbnails

### LINKED ISSUE #20906: File Manager: slow and unresponsive in directories with many thumbnails.
### Problem

File Manager becomes slow and unresponsive when opening directories with many thumbnails.

### Steps to reproduce

1. Open `/res/emoji` in File Manager
2. A loading bar will appear at the bottom mentioning that thumbnails are being generated.
3. The log will mention the following.

```
11.965 FileManager(45:45): Started Thread "Background Thread"(46)
12.040 FileManager(45:45): ThreadEventQueue::process: Job queue wasn't designed for this load (1858 promises)
```

4. The entire system will become slow and unresponsive and may even turn the cursor into a sand timer.

### Possible solutions

1. Thumbnails could be generated more lazily rather than dumping a load of tasks on to the event queue.
2. Batching jobs could help with the load, although eventually it would suffer too at larger scales.

Lazy loading thumbnails is probably sensible as other OSes appear to do so. This has some visual artefacts such as thumbnails not loading immediately when the user scrolls. Therefore we can play some more clever tricks such as loading at least 3 pages worth of thumbnails relative to the scroll position.

One thing is for certain, we shouldn't be generating every single thumbnail immediately as this does not scale well at all!

### PR DESCRIPTION
**Pull request by tcl3**
Instead of updating the UI after each thumbnail is generated, we now only update the UI every 100ms. This improves the responsiveness of FileManager when navigating directories with lots of small thumbnails.

There are still opportunities to improve performance further here, but this change at least makes `/res/emoji` navigable, whereas previously it would lock up the system for a significant amount of time.

Demo (from a cold reboot):

https://github.com/SerenityOS/serenity/assets/2817754/75d449b8-5e69-413c-933b-2cff403834e3

Fixes #20906

### CODE REVIEW

File: Userland/Libraries/LibGUI/FileSystemModel.cpp [hunk 1]
```diff
@@ -718,17 +718,24 @@ bool FileSystemModel::fetch_thumbnail_for(Node const& node)
                 strong_this->m_thumbnail_progress_total = 0;
             }
 
-            if (with_success)
+            if (with_success && (!strong_this->m_ui_update_timer.is_valid() || strong_this->m_ui_update_timer.elapsed_time() > 50_ms)) {
```
Comment (awesomekling) [inline Userland/Libraries/LibGUI/FileSystemModel.cpp:721]: We've got 50ms here, but the commit message says 100ms?

Comment (tcl3) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp]: Oops, I've set it to 100ms; that's what I used in the video and I couldn't see a massive difference between 50 and 100ms. That number is kind of pulled out of the air though, so happy to change it if there is a more principled value.

**Comment by Alizter** [comment]
Good job and thanks!
