### PR TITLE
LibJS: Fix Object::delete_property() with numeric string property 

### LINKED ISSUE #3950: LibJS: is_number() assertion failed in Object::delete_property
Found with Fuzzilli.

Code:
```js
function main() {
const v3 = [13.37];
const v4 = [65537,v3,13.37,65537,Boolean,65537,13.37];
for (const v5 in v4) {
    delete Boolean[v5];
}
}
main();
// Stderr:
// FuzzJs: ../Libraries/LibJS/Runtime/PropertyName.h:111: i32 JS::PropertyName::as_number() const: Assertion `is_number()' failed.
```

Trace:
```
USERSPACE(24) ASSERTION FAILED: is_number()
../Libraries/LibJS/Runtime/PropertyName.h:111
[js(24:24)]: Terminating js(24) due to signal 6
[FinalizerTask(3:3)]: CPU[0] NP(error) fault at invalid address V0x01301d6c
[FinalizerTask(3:3)]: copy_from_user(0xc094a9ac, 0x01301d6c, 4) failed at V0x01301d6c
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +181
0xdeadc0de  Kernel::Scheduler::pick_next() +1965
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x080c3cce  raise +22
0x080480bd   +13
0x080bfaf1  tolower +0
0x08087a2f  JS::PropertyName::as_number() const +27
0x08087785  JS::Object::delete_property(JS::PropertyName const&) +161
0x0805b555  JS::UnaryExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +207
0x0805a0b6  JS::ExpressionStatement::execute(JS::Interpreter&, JS::GlobalObject&) const +44
0x080668e9  JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, AK::Vector<JS::Argument, 8ul>, JS::ScopeType) +455
0x08060721  JS::ForInStatement::execute(JS::Interpreter&, JS::GlobalObject&) const +649
0x080668e9  JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, AK::Vector<JS::Argument, 8ul>, JS::ScopeType) +455
0x0808f516  JS::ScriptFunction::call() +1448
0x08096229  JS::VM::call_internal(JS::Function&, JS::Value, AK::Optional<JS::MarkedValueList>) +495
0x0805e8ca  JS::CallExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +2340
0x0805a0b6  JS::ExpressionStatement::execute(JS::Interpreter&, JS::GlobalObject&) const +44
0x080668e9  JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, AK::Vector<JS::Argument, 8ul>, JS::ScopeType) +455
0x0805d57a  JS::Program::execute(JS::Interpreter&, JS::GlobalObject&) const +64
0x08066d35  JS::Interpreter::run(JS::GlobalObject&, JS::Program const&) +407
0x0804b4d3  parse_and_run(JS::Interpreter&, AK::StringView const&) +467
0x08048df5  main +2310
0x08049ace  _start +94
```

### PR DESCRIPTION
**Pull request by linusg**
- We have to check if the property name is a string before calling `as_string()` on it
- We can't `as_number()` the same property name but have to use the parsed index number

Fixes #3950.

### CODE REVIEW

File: Libraries/LibJS/Runtime/Object.cpp [hunk 1]
```diff
@@ -631,9 +631,12 @@ Value Object::delete_property(const PropertyName& property_name)
 
     if (property_name.is_number())
         return Value(m_indexed_properties.remove(property_name.as_number()));
-    int property_index = property_name.as_string().to_int().value_or(-1);
-    if (property_index >= 0)
-        return Value(m_indexed_properties.remove(property_name.as_number()));
+
+    if (property_name.is_string()) {
+        i32 property_index = property_name.as_string().to_int().value_or(-1);
```
Comment (awesomekling) [inline Libraries/LibJS/Runtime/Object.cpp:636]: Hmm. Perhaps it would be better to check when constructing a `PropertyName` from a string if the string is in fact a number, and if so, turning into a numeric `PropertyName`. Then we wouldn't have to worry about this sort of logic when using a `PropertyName`.

What do you think?

Comment (linusg) [reply Libraries/LibJS/Runtime/Object.cpp:636]: Nice idea, and I briefly tried it, but it made other things fall apart. Let's do this separately.
