### PR TITLE
LibWeb: Handle overlapping floating box and left margin

### LINKED ISSUE #20233: LibWeb: Wrong layout for boxes which create a BFC with left margin and sibling floating boxes to the left
For the following input:

```
<style>
    .a {
        float: left;
    }

    .a4 {
        display: block;
    }

    .c {
        overflow: hidden;
    }
</style>

<div>
    <div>
        <div class="a">
            <div class="a4">AAAA</div>
            <div>A</div>
        </div>
    </div>
    <div style="margin-left: 100px">
        <div>B</div>
        <div class="c">C</div>
    </div>
</div>
```

we render:
before

However, other browsers render:
ref

### PR DESCRIPTION
**Pull request by axgallo**
Allow the left margin of a box which creates a block formatting context to overlap with left floating boxes which are siblings in the document tree.

Fixes #20233 and the comment layout on https://lobste.rs.

### CODE REVIEW

**Comment by axgallo** [comment]
Before:
lobsters_before

After:
lobsters_after

File: Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp [hunk 1]
```diff
@@ -802,6 +802,18 @@ void BlockFormattingContext::place_block_level_element_in_normal_flow_vertically
     box_state.set_content_offset(CSSPixelPoint { box_state.offset.x(), y });
 }
 
+// Returns whether the given box has the given ancestor on the path to root, ignoring the anonymous blocks.
+static bool box_has_ancestor(Box const* box, Box const* ancestor, Box const* root)
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:806]: Feels like `box_has_ancestor` hides the fact that this only considers non-anonymous containing blocks.
Perhaps something more explicit, like `box_has_ancestor_in_non_anonymous_containing_block_chain()`?
Also, if a parameter can't be null, please use a reference type, i.e `Box const&` instead of `Box const*` :)

File: Userland/Libraries/LibWeb/Layout/FormattingContext.h [hunk 2]
```diff
@@ -121,6 +121,7 @@ class FormattingContext {
         // Each block in the containing chain adds its own margin and we store the total here.
         CSSPixels left_total_containing_margin;
         CSSPixels right_total_containing_margin;
+        Box const* matching_left_float_box { nullptr };
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/Layout/FormattingContext.h:124]: No corresponding logic is required for right-side floats?

Comment (axgallo) [reply Userland/Libraries/LibWeb/Layout/FormattingContext.h:124]: Good question, I don't think it's required since the right floats don't affect the offset. There might be a related bug affecting the available space instead, but I couldn't come up with an example.

File: Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp (hunk 1 above)
Comment (axgallo) [reply Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp]: Sounds good, done.
