### PR TITLE
WebP/Lossy: Add support for images with more than one partition

### LINKED ISSUE #19149: support for multi-partition lossy webp images
Lossy webp supports splitting macroblock coefficients into multiple independent partitions: https://datatracker.ietf.org/doc/html/rfc6386#section-9.5

This is currently not implemented.

I've never seen a multi-partition file in the wild, and they seem to be hard to create.

In `https://github.com/webmproject/libwebp/commit/f61d14aabfd35d004d`, the help text of `cwebp` had a `-partitions` flag, but it wasn't hooked up to anything.

https://github.com/webmproject/libwebp/commit/2e3e8b2ef5d2e7d removed the flag from the help text again.

As far as I can tell, there's no way to create a multi-partition webp file with `cwebp` as-is.

But libwebp definitely has code for it, and programs using its API can create such files. And it's part of the spec, so we should implement it for completionism.

This adds a flag to `cwebp` to create multi-partition files:

```diff
diff --git a/examples/cwebp.c b/examples/cwebp.c
index 9adb31ec..c2ed60c9 100644
--- a/examples/cwebp.c
+++ b/examples/cwebp.c
@@ -569,6 +569,7 @@ static void HelpLong(void) {
   printf("                           "
          "the first partition (0=no degradation ... 100=full)\n");
   printf("  -pass <int> ............ analysis pass number (1..10)\n");
+  printf("  -partitions <int> ...... number of partitions to use (0..3)\n");
   printf("  -qrange <min> <max> .... specifies the permissible quality range\n"
          "                           (default: 0 100)\n");
   printf("  -crop <x> <y> <w> <h> .. crop picture with the given rectangle\n");
@@ -704,6 +705,8 @@ int main(int argc, const char* argv[]) {
     } else if (!strcmp(argv[c], "-d") && c + 1 < argc) {
       dump_file = (const char*)GET_WARGV(argv, ++c);
       config.show_compressed = 1;
+    } else if (!strcmp(argv[c], "-partitions") && c + 1 < argc) {
+      config.partitions = ExUtilGetInt(argv[++c], 0, &parse_error);
     } else if (!strcmp(argv[c], "-print_psnr")) {
       config.show_compressed = 1;
       print_distortion = 0;
```

It's then possible to create such a file:

```sh
% examples/cwebp -low_memory -partitions 1 ~/src/serenity/Tests/LibGfx/test-inputs/extended-lossless.webp -o foo.webp
```

(`-low_memory` is needed because otherwise `src/enc/webp_enc.c` does:

```c
    if (enc->use_tokens_) {
      enc->num_parts_ = 1;   // doesn't work with multi-partition
    }
```

See also https://github.com/webmproject/libwebp/commit/9bfbdd144)

And with that file:

```sh
% time Build/lagom/image ~/src/libwebp/foo.webp  -o tmp.png
Runtime error: WebPImageDecoderPlugin: decoding lossy webps with more than one dct partition not yet implemented
```

(mostly as note-to-self, so I have a place to dump a few things.)

### PR DESCRIPTION
**Pull request by nico**
Each secondary partition has an independent BooleanDecoder. Their bitstreams interleave per macroblock row, that is the first macroblock row is read from the first decoder, the second from the second, ..., until it wraps around again.

All partitions share a single prediction state though: The second macroblock row (which reads coefficients off the second decoder) is predicted using the result of decoding the frist macroblock row (which reads coefficients off the first decoder).

So if I understand things right, in theory the coefficient reading could be parallelized, but prediction can't be. (IDCT can also be parallelized, but that's true with just a single partition too.)

I created the test image by running

    examples/cwebp -low_memory -partitions 3 -o foo.webp \
        ~/src/serenity/Tests/LibGfx/test-inputs/4.webp

using a cwebp hacked up as described in #19149. Since creating multi-partition lossy webps requires hacking up `cwebp`, they're likely very rare in practice. (But maybe other programs using the libwebp API create them.)

Fixes #19149.

With this, webp lossy support is complete (*) :^)

And with that, webp support is complete: Lossless, lossy, lossy with alpha, animated lossless, animated lossy, animated lossy with alpha all work.

(*: Loop filtering isn't implemented yet, which has a minor visual effect on the output. But it's only visible when carefully comparing a webp decoded without loop filtering to the same decoded with it. But it's technically a part of the spec that's still missing.

The upsampling of UV in the YUV->RGB code is also low-quality. This produces somewhat visible banding in practice in some images (e.g. in the fire breather's face in 5.webp), so we should probably improve that at some point. Our JPG decoder has the same issue.)

### CODE REVIEW

File: Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp [hunk 1]
```diff
@@ -1223,6 +1230,40 @@ ErrorOr<void> decode_VP8_image_data(Gfx::Bitmap& bitmap, FrameHeader const& head
...
+{
+    Vector<ReadonlyBytes> data_partitions;
+    // https://datatracker.ietf.org/doc/html/rfc6386#section-9.5 "Token Partition and Partition Data Offsets"
+    // "If the number of data partitions is
+    //  greater than 1, the size of each partition (except the last) is
+    //  written in 3 bytes (24 bits).  The size of the last partition is the
+    //  remainder of the data not used by any of the previous partitions.
+    //  The partitioned data are consecutive in the bitstream, so the size
+    //  can also be used to calculate the offset of each partition."
+    // In practice, virtually all lossy webp files have a since data partition.
```
Comment (Zaggy1024) [inline Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp:1243]: > since

single?

File: Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp [hunk 2]
```diff
@@ -1245,13 +1286,11 @@ ErrorOr<NonnullRefPtr<Bitmap>> decode_webp_chunk_VP8_contents(VP8Header const& v
...
     // Done with the first partition!
 
-    if (header.number_of_dct_partitions > 1)
-        return Error::from_string_literal("WebPImageDecoderPlugin: decoding lossy webps with more than one dct partition not yet implemented");
-
     auto bitmap_format = include_alpha_channel ? BitmapFormat::BGRA8888 : BitmapFormat::BGRx8888;
     auto bitmap = TRY(Bitmap::create(bitmap_format, { macroblock_width * 16, macroblock_height * 16 }));
 
-    TRY(decode_VP8_image_data(*bitmap, header, vp8_header.second_partition, macroblock_width, macroblock_height, macroblock_metadata));
+    auto data_partitions = TRY(split_data_partitions(vp8_header.second_partition, header.number_of_dct_partitions));
```
Comment (Zaggy1024) [inline Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp:1292]: Bit of a nitpick, but perhaps `second_partition` should be called `secondary_partitions` or similar to indicate that it contains multiple partitions?

**Review by Zaggy1024 — CHANGES_REQUESTED** [review]
Some nitpicks, but overall looks good to me!

File: Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp (hunk 2 above)
Comment (nico) [reply Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp:1292]: The spec alls it "second partition" :/

File: Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp [hunk 3]
```diff
@@ -1223,6 +1230,40 @@ ErrorOr<void> decode_VP8_image_data(Gfx::Bitmap& bitmap, FrameHeader const& head
     return {};
 }
 
+static ErrorOr<Vector<ReadonlyBytes>> split_data_partitions(ReadonlyBytes second_partition, u8 number_of_dct_partitions)
+{
+    Vector<ReadonlyBytes> data_partitions;
```
[the remark this answers is not in the document]
Comment (nico) [reply Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp:1235]: Eh, it's at most 8 entries and almost always 1 entry. There are bigger performance worries than the handful of allocations we need for this :)

File: Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp (hunk 2 above)
Comment (Zaggy1024) [reply Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp:1292]: Ah, looking back at this, it seems like I misunderstood that `second_partition` was referring to all the DCT token partitions, including the first.

**Review by Zaggy1024 — APPROVED** [review]
