### PR TITLE
Meta: Add clang-19 support to compiler detection

### LINKED ISSUE #25123: clang19 not work
https://github.com/SerenityOS/serenity/blob/61f6c6c9664f417964414a8642e55e953ac824ce/Meta/find_compiler.sh#L59

### PR DESCRIPTION
**Pull request by Sujit-Hiwale**
Extended the compiler detection logic by adding clang-19 support.
This allows the build system to correctly locate and use clang-19 and aligns with the logic for clang-17 and 18.
This also fixes #25123.

### CODE REVIEW

File: Meta/find_compiler.sh [hunk 1]
```diff
@@ -56,7 +56,7 @@ pick_host_compiler() {
         return
     fi
 
-    find_newest_compiler clang clang-17 clang-18 /opt/homebrew/opt/llvm/bin/clang
+    find_newest_compiler clang clang-19 clang-17 clang-18 /opt/homebrew/opt/llvm/bin/clang
```
Comment (LucasChollet) [inline Meta/find_compiler.sh]: Let's use `clang-{17..19}` or maybe even `clang-{17..21}`

Comment (Sujit-Hiwale) [reply Meta/find_compiler.sh]: Thanks for the suggestion.
I'll update it using `clang-{17..21}`.

Comment (LucasChollet) [reply Meta/find_compiler.sh]: We use a rebase workflow in this project, so please add my suggestion to the first commit and drop the second one.

In the end, you should have a single commit that adds support for all the new versions with an updated commit message.

If you have any issue while doing so, don't hesitate to ask questions on discord.

Comment (Sujit-Hiwale) [reply Meta/find_compiler.sh]: I added the second commit into the first one and dropped the second one.
Now it is showing only one commit in the branch,

```
(base) sujit@sujit:~/Desktop/serenity$ git log --oneline master..add-clang19-support
1ff6e126ee (HEAD -> add-clang19-support, origin/add-clang19-support) Meta: Expand compiler detection to clang 17–21
```

**Comment by nico** [comment]
Thanks!
