### PR TITLE
LibWeb: More animation fixes

### LINKED ISSUE #23471: Ladybird: apple.com crash in interpolate_transform
Opening https://apple.com no longer works. Instead I get this stack trace:

```
1638131.070 RequestServer(90037): Loaded 145 of 145 (100%) provided CA Certificates
1638131.072 WebSocket(90038): Loaded 145 of 145 (100%) provided CA Certificates
1638132.115 WebContent(90036): Potential FIXME: Creating unknown generic element 'animate' in namespace 'http://www.w3.org/2000/svg'
1638132.115 WebContent(90036): Potential FIXME: Creating unknown generic element 'animate' in namespace 'http://www.w3.org/2000/svg'
1638132.115 WebContent(90036): Potential FIXME: Creating unknown generic element 'animate' in namespace 'http://www.w3.org/2000/svg'
1638132.115 WebContent(90036): Potential FIXME: Creating unknown generic element 'animate' in namespace 'http://www.w3.org/2000/svg'
1638133.712 WebContent(90036): Can't keep up! Skipping approximately 11 iteration(s) of a reloading timer (delayed by 168ms).
1638134.056 WebContent(90036): Can't keep up! Skipping approximately 14 iteration(s) of a reloading timer (delayed by 223ms).
1638134.056 WebContent(90036): Can't keep up! Skipping approximately 14 iteration(s) of a reloading timer (delayed by 221ms).
1638134.442 WebContent(90036): Can't keep up! Skipping approximately 23 iteration(s) of a reloading timer (delayed by 352ms).
VERIFICATION FAILED: value.is_value_list() at /Users/nico/Documents/Dev/serenity/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:824
0   liblagom-ak.0.0.0.dylib             0x0000000104d39a48 ak_verification_failed + 216
1   liblagom-web.0.0.0.dylib            0x0000000105fea794 Web::CSS::interpolate_transform(Web::DOM::Element&, Web::CSS::StyleValue const&, Web::CSS::StyleValue const&, float)::$_29::operator()(Web::DOM::Element&, Web::CSS::StyleValue const&) const + 732
2   liblagom-web.0.0.0.dylib            0x0000000105fe0768 Web::CSS::StyleComputer::collect_animation_into(JS::NonnullGCPtr<Web::Animations::KeyframeEffect>, Web::CSS::StyleProperties&) const + 1560
3   liblagom-web.0.0.0.dylib            0x0000000105fe26d0 Web::CSS::StyleComputer::compute_cascaded_values(Web::CSS::StyleProperties&, Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>, bool&, Web::CSS::StyleComputer::ComputeStyleMode) const + 2904
4   liblagom-web.0.0.0.dylib            0x0000000105fe7f60 Web::CSS::StyleComputer::compute_style_impl(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>, Web::CSS::StyleComputer::ComputeStyleMode) const + 640
5   liblagom-web.0.0.0.dylib            0x0000000105fe7c5c Web::CSS::StyleComputer::compute_style(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>) const + 76
6   liblagom-web.0.0.0.dylib            0x000000010605301c Web::DOM::Element::recompute_style() + 108
7   liblagom-web.0.0.0.dylib            0x0000000106033e18 Web::DOM::update_style_recursively(Web::DOM::Node&) + 60
8   liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
9   liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
10  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
11  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
12  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
13  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
14  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
15  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
16  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
17  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
18  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
19  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
20  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
21  liblagom-web.0.0.0.dylib            0x0000000106033f24 Web::DOM::update_style_recursively(Web::DOM::Node&) + 328
22  liblagom-web.0.0.0.dylib            0x0000000106033278 Web::DOM::Document::update_style() + 132
23  liblagom-web.0.0.0.dylib            0x0000000106032d60 Web::DOM::Document::update_layout() + 148
24  liblagom-web.0.0.0.dylib            0x0000000105fd62c0 Web::CSS::ResolvedCSSStyleDeclaration::property(Web::CSS::PropertyID) const + 100
25  liblagom-web.0.0.0.dylib            0x0000000105f6d790 Web::CSS::CSSStyleDeclaration::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*) const + 632
26  liblagom-js.0.0.0.dylib             0x0000000105269a38 JS::Bytecode::get_by_id(JS::VM&, AK::DeprecatedFlyString const&, JS::Value, JS::Value, JS::Bytecode::PropertyLookupCache&) + 732
27  liblagom-js.0.0.0.dylib             0x00000001052695ec JS::Bytecode::Op::GetById::execute_impl(JS::Bytecode::Interpreter&) const + 248
28  liblagom-js.0.0.0.dylib             0x0000000105253d10 JS::Bytecode::Interpreter::run_bytecode() + 3664
29  liblagom-js.0.0.0.dylib             0x0000000105252a1c JS::Bytecode::Interpreter::run_and_return_frame(JS::Bytecode::Executable&, JS::Bytecode::BasicBlock const*, JS::Bytecode::CallFrame*) + 444
30  liblagom-js.0.0.0.dylib             0x000000010536232c JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() + 1152
31  liblagom-js.0.0.0.dylib             0x0000000105361778 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) + 328
32  liblagom-js.0.0.0.dylib             0x000000010537953c JS::FunctionPrototype::call(JS::VM&) + 324
33  liblagom-js.0.0.0.dylib             0x0000000105405d58 AK::Function<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::operator()(JS::VM&) const + 84
34  liblagom-js.0.0.0.dylib             0x000000010540588c JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) + 364
35  liblagom-js.0.0.0.dylib             0x000000010526d220 JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) + 312
36  liblagom-js.0.0.0.dylib             0x000000010526d61c JS::Bytecode::Op::CallWithArgumentArray::execute_impl(JS::Bytecode::Interpreter&) const + 472
37  liblagom-js.0.0.0.dylib             0x0000000105253ba0 JS::Bytecode::Interpreter::run_bytecode() + 3296
38  liblagom-js.0.0.0.dylib             0x0000000105252a1c JS::Bytecode::Interpreter::run_and_return_frame(JS::Bytecode::Executable&, JS::Bytecode::BasicBlock const*, JS::Bytecode::CallFrame*) + 444
39  liblagom-js.0.0.0.dylib             0x000000010536232c JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() + 1152
40  liblagom-js.0.0.0.dylib             0x0000000105361778 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) + 328
41  liblagom-js.0.0.0.dylib             0x000000010526d220 JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) + 312
42  liblagom-js.0.0.0.dylib             0x000000010526d61c JS::Bytecode::Op::CallWithArgumentArray::execute_impl(JS::Bytecode::Interpreter&) const + 472
43  liblagom-js.0.0.0.dylib             0x0000000105253ba0 JS::Bytecode::Interpreter::run_bytecode() + 3296
44  liblagom-js.0.0.0.dylib             0x0000000105252a1c JS::Bytecode::Interpreter::run_and_return_frame(JS::Bytecode::Executable&, JS::Bytecode::BasicBlock const*, JS::Bytecode::CallFrame*) + 444
45  liblagom-js.0.0.0.dylib             0x000000010536232c JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() + 1152
46  liblagom-js.0.0.0.dylib             0x0000000105361778 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) + 328
47  liblagom-js.0.0.0.dylib             0x000000010526d220 JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) + 312
48  liblagom-js.0.0.0.dylib             0x000000010526c734 JS::Bytecode::Op::Call::execute_impl(JS::Bytecode::Interpreter&) const + 768
49  liblagom-js.0.0.0.dylib             0x0000000105253b8c JS::Bytecode::Interpreter::run_bytecode() + 3276
50  liblagom-js.0.0.0.dylib             0x0000000105252a1c JS::Bytecode::Interpreter::run_and_return_frame(JS::Bytecode::Executable&, JS::Bytecode::BasicBlock const*, JS::Bytecode::CallFrame*) + 444
51  liblagom-js.0.0.0.dylib             0x000000010536232c JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() + 1152
52  liblagom-js.0.0.0.dylib             0x0000000105361778 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) + 328
53  liblagom-web.0.0.0.dylib            0x000000010638c878 Web::WebIDL::invoke_callback(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, JS::MarkedVector<JS::Value, 0ul>) + 284
54  liblagom-web.0.0.0.dylib            0x0000000106234b64 JS::Completion Web::WebIDL::invoke_callback<JS::Value>(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, JS::Value&&) + 352
55  liblagom-web.0.0.0.dylib            0x00000001062348d8 AK::Function<void (int)>::CallableWrapper<Web::HTML::Window::request_animation_frame(Web::WebIDL::CallbackType&)::$_8>::call(int) + 128
56  liblagom-web.0.0.0.dylib            0x00000001062318a8 AK::Function<void (int)>::operator()(int) const + 84
57  liblagom-web.0.0.0.dylib            0x000000010622a1b0 Web::HTML::run_animation_frame_callbacks(Web::DOM::Document&, double) + 132
58  liblagom-web.0.0.0.dylib            0x0000000106123568 Web::HTML::EventLoop::process() + 628
59  liblagom-web.0.0.0.dylib            0x00000001063138dc AK::Function<void ()>::CallableWrapper<Web::Platform::TimerSerenity::TimerSerenity()::$_0>::call() + 88
60  liblagom-core.0.0.0.dylib           0x0000000104cc2800 AK::Function<void ()>::operator()() const + 84
61  liblagom-core.0.0.0.dylib           0x0000000104cc1ccc Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) + 112
62  liblagom-core.0.0.0.dylib           0x0000000104cdcc7c Core::ThreadEventQueue::process() + 452
63  liblagom-core.0.0.0.dylib           0x0000000104cbb49c Core::EventLoop::spin_until(AK::Function<bool ()>) + 124
64  liblagom-web.0.0.0.dylib            0x00000001063129c0 Web::Platform::EventLoopPluginSerenity::spin_until(JS::SafeFunction<bool ()>) + 184
65  liblagom-web.0.0.0.dylib            0x00000001061231b8 Web::HTML::EventLoop::spin_until(JS::SafeFunction<bool ()>) + 216
66  liblagom-web.0.0.0.dylib            0x00000001061cdba8 Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) + 892
67  liblagom-web.0.0.0.dylib            0x00000001061c5fc8 Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 392
68  liblagom-web.0.0.0.dylib            0x00000001061c72ac Web::HTML::HTMLParser::run(AK::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 236
69  liblagom-web.0.0.0.dylib            0x000000010604dd74 JS::SafeFunction<void (AK::Detail::ByteBuffer<32ul>)>::CallableWrapper<Web::load_html_document(Web::HTML::NavigationParams&)::$_1>::call(AK::Detail::ByteBuffer<32ul>) + 128
70  liblagom-web.0.0.0.dylib            0x00000001060d10c4 JS::SafeFunction<void (AK::Detail::ByteBuffer<32ul>)>::operator()(AK::Detail::ByteBuffer<32ul>) const + 184
71  liblagom-web.0.0.0.dylib            0x00000001060d0eac JS::SafeFunction<void ()>::CallableWrapper<Web::Fetch::Infrastructure::Body::fully_read(JS::Realm&, JS::SafeFunction<void (AK::Detail::ByteBuffer<32ul>)>, JS::SafeFunction<void (JS::GCPtr<Web::WebIDL::DOMException>)>, AK::Variant<AK::Empty, JS::NonnullGCPtr<JS::Object>>) const::$_0::operator()(AK::Detail::ByteBuffer<32ul> const&)::'lambda'()>::call() + 60
72  liblagom-web.0.0.0.dylib            0x00000001061250f8 Web::HTML::Task::execute() + 92
73  liblagom-web.0.0.0.dylib            0x0000000106123344 Web::HTML::EventLoop::process() + 80
74  liblagom-web.0.0.0.dylib            0x00000001063138dc AK::Function<void ()>::CallableWrapper<Web::Platform::TimerSerenity::TimerSerenity()::$_0>::call() + 88
75  liblagom-core.0.0.0.dylib           0x0000000104cc2800 AK::Function<void ()>::operator()() const + 84
76  liblagom-core.0.0.0.dylib           0x0000000104cc1ccc Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) + 112
77  liblagom-core.0.0.0.dylib           0x0000000104cdcc7c Core::ThreadEventQueue::process() + 452
78  liblagom-core.0.0.0.dylib           0x0000000104cbc660 Core::EventLoopImplementationUnix::exec() + 44
79  liblagom-core.0.0.0.dylib           0x0000000104cbb3a0 Core::EventLoop::exec() + 80
80  WebContent                          0x0000000104249b54 serenity_main(Main::Arguments) + 3280
81  WebContent                          0x00000001042db904 main + 216
82  dyld                                0x000000018c2690e0 start + 2360
```

### LINKED ISSUE #23473: LibWeb: Style computer should never fail
We should never fail to compute style for an element.
If a property is somehow invalid, we should not abort style computation.
Basically all use of `ErrorOr` and `TRY` in `StyleComputer` is wrong or at least misused.

As an example, https://twinings.co.uk/ crashes (after a while) right now because some animated CSS transform has an invalid value.

cc @mattco98 @kalenikaliaksandr

### PR DESCRIPTION
**Pull request by mattco98**
Fixes #23473, fixes #23471. Also fixes an overly-excited button on [shopify.com](https://shopify.com) (the hover animation was blinking on and off). Note that it uses transitions to animate on hover, so the fact that it now no longer animates at all is expected.

### CODE REVIEW

File: Userland/Libraries/LibWeb/CSS/StyleComputer.cpp [hunk 1]
```diff
@@ -1335,9 +1333,14 @@ void StyleComputer::collect_animation_into(JS::NonnullGCPtr<Animations::Keyframe
...
-        dbgln_if(LIBWEB_CSS_ANIMATION_DEBUG, "Interpolated value for property {} at {}: {} -> {} = {}", string_from_property_id(it.key), progress_in_keyframe, start->to_string(), end->to_string(), next_value->to_string());
-        style_properties.set_property(it.key, next_value);
+        if (auto next_value = interpolate_property(*effect->target(), it.key, *start, *end, progress_in_keyframe)) {
+            dbgln_if(LIBWEB_CSS_ANIMATION_DEBUG, "Interpolated value for property {} at {}: {} -> {} = {}", string_from_property_id(it.key), progress_in_keyframe, start->to_string(), end->to_string(), next_value->to_string());
+            style_properties.set_property(it.key, *next_value);
+        } else {
+            // If interpolate_property() fails, the element should not be rendered
+            dbgln_if(LIBWEB_CSS_ANIMATION_DEBUG, "Interpolated value for property {} at {}: {} -> {} is invalid", string_from_property_id(it.key), progress_in_keyframe, start->to_string(), end->to_string());
+            style_properties.set_property(PropertyID::Visibility, IdentifierStyleValue::create(ValueID::Hidden));
```
Comment (mattco98) [inline Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:1342]: Is this a sensible way to accomplish "not rendering" the element? It feels odd, but I wasn't sure how else to do it.

Comment (awesomekling) [reply Userland/Libraries/LibWeb/CSS/StyleComputer.cpp:1342]: I'm not entirely sure what's the best strategy here.
Overriding the `visibility` property is probably not entirely correct since it's observable from JavaScript, but we can do it this way for now, and then figure out something different after we look at how other browsers behave :)
