### PR TITLE
SystemMonitor: Handle zombie processes properly

### LINKED ISSUE #18200: SystemMonitor: Crashes when there are zombie processes
Related to #17810.
`SystemMonitor` will promptly crash if there are zombie processes in the system.

### PR DESCRIPTION
**Pull request by supercomputer7**
SystemMonitor had a bug in which it would crash in case there are zombie processes left in the system.
The fix for this is to check if a process has no threads (which will indicate that the process is a zombie and is waiting to be reaped), and if that's the case, artificially create a thread row that is just enough to represent the zombie process.

Fixes #18200.

### CODE REVIEW

**Comment by supercomputer7** [comment]
A test program to unleash zombie processes:
```c++
/*
 * Copyright (c) 2023, Liav A. <liavalb@hotmail.co.il>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <LibCore/ArgsParser.h>
#include <LibCore/System.h>
#include <LibCore/EventLoop.h>
#include <LibMain/Main.h>
#include <unistd.h>

static void sigchld_handler(int)
{
}

ErrorOr<int> serenity_main(Main::Arguments arguments)
{
    Vector<StringView> command;
    Core::ArgsParser args_parser;
    bool preserve_env = false;
    args_parser.set_stop_on_first_non_option(true);
    args_parser.add_option(preserve_env, "Preserve user environment when running command", "preserve-env", 'E');
    args_parser.add_positional_argument(command, "Command to execute", "command");
    args_parser.parse(arguments);

    TRY(Core::System::pledge("stdio rpath exec id jail proc tty sigaction"));

    Core::EventLoop event_loop;

    event_loop.register_signal(SIGCHLD, sigchld_handler);

    pid_t child_pid = TRY(Core::System::fork());
    if (!child_pid) {
        TRY(Core::System::exec_command(command, preserve_env));
    }
    
    return event_loop.exec();
}

```

**Comment by supercomputer7** [comment]
Screenshot_2023-04-06_11-01-44

File: Userland/Applications/SystemMonitor/ProcessModel.cpp [hunk 1]
```diff
@@ -469,54 +469,104 @@ void ProcessModel::update()
...
+                    auto thread_data = m_threads.ensure(thread.tid, [&] { return make_ref_counted<Thread>(**process_state); });
+                    thread_data->previous_state = move(thread_data->current_state);
+                    thread_data->current_state = move(state);
+                    if (auto maybe_thread_index = (*process_state)->threads.find_first_index(thread_data); maybe_thread_index.has_value()) {
+                        (*process_state)->threads[maybe_thread_index.value()] = thread_data;
+                    } else {
+                        (*process_state)->threads.append(thread_data);
+                    }
+
+                    live_tids.set(thread.tid);
```
Comment (GMTA) [inline Userland/Applications/SystemMonitor/ProcessModel.cpp:520]: Maybe pull this out into a lambda?

File: Userland/Applications/SystemMonitor/ProcessModel.cpp [hunk 2]
```diff
@@ -469,54 +469,104 @@ void ProcessModel::update()
...
+                }
+            } else {
+                // NOTE: If there are no threads left in a process this is an indication
+                // for a zombie process, so it should be handled differently.
                 ThreadState state(**process_state);
-                state.tid = thread.tid;
+                state.tid = process.pid;
```
Comment (GMTA) [inline Userland/Applications/SystemMonitor/ProcessModel.cpp:526]: It feels wrong to report a thread ID if there isn't one. Can we set it to 0 instead?

File: Userland/Applications/SystemMonitor/ProcessModel.cpp [hunk 3]
```diff
@@ -469,54 +469,104 @@ void ProcessModel::update()
...
+                state.syscall_count = 0;
+                state.inode_faults = 0;
+                state.zero_faults = 0;
+                state.cow_faults = 0;
+                state.unix_socket_read_bytes = 0;
+                state.unix_socket_write_bytes = 0;
+                state.ipv4_socket_read_bytes = 0;
+                state.ipv4_socket_write_bytes = 0;
+                state.file_read_bytes = 0;
+                state.file_write_bytes = 0;
```
Comment (GMTA) [inline Userland/Applications/SystemMonitor/ProcessModel.cpp:559]: These are all `ThreadState` default values - maybe not set them again here to reduce the amount of real estate being used / increase readability?

File: Userland/Applications/SystemMonitor/ProcessModel.cpp (hunk 2 above)
Comment (supercomputer7) [reply Userland/Applications/SystemMonitor/ProcessModel.cpp:530]: I tested this and it seems to be the actually another source of a crash we have with zombie processes - TID 0 is invalid and TID that equals the PID actually makes sense to me because the first thread of each process has a TID which is the same for the PID, so we essentially simulate a process with one thread although it does not have any.

Comment (GMTA) [reply Userland/Applications/SystemMonitor/ProcessModel.cpp:530]: > it seems to be the actually another source of a crash we have with zombie processes - TID 0 is invalid

Is that crash fixable? It probably stems from the fact that we're trying to shoehorn a process inside of a thread structure...

> TID 0 is invalid and TID that equals the PID actually makes sense to me because the first thread of each process has a TID which is the same for the PID

Sure, but that thread doesn't exist anymore, so TID=PID actually no longer makes sense to me at that point.

Comment (supercomputer7) [reply Userland/Applications/SystemMonitor/ProcessModel.cpp:530]: I tried for a couple of hours and the answer is sure, yes, this is fixable, but not with an easy one-line solution. I still need to learn more about the whole LibGUI model abstractions as this is completely new to me.

And yes, the crash is happening because the whole process model and its entries are tied to threads as the main representative rather using processes, just like you said.

Can we put a FIXME note on this and work this out later on?

Comment (GMTA) [reply Userland/Applications/SystemMonitor/ProcessModel.cpp:530]: Yes, FIXME sounds fine!

**Comment by ADKaster** [comment]
There's a suspicious failure on your branch in the clang tests

https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=29852&view=logs&jobId=1427867c-05b9-544b-63a5-81f0b096b4ff&j=1427867c-05b9-544b-63a5-81f0b096b4ff&t=e99ee61b-bd91-5005-d29b-1e01d815fdb7>
```
CRASHED LibThreading/TestThread (1.022959s)
         Test:   TestThread (crashed)
Running test 'threads_can_detach'.
ASSERTION FAILED: false
Userland/Libraries/LibThreading/Thread.cpp:131
```

But since this PR only touches SystemMonitor it's unlikely to be related.

**Comment by supercomputer7** [comment]
> There's a suspicious failure on your branch in the clang tests
> 
> [https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=29852&view=logs&jobId=1427867c-05b9-544b-63a5-81f0b096b4ff&j=1427867c-05b9-544b-63a5-81f0b096b4ff&t=e99ee61b-bd91-5005-d29b-1e01d815fdb7>](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=29852&view=logs&jobId=1427867c-05b9-544b-63a5-81f0b096b4ff&j=1427867c-05b9-544b-63a5-81f0b096b4ff&t=e99ee61b-bd91-5005-d29b-1e01d815fdb7%3E)
> 
> ```
> CRASHED LibThreading/TestThread (1.022959s)
>          Test:   TestThread (crashed)
> Running test 'threads_can_detach'.
> ASSERTION FAILED: false
> Userland/Libraries/LibThreading/Thread.cpp:131
> ```
> 
> But since this PR only touches SystemMonitor it's unlikely to be related.

I can rebase and push it to clear this out :)

**Review by ADKaster — APPROVED** [review]
