### PR TITLE
Kernel: Fix the shutdown procedure

### LINKED ISSUE #20560: Kernel: Shutting down can hang waiting for filesystems to sync
This is often seen on CI in the "Check manpages for completeness" step. After issuing `shutdown -n`, the script gets stuck waiting for Serenity to actually shut down. The debug log shows:
```
0.682 [#0 Power State Switch Task(12:12)]: Killing remaining processes...
0.682 [#0 Finalizer Task(5:5)]: Init process quitting for shutdown.
0.688 [#0 Power State Switch Task(12:12)]: Locking all file systems...
```

It is the call to `FileSystem::sync();` after that last log point which gets stuck. If NVMe is enabled, we are stuck here waiting for an NVMe read request to complete:
https://github.com/SerenityOS/serenity/blob/500b7b08d6e65cf0cf5eb29eb7205c53aa30b52f/Kernel/Devices/Storage/StorageDevice.cpp#L202

If NVMe is disabled, we are stuck here waiting for an ATA device write to complete:
https://github.com/SerenityOS/serenity/blob/500b7b08d6e65cf0cf5eb29eb7205c53aa30b52f/Kernel/Devices/Storage/StorageDevice.cpp#L179

This started with commit b645f87b7ad282af7a8918777be724992803ef7f (#19668). If I check out the repo to just before that PR landed, there's no hanging issues on shutdown.

For a more minimal repro than that CI step, see:
https://github.com/trflynn89/serenity/tree/shutdown_bug

### PR DESCRIPTION
**Pull request by supercomputer7**
Originally started in #20588, this completely fixes the shutdown procedure, without going for the architectural changes first.

Fixes #20560.

### CODE REVIEW

File: Kernel/FileSystem/Ext2FS/FileSystem.cpp [hunk 1]
```diff
@@ -589,14 +589,14 @@ ErrorOr<void> Ext2FS::prepare_to_clear_last_mount(Inode& mount_guest_inode)
...
 
-    BlockBasedFileSystem::remove_disk_cache_before_last_unmount();
     m_inode_cache.clear();
     m_root_inode = nullptr;
 
     // Mark filesystem as valid before unmount.
     dmesgln("Ext2FS: Clean unmount, setting superblock to valid state");
     m_super_block.s_state = EXT2_VALID_FS;
     TRY(flush_super_block());
+    BlockBasedFileSystem::remove_disk_cache_before_last_unmount();
```
Comment (BertalanD) [inline Kernel/FileSystem/Ext2FS/FileSystem.cpp:599]: The commit message indicates that the `flush_super_block` call goes through the disk cache. How do we ensure that this cache is flushed and the AsyncDeviceRequests have completed before the system is shut down?

**Review by BertalanD — COMMENTED** [review]
Looks good to me in general. But I have one question about how caches behave during shutdown.

File: Kernel/Tasks/PowerStateSwitchTask.cpp [hunk 2]
```diff
@@ -152,15 +155,16 @@ ErrorOr<void> PowerStateSwitchTask::perform_shutdown()
...
-
-    Process::all_instances().for_each([&](Process& process) {
-        if (process.pid() != Process::current().pid() && process.pid() != finalizer_pid && process.is_kernel_process() == kill_kernel_processes) {
-            process.die();
-        }
-    });
+    {
+        SpinlockLocker lock(g_scheduler_lock);
+        Process::all_instances().for_each([&](Process& process) {
+            if (process.pid() != Process::current().pid() && process.pid() != finalizer_pid && !process.is_kernel_process()) {
```
Comment (ADKaster) [inline Kernel/Tasks/PowerStateSwitchTask.cpp:158]: Isn't the finalizer a kernel process?

Comment (ADKaster) [reply Kernel/Tasks/PowerStateSwitchTask.cpp:158]: Actually, since we know that this will only ever be called by the power state switch task, can't we just ignore all kernel processes and skip checking the other pids, even our own?

File: Kernel/FileSystem/Ext2FS/FileSystem.cpp (hunk 1 above)
Comment (supercomputer7) [reply Kernel/FileSystem/Ext2FS/FileSystem.cpp:599]: As far as I can tell the call to flush the superblock will create an async IO request and will block until it is completed.

File: Kernel/Tasks/PowerStateSwitchTask.cpp (hunk 2 above)
Comment (supercomputer7) [reply Kernel/Tasks/PowerStateSwitchTask.cpp:158]: Yes, it is actually possible to do so. I will fix this today this evening.

**Review by ADKaster — APPROVED** [review]
