### PR TITLE
FileManager+LibGUI: Fix crash when opening a folder, as well as when …

### LINKED ISSUE #536: FileManager: making a directory and navigating to it immediately after crashes the app
After the crash, FileManager can be reopened and the directory will work.

### PR DESCRIPTION
**Pull request by xeons**
- Fixed a crash that occurs when trying to open a folder, or when trying to open a newly created folder.
- Treeview now refreshes after creating the new folder.

This fixes #536.

### CODE REVIEW

File: Libraries/LibGUI/GFileSystemModel.cpp [hunk 1]
```diff
@@ -31,6 +31,15 @@ struct GFileSystemModel::Node {
         ASSERT_NOT_REACHED();
     }
 
+    void cleanup()
+    {
+        for(auto &child: children) {
```
Comment (awesomekling) [inline Libraries/LibGUI/GFileSystemModel.cpp]: Please use the same formatting as the rest of the codebase:

```suggestion
        for (auto& child : children) {
```

You can use `clang-format` (version 8 or later) to do this automatically. I have it set up so I just press a key combination in my editor to invoke it, for example :)

File: Applications/FileManager/main.cpp [hunk 2]
```diff
@@ -104,6 +104,22 @@ int main(int argc, char** argv)
             if (rc < 0) {
                 GMessageBox::show(String::format("mkdir(\"%s\") failed: %s", new_dir_path.characters(), strerror(errno)), "Error", GMessageBox::Type::Error, GMessageBox::InputType::OK, window);
             } else {
+                file_system_model->update();
+
+                auto current_path = directory_view->path();
+
+                // not exactly sure why i have to reselect the root node first, but the index() fails if I dont
```
Comment (awesomekling) [inline Applications/FileManager/main.cpp]: This is very suspicious but okay for now :)

File: Applications/FileManager/main.cpp [hunk 3]
```diff
@@ -104,6 +104,22 @@ int main(int argc, char** argv)
...
+                auto root_index = file_system_model->index(file_system_model->root_path());
+                tree_view->selection().set(root_index);
+                tree_view->scroll_into_view(root_index, Orientation::Vertical);
```
Comment (awesomekling) [inline Applications/FileManager/main.cpp]: Do we really need to `scroll_into_view` and `update` twice for the workaround as well?

Comment (xeons) [reply Applications/FileManager/main.cpp]: I'll play around with this tonight to see if everything is required or not.

Comment (xeons) [reply Applications/FileManager/main.cpp]: Looks as though just setting the index was required.

File: Libraries/LibGUI/GFileSystemModel.cpp (hunk 1 above)
Comment (xeons) [reply Libraries/LibGUI/GFileSystemModel.cpp]: I'll see if I can get this, looks like linux mint only has version 6.
