### PR TITLE
Kernel: Make Random work on CPUs without rdrand

### LINKED ISSUE #2634: First boot, Fortuna RNG assertion failed m_reseed_number > 0
It looks to me like an initial `this->reseed();` is missing.

### PR DESCRIPTION
**Pull request by Petelliott**
- If rdseed is not available, fallback to rdrand.
- If rdrand is not available, block when user needs good random, and use insecure PRNG when user needs fast random.

Fixes #2634

### CODE REVIEW

File: Kernel/Random.h [hunk 1]
```diff
@@ -86,6 +86,16 @@ class FortunaPRNG {
         m_pools[pool].update(reinterpret_cast<const u8*>(&event_data), sizeof(T));
     }
 
+    bool seeded()
```
Comment (awesomekling) [inline Kernel/Random.h:89]: This should be `const`. Also let's call it `is_seeded()` per the project coding style.

File: Kernel/Random.h [hunk 2]
```diff
@@ -86,6 +86,16 @@ class FortunaPRNG {
...
+    {
+        return m_reseed_number > 0;
+    }
+
+    bool ready()
```
Comment (awesomekling) [inline Kernel/Random.h:94]: This should be `const`. Also let's call it `is_ready()` per the project coding style.

File: Kernel/Random.h [hunk 3]
```diff
@@ -86,6 +86,16 @@ class FortunaPRNG {
...
+    {
+        return this->seeded() || m_p0_len >= reseed_threshold;
```
Comment (awesomekling) [inline Kernel/Random.h:96]: No need for `this->` here.

File: Kernel/Random.cpp [hunk 4]
```diff
@@ -73,7 +97,25 @@ void get_good_random_bytes(u8* buffer, size_t buffer_size)
 
 void get_fast_random_bytes(u8* buffer, size_t buffer_size)
 {
-    return get_good_random_bytes(buffer, buffer_size);
+    if (KernelRng::the().resource().ready()) {
+        return get_good_random_bytes(buffer, buffer_size);
+    } else {
```
Comment (awesomekling) [inline Kernel/Random.cpp:102]: No need for `else` after `return`.
