### PR TITLE
Kernel: Ensure Ext2FSInode's lookup is populated before use

### LINKED ISSUE #8133: Kernel+FileManager: Large deletes sometimes fail due to filesystem corruption
(Pretty sure this is a Kernel issue, but it could well be something the FileManager is doing.)

Steps to reproduce:

1. Start with a fresh Serenity _disk_image
2. Copy /usr/include to the Desktop
3. Delete the copy
4. Repeat 2 and 3 a few times and it will eventually fail with a complaint that the directory isn't empty:

image

Both inner directories have no contents but the OS thinks they are not empty. This persists after restarting the VM.

### PR DESCRIPTION
**Pull request by AtkinsSJ**
This fixes #8133.

### CODE REVIEW

File: Kernel/FileSystem/Ext2FileSystem.cpp [hunk 1]
```diff
@@ -1209,6 +1209,7 @@ KResult Ext2FSInode::add_child(Inode& child, const StringView& name, mode_t mode
     if (result.is_error())
         return result;
 
+    VERIFY(populate_lookup_cache());
```
Comment (awesomekling) [inline Kernel/FileSystem/Ext2FileSystem.cpp:1212]: Please don't do effectful things inside `VERIFY` as it makes it much harder to see what's happening.

Also, if populating the lookup cache causes an error, we should propagate that error to the caller instead of panicking the kernel :)

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Kernel/FileSystem/Ext2FileSystem.cpp (hunk 1 above)
Comment (AtkinsSJ) [reply Kernel/FileSystem/Ext2FileSystem.cpp:1212]: Thanks!

Should I modify `populate_lookup_cache()` to return the error? Right now it just returns a bool.

Also there's one place where the result of `populate_lookup_cache()` is ignored: `Ext2FSInode::directory_entry_count()`, so probably that should propagate it too? It's also called in `Ext2FSInode::lookup()`, but that doesn't have a way of returning errors except an empty pointer.

Comment (AtkinsSJ) [reply Kernel/FileSystem/Ext2FileSystem.cpp]: Thanks! I've modified populate_lookup_cache() to return a KResult, and the error is propagated out everywhere it's called.
