### PR TITLE
LibJS: Fix Bytecode Optimization flakiness

### LINKED ISSUE #15753: LibJS: Bytecodes NewBigInt is not trivially copyable, but is copied by memcpy in MergeBlocks
Essentially what the title says.

This is surely one if the causes of the optimization flakes and fails we have experienced, while they were set to always on for test262 runs

### PR DESCRIPTION
**Pull request by Hendiadyoin1**
With this `test-js -b` seems as broken with optimizations as it is without them

Alternatively making the cfg ordered also seems to fix the issue fixed by `LibJS: Fix MergeBlocks emitting some blocks twice`,
but that seemed to me as only papering over the underlying issue.

also
Fixes #15753

### CODE REVIEW

File: Userland/Libraries/LibJS/Bytecode/Pass/DumpCFG.cpp [hunk 1]
```diff
@@ -13,12 +13,12 @@ void DumpCFG::perform(PassPipelineExecutable& executable)
     started();
 
     VERIFY(executable.cfg.has_value());
-    outln(m_file, "CFG Dump for {} basic blocks:", executable.executable.basic_blocks.size());
```
Comment (alimpfard) [inline Userland/Libraries/LibJS/Bytecode/Pass/DumpCFG.cpp:16]: you can pass arguments to `PassManager::add<T>(...)`, which would be given to the ctor
Even if it didn't, instead of removing this, you could just add a default value for the file in the constructor

File: Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp [hunk 2]
```diff
@@ -119,7 +119,7 @@ void MergeBlocks::perform(PassPipelineExecutable& executable)
                 if (entry == cfg.end())
                     continue;
                 auto const* successor = *entry->value.begin();
-                if (successor == successors.first() && last != successor) {
+                if (successor == successors.first()) {
```
Comment (alimpfard) [inline Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp:122]: that's not a sanity check

File: Userland/Libraries/LibJS/Bytecode/Pass/UnifySameBlocks.cpp [hunk 3]
```diff
@@ -29,6 +29,8 @@ void UnifySameBlocks::perform(PassPipelineExecutable& executable)
                 continue;
 
             auto candidate_bytes = candidate_block->instruction_stream();
+            // FIXME: NewBigInt holds a SignedBigInteger, which's memory footprint
+            //        does not reflect its value
```
Comment (alimpfard) [inline Userland/Libraries/LibJS/Bytecode/Pass/UnifySameBlocks.cpp:33]: this sentence took a good minute to parse
```suggestion
            // FIXME: NewBigInt's value is not correctly reflected by its encoding in memory,
            //        this will yield false negatives for blocks containing that
```
or something of the sort.

**Review by alimpfard — COMMENTED** [review]
Quick review for now, will do a proper review later tonight.

File: Userland/Libraries/LibJS/Bytecode/Pass/DumpCFG.cpp (hunk 1 above)
Comment (Hendiadyoin1) [reply Userland/Libraries/LibJS/Bytecode/Pass/DumpCFG.cpp:16]: Ah Ok, then it turns out that I was just to stupid to use it....

File: Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp (hunk 2 above)
Comment (Hendiadyoin1) [reply Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp:122]: Oops, that slipped into the wrong commit

**Comment by nico** [comment]
Typo "isntruction" in 2nd commit message.

**Review by alimpfard — COMMENTED** [review]
Seems alright, please also reenable the default optimisation pipeline :^)

**Comment by Hendiadyoin1** [comment]
Done that now
