### PR TITLE
WindowServer: Fix notification placement

### LINKED ISSUE #6262: WindowServer: Notification placement looks off now that the menu bar is gone
As mentioned by Clovqr on Discord. Could either move them up a bit, or down to the task bar, stacking upwards rather than downwards.

image

### PR DESCRIPTION
**Pull request by vkoskiv**
No more top bar, no more extra padding. Spacing is equal on the top and
on the left, so it looks pretty tidy.

Resolves #6262

### CODE REVIEW

File: Userland/Services/NotificationServer/NotificationWindow.cpp [hunk 1]
```diff
@@ -46,7 +46,7 @@ static void update_notification_window_locations(const Gfx::IntRect& screen_rect
         auto& window = window_entry.value;
         Gfx::IntPoint new_window_location;
         if (last_window_rect.is_null())
-            new_window_location = screen_rect.top_right().translated(-window->rect().width() - 24, 26);
+            new_window_location = screen_rect.top_right().translated(-window->rect().width() - 24, 7);
```
Comment (vkoskiv) [inline Userland/Services/NotificationServer/NotificationWindow.cpp:49]: Maybe these magic numbers could be documented with a constexpr variable somewhere?
