### PR TITLE
ping: Fix broken count argument error

### LINKED ISSUE #12524: Ping: Invalid count argument error when not specifying count argument at all
Seems like changes from today broke the utility:
https://github.com/SerenityOS/serenity/commit/75a3be852d43742babff74c6b84a7cda6bcb6242

Trying to run the command without any argument (besides a specified host) says:
```
invalid count argument: '0' : out of range: 1 <= value <= 4294967295
```
instead of running ping indefinitely, like on Linux.

cc @brapru

### PR DESCRIPTION
**Pull request by brapru**
Apologies for the silly bug :flushed: 

**ArgsParser: Add support for Optional<size_t>**

**ping: Fix broken count argument error**
By storing count as an Optional<size_t>, we can leverage count's empty
state to proceed with pinging indefinitely, and ensure a proper value is
passed when count does have a value.

This returns pings expected behavior to send infinite packets when a
count is not specified, stop after sending a specified count, and
disallow any count < 1.

Closes #12524

### CODE REVIEW

File: Userland/Utilities/ping.cpp [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
 static uint32_t total_pings;
 static int successful_pings;
-static uint32_t count;
+static uint32_t count = -1;
```
Comment (davidot) [inline Userland/Utilities/ping.cpp:29]: This will just underflow `count`, shouldn't the default be `0`? 
Which then means infinite packets?
Maybe that should also be mentioned in the argument text. Something like:
`"Stop after sending specified number of ECHO_REQUEST packets, use 0 to never stop (default: 0)."`

Comment (trflynn89) [reply Userland/Utilities/ping.cpp:29]: Why don't we store `count` as `Optional<size_t>`? Might need to add support for that to `ArgParser`, but then we can use `count`'s empty state instead of a special `-1` value here.

Comment (brapru) [reply Userland/Utilities/ping.cpp:29]: Fair enough! I can look into it :+1:

Comment (brapru) [reply Userland/Utilities/ping.cpp]: @trflynn89 yeah, this feels a lot better. Let me know what you think

File: Userland/Libraries/LibCore/ArgsParser.cpp [hunk 2]
```diff
@@ -484,6 +484,23 @@ void ArgsParser::add_option(Optional<double>& value, const char* help_string, co
...
+    Option option {
+        true,
+        help_string,
+        long_name,
+        short_name,
+        value_name,
+        [&value](const char* s) {
+            auto opt = AK::StringUtils::convert_to_uint<size_t>(s);
+            value = opt.value_or(0);
+            return opt.has_value();
```
Comment (trflynn89) [inline Userland/Libraries/LibCore/ArgsParser.cpp:498]: We should match the behavior of the `Optional<bool>` overload above, otherwise `value` here will always have a value:
```c++
            value = AK::StringUtils::convert_to_uint<size_t>(s);
            return value.has_value();
```

File: Userland/Utilities/ping.cpp [hunk 3]
```diff
@@ -157,7 +157,7 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
         struct timeval tv_send;
         gettimeofday(&tv_send, nullptr);
 
-        if (count && total_pings == count)
+        if (count.has_value() && total_pings == count.value())
```
Comment (trflynn89) [inline Userland/Utilities/ping.cpp:160]: So this will loop forever if `count` is larger than `UINT32_MAX` because then `total_pings` can never reach it (it will rollover to 0).

You can leave the max limit on line 70 as `UINT32_MAX` to prevent this, or update all appropriate types to `size_t`.

File: Userland/Libraries/LibCore/ArgsParser.cpp (hunk 2 above)
Comment (brapru) [reply Userland/Libraries/LibCore/ArgsParser.cpp]: Fixed :+1:

File: Userland/Utilities/ping.cpp (hunk 3 above)
Comment (brapru) [reply Userland/Utilities/ping.cpp:160]: Ah, good catch. We'll just keep it at `UINT32_MAX` for now.
