### PR TITLE
LibC+DynamicLoader: Store the auxiliary vector address at startup

### LINKED ISSUE #10087: HackStudio: Crash on exit when opened from serenity menu
Steps to reproduce: Open Hackstudio from the serenity menu, close it right away. This is without git and make installed. This does not seem to happen when HackStudio is opened from the terminal.

Dump:
<details>

```
[#0 HackStudio(40:40)]: Unrecoverable page fault, read from address V0x00000002bbdc0008
[HackStudio(40:40)]: CRASH: CPU #0 Page Fault in ring 3
[#0 HackStudio(40:40)]: Exception code: 0004 (isr: 0000)
[#0 HackStudio(40:40)]:     pc=0x0013:0x0000000a2c769c50 rflags=0x0000000000010282
[#0 HackStudio(40:40)]:  stack=0x0000000001400948
[#0 HackStudio(40:40)]:    rax=0xedededededededed rbx=0x0000000a2cb5d6d8 rcx=0xfffffffffffffdf4 rdx=0x00000002bbdbfff8
[#0 HackStudio(40:40)]:    rbp=0x0000000001400960 rsp=0x000000200749ef40 rsi=0x000000000bd9f000 rdi=0x0000000a2c944f33
[#0 HackStudio(40:40)]:     r8=0x0000000000000000  r9=0x0000000000000001 r10=0x0000000065038731 r11=0x0000000000000000
[#0 HackStudio(40:40)]:    r12=0x0000000000000000 r13=0x0000000001400bb0 r14=0x0000000001400bc0 r15=0x00000000c6c7c8c9
[#0 HackStudio(40:40)]:    cr0=0x0000000080010013 cr2=0x00000002bbdc0008 cr3=0x0000000018c3f000 cr4=0x0000000000340ee4
[#0 HackStudio(40:40)]: 0x0000000a2c769c50  (?)

[#0 HackStudio(40:40)]: Process regions:
[#0 HackStudio(40:40)]: BEGIN                 END                SIZE               ACCESS NAME
[#0 HackStudio(40:40)]: 0x0000000001301000 -- 0x0000000001400fff 0x0000000000100000 RW  T  Stack (Main thread)
[#0 HackStudio(40:40)]: 0x0000000001402000 -- 0x0000000001402fff 0x0000000000001000 R XS C Signal trampoline
[#0 HackStudio(40:40)]: 0x000000000140c000 -- 0x000000000140ffff 0x0000000000004000 R  S   /res/fonts/CsillaBold10.font
[#0 HackStudio(40:40)]: 0x0000000001411000 -- 0x0000000001415fff 0x0000000000005000 R  S   /res/fonts/CsillaBold12.font
[#0 HackStudio(40:40)]: 0x0000000001417000 -- 0x0000000001423fff 0x000000000000d000 R  S   /res/fonts/CsillaRegular10.font
[#0 HackStudio(40:40)]: 0x0000000001425000 -- 0x0000000001429fff 0x0000000000005000 R  S   /res/fonts/CsillaRegular12.font
[#0 HackStudio(40:40)]: 0x000000000142b000 -- 0x000000000143afff 0x0000000000010000 R  S   /res/fonts/KaticaBold10.font
[#0 HackStudio(40:40)]: 0x000000000143c000 -- 0x0000000001440fff 0x0000000000005000 R  S   /res/fonts/KaticaBold12.font
[#0 HackStudio(40:40)]: 0x0000000001442000 -- 0x0000000001451fff 0x0000000000010000 R  S   /res/fonts/KaticaRegular10.font
[#0 HackStudio(40:40)]: 0x0000000001453000 -- 0x0000000001457fff 0x0000000000005000 R  S   /res/fonts/KaticaRegular12.font
[#0 HackStudio(40:40)]: 0x0000000001459000 -- 0x00000000014b2fff 0x000000000005a000 R  S   /res/fonts/LiberationSerif-Bold.ttf
[#0 HackStudio(40:40)]: 0x00000000014b4000 -- 0x000000000150efff 0x000000000005b000 R  S   /res/fonts/LiberationSerif-BoldItalic.ttf
[#0 HackStudio(40:40)]: 0x0000000001510000 -- 0x000000000156afff 0x000000000005b000 R  S   /res/fonts/LiberationSerif-Italic.ttf
[#0 HackStudio(40:40)]: 0x000000000156c000 -- 0x00000000015cafff 0x000000000005f000 R  S   /res/fonts/LiberationSerif-Regular.ttf
[#0 HackStudio(40:40)]: 0x00000000015cc000 -- 0x00000000015cffff 0x0000000000004000 R  S   /res/fonts/LizaBlack10.font
[#0 HackStudio(40:40)]: 0x00000000015d1000 -- 0x00000000015dafff 0x000000000000a000 R  S   /res/fonts/LizaBlack24.font
[#0 HackStudio(40:40)]: 0x00000000015dc000 -- 0x00000000015e9fff 0x000000000000e000 R  S   /res/fonts/LizaBlack36.font
[#0 HackStudio(40:40)]: 0x00000000015eb000 -- 0x00000000015eefff 0x0000000000004000 R  S   /res/fonts/LizaBold10.font
[#0 HackStudio(40:40)]: 0x00000000015f0000 -- 0x00000000015f9fff 0x000000000000a000 R  S   /res/fonts/LizaBold24.font
[#0 HackStudio(40:40)]: 0x00000000015fb000 -- 0x0000000001608fff 0x000000000000e000 R  S   /res/fonts/LizaBold36.font
[#0 HackStudio(40:40)]: 0x000000000160a000 -- 0x000000000160dfff 0x0000000000004000 R  S   /res/fonts/LizaRegular10.font
[#0 HackStudio(40:40)]: 0x000000000160f000 -- 0x0000000001618fff 0x000000000000a000 R  S   /res/fonts/LizaRegular24.font
[#0 HackStudio(40:40)]: 0x000000000161a000 -- 0x0000000001627fff 0x000000000000e000 R  S   /res/fonts/LizaRegular36.font
[#0 HackStudio(40:40)]: 0x0000000001629000 -- 0x000000000162ffff 0x0000000000007000 R  S   /res/fonts/MarietaBold24.font
[#0 HackStudio(40:40)]: 0x0000000001631000 -- 0x000000000163afff 0x000000000000a000 R  S   /res/fonts/MarietaBold36.font
[#0 HackStudio(40:40)]: 0x000000000163c000 -- 0x0000000001642fff 0x0000000000007000 R  S   /res/fonts/MarietaRegular24.font
[#0 HackStudio(40:40)]: 0x0000000001644000 -- 0x000000000164dfff 0x000000000000a000 R  S   /res/fonts/MarietaRegular36.font
[#0 HackStudio(40:40)]: 0x000000000164f000 -- 0x0000000001654fff 0x0000000000006000 R  S   /res/fonts/PebbletonBold14.font
[#0 HackStudio(40:40)]: 0x0000000001656000 -- 0x000000000165bfff 0x0000000000006000 R  S   /res/fonts/PebbletonRegular14.font
[#0 HackStudio(40:40)]: 0x000000000165d000 -- 0x000000000165ffff 0x0000000000003000 R  S   /res/fonts/SerenitySans-Regular.ttf
[#0 HackStudio(40:40)]: 0x00000000018fd000 -- 0x00000000018fdfff 0x0000000000001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/app-hack-studio.png
[#0 HackStudio(40:40)]: 0x00000000018ff000 -- 0x00000000018fffff 0x0000000000001000 RW     Gfx::Bitmap [[32x32]] - Decoded PNG: /res/icons/32x32/app-hack-studio.png
[#0 HackStudio(40:40)]: 0x000000000bd9c000 -- 0x000000000bd9cfff 0x0000000000001000 RW     Master TLS
[#0 HackStudio(40:40)]: 0x000000000bd9e000 -- 0x000000000bd9ffff 0x0000000000002000 RW     Thread-specific
[#0 HackStudio(40:40)]: 0x000000000bdcf000 -- 0x000000000bdd4fff 0x0000000000006000 R      
[#0 HackStudio(40:40)]: 0x000000000c167000 -- 0x000000000c168fff 0x0000000000002000 R  S C /usr/lib/Loader.so
[#0 HackStudio(40:40)]: 0x000000000c169000 -- 0x000000000c1d5fff 0x000000000006d000 R XS C /usr/lib/Loader.so
[#0 HackStudio(40:40)]: 0x000000000c1d6000 -- 0x000000000c1edfff 0x0000000000018000 R  S C /usr/lib/Loader.so
[#0 HackStudio(40:40)]: 0x000000000c1ef000 -- 0x000000000c1f1fff 0x0000000000003000 RW     0x00000020072bd5f0 (data-rw)
[#0 HackStudio(40:40)]: 0x00000000a06d0000 -- 0x00000000a06dffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000001180ac000 -- 0x0000000118180fff 0x00000000000d5000 R  S   libgui.so: .rodata
[#0 HackStudio(40:40)]: 0x00000001182ac000 -- 0x0000000118411fff 0x0000000000166000 R XS   libgui.so: .text
[#0 HackStudio(40:40)]: 0x00000001184ac000 -- 0x0000000118504fff 0x0000000000059000 R  S   libgui.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000118705000 -- 0x000000011871ffff 0x000000000001b000 R      libgui.so: .relro
[#0 HackStudio(40:40)]: 0x0000000118720000 -- 0x0000000118720fff 0x0000000000001000 RW     libgui.so: .data
[#0 HackStudio(40:40)]: 0x00000001690d0000 -- 0x00000001690dffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000001834b3000 -- 0x0000000183c10fff 0x000000000075e000 R  S   libunicode.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000183cb3000 -- 0x0000000183cf8fff 0x0000000000046000 R XS   libunicode.so: .text
[#0 HackStudio(40:40)]: 0x0000000183eb3000 -- 0x0000000183ff9fff 0x0000000000147000 R  S   libunicode.so: .rodata
[#0 HackStudio(40:40)]: 0x00000001841fa000 -- 0x00000001848bafff 0x00000000006c1000 R      libunicode.so: .relro
[#0 HackStudio(40:40)]: 0x00000001848bb000 -- 0x00000001848bbfff 0x0000000000001000 RW     libunicode.so: .data
[#0 HackStudio(40:40)]: 0x000000023c580000 -- 0x000000023c58ffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000000266281000 -- 0x000000026628cfff 0x000000000000c000 R  S   libconfig.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000266481000 -- 0x000000026648dfff 0x000000000000d000 R XS   libconfig.so: .text
[#0 HackStudio(40:40)]: 0x0000000266681000 -- 0x0000000266684fff 0x0000000000004000 R  S   libconfig.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000266885000 -- 0x0000000266886fff 0x0000000000002000 R      libconfig.so: .relro
[#0 HackStudio(40:40)]: 0x0000000266887000 -- 0x0000000266887fff 0x0000000000001000 RW     libconfig.so: .data
[#0 HackStudio(40:40)]: 0x000000027c1c0000 -- 0x000000027c1cffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000002bbdb0000 -- 0x00000002bbdbffff 0x0000000000010000 RW     malloc: ChunkedBlock(32)
[#0 HackStudio(40:40)]: 0x000000031e560000 -- 0x000000031e56ffff 0x0000000000010000 RW     malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x000000032af00000 -- 0x000000032af0ffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000003a6dd0000 -- 0x00000003a6ddffff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000003d4182000 -- 0x00000003d4195fff 0x0000000000014000 R  S   libwasm.so: .rodata
[#0 HackStudio(40:40)]: 0x00000003d4382000 -- 0x00000003d4407fff 0x0000000000086000 R XS   libwasm.so: .text
[#0 HackStudio(40:40)]: 0x00000003d4582000 -- 0x00000003d458bfff 0x000000000000a000 R  S   libwasm.so: .rodata
[#0 HackStudio(40:40)]: 0x00000003d478c000 -- 0x00000003d478dfff 0x0000000000002000 R      libwasm.so: .relro
[#0 HackStudio(40:40)]: 0x00000003d478e000 -- 0x00000003d478efff 0x0000000000001000 RW     libwasm.so: .data
[#0 HackStudio(40:40)]: 0x00000003e96c5000 -- 0x00000003e96d9fff 0x0000000000015000 R  S   libcpp.so: .rodata
[#0 HackStudio(40:40)]: 0x00000003e98c5000 -- 0x00000003e98fefff 0x000000000003a000 R XS   libcpp.so: .text
[#0 HackStudio(40:40)]: 0x00000003e9ac5000 -- 0x00000003e9acdfff 0x0000000000009000 R  S   libcpp.so: .rodata
[#0 HackStudio(40:40)]: 0x00000003e9cce000 -- 0x00000003e9cd0fff 0x0000000000003000 R      libcpp.so: .relro
[#0 HackStudio(40:40)]: 0x00000003e9cd1000 -- 0x00000003e9cd1fff 0x0000000000001000 RW     libcpp.so: .data
[#0 HackStudio(40:40)]: 0x000000042f460000 -- 0x000000042f46ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000004d7fa0000 -- 0x00000004d7faffff 0x0000000000010000 RW     malloc: ChunkedBlock(1008)
[#0 HackStudio(40:40)]: 0x00000005c17d2000 -- 0x00000005c17dbfff 0x000000000000a000 R  S   libvt.so: .rodata
[#0 HackStudio(40:40)]: 0x00000005c19d2000 -- 0x00000005c19edfff 0x000000000001c000 R XS   libvt.so: .text
[#0 HackStudio(40:40)]: 0x00000005c1bd2000 -- 0x00000005c1bd9fff 0x0000000000008000 R  S   libvt.so: .rodata
[#0 HackStudio(40:40)]: 0x00000005c1dd9000 -- 0x00000005c1ddafff 0x0000000000002000 R      libvt.so: .relro
[#0 HackStudio(40:40)]: 0x00000005c1ddb000 -- 0x00000005c1ddbfff 0x0000000000001000 RW     libvt.so: .data
[#0 HackStudio(40:40)]: 0x0000000637248000 -- 0x0000000637255fff 0x000000000000e000 R  S   libdesktop.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000637448000 -- 0x0000000637458fff 0x0000000000011000 R XS   libdesktop.so: .text
[#0 HackStudio(40:40)]: 0x0000000637648000 -- 0x000000063764cfff 0x0000000000005000 R  S   libdesktop.so: .rodata
[#0 HackStudio(40:40)]: 0x000000063784c000 -- 0x000000063784dfff 0x0000000000002000 R      libdesktop.so: .relro
[#0 HackStudio(40:40)]: 0x000000063784e000 -- 0x000000063784efff 0x0000000000001000 RW     libdesktop.so: .data
[#0 HackStudio(40:40)]: 0x00000006649e4000 -- 0x00000006649ebfff 0x0000000000008000 R  S   libimagedecoderclient.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000664be4000 -- 0x0000000664be9fff 0x0000000000006000 R XS   libimagedecoderclient.so: .text
[#0 HackStudio(40:40)]: 0x0000000664de4000 -- 0x0000000664de5fff 0x0000000000002000 R  S   libimagedecoderclient.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000664fe6000 -- 0x0000000664fe6fff 0x0000000000001000 R      libimagedecoderclient.so: .relro
[#0 HackStudio(40:40)]: 0x0000000664fe7000 -- 0x0000000664fe7fff 0x0000000000001000 RW     libimagedecoderclient.so: .data
[#0 HackStudio(40:40)]: 0x0000000675700000 -- 0x000000067570ffff 0x0000000000010000 RW     malloc: ChunkedBlock(32)
[#0 HackStudio(40:40)]: 0x0000000709770000 -- 0x000000070978ffff 0x0000000000020000 RW     malloc: BigAllocationBlock
[#0 HackStudio(40:40)]: 0x00000007fc440000 -- 0x00000007fc44ffff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x0000000881480000 -- 0x000000088148ffff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000008b0bb0000 -- 0x00000008b0bbffff 0x0000000000010000 RW     malloc: ChunkedBlock(1008)
[#0 HackStudio(40:40)]: 0x00000008c7370000 -- 0x00000008c737ffff 0x0000000000010000        malloc: ChunkedBlock(1008)
[#0 HackStudio(40:40)]: 0x0000000983f78000 -- 0x0000000983f9bfff 0x0000000000024000 R  S   /bin/HackStudio: .rodata
[#0 HackStudio(40:40)]: 0x0000000983f9c000 -- 0x000000098400dfff 0x0000000000072000 R XS   /bin/HackStudio: .text
[#0 HackStudio(40:40)]: 0x000000098400e000 -- 0x0000000984028fff 0x000000000001b000 R  S   /bin/HackStudio: .rodata
[#0 HackStudio(40:40)]: 0x0000000984029000 -- 0x0000000984030fff 0x0000000000008000 R      /bin/HackStudio: .relro
[#0 HackStudio(40:40)]: 0x0000000984031000 -- 0x0000000984031fff 0x0000000000001000 RW     /bin/HackStudio: .data
[#0 HackStudio(40:40)]: 0x0000000a2c541000 -- 0x0000000a2c55afff 0x000000000001a000 R  S   libc.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000a2c741000 -- 0x0000000a2c7b9fff 0x0000000000079000 R XS   libc.so: .text
[#0 HackStudio(40:40)]: 0x0000000a2c941000 -- 0x0000000a2c95afff 0x000000000001a000 R  S   libc.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000a2cb5a000 -- 0x0000000a2cb5cfff 0x0000000000003000 R      libc.so: .relro
[#0 HackStudio(40:40)]: 0x0000000a2cb5d000 -- 0x0000000a2cb5efff 0x0000000000002000 RW     libc.so: .data
[#0 HackStudio(40:40)]: 0x0000000ab33c0000 -- 0x0000000ab33cffff 0x0000000000010000 RW     malloc: ChunkedBlock(16)
[#0 HackStudio(40:40)]: 0x0000000af6130000 -- 0x0000000af613ffff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000000b1407f000 -- 0x0000000b14089fff 0x000000000000b000 R  S   libcompress.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000b1427f000 -- 0x0000000b1428dfff 0x000000000000f000 R XS   libcompress.so: .text
[#0 HackStudio(40:40)]: 0x0000000b1447f000 -- 0x0000000b14483fff 0x0000000000005000 R  S   libcompress.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000b14683000 -- 0x0000000b14685fff 0x0000000000003000 R      libcompress.so: .relro
[#0 HackStudio(40:40)]: 0x0000000b14686000 -- 0x0000000b14686fff 0x0000000000001000 RW     libcompress.so: .data
[#0 HackStudio(40:40)]: 0x0000000b90950000 -- 0x0000000b9096ffff 0x0000000000020000 RW     malloc: BigAllocationBlock
[#0 HackStudio(40:40)]: 0x0000000be4187000 -- 0x0000000be4187fff 0x0000000000001000 R  S   Kernel time page
[#0 HackStudio(40:40)]: 0x0000000c1c439000 -- 0x0000000c1c439fff 0x0000000000001000 R  S   libdiff.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000c1c639000 -- 0x0000000c1c63bfff 0x0000000000003000 R XS   libdiff.so: .text
[#0 HackStudio(40:40)]: 0x0000000c1c839000 -- 0x0000000c1c839fff 0x0000000000001000 R  S   libdiff.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000c1ca39000 -- 0x0000000c1ca39fff 0x0000000000001000 R      libdiff.so: .relro
[#0 HackStudio(40:40)]: 0x0000000c1ca3a000 -- 0x0000000c1ca3afff 0x0000000000001000 RW     libdiff.so: .data
[#0 HackStudio(40:40)]: 0x0000000c87ed1000 -- 0x0000000c87ed2fff 0x0000000000002000 R  S   libx86.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000c880d1000 -- 0x0000000c880dffff 0x000000000000f000 R XS   libx86.so: .text
[#0 HackStudio(40:40)]: 0x0000000c882d1000 -- 0x0000000c882d2fff 0x0000000000002000 R  S   libx86.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000c884d3000 -- 0x0000000c884d3fff 0x0000000000001000 R      libx86.so: .relro
[#0 HackStudio(40:40)]: 0x0000000c884d4000 -- 0x0000000c884e4fff 0x0000000000011000 RW     libx86.so: .data
[#0 HackStudio(40:40)]: 0x0000000d172f0000 -- 0x0000000d172fffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000000d24cd0000 -- 0x0000000d24ceffff 0x0000000000020000 RW     malloc: BigAllocationBlock
[#0 HackStudio(40:40)]: 0x0000000daa0e2000 -- 0x0000000daa0f8fff 0x0000000000017000 R  S   libprotocol.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000daa2e2000 -- 0x0000000daa2fffff 0x000000000001e000 R XS   libprotocol.so: .text
[#0 HackStudio(40:40)]: 0x0000000daa4e2000 -- 0x0000000daa4e8fff 0x0000000000007000 R  S   libprotocol.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000daa6e9000 -- 0x0000000daa6ebfff 0x0000000000003000 R      libprotocol.so: .relro
[#0 HackStudio(40:40)]: 0x0000000daa6ec000 -- 0x0000000daa6edfff 0x0000000000002000 RW     libprotocol.so: .data
[#0 HackStudio(40:40)]: 0x0000000dc36a0000 -- 0x0000000dc36affff 0x0000000000010000 RW     malloc: ChunkedBlock(8176)
[#0 HackStudio(40:40)]: 0x0000000e95884000 -- 0x0000000e95889fff 0x0000000000006000 R  S   libgemini.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000e95a84000 -- 0x0000000e95a93fff 0x0000000000010000 R XS   libgemini.so: .text
[#0 HackStudio(40:40)]: 0x0000000e95c84000 -- 0x0000000e95c87fff 0x0000000000004000 R  S   libgemini.so: .rodata
[#0 HackStudio(40:40)]: 0x0000000e95e88000 -- 0x0000000e95e88fff 0x0000000000001000 R      libgemini.so: .relro
[#0 HackStudio(40:40)]: 0x0000000e95e89000 -- 0x0000000e95e89fff 0x0000000000001000 RW     libgemini.so: .data
[#0 HackStudio(40:40)]: 0x0000000f9b490000 -- 0x0000000f9b49ffff 0x0000000000010000 RW     malloc: ChunkedBlock(256)
[#0 HackStudio(40:40)]: 0x0000001003ad0000 -- 0x0000001003adffff 0x0000000000010000 RW     malloc: ChunkedBlock(16)
[#0 HackStudio(40:40)]: 0x0000001049ca0000 -- 0x0000001049caffff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000011384f0000 -- 0x00000011384fffff 0x0000000000010000 RW     malloc: ChunkedBlock(1008)
[#0 HackStudio(40:40)]: 0x000000116e800000 -- 0x000000116e80ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000011788a0000 -- 0x00000011788affff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x000000119594d000 -- 0x000000119594efff 0x0000000000002000 R  S   libipc.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001195b4d000 -- 0x0000001195b51fff 0x0000000000005000 R XS   libipc.so: .text
[#0 HackStudio(40:40)]: 0x0000001195d4d000 -- 0x0000001195d4dfff 0x0000000000001000 R  S   libipc.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001195f4e000 -- 0x0000001195f4efff 0x0000000000001000 R      libipc.so: .relro
[#0 HackStudio(40:40)]: 0x0000001195f4f000 -- 0x0000001195f4ffff 0x0000000000001000 RW     libipc.so: .data
[#0 HackStudio(40:40)]: 0x00000011fbb1b000 -- 0x00000011fbb1dfff 0x0000000000003000 R  S   libsymbolication.so: .rodata
[#0 HackStudio(40:40)]: 0x00000011fbd1b000 -- 0x00000011fbd21fff 0x0000000000007000 R XS   libsymbolication.so: .text
[#0 HackStudio(40:40)]: 0x00000011fbf1b000 -- 0x00000011fbf1bfff 0x0000000000001000 R  S   libsymbolication.so: .rodata
[#0 HackStudio(40:40)]: 0x00000011fc11c000 -- 0x00000011fc11cfff 0x0000000000001000 R      libsymbolication.so: .relro
[#0 HackStudio(40:40)]: 0x00000011fc11d000 -- 0x00000011fc11dfff 0x0000000000001000 RW     libsymbolication.so: .data
[#0 HackStudio(40:40)]: 0x0000001239940000 -- 0x000000123994ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000012402c0000 -- 0x00000012402cffff 0x0000000000010000 RW     malloc: ChunkedBlock(32752)
[#0 HackStudio(40:40)]: 0x000000125dd61000 -- 0x000000125dd66fff 0x0000000000006000 R  S   libmarkdown.so: .rodata
[#0 HackStudio(40:40)]: 0x000000125df61000 -- 0x000000125df6cfff 0x000000000000c000 R XS   libmarkdown.so: .text
[#0 HackStudio(40:40)]: 0x000000125e161000 -- 0x000000125e162fff 0x0000000000002000 R  S   libmarkdown.so: .rodata
[#0 HackStudio(40:40)]: 0x000000125e363000 -- 0x000000125e363fff 0x0000000000001000 R      libmarkdown.so: .relro
[#0 HackStudio(40:40)]: 0x000000125e364000 -- 0x000000125e364fff 0x0000000000001000 RW     libmarkdown.so: .data
[#0 HackStudio(40:40)]: 0x00000012925e0000 -- 0x00000012925effff 0x0000000000010000 RW     malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x000000129b850000 -- 0x000000129b85ffff 0x0000000000010000 RW     malloc: ChunkedBlock(256)
[#0 HackStudio(40:40)]: 0x00000012bbd50000 -- 0x00000012bbd5ffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000012fcf10000 -- 0x00000012fcf1ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x000000141f120000 -- 0x000000141f12ffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000014397b0000 -- 0x00000014397bffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x000000143b750000 -- 0x000000143b75ffff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000014ada91000 -- 0x00000014ada98fff 0x0000000000008000 R  S   libdebug.so: .rodata
[#0 HackStudio(40:40)]: 0x00000014adc91000 -- 0x00000014adcaafff 0x000000000001a000 R XS   libdebug.so: .text
[#0 HackStudio(40:40)]: 0x00000014ade91000 -- 0x00000014ade95fff 0x0000000000005000 R  S   libdebug.so: .rodata
[#0 HackStudio(40:40)]: 0x00000014ae096000 -- 0x00000014ae096fff 0x0000000000001000 R      libdebug.so: .relro
[#0 HackStudio(40:40)]: 0x00000014ae097000 -- 0x00000014ae097fff 0x0000000000001000 RW     libdebug.so: .data
[#0 HackStudio(40:40)]: 0x00000014d45a0000 -- 0x00000014d45affff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x00000014d6150000 -- 0x00000014d615ffff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000014eae3f000 -- 0x00000014eae41fff 0x0000000000003000 R  S   libtextcodec.so: .rodata
[#0 HackStudio(40:40)]: 0x00000014eb03f000 -- 0x00000014eb042fff 0x0000000000004000 R XS   libtextcodec.so: .text
[#0 HackStudio(40:40)]: 0x00000014eb23f000 -- 0x00000014eb240fff 0x0000000000002000 R  S   libtextcodec.so: .rodata
[#0 HackStudio(40:40)]: 0x00000014eb441000 -- 0x00000014eb441fff 0x0000000000001000 R      libtextcodec.so: .relro
[#0 HackStudio(40:40)]: 0x00000014eb442000 -- 0x00000014eb442fff 0x0000000000001000 RW     libtextcodec.so: .data
[#0 HackStudio(40:40)]: 0x000000153da90000 -- 0x000000153da9ffff 0x0000000000010000 RW     malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x000000155cb90000 -- 0x000000155cb9ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x000000157028b000 -- 0x000000157028cfff 0x0000000000002000 R  S   libthreading.so: .rodata
[#0 HackStudio(40:40)]: 0x000000157048b000 -- 0x000000157048dfff 0x0000000000003000 R XS   libthreading.so: .text
[#0 HackStudio(40:40)]: 0x000000157068b000 -- 0x000000157068bfff 0x0000000000001000 R  S   libthreading.so: .rodata
[#0 HackStudio(40:40)]: 0x000000157088c000 -- 0x000000157088cfff 0x0000000000001000 R      libthreading.so: .relro
[#0 HackStudio(40:40)]: 0x000000157088d000 -- 0x000000157088dfff 0x0000000000001000 RW     libthreading.so: .data
[#0 HackStudio(40:40)]: 0x00000015b1580000 -- 0x00000015b158ffff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x000000163f050000 -- 0x000000163f05ffff 0x0000000000010000        malloc: ChunkedBlock(32752)
[#0 HackStudio(40:40)]: 0x00000016b0bc0000 -- 0x00000016b0bcffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x000000172f130000 -- 0x000000172f13ffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000001757a96000 -- 0x0000001757a97fff 0x0000000000002000 R  S   libm.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001757c96000 -- 0x0000001757c9bfff 0x0000000000006000 R XS   libm.so: .text
[#0 HackStudio(40:40)]: 0x0000001757e96000 -- 0x0000001757e98fff 0x0000000000003000 R  S   libm.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001758098000 -- 0x0000001758098fff 0x0000000000001000 R      libm.so: .relro
[#0 HackStudio(40:40)]: 0x0000001758099000 -- 0x0000001758099fff 0x0000000000001000 RW     libm.so: .data
[#0 HackStudio(40:40)]: 0x00000017c92c1000 -- 0x00000017c92c1fff 0x0000000000001000 R  S   libsystem.so: .rodata
[#0 HackStudio(40:40)]: 0x00000017c94c1000 -- 0x00000017c94c1fff 0x0000000000001000 R XS C libsystem.so: .text
[#0 HackStudio(40:40)]: 0x00000017c96c1000 -- 0x00000017c96c1fff 0x0000000000001000 R  S   libsystem.so: .rodata
[#0 HackStudio(40:40)]: 0x00000017c98c1000 -- 0x00000017c98c1fff 0x0000000000001000 R      libsystem.so: .relro
[#0 HackStudio(40:40)]: 0x0000001814528000 -- 0x0000001814530fff 0x0000000000009000 R  S   libtls.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001814728000 -- 0x0000001814751fff 0x000000000002a000 R XS   libtls.so: .text
[#0 HackStudio(40:40)]: 0x0000001814928000 -- 0x000000181492efff 0x0000000000007000 R  S   libtls.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001814b2f000 -- 0x0000001814b2ffff 0x0000000000001000 R      libtls.so: .relro
[#0 HackStudio(40:40)]: 0x0000001814b30000 -- 0x0000001814b30fff 0x0000000000001000 RW     libtls.so: .data
[#0 HackStudio(40:40)]: 0x0000001823430000 -- 0x000000182343ffff 0x0000000000010000 RW     malloc: ChunkedBlock(32)
[#0 HackStudio(40:40)]: 0x00000018242cc000 -- 0x00000018242dcfff 0x0000000000011000 R  S   libregex.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018244cc000 -- 0x0000001824510fff 0x0000000000045000 R XS   libregex.so: .text
[#0 HackStudio(40:40)]: 0x00000018246cc000 -- 0x00000018246d3fff 0x0000000000008000 R  S   libregex.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018248d3000 -- 0x00000018248d4fff 0x0000000000002000 R      libregex.so: .relro
[#0 HackStudio(40:40)]: 0x00000018248d5000 -- 0x00000018248d5fff 0x0000000000001000 RW     libregex.so: .data
[#0 HackStudio(40:40)]: 0x000000187a7a0000 -- 0x000000187a7affff 0x0000000000010000        malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000018800d0000 -- 0x00000018800d1fff 0x0000000000002000 R  S   libpthread.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018802d0000 -- 0x00000018802d1fff 0x0000000000002000 R XS   libpthread.so: .text
[#0 HackStudio(40:40)]: 0x00000018804d0000 -- 0x00000018804d1fff 0x0000000000002000 R  S   libpthread.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018806d1000 -- 0x00000018806d1fff 0x0000000000001000 R      libpthread.so: .relro
[#0 HackStudio(40:40)]: 0x00000018806d2000 -- 0x00000018806d2fff 0x0000000000001000 RW     libpthread.so: .data
[#0 HackStudio(40:40)]: 0x000000189125d000 -- 0x0000001891273fff 0x0000000000017000 R  S   libcore.so: .rodata
[#0 HackStudio(40:40)]: 0x000000189145d000 -- 0x00000018914a0fff 0x0000000000044000 R XS   libcore.so: .text
[#0 HackStudio(40:40)]: 0x000000189165d000 -- 0x0000001891669fff 0x000000000000d000 R  S   libcore.so: .rodata
[#0 HackStudio(40:40)]: 0x000000189186a000 -- 0x000000189186cfff 0x0000000000003000 R      libcore.so: .relro
[#0 HackStudio(40:40)]: 0x000000189186d000 -- 0x000000189186dfff 0x0000000000001000 RW     libcore.so: .data
[#0 HackStudio(40:40)]: 0x000000189db7d000 -- 0x000000189dd1dfff 0x00000000001a1000 R  S   libweb.so: .rodata
[#0 HackStudio(40:40)]: 0x000000189dd7d000 -- 0x000000189e107fff 0x000000000038b000 R XS   libweb.so: .text
[#0 HackStudio(40:40)]: 0x000000189e17d000 -- 0x000000189e203fff 0x0000000000087000 R  S   libweb.so: .rodata
[#0 HackStudio(40:40)]: 0x000000189e404000 -- 0x000000189e436fff 0x0000000000033000 R      libweb.so: .relro
[#0 HackStudio(40:40)]: 0x000000189e437000 -- 0x000000189e445fff 0x000000000000f000 RW     libweb.so: .data
[#0 HackStudio(40:40)]: 0x00000018abc80000 -- 0x00000018abc8ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x00000018f25ce000 -- 0x00000018f2604fff 0x0000000000037000 R  S   libshell.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018f27ce000 -- 0x00000018f2871fff 0x00000000000a4000 R XS   libshell.so: .text
[#0 HackStudio(40:40)]: 0x00000018f29ce000 -- 0x00000018f29e3fff 0x0000000000016000 R  S   libshell.so: .rodata
[#0 HackStudio(40:40)]: 0x00000018f2be3000 -- 0x00000018f2be9fff 0x0000000000007000 R      libshell.so: .relro
[#0 HackStudio(40:40)]: 0x00000018f2bea000 -- 0x00000018f2beafff 0x0000000000001000 RW     libshell.so: .data
[#0 HackStudio(40:40)]: 0x0000001978710000 -- 0x000000197871ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x0000001a1abc0000 -- 0x0000001a1abcffff 0x0000000000010000 RW     malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000001a2cdd0000 -- 0x0000001a2cddffff 0x0000000000010000 RW     malloc: ChunkedBlock(1008)
[#0 HackStudio(40:40)]: 0x0000001a4e9d0000 -- 0x0000001a4e9dffff 0x0000000000010000 RW     malloc: ChunkedBlock(2032)
[#0 HackStudio(40:40)]: 0x0000001a5cad1000 -- 0x0000001a5cba8fff 0x00000000000d8000 R  S   libjs.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001a5ccd1000 -- 0x0000001a5cf57fff 0x0000000000287000 R XS   libjs.so: .text
[#0 HackStudio(40:40)]: 0x0000001a5d0d1000 -- 0x0000001a5d129fff 0x0000000000059000 R  S   libjs.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001a5d329000 -- 0x0000001a5d345fff 0x000000000001d000 R      libjs.so: .relro
[#0 HackStudio(40:40)]: 0x0000001a5d346000 -- 0x0000001a5d347fff 0x0000000000002000 RW     libjs.so: .data
[#0 HackStudio(40:40)]: 0x0000001a8c16b000 -- 0x0000001a8c178fff 0x000000000000e000 R  S   libline.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001a8c36b000 -- 0x0000001a8c390fff 0x0000000000026000 R XS   libline.so: .text
[#0 HackStudio(40:40)]: 0x0000001a8c56b000 -- 0x0000001a8c573fff 0x0000000000009000 R  S   libline.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001a8c774000 -- 0x0000001a8c776fff 0x0000000000003000 R      libline.so: .relro
[#0 HackStudio(40:40)]: 0x0000001a8c777000 -- 0x0000001a8c777fff 0x0000000000001000 RW     libline.so: .data
[#0 HackStudio(40:40)]: 0x0000001aa1f10000 -- 0x0000001aa1f2bfff 0x000000000001c000 R  S   libsql.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001aa2110000 -- 0x0000001aa2160fff 0x0000000000051000 R XS   libsql.so: .text
[#0 HackStudio(40:40)]: 0x0000001aa2310000 -- 0x0000001aa231cfff 0x000000000000d000 R  S   libsql.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001aa251d000 -- 0x0000001aa251ffff 0x0000000000003000 R      libsql.so: .relro
[#0 HackStudio(40:40)]: 0x0000001aa2520000 -- 0x0000001aa2520fff 0x0000000000001000 RW     libsql.so: .data
[#0 HackStudio(40:40)]: 0x0000001ac3b20000 -- 0x0000001ac3b2ffff 0x0000000000010000 RW     malloc: ChunkedBlock(496)
[#0 HackStudio(40:40)]: 0x0000001ada040000 -- 0x0000001ada04ffff 0x0000000000010000 RW     malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x0000001b073d0000 -- 0x0000001b073dffff 0x0000000000010000        malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x0000001ba5e90000 -- 0x0000001ba5e9ffff 0x0000000000010000 RW     malloc: ChunkedBlock(64)
[#0 HackStudio(40:40)]: 0x0000001bd7200000 -- 0x0000001bd720ffff 0x0000000000010000 RW     malloc: ChunkedBlock(496)
[#0 HackStudio(40:40)]: 0x0000001bd81a8000 -- 0x0000001bd81b2fff 0x000000000000b000 R  S   libcrypto.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001bd83a8000 -- 0x0000001bd83c5fff 0x000000000001e000 R XS   libcrypto.so: .text
[#0 HackStudio(40:40)]: 0x0000001bd85a8000 -- 0x0000001bd85affff 0x0000000000008000 R  S   libcrypto.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001bd87b0000 -- 0x0000001bd87b0fff 0x0000000000001000 R      libcrypto.so: .relro
[#0 HackStudio(40:40)]: 0x0000001bd87b1000 -- 0x0000001bd87b1fff 0x0000000000001000 RW     libcrypto.so: .data
[#0 HackStudio(40:40)]: 0x0000001c437e0000 -- 0x0000001c437effff 0x0000000000010000 RW     malloc: ChunkedBlock(256)
[#0 HackStudio(40:40)]: 0x0000001c87130000 -- 0x0000001c8713ffff 0x0000000000010000 RW     malloc: ChunkedBlock(32)
[#0 HackStudio(40:40)]: 0x0000001cc678a000 -- 0x0000001cc678afff 0x0000000000001000 R  S   libcrypt.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001cc698a000 -- 0x0000001cc698afff 0x0000000000001000 R XS   libcrypt.so: .text
[#0 HackStudio(40:40)]: 0x0000001cc6b8a000 -- 0x0000001cc6b8afff 0x0000000000001000 R  S   libcrypt.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001cc6d8a000 -- 0x0000001cc6d8afff 0x0000000000001000 R      libcrypt.so: .relro
[#0 HackStudio(40:40)]: 0x0000001cc6d8b000 -- 0x0000001cc6d8bfff 0x0000000000001000 RW     libcrypt.so: .data
[#0 HackStudio(40:40)]: 0x0000001d735f7000 -- 0x0000001d7360dfff 0x0000000000017000 R XS   libgcc_s.so: .text
[#0 HackStudio(40:40)]: 0x0000001d7380d000 -- 0x0000001d7380dfff 0x0000000000001000 RW     libgcc_s.so: .data
[#0 HackStudio(40:40)]: 0x0000001d76950000 -- 0x0000001d7695ffff 0x0000000000010000        malloc: ChunkedBlock(4080)
[#0 HackStudio(40:40)]: 0x0000001de1930000 -- 0x0000001de193ffff 0x0000000000010000 RW     malloc: ChunkedBlock(128)
[#0 HackStudio(40:40)]: 0x0000001de9030000 -- 0x0000001de904ffff 0x0000000000020000 R  S   libgfx.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001de9230000 -- 0x0000001de92a7fff 0x0000000000078000 R XS   libgfx.so: .text
[#0 HackStudio(40:40)]: 0x0000001de9430000 -- 0x0000001de94befff 0x000000000008f000 R  S   libgfx.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001de96be000 -- 0x0000001de96c0fff 0x0000000000003000 R      libgfx.so: .relro
[#0 HackStudio(40:40)]: 0x0000001de96c1000 -- 0x0000001de96c1fff 0x0000000000001000 RW     libgfx.so: .data
[#0 HackStudio(40:40)]: 0x0000001dee3a0000 -- 0x0000001dee3affff 0x0000000000010000 RW     malloc: ChunkedBlock(496)
[#0 HackStudio(40:40)]: 0x0000001ed0cae000 -- 0x0000001ed0caefff 0x0000000000001000 R  S   libsyntax.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001ed0eae000 -- 0x0000001ed0eaefff 0x0000000000001000 R XS   libsyntax.so: .text
[#0 HackStudio(40:40)]: 0x0000001ed10ae000 -- 0x0000001ed10aefff 0x0000000000001000 R  S   libsyntax.so: .rodata
[#0 HackStudio(40:40)]: 0x0000001ed12ae000 -- 0x0000001ed12aefff 0x0000000000001000 R      libsyntax.so: .relro
[#0 HackStudio(40:40)]: 0x0000001ed12af000 -- 0x0000001ed12affff 0x0000000000001000 RW     libsyntax.so: .data
[#0 HackStudio(40:40)]: 0x0000001fb9500000 -- 0x0000001fb950ffff 0x0000000000010000        malloc: ChunkedBlock(496)
[#0 HackStudio(40:40)]: Kernel regions:
[#0 HackStudio(40:40)]: BEGIN                 END                SIZE               ACCESS NAME
[#0 HackStudio(40:40)]: 0x0000002003003000 -- 0x0000002003102fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x0000002003106000 -- 0x0000002003106fff 0x0000000000001000 RW     HPET MMIO
[#0 HackStudio(40:40)]: 0x0000002003108000 -- 0x0000002003108fff 0x0000000000001000 RW     Time page
[#0 HackStudio(40:40)]: 0x000000200310a000 -- 0x000000200310afff 0x0000000000001000 R    C Signal trampolines
[#0 HackStudio(40:40)]: 0x000000200310c000 -- 0x000000200311bfff 0x0000000000010000 RW  T  Kernel stack (thread 0)
[#0 HackStudio(40:40)]: 0x000000200312e000 -- 0x000000200313dfff 0x0000000000010000 RW  T  Kernel stack (thread 2)
[#0 HackStudio(40:40)]: 0x000000200313f000 -- 0x000000200313ffff 0x0000000000001000 RW     
[#0 HackStudio(40:40)]: 0x0000002003416000 -- 0x0000002003425fff 0x0000000000010000 RW  T  Kernel stack (thread 3)
[#0 HackStudio(40:40)]: 0x0000002003427000 -- 0x0000002003436fff 0x0000000000010000 RW  T  Kernel stack (thread 4)
[#0 HackStudio(40:40)]: 0x00000020043d6000 -- 0x00000020043e5fff 0x0000000000010000 RW  T  Kernel stack (thread 5)
[#0 HackStudio(40:40)]: 0x0000002003438000 -- 0x0000002003438fff 0x0000000000001000  W     UHCI Framelist
[#0 HackStudio(40:40)]: 0x000000200343a000 -- 0x000000200343afff 0x0000000000001000 RW     UHCI Descriptor Pool
[#0 HackStudio(40:40)]: 0x000000200343c000 -- 0x000000200343cfff 0x0000000000001000 RW     UHCI Descriptor Pool
[#0 HackStudio(40:40)]: 0x000000200343e000 -- 0x000000200343efff 0x0000000000001000 RW     UHCI Isochronous Descriptor Pool
[#0 HackStudio(40:40)]: 0x00000020043e7000 -- 0x00000020043e7fff 0x0000000000001000 RW     E1000 RX Descriptors
[#0 HackStudio(40:40)]: 0x00000020043e9000 -- 0x00000020043e9fff 0x0000000000001000 RW     E1000 TX Descriptors
[#0 HackStudio(40:40)]: 0x00000020043eb000 -- 0x000000200440afff 0x0000000000020000 RW     E1000 MMIO
[#0 HackStudio(40:40)]: 0x000000200440c000 -- 0x000000200444bfff 0x0000000000040000 RW     E1000 RX buffers
[#0 HackStudio(40:40)]: 0x000000200444d000 -- 0x000000200445cfff 0x0000000000010000 RW     E1000 TX buffers
[#0 HackStudio(40:40)]: 0x000000200445e000 -- 0x000000200445efff 0x0000000000001000 RW     E1000 RX Descriptors
[#0 HackStudio(40:40)]: 0x0000002004460000 -- 0x0000002004460fff 0x0000000000001000 RW     E1000 TX Descriptors
[#0 HackStudio(40:40)]: 0x0000002004462000 -- 0x0000002004481fff 0x0000000000020000 RW     E1000 MMIO
[#0 HackStudio(40:40)]: 0x0000002004483000 -- 0x00000020044c2fff 0x0000000000040000 RW     E1000 RX buffers
[#0 HackStudio(40:40)]: 0x00000020044c4000 -- 0x00000020044d3fff 0x0000000000010000 RW     E1000 TX buffers
[#0 HackStudio(40:40)]: 0x00000020044d5000 -- 0x00000020044d5fff 0x0000000000001000 RW     IDE PRDT
[#0 HackStudio(40:40)]: 0x00000020044d7000 -- 0x00000020044d7fff 0x0000000000001000 RW     IDE DMA region
[#0 HackStudio(40:40)]: 0x00000020044d9000 -- 0x00000020044d9fff 0x0000000000001000 RW     IDE PRDT
[#0 HackStudio(40:40)]: 0x00000020044db000 -- 0x00000020044dbfff 0x0000000000001000 RW     IDE DMA region
[#0 HackStudio(40:40)]: 0x00000020044dd000 -- 0x00000020044defff 0x0000000000002000 RW     AHCI HBA
[#0 HackStudio(40:40)]: 0x00000020044e0000 -- 0x00000020044e0fff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044e2000 -- 0x00000020044e2fff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044e4000 -- 0x00000020044e4fff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044e6000 -- 0x00000020044e6fff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044e8000 -- 0x00000020044e8fff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044ea000 -- 0x00000020044eafff 0x0000000000001000 RW     AHCI Port Command List
[#0 HackStudio(40:40)]: 0x00000020044ec000 -- 0x0000002006bfbfff 0x0000000002710000 RW     KBuffer
[#0 HackStudio(40:40)]: 0x0000002006bfd000 -- 0x0000002006c72fff 0x0000000000076000 RW     KBuffer
[#0 HackStudio(40:40)]: 0x0000002006c74000 -- 0x0000002006c74fff 0x0000000000001000 RW     Ext2FS: Block group descriptors
[#0 HackStudio(40:40)]: 0x0000002006c76000 -- 0x0000002006c76fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002006c78000 -- 0x0000002006c87fff 0x0000000000010000 RW  T  Kernel stack (thread 6)
[#0 HackStudio(40:40)]: 0x0000002006c89000 -- 0x0000002006c89fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002006c8b000 -- 0x0000002006c8bfff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002006c8d000 -- 0x0000002006c9cfff 0x0000000000010000 RW  T  Kernel stack (thread 7)
[#0 HackStudio(40:40)]: 0x0000002006c9e000 -- 0x0000002006cadfff 0x0000000000010000 RW     Kernel Packet Buffer
[#0 HackStudio(40:40)]: 0x000000200311d000 -- 0x000000200311dfff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x000000200311f000 -- 0x000000200311ffff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002003121000 -- 0x0000002003121fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002003123000 -- 0x0000002003123fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002003125000 -- 0x0000002003125fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002006caf000 -- 0x0000002006ccefff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006cd0000 -- 0x0000002006ceffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006cf1000 -- 0x0000002006d10fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006d12000 -- 0x0000002006d31fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006d33000 -- 0x0000002006d52fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006d54000 -- 0x0000002006d73fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006d75000 -- 0x0000002006d94fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006d96000 -- 0x0000002006db5fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006db7000 -- 0x0000002006dd6fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006dd8000 -- 0x0000002006df7fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006df9000 -- 0x0000002006e18fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006e1a000 -- 0x0000002006e39fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006e3b000 -- 0x0000002006e5afff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006e5c000 -- 0x0000002006e7bfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006e7d000 -- 0x0000002006e9cfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006e9e000 -- 0x0000002006ebdfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006ebf000 -- 0x0000002006edefff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006ee0000 -- 0x0000002006efffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006f01000 -- 0x0000002006f20fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006f22000 -- 0x0000002006f41fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006f43000 -- 0x0000002006f62fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006f64000 -- 0x0000002006f83fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006f85000 -- 0x0000002006fa4fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006fa6000 -- 0x0000002006fc5fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006fc7000 -- 0x0000002006fe6fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002006fe8000 -- 0x0000002007007fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007009000 -- 0x0000002007028fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200702a000 -- 0x0000002007049fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200704b000 -- 0x000000200706afff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200706c000 -- 0x000000200708bfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200708d000 -- 0x00000020070acfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020070ae000 -- 0x00000020070cdfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020070cf000 -- 0x00000020070eefff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020070f0000 -- 0x000000200710ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007111000 -- 0x0000002007130fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007132000 -- 0x0000002007151fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007153000 -- 0x0000002007172fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007185000 -- 0x0000002007194fff 0x0000000000010000 RW  T  Kernel stack (thread 10)
[#0 HackStudio(40:40)]: 0x0000002007196000 -- 0x00000020071a5fff 0x0000000000010000 RW  T  Kernel stack (thread 11)
[#0 HackStudio(40:40)]: 0x00000020071c9000 -- 0x00000020071d8fff 0x0000000000010000 RW  T  Kernel stack (thread 14)
[#0 HackStudio(40:40)]: 0x00000020071da000 -- 0x00000020071e9fff 0x0000000000010000 RW  T  Kernel stack (thread 15)
[#0 HackStudio(40:40)]: 0x00000020071eb000 -- 0x00000020071fafff 0x0000000000010000 RW  T  Kernel stack (thread 16)
[#0 HackStudio(40:40)]: 0x00000020071fc000 -- 0x000000200720bfff 0x0000000000010000 RW  T  Kernel stack (thread 17)
[#0 HackStudio(40:40)]: 0x000000200720d000 -- 0x000000200721cfff 0x0000000000010000 RW  T  Kernel stack (thread 18)
[#0 HackStudio(40:40)]: 0x000000200721e000 -- 0x000000200722dfff 0x0000000000010000 RW  T  Kernel stack (thread 19)
[#0 HackStudio(40:40)]: 0x000000200722f000 -- 0x000000200723efff 0x0000000000010000 RW  T  Kernel stack (thread 20)
[#0 HackStudio(40:40)]: 0x0000002007240000 -- 0x000000200724ffff 0x0000000000010000 RW  T  Kernel stack (thread 21)
[#0 HackStudio(40:40)]: 0x0000002007251000 -- 0x0000002007260fff 0x0000000000010000 RW  T  Kernel stack (thread 22)
[#0 HackStudio(40:40)]: 0x0000002007262000 -- 0x0000002007271fff 0x0000000000010000 RW  T  Kernel stack (thread 23)
[#0 HackStudio(40:40)]: 0x0000002007273000 -- 0x0000002007282fff 0x0000000000010000 RW  T  Kernel stack (thread 24)
[#0 HackStudio(40:40)]: 0x0000002007284000 -- 0x0000002007293fff 0x0000000000010000 RW  T  Kernel stack (thread 25)
[#0 HackStudio(40:40)]: 0x0000002007295000 -- 0x00000020072a4fff 0x0000000000010000 RW  T  Kernel stack (thread 26)
[#0 HackStudio(40:40)]: 0x00000020072a6000 -- 0x00000020073a5fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x00000020074a8000 -- 0x00000020075a7fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x00000020075a9000 -- 0x00000020076a8fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x00000020073b8000 -- 0x00000020073d7fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020073d9000 -- 0x00000020073f8fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020073fa000 -- 0x0000002007419fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200741b000 -- 0x000000200742afff 0x0000000000010000 RW  T  Kernel stack (thread 28)
[#0 HackStudio(40:40)]: 0x000000200742c000 -- 0x000000200744bfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020076aa000 -- 0x0000002007729fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200744d000 -- 0x000000200746cfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200772b000 -- 0x00000020077aafff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020077ac000 -- 0x000000200782bfff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200782d000 -- 0x00000020078acfff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020078ae000 -- 0x00000020078cdfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002003127000 -- 0x0000002003127fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x0000002003129000 -- 0x0000002003129fff 0x0000000000001000 RW     Ext2FS: Cached bitmap block
[#0 HackStudio(40:40)]: 0x000000200746e000 -- 0x000000200748dfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020034d1000 -- 0x00000020037d0fff 0x0000000000300000 RW     Framebuffer Console
[#0 HackStudio(40:40)]: 0x0000002003263000 -- 0x00000020032f2fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x00000020032f4000 -- 0x0000002003383fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x00000020037d2000 -- 0x0000002003861fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x0000002003863000 -- 0x00000020038f2fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x00000020038f4000 -- 0x0000002003983fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x0000002003985000 -- 0x0000002003a14fff 0x0000000000090000 RW     Virtual Console Cells
[#0 HackStudio(40:40)]: 0x0000002003a16000 -- 0x0000002004015fff 0x0000000000600000 RW     Framebuffer
[#0 HackStudio(40:40)]: 0x0000002007ed0000 -- 0x00000020084cffff 0x0000000000600000 RW     Framebuffer Swap (Blank)
[#0 HackStudio(40:40)]: 0x0000002003141000 -- 0x00000020031c0fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020031c2000 -- 0x00000020031c2fff 0x0000000000001000 RW     Packet Buffer
[#0 HackStudio(40:40)]: 0x00000020031c4000 -- 0x0000002003243fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002003385000 -- 0x0000002003404fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004017000 -- 0x0000002004116fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x0000002003440000 -- 0x000000200345ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002003461000 -- 0x0000002003480fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002003482000 -- 0x00000020034a1fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020034a3000 -- 0x00000020034c2fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004118000 -- 0x0000002004137fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004139000 -- 0x0000002004158fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200415a000 -- 0x0000002004179fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200417b000 -- 0x000000200419afff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200419c000 -- 0x00000020041bbfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020041bd000 -- 0x00000020041dcfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020041de000 -- 0x00000020041fdfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020041ff000 -- 0x000000200421efff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004220000 -- 0x000000200423ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004241000 -- 0x0000002004260fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004262000 -- 0x0000002004281fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004283000 -- 0x00000020042a2fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020042a4000 -- 0x00000020042c3fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020042c5000 -- 0x00000020042e4fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020042e6000 -- 0x0000002004305fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004307000 -- 0x0000002004326fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004328000 -- 0x0000002004347fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002004349000 -- 0x0000002004368fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200436a000 -- 0x0000002004389fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200438b000 -- 0x00000020043aafff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020043ac000 -- 0x00000020043cbfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020078cf000 -- 0x00000020078eefff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020078f0000 -- 0x000000200790ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007911000 -- 0x0000002007930fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007932000 -- 0x0000002007951fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007953000 -- 0x0000002007972fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007974000 -- 0x0000002007993fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007995000 -- 0x00000020079b4fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020079b6000 -- 0x00000020079d5fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020079d7000 -- 0x00000020079f6fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020079f8000 -- 0x0000002007a17fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007a19000 -- 0x0000002007a38fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007a3a000 -- 0x0000002007a59fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007a5b000 -- 0x0000002007a7afff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007a7c000 -- 0x0000002007a9bfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007a9d000 -- 0x0000002007abcfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007abe000 -- 0x0000002007addfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007adf000 -- 0x0000002007afefff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007b00000 -- 0x0000002007b1ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007b21000 -- 0x0000002007b40fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007b42000 -- 0x0000002007b61fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007b63000 -- 0x0000002007b82fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007b84000 -- 0x0000002007ba3fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007ba5000 -- 0x0000002007bc4fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007bc6000 -- 0x0000002007be5fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007be7000 -- 0x0000002007c06fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007c08000 -- 0x0000002007c27fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002003245000 -- 0x0000002003254fff 0x0000000000010000 RW  T  Kernel stack (thread 29)
[#0 HackStudio(40:40)]: 0x0000002007c29000 -- 0x0000002007c48fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007c4a000 -- 0x0000002007c69fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007c6b000 -- 0x0000002007c8afff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007c8c000 -- 0x0000002007d0bfff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007d0d000 -- 0x0000002007d8cfff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007d8e000 -- 0x0000002007e0dfff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007e0f000 -- 0x0000002007e8efff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020084d1000 -- 0x0000002008550fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008d54000 -- 0x0000002008dd3fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008953000 -- 0x00000020089d2fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008552000 -- 0x00000020085d1fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007eb1000 -- 0x0000002007ec0fff 0x0000000000010000 RW  T  Kernel stack (thread 35)
[#0 HackStudio(40:40)]: 0x0000002008699000 -- 0x00000020086b8fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020086ba000 -- 0x00000020086d9fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020086db000 -- 0x00000020086fafff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020086fc000 -- 0x000000200871bfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200871d000 -- 0x000000200873cfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200dd54000 -- 0x0000002012551fff 0x00000000047fe000 RW     KBuffer
[#0 HackStudio(40:40)]: 0x00000020095d7000 -- 0x000000200a17afff 0x0000000000ba4000 RW     KBuffer
[#0 HackStudio(40:40)]: 0x00000020071a7000 -- 0x00000020071b6fff 0x0000000000010000 RW  T  Kernel stack (thread 39)
[#0 HackStudio(40:40)]: 0x00000020085d3000 -- 0x0000002008652fff 0x0000000000080000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200748f000 -- 0x000000200749efff 0x0000000000010000 RW  T  Kernel stack (thread 40)
[#0 HackStudio(40:40)]: 0x0000002008654000 -- 0x0000002008673fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008675000 -- 0x0000002008694fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200873e000 -- 0x000000200875dfff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200875f000 -- 0x000000200877efff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008780000 -- 0x000000200879ffff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020087e3000 -- 0x0000002008802fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008804000 -- 0x0000002008823fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002007e90000 -- 0x0000002007e9ffff 0x0000000000010000 RW  T  Kernel stack (thread 42)
[#0 HackStudio(40:40)]: 0x0000002008825000 -- 0x0000002008844fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008846000 -- 0x0000002008865fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008867000 -- 0x0000002008876fff 0x0000000000010000 RW  T  Kernel stack (thread 43)
[#0 HackStudio(40:40)]: 0x00000020089d4000 -- 0x0000002008ad3fff 0x0000000000100000 RW     kmalloc subheap
[#0 HackStudio(40:40)]: 0x0000002008878000 -- 0x0000002008897fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x0000002008899000 -- 0x00000020088b8fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020088ba000 -- 0x00000020088d9fff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x00000020088db000 -- 0x00000020088fafff 0x0000000000020000 RW     DoubleBuffer
[#0 HackStudio(40:40)]: 0x000000200a97e000 -- 0x000000200ad7dfff 0x0000000000400000 RW     KBuffer
[#0 HackStudio(40:40)]: 0x0000002008dd5000 -- 0x00000020091d4fff 0x0000000000400000 RW     KBuffer
[#0 FinalizerTask(4:4)]: Generating coredump for pid: 40
CrashDaemon(39:39): New coredump file: /tmp/coredump/HackStudio_40_1631869611
```

</details>

### PR DESCRIPTION
**Pull request by itamar8910**
`getauxval()` always re-calculated the address of the auxiliary vector by traversing to the end of the `environ` pointer, but the `environ` array may get re-allocated at runtime which caused `getauxval()` to work with an incorrect auxiliary vector address.

Fixes #10087.

### CODE REVIEW

File: Userland/Libraries/LibELF/DynamicLinker.cpp [hunk 1]
```diff
@@ -226,6 +226,10 @@ static void initialize_libc(DynamicObject& libc)
     VERIFY(res.has_value());
     *((bool*)res.value().address.as_ptr()) = false;
 
+    res = libc.lookup_symbol("__auxiliary_vector"sv);
+    VERIFY(res.has_value());
+    *((void**)res.value().address.as_ptr()) = nullptr;
```
Comment (BenWiederhake) [inline Userland/Libraries/LibELF/DynamicLinker.cpp:231]: Out of curiosity: Either this symbol exists, or it doesn't. If it doesn't exist, there's no real reason to `VERIFY(false)` here. If it does exist, it will be initialized when we call `__libc_init` a few lines down. Until then, nothing will access `__auxiliary_vector` anyway.

So, what does this code do?

Comment (itamar8910) [reply Userland/Libraries/LibELF/DynamicLinker.cpp]: Right, no point in initializing it here :+1:

Comment (itamar8910) [reply Userland/Libraries/LibELF/DynamicLinker.cpp]: (I also removed another redundant initialization in the DynamicLoader's `init_libc`).

**Comment by awesomekling** [comment]
Dude, great catch!
