### PR TITLE
LibJS: Add and begin using a completion-compatible string builder

### LINKED ISSUE #16814: LibJS assertion failed: !_temporary_result.is_error()
The following JS code produces an assertion failure
```js
a = ' ';
a.repeat(2**32);null 
```

### PR DESCRIPTION
**Pull request by trflynn89**
`ThrowableStringBuilder` is a thin wrapper around `StringBuilder` to map results from the `try_*` methods to a throw completion. This will let us try to throw on OOM conditions rather than just blowing up.

Fixes #16814. We now get:

Screenshot from 2023-01-05 15-35-15

### CODE REVIEW

File: Userland/Libraries/LibJS/Runtime/SafeStringBuilder.cpp [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+SafeStringBuilder::SafeStringBuilder(VM& vm)
+    : m_vm(vm)
+{
+}
+
+ThrowCompletionOr<void> SafeStringBuilder::append(char ch)
+{
+    if (try_append(ch).is_error())
+        return m_vm.throw_completion<RangeError>(ErrorType::NotEnoughMemoryToAllocate, length() + 1);
```
Comment (linusg) [inline Userland/Libraries/LibJS/Runtime/SafeStringBuilder.cpp:19]: Please use `InternalError` for these, I'm not convinced that we should be using `RangeError` for unspec'd OOM situations. Imagine someone doing something that catches such an OOM RangeError, assuming it's related to an ArrayBuffer allocation failure and continuing even though it's totally unrelated string allocation failure.

File: Userland/Libraries/LibJS/Runtime/SafeStringBuilder.cpp [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+{
+    if (try_append(string).is_error())
+        return m_vm.throw_completion<RangeError>(ErrorType::NotEnoughMemoryToAllocate, length() + string.length());
+    return {};
+}
+
+ThrowCompletionOr<void> SafeStringBuilder::append(Utf16View string)
+{
+    if (try_append(string).is_error())
+        return m_vm.throw_completion<RangeError>(ErrorType::NotEnoughMemoryToAllocate, length() + string.length_in_code_units());
```
Comment (linusg) [inline Userland/Libraries/LibJS/Runtime/SafeStringBuilder.cpp:33]: This doesn't seem right, the code units span holds `u16`s, which are two bytes each?

https://github.com/SerenityOS/serenity/blob/3b682e885e492e24aef952050998a2cf1a83f16e/AK/Utf16View.h#L114

**Review by linusg — CHANGES_REQUESTED** [review]
Nice! I'm not convinced about the name through, "safe" doesn't explain what it actually does very well 🤔

**Comment by trflynn89** [comment]
> Nice! I'm not convinced about the name through, "safe" doesn't explain what it actually does very well thinking

Hmm not really sure what to call it. "ThrowableStringBuilder"? :man_shrugging:

**Comment by linusg** [comment]
I don't have a great suggestion either, but that seems better than SafeStringBuilder 👍

**Review by linusg — APPROVED** [review]
