### PR TITLE
Kernel: Start reducing the amount of `RecursiveSpinlock`s

### LINKED ISSUE #22585: Kernel: Intermittent FS lock panic on shutdown with SMP on
With this boot step:

```
SERENITY_RAM_SIZE=1G SERENITY_CPUS=4 ./Meta/serenity.sh run x86_64 Clang smp=on
```

We intermittently panic on shutdown with locks being held by the wrong Processor.

This was reproduced without KVM, on TCG (from my M2 MacBook). 

```
11.946 [#2 Power State Switch Task(48:48)]: Killing remaining processes...
11.950 [#2 Finalizer Task(8:8)]: Init process quitting for shutdown.
12.331 [#1 Power State Switch Task(48:48)]: Locking all file systems...
12.331 [#1 Power State Switch Task(48:48)]: Unmounting all file systems...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 6 for the last time...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 6...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 5 for the last time...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 5...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 4 for the last time...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 4...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 3 for the last time...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 3...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 2 for the last time...
12.335 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 2...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [#1 Power State Switch Task(48:48)]: VirtualFileSystem: Unmounting file system 1...
12.339 [Power State Switch Task(48:48)]: Ext2FS: Clean unmount, setting superblock to valid state
[Power State Switch Task(48:48)]: ASSERTION FAILED: m_lock.load(AK::memory_order_relaxed) == FlatPtr(&Processor::current())
[Power State Switch Task(48:48)]: Kernel/Locking/Spinlock.h:92 in void Kernel::RecursiveSpinlock<Kernel::LockRank::FileSystem>::unlock(InterruptsState) [Rank = Kernel::LockRank::FileSystem]
[Power State Switch Task(48:48)]: KERNEL PANIC! :^(
[Power State Switch Task(48:48)]: Aborted
[Power State Switch Task(48:48)]: at Kernel/Arch/x86_64/CPU.cpp:35 in void abort()
[Power State Switch Task(48:48)]: Kernel + 0x0000000000509c30  Kernel::__panic(char const*, unsigned int, char const*) +0xf0
[Power State Switch Task(48:48)]: Kernel + 0x00000000007dcb59  abort +0x109
[Power State Switch Task(48:48)]: Kernel + 0x00000000007dca44  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xa4
[Power State Switch Task(48:48)]: Kernel + 0x000000000032449e  Kernel::RecursiveSpinlock<(Kernel::LockRank)4>::unlock(Kernel::InterruptsState) +0x25e
[Power State Switch Task(48:48)]: Kernel + 0x0000000000323adb  Kernel::FileSystem::prepare_to_unmount(Kernel::Inode&) +0x24b
[Power State Switch Task(48:48)]: Kernel + 0x000000000042b913  Kernel::VirtualFileSystem::unmount(Kernel::Inode&, AK::StringView) +0x5e3
[Power State Switch Task(48:48)]: Kernel + 0x00000000007296e1  Kernel::PowerStateSwitchTask::perform_shutdown(Kernel::PowerStateSwitchTask::DoReboot) +0xf81
[Power State Switch Task(48:48)]: Kernel + 0x000000000072852b  Kernel::PowerStateSwitchTask::power_state_switch_task(void*) +0x8b
```

### PR DESCRIPTION
**Pull request by implicitfield**
The Linux kernel doesn't have any recursive spinlocks at all (well, at least not kernel-wide, IDK about random subsystems), so we certainly don't *need* to have these either. Primarily, these just lead to rather sloppy code (just see all the refactoring in this PR, which could have been fairly easily avoided if we hadn't used these to begin with) and are very SMP-unfriendly (a crash [here](https://github.com/SerenityOS/serenity/blob/93add0a510fe656a56585c124a59efa45b347feb/Kernel/Locking/Spinlock.h#L92) is both commonplace and nigh-impossible to debug).

Historically, the proliferation of `RecursiveSpinlock`s has also been brought forward by the fact that `SpinlockProtected` (since its introduction in 019ad8a5, part of #8851) used a `RecursiveSpinlock` under the hood, which was only recently corrected (in a264a833), though this naturally left a ton of instances of `RecursiveSpinlockProtected` all over the place.

This PR is based off of a branch where I removed `RecursiveSpinlock` entirely, but that didn't really pan out for SMP systems either, because when you put a proper `Spinlock` on the scheduler, only a single thread can run at a time. In the long term, it might prove favorable to rework the scheduling in an xv6-style way, where each CPU has its own instance of the scheduler (at least that would make the locking less of a nightmare).

In conclusion, this PR shouldn't have much of an impact on the behavior of the system, but it should be a good step towards getting rid of `RecursiveSpinlock`s entirely. This probably fixes #22585 because nothing in `Kernel/FileSystem` uses `RecursiveSpinlock`s anymore, but otherwise this shouldn't affect the stability of SMP systems in one way or another.

### CODE REVIEW

File: Kernel/FileSystem/DevPtsFS/FileSystem.cpp [hunk 1]
```diff
@@ -61,18 +61,31 @@ ErrorOr<NonnullRefPtr<Inode>> DevPtsFS::get_inode(InodeIdentifier inode_id) cons
...
     inode->m_metadata.inode = inode_id;
     inode->m_metadata.size = 0;
-    inode->m_metadata.uid = pts_device.uid();
-    inode->m_metadata.gid = pts_device.gid();
+    inode->m_metadata.uid = pty_uid;
+    inode->m_metadata.gid = pty_gid;
     inode->m_metadata.mode = 0020600;
-    inode->m_metadata.major_device = device->major();
-    inode->m_metadata.minor_device = device->minor();
+    inode->m_metadata.major_device = 201;
```
Comment (Hendiadyoin1) [inline Kernel/FileSystem/DevPtsFS/FileSystem.cpp:87]: Where does this magic number come from now?

**Review by Hendiadyoin1 — COMMENTED** [review]
Just one thing that stuck out to me
(Also I should revive #20619, as that plays into this)

File: Kernel/Syscalls/prctl.cpp [hunk 2]
```diff
@@ -12,111 +12,113 @@ namespace Kernel {
 ErrorOr<FlatPtr> Process::sys$prctl(int option, FlatPtr arg1, FlatPtr arg2, FlatPtr arg3)
 {
     VERIFY_NO_PROCESS_BIG_LOCK(this);
-    return with_mutable_protected_data([&](auto& protected_data) -> ErrorOr<FlatPtr> {
-        switch (option) {
-        case PR_GET_DUMPABLE:
+    switch (option) {
+    case PR_GET_DUMPABLE:
+        return with_protected_data([&](auto& protected_data) {
```
Comment (Hendiadyoin1) [inline Kernel/Syscalls/prctl.cpp:17]: Looking at the `SpinLockProtectedBase`, exposing it's internal RAII-like `Locker` with a nice name
like `acquire()` or `access()` may make this code a bit nicer (and probably all other users that blew up in size

File: Kernel/FileSystem/Custody.cpp
Comment (Hendiadyoin1) [inline Kernel/FileSystem/Custody.cpp:1]: Bit unfortunate that we loose this, any guess how bad this is for testing performance or the like?

**Review by Hendiadyoin1 — COMMENTED** [review]
Two more things on the second read-through,
otherwise looks fine by me

File: Kernel/FileSystem/Custody.cpp
Comment (Hendiadyoin1) [reply Kernel/FileSystem/Custody.cpp:1]: interesting

File: Kernel/Syscalls/prctl.cpp (hunk 2 above)
Comment (Hendiadyoin1) [reply Kernel/Syscalls/prctl.cpp:17]: Weren't many places then entering the scope again, or was I misreading things

Comment (Hendiadyoin1) [reply Kernel/Syscalls/prctl.cpp:17]: Ah checker locally, where I can hide whitespace changes, and yeeh only two places where actually using that lock

**Review by spholz — COMMENTED** [review]
Here is my first review. I still need to look at all the "Prefer non-recursive Spinlocks" commits if it's safe to use non-recursive spinlocks in all those cases.

File: Kernel/Heap/kmalloc.cpp [hunk 3]
```diff
@@ -37,7 +37,9 @@ nothrow_t const nothrow;
 }
 
 // FIXME: Figure out whether this can be MemoryManager.
-static RecursiveSpinlock<LockRank::None> s_lock {}; // needs to be recursive because of dump_backtrace()
+static Spinlock<LockRank::None> s_lock {};
+
+static void* kmalloc_impl(size_t size, size_t alignment, CallerWillInitializeMemory caller_will_initialize_memory, bool acquire_lock);
```
[the remark this answers is not in the document]
Comment (Hendiadyoin1) [reply Kernel/Heap/kmalloc.cpp:42]: In theory we could set a global variable during panic to disable the lock, as we are going down anyway,
but that's likely a thing for another day

File: Kernel/Devices/Generic/DeviceControlDevice.cpp [hunk 4]
```diff
@@ -66,15 +66,18 @@ ErrorOr<void> DeviceControlDevice::ioctl(OpenFileDescription&, unsigned request,
...
+        LockRefPtr<LoopDevice> loop_device;
+        Device::run_by_type_and_major_minor_numbers(DeviceNodeType::Block, to_underlying(MajorAllocation::BlockDeviceFamily::Loop), index, [&](RefPtr<Device> device) {
+            if (device)
+                loop_device = static_cast<LoopDevice&>(*device);
         });
+
+        if (!loop_device)
+            return Error::from_errno(ENODEV);
+
+        loop_device->remove({});
```
[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/Devices/Generic/DeviceControlDevice.cpp]: Yeah we should get rid of all `*Lock*Ptr`s. They only protect the pointer, not the pointed-to object.

These classes were just a hack fix for some old synchronization issues in the kernel.

File: Kernel/FileSystem/BlockBasedFileSystem.cpp [hunk 5]
```diff
@@ -126,8 +126,8 @@ ErrorOr<void> BlockBasedFileSystem::initialize_while_locked()
     VERIFY(m_lock.is_locked());
     VERIFY(!is_initialized_while_locked());
     VERIFY(logical_block_size() != 0);
-    auto cached_block_data = TRY(KBuffer::try_create_with_size("BlockBasedFS: Cache blocks"sv, DiskCache::EntryCount * logical_block_size()));
-    auto entries_data = TRY(KBuffer::try_create_with_size("BlockBasedFS: Cache entries"sv, DiskCache::EntryCount * sizeof(CacheEntry)));
+    auto cached_block_data = TRY(KBuffer::try_create_with_size("BlockBasedFS: Cache blocks"sv, DiskCache::EntryCount * logical_block_size(), Memory::Region::Access::ReadWrite, AllocationStrategy::AllocateNow));
+    auto entries_data = TRY(KBuffer::try_create_with_size("BlockBasedFS: Cache entries"sv, DiskCache::EntryCount * sizeof(CacheEntry), Memory::Region::Access::ReadWrite, AllocationStrategy::AllocateNow));
```
[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/FileSystem/BlockBasedFileSystem.cpp:130]: Oh so NVMe completes the request while interrupts are disabled?
We should probably use WorkQueues in the NVMe code tbh.

I think we're currently really bad at keeping interrupt latency low in general.
Interrupt handlers ideally should only do the minimum amount of work so that the interrupt line is disabled again (if the interrupt is level triggered).

[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/FileSystem/BlockBasedFileSystem.cpp:130]: What exactly was the error? Or did it deadlock?

In general, it would be nice if you could add reasons for changes like that in your commit message. This makes your changes easier to follow during review.

File: Kernel/KSyms.cpp [hunk 6]
```diff
@@ -109,16 +110,84 @@ UNMAP_AFTER_INIT static void load_kernel_symbols_from_data(Bytes buffer)
     g_kernel_symbols_available.set();
 }
 
-NEVER_INLINE static void dump_backtrace_impl(FlatPtr frame_pointer, bool use_ksyms, PrintToScreen print_to_screen)
+// Special print helper which avoids allocating any memory at runtime.
+// This is needed because kmalloc can be made to dump backtraces, and
+// we don't want to recursively call kmalloc because that would really mess
+// with its locking.
+NEVER_INLINE static void print(PrintToScreen print_to_screen, FlatPtr address, char const* name, Optional<size_t> symbol_offset, bool kernel)
```
[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/KSyms.cpp]: I guess we could make the `StringBuilder` inline capacity a template parameter. But limiting the line length is good for now I guess.

File: Kernel/Devices/GPU/VirtIO/Console.h [hunk 7]
```diff
@@ -29,8 +29,9 @@ class Console final : public GenericFramebufferConsole {
     virtual void hide_cursor() override;
     virtual void show_cursor() override;
 
-    Console(VirtIODisplayConnector const& parent_display_connector, DisplayConnector::ModeSetting current_resolution);
+    Console(VirtIODisplayConnector const& parent_display_connector, DisplayConnector::ModeSetting current_resolution, NonnullLockRefPtr<Timer> timer);
     NonnullLockRefPtr<VirtIODisplayConnector> m_parent_display_connector;
+    NonnullLockRefPtr<Timer> m_refresh_timer;
```
[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/Devices/GPU/VirtIO/Console.h:34]: `m_parent_display_connector` afaict also doesn't need a `NonnullLockRefPtr`.

File: Kernel/FileSystem/BlockBasedFileSystem.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (spholz) [reply Kernel/FileSystem/BlockBasedFileSystem.cpp:130]: > > Oh so NVMe completes the request while interrupts are disabled?
> 
> I mean with `nvme_poll` enabled there's no crash since we don't use IRQs to drive the requests. That's why I was only able to observe the crash on x86-64 since IRQ-driven NVMe has never worked on AArch64 for some reason.

Oh sorry, I meant that NVMe accesses the disk cache in the interrupt handler, so while interrupts are disabled in the CPU, not while `nvme_poll` is on.

So you mean you need to boot with `nvme_poll` on AArch64? That's weird.

> > What exactly was the error? Or did it deadlock?
> 
> This was just a straight-up panic. I'll amend the commit message in the next push then, I just figured this was a farily straightforward isolated fix at the time.

Oh I didn't know that we panic on purpose if that happens.

File: Kernel/Devices/Device.cpp [hunk 8]
```diff
@@ -44,7 +44,7 @@ UNMAP_AFTER_INIT void Device::initialize_base_devices()
     s_all_details->base_devices = move(base_devices);
 }
 
-RefPtr<Device> Device::acquire_by_type_and_major_minor_numbers(DeviceNodeType type, MajorNumber major, MinorNumber minor)
+void Device::run_by_type_and_major_minor_numbers(DeviceNodeType type, MajorNumber major, MinorNumber minor, Function<void(RefPtr<Device>)> callback)
```
[the remark this answers is not in the document]
Comment (Hendiadyoin1) [reply Kernel/Devices/Device.cpp:47]: A rvalue reference should also work, I think

File: Kernel/Memory/MemoryManager.h [hunk 9]
```diff
@@ -307,7 +299,7 @@ class MemoryManager {
     PhysicalPageEntry* m_physical_page_entries { nullptr };
     size_t m_physical_page_entries_count { 0 };
 
-    RecursiveSpinlockProtected<GlobalData, LockRank::None> m_global_data;
+    SpinlockProtected<GlobalData, LockRank::None> m_global_data;
```
Comment (spholz) [inline Kernel/Memory/MemoryManager.h:302]: This is locked twice during `find_rsdp_in_ia_pc_specific_memory_locations` if the RSDP wasn't found in the BIOS/EBDA. First by `MemoryManager::for_each_physical_memory_range` and then by `MemoryManager::allocate_mmio_kernel_region`.

**Review by spholz — COMMENTED** [review]
The last 4 commits look fine, except for these 2 small instances of double locking.

**Comment by spholz** [comment]
Thanks for removing all of these `RecursiveSpinlock`s! I agree that we should preferably have less and possibly even none of them.

Reviewing this PR was just a bit annoying since you replaced so many of them at once.
Next time you make such a large refactoring commit that also requires this much attention, please split it into smaller commits and probably even multiple PRs. Thanks!

**Comment by spholz** [comment]
I found a new deadlock(?) with this PR applied:

Running `run-tests` on riscv64 with `FileManager` hangs with this backtrace after running LibELF/TestOrder:
```
(gdb) bt
#0  AK::Atomic<unsigned char, (AK::MemoryOrder)5>::exchange (this=0x2000cc3d50 <initial_kmalloc_memory+7388496>, desired=1 '\001', order=AK::memory_order_acquire) at ././Kernel/Locking/Spinlock.h:29
#1  Kernel::Spinlock<(Kernel::LockRank)0>::lock (this=0x2000cc3d50 <initial_kmalloc_memory+7388496>) at ././Kernel/Locking/Spinlock.h:29
#2  0x0000002000009f7c in Kernel::SpinlockLocker<Kernel::Spinlock<(Kernel::LockRank)0> >::SpinlockLocker (this=0x2017a9f958, lock=<optimized out>) at ././Kernel/Locking/Spinlock.h:135
#3  0x00000020000f4000 in Kernel::SpinlockProtectedBase<AK::HashTable<Kernel::InodeWatcher*, AK::Traits<Kernel::InodeWatcher*>, false>, Kernel::Spinlock<(Kernel::LockRank)0> >::Locked<AK::HashTable<Kernel::InodeWatcher*, AK::Traits<Kernel::InodeWatcher*>, false> >::Locked
    (this=0x2017a9f950, value=..., spinlock=...) at ././Kernel/Locking/SpinlockProtectedBase.h:27
#4  Kernel::SpinlockProtectedBase<AK::HashTable<Kernel::InodeWatcher*, AK::Traits<Kernel::InodeWatcher*>, false>, Kernel::Spinlock<(Kernel::LockRank)0> >::lock_mutable (this=0x2000cc3df0 <initial_kmalloc_memory+7388656>) at ././Kernel/Locking/SpinlockProtectedBase.h:46
#5  Kernel::SpinlockProtectedBase<AK::HashTable<Kernel::InodeWatcher*, AK::Traits<Kernel::InodeWatcher*>, false>, Kernel::Spinlock<(Kernel::LockRank)0> >::with<Kernel::Inode::unregister_watcher(AK::Badge<Kernel::InodeWatcher>, Kernel::InodeWatcher&)::<lambda(auto:199&)> >(struct {...}) (this=this@entry=0x2000cc3d38 <initial_kmalloc_memory+7388472>, callback=...) at ././Kernel/Locking/SpinlockProtectedBase.h:65
#6  0x00000020000f404c in Kernel::Inode::unregister_watcher (this=this@entry=0x2000cc3c80 <initial_kmalloc_memory+7388288>, watcher=<optimized out>) at ./Kernel/FileSystem/Inode.cpp:188
#7  0x00000020000f9d7c in operator()<Kernel::InodeWatcher::WatchMaps> (__closure=__closure@entry=0x2017a9fa30, watch_maps=...) at ././AK/NonnullOwnPtr.h:98
#8  0x00000020000f9e98 in Kernel::SpinlockProtectedBase<Kernel::InodeWatcher::WatchMaps, Kernel::Spinlock<(Kernel::LockRank)0> >::with<Kernel::InodeWatcher::unregister_by_wd(int)::<lambda(auto:198&)> >(struct {...})
    (this=this@entry=0x2000c60870 <initial_kmalloc_memory+6981744>, callback=...) at ././Kernel/Locking/SpinlockProtectedBase.h:66
#9  0x00000020000f9f18 in Kernel::InodeWatcher::unregister_by_wd (this=0x2000c605c0 <initial_kmalloc_memory+6981056>, wd=wd@entry=26) at ./Kernel/FileSystem/InodeWatcher.cpp:150
#10 0x00000020002063bc in Kernel::Process::sys$inode_watcher_remove_watch (this=<optimized out>, fd=9, wd=26) at ./Kernel/Syscalls/inode_watcher.cpp:64
#11 0x00000020001fd9ba in Kernel::Syscall::handle (regs=..., function=<optimized out>, function@entry=67, arg1=<optimized out>, arg1@entry=9, arg2=<optimized out>, arg2@entry=26, arg3=<optimized out>, arg3@entry=26, arg4=<optimized out>, arg4@entry=44669444197)
    at ./Kernel/Syscalls/SyscallHandler.cpp:95
#12 0x00000020001fdf42 in Kernel::syscall_handler (trap=<optimized out>) at ./Kernel/Syscalls/SyscallHandler.cpp:158
#13 0x0000002000242194 in Kernel::trap_handler (trap_frame=...) at ./Kernel/Arch/riscv64/Interrupts.cpp:137
#14 0x0000002000248016 in --- TRAP --- asm_trap_handler (scause=0x8, stval=0x0, sstatus=0x8000000200006020) at ./Kernel/Arch/riscv64/trap_handler.S:153
#15 0x0000000115974052 in Kernel::Syscall::invoke<unsigned long, unsigned long> () at ././Kernel/API/Syscall.h:648
#16 syscall2 () at ./Userland/Libraries/LibSystem/syscall.cpp:24
#17 0x00000014f03757b6 in syscall<Kernel::Syscall::Function, int, int> () at ./Userland/Libraries/LibSystem/syscall.h:35
#18 inode_watcher_remove_watch () at ./Userland/Libraries/LibC/fcntl.cpp:47
#19 0x00000010a95a7f4e in Core::FileWatcherBase::remove_watch () at ./Userland/Libraries/LibCore/FileWatcherSerenity.cpp:144
#20 0x00000010a95a8204 in operator() () at ./Userland/Libraries/LibCore/FileWatcherSerenity.cpp:206
#21 call () at ././AK/Function.h:198
#22 0x000000117368efb2 in AK::Function<void()>::operator() () at ././AK/Function.h:132
#23 Core::Notifier::event () at ./Userland/Libraries/LibCore/Notifier.cpp:63
#24 Core::Notifier::event () at ./Userland/Libraries/LibCore/Notifier.cpp:59
#25 0x000000117368c1f0 in Core::EventReceiver::dispatch_event () at ./Userland/Libraries/LibCore/EventReceiver.cpp:162
#26 0x000000117368e400 in Core::ThreadEventQueue::process () at ./Userland/Libraries/LibCore/ThreadEventQueue.cpp:121
#27 0x0000001173689484 in Core::EventLoopImplementationUnix::pump () at ./Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp:324
#28 Core::EventLoopImplementationUnix::exec () at ./Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp:316
#29 0x0000001173686158 in Core::EventLoop::exec () at ./Userland/Libraries/LibCore/EventLoop.cpp:88
#30 0x0000000cbec815a8 in run_in_windowed_mode () at ./Userland/Applications/FileManager/main.cpp:1333
#31 0x0000000cbec829fc in serenity_main () at ./Userland/Applications/FileManager/main.cpp:159
#32 0x0000000cbec648e4 in main () at ./Userland/Libraries/LibMain/Main.cpp:39
#33 0x0000000cbec64a7c in _entry () at ./Userland/Libraries/LibC/crt0.cpp:47
#34 0x0000000000000000 in ??? ()
```

But no other thread seems to hold that lock afaict. Weird.

File: Kernel/Memory/VMObject.cpp [hunk 10]
```diff
@@ -38,11 +38,18 @@ VMObject::~VMObject()
     VERIFY(m_regions.is_empty());
 }
 
+void VMObject::remap_regions_locked()
```
[the remark this answers is not in the document]
Comment (implicitfield) [reply Kernel/Memory/VMObject.cpp:41]: Likely yes, I've changed those callers to use the locked version.

File: Kernel/Memory/SharedFramebufferVMObject.h [hunk 11]
```diff
@@ -87,7 +87,7 @@ class SharedFramebufferVMObject final : public VMObject {
     LockRefPtr<FakeWritesFramebufferVMObject> m_fake_writes_framebuffer_vmobject;
     LockRefPtr<RealWritesFramebufferVMObject> m_real_writes_framebuffer_vmobject;
     bool m_writes_are_faked { false };
-    mutable RecursiveSpinlock<LockRank::None> m_writes_state_lock {};
+    mutable Spinlock<LockRank::None> m_writes_state_lock {};
```
[the remark this answers is not in the document]
Comment (implicitfield) [reply Kernel/Memory/SharedFramebufferVMObject.h]: Turned this back into a `RecursiveSpinlock` for now, since I don't see any particularly straightforward way to fix this.

File: Kernel/Memory/VMObject.h [hunk 12]
```diff
@@ -63,13 +63,14 @@ class VMObject
...
 
+    void remap_regions_locked();
     void remap_regions();
     bool remap_regions_one_page(size_t page_index, NonnullRefPtr<PhysicalRAMPage> page);
 
     IntrusiveListNode<VMObject> m_list_node;
     FixedArray<RefPtr<PhysicalRAMPage>> m_physical_pages;
 
-    mutable RecursiveSpinlock<LockRank::None> m_lock {};
+    mutable Spinlock<LockRank::None> m_lock {};
```
[the remark this answers is not in the document]
Comment (implicitfield) [reply Kernel/Memory/VMObject.h:73]: Yeah, this is a fairly major change, but I don't think I've seen any issues with this change.

AFAIK static analysis for spinlocks is a bit of an open problem, but it would definitely be nice to have that, it'd just probably take a fair amount of extra tooling.

File: Kernel/Memory/MemoryManager.h (hunk 9 above)
Comment (implicitfield) [reply Kernel/Memory/MemoryManager.h:302]: Used some hacky type-erasure to get around this, thought that solution doesn't feel particularly clean.

**Comment by implicitfield** [comment]
> Reviewing this PR was just a bit annoying since you replaced so many of them at once.
Next time you make such a large refactoring commit that also requires this much attention, please split it into smaller commits and probably even multiple PRs. Thanks!

Sure, the size/complexity of this PR was also a reason why it took a while for me to get back to this (I did always intend to get back to this at some point)

re `/usr/Tests/LibELF/TestOrder`:

I can reproduce the hang on `x86_64` by opening FileManager, pointing it to `/tmp`, then in Terminal running `cd /usr/Tests/LibELF` (the test doesn't work from any other directory), and then running `./TestOrder` four times, where it always causes a hang of specifically the fourth run.

This happens on `master` too though, so I have no idea what the root cause is.

File: Kernel/Memory/MemoryManager.h (hunk 9 above)
Comment (spholz) [reply Kernel/Memory/MemoryManager.h:302]: This function is only used during early boot, so no race conditions should be possible.
I think it would be cleaner to first copy all memory regions into some vector and then try each of them outside of `MM.for_each_physical_memory_range`.

**Comment by spholz** [comment]
> I can reproduce the hang on `x86_64` by opening FileManager, pointing it to `/tmp`, then in Terminal running `cd /usr/Tests/LibELF` (the test doesn't work from any other directory), and then running `./TestOrder` four times, where it always causes a hang of specifically the fourth run.

I don't even need to select `/tmp` in FileManager. I just need to open it and keep it in the home directory. Weird.

> This happens on `master` too though, so I have no idea what the root cause is.

Oh I guess I should have tried that first.

File: Kernel/Memory/MemoryManager.h (hunk 9 above)
Comment (implicitfield) [reply Kernel/Memory/MemoryManager.h:302]: Yeah, that's a quite a bit cleaner stylewise, and I guess this isn't particularly performance-sensitive, so I've implemented this solution. I can't actually test this code path, since QEMU doesn't seem to work this way, but I guess this should work fine.

File: Kernel/Arch/x86_64/Firmware/ACPI.cpp [hunk 13]
```diff
@@ -28,30 +28,36 @@ Optional<PhysicalAddress> find_rsdp_in_ia_pc_specific_memory_locations()
...
         if (region_size_or_error.is_error())
             return IterationDecision::Continue;
-        auto region_or_error = MM.allocate_mmio_kernel_region(memory_range.start, region_size_or_error.value(), {}, Memory::Region::Access::Read);
+
+        (void)potential_ranges.try_append(memory_range);
+        return IterationDecision::Continue;
+    });
+
+    for (auto const& range : potential_ranges) {
+        auto region_or_error = MM.allocate_mmio_kernel_region(range.start, range.length, {}, Memory::Region::Access::Read);
```
Comment (spholz) [inline Kernel/Arch/x86_64/Firmware/ACPI.cpp]: Now you use `range.length` instead of `region_size_or_error` here. That function wants a page-aligned size.

(The `MappedROM::size` should of course be `range.length` though.)

File: Kernel/Arch/x86_64/Firmware/ACPI.cpp [hunk 14]
```diff
@@ -28,30 +28,36 @@ Optional<PhysicalAddress> find_rsdp_in_ia_pc_specific_memory_locations()
...
         if (!(memory_range.type == Memory::PhysicalMemoryRangeType::ACPI_NVS || memory_range.type == Memory::PhysicalMemoryRangeType::ACPI_Reclaimable))
             return IterationDecision::Continue;
 
-        Memory::MappedROM mapping;
         auto region_size_or_error = Memory::page_round_up(memory_range.length);
         if (region_size_or_error.is_error())
             return IterationDecision::Continue;
-        auto region_or_error = MM.allocate_mmio_kernel_region(memory_range.start, region_size_or_error.value(), {}, Memory::Region::Access::Read);
+
+        (void)potential_ranges.try_append(memory_range);
```
Comment (spholz) [inline Kernel/Arch/x86_64/Firmware/ACPI.cpp]: I would use `MUST` here instead of ignoring the error.
We should never run out of memory this early.

Comment (implicitfield) [reply Kernel/Arch/x86_64/Firmware/ACPI.cpp]: We have `append()` too for some reason, which is basically just a wrapper around `try_append()`, so I've used that here now.

File: Kernel/Arch/x86_64/Firmware/ACPI.cpp (hunk 13 above)
Comment (implicitfield) [reply Kernel/Arch/x86_64/Firmware/ACPI.cpp]: Ah, kind of botched this commit. I think this should be good now, and the diff should be nicer too.

**Review by spholz — APPROVED** [review]
