### PR TITLE
FileSystemAccessServer+TextEditor: Implement cross-process modal prompts

### LINKED ISSUE #8628: TextEditor: App becomes unresponsive when opening a file
Steps to reproduce:

1. File -> Open
2. Wait a few seconds.

image

cc @timmot

### LINKED ISSUE #8630: TextEditor: Open dialog is not a modal dialog
This is because the dialog belongs to another process. It does however allow the user to resize the parent window and make other changes to it while the file picker is open.

cc @timmot

### PR DESCRIPTION
**Pull request by timmot**
~~The FilePicker is modal-like while the prompts are synchronous, I'm unsure if we should merge this without also solving #8630~~

~~Also, with this new complexity in the FileSystemAccessClient it is probably better to move it to a library.~~

Fixes #8628
Fixes #8630

### CODE REVIEW

File: Userland/Applications/TextEditor/MainWidget.cpp [hunk 1]
```diff
@@ -6,6 +6,7 @@
 
 #include "MainWidget.h"
 #include <AK/Optional.h>
+#include <AK/Random.h>
```
Comment (alimpfard) [inline Userland/Applications/TextEditor/MainWidget.cpp:9]: It doesn't look like this is used at all...

Comment (timmot) [reply Userland/Applications/TextEditor/MainWidget.cpp:9]: Thank you :), leftovers from when I was trying to use a token approach.

File: Userland/Services/FileSystemAccessServer/ClientConnection.cpp [hunk 2]
```diff
@@ -90,23 +90,35 @@ Messages::FileSystemAccessServer::RequestFileResponse ClientConnection::request_
...
 {
     auto relevant_permissions = requested_access & (Core::OpenMode::ReadOnly | Core::OpenMode::WriteOnly);
     VERIFY(relevant_permissions != Core::OpenMode::NotOpen);
 
     auto main_window = GUI::Window::construct();
+    main_window->set_opacity(0);
+    main_window->set_frameless(true);
+    main_window->show();
+
+    GUI::Application::the()->set_parent(window_server_client_id, parent_window_id, main_window->window_id());
```
Comment (timmot) [inline Userland/Services/FileSystemAccessServer/ClientConnection.cpp:103]: I'd prefer to have a method like `GUI::Application::create_dummy_window(window_server_client_id, parent_window_id)` rather than this.

File: Userland/Services/WindowServer/ClientConnection.cpp [hunk 3]
```diff
@@ -1115,4 +1115,19 @@ void ClientConnection::set_flash_flush(bool enabled)
     Compositor::the().set_flash_flush(enabled);
 }
 
+void ClientConnection::set_parent(i32 client_id, i32 parent_id, i32 child_id)
```
Comment (timmot) [inline Userland/Services/WindowServer/ClientConnection.cpp:1118]: `set_parent` isn't a very informative name.
Perhaps `update_window_parent_from_id`?

**Comment by gunnarbeutner** [comment]
If FileSystemAccessServer dies while selecting a file to open TextEditor won't realize and also won't let you open another file.

**Comment by timmot** [comment]
> If FileSystemAccessServer dies while selecting a file to open TextEditor won't realize and also won't let you open another file.

I tried a Singleton style fix for this, which works unless you try to click the prompt again before the CrashDump has completed.

```cpp
static Client* s_the;

Client* Client::the()
{
    if (!s_the)
        s_the = new Client;

    return s_the;
}

void Client::die()
{
    s_the = nullptr;
}
```

**Comment by gunnarbeutner** [comment]
I've updated LibFileSystemAccessClient to gracefully detect when it got disconnected: https://github.com/gunnarbeutner/serenity/tree/fsas :)

File: Userland/Applications/TextEditor/MainWidget.cpp [hunk 4]
```diff
@@ -370,6 +369,13 @@ Web::OutOfProcessWebView& MainWidget::ensure_web_view()
     return *m_page_view;
 }
 
+FileSystemAccessClient::Client& MainWidget::ensure_file_system_access_client()
```
Comment (timmot) [inline Userland/Applications/TextEditor/MainWidget.cpp:372]: I'm going to move this into `FileSystemAccessClient::Client` because I think every client is going to want this functionality.

**Comment by awesomekling** [comment]
This (asynchronous API) doesn't look like a pleasant way of programming. Can we not find a way to make the operations synchronous by using a nested event loop and hiding the asynchronous communication from the application developer?

**Comment by timmot** [comment]
We sure can.

I wrote a specific solution for this, but `Promise` from `LibIMAP` solved it in a much nicer way.
I'll rebase off #8765 when that's on master and that will give us a synchronous API again without locking out the parent Application.

**Comment by gunnarbeutner** [comment]
I've just retested this and it works for me. :)

File: Userland/Libraries/LibGUI/Application.h [hunk 5]
```diff
@@ -75,6 +75,7 @@ class Application : public Core::Object {
     }
     void notify_drag_cancelled(Badge<WindowServerConnection>);
 
+    RefPtr<Window> create_dummy_child_window(i32 window_server_client_id, i32 window_parent_id);
```
Comment (awesomekling) [inline Userland/Libraries/LibGUI/Application.h:78]: I don't understand the purpose of this API. This sounds like something that belongs in a test program, not as a public Application API.

File: Userland/Services/WindowServer/ClientConnection.cpp [hunk 6]
```diff
@@ -1115,4 +1115,19 @@ void ClientConnection::set_flash_flush(bool enabled)
     Compositor::the().set_flash_flush(enabled);
 }
 
+void ClientConnection::set_window_parent_from_id(i32 client_id, i32 parent_id, i32 child_id)
```
Comment (awesomekling) [inline Userland/Services/WindowServer/ClientConnection.cpp:1118]: This allows any application to "steal" windows from another application, as long as they can guess a client ID.
It feels like the window owner should let WindowServer know that this is okay before we allow it.

File: Userland/Libraries/LibGUI/Application.h (hunk 5 above)
Comment (timmot) [reply Userland/Libraries/LibGUI/Application.h]: I've moved this into a private method for the server. Also went on a rampage and removed all the changes from `Application` as they weren't technically necessary.

File: Userland/Services/WindowServer/ClientConnection.cpp (hunk 6 above)
Comment (timmot) [reply Userland/Services/WindowServer/ClientConnection.cpp:1118]: Implemented and started using this idea in the last two commits.

File: Userland/Services/WindowServer/ClientConnection.cpp [hunk 7]
```diff
@@ -1115,4 +1115,22 @@ void ClientConnection::set_flash_flush(bool enabled)
...
+    auto client_connection = from_client_id(client_id);
+    if (!client_connection)
+        did_misbehave("SetWindowParentFromId: Bad client ID");
+
+    auto parent_window = client_connection->window_from_id(parent_id);
+    if (!parent_window)
+        did_misbehave("SetWindowParentFromId: Bad parent window ID");
+
+    child_window->set_parent_window(*parent_window);
+    child_window->set_rect(parent_window->rect());
```
Comment (timmot) [inline Userland/Services/WindowServer/ClientConnection.cpp]: The `set_rect` makes this not very generic, but it is necessary to make the prompts appear in the centre for the following commits.

Can we set the size elsewhere or are we forced into something strange here?

Comment (timmot) [reply Userland/Services/WindowServer/ClientConnection.cpp]: See the `get_window_rect_from_client` commit.

**Comment by timmot** [comment]
Some changes that are probably hidden due to squashing and rebasing:
* `Application` isn't used in `LibFileSystemAccessClient` anymore
* `LibGUI/WindowServerConnection.h` is included out of order due to difficulties with `LibIPC` `Decoder` and `Encoder`

File: Userland/Services/WindowServer/ClientConnection.cpp [hunk 8]
```diff
@@ -1129,7 +1129,11 @@ void ClientConnection::set_window_parent_from_client(i32 client_id, i32 parent_i
     if (!parent_window)
         did_misbehave("SetWindowParentFromClient: Bad parent window ID");
 
-    child_window->set_parent_window(*parent_window);
+    if (parent_window->is_stealable()) {
```
Comment (awesomekling) [inline Userland/Services/WindowServer/ClientConnection.cpp:1132]: This still seems too lax. Any application can still steal the window, as long as it's marked as stealable.

Can we arrange things so that only the intended window thief can get to it?

Comment (timmot) [reply Userland/Services/WindowServer/ClientConnection.cpp:1132]: This is making me think about multiple window thieves, I'd like to save that for later and just store `Optional<i32> m_thief_client_id` in `Window` for now.
