### PR TITLE
Userland: Fix absolute paths in man page links

### LINKED ISSUE #20041: Help: app-help.png not found
When I open "help" utility I get this error message:

image

### LINKED ISSUE #20889: Userland: Icons are being looked for in the wrong place
When opening the man pages for an application, for instance `Demos/Eyes`, the man pages appear to point to the wrong place. I get the following error:
image
I've checked and the man page is trying to point to the path:
```
/res/icons/16x16/app-eyes.png
```
This file does exist. However it seems that the man page viewer (perhaps) is not taking this as an absolute path but rather turning it into a relative one; thus looking for it in the wrong place:
```
/usr/share/man/man1/Applications/res/...
```
I'm not sure how the paths in the man pages are resolved but I suspect that it is not handling absolute paths correctly.

I believe that this is a general issue with the `Help` application.

I am on revision `24bc761`.

### PR DESCRIPTION
**Pull request by Alizter**
Absolute paths in man page links such as

```
[some link](/foo/bar)
```

Were being interpreted as relative paths when rendered in HTML. This issue was observed in #20889 and #20041.

The fix is to make sure we don't leave any absolute paths when parsing links. Instead we check if a directory is absolute (by checking for `/`) and add `file://` accordingly. This turns the above link into:

```
[some link](file:///foo/bar)
```

Which does get interpreted correctly when rendered as HTML.

- fixes #20889
- fixes #20041

Before this patch, opening the Help application would raise an error. Now all the pictures in the man pages render correctly.

### CODE REVIEW

**Comment by Alizter** [comment]
### Before
image

### After
image

**Comment by AtkinsSJ** [comment]
We also generate https://man.serenityos.org from these. Can you check that it still works with your changes? The generator script is at `Meta/build-manpages-website.sh`

**Comment by Alizter** [comment]
@AtkinsSJ Yes, it still works. The generator doesn't use our markdown rendering engine so the links are unaffected.

From `Eyes.html`:
```html
<h2 id="name">Name</h2>
<p><img src="/icons/16x16/app-eyes.png" alt="Icon" /> Eyes - follow the
mouse LibGUI demo</p>
<p><a href="/cant-run-application.html">Open</a></p>
```

File: Userland/Libraries/LibMarkdown/Text.cpp [hunk 1]
```diff
@@ -663,14 +663,26 @@ NonnullOwnPtr<Text::Node> Text::parse_link(Vector<Token>::ConstIterator& tokens)
...
     for (auto iterator = tokens + 1; !iterator.is_end(); ++iterator) {
         // FIXME: What to do if there's multiple dimension tokens?
         if (is_image && !address.is_empty() && parse_image_dimensions(iterator->data))
             continue;
 
         if (*iterator == ")"sv) {
             tokens = iterator;
-            return make<LinkNode>(is_image, move(link_text), address.to_deprecated_string().trim_whitespace(), image_width, image_height);
+
+            href = address.to_deprecated_string().trim_whitespace();
```
Comment (AtkinsSJ) [inline Userland/Libraries/LibMarkdown/Text.cpp:675]: Declare the `href` variable here instead of above. It's only used locally.

File: Userland/Libraries/LibMarkdown/Text.cpp [hunk 2]
```diff
@@ -663,14 +663,26 @@ NonnullOwnPtr<Text::Node> Text::parse_link(Vector<Token>::ConstIterator& tokens)
...
+
+            // Add file:// if the link is an absolute path otherwise it will be assumed relative.
+            if (AK::StringUtils::starts_with(href, "/"sv, CaseSensitivity::CaseSensitive)) {
+                StringBuilder href_builder;
+                href_builder.append("file://"sv);
+                href_builder.append(href);
+                href = href_builder.to_deprecated_string();
```
Comment (AtkinsSJ) [inline Userland/Libraries/LibMarkdown/Text.cpp:682]: You can simplify this to:
```suggestion
                href = DeprecatedString::format("file://{}", href);
```
Then you wouldn't need the `{}` for the `if` either.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Works nicely!

I hadn't looked at the code when I commented before, I see now that my question didn't make sense. :sweat_smile:  Just, someone previously attempted to fix the issues by changing all the image urls to `file:///...` in the markdown files, which does affect pandoc.

File: Userland/Libraries/LibMarkdown/Text.cpp (hunk 2 above)
Comment (Alizter) [reply Userland/Libraries/LibMarkdown/Text.cpp:682]: @AtkinsSJ It appears that format is not a member of AK::DeprecatedString. Did you mean something else?

Comment (Alizter) [reply Userland/Libraries/LibMarkdown/Text.cpp:682]: Maybe `formatted`?

**Comment by Alizter** [comment]
@AtkinsSJ I've added your suggestions and tested that it still works.

File: Userland/Libraries/LibMarkdown/Text.cpp (hunk 2 above)
Comment (AtkinsSJ) [reply Userland/Libraries/LibMarkdown/Text.cpp]: Ah yeah, that's the one sorry!

**Comment by AtkinsSJ** [comment]
You need to run `clang-format` on that file. You can make that check run automatically when you commit by installing the commit hook: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks

**Comment by Alizter** [comment]
@AtkinsSJ Sorry, I had accidentally deleted my clang toolchain. I'll set it up again and format.

**Review by AtkinsSJ — APPROVED** [review]
Thanks!

**Comment by Alizter** [comment]
@AtkinsSJ CI seems to be good.
