### PR TITLE
AK: Reject BitStream reads beyond EOF

### LINKED ISSUE #21869: REGRESSION: LibGfx/GIF: GIF decoder hangs in LZW compression
This file fails to decode:

trouble

This is currently causing us to spin an `ImageDecoder` process forever when hitting `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7` on https://hemnet.se/

Bisected to 5e2b049de89a996872151c8c91532ce0c99567bd

cc @LucasChollet

### PR DESCRIPTION
**Pull request by timschumi**
With the exception of [WebP](https://chromium.googlesource.com/webm/libwebp/+/24d7f9cb6ef1ef90a04d7b6c15d3477813f75ee0/src/utils/bit_reader_utils.c#220), being able to read null bits beyond the end of a Stream is almost always unintentional and can lead to infinite loops if `0` isn't the "end of stream" symbol by accident.

Fixes #21869.
Fixes [oss-fuzz issue 58046](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58046).
Fixes [oss-fuzz issue 62111](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62111).
Supersedes #18448.

### CODE REVIEW

File: AK/BitStream.h [hunk 1]
```diff
@@ -150,8 +150,14 @@ class LittleEndianBitStream : public Stream {
 /// in little-endian order from another stream.
 class LittleEndianInputBitStream : public LittleEndianBitStream {
 public:
-    explicit LittleEndianInputBitStream(MaybeOwned<Stream> stream)
+    enum UnsatisfiableReadBehavior {
+        Reject,
+        FillWithZero,
+    };
+
+    explicit LittleEndianInputBitStream(MaybeOwned<Stream> stream, UnsatisfiableReadBehavior unsatisfiable_read_behavior = UnsatisfiableReadBehavior::FillWithZero)
```
Comment (IdanHo) [inline AK/BitStream.h]: nitpick: Might be nicer to make this a template parameter to eliminate the branch when it's not needed?

Comment (timschumi) [reply AK/BitStream.h]: I considered it (6 months ago), but making the zeroing Stream a separate type will keep us from layering the `CanonicalCode` for `WebP` like we do at the moment (since it is shared between WebP and DEFLATE).

I don't expect it to make a big difference, if any at all. If it does, I'd rather just slap an `[[unlikely]]` on it, like we do in other places in the system in error paths.

**Comment by tcl3** [comment]
No comment on the change itself, just chiming in to say that this also fixes oss-fuzz issues: [62097](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62097), [59934](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59934), [58059](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58059) and [58040](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58040).

File: AK/BitStream.h (hunk 1 above)
Comment (trflynn89) [reply AK/BitStream.h]: FWIW this PR does consistently slow down `gunzip` of https://www.mattmahoney.net/dc/enwik8.zip from 0.94s to 1.03s on my machine, about 9.5% slower.

Comment (timschumi) [reply AK/BitStream.h]: For me it's the following, on `/tmp` however.

Before:
```
Command:         time -n 100 unzip /home/anon/enwik8.zip
Average time:    1365.53 ms (median: 1362, stddev: 72.56, min: 1269, max:1938)
Excluding first: 1359.75 ms (median: 1360, stddev: 44.44, min: 1269, max:1529)
```

After (~1.5% slower):
```
Command:         time -n 100 unzip /home/anon/enwik8.zip
Average time:    1379.97 ms (median: 1380, stddev: 63.39, min: 1266, max:1551)
Excluding first: 1380.76 ms (median: 1380, stddev: 63.22, min: 1266, max:1551)
```

After with `[[likely]]` (~0.6% slower):
```
Command:         time -n 100 unzip /home/anon/enwik8.zip
Average time:    1373.48 ms (median: 1357.5, stddev: 76.58, min: 1290, max:2023)
Excluding first: 1366.92 ms (median: 1357, stddev: 40.25, min: 1290, max:1465)
```

Could you retest on your setup using `/tmp`, just to avoid our disk driver having any influence?

Comment (trflynn89) [reply AK/BitStream.h]: >avoid our disk driver having any influence
Oh, my numbers are from my host, not Serenity

Comment (timschumi) [reply AK/BitStream.h]: Ah, Lagom doesn't have an `unzip` target, so I assumed you were talking about inside Serenity.

Comment (LucasChollet) [reply AK/BitStream.h]: For completeness, here is an implementation with template parameters (which shouldn't have any performance impact), please don't mind my naming skills :sweat_smile: :
https://github.com/SerenityOS/serenity/compare/master...LucasChollet:serenity:le_bitstream

Comment (trflynn89) [reply AK/BitStream.h]: > Ah, Lagom doesn't have an `unzip` target, so I assumed you were talking about inside Serenity.

I'm using `gunzip`

Comment (timschumi) [reply AK/BitStream.h]: But `gunzip` doesn't support ZIP files, only '.gz'.

In any case, I retried with a file that I recompressed into `gzip` and can somewhat reproduce the performance loss (~5%). `[[likely]]` doesn't seem to make a significant difference either, so I guess I'll look into templates next.

Comment (trflynn89) [reply AK/BitStream.h]: Well yeah, and I did exactly what you did - the file is just hosted online as a .zip.

Comment (timschumi) [reply AK/BitStream.h]: > For completeness, here is an implementation with template parameters (which shouldn't have any performance impact), please don't mind my naming skills 😅 : [master...LucasChollet:serenity:le_bitstream](https://github.com/SerenityOS/serenity/compare/master...LucasChollet:serenity:le_bitstream)

I'm not sure if I'm 100% on-board with all the `Impl` stuff, but I currently don't have enough time to try and make it look nicer either. One thing I _will_ try though is whether moving the loop into `refill_buffer_from_stream` like you did will have a positive impact on performance.

Comment (timschumi) [reply AK/BitStream.h]: > For completeness, here is an implementation with template parameters (which shouldn't have any performance impact), please don't mind my naming skills 😅 : [master...LucasChollet:serenity:le_bitstream](https://github.com/SerenityOS/serenity/compare/master...LucasChollet:serenity:le_bitstream)

We (apparently) decided to go with the non-templated variant for now, since moving the loop and marking the branches seems to mitigate most of the performance impact (I asked the other Tim to rerun the test, and it looks to be essentially no impact now). I added you as a coauthor on the last commit, since at least the loop moving has been taken from there.

In case this turns out to not be sufficient, we can always bring back your branch and rebase it on top of these changes.
