### PR TITLE
LibWeb: Allow CR inside of elements title attributes

### LINKED ISSUE #14173: LibWeb: Unexpected behavior when using CR in the title attribute
I've been using CR `&#013;` for line breaks in the title attribute out of habit(that's what worked a long time ago), when troubleshooting why it doesn't work in Browser I see in the [spec](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute) that LF `&#010;` should be used for line breaks.

Chromium, Firefox and Netsurf handle CR and LF the same.

Testcase: https://ports.serenityos.net/tests/title.html

I think the weird placement of ellipsis and alignment in Browser is a bug?

Expected behavior would be either:
a) Follow the non-standard implementation and treat CR as LF (Like Chromium or Firefox)
b) Ignore CR and show all of the tooltip on one line (Like Netsurf)
c) Cut title at CR, show ellipsis and fix alignment

image

image

### PR DESCRIPTION
**Pull request by bplaat**
Fixes #14173

### CODE REVIEW

File: Userland/Libraries/LibWeb/Page/EventHandler.cpp [hunk 1]
```diff
@@ -542,7 +542,8 @@ bool EventHandler::handle_mousemove(CSSPixelPoint position, CSSPixelPoint screen
     if (hovered_node_changed) {
         JS::GCPtr<HTML::HTMLElement const> hovered_html_element = document.hovered_node() ? document.hovered_node()->enclosing_html_element_with_attribute(HTML::AttributeNames::title) : nullptr;
         if (hovered_html_element && hovered_html_element->title().has_value()) {
-            page.client().page_did_enter_tooltip_area(m_browsing_context->active_document()->navigable()->to_top_level_position(position), hovered_html_element->title()->to_byte_string());
+            auto title = hovered_html_element->title()->bytes_as_string_view().replace("\r\n"sv, "\n"sv, ReplaceMode::All).replace("\r"sv, "\n"sv, ReplaceMode::All);
+            page.client().page_did_enter_tooltip_area(m_browsing_context->active_document()->navigable()->to_top_level_position(position), title);
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/Page/EventHandler.cpp:546]: This feels like an arbitrary thing to do CR/LF conversion on. If we do it on link titles, what else should we be doing it on?
Would it make sense to handle this in the GUI library instead?

Comment (bplaat) [reply Userland/Libraries/LibWeb/Page/EventHandler.cpp:546]: My argument was that we want to normalize the line endings in the WebContent ipc to LF. All current GUI Frameworks: AppKit, Qt & LibGUI support this. When a GUI framework needs a different line ending (win32) we can convert it on that chrome side.

Comment (trflynn89) [reply Userland/Libraries/LibWeb/Page/EventHandler.cpp:546]: This seems like a chrome issue rather than a LibWeb issue. AppKit and LibGUI already do break on `\r`.

AppKit:
Screenshot 2024-03-08 at 7 20 37 AM

LibGUI (though the height measurement is off):
Screenshot_20240308_071813

It seems only Qt does not break on CR, so if we need to break on CR, the fix here IMO should be in the Qt side.

(And side note, this patch makes it so we allocate the title string 3 times for the probably very rare chance that it contains a CR, which is a bit sad)

Comment (bplaat) [reply Userland/Libraries/LibWeb/Page/EventHandler.cpp]: You are right I moved the change to the Qt chrome, I saw that you also fixed CR support in LibGUI in the mean time nice!
