### PR TITLE
LibDebug: Fix crash when debugging short lived programs

### LINKED ISSUE #4327: Bugs around DebugSession
When running `functrace` on a short-lived program, such as `echo whf`, the program immediately crashes, apparently because it doesn't stop the program soon enough:

```
functrace(24): perror(): open: No such file or directory
USERSPACE(24) ASSERTION FAILED: executable->is_valid()
../Libraries/LibDebug/DebugSession.cpp:44
[functrace(24:24)]: CPU[0] NP(error) fault at invalid address V0x02601c58
[functrace(24:24)]: 0xc0181eb1  Kernel::Process::sys$exit(int) +31
[functrace(24:24)]: 0xc017b917  syscall_handler +691
[functrace(24:24)]: 0xc017b65c  syscall_asm_entry +49
[functrace(24:24)]: 0x080480d5  d_type.cold +0
[functrace(24:24)]: 0x0805c5a9  __cxa_atexit +0
[functrace(24:24)]: 0x080516c4  Debug::DebugSession::initialize_executable_mapped_file(int) +90
[functrace(24:24)]: 0x080516f3  Debug::DebugSession::DebugSession(int) +31
[functrace(24:24)]: 0x080519cc  Debug::DebugSession::exec_and_attach(AK::String const&) +382
[functrace(24:24)]: 0x08048239  main +218
[functrace(24:24)]: 0x0804ef76  _start +94
[Shell(22:22)]: select was interrupted
Shell(22): Job entry "functrace echo whf" deleted in 54 ms
```

When running it on a GUI program like `Browser` or `SystemMonitor`, it seems to work for a moment, and then crashes the Kernel:

```
[Terminal(20:20)]: ASSERTION FAILED: !g_scheduler_lock.own_lock()
../Kernel/Syscall.cpp:198 in void Kernel::syscall_handler(Kernel::TrapFrame*)
[Terminal(20:20)]: CPU[0] NP(error) fault at invalid address V0x00c02ab8
[Terminal(20:20)]: 0xc011f355  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[Terminal(20:20)]: 0xc017b805  syscall_handler +417
[Terminal(20:20)]: 0xc017b65c  syscall_asm_entry +49
[Terminal(20:20)]: 0x080fc638  select +57
[Terminal(20:20)]: 0x080de648  Core::EventLoop::wait_for_event(Core::EventLoop::WaitMode) +528
[Terminal(20:20)]: 0x080de9c5  Core::EventLoop::pump(Core::EventLoop::WaitMode) +23
[Terminal(20:20)]: 0x080dedb1  Core::EventLoop::exec() +43
[Terminal(20:20)]: 0x080495d7  main +4591
[Terminal(20:20)]: 0x0804a4ae  _start +94
```

### PR DESCRIPTION
**Pull request by ccapitalK**
Fixes #4327.

I believe these waitpid/ptrace calls are unnecessary, since the tracee waits till it starts executing execvp before it allows a tracer to attach based on my understanding. This fixes the debugger & functrace, but It would be nice to get other eyes on this to make sure I haven't misunderstood how it works.

### CODE REVIEW

File: Libraries/LibDebug/DebugSession.cpp [hunk 1]
```diff
@@ -64,6 +64,11 @@ OwnPtr<DebugSession> DebugSession::exec_and_attach(const String& command)
 {
     int pid = fork();
 
+    if (pid < 0) {
+        perror("fork");
+        exit(1);
+    }
```
Comment (BenWiederhake) [inline Libraries/LibDebug/DebugSession.cpp:70]: [<3](https://rachelbythebay.com/w/2014/08/19/fork/)
