### PR TITLE
Kernel: Don't VERIFY that the DMA channel is running on AC'97 interrupt

### LINKED ISSUE #13771: KERNEL Panic in AC97.cpp:277
image

```
18.480 SystemServer(6:6): Creating /tmp/coredump directory
18.493 SystemServer(6:6): Read system_mode: graphical
18.522 SystemServer(6:6): System in graphical mode
19.082 SystemServer(6:6): Activating 21 services...
21.287 SystemServer(6:6): Service KeyboardPreferenceLoader has exited with exit code 0
21.864 DHCPClient(16:16): We were offered 10.0.2.15 for 2152792320
21.911 DHCPClient(16:16): Leasing the IP 10.0.2.15 for adapter ep0s8
23.069 LookupServer(18:18): Using network config file at /etc/LookupServer.ini
23.446 [#0 keymap(20:20)]: New Character map 'en-us' passed in by client.
23.535 AudioServer(19:19): Started thread "AudioServer[mixer]", tid = 21
24.148 [#0 SyncTask(3:3)]: Ext2FS: Flushed 5 blocks to disk
24.484 SpiceAgent(14:14): Exiting with runtime error: unveil: No such file or directory (errno=2)
24.755 SystemServer(6:6): Service SpiceAgent has exited with exit code 256
25.415 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
25.510 [#0 WindowServer(17:17)]: BochsGraphicsAdapter: resolution set to 1024x768
25.510 [#0 WindowServer(17:17)]: Framebuffer Console: taking 3145728 bytes
25.839 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
26.059 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
30.748 WindowServer(17:17): Entering WindowServer main loop
32.388 LoginServer(22:22): login with sid=22
32.429 SystemServer(22:22): Activating 9 services...
35.190 ResourceGraph.Applet(31:31): Create applet: 0 with spec 'CPUGraph,#00bb00'
38.145 utmpupdate(33:33): Updating utmp from UID=100 GID=100 EGID=5 PID=32
38.900 Audio.Applet(27:27): Started thread "", tid = 35
[AudioServer(19:21)]: ASSERTION FAILED: m_dma_running
[AudioServer(19:21)]: ../../Kernel/Devices/Audio/AC97.cpp:277 in void Kernel::AC97::AC97Channel::handle_dma_stopped()
[AudioServer(19:21)]: KERNEL PANIC! :^(
[AudioServer(19:21)]: Aborted
[AudioServer(19:21)]: at ../../Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[AudioServer(19:21)]: Kernel + 0x00cc8e71  Kernel::__panic(char const*, unsigned int, char const*) +0xf1
[AudioServer(19:21)]: Kernel + 0x0106df79  abort.localalias +0x245
[AudioServer(19:21)]: Kernel + 0x0106dd34  abort.localalias +0x0
[AudioServer(19:21)]: Kernel + 0x00506a8f  Kernel::AC97::handle_irq(Kernel::RegisterState const&) +0x40f
[AudioServer(19:21)]: Kernel + 0x00a69766  Kernel::SharedIRQHandler::handle_interrupt(Kernel::RegisterState const&) [clone .localalias] +0x1e
6
[AudioServer(19:21)]: Kernel + 0x0107fc48  handle_interrupt +0x328
[AudioServer(19:21)]: Kernel + 0x0106ae3b  interrupt_common_asm_entry +0x2b
[AudioServer(19:21)]: Kernel + 0x0050c356  Kernel::AC97::write(unsigned int, Kernel::UserOrKernelBuffer const&, unsigned int) [clone .localal
ias] +0x156
[AudioServer(19:21)]: Kernel + 0x00511f12  Kernel::AudioChannel::write(Kernel::OpenFileDescription&, unsigned long long, Kernel::UserOrKernel
Buffer const&, unsigned int) [clone .localalias] +0x3c2
[AudioServer(19:21)]: Kernel + 0x00927869  Kernel::OpenFileDescription::write(Kernel::UserOrKernelBuffer const&, unsigned int) +0x2f9
[AudioServer(19:21)]: Kernel + 0x00f43d8b  Kernel::Process::do_write(Kernel::OpenFileDescription&, Kernel::UserOrKernelBuffer const&, unsigne
d int) [clone .localalias] +0x81b
[AudioServer(19:21)]: Kernel + 0x00f44c1f  Kernel::Process::sys$write(int, AK::Userspace<unsigned char const*>, unsigned int) +0x85f
[AudioServer(19:21)]: Kernel + 0x00da3673  syscall_handler +0xea3
[AudioServer(19:21)]: Kernel + 0x00da27c1  syscall_asm_entry +0x31
dsound: warning: Voice is not playing
```

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
Fixes #13771; as discussed it's not really a problem to receive an interrupt while the DMA channel is not running, but we do want to log it.

### CODE REVIEW

**Review by GMTA — APPROVED** [review]

File: Kernel/Devices/Audio/AC97.cpp [hunk 1]
```diff
@@ -274,7 +274,9 @@ ErrorOr<void> AC97::write_single_buffer(UserOrKernelBuffer const& data, size_t o
 void AC97::AC97Channel::handle_dma_stopped()
 {
     dbgln_if(AC97_DEBUG, "AC97 @ {}: channel {}: DMA engine has stopped", m_device.pci_address(), name());
-    VERIFY(m_dma_running);
+    // QEMU might send spurious interrupts while we're not running, so we don't want to panic here.
+    if (!m_dma_running)
+        dbgln("AC97 @ {}: received DMA interrupt while it wasn't running", m_device.pci_address());
     m_dma_running = false;
```
Comment (bgianfo) [inline Kernel/Devices/Audio/AC97.cpp:280]: Can this spurious interrupt race with the actual enablement of DMA?
If so, we should probably attempt to atomically read `m_dma_running` and avoid setting it to false again. Otherwise, we risk racing and having the spurious interrupt turn it off.

In general, it seems bad that `m_dma_running` isn't handled atomically?

Comment (supercomputer7) [reply Kernel/Devices/Audio/AC97.cpp:280]: I'd suggest to use a small SpinLock scope to ensure we don't have a race condition here as you mentioned. Using an atomic variable is fine if you only need to do the if statement, not if you need to also change it afterwards.

File: Kernel/Devices/Audio/AC97.cpp [hunk 2]
```diff
@@ -274,7 +274,9 @@ ErrorOr<void> AC97::write_single_buffer(UserOrKernelBuffer const& data, size_t o
 void AC97::AC97Channel::handle_dma_stopped()
 {
     dbgln_if(AC97_DEBUG, "AC97 @ {}: channel {}: DMA engine has stopped", m_device.pci_address(), name());
-    VERIFY(m_dma_running);
+    // QEMU might send spurious interrupts while we're not running, so we don't want to panic here.
```
Comment (supercomputer7) [inline Kernel/Devices/Audio/AC97.cpp:277]: Small nitpick: We usually start a note with `// Note: ...`, to be able to easily track them :)

Comment (kleinesfilmroellchen) [reply Kernel/Devices/Audio/AC97.cpp:277]: I think we should put that in the code style at this point, I've seen people both do and not do it

File: Kernel/Devices/Audio/AC97.h [hunk 3]
```diff
@@ -141,6 +142,7 @@ class AC97 final
         IOAddress m_channel_base;
         AC97& m_device;
         bool m_dma_running { false };
+        Spinlock m_dma_running_spinlock;
```
Comment (IdanHo) [inline Kernel/Devices/Audio/AC97.h:145]:
```suggestion
        SpinlockProtected<bool> m_dma_running { false };
```

Comment (kleinesfilmroellchen) [reply Kernel/Devices/Audio/AC97.h:145]: see, I write too little kernel code :\)

**Review by IdanHo — APPROVED** [review]
Thanks.
