### PR TITLE
LibCrypto+LibTLS: Avoid crashing on invalid input

### LINKED ISSUE #18307: ASN1: Assertion failure in TLS::Certificate::parse_asn1
When fuzzing FuzzASN1, we found that the program crashed with an assertion failure:
```
FuzzASN1: /root/build/serenity/Meta/Lagom/../../Userland/Libraries/LibCrypto/ASN1/DER.h:27: AK::ReadonlyBytes Crypto::ASN1::BitStringView::raw_bytes() const: Assertion `m_unused_bits == 0' failed.
```

Here's the stack trace:
```
#5  0x000055555569532b in TLS::Certificate::parse_asn1 (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzASN1)
                       36: class TLS::Certificate::parse_asn1(buffer = (AK::ReadonlyBytes){<AK::Detail::Span<unsigned char const>> = {m_values = <optimized out>, m_size = <optimized out>}, <No data fields>}) {
                       ||:
                       --: }
                       at /root/build/serenity/Meta/Lagom/../../Userland/Libraries/LibCrypto/ASN1/DER.h:27

#6  0x000055555568aa48 in LLVMFuzzerTestOneInput (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan/FuzzASN1)
                       11: int LLVMFuzzerTestOneInput(data = (const uint8_t *)0x7ffff51f6800 "0\202\003", size = (size_t)773) {
                       ||: /* Local reference: const uint8_t * data = 0x7ffff51f6800 "0\202\003"; */
                       ||: /* Local reference: size_t size = 773; */
                       12: {
                       13:     (void)TLS::Certificate::parse_asn1({ data, size });
                       ||:
                       --: }
                       at /root/build/serenity/Meta/Lagom/Fuzzers/FuzzASN1.cpp:13
```

You can reproduce the bug with the following base64 encoded input:
```
MIIDADCCAemgAwABAAABADANAAkqhkiG9w0BAQUAADBbMQswCQYDAAAAAAAAADETMBEGAwAAAAAA
AAAAAAAAAAAAADEhMB8GAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMRQwEgYDAAAAAAAA
AAAAAAAAAAAAADAeFw0xNTA2MTgwNDI2MzFaFw0xNjA2MTcwNDI2MzFaMAAwggEAMA0ACSqGSIb3
DQEBBQAAADE2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

### PR DESCRIPTION
**Pull request by BenWiederhake**
Fixes #18307.

A library should rarely, if ever, crash on invalid input. Especially if it's something that is used prominently in a security context.

CC @stelar7, since I don't quite understand why this was a `VERIFY` to begin with.

### CODE REVIEW

**Comment by stelar7** [comment]
I have no clue why it was a verify, since its not my work :P
https://github.com/serenityos/serenity/commit/a6e465fba280346e937aa9f0203ea64820c01d78#diff-a98ac3bfd0590be04a19589159a922e889333e17f7d335cf2d2908f5ade34268R37-R41

Change looks ok tho 👍

**Comment by BenWiederhake** [comment]
Oh! You're right. If @msvisser could chime in that would be nice, but I think the answer is that is was just a simple oversight :)

**Comment by BenWiederhake** [comment]
This fixes both of the following OSS Fuzz bugs:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57765&q=label%3AProj-serenity&sort=summary
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57820&q=label%3AProj-serenity&sort=summary

**Comment by msvisser** [comment]
It has been a while since I have worked on this code, but it seems like it was an oversight. Crashing on user input is probably a bad idea in any case.

File: Userland/Libraries/LibCrypto/ASN1/DER.h [hunk 1]
```diff
@@ -22,9 +22,11 @@ class BitStringView {
     {
     }
 
-    ReadonlyBytes raw_bytes() const
+    ErrorOr<ReadonlyBytes> raw_bytes() const
     {
-        VERIFY(m_unused_bits == 0);
+        if (m_unused_bits != 0) {
+            return Error::from_string_literal("ASN1::Decoder: BitStringView contains unexpected partial bytes");
+        }
```
Comment (GMTA) [inline Userland/Libraries/LibCrypto/ASN1/DER.h:29]:
```suggestion
        if (m_unused_bits != 0)
            return Error::from_string_literal("ASN1::Decoder: BitStringView contains unexpected partial bytes");
```

**Comment by BenWiederhake** [comment]
Changes since initial push:
- Removed superfluous curlies
- Rebased for convenience

**Review by GMTA — APPROVED** [review]
