### PR TITLE
Spreadsheet: Fix a crash when opening help window twice

### LINKED ISSUE #20307: Spreadsheet: Opening Spreadsheet Functions Help while it is already open causes crash
- Click spreadsheet funtion button once
- Click spreadsheet funtion button a second time while the function help window is open

Screenshot 2023-08-01 145252

image

### PR DESCRIPTION
**Pull request by 0GreenClover0**
Fixes #20307 + a small inconsistency fix.

### CODE REVIEW

File: Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp [hunk 1]
```diff
@@ -55,7 +55,10 @@ SpreadsheetWidget::SpreadsheetWidget(GUI::Window& parent_window, Vector<NonnullR
             auto docs = sheet_ptr->gather_documentation();
             auto help_window = HelpWindow::the(window());
             help_window->set_docs(move(docs));
-            help_window->set_window_mode(GUI::WindowMode::Modeless);
+
+            if (!help_window->is_visible())
+                help_window->set_window_mode(GUI::WindowMode::Modeless);
```
Comment (LucasChollet) [inline Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp:60]: Shouldn't this be set at initialization time rather than every time we show the window?
