### PR TITLE
Minesweeper: make Field::flood_fill iterative

### LINKED ISSUE #366: Minesweeper: ASSERTION FAILED when minecount too low
Minesweeper crashes when the user sets a high custom row/column size in Minesweeper.ini.
I think this happens when the mine count is too low & there is too much recursion calls during the flood fill.
`ASSERTION FAILED: recognized_symbol_count < max_recognized_symbol_count`
I tried to knock this error out but it was taking an uncomfortable amount of time to figure out :P

### PR DESCRIPTION
**Pull request by DrewStratford**
This change uses an iterative traversal to avoid stack overflows
in, the previously recursive, flood_fill.

This fixes #366.

### CODE REVIEW

File: Games/Minesweeper/Field.cpp [hunk 1]
```diff
@@ -271,15 +272,40 @@ void Field::reset()
     set_updates_enabled(true);
 }
 
+void Field::flood_mark(Square& square)
```
Comment (awesomekling) [inline Games/Minesweeper/Field.cpp]: Can we share some of this code with `on_square_clicked()` in a nice way?
There's a bit of duplication here.

File: Games/Minesweeper/Field.cpp [hunk 2]
```diff
@@ -271,15 +272,40 @@ void Field::reset()
...
 void Field::flood_fill(Square& square)
 {
-    on_square_clicked(square);
-    square.for_each_neighbor([this](auto& neighbor) {
-        if (!neighbor.is_swept && !neighbor.has_mine && neighbor.number == 0)
-            flood_fill(neighbor);
-        if (!neighbor.has_mine && neighbor.number)
-            on_square_clicked(neighbor);
-    });
+    DoublyLinkedList<Square*> queue;
```
Comment (awesomekling) [inline Games/Minesweeper/Field.cpp]: I think it would be more appropriate to use a `Queue` here, the variable name is kind of a giveaway ;)

You can find an example of a flood fill using `Queue` in `Applications/PaintBrush/BucketTool.cpp`

`Queue` uses a list of `Vector`s internally so it's a lot more space efficient than the scattered `DoublyLinkedList`.

**Comment by awesomekling** [comment]
Very nice!
