### PR TITLE
RequestServer: Make pre-connection job refcounted

### LINKED ISSUE #22582: RequestServer: Use-after-free when loading https://bing.com/
100% reproducible for me right now with `Ladybird bing.com`

ASAN report:

```
==498729==ERROR: AddressSanitizer: heap-use-after-free on address 0x60c0000148f0 at pc 0x7ff00a2154a4 bp 0x7ffcfb480fb0 sp 0x7ffcfb480fa8
READ of size 1 at 0x60c0000148f0 thread T0
    #0 0x7ff00a2154a3 in has<unsigned int> /home/kling/src/serenity/Meta/Lagom/../../AK/Variant.h:419:33
    #1 0x7ff00a2154a3 in AK::URLParser::serialize_host(AK::Variant<unsigned int, AK::Array<unsigned short, 8ul>, AK::String, AK::Empty> const&) /home/kling/src/serenity/AK/URLParser.cpp:641:14
    #2 0x7ff00a206701 in AK::URL::serialized_host() const /home/kling/src/serenity/AK/URL.cpp:98:12
    #3 0x55d38d194094 in RequestServer::ConnectionCache::request_did_finish(AK::URL const&, Core::Socket const*) /home/kling/src/serenity/Userland/Services/RequestServer/ConnectionCache.cpp:26:37
    #4 0x55d38d0ad81f in RequestServer::Job::start(Core::Socket&) /home/kling/src/serenity/Userland/Services/RequestServer/ConnectionFromClient.cpp:127:9
    #5 0x55d38d108d0f in auto RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData::create<RequestServer::Job>(RequestServer::Job&)::'lambda'(RequestServer::Job&)::operator()<Core::BufferedSocketBase>(RequestServer::Job&) const /home/kling/src/serenity/Meta/Lagom/../../Userland/Services/RequestServer/ConnectionCache.h:70:25
    #6 0x55d38d108910 in AK::Function<void (Core::BufferedSocketBase&)>::CallableWrapper<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData::create<RequestServer::Job>(RequestServer::Job&)::'lambda'(RequestServer::Job&)>::call(Core::BufferedSocketBase&) /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:182:20
    #7 0x55d38d0a52a7 in AK::Function<void (Core::BufferedSocketBase&)>::operator()(Core::BufferedSocketBase&) const /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115:25
    #8 0x55d38d10642a in decltype(auto) RequestServer::ConnectionCache::get_or_create_connection<AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>, RequestServer::Job>(AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>&, AK::URL const&, RequestServer::Job&, Core::ProxyData)::'lambda4'()::operator()() const /home/kling/src/serenity/Meta/Lagom/../../Userland/Services/RequestServer/ConnectionCache.h:251:13
    #9 0x55d38d105418 in AK::Function<void ()>::CallableWrapper<decltype(auto) RequestServer::ConnectionCache::get_or_create_connection<AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>, RequestServer::Job>(AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>&, AK::URL const&, RequestServer::Job&, Core::ProxyData)::'lambda4'()>::call() /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:182:20
    #10 0x7ff00a057c17 in AK::Function<void ()>::operator()() const /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115:25
    #11 0x7ff00a0e3763 in Core::ThreadEventQueue::process() /home/kling/src/serenity/Userland/Libraries/LibCore/ThreadEventQueue.cpp:108:13
    #12 0x7ff00a03905d in Core::EventLoopImplementationUnix::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp:101:9
    #13 0x7ff00a034451 in Core::EventLoop::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoop.cpp:86:20
    #14 0x55d38d007477 in serenity_main(Main::Arguments) /home/kling/src/serenity/Ladybird/RequestServer/main.cpp:62:30
    #15 0x55d38d23039d in main /home/kling/src/serenity/Userland/Libraries/LibMain/Main.cpp:39:19
    #16 0x7ff009623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #17 0x7ff009623b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #18 0x55d38cf2e964 in _start (/home/kling/src/serenity/Build/lagom/bin/RequestServer+0x33c964) (BuildId: c5655325e898ee40)

0x60c0000148f0 is located 48 bytes inside of 128-byte region [0x60c0000148c0,0x60c000014940)
freed by thread T0 here:
    #0 0x55d38d00341d in operator delete(void*) (/home/kling/src/serenity/Build/lagom/bin/RequestServer+0x41141d) (BuildId: c5655325e898ee40)
    #1 0x55d38d03f572 in AK::NonnullOwnPtr<RequestServer::Job>::clear() /home/kling/src/serenity/Meta/Lagom/../../AK/NonnullOwnPtr.h:133:9
    #2 0x55d38d03e5b8 in AK::NonnullOwnPtr<RequestServer::Job>::~NonnullOwnPtr() /home/kling/src/serenity/Meta/Lagom/../../AK/NonnullOwnPtr.h:50:9
    #3 0x55d38d03e53f in AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry::~Entry() /home/kling/src/serenity/Meta/Lagom/../../AK/HashMap.h:23:12
    #4 0x55d38d072f2c in void AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>::delete_bucket<AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>::Bucket>(AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>::Bucket&) /home/kling/src/serenity/Meta/Lagom/../../AK/HashTable.h:713:25
    #5 0x55d38d072c76 in AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>::remove(AK::HashTableIterator<AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashTable<AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::Entry, AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::EntryTraits, false>::Bucket>&) /home/kling/src/serenity/Meta/Lagom/../../AK/HashTable.h:446:9
    #6 0x55d38d0723a6 in AK::HashMap<AK::URL, AK::NonnullOwnPtr<RequestServer::Job>, AK::Traits<AK::URL>, AK::Traits<AK::NonnullOwnPtr<RequestServer::Job>>, false>::remove(AK::URL const&) /home/kling/src/serenity/Meta/Lagom/../../AK/HashMap.h:71:21
    #7 0x55d38d0ad85f in RequestServer::Job::start(Core::Socket&) /home/kling/src/serenity/Userland/Services/RequestServer/ConnectionFromClient.cpp:128:16
    #8 0x55d38d108d0f in auto RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData::create<RequestServer::Job>(RequestServer::Job&)::'lambda'(RequestServer::Job&)::operator()<Core::BufferedSocketBase>(RequestServer::Job&) const /home/kling/src/serenity/Meta/Lagom/../../Userland/Services/RequestServer/ConnectionCache.h:70:25
    #9 0x55d38d108910 in AK::Function<void (Core::BufferedSocketBase&)>::CallableWrapper<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>::JobData::create<RequestServer::Job>(RequestServer::Job&)::'lambda'(RequestServer::Job&)>::call(Core::BufferedSocketBase&) /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:182:20
    #10 0x55d38d0a52a7 in AK::Function<void (Core::BufferedSocketBase&)>::operator()(Core::BufferedSocketBase&) const /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115:25
    #11 0x55d38d10642a in decltype(auto) RequestServer::ConnectionCache::get_or_create_connection<AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>, RequestServer::Job>(AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>&, AK::URL const&, RequestServer::Job&, Core::ProxyData)::'lambda4'()::operator()() const /home/kling/src/serenity/Meta/Lagom/../../Userland/Services/RequestServer/ConnectionCache.h:251:13
    #12 0x55d38d105418 in AK::Function<void ()>::CallableWrapper<decltype(auto) RequestServer::ConnectionCache::get_or_create_connection<AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>, RequestServer::Job>(AK::HashMap<RequestServer::ConnectionCache::ConnectionKey, AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>, AK::Traits<RequestServer::ConnectionCache::ConnectionKey>, AK::Traits<AK::NonnullOwnPtr<AK::Vector<AK::NonnullOwnPtr<RequestServer::ConnectionCache::Connection<TLS::TLSv12, TLS::TLSv12>>, 0ul>>>, false>&, AK::URL const&, RequestServer::Job&, Core::ProxyData)::'lambda4'()>::call() /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:182:20
    #13 0x7ff00a057c17 in AK::Function<void ()>::operator()() const /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115:25
    #14 0x7ff00a0e3763 in Core::ThreadEventQueue::process() /home/kling/src/serenity/Userland/Libraries/LibCore/ThreadEventQueue.cpp:108:13
    #15 0x7ff00a03905d in Core::EventLoopImplementationUnix::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp:101:9
    #16 0x7ff00a034451 in Core::EventLoop::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoop.cpp:86:20
    #17 0x55d38d007477 in serenity_main(Main::Arguments) /home/kling/src/serenity/Ladybird/RequestServer/main.cpp:62:30
    #18 0x55d38d23039d in main /home/kling/src/serenity/Userland/Libraries/LibMain/Main.cpp:39:19
    #19 0x7ff009623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x55d38d002bbd in operator new(unsigned long) (/home/kling/src/serenity/Build/lagom/bin/RequestServer+0x410bbd) (BuildId: c5655325e898ee40)
    #1 0x55d38d0402f2 in AK::NonnullOwnPtr<RequestServer::Job> AK::make<RequestServer::Job, AK::URL const&>(AK::URL const&) /home/kling/src/serenity/Meta/Lagom/../../AK/NonnullOwnPtr.h:150:55
    #2 0x55d38d029c0e in RequestServer::Job::ensure(AK::URL const&) /home/kling/src/serenity/Userland/Services/RequestServer/ConnectionFromClient.cpp:117:24
    #3 0x55d38d01e58c in RequestServer::ConnectionFromClient::ensure_connection(AK::URL const&, RequestServer::CacheLevel const&) /home/kling/src/serenity/Userland/Services/RequestServer/ConnectionFromClient.cpp:156:17
    #4 0x55d38d0305c7 in RequestServerStub::handle(IPC::Message const&) /home/kling/src/serenity/Build/lagom/Userland/Services/RequestServer/RequestServerEndpoint.h:824:13
    #5 0x7ff00a94415e in IPC::ConnectionBase::handle_messages() /home/kling/src/serenity/Userland/Libraries/LibIPC/Connection.cpp:88:48
    #6 0x7ff00a057c17 in AK::Function<void ()>::operator()() const /home/kling/src/serenity/Meta/Lagom/../../AK/Function.h:115:25
    #7 0x7ff00a0e3763 in Core::ThreadEventQueue::process() /home/kling/src/serenity/Userland/Libraries/LibCore/ThreadEventQueue.cpp:108:13
    #8 0x7ff00a03905d in Core::EventLoopImplementationUnix::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp:101:9
    #9 0x7ff00a034451 in Core::EventLoop::exec() /home/kling/src/serenity/Userland/Libraries/LibCore/EventLoop.cpp:86:20
    #10 0x55d38d007477 in serenity_main(Main::Arguments) /home/kling/src/serenity/Ladybird/RequestServer/main.cpp:62:30
    #11 0x55d38d23039d in main /home/kling/src/serenity/Userland/Libraries/LibMain/Main.cpp:39:19
    #12 0x7ff009623a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-use-after-free /home/kling/src/serenity/Meta/Lagom/../../AK/Variant.h:419:33 in has<unsigned int>
Shadow bytes around the buggy address:
  0x60c000014600: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x60c000014680: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x60c000014700: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x60c000014780: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x60c000014800: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
=>0x60c000014880: fa fa fa fa fa fa fa fa fd fd fd fd fd fd[fd]fd
  0x60c000014900: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x60c000014980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 05 fa
  0x60c000014a00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x60c000014a80: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x60c000014b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 05
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb

```

### PR DESCRIPTION
**Pull request by MacDue**
Fixes #22582

Previously, the job and the (cache of them) would lead to a UAF, as after `.start()` was called on the job it'd be immediately destroyed.

Example of previous bug:

```
// Note due to the cache &jobA == &jobB
auto& jobA = Job::ensure("https://r.bing.com/");
auto& jobB = Job::ensure("https://r.bing.com/");
// Previously, the first .start() free'd the job
jobA.start();
// So the second .start() was a UAF
jobB.start();
```

I'm not too familiar with RequestServer, but as far as I can tell this fixes the issue.

### CODE REVIEW

File: Userland/Services/RequestServer/ConnectionFromClient.cpp [hunk 1]
```diff
@@ -106,35 +106,40 @@ Messages::RequestServer::SetCertificateResponse ConnectionFromClient::set_certif
...
-    URL m_url;
 
 private:
+    explicit Job(URL url)
+        : m_url(move(url))
+    {
+    }
+
+    URL m_url;
+    int m_use_count { 0 };
```
Comment (ADKaster) [inline Userland/Services/RequestServer/ConnectionFromClient.cpp:142]: hem. Perhaps making these guys RefCounted would do the trick in a more idiomatic way?

Comment (ADKaster) [reply Userland/Services/RequestServer/ConnectionFromClient.cpp:142]: we also have the magical `one_ref_left` function available to do the cache removal

Comment (MacDue) [reply Userland/Services/RequestServer/ConnectionFromClient.cpp]: I've given that a try. It also works, though it does slightly change other users too. I placed a few logs around and it seems the jobs are still destroyed too.
