### PR TITLE
LibJS/Date: Ensure `YearFromTime(t)` holds invariant after approximation

### LINKED ISSUE #21533: LibJS: `new Date(-1112, 11, 31)` crashes
```console
$ js
> new Date(-1112, 11, 31)
VERIFICATION FAILED: day_within_year < (365 + in_leap_year) at Userland/Libraries/LibJS/Runtime/Date.cpp:223
...
```

### PR DESCRIPTION
**Pull request by cg-jl**
As of https://tc39.es/ecma262/#sec-yearfromtime, YearFromTime(t) should
return `y` such that `TimeFromYear(YearFromTime(t)) <= t`. This wasn't
held, since the approximation would only go the desired direction once.

Adapted from Kiesel:
https://codeberg.org/kiesel-js/kiesel/commit/6548a857439ca175d4254c880442bb5267e92a04

Fixes #21533.

### CODE REVIEW

**Comment by cg-jl** [comment]
Looks like your `floor` approximation doesn't agree with what node does. The string I test in `Tests/time-from-year.js` is the one I get from node and bun.

File: Userland/Libraries/LibJS/Tests/time-from-year.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+test("YearFromTime(TimeFromYear(t)) <= t", () => {
+    let d = new Date(-1112, 11, 31);
+    expect(d.toGMTString()).toBe("Fri, 31 Dec -1112 00:14:44 GMT");
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/time-from-year.js:3]:
```
ExpectationError: toBe: expected _Fri, 31 Dec -1112 00:14:44 GMT_, got _Fri, 31 Dec -1112 00:00:00 GMT_
```

This returns `Fri, 31 Dec -1112 00:01:15 GMT` here (UTC+1), and yet another result on CI. Might be best to test this another way (`getDate()` should also trigger the crash) instead of introducing a possibly flaky test.

Comment (cg-jl) [reply Userland/Libraries/LibJS/Tests/time-from-year.js:3]: do the `UTC` variants use always the same reference? Or should I use `getDate()` and the like?

Comment (linusg) [reply Userland/Libraries/LibJS/Tests/time-from-year.js]: Hmm, I think the issue may be that we're creating a localtime-`Date` - this may work reliably: `new Date(Date.UTC(-1112, 11, 31)).toGMTString() // "Fri, 31 Dec -1112 00:00:00 GMT"

Just saw your force-push, feel free to keep it as-is if that passes CI now :)

Comment (cg-jl) [reply Userland/Libraries/LibJS/Tests/time-from-year.js]: `Date.UTC` it is then

**Review by linusg — APPROVED** [review]
Random passerby review: LGTM assuming CI will pass this time :+1:

File: Userland/Libraries/LibJS/Tests/time-from-year.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+test("YearFromTime(TimeFromYear(t)) <= t", () => {
```
Comment (trflynn89) [inline Userland/Libraries/LibJS/Tests/time-from-year.js:1]: Instead of adding this as a random test file in the root LibJS/Tests directory, let's add it to LibJS/Tests/builtins/Date/Date.UTC.js (with a plain-english test name too please - if I came across this test a year from now, I'd have no idea what's special about the date being tested here).

Comment (cg-jl) [reply Userland/Libraries/LibJS/Tests/time-from-year.js]: I settled for `month from negative time` as the test title. It is a bit difficult to choose it, since what that input uncovered is precisely that the condition from `YearFromTime(TimeFromYear(t)) <= t` wasn't being held in the case of negative time.

Since that condition didn't hold, the interpreter crashed before it could get out of the `Date` constructor.

Comment (cg-jl) [reply Userland/Libraries/LibJS/Tests/time-from-year.js]: I settled for `month from negative time` as the test title. It is a bit difficult to choose it, since what that input uncovered is precisely that the condition from `YearFromTime(TimeFromYear(t)) <= t` wasn't being held in the case of negative time.

Since that condition didn't hold, the interpreter crashed before it could get out of the `Date` constructor.
