### PR TITLE
LibC: Remove strtold impossible assert and add tests

### LINKED ISSUE #25791: LibC: strtold crashes on x86_64
LibC crashes just by calling `strtold` since `sizeof(double) == sizeof(long double)` is false.
```c
long double strtold(char const* str, char** endptr)
{
    assert(sizeof(double) == sizeof(long double));
    return strtod(str, endptr);
}
```

I built SerenityOS on Ubuntu24.04 with GCC 13.

### PR DESCRIPTION
**Pull request by hiperbolt**
Removed the impossible assertion of sizeof(double) == sizeof(long double) in strtold, and made it use c_str_to_floating_point casted to long double. This fixes the crash but suffers from lack of precision. Our eisel-lemire implementation on FloatingPointStringConversions needs a big overhaul to work properly with long doubles, especially with x87 80-bit extended precision format. As discussed in Discord, this is an acceptable first contribution/fix for the crash while we don't get around to overhauling our eisel-lemire implementation

Also added tests missing for FloatingPointStringConversions.cpp.

Fixes #25791

### CODE REVIEW

File: Userland/Libraries/LibC/stdlib.cpp [hunk 1]
```diff
@@ -579,8 +579,9 @@ double strtod(char const* str, char** endptr)
 // https://pubs.opengroup.org/onlinepubs/9699919799/functions/strtold.html
 long double strtold(char const* str, char** endptr)
 {
-    assert(sizeof(double) == sizeof(long double));
-    return strtod(str, endptr);
+    // FIXME: eisel-lemire needs a deep overhaul to work with fp80 and fp128.
+    // For now, we just cast to long double and accept the loss of precision.
+    return (long double)c_str_to_floating_point<double>(str, endptr);
```
Comment (DanShaders) [inline Userland/Libraries/LibC/stdlib.cpp:584]: Oh, and I missed this. Prefer `static_cast<long_double>` to C-style casts.

File: Tests/AK/TestFloatingPointStringConversions.cpp
[the remark this answers is not in the document]
Comment (hiperbolt) [reply Tests/AK/TestFloatingPointStringConversions.cpp:1]: Should I remove the file from this PR then?

[the remark this answers is not in the document]
Comment (DanShaders) [reply Tests/AK/TestFloatingPointStringConversions.cpp:1]: Well, you can but you can also just split the commit into two.

[the remark this answers is not in the document]
Comment (hiperbolt) [reply Tests/AK/TestFloatingPointStringConversions.cpp:1]: Per contribution guidelines I split the commits and squashed the fixes

**Comment by hiperbolt** [comment]
I've implemented your suggestions @DanShaders! Now using a C++ style cast and iterating over an array of tests (which are now using EXPECT_EQ).

My only question is it's okay to use warnln() to print what case is currently being tested? Since we are iterating over a single test case, we lose some verbosity which I think might be important. Since in TestSuite.cpp we use warnln(), I think it makes sense to replicate that here.

File: Tests/AK/TestFloatingPointStringConversions.cpp [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+struct FloatingPointTestCase {
+    StringView input;
+    double expected_value;
+    FloatingPointError expected_error;
+    int expected_end_offset;
+    ParserType parser_type;
+    StringView name;
+};
+
+constexpr auto test_cases = Array<FloatingPointTestCase, 13>({ { "123"sv, 123.0, FloatingPointError::None, 3, ParserType::Regular, "basic_integer"sv },
```
Comment (DanShaders) [inline Tests/AK/TestFloatingPointStringConversions.cpp:28]: Use `to_array` as I did in the suggestion, this way you don't have to count the number of tests.

File: Tests/AK/TestFloatingPointStringConversions.cpp [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    { "-67.89"sv, -67.89, FloatingPointError::None, 6, ParserType::Regular, "negative_number"sv },
+    { "0"sv, 0.0, FloatingPointError::None, 1, ParserType::Regular, "zero"sv },
+    { "-0.0"sv, -0.0, FloatingPointError::None, 4, ParserType::Regular, "negative_zero"sv },
+    { "abc"sv, 0.0, FloatingPointError::NoOrInvalidInput, 0, ParserType::Regular, "invalid_input"sv },
+    { "123.45abc"sv, 123.45, FloatingPointError::None, 6, ParserType::Regular, "partial_parse"sv },
+    { "0x1.8p1"sv, 3.0, FloatingPointError::None, 7, ParserType::Hexfloat, "hex_float"sv },
+    { "1e309"sv, __builtin_huge_val(), FloatingPointError::OutOfRange, 5, ParserType::Regular, "out_of_range"sv },
+    { "1e-400"sv, 0.0, FloatingPointError::RoundedDownToZero, 6, ParserType::Regular, "rounded_down_to_zero"sv },
+    { "123.45"sv, 123.45, FloatingPointError::None, 0, ParserType::Complete, "parse_completely_valid"sv },
+    { "123.45a"sv, 0.0, FloatingPointError::NoOrInvalidInput, 0, ParserType::Complete, "parse_completely_invalid"sv } });
```
Comment (DanShaders) [inline Tests/AK/TestFloatingPointStringConversions.cpp:40]: With the trailing comma, you get nicer formatting.

**Review by DanShaders — COMMENTED** [review]
Two nits, otherwise lgtm

File: Tests/AK/TestFloatingPointStringConversions.cpp (hunk 2 above)
Comment (hiperbolt) [reply Tests/AK/TestFloatingPointStringConversions.cpp:28]: In the suggestion I believe you use `vector<>`, not to `to_array`, but it does seem like good practice to use `to_array`!

**Comment by hiperbolt** [comment]
> Two nits, otherwise lgtm

Thank you! Should be ready for merge as soon as the pipeline finishes.

File: Userland/Libraries/LibC/stdlib.cpp [hunk 4]
```diff
@@ -579,8 +579,9 @@ double strtod(char const* str, char** endptr)
 // https://pubs.opengroup.org/onlinepubs/9699919799/functions/strtold.html
 long double strtold(char const* str, char** endptr)
 {
-    assert(sizeof(double) == sizeof(long double));
-    return strtod(str, endptr);
+    // FIXME: eisel-lemire needs a deep overhaul to work with fp80 and fp128.
+    // For now, we just cast to long double and accept the loss of precision.
+    return static_cast<long double>(c_str_to_floating_point<double>(str, endptr));
```
Comment (LucasChollet) [inline Userland/Libraries/LibC/stdlib.cpp:584]: You're not only removing the assert here, which, first, isn't super atomic, but also raise the question : why not keeping the call to `strtod`?

File: Tests/AK/TestFloatingPointStringConversions.cpp [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+    { "123.45a"sv, 0.0, FloatingPointError::NoOrInvalidInput, 0, ParserType::Complete, "parse_completely_invalid"sv },
+});
+
+TEST_CASE(unified_floating_point_parsing)
+{
+    for (auto const& test_case : test_cases) {
+        auto const* input = test_case.input.characters_without_null_termination();
+        size_t const input_length = test_case.input.length();
+
+        warnln("Running test: {}", test_case.name);
```
Comment (LucasChollet) [inline Tests/AK/TestFloatingPointStringConversions.cpp:50]: Simply suggestion, as I know that we just made you create the array, so don't feel obliged to implement it. But another solution to the problem of code duplication would have been to put move all that code to a function and then have very brief tests like this:
```cpp
TEST_CASE(basic_integer)
{
	floating_point_parsing_helper({ "123"sv, 123.0, FloatingPointError::None, 3, ParserType::Regular});
}
```

File: Userland/Libraries/LibC/stdlib.cpp (hunk 4 above)
Comment (hiperbolt) [reply Userland/Libraries/LibC/stdlib.cpp:584]: What do you mean it isn't 'super atomic'? The assert is removed exactly because it is impossible: `sizeof(double)` is never `size(long double)` in any of the supported architectures (this is discussed in greater detail in the original issue).

Also, we call `c_str_to_floating_point` instead of using `strtod` because (I think) it just makes more sense - the idea is that `c_str_to_floating_point` is the underlying method for any string to floating point conversion, and that eventually it will support long double as a type. Since it doesn't for now, it makes sense to explicitly call it and static cast its result to long double.

Not only that, the original call to `strtod` wouldn't work anyway? `strtold` returns a double, so either we would have an implicit cast or it would crash altogether (not sure what the behaviour would be).

Comment (LucasChollet) [reply Userland/Libraries/LibC/stdlib.cpp:584]: > What do you mean it isn't 'super atomic'?

Commits are supposed to be atomic - only do one thing. So when I read the commit title which is about removing an assert, I expect you to only do that in the commit.

> strtold returns a double, so either we would have an implicit cast or it would crash altogether (not sure what the behaviour would be).

Using an implicit cast seems to compile, so we can leave this line alone. The `FIXME` is relevant though.

---

The general idea behind my comment was that if you don't need to touch a line, don't do it. I agree that in the end we will call `c_str_to_floating_point` directly, but we will change that when it will be required/useful.

Comment (hiperbolt) [reply Userland/Libraries/LibC/stdlib.cpp:584]: > Commits are supposed to be atomic - only do one thing. So when I read the commit title which is about removing an assert, I expect you to only do that in the commit.

I elaborate more on what *exactly* is being done on the commit message body, but I do agree the commit title could be more explicit. If we do decide to also leave the cast, I'll update the title accordingly.

> Using an implicit cast seems to compile, so we can leave this line alone. The `FIXME` is relevant though.
I went to test it - I was under the impression it would crash at runtime. It does indeed work.

> The general idea behind my comment was that if you don't need to touch a line, don't do it. I agree that in the end we will call `c_str_to_floating_point` directly, but we will change that when it will be required/useful.
I can understand this as a general principle, but in this particular case I still don't agree with leaving it as is - if anything, using `c_str_to_floating_point` with the cast makes what is going on more explicit.

So, ultimately, would you prefer that:
1. I remove the cast and leave the call to `strtod` as is, keeping the FIXME and mantaining the current commit title?
2. I leave my PR as-is and update the commit title?

Thank you for the time spent on this review!

File: Tests/AK/TestFloatingPointStringConversions.cpp (hunk 5 above)
Comment (LucasChollet) [reply Tests/AK/TestFloatingPointStringConversions.cpp:50]: I forgot to answer here, my bad. But again this is not a huge deal, so do as you want. That being said, I see a slight advantage to my solution is that it's using the standard way of printing the test names, so it's the same formatting but also the same output (stdout vs stderr).

Comment (hiperbolt) [reply Tests/AK/TestFloatingPointStringConversions.cpp:50]: I agree, that does make sense. I'll amend the commit shortly to follow that pattern.

File: Userland/Libraries/LibC/stdlib.cpp (hunk 4 above)
Comment (hiperbolt) [reply Userland/Libraries/LibC/stdlib.cpp:584]: I value your input, and if you feel like 1. is the way to go, I'll amend the commit shortly!

**Comment by hiperbolt** [comment]
@LucasChollet @DanShaders should be all good to be merged, could you take a look when you have the time? Thank you.

**Review by LucasChollet — APPROVED** [review]
I don't have merge permissions here, the best I can do is this approval.
