### PR TITLE
LibWeb: Implement Document named properties with light caching

### LINKED ISSUE #22232: Ladybird: Implement `past-names-map`
Minimal repro:

```html
<form name="the_form"><input id="bar"></form>
<script>
alert(the_form.bar);
</script>
```

https://html.spec.whatwg.org/multipage/forms.html#past-names-map

See: https://discord.com/channels/830522505605283862/830525031720943627/1183758058426478632 ff

---

After #17970 was fixed, the login process is now able to start on https://world-of-dungeons.net/

But errors out directly without even sending a request with the following error:

```
HTMLScriptElement: Refusing to run script because the element's result is null.
Unhandled JavaScript exception: [TypeError] ToObject on null or undefined
    at submit
    at <unknown>
    at <unknown>
```

No valid credentials are needed to reproduce the error.

### PR DESCRIPTION
**Pull request by ADKaster**
We now cache potentially named elements on the Document when elements are inserted and removed. This allows us to do lookup of what names are supported much faster than if we had to iterate the tree every time.

This first cut doesn't implement the rules for 'exposed' object and embed elements.

Fixes #22232

### CODE REVIEW

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 1]
```diff
@@ -3714,16 +3723,85 @@ void Document::append_pending_animation_event(Web::DOM::Document::PendingAnimati
...
-void Document::element_id_changed(Badge<DOM::Element>)
+static bool is_potentially_named_element(DOM::Element const& element)
+{
+    return is<HTML::HTMLEmbedElement>(element) || is<HTML::HTMLFormElement>(element) || is<HTML::HTMLIFrameElement>(element) || is<HTML::HTMLImageElement>(element) || is<HTML::HTMLObjectElement>(element);
+}
+
+static bool is_potentially_named_element_by_id(DOM::Element const& element)
+{
+    return is<HTML::HTMLObjectElement>(element) || is<HTML::HTMLImageElement>(element);
+}
```
Comment (trflynn89) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:3734]: Are there spec links we can reference for this list of elements? Or is it just scattered throughout the spec?

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 2]
```diff
@@ -3857,4 +3935,126 @@ Vector<JS::NonnullGCPtr<Element>> Document::elements_from_point(double x, double
...
+
+    return true;
+}
+
+// https://html.spec.whatwg.org/multipage/dom.html#dom-document-namedItem-which
+Vector<FlyString> Document::supported_property_names() const
+{
+    //  The supported property names of a Document object document at any moment consist of the following,
+    //  in tree order according to the element that contributed them, ignoring later duplicates,
+    //  and with values from id attributes coming before values from name attributes when the same element contributes both:
```
Comment (trflynn89) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:3955]: You've got double-spaces at the start of each line here

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 3]
```diff
@@ -3857,4 +3935,126 @@ Vector<JS::NonnullGCPtr<Element>> Document::elements_from_point(double x, double
...
+        if (auto name = element->name(); name.has_value())
+            names.set(name.value());
+    }
+
+    Vector<FlyString> result;
+    result.ensure_capacity(names.size());
+    for (auto const& name : names)
+        result.unchecked_append(name);
+
+    return result;
```
Comment (trflynn89) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:3991]: `return names.values();` :)

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 4]
```diff
@@ -3857,4 +3935,126 @@ Vector<JS::NonnullGCPtr<Element>> Document::elements_from_point(double x, double
...
+
+        if (element->name() == name) {
+            named_elements.append(*element);
+        }
+    }
+
+    return named_elements;
+}
+
+// https://html.spec.whatwg.org/multipage/dom.html#dom-document-namedItem
```
Comment (trflynn89) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:4024]: Same as the other PR this spec link doesn't work:
```
https://html.spec.whatwg.org/multipage/dom.html#dom-document-nameditem
```
(I didn't check the other links in this PR)

**Review by trflynn89 — COMMENTED** [review]
Seems good, just a couple small things

File: Userland/Libraries/LibWeb/DOM/Document.cpp (hunk 4 above)
Comment (ADKaster) [reply Userland/Libraries/LibWeb/DOM/Document.cpp:4024]: d'oh. was just this one thankfully

File: Userland/Libraries/LibWeb/DOM/Document.cpp (hunk 3 above)
Comment (ADKaster) [reply Userland/Libraries/LibWeb/DOM/Document.cpp:3991]: woah. There's a few other places we could use that instead of this pattern...

**Review by trflynn89 — APPROVED** [review]
