### PR TITLE
LibJS: More this values fixes

### LINKED ISSUE #9024: LibJS: `this` is undefined in nested functions inside class constructors
For example:

```js
class Base {
    constructor() {
    }
}

class Test extends Base {
    constructor() {
        super();
        (() => {
                console.log(this);
        })();
    }
}

new Test();
```

The `console.log` should print the instance of `Test`, but instead prints `undefined`.

### LINKED ISSUE #9025: LibJS: `this` initialization check is not performed when accessing `this` in nested functions inside constructor
For example:
```js
class Base {
    constructor() {
    }
}

class Test extends Base {
    constructor() {
        (() => {
            console.log(this);
        })();
        console.log("Missing |this| init check");
    }
}

new Test();
```

Expected:
```
Uncaught exception: [ReferenceError] |this| has not been initialized
```

Actual:
```
undefined
Missing |this| init check
Uncaught exception: [ReferenceError] |this| has not been initialized
```

The exception in the `Actual` is when it leaves the constructor and `this` is still not initialized.
Note that removing the IIFE gives the expected result.
IIFE is not a requirement, this can happen in callbacks for example (such as from Array.prototype.filter)

### PR DESCRIPTION
**Pull request by davidot**
Browser is still working :heavy_check_mark: 
No regressions in test262 :heavy_check_mark: 
Added a large this value test :heavy_check_mark: 

Fixes #9024 and fixes #9025.

If there are still cases which are not covered (or not covered enough) in the test please let me know so we can add them.
I'm sure there are still some cases which are broken or should be handled differently.

Also on a personal note I now consider Array to be spec compliant! :tada: 
`test/built-ins/Array                                                             2799/2801  ( 99.93%) [ ✅ 2799  ❌ 1     💥️ 1     ]` which was my original goal when I started working on LibJS. The failures are one from generator functions the other from realm exceptions which I will ignore (although that is what I said about the this value failures...)

### CODE REVIEW

File: Userland/Libraries/LibJS/Tests/this-value.js [hunk 1]
```diff
@@ -0,0 +1,446 @@
...
+    expect(globalArrow()).toBe(globalThisValue);
+
+    const arrowInGlobalFunction = () => this;
+    expect(arrowInGlobalFunction()).toBe(globalObject);
+
+    return arrowInGlobalFunction;
+}
+
+expect(globalArrow()).toBe(globalThisValue);
+expect(globalFunction()()).toBe(globalObject);
```
Comment (davidot) [inline Userland/Libraries/LibJS/Tests/this-value.js:23]: Bit ugly but it needs to be global to test it...

File: Userland/Libraries/LibJS/Runtime/Object.h [hunk 2]
```diff
@@ -150,18 +150,30 @@ class Object : public Cell {
...
-            return invoke(property_name, move(arglist));
+            return invoke(this, property_name, move(arglist));
         }
 
-        return invoke(property_name);
+        return invoke(this, property_name);
+    }
+
+    template<typename... Args>
+    [[nodiscard]] ALWAYS_INLINE Value invoke(Value this_value, PropertyName const& property_name, Args... args)
```
Comment (davidot) [inline Userland/Libraries/LibJS/Runtime/Object.h:168]: I did not add a spec link here since it is not completely the same and we now have to functions as well which makes it even more complicated.

File: Userland/Libraries/LibJS/Runtime/GlobalObject.h [hunk 3]
```diff
@@ -163,4 +163,17 @@ inline GlobalObject* Shape::global_object() const
...
+    if constexpr (sizeof...(Args) > 0) {
+        MarkedValueList arglist { global_object.vm().heap() };
+        (..., arglist.append(move(args)));
+        return invoke_internal(global_object, property_name, move(arglist));
+    }
+
+    return invoke_internal(global_object, property_name, Optional<MarkedValueList>{});
+}
+
+
```
Comment (davidot) [inline Userland/Libraries/LibJS/Runtime/GlobalObject.h:178]: Not the best location for this but otherwise I ran into dependency cycles.
And since you need to pass GlobalObject you probably have this header included.

Maybe there is some better way? In which case lets change it

File: Userland/Libraries/LibJS/Tests/this-value-strict.js [hunk 4]
```diff
@@ -0,0 +1,424 @@
...
+    });
+
+    test("bound function gets overwritten this value", () => {
+        const boundFunction = functionInArrow.bind(customThisValue);
+        expect(boundFunction()).toBe(customThisValue);
+
+        const boundFunctionWithArrow = functionWithArrow.bind(customThisValue);
+        expect(boundFunctionWithArrow()()).toBe(customThisValue);
+
+        // However we cannot bound the arrow function itself
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value-strict.js:109]:
```suggestion
        // However we cannot bind the arrow function itself
```

File: Userland/Libraries/LibJS/Tests/this-value-strict.js [hunk 5]
```diff
@@ -0,0 +1,424 @@
...
+        expect(basic.func()).toBe(basic);
+        expect(basic2.func()).toBe(basic2);
+    });
+
+    test("calling arrow function created in constructor should give instance as this value", () => {
+        expect(basic.arrowFunctionInClass()).toBe(basic);
+        expect(basic2.arrowFunctionInClass()).toBe(basic2);
+    });
+
+    test("can bound function in class", () => {
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value-strict.js:220]:
```suggestion
    test("can bind function in class", () => {
```

File: Userland/Libraries/LibJS/Tests/this-value-strict.js [hunk 6]
```diff
@@ -0,0 +1,424 @@
...
+    });
+
+    test("base and derived functions get correct this values", () => {
+        const derived = new Derived(12);
+
+        expect(derived.derivedFunction()).toBe(derived);
+        expect(derived.baseFunction()).toBe(derived);
+    });
+
+    test("can bound derived and base functions", () => {
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value-strict.js:275]:
```suggestion
    test("can bind derived and base functions", () => {
```

File: Userland/Libraries/LibJS/Tests/this-value.js [hunk 7]
```diff
@@ -0,0 +1,446 @@
...
+    });
+
+    test("bound function gets overwritten this value", () => {
+        const boundFunction = functionInArrow.bind(customThisValue);
+        expect(boundFunction()).toBe(customThisValue);
+
+        const boundFunctionWithArrow = functionWithArrow.bind(customThisValue);
+        expect(boundFunctionWithArrow()()).toBe(customThisValue);
+
+        // However we cannot bound the arrow function itself
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value.js:107]:
```suggestion
        // However we cannot bind the arrow function itself
```

File: Userland/Libraries/LibJS/Tests/this-value.js [hunk 8]
```diff
@@ -0,0 +1,446 @@
...
+        expect(basic.func()).toBe(basic);
+        expect(basic2.func()).toBe(basic2);
+    });
+
+    test("calling arrow function created in constructor should give instance as this value", () => {
+        expect(basic.arrowFunctionInClass()).toBe(basic);
+        expect(basic2.arrowFunctionInClass()).toBe(basic2);
+    });
+
+    test("can bound function in class", () => {
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value.js:218]:
```suggestion
    test("can bind function in class", () => {
```

File: Userland/Libraries/LibJS/Tests/this-value.js [hunk 9]
```diff
@@ -0,0 +1,446 @@
...
+    });
+
+    test("base and derived functions get correct this values", () => {
+        const derived = new Derived(12);
+
+        expect(derived.derivedFunction()).toBe(derived);
+        expect(derived.baseFunction()).toBe(derived);
+    });
+
+    test("can bound derived and base functions", () => {
```
Comment (linusg) [inline Userland/Libraries/LibJS/Tests/this-value.js:273]:
```suggestion
    test("can bind derived and base functions", () => {
```

**Comment by davidot** [comment]
Fixed typos and skipped tests which ASAN was not happy with for now.
(The tests are kind overly complicated anyway)

File: Userland/Libraries/LibJS/Runtime/GlobalObject.h (hunk 3 above)
Comment (linusg) [reply Userland/Libraries/LibJS/Runtime/GlobalObject.h]: I don't know of a better way, I think this is fine for now :)
