### PR TITLE
Userland: Fix crash when inputting non-tty device into ps

### LINKED ISSUE #13299: ps: Crash when trying to autocomplete parameters from Shell
To reproduce, in Shell: `ps -<tab>`

cc @supercomputer7 @alimpfard

### PR DESCRIPTION
**Pull request by tsymalla**
This PR aims to fix #13299 by avoiding assertion failure
while trying to determine the pseudo tty when inputting
any non-tty device device into ps.

### CODE REVIEW

File: Userland/Utilities/ps.cpp [hunk 1]
```diff
@@ -20,14 +20,22 @@ static ErrorOr<String> determine_tty_pseudo_name()
...
     if (tty_device_major == 201) {
         return String::formatted("pts:{}", tty_device_minor);
     }
+
     if (tty_device_major == 4) {
         return String::formatted("tty:{}", tty_device_minor);
     }
+
+    if (tty_device_major == 1 && tty_device_minor == 3) {
+        return String::formatted("tty:{}", tty_device_minor);
```
Comment (Hendiadyoin1) [inline Userland/Utilities/ps.cpp:36]: When you already know the device minor, there is no need to call String::formatted, just hardcode the string

File: Userland/Utilities/ps.cpp [hunk 2]
```diff
@@ -20,14 +20,22 @@ static ErrorOr<String> determine_tty_pseudo_name()
...
     if (tty_device_major == 201) {
         return String::formatted("pts:{}", tty_device_minor);
     }
+
     if (tty_device_major == 4) {
         return String::formatted("tty:{}", tty_device_minor);
     }
+
+    if (tty_device_major == 1 && tty_device_minor == 3) {
+        return "tty:3";
```
[the remark this answers is not in the document]
Comment (tsymalla) [reply Userland/Utilities/ps.cpp]: Sure. `null` should be a good one, so I changed this.

**Comment by tsymalla** [comment]
> Please put a note near your change in the code to explain that this is the major and minor numbers of the "/dev/null" device node. Otherwise people will look at it and might not understand why we check for these numbers.

Done.

File: Userland/Utilities/ps.cpp [hunk 3]
```diff
@@ -20,14 +20,25 @@ static ErrorOr<String> determine_tty_pseudo_name()
...
     }
+
+    // Handle the /dev/null memory device.
+    // Not doing so, will give an assertion failure
+    // when forwarding /dev/null into ps.
+    if (tty_device_major == 1 && tty_device_minor == 3) {
+        return "null";
+    }
+
     VERIFY_NOT_REACHED();
```
Comment (awesomekling) [inline Userland/Utilities/ps.cpp:42]: Okay but what if I do `ps < /dev/zero` now? :^)

I suggest we fix this for any non-TTY by simply returning `"n/a"` instead of the `VERIFY_NOT_REACHED()`

Comment (tsymalla) [reply Userland/Utilities/ps.cpp:42]: Can do that. I did not know if there was a reason for the assertion. :-)

File: Userland/Utilities/ps.cpp [hunk 4]
```diff
@@ -20,15 +20,19 @@ static ErrorOr<String> determine_tty_pseudo_name()
...
+
     if (tty_device_major == 201) {
         return String::formatted("pts:{}", tty_device_minor);
     }
+
     if (tty_device_major == 4) {
         return String::formatted("tty:{}", tty_device_minor);
     }
-    VERIFY_NOT_REACHED();
+
```
Comment (supercomputer7) [inline Userland/Utilities/ps.cpp:34]: Nitpick: No need for this new line here :)

**Review by supercomputer7 — APPROVED** [review]
I'd suggest to rename the commit message to be:
```
Userland: Fix crash when inputting non-TTY device into ps
```
Besides that one little nitpick I posted, this looks OK :)

**Comment by tsymalla** [comment]
Alright! Thanks for the review comments.
