### PR TITLE
LibWeb: A bunch of fixes that are actually very related to text layouting and only tangentially related to the web

### LINKED ISSUE #9415: Regression: Help fails to render code (some) code snippets
help

See screenshot. The code snippet shows up fine in Terminal, but is missing lines in Help.

### PR DESCRIPTION
**Pull request by sin-ack**
All boogs fixed, no moar boogs.

image

Fixes #9415.

**LibWeb: Refactor TextNode::ChunkIterator**

This commit refactors the text chunking algorithm used in
TextNode::ChunkIterator. The m_start_of_chunk member parameter has been
replaced with a local variable that's anchored to the current iterator
at the start of every next() call, and the algorithm is made a little
more clear by explicitly separating what can and cannot peek into the
next character during iteration.

**LibWeb: Rename wrap_breaks to respect_linebreaks**

This more clearly expresses the purpose of this flag. Since only
CSS::WhiteSpace::Nowrap sets this value to false and it does not respect
linebreaks, this made the most sense as a flag name.

**LibGfx: Return 0 width for non-printable ASCII characters**

Non-printable characters should always have a width of 0. This is not
true for some characters like tab, but those can be exempted as the need
arises. Doing this here saves us from a bunch of checks in any place
that needs to figure out glyph widths for text which can contain
non-printable characters.

**LibWeb: Properly handle newlines at the end of LineBoxes**

This always subtracted the glyph width of a space, despite isspace
also accepting newlines and a few other characters. It now also uses
AK/CharacterTypes.h. :^)

### CODE REVIEW

File: Userland/Libraries/LibWeb/Layout/LineBox.cpp [hunk 1]
```diff
@@ -40,16 +40,21 @@ void LineBox::trim_trailing_whitespace()
...
 
-    int space_width = last_fragment.layout_node().font().glyph_width(' ');
-    while (last_fragment.length() && isspace(last_text[last_fragment.length() - 1])) {
+    while (last_fragment.length()) {
+        auto last_character = last_text[last_fragment.length() - 1];
+        if (!is_ascii_space(last_character))
+            break;
+
+        int last_character_width = last_fragment.layout_node().font().glyph_width(last_character);
+        dbgln("Width of {} is apparently {}", last_character, last_character_width);
```
Comment (TobyAsE) [inline Userland/Libraries/LibWeb/Layout/LineBox.cpp:54]: I don't think this is supposed to stay here is it?

**Comment by awesomekling** [comment]
Looks excellent!
