### PR TITLE
Calendar improvements

### LINKED ISSUE #21713: Calendar: Window marked as "modified" after adding event, no prompt on close
To reproduce:

1. Open Calendar
2. Create a new event
3. Notice that the Calendar window now has the "x" close button with "..."
4. Click the close button
5. Notice how it closes without prompting

The window modified state is supposed to indicate that there's some unsaved state. If I close the window with unsaved state, I expect to be prompted about saving it :)

### PR DESCRIPTION
**Pull request by david072**
This PR contains some small improvements for the calendar application:
- Added a date picker dialog to make selecting dates easier
- Refactored the code a little bit to make calendar events easier to work with
- Removed some unused code
- Ask about unsaved changes when attempting to close the window (fixes #21713)

image

### CODE REVIEW

File: Userland/Applications/Calendar/EventManager.cpp [hunk 1]
```diff
@@ -26,13 +26,14 @@ OwnPtr<EventManager> EventManager::create()
 void EventManager::add_event(Event event)
 {
     m_events.append(move(event));
-    set_dirty(true);
+    m_dirty = true;
```
Comment (AtkinsSJ) [inline Userland/Applications/Calendar/EventManager.cpp:29]: What's the intention behind this commit? Either we should always use `set_dirty()`, or we should remove that method entirely.

**Comment by ADKaster** [comment]
@david072 I rebased this and fixed the conflicts, and I'll merge once it passes CI. I did find a couple boogs that I'll open as issues though.

**Review by ADKaster — APPROVED** [review]
