### PR TITLE
Kernel: Clear stopped state when a process dies

### LINKED ISSUE #26492: Kernel: Crash while shutting down with a stopped process
Seems like thread and process states aren't getting desynchronized when stopping (not sure why the `VERIFY` would expect that tbh). This happens quite easily, just:
1. start any process (e.g. `cat`)
2. `^Z`
3. `poweroff`

...and you'll hit this assertion during the shutdown process:
https://github.com/SerenityOS/serenity/blob/5cd22bb99c2a9e201f88cdb359df0db167bdaa19/Kernel/Tasks/Thread.cpp#L366-L370

### PR DESCRIPTION
**Pull request by lukarajic**
Fixes #26492

### Problem Description
When a process is stopped (e.g. via `SIGTSTOP` or `^Z`) and then killed (e.g. via `poweroff`), it transitions to the Dying state but remains marked as stopped. This causes an assertion failure in `Thread::set_should_die()` because it expects the process to not be stopped if the thread is stopped.

### Proposed Fix
This patch clears the stopped state in `Process::die()` while holding the scheduler lock, ensuring that threads can be correctly resumed to clean up their kernel stacks before exiting.

### CODE REVIEW

File: Kernel/Tasks/Process.cpp [hunk 1]
```diff
@@ -1015,6 +1015,10 @@ void Process::die()
         return;
     }
 
+    {
```
Comment (implicitfield) [inline Kernel/Tasks/Process.cpp:1018]: I'd remove the extra scoping for this and just hold the lock until the end of the function. `set_stopped` is already an atomic operation, so the idea with taking this lock is just to prevent a concurrent `Thread::set_state` from changing the process's stopped state before its threads are marked to die.

Comment (lukarajic) [reply Kernel/Tasks/Process.cpp]: I've gone ahead and removed the extra scoping as requested and amended my commit

**Comment by implicitfield** [comment]
Thanks, looks good to me! I can neither approve nor merge this though, so we'll need to wait for a maintainer to look at this.

File: Kernel/Tasks/Process.cpp [hunk 2]
```diff
@@ -1015,6 +1015,8 @@ void Process::die()
         return;
     }
 
+    SpinlockLocker lock(g_scheduler_lock);
+    set_stopped(false);
```
Comment (spholz) [inline Kernel/Tasks/Process.cpp]: nit: please add an empty line after this line here

**Comment by lukarajic** [comment]
Hi @implicitfield! 
There's been some discussion around this fix on the SerenityOS discord, particularly around taking the global scheduler lock for what seems to be some relatively heavy operations. Do you have any input or suggestions to mitigate this? 
Also, could you please clarify why `Thread::set_state` can cause problems in the first place because currently we are holding the spinlock after setting the state to dying and there seems to be some confusion around this.

**Comment by implicitfield** [comment]
> There's been some discussion around this fix on the SerenityOS discord, particularly around taking the global scheduler lock for what seems to be some relatively heavy operations. Do you have any input or suggestions to mitigate this?

You could probably handle notifying the tracer threads outside of the lock (that could even be the last thing that this function does), but changing anything that affects the process's internal state without holding that lock seems risky.

> Also, could you please clarify why `Thread::set_state` can cause problems in the first place because currently we are holding the spinlock after setting the state to dying and there seems to be some confusion around this.

My concern is just that the scheduler might (concurrently or in parallel) be scheduling another thread that is also a member of the same process and has a SIGSTOP pending. Dispatching that signal to that thread would then stop the process again (via `Thread::set_state`).

I doubt that just marking the process as dying without taking the scheduler lock would be enough to prevent that scenario from happening since the scheduler doesn't actually look at the process's state (it only looks at the thread's state, and `Process::die()` doesn't actually change that). IMO the scheduler shouldn't dispatch signals to threads that are marked to die, and I was planning on fixing that once this gets merged, but that depends on `Process::die()` holding the scheduler lock while it changes the properties of the process's member threads.

**Comment by lukarajic** [comment]
> You could probably handle notifying the tracer threads outside of the lock (that could even be the last thing that this function does), but changing anything that affects the process's internal state without holding that lock seems risky.

Ok, I've gone ahead and applied the newly suggested smaller lock scope. Please let me know what you think!

**Comment by implicitfield** [comment]
> Ok, I've gone ahead and applied the newly suggested smaller lock scope. Please let me know what you think!

This seems fine to me as well. It looks like ptrace is somewhat buggy (it allows tracing threads in the same process in some cases) so sending a SIGSTOP to the current process could place it in the stopped state again, but IMO that's really a separate bug that should be fixed by properly disallowing that at the syscall level.
