### PR TITLE
Kernel: Ignore an invalid QEMU multiboot entry

### LINKED ISSUE #14952: Kernel: x86_64 Fails to boot (physical page alloc issue?)
SerenityOS repository commit ID: 7881331 (08/21/2022)

**Issue:**
SerenityOS fails to boot in a fresh x86_64 build, both with 1G and 2G memory under QEMU. It builds and happily boots with the same configuration under i686. Any help would be appreciated!

**Boot arguments:**
```text
qemu-system-x86_64.exe -name "SerenityOS" -d guest_errors -m 1G -cpu max,vmx=off,-x2apic -accel whpx,kernel-irqchip=off -smp 2 -drive file=serenityos.qcow2,format=qcow2,index=0,media=disk,id=disk -kernel "Prekernel" -initrd "Kernel" -append "hello disable_virtio" -device pci-bridge,chassis_nr=1,id=bridge1 -device i82801b11-bridge,bus=bridge1,id=bridge2 -device i82801b11-bridge,id=bridge3 -device sdhci-pci,bus=bridge2 -device sdhci-pci,bus=bridge3 -device ich9-ahci,bus=bridge3 -device e1000,bus=bridge1 -device e1000,netdev=breh -netdev user,id=breh,hostfwd=tcp:127.0.0.1:8888-10.0.2.15:8888,hostfwd=tcp:127.0.0.1:8823-10.0.2.15:23,hostfwd=tcp:127.0.0.1:8000-10.0.2.15:8000,hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22 -audiodev dsound,id=snd0 -machine pcspk-audiodev=snd0 -device ac97,audiodev=snd0 -device VGA,vgamem_mb=64 -display sdl,gl=off -spice port=5930,agent-mouse=off,disable-ticketing=on -device virtio-serial,max_ports=2 -device virtconsole,chardev=stdout -device isa-debugcon,chardev=stdout -device virtio-rng-pci -chardev stdio,id=stdout,mux=on -chardev qemu-vdagent,clipboard=on,mouse=off,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,nr=1 -usb
```

**Kernel bootlog:**
```text
Windows Hypervisor Platform accelerator is operational
qemu-system-x86_64.exe: warning: nic e1000.0 has no peer
0.000 [Kernel]: Loading kernel symbol table...
0.000 [Kernel]: CPU[0]: Supported features: sse3 pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 cnxt_id sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 movbe popcnt tsc_deadline aes xsave osxsave avx f16c rdrand hypervisor fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 psn clflush ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe fsgsbase bmi1 avx2 smep bmi2 erms invpcid zero_fcs_fds mpx rdseed adx smap clflushopt ia32_arch_capabilities lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb dbx perftsc pcx_l2i syscall mp nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow
0.000 [Kernel]: CPU[0]: Physical address bit width: 39
0.000 [Kernel]: CPU[0]: Virtual address bit width: 48
0.000 [#0 Kernel]: Initializing unhandled interrupt handlers
0.000 [Kernel]: CPU[0]: CPUID hypervisor signature '', max leaf 0x40000010
0.000 [Kernel]: Kernel Commandline: Prekernel hello disable_virtio
0.000 [Kernel]: MM: Multiboot mmap: address=0x0000000000000000, length=654336, type=1
0.000 [Kernel]: MM: Got an unaligned physical_region from the bootloader; correcting length 654336 by 3072 bytes
0.000 [Kernel]: MM: Multiboot mmap: address=0x000000000009fc00, length=1024, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x00000000000f0000, length=65536, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x0000000000100000, length=1072562176, type=1
0.000 [Kernel]: MM: Multiboot mmap: address=0x000000003ffe0000, length=131072, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x00000000fffc0000, length=262144, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x000000fd00000000, length=12884901888, type=2
0.000 [Kernel]: MM: Contiguous reserved range from P000000000009fc00, length is 394240
0.000 [Kernel]: MM: Contiguous reserved range from P000000003ffe0000, length is 1098438017024
0.000 [Kernel]: MM: Need 525314 bytes for physical page management, but no memory region is large enough!
[Kernel]: ASSERTION FAILED: not reached
[Kernel]: ./Kernel/Memory/MemoryManager.cpp:418 in void Kernel::Memory::MemoryManager::initialize_physical_pages()
[Kernel]: KERNEL PANIC! :^(
[Kernel]: Aborted
[Kernel]: at ./Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[Kernel]: Kernel + 0x0000000000ce882f  Kernel::__panic(char const*, unsigned int, char const*) +0x16f
[Kernel]: Kernel + 0x0000000001239671  abort.localalias +0x38a
[Kernel]: Kernel + 0x00000000012392e7  abort.localalias +0x0
[Kernel]: Kernel + 0x00000000015c2f6c  Kernel::Memory::MemoryManager::initialize_physical_pages() [clone .localalias] +0x172c
[Kernel]: Kernel + 0x00000000015ce91f  Kernel::Memory::MemoryManager::parse_memory_map() [clone .localalias] +0x58ff
[Kernel]: Kernel + 0x00000000015d0d64  Kernel::Memory::MemoryManager::MemoryManager() [clone .localalias] +0x7a4
[Kernel]: Kernel + 0x00000000015d3527  Kernel::Memory::MemoryManager::initialize(unsigned int) +0x1b7
[Kernel]: Kernel + 0x0000000001632f56  init +0x506
[Kernel]: Kernel + 0xffffffdff13038f7
```

**Build host:**
Ubuntu/WSL2 running on Windows 10 21H2 64-bit (19044.1889), Hypervisor Platform enabled

**uname -a:**
```
Linux BLW-HP 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Build steps:**
```text
git clone https://github.com/SerenityOS/serenity.git && cd serenity && Meta/serenity.sh rebuild-toolchain x86_64 && Meta/serenity.sh build x86_64 && Meta/serenity.sh copy-src x86_64
```

Afterwards, I wanted faster I/O, so I copied the image, Kernel, Prekernel & launch arguments (into a batch file) into a seperate directory on my SSD (and converted the disk to QCOW2 because why not?).

No errors were reported during build.

**Additional notes:**
Do note that I built i686 successfully before, and it worked without any issues, both with 1 & 2 GBs of RAM. This only happened in a clean build of x86_64.

### PR DESCRIPTION
**Pull request by implicitfield**
This makes the kernel ignore a seemingly invalid QEMU multiboot entry and allows Serenity to boot once again on the q35 machine on x86-based platforms.

For reference, a similar fix was put in place by [this](https://gitlab.com/weinholt/loko/-/commit/1e88ef9067a3d53f1148e87962335a6a1bb12bc8) project.

Fixes #14952.

### CODE REVIEW

**Comment by ADKaster** [comment]
I haven't convinced myself that the conditional is correct there yet, but a fix for 14952 should remove the workaround in run.sh that we added for it. 

https://github.com/SerenityOS/serenity/blob/master/Meta/run.sh#L124

File: Kernel/Memory/MemoryManager.cpp [hunk 1]
```diff
@@ -291,7 +291,11 @@ UNMAP_AFTER_INIT void MemoryManager::parse_memory_map()
                 global_data.physical_memory_ranges.append(PhysicalMemoryRange { PhysicalMemoryRangeType::Usable, start_address, length });
                 break;
             case (MULTIBOOT_MEMORY_RESERVED):
-                global_data.physical_memory_ranges.append(PhysicalMemoryRange { PhysicalMemoryRangeType::Reserved, start_address, length });
+#if ARCH(I386) || ARCH(X86_64)
+                // Workaround for QEMU commit 8504f12.
```
Comment (linusg) [inline Kernel/Memory/MemoryManager.cpp:295]: Please:
- Add a link to said commit
- Go into slightly more detail so others can understand what this is doing

Comments are free :)

**Review by linusg — CHANGES_REQUESTED** [review]

File: Kernel/Memory/MemoryManager.cpp [hunk 2]
```diff
@@ -291,7 +291,18 @@ UNMAP_AFTER_INIT void MemoryManager::parse_memory_map()
...
-                global_data.physical_memory_ranges.append(PhysicalMemoryRange { PhysicalMemoryRangeType::Reserved, start_address, length });
+#if ARCH(I386) || ARCH(X86_64)
+                // Workaround for https://gitlab.com/qemu-project/qemu/-/commit/8504f129450b909c88e199ca44facd35d38ba4de
+                // That commit added a reserved 12GiB entry for the benefit of virtual firmware.
+                // We can safely ignore this block as it isn't actually reserved on any real hardware.
+                // From: https://lore.kernel.org/all/20220701161014.3850-1-joao.m.martins@oracle.com/
+                // "Always add the HyperTransport range into e820 even when the relocation isn't
+                // done *and* there's >= 40 phys bit that would put max phyusical boundary to 1T
+                // This should allow virtual firmware to avoid the reserved range at the
+                // 1T boundary on VFs with big bars."
```
Comment (linusg) [inline Kernel/Memory/MemoryManager.cpp:302]: :100:

File: Kernel/Memory/MemoryManager.cpp (hunk 1 above)
Comment (linusg) [reply Kernel/Memory/MemoryManager.cpp]: :100:
