### PR TITLE
LibSQL: Handle statements with malformed exists expressions correctly

### LINKED ISSUE #18036: SQLParser: Null pointer dereference in parse_insert_statement
When fuzzing `FuzzSQLParser`, we found that the program crashed with the following statement: ```INSERT INTO t(a,b)VALUES(0,8),(/**/SELECT```. I'm sorry that I cannot find the root cause, but here's a stack trace:

```
Crashing thread backtrace:
#0  0x000055555572c5e6 in AK::unref_if_not_null<SQL::AST::CommonTableExpressionList> (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzSQLParser)
                       ??: void AK::unref_if_not_null<SQL::AST::CommonTableExpressionList>(ptr = (SQL::AST::CommonTableExpressionList *)<optimized out>) {
                       ||:
                       ||: /* Local reference: SQL::AST::CommonTableExpressionList * ptr = <optimized out>; */
                       31: {
                       32:     if (ptr)
                       33:         ptr->unref();
                       ||:
                       --: }
                       at /root/build/serenity/Meta/Lagom/../../AK/NonnullRefPtr.h:33

#1  0x000055555572c5e6 in AK::RefPtr<SQL::AST::CommonTableExpressionList>::clear (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzSQLParser)
                       ???: void AK::RefPtr<SQL::AST::CommonTableExpressionList>::clear(this = (AK::RefPtr<SQL::AST::CommonTableExpressionList> *)<optimized out>) {
                       |||:
                       221:     ALWAYS_INLINE void clear()
                       222:     {
                       223:         unref_if_not_null(m_ptr);
                       |||:
                       ---: }
                       at /root/build/serenity/Meta/Lagom/../../AK/RefPtr.h:223

#2  0x000055555572c5e6 in AK::RefPtr<SQL::AST::CommonTableExpressionList>::~RefPtr (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzSQLParser)
                       ???: void AK::RefPtr<SQL::AST::CommonTableExpressionList>::~RefPtr(this = (AK::RefPtr<SQL::AST::CommonTableExpressionList> *)<optimized out>) {
                       |||:
                       102:     ALWAYS_INLINE ~RefPtr()
                       103:     {
                       104:         clear();
                       |||:
                       ---: }
                       at /root/build/serenity/Meta/Lagom/../../AK/RefPtr.h:104

#3  0x000055555572c5e6 in SQL::AST::Parser::parse_insert_statement (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-AFLpp-ASan-UBSan/FuzzSQLParser)
                       197: AK::NonnullRefPtr<SQL::AST::Insert> SQL::AST::Parser::parse_insert_statement(this = (SQL::AST::Parser *)<optimized out>, common_table_expression_list = (AK::RefPtr<SQL::AST::CommonTableExpressionList>){m_ptr = <optimized out>}) {
                       |||:
                       |||: /* Local reference: AK::RefPtr<SQL::AST::Select> select_statement = {m_ptr = <optimized out>}; */
                       231:         });
                       232:     } else if (match(TokenType::Select)) {
                       233:         select_statement = parse_select_statement({});
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:233
```

### LINKED ISSUE #18302: SQLParser: Null pointer dereference in parse_comma_separated_list
When fuzzing FuzzSQLParser, we found that the program crashed with the following statement: `INSERT INTO d(a,b)VALUES(2,5),(SELECT+`:

```
Crashing thread backtrace:
#0  0x00005555559538dc in operator() (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzSQLParser)
                       ???: void operator()() {
                       |||:
                       221:             if (auto chained_expression = parse_chained_expression()) {
                       222:                 auto chained_expr = dynamic_cast<ChainedExpression*>(chained_expression.ptr());
                       223:                 if ((column_names.size() > 0) && (chained_expr->expressions().size() != column_names.size())
) {
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:223

#1  0x00005555559538dc in parse_comma_separated_list<(lambda at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:220:43)> (
/root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzSQLParser)
                       ???: void parse_comma_separated_list<(lambda at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:220
:43)>() {
                       |||:
                       108:
                       109:         while (!has_errors() && !match(TokenType::Eof)) {
                       110:             parse_callback();
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.h:110

#2  0x00005555559538dc in parse_insert_statement (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzSQLParser)
                       ???: void parse_insert_statement() {
                       |||:
                       218:
                       219:     if (consume_if(TokenType::Values)) {
                       220:         parse_comma_separated_list(false, [&]() {
                       |||:
                       ---: }
                       at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:220

#3  0x0000555555950e36 in parse_statement (/root/build/serenity/Meta/Lagom/Bin/Fuzzers-DataCov/FuzzSQLParser)
                       ??: void parse_statement() {
                       ||:
                       51:         return parse_describe_table_statement();
                       52:     case TokenType::Insert:
                       53:         return parse_insert_statement({});
                       ||:
                       --: }
                       at /root/build/serenity/Userland/Libraries/LibSQL/AST/Parser.cpp:53
```

### PR DESCRIPTION
**Pull request by tcl3**
Previously, using the `SELECT` keyword within a `VALUES` expression would cause a null pointer dereference, crashing the running program.

I was able to reproduce the bug with the following statement, on a blank database in SQL Studio:

`INSERT INTO t(a) VALUES(SELECT);`

I have also tested this fix against the statements in the linked issues:

`INSERT INTO t(a,b)VALUES(0,8),(/**/SELECT;`

and

`INSERT INTO d(a,b)VALUES(2,5),(SELECT+;`

Fixes #18036

Fixes #18302

### CODE REVIEW

File: Userland/Libraries/LibSQL/AST/Parser.cpp [hunk 1]
```diff
@@ -219,8 +219,10 @@ NonnullRefPtr<Insert> Parser::parse_insert_statement(RefPtr<CommonTableExpressio
     if (consume_if(TokenType::Values)) {
         parse_comma_separated_list(false, [&]() {
             if (auto chained_expression = parse_chained_expression()) {
-                auto chained_expr = dynamic_cast<ChainedExpression*>(chained_expression.ptr());
-                if ((column_names.size() > 0) && (chained_expr->expressions().size() != column_names.size())) {
+                auto* chained_expr = dynamic_cast<ChainedExpression*>(chained_expression.ptr());
+                if (!chained_expr) {
+                    expected("Chained expression"sv);
```
Comment (trflynn89) [inline Userland/Libraries/LibSQL/AST/Parser.cpp:224]: I don't think this is the right fix, as `parsed_chain_expression` can clearly return an EXISTS expression. That might have a misunderstanding of the grammar though.

IIRC, the ambiguity was that the grammar here is basically `(expr, expr, expr, ...)` where `expr` is any of these:
https://sqlite.org/syntax/expr.html

So I think at the time, this was trying to disambiguate a single-chain chained expression - `(expr)` - from an EXISTS expression that does not have the `EXISTS` keyword, which is legal - `(SELECT ...)`. However, looking a bit more closely, I think that would require a second set of parentheses, `((SELECT ...))`.

If that's the case, the fix is to probably just remove the ambiguity check from `parsed_chain_expression`.

Comment (tcl3) [reply Userland/Libraries/LibSQL/AST/Parser.cpp]: Thanks for the detailed explanation. I've attempted a more complete fix to the problem. 

The fact that you can drop the EXISTS keyword in an ExistsExprerssion means that there is an ambiguity in the grammar at the point that you encounter the second open parenthesis in `((SELECT ...)). In this situation, it is not possible to determine whether you are looking at a nested ChainedExpression or an ExistsExpression before consuming the ParenOpen token. 

The attempt I've made to fix it seems a bit hacky to me. Situations like this could be handled more neatly if the parser had the ability to lookahead multiple tokens. I realize that this isn't straightforward and potentially makes the parser code more difficult to reason about though. Given the few places where ambiguities like this occur, it probably isn't worth doing.

**Comment by tcl3** [comment]
orry it's taken me a while to get to this. My latest push is a more complete fix to the parsing of exists expressions. Statements like:

`INSERT INTO t(a) VALUES (EXISTS (SELECT 1));`

or the shorthand:

`INSERT INTO t(a) VALUES ((SELECT 1));`

should now parse correctly. Attempting to execute statements like these will currently result in a `NotYetImplemented` error message though, as sub-selects have not been implemented. I've included test cases for statements where exists expressions can be used.

**Comment by GMTA** [comment]
@tcl3

> Let me know if I should only include test cases which test the issue I'm fixing.

Well, adding a test case exposing the issue you've fixed would be the most interesting of course! It will also prevent a regression in the future.

**Review by trflynn89 — APPROVED** [review]
This seems fine, and the extra tests are much appreciated :)

I think we could make it a bit cleaner if we steal the "look ahead N tokens" method from LibJS's parser:
```c++
Token Parser::next_token(size_t steps) const
{
    Lexer lookahead_lexer = m_state.lexer;

    Token lookahead_token;

    while (steps > 0) {
        lookahead_token = lookahead_lexer.next();
        steps--;
    }

    return lookahead_token;
}
```

But this is fine for now.
