### PR TITLE
LibWeb: Implement HTML Specifications's "encoding sniffing algorithm"

### LINKED ISSUE #6910: LibWeb: Opening non-Unicode local file fails even with <meta charset> tag
When opening a local HTML file with a non-Unicode encoding in the browser. The browser crashes if the file contains codepoint larger than 0x80.

This happens because the browser reads the file with UTF-8 encoding:
```
Browser(31:31): I believe this content has MIME type 'text/html', encoding 'utf-8'
Browser(31:31): USERSPACE(31) ASSERTION FAILED: first_byte_makes_sense
../../AK/Utf8View.cpp:171
```

### Expected Behaviour
While I haven't read the HTML spec, I think there is something like: "If you encounter an meta-charset tag with a different encoding, continue reading the file with the new encoding." This seems not to be implemented (correctly).

### Steps to Reproduce
```
$ printf "<head><meta charset='latin1'></head>\n" > test.html
$ printf "Copyright sign: \xA9\n" >> test.html
$ br -s test.html
ASSERTION FAILED: first_byte_makes_sense
../../AK/Utf8View.cpp:171
Shell: Job 1 (Browser -s test.html) Aborted
```
If you omit the Latin-1-specific `\xA9` (copyright sign) then everything works as expected.

### PR DESCRIPTION
**Pull request by MaxWipfli**
This pull request partly implements the [HTML Specification's encoding sniffing algorithm](https://html.spec.whatwg.org/multipage/parsing.html#determining-the-character-encoding). This allows LibWeb to now load some non-UTF-8 files even when there is no `Content-Type: text/html; charset=foo` HTTP header available (such as if a local file is loaded).

Now, this should work:
```sh
printf "\xA9" >> test.html # This is a windows-1252 copyright sign, which is invalid UTF-8.
br -s test.html
```

Whereas before, this happened:
```
ASSERTION FAILED: first_byte_makes_sense
../../AK/Utf8View.cpp:169
```

This change required some minor architectural changes, as the information that no encoding was specified in the `Content-Type` header has to be "transmitted" from `FrameLoader` to `Resource` to `Document` to `HTMLDocumentParser`, where this algorithm should reside (at least that's what I think). Most importantly, I modified the `Resource` and `Document` classes to use `Optional<String>` for their `m_encoding`.

With all of this, if no encoding is specified, we do no longer decide on using UTF-8 in `FrameLoader`, rather delaying this decision as long as possible. This allows the HTML encoding sniffing algorithm (as well as possible future algorithms for determining encodings of arbitrary non-HTML plain text documents) to determine whether the encoding is already known or if they need to get to work.

This pull request also includes three minor changes to some more generic APIs:
* `AK::StringBuilder::append_as_lowercase(char ch)` has been added.
* `TextCodec::get_standardized_encoding` now returns `Optional<String>`. If it cannot match the provided encoding to a standarized one, it will now return as an empty `Optional`. Before that, this function returned the empty string to indicate failure.
* `TextCodec::is_valid_utf8(const ByteBuffer& input)` has been added.

This pull request fixes #6910.

**Note**: I am not expecting a merge right away. This is my first large change here. I would especially like some feedback about my choice of putting the algorithm into it's own file, `HTMLEncodingDetection.cpp/h`. I am not sure if this is the right way to structure it.

### CODE REVIEW

File: Userland/Libraries/LibWeb/DOM/Document.h [hunk 1]
```diff
@@ -237,13 +237,15 @@ class Document
...
+    String encoding_or_default() const { return m_encoding.value_or("UTF-8"); }
     void set_encoding(const String& encoding) { m_encoding = encoding; }
 
     // NOTE: These are intended for the JS bindings
-    const String& character_set() const { return encoding(); }
-    const String& charset() const { return encoding(); }
-    const String& input_encoding() const { return encoding(); }
+    String character_set() const { return encoding_or_default(); }
+    String charset() const { return encoding_or_default(); }
+    String input_encoding() const { return encoding_or_default(); }
```
Comment (MaxWipfli) [inline Userland/Libraries/LibWeb/DOM/Document.h:248]: What are these "JS bindings"? I cannot seem to find any reference to these functions anywhere in the repository, so maybe they could even be removed?

Comment (linusg) [reply Userland/Libraries/LibWeb/DOM/Document.h:248]: Things that are exposed to JS via IDL - you'll find them used in the generated bindings code. Don't remove these, it'll break the build :)

File: Userland/Libraries/LibWeb/Loader/Resource.h [hunk 2]
```diff
@@ -52,7 +52,8 @@ class Resource : public RefCounted<Resource> {
     void register_client(Badge<ResourceClient>, ResourceClient&);
     void unregister_client(Badge<ResourceClient>, ResourceClient&);
 
-    const String& encoding() const { return m_encoding; }
+    bool has_encoding() const { return m_encoding.has_value(); }
+    const Optional<String> encoding() const { return m_encoding; }
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/Resource.h:56]: This should be returned by reference to avoid copies.
```suggestion
    const Optional<String>& encoding() const { return m_encoding; }
```

File: Userland/Libraries/LibWeb/Loader/FrameLoader.cpp [hunk 3]
```diff
@@ -251,12 +251,13 @@ void FrameLoader::resource_did_load()
...
     } else {
-        dbgln("This content has MIME type '{}', encoding unknown (defaulting to 'utf-8')", resource()->mime_type());
+        dbgln("This content has MIME type '{}', encoding unknown", resource()->mime_type());
     }
 
     auto document = DOM::Document::create();
     document->set_url(url);
-    document->set_encoding(resource()->encoding().value_or("utf-8"));
+    if (resource()->has_encoding())
+        document->set_encoding(resource()->encoding().value());
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/FrameLoader.cpp:260]: This relies on the document having no encoding before trying to set it, otherwise it would "keep" the previous encoding. This wouldn't be an issue with the current architecture, but could become one later if the document creation changes somehow : this limitation could go unnoticed during a refactor and cause a bug where the previous document encoding is kept on new documents.

How about changing the `set_encoding` method to `document.set_encoding(Optional<String> const&)`, and passing the optional resource encoding directly ?

File: Userland/Libraries/LibWeb/Loader/Resource.cpp [hunk 4]
```diff
@@ -90,9 +90,6 @@ void Resource::did_load(Badge<ResourceLoader>, ReadonlyBytes data, const HashMap
         if (encoding.has_value()) {
             dbgln_if(RESOURCE_DEBUG, "Set encoding '{}' from Content-Type", encoding.has_value());
             m_encoding = encoding.value();
-        } else {
-            // FIXME: This doesn't seem nice.
-            m_encoding = "utf-8";
         }
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/Resource.cpp]: Let's unset the encoding explicitly if we can't find one from the content type and encoding (probably by adding a `m_encoding = {};` before this whole if)

**Review by Dexesttp — COMMENTED** [review]
Pretty good stuff, very idiomatic and easy to read :)

**Comment by MaxWipfli** [comment]
> Pretty good stuff, very idiomatic and easy to read :)

Thanks for the review @Dexesttp, I have implemented all your suggestions!

**Review by awesomekling — CHANGES_REQUESTED** [review]
`String` already has a null state. It's different from the empty string.

`String()` gives you a null string (the internal `StringImpl` pointer is null)
`String("")` or `String::empty()` gives you the empty string (the internal `StringImpl` pointer points to a null-terminated, zero-length character array)

There's been some talk of getting rid of the null state in favor of using `Optional<String>` everywhere, but nobody has picked up that yak razor yet, that I know of.

So the changes around putting `String` into `Optional<String>` are a bit misinformed. That said, I think it's okay to start moving `String` into `Optional<String>` and incrementally eschewing the null state. But we should do this deliberately, so please update your commit messages to reflect this :)

File: Userland/Libraries/LibTextCodec/Decoder.cpp [hunk 5]
```diff
@@ -179,6 +179,38 @@ bool is_standardized_encoding(const String& encoding)
     return standardized_encoding.has_value() && encoding.equals_ignoring_case(standardized_encoding.value());
 }
 
+bool is_valid_utf8(const ByteBuffer& input)
```
[the remark this answers is not in the document]
Comment (MaxWipfli) [reply Userland/Libraries/LibTextCodec/Decoder.cpp:182]: The "problem" I see is that using `Utf8View::validate` requires us to create a `Utf8View` object. I have no idea about the overhead or possible copying that happens there. If there is none, I can happily do `Utf8View(StringView(input)).validate()`, it's just that this seems very "expensive" to the "untrained eye".

**Comment by MaxWipfli** [comment]
> So the changes around putting `String` into `Optional<String>` are a bit misinformed. That said, I think it's okay to start moving `String` into `Optional<String>` and incrementally eschewing the null state. But we should do this deliberately, so please update your commit messages to reflect this :)

Thanks for the heads-up. TIL. Sorry, I wasn't aware of this. I will update all the commit messages accordingly.
