### PR TITLE
LibLine+Shell: Slash mess-up fix, hidden file completion

### LINKED ISSUE #1535: Shell: Tab completion fails for .hidden files beginning with .
Tab completion fails for `.hidden` files beginning with `.`

```
$ touch .hidden
$ ls -la .h<tab><tab><tab>
$ ls -la ./.h<tab><tab><tab>
```

### LINKED ISSUE #1762: LibLine: Auto-completion goofs with "cd /<tab>"
To reproduce:

1. Open a shell
2. Type "cd /"
3. Press tab

This autocompletes to "/ost+found" for me :eyes:

### PR DESCRIPTION
**Pull request by alimpfard**
fixes #1762.

Also de-soupifies the code soup @awesomekling had created in the path suggestions of Shell

Edit: also fixes #1535
```sh
touch .test
ls .<tab> #-> ls .test
```

### CODE REVIEW

File: Libraries/LibLine/Editor.cpp [hunk 1]
```diff
@@ -445,7 +437,7 @@ String Editor::get_line(const String& prompt)
                 m_refresh_needed = true;
                 continue;
             }
-            if (ch == 0xc) {                    // ^L
```
Comment (alimpfard) [inline Libraries/LibLine/Editor.cpp:440]: oh ffs...someone give me a clang-format configuration that doesn't do this braindead thing

**Comment by awesomekling** [comment]
Excellent!
