### PR TITLE
AutocompleteBox: Enable hover over

### LINKED ISSUE #7165: GML Playground: Hovering over the auto-completion window makes it disappear
Steps to reproduce:

1. Enter `@` in the text editor and hit Ctrl-Space.
2. Try to select one of the options from the auto-completion window that appears.

Screenshot from 2021-05-16 09-21-35

The auto-completion window disappears when the mouse cursor leaves the main GML Playground window (as it should). However, this also happens when it leaves the window by moving above the auto-completion window.

### PR DESCRIPTION
**Pull request by sr1j**
Enables hovering over the autocomplete_box and also closes it when the parent_window is deactivated.
Fixes #7165 . This is my first PR and thanks to @alimpfard, @gunnarbeutner and others for the help at Discord, and not to mention @AnandBaburajan for helping me to get my first PR open.

### CODE REVIEW

**Comment by AnandBaburajan** [comment]
Fixes https://youtu.be/O3MtPgTUOC8?t=1375 :P

File: Userland/Libraries/LibGUI/TextEditor.cpp [hunk 1]
```diff
@@ -1330,10 +1330,6 @@ void TextEditor::leave_event(Core::Event&)
 {
```
Comment (alimpfard) [inline Userland/Libraries/LibGUI/TextEditor.cpp:1330]: The commit message is the same as its description, that's redundant.
Also, please write a more concise message describing what's actually happening, and add what it fixes/enables to the description instead?

Comment (sr1j) [reply Userland/Libraries/LibGUI/TextEditor.cpp:1358]: Thank you! I've updated the commit messages, please check.
