### PR TITLE
Spreadsheet: Tiny fixes

### LINKED ISSUE #4716: Spreadsheet: "click to view" example on sum help corrupts JS interpreter stack
Steps:

- Open Spreadsheets
- Open Function Help box from the ? next to the formula bar.
- Click on `sum`
- Click the `view example` buttom
- Close the example spreadsheet with the `x`
- Close the help box with the `x`
- Close the main spreadsheet window with the `x`
- 💥 

```
USERSPACE(29) ASSERTION FAILED: popped_interpreter == &interpreter
../Libraries/LibJS/Runtime/VM.cpp:87
```

```
CrashDaemon(19): New coredump file: /tmp/coredump/Spreadsheet_29_1609509863
Shell(24): Job entry "Spreadsheet" deleted in 160918 ms
CrashDaemon(19): 0x045fdf5e: [libc.so] kill +28 (Syscall.h:479)
CrashDaemon(19): 0x045fdfda: [libc.so] raise +32 (signal.cpp:54)
CrashDaemon(19): 0x045f60c9: [libc.so]  +25 (stdlib.cpp:230)
CrashDaemon(19): 0x045f69c9: [libc.so] tolower +0 (assert.cpp:51)
CrashDaemon(19): 0x0479f005: [libjs.so] JS::VM::pop_interpreter(JS::Interpreter&) +111 (VM.cpp:88)
CrashDaemon(19): 0x0479f035: [libjs.so] JS::VM::InterpreterExecutionScope::~InterpreterExecutionScope() +39 (VM.cpp:99)
CrashDaemon(19): 0x04d834d9: [/bin/Spreadsheet] Spreadsheet::SpreadsheetWidget::~SpreadsheetWidget() +67 (NonnullOwnPtr.h:157)
CrashDaemon(19): 0x04d83722: [/bin/Spreadsheet] Spreadsheet::SpreadsheetWidget::~SpreadsheetWidget() +28 (kmalloc.h:69)
CrashDaemon(19): 0x04681916: [libcore.so] AK::RefCounted<Core::Object>::unref() const [clone .isra.0] +58 (RefCounted.h:119)
CrashDaemon(19): 0x0468336f: [libcore.so] AK::Vector<AK::NonnullRefPtr<Core::Object>, 0ul>::clear_with_capacity() +105 (Atomic.h:268)
CrashDaemon(19): 0x046833a4: [libcore.so] AK::Vector<AK::NonnullRefPtr<Core::Object>, 0ul>::clear() +28 (Vector.h:138)
CrashDaemon(19): 0x04682c69: [libcore.so] Core::Object::~Object() +199 (NonnullPtrVector.h:34)
CrashDaemon(19): 0x049ca11b: [libgui.so] GUI::Window::~Window() +547 (Window.cpp:92)
CrashDaemon(19): 0x049ca16a: [libgui.so] GUI::Window::~Window() +28 (kmalloc.h:69)
CrashDaemon(19): 0x04d6d66f: [/bin/Spreadsheet] AK::RefCounted<Core::Object>::unref() const +63 (RefCounted.h:119)
CrashDaemon(19): 0x04d651a5: [/bin/Spreadsheet] main +4032 (NonnullRefPtr.h:56)
CrashDaemon(19): 0x04d6526c: [/bin/Spreadsheet] _start +36 (crt0_shared.cpp:50)
```

### PR DESCRIPTION
**Pull request by alimpfard**
This addresses https://github.com/SerenityOS/serenity/issues/4277#issuecomment-753436495 and fixes #4716.

### CODE REVIEW

File: Applications/Spreadsheet/HelpWindow.cpp [hunk 1]
```diff
@@ -124,19 +124,26 @@ HelpWindow::HelpWindow(GUI::Window* parent)
...
                 return;
             }
 
             widget.add_sheet(sheet.release_nonnull());
-            dialog->show();
+            window->show();
+            window->on_close_request = [this, key = window.ptr()] {
+                auto window = m_all_example_windows.get(key).value();
+                m_all_example_windows.remove(key);
+                const_cast<GUI::Window*>(window)->remove_from_parent();
```
Comment (alimpfard) [inline Applications/Spreadsheet/HelpWindow.cpp:144]: I feel like this is a bit hacky, not sure why `GUI::Window::construct(parent)` has to create a strong reference to the new object in the parent, but this is what I came up with :shrug:

Comment (awesomekling) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: Why do you need `m_all_example_windows` at all?

Comment (alimpfard) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: Another option is to copy `window` into this lambda to be able to call `remove_from_parent()` on it. but that's a reference cycle and I'd rather not introduce any of those

Comment (alimpfard) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: Am I missing an obvious solution here?

Comment (awesomekling) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: What I've done elswhere is capturing a raw pointer and using `on_close`:

```cpp
    properties->on_close = [properties = properties.ptr()] {
        properties->remove_from_parent();
    };
```

Comment (awesomekling) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: It's not the most beautiful thing, but meh. Another alternative might be to have `on_close` include  a `Window&` parameter.

Comment (alimpfard) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: That's what I was trying to avoid, but if it's there already, I'll change this to match.

Perhaps a better suggestion, why not just remove the window from its parent when it's "closed"?

Comment (awesomekling) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: I've specifically tried to avoid those kinds of magical ownership behaviors in LibCore/LibGUI. Some GUI toolkits work that way and it makes lifetime very confusing.

Comment (alimpfard) [reply Applications/Spreadsheet/HelpWindow.cpp:144]: is it really magical though? I fully expect a window to be deleted when
- I have no references to it
- it's closed

if anything, I think the parent holding on to it is more surprising than not.

File: Libraries/LibGUI/Window.cpp [hunk 2]
```diff
@@ -96,6 +96,8 @@ void Window::close()
     hide();
     if (on_close)
         on_close();
+    if (this->ref_count() == 1) // Only the parent is holding on to us
+        remove_from_parent();
```
Comment (alimpfard) [inline Libraries/LibGUI/Window.cpp:100]: Ooops

File: Applications/Spreadsheet/HelpWindow.cpp (hunk 1 above)
Comment (awesomekling) [reply Applications/Spreadsheet/HelpWindow.cpp]: Hm, maybe you're right. It does seem like a fairly intuitive behavior. Let's do it.

Comment (alimpfard) [reply Applications/Spreadsheet/HelpWindow.cpp]: I tried this, but it doesn't look like we can reliably detect "only referenced by parent object and being closed".
a window with no external refs has a refcount of 3 in its `close()` (when invoked through the close button)
The same could also happen if it's called from outside the event handlers, where it would have refcount == 3.
Unconditionally removing from the parent child list isn't really an option either, it would also be really surprising.

I'll just leave it be the way it is for now
