### PR TITLE
Kernel: Simplify the mount syscall before trying to fix the filesystem-mounts hierarchy design

### LINKED ISSUE #11283: Kernel: Filesystem-Mounts hierarchy design is flawed
_I put this mainly as a reminder for myself to work on this, however, if you want to do that as well, feel free to do this!_

Let's consider the following example to demonstrate the problem I'm pointing on:
A user boots up the system which by default mounts a disk device to `/`. This might be represented also as a block device on `/dev`.
The user creates a folder called `/mnt` and wants to mount that device again (`mount /dev/hda /mnt`).
We create an `Ext2FS` object when doing that, which seems like a "new" filesystem to the Kernel.
This scenario leads to quite few problems:
1. Because we know that `Ext2FS` is backed by a DiskCache, as can be seen in `BlockBasedFileSystem` class, this could lead to duplication in what DiskCache we hold at one moment, which could also lead to severe corruptions when the filesystem sync process is running to write cache (flushing) back to disk.
2. The superblock and other components can be in a non-sync situation, which again, can lead to severe corruptions.
3. Flags of mount which are filesystem specific (in linux, for example, discard is a filesystem-specific mount flag) are not applied to all instances which can lead to silent corruptions (imagine what happens if we could send a TRIM command on a device that actually corrupts data because of that bug in its controller, but we can't be sure because we have instances that allow it to happen when we debug it).

Therefore, I think we should change the hierarchy. I'm not sure how it should be built really and I'm working on creating a solution for this problem.
Any suggestions for a solution is always appreciated! :)

### PR DESCRIPTION
**Pull request by supercomputer7**
This is mainly a preparation before I try (again) to fix #11283.
The next PR will try to create a way to fix that issue, hopefully for good.

### CODE REVIEW

File: Kernel/FileSystem/DevPtsFS.cpp [hunk 1]
```diff
@@ -12,9 +12,10 @@
 
 namespace Kernel {
 
-ErrorOr<NonnullRefPtr<DevPtsFS>> DevPtsFS::try_create()
+ErrorOr<NonnullRefPtr<FileSystem>> DevPtsFS::try_create()
 {
-    return adopt_nonnull_ref_or_enomem(new (nothrow) DevPtsFS);
+    auto fs = TRY(adopt_nonnull_ref_or_enomem(new (nothrow) DevPtsFS));
+    return fs;
```
Comment (linusg) [inline Kernel/FileSystem/DevPtsFS.cpp:18]: No need for the temporary variable:

```suggestion
    return TRY(adopt_nonnull_ref_or_enomem(new (nothrow) DevPtsFS));
```

Same everywhere below

File: Kernel/Syscalls/mount.cpp [hunk 2]
```diff
@@ -18,6 +18,54 @@
...
+
+static constexpr FileSystemInitializer s_initializers[] = {
+    { "proc"sv, "ProcFS"sv, false, false, false, {}, ProcFS::try_create },
+    { "devpts"sv, "DevPtsFS"sv, false, false, false, {}, DevPtsFS::try_create },
+    { "dev"sv, "DevTmpFS"sv, false, false, false, {}, DevTmpFS::try_create },
+    { "sys"sv, "SysFS"sv, false, false, false, {}, SysFS::try_create },
+    { "tmp"sv, "TmpFS"sv, false, false, false, {}, TmpFS::try_create },
+    { "ext2"sv, "Ext2FS"sv, true, true, true, Ext2FS::try_create, {} },
+    { "9p"sv, "Plan9FS"sv, true, true, true, Plan9FS::try_create, {} },
+    { "iso9660"sv, "ISO9660FS"sv, true, true, true, ISO9660FS::try_create, {} },
```
Comment (linusg) [inline Kernel/Syscalls/mount.cpp:39]: This is much nicer! :^)
