### PR TITLE
sed: Fix `unveil` error for every run

### LINKED ISSUE #19364: FileSystem::absolute_path triggers unveil error
So we have this unveil pattern in `sed` right now a few times:

`TRY(Core::System::unveil(TRY(FileSystem::absolute_path(filename)), edit_in_place ? "rwc"sv : "r"sv));`

It does work fine, but gives an error like this:

`34.775 [#0 sed(47:47)]: Rejecting path '/home/anon/foo' because it hasn't been unveiled`

The reason for that is, that 

https://github.com/SerenityOS/serenity/blob/b86ca2769222c6191afe6ebb4fb9c4fa781f5fd2/Userland/Libraries/LibFileSystem/FileSystem.cpp#L31-L34

This shortcut in `FileSystem::absolute_path(path)` calls `Core::System::stat(path)` under the hood and therefore tries to access a file that is not unveiled.

### PR DESCRIPTION
**Pull request by fdellwing**
`FileSystem::absolute_path()` does `stat` the file, this commit runs all `absolute_path` calls before touching the veil to make sure this works as intended.

Closes  #19364

### CODE REVIEW

File: Userland/Utilities/sed.cpp [hunk 1]
```diff
@@ -942,27 +942,33 @@ ErrorOr<int> serenity_main(Main::Arguments args)
         pos_args.remove(0);
     }
 
+    HashMap<String, String> paths_to_unveil;
```
Comment (trflynn89) [inline Userland/Utilities/sed.cpp:945]: It's fine as-is since the permission strings are short strings, but this could be:
```c++
HashMap<String, StringView>
```

Comment (fdellwing) [reply Userland/Utilities/sed.cpp:945]: I actually tried that and it did not compile with StringView, no idea why exactly.

Comment (trflynn89) [reply Userland/Utilities/sed.cpp:945]: :shrug: this patch compiles for me:
```c++
diff --git a/Userland/Utilities/sed.cpp b/Userland/Utilities/sed.cpp
index 9a7ac61c51..30ff078370 100644
--- a/Userland/Utilities/sed.cpp
+++ b/Userland/Utilities/sed.cpp
@@ -953,13 +953,13 @@ ErrorOr<int> serenity_main(Main::Arguments args)
         pos_args.remove(0);
     }
 
-    HashMap<String, String> paths_to_unveil;
+    HashMap<String, StringView> paths_to_unveil;
 
     for (auto const& input_filename : TRY(script.input_filenames())) {
-        TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(input_filename)), edit_in_place ? "rwc"_short_string : "r"_short_string));
+        TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(input_filename)), edit_in_place ? "rwc"sv : "r"sv));
     }
     for (auto const& output_filename : TRY(script.output_filenames())) {
-        TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(output_filename)), "w"_short_string));
+        TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(output_filename)), "w"sv));
     }
 
     Vector<File> inputs;
@@ -967,7 +967,7 @@ ErrorOr<int> serenity_main(Main::Arguments args)
         if (filename == "-"sv) {
             inputs.empend(TRY(File::create_from_stdin()));
         } else {
-            TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(filename)), edit_in_place ? "rwc"_short_string : "r"_short_string));
+            TRY(paths_to_unveil.try_set(TRY(FileSystem::absolute_path(filename)), edit_in_place ? "rwc"sv : "r"sv));
             auto file = TRY(Core::File::open(filename, Core::File::OpenMode::Read));
             if (edit_in_place)
                 inputs.empend(TRY(File::create_with_output_file(LexicalPath { filename }, move(file))));
```

Comment (fdellwing) [reply Userland/Utilities/sed.cpp:945]: Strange.
