### PR TITLE
LibWeb: Fix two issues encountered on jscrew.it

### LINKED ISSUE #12658: LibWeb: HTMLParser crash in handle_in_select
The snippet `<select><option></select>` crashes the HTML parser with this stacktrace:
```
ASSERTION FAILED: m_parsing_fragment
../../Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:2535

0x0a92502e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
0x0d198b24: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
0x0d17db59: [libc.so] abort +0x29 (stdlib.cpp:220)
0x0d18468c: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
0x41c75dd5: [libweb.so.serenity] Web::HTML::HTMLParser::handle_in_select(Web::HTML::HTMLToken&) [clone .localalias] +0x805 (HTMLParser.cpp:2535)
0x41c7730b: [libweb.so.serenity] Web::HTML::HTMLParser::run(AK::URL const&) [clone .localalias] +0x58b (HTMLParser.cpp:174)
0x41ce4f6d: [libweb.so.serenity] Web::FrameLoader::load_html(AK::StringView, AK::URL const&) +0xbd (FrameLoader.cpp:230)
0x41d1043d: [libweb.so.serenity] Web::Page::load_html(AK::StringView, AK::URL const&) +0x2d (Page.cpp:46)
0x26ada858: [/bin/WebContent] .L4475 +0x68 (ClientConnection.cpp:97 => WebContentServerEndpoint.h:2523)
0xa4a4a532: [libipc.so.serenity] IPC::ConnectionBase::handle_messages() +0x102 (Connection.cpp:95)
0xa4ae1165: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::Object::deferred_invoke(AK::Function<void ()>)::{lambda()#1}>::call() +0x245 (Function.h:91)
0xa4aca778: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x2a8 (Function.h:91)
0xa4acafaa: [libcore.so.serenity] Core::EventLoop::exec() +0x11a (EventLoop.cpp:428)
0x26add6af: [/bin/WebContent] serenity_main(Main::Arguments) +0x1ef (main.cpp:26)
0x1daff1e7: [libmain.so.serenity] main +0x77 (Main.cpp:23)
0x26ac4c55: [/bin/WebContent] _entry +0x65 (crt0.cpp:49)
```
It seems like this
https://github.com/SerenityOS/serenity/blob/eca8208a345858ef2e132623af08b885a43c7ad4/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp#L3135
 is the only place where `m_parsing_fragment` is set to true. I am not sure why this is the expected state for that [`VERIFY`](https://github.com/SerenityOS/serenity/blob/eca8208a345858ef2e132623af08b885a43c7ad4/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp#L2535) or how this should work exactly.

### PR DESCRIPTION
**Pull request by skyrising**
Fixes #12658

### CODE REVIEW

File: Userland/Libraries/LibWeb/Loader/Resource.cpp [hunk 1]
```diff
@@ -64,6 +65,11 @@ static String mime_type_from_content_type(const String& content_type)
     return content_type;
 }
 
+static bool is_valid_encoding(String const& encoding)
+{
+    return !!TextCodec::decoder_for(encoding);
```
Comment (Hendiadyoin1) [inline Userland/Libraries/LibWeb/Loader/Resource.cpp:70]:
```suggestion
    return TextCodec::decoder_for(encoding);
```

File: Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp [hunk 2]
```diff
@@ -68,9 +68,22 @@ bool StackOfOpenElements::has_in_list_item_scope(const FlyString& tag_name) cons
     return has_in_scope_impl(tag_name, list);
```
Comment (Hendiadyoin1) [inline Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp:68]: On the Commit Title

Don't use "Fix ABC" when doing something more complex,
Explain what you are doing in the commit title, as per the contribution guidelines

File: Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp [hunk 3]
```diff
@@ -68,9 +68,22 @@ bool StackOfOpenElements::has_in_list_item_scope(const FlyString& tag_name) cons
...
+    for (ssize_t i = m_elements.size() - 1; i >= 0; --i) {
+        auto& node = m_elements.at(i);
+        if (node.local_name() == tag_name)
+            return true;
+        if (node.local_name() == HTML::TagNames::option || node.local_name() == HTML::TagNames::optgroup)
+            continue;
+        return false;
+    }
+    VERIFY_NOT_REACHED();
 }
```
Comment (Hendiadyoin1) [inline Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp:87]: Is there a Spec link for this?
(Also I would place a comma after the first line)
