### PR TITLE
Kernel: Fix AC'97 compatibility with multiscreen setup

### LINKED ISSUE #11094: Kernel: Panic in AC97 when booting with SERENITY_SCREENS=2
Steps to reproduce:
1. Boot with `SERENITY_SCREENS=2`
2. Observe that the kernel crashes during boot

```
[colonel(0:0)]: ASSERTION FAILED: is_completion_interrupt
[colonel(0:0)]: ../../Kernel/Devices/Audio/AC97.cpp:71 in virtual bool Kernel::AC97::handle_irq(const Kernel::RegisterState&)
[colonel(0:0)]: KERNEL PANIC! :^(
[colonel(0:0)]: Aborted
[colonel(0:0)]: at ../../Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[colonel(0:0)]: Kernel + 0x0083cafd  Kernel::__panic(char const*, unsigned int, char const*) +0x115
[colonel(0:0)]: Kernel + 0x00a0bacd  abort.localalias +0x244
[colonel(0:0)]: Kernel + 0x00a0b889  abort.localalias +0x0
[colonel(0:0)]: Kernel + 0x0048b9d7  Kernel::AC97::handle_irq(Kernel::RegisterState const&) +0x131
[colonel(0:0)]: Kernel + 0x00711149  Kernel::SharedIRQHandler::handle_interrupt(Kernel::RegisterState const&) [clone .localalias] +0x157
[colonel(0:0)]: Kernel + 0x00a0f896  handle_interrupt +0x602
[colonel(0:0)]: Kernel + 0x00a0a56b  interrupt_common_asm_entry +0x2b
[colonel(0:0)]: Kernel + 0x008992b6  Kernel::Scheduler::idle_loop(void*) +0x116
[colonel(0:0)]: Kernel + 0x00a1131b  exit_kernel_thread +0x0
```

git bisect points to 03329bbfa51f2c0cf24d7374efcdc43eb4979633

### PR DESCRIPTION
**Pull request by GMTA**
Fixes #11094

### CODE REVIEW

File: Kernel/Devices/Audio/AC97.cpp [hunk 1]
```diff
@@ -78,13 +77,16 @@ bool AC97::handle_irq(RegisterState const&)
         | AudioStatusRegisterFlag::FIFOError;
     pcm_out_status_register.out(pcm_out_status);
 
+    // If there is no buffer completion, we're not going to do anything
+    if (!is_completion_interrupt)
+        return true;
```
Comment (supercomputer7) [inline Kernel/Devices/Audio/AC97.cpp:82]: You should actually return `false` here if the AC97 device was not responsible for the IRQ.

Comment (GMTA) [reply Kernel/Devices/Audio/AC97.cpp]: And I should also not reset any interrupt flags in that case as well. Updated, thanks!

**Review by IdanHo — APPROVED** [review]
