### PR TITLE
FileManager+LibGUI: React reasonably when open directories are deleted

### LINKED ISSUE #8204: FileManager: Deleting a directory that is open in FM leaves FM in an invalid state
Steps to reproduce:

1. Copy a directory to the desktop
2. Double-click it to open it in File Manager
3. Select it on the desktop and delete it

The File Manager window stays open, still claiming to be in the deleted directory. If you then click on 'Desktop' on the breadcrumbs bar, and then back on the deleted directory, it crashes. (Stack trace below.)

Correct behavior when the directory is deleted could be to close the window, or to navigate to the nearest-existing parent and refresh the breadcrumbs.

```
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 37) ---
CrashDaemon(20:20): 0xb77941ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashDaemon(20:20): 0x5c2d03e4: [libc.so] raise +0x24 (syscall.h:34 => signal.cpp:20)
CrashDaemon(20:20): 0x5c2b9545: [libc.so] abort +0x29 (stdlib.cpp:230)
CrashDaemon(20:20): 0x5c2ba0aa: [libc.so] __assertion_failed +0xea (assert.cpp:31)
CrashDaemon(20:20): 0x3f63bcfa: [/bin/FileManager] run_in_windowed_mode(AK::RefPtr<Core::ConfigFile, AK::RefPtrTraits<Core::ConfigFile> >, AK::String, AK::String)::{lambda(AK::String const&, bool, bool)#35}::operator()(AK::String const&, bool, bool) const +0xc6a (Function.h:212)
CrashDaemon(20:20): 0x3f63bd74: [/bin/FileManager] AK::Function<void (AK::StringView const&, bool, bool)>::CallableWrapper<run_in_windowed_mode(AK::RefPtr<Core::ConfigFile, AK::RefPtrTraits<Core::ConfigFile> >, AK::String, AK::String)::{lambda(AK::String const&, bool, bool)#35}>::call(AK::StringView const&, bool, bool) +0x54 (Function.h:151)
CrashDaemon(20:20): 0x3f624c54: [/bin/FileManager] AK::Function<void ()>::CallableWrapper<FileManager::DirectoryView::setup_model()::{lambda()#2}>::call() +0x2c4 (Function.h:91)
CrashDaemon(20:20): 0x52f35504: [libgui.so] GUI::FileSystemModel::set_root_path(AK::String) +0x2d4 (Function.h:91)
CrashDaemon(20:20): 0x3f621bc2: [/bin/FileManager] FileManager::DirectoryView::open(AK::String const&) [clone .localalias] +0x202 (DirectoryView.cpp:343)
CrashDaemon(20:20): 0x3f634c64: [/bin/FileManager] AK::Function<void (unsigned long)>::CallableWrapper<run_in_windowed_mode(AK::RefPtr<Core::ConfigFile, AK::RefPtrTraits<Core::ConfigFile> >, AK::String, AK::String)::{lambda(AK::String const&, bool, bool)#35}::operator()(AK::String const&, bool, bool) const::{lambda(unsigned long)#2}>::call(unsigned long) +0x84 (main.cpp:936)
CrashDaemon(20:20): 0x52ee87b1: [libgui.so] AK::Function<void (unsigned int)>::CallableWrapper<GUI::Breadcrumbbar::append_segment(AK::String, Gfx::Bitmap const*, AK::String, AK::String)::{lambda(auto:1)#1}>::call(unsigned int) +0x61 (Function.h:91 => Breadcrumbbar.cpp:87)
CrashDaemon(20:20): 0x52eecee4: [libgui.so] GUI::Button::click(unsigned int) +0x114 (Function.h:91)
CrashDaemon(20:20): 0x52ea9f6c: [libgui.so] GUI::AbstractButton::mouseup_event(GUI::MouseEvent&) +0x9c (AbstractButton.cpp:129)
CrashDaemon(20:20): 0x9d80bf90: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0x52feb833: [libgui.so] GUI::Window::handle_mouse_event(GUI::MouseEvent&) [clone .localalias] +0x383 (Window.cpp:350)
CrashDaemon(20:20): 0x52fed748: [libgui.so] GUI::Window::event(Core::Event&) +0x38 (Window.cpp:549)
CrashDaemon(20:20): 0x9d80bf90: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:213)
CrashDaemon(20:20): 0x9d7f1432: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x572 (EventLoop.cpp:398)
CrashDaemon(20:20): 0x9d7f1c5a: [libcore.so] Core::EventLoop::exec() +0x5a (EventLoop.cpp:362)
CrashDaemon(20:20): 0x52ec48a7: [libgui.so] GUI::Application::exec() +0x27 (Application.cpp:105)
CrashDaemon(20:20): 0x3f643f70: [/bin/FileManager] run_in_windowed_mode(AK::RefPtr<Core::ConfigFile, AK::RefPtrTraits<Core::ConfigFile> >, AK::String, AK::String) +0x5010 (main.cpp:1185)
CrashDaemon(20:20): 0x3f61ea30: [/bin/FileManager] main +0x1980 (main.cpp:131)
CrashDaemon(20:20): 0x3f61eef7: [/bin/FileManager] _start +0x57 (crt0.cpp:37)
```

### PR DESCRIPTION
**Pull request by AtkinsSJ**
This fixes #8204, in two parts:

1. When FileManager has a directory open which has been deleted, it now notices, and navigates up to the nearest existing parent directory, and removes the breadcrumbs for the deleted child.
2. When you click on a breadcrumb segment, it now checks that the target directory exists before navigating to it. If it doesn't exist, we remove it from the breadcrumbbar, along with any of its children.

As noted in commit https://github.com/SerenityOS/serenity/commit/95675808db512c8d3bb63a80b44ed66192b4f799, detecting that a child directory has been deleted, and then automatically removing any breadcrumbs for it, might be better. But this seemed like a reasonable solution for now.

### CODE REVIEW

File: Userland/Libraries/LibGUI/FileSystemModel.cpp [hunk 1]
```diff
@@ -260,10 +260,28 @@ FileSystemModel::FileSystemModel(String root_path, Mode mode)
...
+
+        if (event.type == Core::FileWatcherEvent::Type::Deleted) {
+            auto canonical_event_path = LexicalPath::canonicalized_path(event.event_path);
+            if (m_root_path.starts_with(canonical_event_path)) {
+                // Deleted directory contains our root, so navigate to our nearest parent.
+                auto new_path = LexicalPath(m_root_path).dirname();
+                while (!Core::File::is_directory(new_path))
+                    new_path = LexicalPath(new_path).dirname();
+
+                set_root_path(new_path);
```
Comment (MaxWipfli) [inline Userland/Libraries/LibGUI/FileSystemModel.cpp:278]: Couldn't you just go to the parent directory of `canonical_event_path`, since `canonical_event_path` and all of it's children have been deleted? This would remove the need for the `while` loop.

Comment (AtkinsSJ) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp:278]: @MaxWipfli Possibly. I think my thought was, the parent might also have been deleted too (or that parent's parent, etc) - I'm not familiar with how file watchers work and which directories they notify you about.

Comment (AtkinsSJ) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp:278]: Having now tested this, just using the event path's parent does not work. If it's we're in `a/b/c`, and `b` is deleted, then it navigates to `b` and then fails and navigates to `a` but with a big error message where the directory contents should be displayed.

But testing this out did remind me there was one more thing I wanted to change, so thanks!

**Comment by AtkinsSJ** [comment]
A modification made since opening the PR:
In on_path_change, FileManager now checks if the breadcrumb for the child of the new path is still valid, and removes the breadcrumb if not. This doesn't catch all cases where a breadcrumb's directory is deleted, but it does handle the case where we just navigated up because a directory was deleted, and it makes sense to remove those breadcrumbs then.

**Comment by AtkinsSJ** [comment]
Some of the tests failed but I'm not sure why? They're in libraries I haven't touched, mostly JS related.

File: Userland/Libraries/LibGUI/FileSystemModel.cpp [hunk 2]
```diff
@@ -260,10 +260,28 @@ FileSystemModel::FileSystemModel(String root_path, Mode mode)
...
+            node.reify_if_needed();
+        };
+
+        if (event.type == Core::FileWatcherEvent::Type::Deleted) {
+            auto canonical_event_path = LexicalPath::canonicalized_path(event.event_path);
+            if (m_root_path.starts_with(canonical_event_path)) {
+                // Deleted directory contains our root, so navigate to our nearest parent.
+                auto new_path = LexicalPath(m_root_path).dirname();
+                while (!Core::File::is_directory(new_path))
+                    new_path = LexicalPath(new_path).dirname();
```
Comment (alimpfard) [inline Userland/Libraries/LibGUI/FileSystemModel.cpp:276]: it's pretty sad to reparse this every time, perhaps we could add `LexicalPath::parent()` and use that here?

Comment (AtkinsSJ) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp:276]: Agreed, that makes sense. Right now though, someone else is changing LexicalPath's internals, so I've just added a FIXME for this for now. (Because any changes I make will need to be redone later.)

Comment (alimpfard) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp:277]: That works :P

Comment (AtkinsSJ) [reply Userland/Libraries/LibGUI/FileSystemModel.cpp]: Now using LexicalPath::parent(). :^)

**Review by alimpfard — APPROVED** [review]
