### PR TITLE
WindowServer: Fix inconsistencies when redrawing wallpaper in stretch mode

### LINKED ISSUE #14106: Desktop background artifacts/distortion when opening the context menu
Steps to reproduce:
* Boot SerenityOS
* Change the wallpaper to `sunset-retro.png`
* Change the resolution to anything other than `1024x768`
* Right and left click around the desktop to open and close the desktop context menu repeatedly

What I'm observing as a result is the pixels randomly shifting and distorting around the desktop when opening the context menu, and shifting back into their place when closing the menu. This does not happen with the default resolution.

https://user-images.githubusercontent.com/1154021/170528848-08c0ce20-9e53-4cfa-bb2f-4003c7673de5.mp4

### PR DESCRIPTION
**Pull request by chunngaiau**
Fixes #14106.

Fixes inconsistencies when redrawing subareas of the wallpaper with non-integer scaling.

Adds a backing bitmap where the wallpaper is scaled and painted to first, which is then used directly (blit) when redrawing the wallpaper.

Sacrifices memory usage for aesthetics. To save memory, this is only enabled when using a scaled wallpaper mode.

EDIT: The original fix in this PR is incorrect.

### CODE REVIEW

**Comment by circl-lastname** [comment]
> PS: I'm quite new to contributing here, should I make an issue first and link it?
No need, looks fine to me.

**Comment by chunngaiau** [comment]
Sorry, there are bugs with this PR, it is not ready.

**Comment by chunngaiau** [comment]
Fixes #14106.

**Comment by diath** [comment]
I can confirm that it fixes my issue reported in #14106.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Hi, and thanks for fixing this!

Your commits are a bit confusing - code is added in one, and then immediately removed in the next. Please clean that up. If commits 2 and 3 are just fixes to 1, then combining them together would be clearer.

**Comment by chunngaiau** [comment]
Hi, thanks for reviewing. I have squashed the commits.

File: Userland/Services/WindowServer/Compositor.cpp [hunk 1]
```diff
@@ -303,25 +305,21 @@ void Compositor::compose()
         check_restore_cursor_back(cursor_screen, cursor_rect);
 
     auto paint_wallpaper = [&](Screen& screen, Gfx::Painter& painter, Gfx::IntRect const& rect, Gfx::IntRect const& screen_rect) {
-        // FIXME: If the wallpaper is opaque and covers the whole rect, no need to fill with color!
```
Comment (AtkinsSJ) [inline Userland/Services/WindowServer/Compositor.cpp:306]: This FIXME actually still applies to the `WallpaperMode::Center` branch below. It'd be better to move it there instead of deleting it.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
One tiny nit-pick, otherwise this looks good. :^)

File: Userland/Services/WindowServer/Compositor.cpp (hunk 1 above)
Comment (chunngaiau) [reply Userland/Services/WindowServer/Compositor.cpp:306]: Oh right, I have fixed it.

**Review by davidot — APPROVED** [review]
Code looks good to me, feel free to put `Fixes #14106` in the PR description to auto close that issue when this PR is merged
