### PR TITLE
Utilities+LibArchive: Miscellaneous tar improvements

### LINKED ISSUE #15641: Userland: Tar packing is crashing almost when finishing
How to reproduce:
1. Boot a freshly built image
2. Invoke on the terminal `tar -cf desktop.tar Desktop/`
3. Wait for it to finish
4. Almost at the end of packing you will see a crash

The crash log:
```
75.577 tar(47:47): ASSERTION FAILED: success
./Userland/Libraries/LibArchive/Tar.h:81
75.577 [#0 tar(47:47)]: Terminating tar(47) due to signal 6
75.577 [#0 Finalizer Task(5:5)]: Backtrace:
0x00000000deadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x383
75.577 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 47
75.585 CrashDaemon(26:26): New coredump file: /tmp/coredump/tar_47_1665934995
75.701 CrashReporter(48:48): Started thread "", tid = 49
76.066 CrashReporter(48:49): Generating backtrace took 353 ms
76.066 CrashReporter(48:49): --- Backtrace for thread #0 (TID 47) ---
76.066 CrashReporter(48:49): 0x0000000fd662102b: [/usr/lib/libsystem.so] syscall2 +0xb (syscall.cpp:25 => syscall.cpp:24)
76.066 CrashReporter(48:49): 0x0000000e8cd9fff8: [/usr/lib/libc.so] abort +0x26 (stdlib.cpp:225)
76.066 CrashReporter(48:49): 0x0000000e8cda634e: [/usr/lib/libc.so] __assertion_failed.localalias +0x7e (assert.cpp:33)
76.066 CrashReporter(48:49): 0x000000147ea12403: [/usr/lib/libarchive.so.serenity] Archive::TarOutputStream::add_file(AK::String const&, unsigned short, AK::Span<unsigned char const>) +0x203 (Tar.h:81 => Tar.h:112 => TarStream.cpp:152)
76.070 CrashReporter(48:49): 0x0000000c36a0bd65: [/bin/tar] serenity_main(Main::Arguments)::{lambda(AK::String)#4}::operator()(AK::String) const +0x285 (tar.cpp:239)
76.070 CrashReporter(48:49): 0x0000000c36a0c0df: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x1bf (tar.cpp:261)
76.070 CrashReporter(48:49): 0x0000000c36a0c1b4: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x294 (tar.cpp:263)
76.070 CrashReporter(48:49): 0x0000000c36a0c1b4: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x294 (tar.cpp:263)
76.075 CrashReporter(48:49): 0x0000000c36a0c1b4: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x294 (tar.cpp:263)
76.075 CrashReporter(48:49): 0x0000000c36a0c1b4: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x294 (tar.cpp:263)
76.075 CrashReporter(48:49): 0x0000000c36a0c1b4: [/bin/tar] AK::ErrorOr<void, AK::Error> serenity_main(Main::Arguments)::{lambda(AK::String, auto:1)#5}::operator()<{lambda(AK::String, auto:1)#5}>(AK::String, {lambda(AK::String, auto:1)#5}) const +0x294 (tar.cpp:263)
76.078 CrashReporter(48:49): 0x0000000c36a0d112: [/bin/tar] serenity_main(Main::Arguments) +0xc92 (tar.cpp:272)
76.078 CrashReporter(48:49): 0x0000000c36a0a6d8: [/bin/tar] main +0x128 (Main.cpp:39)
76.078 CrashReporter(48:49): 0x0000000c36a0a878: [/bin/tar] _entry +0x48 (crt0.cpp:48)
```

### PR DESCRIPTION
**Pull request by petelliott**
- Refactor/bugfix of null-terminators in fields
- Support for longer filenames
- Support for creating archives with symlinks

fixes #15641

### CODE REVIEW

File: Userland/Libraries/LibArchive/Tar.cpp [hunk 1]
```diff
@@ -35,4 +35,21 @@ bool TarFileHeader::content_is_like_extended_header() const
...
+    }
+
+    Optional<size_t> slash = filename.find('/');
+    for (slash = filename.find('/');
+         slash.has_value() && filename.length() - slash.value() > sizeof(m_filename);
+         slash = filename.find('/', slash.value() + 1)) { }
+
+    VERIFY(slash.has_value());
+    set_prefix(filename.substring_view(0, slash.value() + 1));
+    set_filename(filename.substring_view(slash.value() + 1));
```
Comment (timschumi) [inline Userland/Libraries/LibArchive/Tar.cpp:53]: Can prefixes really only be split off on slashes? I don't recall seeing or having to rely on that when initially implementing support for prefixes, and if it isn't required it would drastically simplify this function.

**Review by timschumi — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibArchive/Tar.cpp (hunk 1 above)
Comment (petelliott) [reply Userland/Libraries/LibArchive/Tar.cpp:53]: I initially implemented it that way, but then found that our unpacking did require it be split on a slash. I checked and GNU tar will not split filenames. if you give it a 120 character filename in ustar mode it will fail with "filename too long"

Comment (petelliott) [reply Userland/Libraries/LibArchive/Tar.cpp:53]: I found a reference for this: https://pubs.opengroup.org/onlinepubs/7908799/xcu/pax.html

> A new pathname is formed, if prefix is not an empty string (its first character is not NUL), by concatenating prefix (up to the first NUL character), a slash character and name ; otherwise, name is used alone.

note that pax is posix's tar for some reason.

Comment (timschumi) [reply Userland/Libraries/LibArchive/Tar.cpp:53]: Ah, don't mind me then. I also just noticed that what I used back then is a path prepend, not a string prepend.

**Review by timschumi — CHANGES_REQUESTED** [review]
Looks reasonable, I have one last suggestion though. Meanwhile, I'll try to find a chance to test this...

File: Userland/Libraries/LibArchive/Tar.cpp [hunk 2]
```diff
@@ -35,4 +35,21 @@ bool TarFileHeader::content_is_like_extended_header() const
...
+    if (filename.length() <= sizeof(m_filename)) {
+        set_prefix(""sv);
+        set_filename(filename);
+        return;
+    }
+
+    Optional<size_t> slash = filename.find('/');
+    while (slash.has_value() && filename.length() - slash.value() > sizeof(m_filename)) {
+        slash = filename.find('/', slash.value() + 1);
+    }
```
[the remark this answers is not in the document]
Comment (timschumi) [reply Userland/Libraries/LibArchive/Tar.cpp:49]: Also, I guess a `VERIFY(filename.length() < sizeof(m_filename) + sizeof(m_prefix))` before that wouldn't hurt, just to make sure that we have three distinguishable cases of "filename is generally too long to store" (the suggested VERIFY), "basename is too long to store atomically" (no slash found) and "we did something wrong while splitting the string" (one of the VERIFY in set_field).

[the remark this answers is not in the document]
Comment (petelliott) [reply Userland/Libraries/LibArchive/Tar.cpp]: done

File: Userland/Libraries/LibArchive/Tar.h [hunk 3]
```diff
@@ -74,12 +74,10 @@ static StringView get_field_as_string_view(char const (&field)[N])
...
 static void set_field(char (&field)[N], TSource&& source)
 {
-    if constexpr (requires { source.characters_without_null_termination(); }) {
-        memcpy(field, source.characters_without_null_termination(), min(N, source.length()));
-    } else {
-        auto success = source.copy_characters_to_buffer(field, N);
-        VERIFY(success);
-    }
+    VERIFY(N >= source.length());
+    memcpy(field, StringView(source).characters_without_null_termination(), min(N, source.length()));
```
Comment (timschumi) [inline Userland/Libraries/LibArchive/Tar.h:78]: We already verified that `N` is greater to or equal to `source.length()`. This means that `min(N, source.length()) == source.length()`.

File: Userland/Libraries/LibCore/System.cpp [hunk 4]
```diff
@@ -1302,4 +1302,19 @@ ErrorOr<void> access(StringView pathname, int mode)
 #endif
 }
 
+ErrorOr<String> readlink(StringView pathname)
+{
+    // FIXME: Try again with a larger buffer.
+    char data[PATH_MAX];
+#ifdef AK_OS_SERENITY
+    int rc = serenity_readlink(pathname.characters_without_null_termination(), pathname.length(), data, sizeof(data));
```
Comment (timschumi) [inline Userland/Libraries/LibCore/System.cpp:1310]: I feel like the Serenity implementation of `Core::System::readlink` should just be whatever `serenity_readlink` does, i.e. we should move that implementation from LibC to here.

`serenity_readlink` seems to be a remnant of before we started moving the "nicer" alternatives to LibC syscall wrappers into LibCore and making them more "C++-like" in the process. Looking at the only other place where it's used (`Core::File`), it would seemingly also benefit greatly from `ErrorOr<>` error handling and directly passing in a `StringView`.

File: Userland/Utilities/tar.cpp [hunk 5]
```diff
@@ -243,6 +245,20 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
             return {};
         };
 
+        auto add_link = [&](String path) -> ErrorOr<void> {
+            auto statbuf_or_error = Core::System::lstat(path);
+            if (statbuf_or_error.is_error())
+                return statbuf_or_error.error();
+
+            auto statbuf = statbuf_or_error.value();
```
Comment (timschumi) [inline Userland/Utilities/tar.cpp:253]: `TRY()`?

**Review by timschumi — CHANGES_REQUESTED** [review]
Three more things, after that I think we are good to go.

**Review by timschumi — APPROVED** [review]
LGTM!

File: Userland/Libraries/LibArchive/Tar.h [hunk 6]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2020, Peter Elliott <pelliott@serenityos.org>
+ * Copyright (c) 2020, 2022, Peter Elliott <pelliott@serenityos.org>
```
Comment (linusg) [inline Userland/Libraries/LibArchive/Tar.h:2]:
```suggestion
 * Copyright (c) 2020-2022, Peter Elliott <pelliott@serenityos.org>
```

File: Userland/Libraries/LibArchive/Tar.cpp [hunk 7]
```diff
@@ -35,4 +35,21 @@ bool TarFileHeader::content_is_like_extended_header() const
...
+        return;
+    }
+
+    Optional<size_t> slash = filename.find('/', filename.length() - sizeof(m_filename));
+
+    VERIFY(slash.has_value());
+    set_prefix(filename.substring_view(0, slash.value() + 1));
+    set_filename(filename.substring_view(slash.value() + 1));
+}
 }
```
Comment (linusg) [inline Userland/Libraries/LibArchive/Tar.cpp:55]: Please always add a newline before closing namespaces

File: Userland/Libraries/LibCore/System.cpp [hunk 8]
```diff
@@ -1302,4 +1302,24 @@ ErrorOr<void> access(StringView pathname, int mode)
...
+#else
+    String path_string = pathname;
+    int rc = ::readlink(path_string.characters(), data, sizeof(data));
+    if (rc == -1)
+        return Error::from_syscall("readlink"sv, -errno);
+
+    return String(data, rc);
+#endif
+}
 }
```
Comment (linusg) [inline Userland/Libraries/LibCore/System.cpp:1325]: Likewise

File: Userland/Libraries/LibCore/System.h [hunk 9]
```diff
@@ -193,5 +193,5 @@ ErrorOr<int> posix_openpt(int flags);
 ErrorOr<void> grantpt(int fildes);
 ErrorOr<void> unlockpt(int fildes);
 ErrorOr<void> access(StringView pathname, int mode);
-
+ErrorOr<String> readlink(StringView pathname);
 }
```
Comment (linusg) [inline Userland/Libraries/LibCore/System.h:197]: Likewise

**Review by linusg — CHANGES_REQUESTED** [review]
Typo in second commit: its -> it's

File: Userland/Libraries/LibArchive/Tar.cpp (hunk 7 above)
Comment (petelliott) [reply Userland/Libraries/LibArchive/Tar.cpp:55]: that fails our clang-format

**Comment by petelliott** [comment]
> Typo in second commit: its -> it's

fixed

File: Userland/Libraries/LibArchive/Tar.cpp (hunk 7 above)
Comment (linusg) [reply Userland/Libraries/LibArchive/Tar.cpp:55]: It most definitely doesn't, before you made this change there was an empty line.

Comment (petelliott) [reply Userland/Libraries/LibArchive/Tar.cpp:56]: You're right. my clang-format doesn't care. my git-clang-format however, removes the newline.
