### PR TITLE
FileManager: Call on_selection_change with the correct view

### LINKED ISSUE #4185: FileManager: copy/paste broken
copy/paste is always greyed out when you right-click on a file or directory. I'm sure this used to work.

### PR DESCRIPTION
**Pull request by supex0fan**
Fixes #4185

### CODE REVIEW

File: Applications/FileManager/DirectoryView.cpp [hunk 1]
```diff
@@ -482,8 +482,21 @@ void DirectoryView::handle_selection_change()
...
+        case ViewMode::Columns:
+            on_selection_change(*m_columns_view);
+            break;
+        case ViewMode::Icon:
+            on_selection_change(*m_icon_view);
+            break;
+        default:
+            ASSERT_NOT_REACHED();
+        }
+    }
```
Comment (awesomekling) [inline Applications/FileManager/DirectoryView.cpp:499]: You can simplify this by using `current_view()` :)

```cpp
if (on_selection_change)
	on_selection_change(current_view());
```

**Review by awesomekling — CHANGES_REQUESTED** [review]
