### PR TITLE
Browser: Allow the browser to load local file via FileSystemAccessServer

### LINKED ISSUE #5259: Browser: Can't open files outside of /res in multi-process mode
image

To reproduce it, just double click the file that I tried to open in the image above.

### PR DESCRIPTION
**Pull request by LucasChollet**
Few things that justify some design choices :
 - Loading code in ResourceLoader is implemented following the same design as for external request. It is now done in an asynchronous way.
 - FileSystemAccessServer was not able to answer concurrent requests, as there was only one promise slot. I extended it by using a HashMap and unique ids for each request.
 - FSAS was sometimes trying to set a parent to a window with a revoked permission. Making the operation synchronous resolve the issue.

Close #5259

### CODE REVIEW

**Comment by circl-lastname** [comment]
Thank you!

File: Userland/Libraries/LibCore/Stream.cpp [hunk 1]
```diff
@@ -170,6 +170,29 @@ ErrorOr<Bytes> File::read(Bytes buffer)
...
+    ByteBuffer data;
+    data.ensure_capacity(potential_file_size);
+
+    size_t total_read {};
+    while (true) {
+        auto chunk = TRY(data.get_bytes_for_writing(block_size));
+        auto const nread = TRY(read(chunk)).size();
+
+        total_read += nread;
+        if (nread < block_size)
```
Comment (petelliott) [inline Userland/Libraries/LibCore/Stream.cpp:187]: nit: this does not necessarily indicate that the file is at EOF. Only read() == 0 does (or, better yet File::is_eof())

**Comment by Dexesttp** [comment]
Just a note, this kinda reverses the work done in #14018 by adding a link from LibWeb to the LibFileSystemAccessClient library and forcing the use of the filesystemaccess portal directly in libweb.
Not that much of an issue for now, as there is no compilation of libweb on lagom through the CI... yet. But it'll definitely conflict once that part lands.

File: Userland/Services/WebContent/ConnectionFromClient.h [hunk 2]
```diff
@@ -90,6 +94,9 @@ class ConnectionFromClient final
     WeakPtr<JS::Interpreter> m_interpreter;
     OwnPtr<WebContentConsoleClient> m_console_client;
     JS::Handle<JS::GlobalObject> m_console_global_object;
+
+    HashMap<int, NonnullRefPtr<Web::FileRequest>> m_requested_files {};
+    int last_id {};
```
Comment (Dexesttp) [inline Userland/Services/WebContent/ConnectionFromClient.h:99]: Please default-initialize primitive variables
```suggestion
    int last_id { 0 };
```

File: Userland/Libraries/LibFileSystemAccessClient/Client.h [hunk 3]
```diff
@@ -41,10 +42,18 @@ class Client final
...
+    int get_new_id();
+    Result handle_promise(int);
+
+    struct PromiseAndWindow {
+        RefPtr<Core::Promise<Result>> promise {};
+        GUI::Window* parent_window { nullptr };
+    };
+
+    HashMap<int, PromiseAndWindow> m_promises {};
+    int last_id {};
```
Comment (Dexesttp) [inline Userland/Libraries/LibFileSystemAccessClient/Client.h:56]:
```suggestion
    int last_id { 0 };
```

File: Userland/Libraries/LibWeb/Loader/FileRequest.cpp [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+ *
+ * SPDX-License-Identifier: BSD-2-Clause
+ */
+
+#include "FileRequest.h"
+
+namespace Web {
+
+FileRequest::FileRequest(String path)
+    : m_path { move(path) }
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/FileRequest.cpp:12]:
```suggestion
    : m_path(move(path))
```

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h [hunk 5]
```diff
@@ -37,6 +37,9 @@ class LoadRequest {
     void start_timer() { m_load_timer.start(); };
     Time load_time() const { return m_load_timer.elapsed_time(); }
 
+    auto page() const { return m_page; };
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/LoadRequest.h:40]: Not sure about using `auto` for the return type of methods, it's not usually done in Serenity...
```suggestion
    Optional<Page*> page() const { return m_page; }
```

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h [hunk 6]
```diff
@@ -70,6 +73,7 @@ class LoadRequest {
     HashMap<String, String> m_headers;
     ByteBuffer m_body;
     Core::ElapsedTimer m_load_timer;
+    Optional<Page*> m_page;
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/LoadRequest.h:76]: I have no idea if it'd work, but having an `optional nullable pointer` seems counter-productive, would it be possible to do something like `Optional<Page&>`?
```suggestion
    Optional<Page&> m_page;
```
This way, the code is explicit about having either "nothing" or a valid reference.

File: Userland/Libraries/LibWeb/Loader/ResourceLoader.h [hunk 7]
```diff
@@ -7,13 +7,16 @@
 
 #pragma once
 
+#include "FileRequest.h"
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/ResourceLoader.h:10]:
```suggestion
#include <LibWeb/Loader/FileRequest.h>
```

File: Userland/Services/WebContent/ConnectionFromClient.h (hunk 2 above)
Comment (LucasChollet) [reply Userland/Services/WebContent/ConnectionFromClient.h:99]: They are default-initialized, but I can explicitly write it

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h [hunk 8]
```diff
@@ -12,6 +12,9 @@
 #include <AK/URL.h>
 #include <LibCore/ElapsedTimer.h>
 #include <LibWeb/Forward.h>
+#include <LibWeb/Page/Page.h>
+
+#include <utility>
```
Comment (Dexesttp) [inline Userland/Libraries/LibWeb/Loader/LoadRequest.h:17]: This import doesn't seem like it gets used. Also, it makes the CI Clang build completely _explode_.

Comment (LucasChollet) [reply Userland/Libraries/LibWeb/Loader/LoadRequest.h:17]: I don't even know how `<unitility>` have been included, probably CLion/clangd, because I'm sure that I didn't write it.
I should definitely have seen it though

File: Userland/Libraries/LibFileSystemAccessClient/Client.h [hunk 9]
```diff
@@ -41,10 +42,18 @@ class Client final
...
+    int get_new_id();
+    Result handle_promise(int);
+
+    struct PromiseAndWindow {
+        RefPtr<Core::Promise<Result>> promise {};
+        GUI::Window* parent_window { nullptr };
+    };
+
+    HashMap<int, PromiseAndWindow> m_promises {};
+    int last_id { 0 };
```
Comment (linusg) [inline Userland/Libraries/LibFileSystemAccessClient/Client.h:56]: Member variables start with `m_`

File: Userland/Services/WindowServer/WindowServer.ipc [hunk 10]
```diff
@@ -176,9 +176,9 @@ endpoint WindowServer
 
     set_flash_flush(bool enabled) =|
 
-    set_window_parent_from_client(i32 client_id, i32 parent_id, i32 child_id) =|
```
Comment (linusg) [inline Userland/Services/WindowServer/WindowServer.ipc:179]: Commit message nit: `stealing` -> `window stealing`

File: Userland/Applications/Browser/main.cpp [hunk 11]
```diff
@@ -83,6 +83,7 @@ ErrorOr<int> serenity_main(Main::Arguments arguments)
     TRY(Core::System::unveil("/res", "r"));
     TRY(Core::System::unveil("/etc/passwd", "r"));
     TRY(Core::System::unveil("/etc/timezone", "r"));
+    TRY(Core::System::unveil("/tmp/portal/filesystemaccess", "rw"));
```
Comment (linusg) [inline Userland/Applications/Browser/main.cpp:86]: commit message typos:

unveil -> unveils
request -> requests
handle -> handles, send -> sends

File: Userland/Libraries/LibWeb/CMakeLists.txt [hunk 12]
```diff
@@ -275,6 +275,7 @@ set(SOURCES
     Layout/TreeBuilder.cpp
     Loader/ContentFilter.cpp
     Loader/FrameLoader.cpp
+    Loader/FileRequest.cpp
```
Comment (linusg) [inline Userland/Libraries/LibWeb/CMakeLists.txt:278]: Please keep this ordered

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h [hunk 13]
```diff
@@ -37,6 +38,9 @@ class LoadRequest {
     void start_timer() { m_load_timer.start(); };
     Time load_time() const { return m_load_timer.elapsed_time(); }
 
+    Optional<Page&> page() const { return m_page; };
```
Comment (linusg) [inline Userland/Libraries/LibWeb/Loader/LoadRequest.h:41]: `Optional<Page&> const&`?

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h [hunk 14]
```diff
@@ -37,6 +38,9 @@ class LoadRequest {
...
+    void set_page(Page* page) { m_page = *page; }
```
Comment (linusg) [inline Userland/Libraries/LibWeb/Loader/LoadRequest.h:42]: That's silly, just pass a reference directly

File: Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp [hunk 15]
```diff
@@ -219,21 +219,53 @@ void ResourceLoader::load(LoadRequest& request, Function<void(ReadonlyBytes, Has
...
+                if (error_callback)
+                    error_callback(String::formatted("{}", file_or_error.error()), file_or_error.error().code());
+                return;
+            }
+
+            auto const fd = file_or_error.value();
+
+            auto maybe_file = Core::Stream::File::adopt_fd(fd, Core::Stream::OpenMode::Read);
+            if (maybe_file.is_error()) {
+                auto error = maybe_file.error();
```
Comment (linusg) [inline Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp:243]: pointless copy

File: Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp [hunk 16]
```diff
@@ -219,21 +219,53 @@ void ResourceLoader::load(LoadRequest& request, Function<void(ReadonlyBytes, Has
...
+                log_failure(request, error);
+                if (error_callback)
+                    error_callback(String::formatted("{}", error), error.code());
+                return;
+            }
+
+            auto file = maybe_file.release_value();
+            auto maybe_data = file->read_all();
+            if (maybe_data.is_error()) {
+                auto error = maybe_data.error();
```
Comment (linusg) [inline Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp:253]: pointless copy

File: Userland/Libraries/LibWebView/OutOfProcessWebView.cpp [hunk 17]
```diff
@@ -400,6 +401,15 @@ void OutOfProcessWebView::notify_server_did_update_resource_count(i32 count_wait
         on_resource_status_change(count_waiting);
 }
 
+void OutOfProcessWebView::notify_server_did_request_file(Badge<WebContentClient>, AK::String const& path, i32 request_id)
```
Comment (linusg) [inline Userland/Libraries/LibWebView/OutOfProcessWebView.cpp:404]: Please drop the AK prefix

**Review by linusg — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibWeb/Loader/LoadRequest.h (hunk 13 above)
Comment (LucasChollet) [reply Userland/Libraries/LibWeb/Loader/LoadRequest.h:41]: It can't be a `const&`, the `value()` method of a `const optionnal` return a constant `Page` and a mutable one is required down the road

**Comment by linusg** [comment]
LGTM! Thanks for working on this :tada:

One last thing I'd like to understand before merging: why does `WindowServer: Make window stealing related functions synchronous` not require a code change? AFAICT functions like `async_remove_window_stealing_for_client` should no longer be generated with the async prefix, but even a fresh build keeps the `GUI::ConnectionToWindowServer::the().async_remove_window_stealing_for_client(child_window_server_client_id, parent_window_id);` calls compiling...

**Comment by MacDue** [comment]
@linusg, it seems like `synchronous` functions still generate the `async_` methods, and it looks to me (at a glance) that they still send the message asynchronously. I just checked this by looking at the generated code for a random synchronous function.

**Comment by LucasChollet** [comment]
Honestly, I don't know much about LibIPC. Even if I was surprised that it keeps the `async_` prefix, as it works it was good enough for me.

@MacDue I can't check for now but I'm pretty sure that it does change something, as reverting the commit make the browser crash.

**Comment by linusg** [comment]
@MacDue I don't believe you :stuck_out_tongue: 

> I just checked this by looking at the generated code for a random synchronous function.

Likewise checking with a random sync function here - no `async_`:

```console
$ git grep update_notification_icon
Userland/Libraries/LibGUI/Notification.cpp:        m_connection->update_notification_icon(m_icon ? m_icon->to_shareable_bitmap() : Gfx::ShareableBitmap());
Userland/Services/NotificationServer/ConnectionFromClient.cpp:Messages::NotificationServer::UpdateNotificationIconResponse ConnectionFromClient::update_notification_icon(Gfx::ShareableBitmap const& icon)
Userland/Services/NotificationServer/ConnectionFromClient.h:    virtual Messages::NotificationServer::UpdateNotificationIconResponse update_notification_icon(Gfx::ShareableBitmap const&) override;
Userland/Services/NotificationServer/NotificationServer.ipc:    update_notification_icon(Gfx::ShareableBitmap icon) => (bool still_showing)
```

**Comment by MacDue** [comment]
@linusg 
```
    seal_allowlist() => ()  // LaunchServer.ipc
```
Is sync (I think).

Shift click a bit:
```c++
class LaunchServerProxy {
...

    void async_seal_allowlist(
) {
        // FIXME: Handle post_message failures.
        (void) m_connection.post_message(Messages::LaunchServer::SealAllowlist {  });

    }

...
}
```

 ¯\\\_(ツ)_/¯

**Comment by linusg** [comment]
yeah, my point is: now do it with `update_notification_icon`. Doesn't seem consistent.

**Comment by linusg** [comment]
Anyway...
