### PR TITLE
LibJS: Don't change offset when reconfiguring property in unique shape

### LINKED ISSUE #3735: LibJS: Vector OOB in put_own_property when redefining a property with defineProperty
Code:
```js
var a;
Object.defineProperty(globalThis, "a", {});
```

Trace:
```
USERSPACE(24) ASSERTION FAILED: i < m_size
.././AK/Vector.h:200
[js(24:24)]: Terminating js(24) due to signal 6
[FinalizerTask(3:3)]: CPU[0] NP(error) fault at invalid address V0x01601d5c
[FinalizerTask(3:3)]: copy_from_user(0xc094a9ac, 0x01601d5c, 4) failed at V0x01601d5c
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +181
0xdeadc0de  Kernel::Scheduler::pick_next() +1952
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x080c1d82  raise +22
0x080480bd  abort +13
0x080bdba5  tolower +0
0x080853f5  JS::Object::put_own_property(JS::Object&, JS::StringOrSymbol const&, JS::Value, JS::PropertyAttributes, JS::Object::PutOwnPropertyMode, bool) +417
0x080857fa  JS::Object::define_property(JS::PropertyName const&, JS::Value, JS::PropertyAttributes, bool) +174
0x08086097  JS::Object::define_property(JS::StringOrSymbol const&, JS::Object const&, bool) +1809
0x08082fef  JS::ObjectConstructor::define_property_(JS::VM&, JS::GlobalObject&) +705
0x0804bd26  AK::Function<JS::Value (JS::VM&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::VM&, JS::GlobalObject&)>::call(JS::VM&, JS::GlobalObject&) const +22
0x080a8089  JS::NativeFunction::call() +59
0x08095bb2  JS::VM::call_internal(JS::Function&, JS::Value, AK::Optional<JS::MarkedValueList>) +492
0x0805dc44  JS::CallExpression::execute(JS::Interpreter&, JS::GlobalObject&) const +2382
0x0805a2fa  JS::ExpressionStatement::execute(JS::Interpreter&, JS::GlobalObject&) const +44
0x0806751a  JS::Interpreter::execute_statement(JS::GlobalObject&, JS::Statement const&, AK::Vector<JS::Argument, 8ul>, JS::ScopeType) +452
0x0805c91c  JS::Program::execute(JS::Interpreter&, JS::GlobalObject&) const +64
0x080677aa  JS::Interpreter::run(JS::GlobalObject&, JS::Program const&) +342
0x0804b3b8  parse_and_run(JS::Interpreter&, AK::StringView const&) +713
0x08048af3  main +1636
0x080499be  _start +94
```

### PR DESCRIPTION
**Pull request by linusg**
When changing the attributes of an existing property of an object with unique shape we must not change the `PropertyMetadata` offset. Doing so without resizing the underlying storage vector caused an OOB write crash.

Fixes #3735.

### CODE REVIEW

File: Libraries/LibJS/Runtime/Shape.cpp [hunk 1]
```diff
@@ -196,7 +196,8 @@ void Shape::reconfigure_property_in_unique_shape(const StringOrSymbol& property_
     ASSERT(is_unique());
     ASSERT(m_property_table);
     ASSERT(m_property_table->contains(property_name));
-    m_property_table->set(property_name, { m_property_table->size(), attributes });
+    auto metadata = m_property_table->get(property_name).value();
+    m_property_table->set(property_name, { metadata.offset, attributes });
```
Comment (awesomekling) [inline Libraries/LibJS/Runtime/Shape.cpp:200]: This is two separate hash lookups, let's avoid one :)
```cpp
auto it = m_property_table->find(property_name);
ASSERT(it != m_property_table->end());
it->value = { metadata.offset, attributes };
```

(And with this assertion added, we can drop the `contains()` assertion above)
