### PR TITLE
Kernel: Make msync return EINVAL when regions are too large

### LINKED ISSUE #11297: Kernel: sys$msync fuzzer crash with large enough size parameter.
Happened across this today while playing with `fuzz-syscalls`:
```
217.439 fuzz-syscalls(75:75): #164: Calling msync(0x00000000, 0xffffffff, 0x00000001) with 0x3bd24000 containing [0xbffff000, 0x3bd24000, 0x3bd24000, 0x00000000, 0xc0000000, 0x3bd24000, 0x3bd24000, 0x0000000d, 0x7c7928c1, 0xc0000000]
[fuzz-syscalls(75:75)]: ASSERTION FAILED: x == 0 || rounded != 0
[fuzz-syscalls(75:75)]: ././Kernel/Memory/MemoryManager.h:36 in constexpr FlatPtr Kernel::Memory::page_round_up(FlatPtr)
[fuzz-syscalls(75:75)]: KERNEL PANIC! :^(
[fuzz-syscalls(75:75)]: Aborted
[fuzz-syscalls(75:75)]: at ./Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[fuzz-syscalls(75:75)]: Kernel + 0x00c08a81  Kernel::__panic(char const*, unsigned int, char const*) +0xf1
[fuzz-syscalls(75:75)]: Kernel + 0x00fa5ab9  abort.localalias +0x245
[fuzz-syscalls(75:75)]: Kernel + 0x00fa5874  abort.localalias +0x0
[fuzz-syscalls(75:75)]: Kernel + 0x00d81a0c  Kernel::Process::sys$msync(AK::Userspace<void*>, unsigned long, int) +0x46c
[fuzz-syscalls(75:75)]: Kernel + 0x00cd0831  syscall_handler +0x1f31
[fuzz-syscalls(75:75)]: Kernel + 0x00cce8f1  syscall_asm_entry +0x31
```

So we end up calling `msync(0x00000000, 0xffffffff, 0x00000001)`, and we correctly detect that `page_round_up()` on the size would overflow. However we should return an error, not crash the Kernel, :smile:. 

Looks like we need to add a way so this function can propagate error instead of asserting: 
```cpp
constexpr FlatPtr page_round_up(FlatPtr x)
{
    FlatPtr rounded = (((FlatPtr)(x)) + PAGE_SIZE - 1) & (~(PAGE_SIZE - 1));
    // Rounding up >0xfffff000 wraps back to 0. That's never what we want.
    VERIFY(x == 0 || rounded != 0);
    return rounded;
}
```

### PR DESCRIPTION
**Pull request by eggpi**
As a small cleanup, this also makes `page_round_up` verify its precondition with `page_round_up_would_wrap` (which callers are expected to call), rather than having its own logic.

Fixes #11297.

### CODE REVIEW

File: Kernel/Syscalls/mmap.cpp [hunk 1]
```diff
@@ -587,6 +587,10 @@ ErrorOr<FlatPtr> Process::sys$msync(Userspace<void*> address, size_t size, int f
     if (address.ptr() % PAGE_SIZE != 0)
         return EINVAL;
 
+    if (Memory::page_round_up_would_wrap(size)) {
+        return EINVAL;
```
Comment (bgianfo) [inline Kernel/Syscalls/mmap.cpp:591]: Maybe we should tell them the error is overflow specifically? 
```suggestion
        return EOVERFLOW;
```

Comment (eggpi) [reply Kernel/Syscalls/mmap.cpp:591]: Hmm, I like the idea of being specific, but this would make `msync` inconsistent with `mmap`, which returns `EINVAL` at the moment in this situation (unless we change that too). For what it's worth, using this test snippet:

```cpp
#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/errno.h>

int main(void) {
    if (msync(0x00000000, 0xffffffff, 0x00000001) == -1) {
        perror("msync failed");
    }
    return 0;
}
```

I get `ENOMEM` on MacOS (I guess either `EINVAL` or `ENOMEM` would make sense according to the [manpage](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/msync.2.html)). So that leaves us with three options: `EINVAL`, `ENOMEM` or `EOVERFLOW` :)

I think I'd lean towards just `EINVAL`, but happy to apply your suggestion too. What do you think?

Comment (bgianfo) [reply Kernel/Syscalls/mmap.cpp:591]: Ok, not important enough to debate 😁
