### PR TITLE
Shell: Use /tmp for all file operations valid.sh test

### LINKED ISSUE #7336: Shell: valid.sh intermittently fails
intermittent

This shows up in CI sometimes too. The test also fails and blocks execution if run as root from `/` So I suspect some filesystem shenanigains are getting this test into an invalid state.

Perhaps it should create files in /tmp ?

### PR DESCRIPTION
**Pull request by ADKaster**
Not doing so sometimes intermittently caused the '*' glob expansion test
to fail and lock up the shell.

Fixes #7336

### CODE REVIEW

File: Userland/Shell/Tests/valid.sh [hunk 1]
```diff
@@ -78,7 +78,7 @@ pushd sh-test
     if not test "$(echo x(a*))" = "xad xae xaf"  { fail globs in lists do not resolve to lists }
     if not test "$(echo "foo"a*)" = "fooad fooae fooaf"  { fail globs join to dquoted strings }
 popd
-rm -fr sh-test
+rm -fr /tmp/sh-test
```
Comment (alimpfard) [inline Userland/Shell/Tests/valid.sh:81]: Reminds me that the shell doesn't have the equivalent of `atexit`/`trap`...#7339.

**Review by alimpfard — APPROVED** [review]
Thanks!
