### PR TITLE
AK+LibJS: Implement Date.UTC according to the spec

### LINKED ISSUE #4651: LibJS: Date.UTC and Date.prototype.toISOString fail on MacOS
With the StackInfo patch from #4650 applied, test-js can now run to completion on MacOS hosts.

The following two tests fail in CI there:

```
2020-12-30T09:54:44.3666510Z FAIL Builtins/Date/Date.UTC.js
2020-12-30T09:54:44.3668170Z     ❌ Suite: <top-level>
2020-12-30T09:54:44.3669830Z          Test:   basic functionality (failed):
2020-12-30T09:54:44.3670980Z                  ExpectationError: toBe: expected _-5396198400000_, got _-1000_
2020-12-30T09:54:44.3672620Z  FAIL builtins/Date/Date.prototype.toISOString.js
2020-12-30T09:54:44.3673820Z     ❌ Suite:  <top-level>
2020-12-30T09:54:44.3674880Z          Test:   basic functionality (failed):
2020-12-30T09:54:44.3676440Z                  ExpectationError: toBe: expected _1800-01-01T00:00:00.000Z_, got _1969-12-31T23:59:59.000Z_
```

Side note: Would be neat to check for like, the `$CI` environment variable or some such and disable terminal color codes in the pretty printing for the out() stuff. Downloading the 1.9M lines of logs that test-js produces is awkward enough without having to filter out terminal escapes in the logs. :p. `isatty` to the rescue?

Probably gonna need a JS-savvy Mac user to fix this one. until then, can keep ignoring test failures in Mac CI.

The problem appears with dates around 1800. The first is January 1799, which gets mangled to -1000. The second is January 1800, which ends up as -1.

### PR DESCRIPTION
**Pull request by trflynn89**
This fixes all failing Date.UTC test262 tests, which failed due to not
handling invalid input and evaluating inputs out of order. But this also
avoids using `timegm`, which doesn't work on macOS for years before 1900
(they simply return -1 for those years).

Partially addresses #4651. `Date.parse.js` still fails.

### CODE REVIEW

**Comment by trflynn89** [comment]
Making a draft because this didn't actually fix macOS - we now hit the same issue with `mktime` instead of `timegm`.

**Review by linusg — APPROVED** [review]

File: Userland/Libraries/LibJS/Runtime/DateConstructor.cpp [hunk 1]
```diff
@@ -156,7 +156,7 @@ void DateConstructor::initialize(GlobalObject& global_object)
     u8 attr = Attribute::Writable | Attribute::Configurable;
     define_native_function(vm.names.now, now, 0, attr);
     define_native_function(vm.names.parse, parse, 1, attr);
-    define_native_function(vm.names.UTC, utc, 1, attr);
+    define_native_function(vm.names.UTC, utc, 7, attr);
```
Comment (Lubrsi) [inline Userland/Libraries/LibJS/Runtime/DateConstructor.cpp:159]: Can we add a test for this? For example:
```js
    test("length is 7", () => {
        expect(Date.UTC).toHaveLength(7);
    });
```

Comment (trflynn89) [reply Userland/Libraries/LibJS/Runtime/DateConstructor.cpp:159]: Sure, done
