### PR TITLE
LibC: Make asctime_r() in time.cpp POSIX compliant

### LINKED ISSUE #13682: LibC: Assertion failed in `asctime` for large inputs
The program
```cpp
#include <stdio.h>
#include <time.h>

int main()
{
    time_t t = 9251125413094057;
    struct tm* tm = localtime(&t);

    printf("%s", asctime(tm));
}
```
crashes with
```
ASSERTION FAILED: filled_size != 0
./Userland/Libraries/LibC/time.cpp:212

0x7da3502e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
0x520a7054: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
0x5208dc29: [libc.so] abort +0x29 (stdlib.cpp:223)
0x5209384c: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
0x520c672e: [libc.so] asctime +0x4e (time.cpp:212 => time.cpp:202)
0x9fb5a159: [/bin/asctime-crash] main +0x49 (asctime-crash.cpp:9)
0x9fb5a205: [/bin/asctime-crash] _entry +0x65 (crt0.cpp:49)
```
The expected output should be something similar to `Sat Feb  9 16:47:37 293158464`, depending on the value of TZ.

Such large inputs appear in some ports that use autotools to test if `mktime` works correctly, as discussed in #12729.

### PR DESCRIPTION
**Pull request by MejeC10**
Previously, we passed an expected length of 26 to strftime().
This caused the program to crash if the year was too large.
To fix this, the length has now been set to 68, which still fits inside the buffer.
Time.h could also be improved by resizing the asctime() buffer to not waste space.

### CODE REVIEW

**Review by timschumi — CHANGES_REQUESTED** [review]
Not a great commit/PR title, it doesn't explain what is done. Also, the comment above the changed line should probably explain why this is larger than the minimum required value.

**Comment by MejeC10** [comment]
Is there a way to change the PR title to be more explanatory? I'll add a comment to the file when I have the ability.

**Comment by timschumi** [comment]
There should be an edit button right next to the PR title.

File: Userland/Libraries/LibC/time.cpp [hunk 1]
```diff
@@ -205,7 +205,11 @@ char* asctime(const struct tm* tm)
 char* asctime_r(const struct tm* tm, char* buffer)
 {
     // Spec states buffer must be at least 26 bytes.
-    constexpr size_t assumed_len = 26;
+    // However, setting the length to 26 will crash for some tms because the year will be too big to fit.
+    // Additionally, asctime() already allocates for us 69 bytes, so there's no reason to not use them.
+    // Only 68 bytes are used to leave room for the null-terminator.
+
```
Comment (timschumi) [inline Userland/Libraries/LibC/time.cpp:211]: Extraneous newline.

**Review by timschumi — CHANGES_REQUESTED** [review]
Even though it's a horrible API, `asctime_r` is useable by other programs as well, not just by `asctime`. The solution to this problem is not to assume things that are beyond the spec.

The spec says that `asctime_r` formats values in a fixed 25 character format. Additionally, it states that behavior is undefined if the year is longer than four digits (which seems to be the issue that you are talking about).

The only issue that we should be fixing here is that `strftime` crashes when writing a format that is beyond the maximum length(?). The maximum length itself should not be touched, as it is correct (25 characters + null byte).

File: Userland/Libraries/LibC/time.cpp (hunk 1 above)
Comment (MejeC10) [reply Userland/Libraries/LibC/time.cpp:211]: In that case, what should asctime_r() do when strftime() tells it that the string didn't fit? Because we can't disobey the spec, asctime() has to return a char pointer, so the only other way to send the message that the method failed would be to return a null pointer, which would also crash. Should asctime_r() just return an incomplete string? These seem like spec issues, and I don't think I can make those decisions. I know that other time.h implementations that I've used don't crash, and return a string larger than 25 characters.

**Comment by timschumi** [comment]
The POSIX manpage says that `asctime_r` can and should return `NULL` on error, with `errno = EOVERFLOW` if the result cannot be represented.

**Comment by MejeC10** [comment]
When I have access to a computer again I'll make those error checks. Issue #13682 should be closed because asctime() shouldn't return a working string in this case.

**Comment by MejeC10** [comment]
I know the current PR fails linting but I can't figure out what the linter wants me to fix so if anyone could help me understand it would be much appreciated.

**Comment by ADKaster** [comment]
@MejeC10  It looks like you've inserted an actual tab character into the code files. Configure your editor to use 4 spaces and clang-format-14 should be happy with it. I'd recommend also installing the pre-commit hooks as described here to force the linters to run on each commit https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks

File: Userland/Libraries/LibC/time.cpp [hunk 2]
```diff
@@ -208,8 +208,11 @@ char* asctime_r(const struct tm* tm, char* buffer)
     constexpr size_t assumed_len = 26;
     size_t filled_size = strftime(buffer, assumed_len, "%a %b %e %T %Y\n", tm);
 
-    // Verify that the buffer was large enough.
-    VERIFY(filled_size != 0);
+    // If the buffer was not large enough, set EOVERFLOW and return null
```
Comment (timschumi) [inline Userland/Libraries/LibC/time.cpp:211]:
```suggestion
    // If the buffer was not large enough, set EOVERFLOW and return null.
```

**Review by timschumi — CHANGES_REQUESTED** [review]
Please also edit the PR title to match the commit title. After that, this should be ready for merging.

File: Userland/Libraries/LibC/time.cpp (hunk 2 above)
Comment (MejeC10) [reply Userland/Libraries/LibC/time.cpp:211]: How do I commit your addition without making a new commit? Is there a way to run git commit --amend with your change, or should I make the change and commit it myself?

**Review by timschumi — APPROVED** [review]
Looks good to me! The test case mentioned in the issue no longer crashes, and the build failure is ephemeral.

**Comment by MejeC10** [comment]
How do I find someone to merge the changes in? I've already used /pull in the Code Review channel, but should I do it again?

**Comment by timschumi** [comment]
First of all, make sure that it looks ready to merge. This usually means that you should mark all comments that have been resolved as resolved. The fact that the CI is failing right now is unfortunate, but that's just how it is.

If there is no attention by anyone in a few days, you can probably advertise it in the Discord channel again. :^)

**Review by linusg — CHANGES_REQUESTED** [review]
Please wrap the commit message at 72 characters as per the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy).

**Comment by MejeC10** [comment]
I don't see which message is longer than 72 characters. Also, doesn't the commit linter in CI catch commit messages with lines longer than 72?

**Comment by linusg** [comment]
I never said it's longer than 72 characters, and yes, CI would catch that.

```
Previously, when the asctime_r() buffer overflowed,
we would fail an assertion.
```

is not wrapped at 72 characters.

**Comment by timschumi** [comment]
I'm going to assume that the issue is that the first line wraps way too early, way before 72 characters are reached. The way wrapping usually works is "continue on the same line until you can't fit the next word, at which point you make a newline".

**Comment by linusg** [comment]
```
Previously, when the asctime_r() buffer overflowed, we would fail an
assertion.
This patch modifies asctime_r() to instead set errno and return null.
```
