### PR TITLE
Meta: Fix build on some unammed distros that doesn't append `/usr/sbin` in their path

### LINKED ISSUE #16176: Meta: serenity.sh run cannot build image since 45e22dafb3
Since 45e22dafb3 I cannot run SerenityOS; if I hard reset to its previous commit (5556b27e38), it works as expected.

image

### PR DESCRIPTION
**Pull request by LucasChollet**
This patch adds the `find_executable()` function that will hopefully find executables in a distro-agnostic way and that is (hopefully as well) easily upgradable.

Fixes  #16176 
Note: I don't understand how 45e22dafb3d487341809a54ae63bf005300b5bea works, as the failure of `command` will cause the script to exit due to `set -e`.

### CODE REVIEW

**Review by timschumi — CHANGES_REQUESTED** [review]
This could probably be added to `.shell_include.sh` as well (maybe even together with the parts that define the actual `*_PATH` variables), I bet that other scripts could use those as well.

**Comment by timschumi** [comment]
Also, it indeed looks like 45e22dafb3d487341809a54ae63bf005300b5bea was broken, at least assuming that `$(...)` is affected by `set -e`, there is nothing special there to prevent that.

File: Meta/build-image-qemu.sh [hunk 1]
```diff
@@ -1,18 +1,33 @@
 #!/bin/sh
+set -e
 
-# Note: This is done before `set -e` to let `command` fail if needed
-FUSE2FS_PATH=$(command -v fuse2fs)
-RESIZE2FS_PATH=$(command -v resize2fs)
+find_executable() {
+  paths="/usr/sbin/ /sbin/"
```
[the remark this answers is not in the document]
Comment (LucasChollet) [reply Meta/build-image-qemu.sh:5]: `${paths[@]}` isn't POSIX (at least it doesn't work with `dash`)

File: Meta/build-image-qemu.sh [hunk 2]
```diff
@@ -1,18 +1,33 @@
...
+  echo "$executable"
+}
+
+FUSE2FS_PATH=$(find_executable fuse2fs)
+RESIZE2FS_PATH=$(find_executable resize2fs)
+E2FSCK=$(find_executable e2fsck)
+
+echo "$FUSE2FS_PATH"
+echo "$RESIZE2FS_PATH"
+echo "$E2FSCK_PATH"
```
[the remark this answers is not in the document]
Comment (LucasChollet) [reply Meta/build-image-qemu.sh:30]: Yep, mb

File: Meta/build-image-qemu.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (timschumi) [reply Meta/build-image-qemu.sh:5]: We already require `bash` (and bash-specific behavior) in quite a few other scripts already, so if that's an issue we should just switch the shebang to `#!/usr/bin/env bash`.

File: Meta/build-image-qemu.sh [hunk 3]
```diff
@@ -1,18 +1,33 @@
...
+find_executable() {
+  paths="/usr/sbin/ /sbin/"
+  executable="$1"
 
-if [ -z "$FUSE2FS_PATH" ]; then
-    FUSE2FS_PATH=/usr/sbin/fuse2fs
-fi
+  # Note: If, by chance, the executable is in $PATH, use it
+  if command -v "$executable"; then
+    return 0
```
[the remark this answers is not in the document]
Comment (LucasChollet) [reply Meta/build-image-qemu.sh:10]: :works_on_my_machine:
If I understand correctly:
`command` write to the standard output, which is later captured by `$(...)`

File: Meta/build-image-qemu.sh [hunk 4]
```diff
@@ -1,18 +1,33 @@
...
-FUSE2FS_PATH=$(command -v fuse2fs)
-RESIZE2FS_PATH=$(command -v resize2fs)
+find_executable() {
+  paths="/usr/sbin/ /sbin/"
+  executable="$1"
 
-if [ -z "$FUSE2FS_PATH" ]; then
-    FUSE2FS_PATH=/usr/sbin/fuse2fs
-fi
+  # Note: If, by chance, the executable is in $PATH, use it
```
[the remark this answers is not in the document]
Comment (LucasChollet) [reply Meta/build-image-qemu.sh:8]: I left the last comment, because I don't think the reason is obvious

File: Meta/build-image-qemu.sh [hunk 5]
```diff
@@ -1,17 +1,4 @@
...
-
-if [ -z "$FUSE2FS_PATH" ]; then
-    FUSE2FS_PATH=/usr/sbin/fuse2fs
-fi
-
-if [ -z "$RESIZE2FS_PATH" ]; then
-    RESIZE2FS_PATH=/usr/sbin/resize2fs
-fi
-
+#!/usr/bin/env bash
```
Comment (timschumi) [inline Meta/build-image-qemu.sh:1]: This change would also be required for the remaining `build-image-*.sh` scripts and `build-native-partition.sh`, all of those also include `.shell_include.sh`.

File: Meta/.shell_include.sh [hunk 6]
```diff
@@ -13,3 +13,26 @@ die() {
...
+  paths=("/usr/sbin/" "/sbin/")
+  executable="$1"
+
+  # Prefer tools from PATH over fallback paths
+  if command -v "$executable"; then
+    return 0
+  fi
+
+  for path in "${paths[@]}"; do
+    if command -v "$path$executable"; then
```
Comment (timschumi) [inline Meta/.shell_include.sh:27]: Ultimate nitpick, but I'd prefer omitting the trailing slashes from the paths array and using `$path/$executable` instead.

Also, while we're at it, adding curly braces around variable names (i.e. `${path}/${executable}`) would be great for readability. The same probably applies for usages of `${executable}` alone as well.

File: Meta/build-image-qemu.sh [hunk 7]
```diff
@@ -50,15 +37,6 @@ if [ "$(uname -s)" = "Darwin" ]; then
 
     E2FSCK="e2fsck"
     RESIZE2FS_PATH="resize2fs"
```
Comment (timschumi) [inline Meta/build-image-qemu.sh:39]: Can't select the whole block here because it's outside the diff, but would it make sense to move the e2fsck and resize2fs detection logic for Darwin to `.shell_include.sh` as well?

**Review by timschumi — CHANGES_REQUESTED** [review]

File: Meta/build-image-qemu.sh (hunk 7 above)
Comment (LucasChollet) [reply Meta/build-image-qemu.sh:39]: I didn't want to touch the Darwin stuff as I can't test it, but I guess that we can trust the CI.

File: Meta/.shell_include.sh [hunk 8]
```diff
@@ -13,3 +13,32 @@ die() {
...
     exit 1
 }
+
+find_executable() {
+  paths=("/usr/sbin" "/sbin")
+
+  if [ "$(uname -s)" = "Darwin" ]; then
+    paths+=("/usr/local/opt/e2fsprogs/bin" "/usr/local/opt/e2fsprogs/sbin")
+    paths+=("/opt/homebrew/opt/e2fsprogs/bin" "/opt/homebrew/opt/e2fsprogs/sbin")
+  fi
```
Comment (timschumi) [inline Meta/.shell_include.sh:23]: Eh, I would have copied the block to the bottom of the file as-is, but I guess this works as well.

Comment (LucasChollet) [reply Meta/.shell_include.sh:23]: I hope so :eyes:

Comment (timschumi) [reply Meta/.shell_include.sh:23]: The block of code that this is supposed to replace is still there though. :^)

**Review by timschumi — APPROVED** [review]
Looks reasonable to me, let's see if CI passes. :^)
