### PR TITLE
Solitaire: Various bug fixes

### LINKED ISSUE #7792: LibCards+Solitaire: Card corner transparency shows background in game over animation
Not really sure how to fix this. I guess that the problem is that we only draw _one card_ and then returns each `paint_event` when the game over animation is active. 

https://github.com/SerenityOS/serenity/blob/4061d0871676d7cc67c6c936e374083c832b8835/Userland/Games/Solitaire/Game.cpp#L502-L505

### PR DESCRIPTION
**Pull request by AtkinsSJ**
This fixes #7792, and several other bugs that don't have issues logged. Feedback welcome! For one thing, I'm not certain that `set_background_fill_enabled()` is the right solution, or the right name.

Hopefully I can stop obsessing over Solitaire now. :^)

EDIT: Sorry about the initial check fails. This whole time I've been using `clang-format` without the `-i` parameter. 🤦‍♂️

### CODE REVIEW

File: Userland/Games/Solitaire/Game.cpp [hunk 1]
```diff
@@ -410,7 +420,7 @@ void Game::draw_cards()
         else
             update(play_bounding_box);
     }
-
```
Comment (linusg) [inline Userland/Games/Solitaire/Game.cpp]: This whitespace change is incorrectly added in the third commit and then fixed in the fourth - please don't make it in the first place to keep the diffs clean.

**Review by linusg — CHANGES_REQUESTED** [review]

File: Userland/Games/Solitaire/Game.cpp (hunk 1 above)
Comment (AtkinsSJ) [reply Userland/Games/Solitaire/Game.cpp]: Sorry! I only noticed the whitespace when the CI checks failed, and then I fixed it in a rush, and shoved it into the last commit without thinking. I've fixed that now.
