### PR TITLE
LibCore: Automatically create config directories if necessary

### LINKED ISSUE #13555: ConfigServer: Crashes after pledging when `.config` is removed
Steps to reproduce:
1. delete `.config` directory
2. open an application that uses `LibConfig` or `ConfigServer` like **2048 Game**

reason: the `ConfigFile.h` in LibCore doesn't check for `.config` existence when creating a config file

### PR DESCRIPTION
**Pull request by kleinesfilmroellchen**
If the .config directory (or its children, like lib) was deleted,
ConfigFile would crash because it would try to open or create a file in a directory that didn't exist. Therefore, for user and library configs (but not system configs), ensure that the parent directories exist. This allows the user to delete the entire .config folder and all apps still work. (Except those which can't handle missing config. That's a separate issue though.)
    
Fixes #13555
    
Note: Some changes to pledges and unveils are necessary for this to work. The only one who can recreate .config at the moment is ConfigServer, as others probably don't pledge the user home directory.

This PR also contains the new Core::Directory, which has the fixed ConfigFile as its first user.

### CODE REVIEW

File: Userland/Libraries/LibCore/Directory.cpp [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+namespace Core {
+
+// We assume that the fd is a valid directory.
+Directory::Directory(int fd, Optional<LexicalPath> path)
+    : m_path(move(path))
+    , m_directory_fd(fd)
+{
+}
+
+static ErrorOr<bool> is_valid_directory(int fd)
```
Comment (alichraghi) [inline Userland/Libraries/LibCore/Directory.cpp:21]: there's a same function `Core::File`. i guess you have to remove it

https://github.com/SerenityOS/serenity/blob/751b605690fa28540243a347836c19b972362f20/Userland/Libraries/LibCore/File.cpp#L118-L124

File: Userland/Libraries/LibCore/Directory.h [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+// Deal with real system directories. Any Directory instance always refers to a valid existing directory.
+class Directory {
+    AK_MAKE_NONCOPYABLE(Directory);
+
+public:
+    Directory(Directory&&) = default;
+
+    // When this flag is set, both the directory attempted to instantiate as well as all of its parents are created with mode 0755 if necessary.
+    enum class CreateDirectories : bool {
```
Comment (alichraghi) [inline Userland/Libraries/LibCore/Directory.h:30]: the `CreateDirectories` is a bit confusing. `CreateParents` would make more sense

**Review by alichraghi — CHANGES_REQUESTED** [review]

**Review by BertalanD — CHANGES_REQUESTED** [review]
`m_directory_fd` is leaked when the object goes out of scope. `::close` it in the destructor.

File: Userland/Libraries/LibCore/Directory.cpp (hunk 1 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/Directory.cpp:21]: Separate commit but sure

File: Userland/Libraries/LibCore/Directory.h (hunk 2 above)
Comment (kleinesfilmroellchen) [reply Userland/Libraries/LibCore/Directory.h:30]: No, because it also creates the specified directory if that doesn't exist.

**Review by alichraghi — APPROVED** [review]

File: Userland/Libraries/LibCore/Directory.cpp [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+ErrorOr<struct stat> Directory::stat() const
+{
+    return System::fstat(m_directory_fd);
+}
+
+ErrorOr<DirIterator> Directory::create_iterator() const
+{
+    return DirIterator { TRY(path()).string() };
+}
```
Comment (awesomekling) [inline Userland/Libraries/LibCore/Directory.cpp:98]: It'd be neat if this could be smart enough to `dup()` the file descriptor instead of reopening via the path.
But no need to do that now :)
