### PR TITLE
LookupServer: Fix to handle whitespace and tabs in /etc/hosts

### LINKED ISSUE #10316: LookupServer: ping not evaluating /etc/hosts file
The `ping` cmd does **not** evaluate the `/etc/hosts` file, so that a custom added ip/hostname pairs is **not** taken into account and `ping mycustomhostname`results in an 

> Lookup failed for 'mycustomhostname'

 error response.

### PR DESCRIPTION
**Pull request by fleximus**
This fixes #10316 because now both whitespaces and tabs are handled as separators in `/etc/hosts`.

### CODE REVIEW

File: Userland/Services/LookupServer/LookupServer.cpp [hunk 1]
```diff
@@ -107,7 +107,8 @@ void LookupServer::load_etc_hosts()
         if (original_line.is_empty())
             break;
         auto trimmed_line = original_line.view().trim_whitespace();
-        auto fields = trimmed_line.split_view('\t', false);
+        auto replaced_line = trimmed_line.replace(" ", "\t", true);
```
Comment (GMTA) [inline Userland/Services/LookupServer/LookupServer.cpp:110]: Does this also work when using 4 spaces to separate IP address and hostname?

Comment (fleximus) [reply Userland/Services/LookupServer/LookupServer.cpp:110]: Short answer is yes. Long answer is that it did before the patch too. Tested with several spaces, several tabs and a combination of both.

**Comment by awesomekling** [comment]
Seems a little inelegant to modify the string instead of handling both whitespace characters, but it's not the end of the world. :)
