### PR TITLE
FileManager+FileOperation: Pass errors from FileOperation and dont crash when displaying them

### LINKED ISSUE #6310: FileManager: Crash when dragging&dropping nonexistent file from Terminal
Reproduce:
```
$ touch test.txt
$ ls -l
$ rm test.txt
then drag test.txt from ls output
```
```
Terminal(88): TerminalWidget 0x026d0808 DRAG ENTER @ [498,144], text/plain,text/uri-list
TextEditor(71): TextEditor 0x053e0bd0 DRAG ENTER @ [34,269], text/plain,text/uri-list
TextEditor(71): HorizontalSplitter 0x053c2018 DRAG ENTER @ [34,269], text/plain,text/uri-list
TextEditor(71): TextEditorWidget 0x054017e8 DRAG ENTER @ [34,269], text/plain,text/uri-list
Terminal(88): TerminalWidget 0x026d0808 DRAG LEAVE
TextEditor(71): TextEditor 0x053e0bd0 DRAG LEAVE
TextEditor(71): HorizontalSplitter 0x053c2018 DRAG ENTER @ [0,309], text/plain,text/uri-list
TextEditor(71): TextEditorWidget 0x054017e8 DRAG ENTER @ [0,309], text/plain,text/uri-list
FileManager (Desktop)(97): accepting drag of text/plain
TextEditor(71): HorizontalSplitter 0x053c2018 DRAG LEAVE
Terminal(88): DragOperation: event loop returned with result 0
[#0 SyncTask(3:3)]: Ext2FS: Flushed 10 blocks to disk
[#0 SyncTask(3:3)]: Ext2FS: Flushed 32 blocks to disk
Terminal(88): TerminalWidget 0x026d0808 DRAG ENTER @ [493,116], text/plain,text/uri-list
FileManager (Desktop)(97): accepting drag of text/plain
Terminal(88): TerminalWidget 0x026d0808 DRAG LEAVE
Terminal(88): DragOperation: event loop returned with result 0
FileOperation(100): perror(): stat: No such file or directory
[#0 FileManager (Desktop)(97:97)]: sys$select: Bad fd number 13
FileManager (Desktop)(97): USERSPACE(97) ASSERTION FAILED: false
../Userland/Libraries/LibCore/EventLoop.cpp:684
...
CrashDaemon(15): 0x490071a8: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(15): 0xa48f5fd6: [libc.so] __assertion_failed +0x106 (syscall.h:44)
CrashDaemon(15): 0x7cccbaa5: [libcore.so] Core::EventLoop::wait_for_event(Core::EventLoop::WaitMode) +0xb15 (EventLoop.cpp:684)
CrashDaemon(15): 0x7cccbaee: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e (NonnullOwnPtr.h:124)
CrashDaemon(15): 0x7cccc45b: [libcore.so] Core::EventLoop::exec() +0x4b (EventLoop.cpp:390)
CrashDaemon(15): 0x22d7ff8f: [libgui.so] GUI::Dialog::exec() +0xff (OwnPtr.h:135)
CrashDaemon(15): 0x22dd01cc: [libgui.so] GUI::MessageBox::show(GUI::Window*, AK::StringView const&, AK::StringView const&, GUI::MessageBox::Type, GUI::MessageBox::InputType) +0x9c (Atomic.h:266)
CrashDaemon(15): 0x73dd1328: [/bin/FileManager] FileManager::FileOperationProgressWidget::did_error() +0xb8 (TypeCasts.h:41)
CrashDaemon(15): 0x73dd1e0b: [/bin/FileManager] AK::Function<void ()>::CallableWrapper<FileManager::FileOperationProgressWidget::FileOperationProgressWidget(AK::NonnullRefPtr<Core::File>)::{lambda()#2}>::call() const +0x30b (FileOperationProgressWidget.cpp:56)
CrashDaemon(15): 0x7cce262c: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7c (Object.h:103)
CrashDaemon(15): 0x7cccbe94: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e4 (Atomic.h:266)
CrashDaemon(15): 0x7cccc45b: [libcore.so] Core::EventLoop::exec() +0x4b (EventLoop.cpp:390)
CrashDaemon(15): 0x22d3b7f5: [libgui.so] GUI::Application::exec() +0x25 (Application.cpp:120)
CrashDaemon(15): 0x73dc4430: [/bin/FileManager] main +0x11e0 (main.cpp:390)
CrashDaemon(15): 0x73dc4d45: [/bin/FileManager] _start +0x45 (crt0_shared.cpp:60)
```

### PR DESCRIPTION
**Pull request by TobyAsE**
The FileManager crashed when it tried to display the MessageBox that an error occured. This PR fixed that by additionally disabling the Notifier in the close_pipe() function.
Also the generated Errors and Warnings are passed to the FileManager from the FileOperation. Here both cause the Error-Window to open.
In the future we should collect the non-fatal errors and warnings and display them to the user.

This closes #6310 .

### CODE REVIEW

File: Userland/Applications/FileManager/DirectoryView.cpp [hunk 1]
```diff
@@ -54,6 +54,12 @@ static HashTable<RefPtr<GUI::Window>> file_operation_windows;
 
 static void run_file_operation([[maybe_unused]] FileOperation operation, const String& source, const String& destination, GUI::Window* parent_window)
 {
+    struct stat st = {};
+    if (stat(source.characters(), &st) < 0) {
+        perror("stat");
+        return;
+    }
```
Comment (awesomekling) [inline Userland/Applications/FileManager/DirectoryView.cpp:61]: Let's put this responsibility in the `FileOperation` helper program and have it signal an error to `FileManager` instead.

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Userland/Applications/FileManager/DirectoryView.cpp (hunk 1 above)
Comment (TobyAsE) [reply Userland/Applications/FileManager/DirectoryView.cpp:61]: That seems like the better approach.

File: Userland/Applications/FileManager/FileOperationProgressWidget.h [hunk 2]
```diff
@@ -40,7 +40,7 @@ class FileOperationProgressWidget : public GUI::Widget {
     explicit FileOperationProgressWidget(NonnullRefPtr<Core::File> helper_pipe);
 
     void did_finish();
-    void did_error();
+    void did_error(const String message = "");
```
Comment (awesomekling) [inline Userland/Applications/FileManager/FileOperationProgressWidget.h:43]:
```suggestion
    void did_error(String message);
```

File: Userland/Services/FileOperation/main.cpp [hunk 3]
```diff
@@ -64,11 +65,16 @@ struct WorkItem {
     off_t size;
 };
 
+static void report_error(String s)
+{
+    outln("ERROR {} {}", s, strerror(errno));
```
Comment (awesomekling) [inline Userland/Services/FileOperation/main.cpp:71]: It doesn't feel safe to rely on `errno` being intact here, since by this point we've already constructed a `String` object which called `malloc` (and that clobbers `errno`).

File: Userland/Services/FileOperation/main.cpp [hunk 4]
```diff
@@ -64,11 +65,16 @@ struct WorkItem {
     off_t size;
 };
 
+static void report_error(String s)
```
Comment (awesomekling) [inline Userland/Services/FileOperation/main.cpp:69]: Please use descriptive variable names.

File: Userland/Applications/FileManager/FileOperationProgressWidget.cpp [hunk 5]
```diff
@@ -55,6 +55,9 @@ FileOperationProgressWidget::FileOperationProgressWidget(NonnullRefPtr<Core::Fil
             did_error();
             return;
         }
+
+        dbgln(line);
```
Comment (awesomekling) [inline Userland/Applications/FileManager/FileOperationProgressWidget.cpp:59]: The first argument to `dbgln` should be a format string:
```suggestion
        dbgln("{}", line);
```

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Userland/Services/FileOperation/main.cpp (hunk 3 above)
Comment (TobyAsE) [reply Userland/Services/FileOperation/main.cpp]: Ah, right!
Fixed that by caching the errno and building the String in the same way as report_warning does. That should do the trick, shouldn't it?

File: Userland/Applications/FileManager/FileOperationProgressWidget.cpp (hunk 5 above)
Comment (TobyAsE) [reply Userland/Applications/FileManager/FileOperationProgressWidget.cpp]: I just forgot that there from debugging and removed it entirely.

**Comment by TobyAsE** [comment]
@awesomekling do you mind if I bump this PR? I know there is a lot of buzzing going on at the moment :^)
All requested changes have been implemented, this should be ready to merge.

**Comment by awesomekling** [comment]
> @awesomekling do you mind if I bump this PR? I know there is a lot of buzzing going on at the moment :^)
> All requested changes have been implemented, this should be ready to merge.

Thanks for bumping it, I had definitely lost track :)
