### PR TITLE
Shell: Add a "." builtin that aliases to "source"

### LINKED ISSUE #19089: Shell: dot builtin (POSIX source) not recognized
The shell (in POSIX compatibility mode) doesn't support the `.` builtin.  It should do (approximately) the same as the `source` builtin which is supported.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot

Example

```
echo "echo Success" >test
# Works:
source ./test
# Doesn't work, but really should:
. ./test
```

### PR DESCRIPTION
**Pull request by jwijenbergh**
This patch adds an alias to the source builtin when an user types ".". We cannot just add an enumeration entry using `__ENUMERATE_SHELL_BUILTIN` because "." is not a valid name in a function.
This patch adds handling similarly to the name rewriting of ":".

Note that this adds the alias in non-posix mode as well, not sure if that is wanted?

Fixes #19089 

First contribution to serenity :^)

### CODE REVIEW

File: Userland/Shell/Shell.h [hunk 1]
```diff
@@ -462,7 +462,8 @@ class Shell : public Core::Object {
 
 #undef __ENUMERATE_SHELL_BUILTIN
 
-            ":"sv, // POSIX-y name for "noop".
+            "."sv, // Alias to "source".
+        ":"sv,     // POSIX-y name for "noop".
```
Comment (jwijenbergh) [inline Userland/Shell/Shell.h:466]: This is the  indentation clang-format gives to me but it looks quite odd, anything wrong here?

**Comment by oskar-skog** [comment]
It won't fully implement it though, as POSIX requires looking it up in `$PATH`.
But it will work for absolute or relative paths (probably the most common use case anyway).

**Comment by jwijenbergh** [comment]
> It won't fully implement it though, as POSIX requires looking it up in `$PATH`. But it will work for absolute or relative paths (probably the most common use case anyway).

Right. As far as I understand "source" is not necessarily POSIX, whereas "." is? In my bash shell, "." is simply an alias to "source" (they both do PATH lookup according to --help). So I'm guessing a follow-up PR should add PATH lookup to the source built-in.

**Comment by oskar-skog** [comment]
> As far as I understand "source" is not necessarily POSIX, whereas "." is?

Correct.  There should be a link to the standard in the github issue.

File: Userland/Shell/Builtin.cpp [hunk 2]
```diff
@@ -1921,7 +1923,7 @@ ErrorOr<int> Shell::builtin_run_with_env(Main::Arguments arguments)
 
 bool Shell::has_builtin(StringView name) const
 {
-    if (name == ":"sv)
+    if (name == ":"sv || name == "."sv)
```
Comment (alimpfard) [inline Userland/Shell/Builtin.cpp:1926]:
```suggestion
    if (name.is_one_of(":"sv, "."sv))
```

File: Userland/Shell/Shell.h (hunk 1 above)
Comment (alimpfard) [reply Userland/Shell/Shell.h:466]: Yep, looks like a clang-format issue. Please add a `// clang-format off` (and the subsequent `// clang-format on`) comment there (a comment with a brief reason why would be nice too)

File: Userland/Shell/Builtin.cpp (hunk 2 above)
Comment (alimpfard) [reply Userland/Shell/Builtin.cpp:1926]: Actually, please limit this one to posix mode.
```suggestion
    if (name == ":"sv || (m_posix_mode && name == "."sv))
```

File: Userland/Shell/Builtin.cpp [hunk 3]
```diff
@@ -1328,6 +1328,8 @@ ErrorOr<bool> Shell::run_builtin(const AST::Command& command, Vector<NonnullRefP
 
     if (name == ":"sv)
         name = "noop"sv;
+    else if (name == "."sv)
```
Comment (alimpfard) [inline Userland/Shell/Builtin.cpp:1331]: ...plus this:
```suggestion
    else if (m_posix_mode && name == "."sv)
```

**Comment by jwijenbergh** [comment]
Thanks a lot @alimpfard for the review. I have implemented your suggestions, it makes sense that we limit this to POSIX mode. Few caveats I found but should be fine I think

- now the clang-format comments are misaligned instead :/
- in non-posix mode `.` is flagged as command not found correctly but it doesn't show up as a red color, however this is the same for e.g. `run_with_env` in non-POSIX mode (no red color but still command not found). So I assume that is a bug (?) somewhere else

**Comment by alimpfard** [comment]
> [`.`] ... doesn't show up as a red color

That's because `.` is a directory, the intent behind not highlighting directories red was to signal in autocomplete that there could be an executable inside (`./foo`) if you tab to check.
That's mostly unrelated to this PR.

File: Userland/Shell/Shell.h [hunk 4]
```diff
@@ -462,7 +462,11 @@ class Shell : public Core::Object {
 
 #undef __ENUMERATE_SHELL_BUILTIN
 
+            "."sv, // Needs to be aliased to "source" in POSIX mode.
+        // clang-format off
```
Comment (alimpfard) [inline Userland/Shell/Shell.h:466]: ...eh, we can live with this one lol

**Comment by jwijenbergh** [comment]
> > [`.`] ... doesn't show up as a red color
> 
> That's because `.` is a directory, the intent behind not highlighting directories red was to signal in autocomplete that there could be an executable inside (`./foo`) if you tab to check. That's mostly unrelated to this PR.

I thought so as well. And without this pr, . showed as a red color
