### PR TITLE
LibGUI/Application:  Resize recent files list to max open file size

### LINKED ISSUE #23130: PixelPaint: It crashes when Cancel button is selected on either File Save or File Save As
The behavior does not manifest if one is able to do a successful save prior. Cancel button works as expected. 

Try :
1. Launch a new instance of PixelPaint.
2. Either create a new image or try to do a File > Save or File > Save As on the current Untitled.pp.
3. Click on Cancel button.
4. Crash.

Log file output:

[0/5] Performing build step for 'lagom'
ninja: no work to do.
[1/5] Performing install step for 'lagom'
[0/1] Install the project...
-- Install configuration: ""
[2/5] Performing build step for 'serenity'
[0/2] Re-checking globbed directories...
[2/2] cd /home/ubuntu/github/serenity/Build/x86_64/Userlan...b/serenity/Build/x86_64/Userland/Libraries/LibC/libc.a *.o
[3/5] Performing install step for 'serenity'
[0/2] Re-checking globbed directories...
[2/3] Install the project...
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/home/ubuntu/github/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[2/3] Install the project...
-- Install configuration: ""
ninja: Entering directory `/home/ubuntu/github/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[0/1] cd /home/ubuntu/github/serenity/Build/x86_64 && /usr....2.0 /home/ubuntu/github/serenity/Meta/build-image-qemu.sh
checking existing image
e2fsck 1.46.5 (30-Dec-2021)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 3A: Optimizing directories
Pass 4: Checking reference counts
Pass 5: Checking group summary information

_disk_image: ***** FILE SYSTEM WAS MODIFIED *****
_disk_image: 74767/523776 files (0.2% non-contiguous), 1158899/2148931 blocks
done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/home/ubuntu/github/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[0/1] cd /home/ubuntu/github/serenity/Build/x86_64 && /usr...ENITY_ARCH=x86_64 /home/ubuntu/github/serenity/Meta/run.sh
WHPX: setting APIC emulation mode in the hypervisor
Windows Hypervisor Platform accelerator is operational
qemu-system-x86_64.exe: warning: TCG doesn't support requested feature: CPUID.07H:EBX.intel-pt [bit 25]
qemu-system-x86_64.exe: warning: TCG doesn't support requested feature: CPUID.07H:EBX.intel-pt [bit 25]
qemu-system-x86_64.exe: multiboot knows VBE. we don't
whpx: injection failed, MSI (0, 0) delivery: 0, dest_mode: 0, trigger mode: 0, vector: 0, lost (c0350005)
[Kernel]: Loading kernel symbol table...
[Kernel]: CPU[0]: Supported features: sse3 pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 cnxt_id sdbg fma cx16 xtpr
pdcm pcid dca sse4_1 sse4_2 movbe popcnt tsc_deadline aes xsave osxsave avx f16c rdrand hypervisor fpu vme de pse tsc ms
r pae mce cx8 apic sep mtrr pge mca cmov pat pse36 psn clflush ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe fsgsbase bmi
1 avx2 smep bmi2 erms invpcid zero_fcs_fds rdseed adx smap clflushopt clwb sha umip gfni vaes vpclmulqdq rdpid fsrm ia32
_arch_capabilities lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs xop skinit wdt lwp
fma4 tce nodeid_msr tbm perfctr_core perfctr_nb dbx perftsc pcx_l2i syscall mp nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dno
wext 3dnow constant_tsc
[Kernel]: CPU[0]: Physical address bit width: 46
[Kernel]: CPU[0]: Virtual address bit width: 48
[Kernel]: Initializing unhandled interrupt handlers
[Kernel]: CPU[0]: CPUID hypervisor signature '', max leaf 0x40000010
[Kernel]: Kernel Commandline: Kernel/Prekernel/Prekernel hello disable_virtio root=nvme0:1:0
[Kernel]: Initialize MMU
[Kernel]: MM: Multiboot mmap: address=0x0000000000000000, length=654336, type=1
[Kernel]: MM: Got an unaligned physical_region from the bootloader; correcting length 654336 by 3072 bytes
[Kernel]: MM: Multiboot mmap: address=0x000000000009fc00, length=1024, type=2
[Kernel]: MM: Multiboot mmap: address=0x00000000000f0000, length=65536, type=2
[Kernel]: MM: Multiboot mmap: address=0x0000000000100000, length=1072521216, type=1
[Kernel]: MM: Multiboot mmap: address=0x000000003ffd6000, length=172032, type=2
[Kernel]: MM: Multiboot mmap: address=0x00000000fffc0000, length=262144, type=2
[Kernel]: MM: Multiboot mmap: address=0x000000fd00000000, length=12884901888, type=2
[Kernel]: MM: Contiguous reserved range from P000000000009fc00, length is 394240
[Kernel]: MM: Contiguous reserved range from P000000003ffd6000, length is 3221397504
[Kernel]: MM: boot_pml4t @ P0000000000116000
[Kernel]: MM: boot_pdpt @ P0000000000117000
[Kernel]: MM: boot_pd0 @ P0000000000118000
[Kernel]: MM: boot_pd_kernel @ P000000000013c000
[Kernel]: MM: Physical page entries: 0x0000002000200000 - 0x0000002000a00fff (size 0x0000000000801000)
[Kernel]: MM: Low memory range @ P0000000000000000 - P00000000000fffff (size 0x100000)
[Kernel]: MM: Kernel range @ P0000000000200000 - P0000000003342fff (size 0x3143000)
[Kernel]: MM: Physical Pages range @ P0000000003344000 - P0000000003b49fff (size 0x806000)
[Kernel]: MM: User physical region: P0000000000101000 - P00000000001fefff (size 0xfe000)
[Kernel]: MM: User physical region: P0000000003b4a000 - P000000003ffd5fff (size 0x3c48c000)
[Kernel]:  * 60x PhysicalZone (16 MiB) @ 0000000003b4a000-000000003eb49fff
[Kernel]:  * 4x PhysicalZone (1 MiB) @ 000000003fb4a000-000000003fe49fff
[Kernel]: VGA Text mode console initialized!
[Kernel]: Starting SerenityOS...
[Kernel]: Can't enable SMP mode without IOAPIC mode being enabled
[Kernel]: Interrupts: Switch to IOAPIC mode
[Kernel]: Early access to ACPI tables for interrupt setup
[Kernel]: Interrupts: MADT @ P 0x000000003ffe51b4
[Kernel]: PIC: Cascading mode, vectors 0x50-0x5f
[Kernel]: IOAPIC found @ MADT entry 2, MMIO Registers @ P00000000fec00000
[Kernel]: IOAPIC ID: 0x0
[Kernel]: IOAPIC Version: 0x20, redirection entries: 24
[Kernel]: IOAPIC Arbitration ID 0x0
[Kernel]: Interrupts: Overriding INT 0x0 with GSI 2, for bus 0x0
[Kernel]: Interrupts: Overriding INT 0x5 with GSI 5, for bus 0x0
[Kernel]: Interrupts: Overriding INT 0x9 with GSI 9, for bus 0x0
[Kernel]: Interrupts: Overriding INT 0xa with GSI 10, for bus 0x0
[Kernel]: Interrupts: Overriding INT 0xb with GSI 11, for bus 0x0
[Kernel]: Interrupts: Detected Dual i8259 - Disabled
[Kernel]: Interrupts: Detected IOAPIC
[Kernel]: MultiProcessor: Floating Pointer Structure @ P00000000000f5460
[Kernel]: Features 0, IMCR? 0
[Kernel]: MultiProcessor: Get PCI IOAPIC redirections
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 7, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 4, IOAPIC 0, IOAPIC INTIN 9
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 12, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 16, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 20, IOAPIC 0, IOAPIC INTIN 10
[Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 28, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 1, trigger mode 0, INT 3, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 1, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 9
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 3, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 4, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 5, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 10
[Kernel]: Interrupts: Bus 0, polarity 1, PCI device 7, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 11
[Kernel]: ACPI: Using RSDP @ P00000000000f5280
[Kernel]: ACPI: Main Description Table valid? true
[Kernel]: ACPI: Using RSDT, enumerating tables @ P000000003ffe5294
[Kernel]: ACPI: RSDT revision 1, total length: 52
[Kernel]: ACPI: Initializing Fixed ACPI data
[Kernel]: ACPI: Fixed ACPI data, Revision 1, length: 116 bytes
[Kernel]: ACPI: Using DSDT @ P000000003ffe0040 with 20736 bytes
[Kernel]: RTC:  Year: 2024, month: 2, day: 9, hour: 1, minute: 40, second: 11
[Kernel]: HPET @ P000000003ffe5234
[Kernel]: HPET: Minimum clock tick - 0
[Kernel]: HPET: Timers count - 3
[Kernel]: HPET: Main counter size: 64-bit
[Kernel]: HPET: Timer[0] comparator size: 64-bit, mode: 64-bit
[Kernel]: HPET: Timer[1] comparator size: 64-bit, mode: 64-bit
[Kernel]: HPET: Timer[2] comparator size: 64-bit, mode: 64-bit
[Kernel]: HPET: frequency 100000000 Hz (100 MHz) resolution: 10 ns
[Kernel]: HPET: Setting appropriate functions to timers.
[Kernel]: Duration: Scanning for periodic timers
[Kernel]: Duration: Scanning for non-periodic timers
0.000 [Kernel]: APICTimer: Using HPET as calibration source
0.000 [Kernel]: KernelRng: Using RDSEED as entropy source
0.000 [Kernel]: APICTimer: Ticks per second: 240 (4.160320ms)
0.000 [Kernel]: APICTimer: Bus clock speed: 208.9760 MHz
0.000 [Kernel]: APICTimer: CPU clock speed: 1877.88050 MHz
0.000 [Kernel]: Duration: Using APIC timer as system timer
0.155 [#0 colonel(0:0)]: Scheduler[0]: idle loop running
0.157 [init_stage2(1:1)]: Testing PCI via manual probing...
0.163 [init_stage2(1:1)]: PCI IO supported
0.174 [init_stage2(1:1)]: PCI [0000:00:00:00] PCI::HardwareID [8086:1237]
0.187 [init_stage2(1:1)]: PCI [0000:00:01:00] PCI::HardwareID [8086:7000]
0.191 [init_stage2(1:1)]: PCI [0000:00:01:01] PCI::HardwareID [8086:7010]
0.195 [init_stage2(1:1)]: PCI [0000:00:01:02] PCI::HardwareID [8086:7020]
0.200 [init_stage2(1:1)]: PCI [0000:00:01:03] PCI::HardwareID [8086:7113]
0.204 [init_stage2(1:1)]: PCI [0000:00:02:00] PCI::HardwareID [8086:244e]
0.208 [init_stage2(1:1)]: PCI [0000:01:00:00] PCI::HardwareID [1b36:0010]
0.212 [init_stage2(1:1)]: PCI [0000:00:03:00] PCI::HardwareID [1af4:1003]
0.225 [init_stage2(1:1)]: PCI [0000:00:04:00] PCI::HardwareID [1af4:1005]
0.230 [init_stage2(1:1)]: PCI [0000:00:05:00] PCI::HardwareID [1b36:0001]
0.234 [init_stage2(1:1)]: PCI [0000:02:00:00] PCI::HardwareID [8086:244e]
0.238 [init_stage2(1:1)]: PCI [0000:03:00:00] PCI::HardwareID [1b36:0007]
0.242 [init_stage2(1:1)]: PCI [0000:02:01:00] PCI::HardwareID [8086:100e]
0.247 [init_stage2(1:1)]: PCI [0000:00:06:00] PCI::HardwareID [8086:244e]
0.251 [init_stage2(1:1)]: PCI [0000:04:00:00] PCI::HardwareID [1b36:0007]
0.263 [init_stage2(1:1)]: PCI [0000:04:01:00] PCI::HardwareID [8086:2922]
0.268 [init_stage2(1:1)]: PCI [0000:00:07:00] PCI::HardwareID [8086:293e]
0.271 [init_stage2(1:1)]: PCI [0000:00:08:00] PCI::HardwareID [1234:1111]
0.276 [#0 init_stage2(1:1)]: I8042: Dual channel controller
0.276 [init_stage2(1:1)]: PS2MouseDevice: Mouse wheel enabled!
0.283 [init_stage2(1:1)]: PS2MouseDevice: 5 buttons enabled!
0.446 [#0 init_stage2(1:1)]: Framebuffer Console: taking 3145728 bytes
0.464 [#0 init_stage2(1:1)]: Framebuffer Console: taking 3145728 bytes
0.469 [#0 init_stage2(1:1)]: VC 0: Resized to 113 x 48
0.472 [#0 init_stage2(1:1)]: VC 1: Resized to 113 x 48
0.472 [#0 init_stage2(1:1)]: VC 2: Resized to 113 x 48
0.477 [#0 init_stage2(1:1)]: VC 3: Resized to 113 x 48
0.480 [#0 init_stage2(1:1)]: VC 4: Resized to 113 x 48
0.480 [#0 init_stage2(1:1)]: VC 5: Resized to 113 x 48
0.489 [init_stage2(1:1)]: UHCI: PCI [0000:00:01:02]: Controller found PCI::HardwareID [8086:7020] @ PCI [0000:00:01:02]
0.508 [init_stage2(1:1)]: UHCI: PCI [0000:00:01:02]: I/O base IO e040
0.511 [init_stage2(1:1)]: UHCI: PCI [0000:00:01:02]: Interrupt line: 11
0.518 [#0 init_stage2(1:1)]: UHCI: Allocated framelist at physical address P00000000084c7000
0.522 [#0 init_stage2(1:1)]: UHCI: Framelist is at virtual address V0x0000002000af9000
0.522 [#0 init_stage2(1:1)]: UHCI: QH(0x2000afafc0) @ 0x84c6fc0: link_ptr=0x84c6fa2, element_link_ptr=0x0001
0.529 [#0 init_stage2(1:1)]: UHCI: QH(0x2000afafa0) @ 0x84c6fa0: link_ptr=0x84c6f82, element_link_ptr=0x0001
0.534 [#0 init_stage2(1:1)]: UHCI: QH(0x2000afaf80) @ 0x84c6f80: link_ptr=0x84c6f62, element_link_ptr=0x0001
0.537 [#0 init_stage2(1:1)]: UHCI: QH(0x2000afaf60) @ 0x84c6f60: link_ptr=0x84c6f82, element_link_ptr=0x84c5fe0
0.542 [#0 init_stage2(1:1)]: UHCI: Reset completed
0.545 [#0 init_stage2(1:1)]: UHCI: Started
0.548 [#0 VFS Sync Task(4:4)]: VFS SyncTask is running
0.548 [#0 init_stage2(1:1)]: SysFSBIOSDirectory: SMBIOS 64bit Entry point @ P00000000000f52a0
0.548 [#0 init_stage2(1:1)]: SysFSBIOSDirectory: Data table @ P00000000000f52c0
0.563 [init_stage2(1:1)]: E1000: PCI [0000:02:01:00]: Found @ PCI [0000:02:01:00]
0.568 [init_stage2(1:1)]: E1000: PCI [0000:02:01:00]: IO base: Memory P00000000fe440000
0.573 [init_stage2(1:1)]: E1000: PCI [0000:02:01:00]: Interrupt line: 10
0.573 [init_stage2(1:1)]: E1000: PCI [0000:02:01:00]: Has EEPROM? true
0.578 [init_stage2(1:1)]: E1000: PCI [0000:02:01:00]: MAC address: {52:54:00:12:34:56}
0.581 [init_stage2(1:1)]: AudioManagement: Failed to probe device PCI [0000:00:07:00], due to Error(errno=5)
0.586 [init_stage2(1:1)]: IntelHDA: PCI [0000:00:07:00]: Intel High Definition Audio specification v1.0
0.593 [init_stage2(1:1)]: IntelHDA: PCI [0000:00:07:00]: Found codec on address #0
0.598 [init_stage2(1:1)]: IntelHDA: PCI [0000:00:07:00]: Successfully configured an audio output path
0.603 [init_stage2(1:1)]: IntelHDA: PCI [0000:00:07:00]: Set output channel #0 PCM rate: 44100 Hz
0.608 [#0 init_stage2(1:1)]: IDE controller @ PCI [0000:00:01:01]: interrupt line was set to 0
0.612 [#0 init_stage2(1:1)]: IDE controller @ PCI [0000:00:01:01]: ISA Compatibility mode-only controller, supports bus
mastering
0.617 [#0 init_stage2(1:1)]: IDE controller @ PCI [0000:00:01:01]: bus master base was set to IO e080
1.250 [#0 init_stage2(1:1)]: Allocated SDHC DMA buffer at P000000000846a000
1.256 [#0 init_stage2(1:1)]: Setting SDHostController to operate using ADMA2 with 32 bit addressing
1.258 [#0 init_stage2(1:1)]: Allocated SDHC DMA buffer at P000000000844a000
1.258 [#0 init_stage2(1:1)]: Setting SDHostController to operate using ADMA2 with 32 bit addressing
1.264 [init_stage2(1:1)]: Unable to initialize AHCI controller: Error(errno=5)
1.267 [#0 init_stage2(1:1)]: GUIDPartitionTable: bad signature 0x00000000 0x00000000
1.275 [init_stage2(1:1)]: Ext2FS: Mount successful, setting superblock to error state.
1.279 [init_stage2(1:1)]: VirtualFileSystem: mounted root(1) from Ext2FS (device:3,0)
1.279 [init_stage2(1:1)]: Write-protected kernel symbols after init.
1.284 [init_stage2(1:1)]: Unmapped 1928 KiB of kernel text after init! :^)
1.284 [init_stage2(1:1)]: Running first user process: /init
1.289 [init_stage2(1:1)]: Init (first) process args: [  ]
1.312 [Network Task(9:9)]: NetworkTask: E1000NetworkAdapter network adapter found: hw={52:54:00:12:34:56}
1.312 [Network Task(9:9)]: NetworkTask: LoopbackAdapter network adapter found: hw={13:55:02:09:55:aa}
1.445 SystemServer(8): Spawning mount -a to mount all filesystems.
1.470 mount(10): Mounting all filesystems...
1.474 mount(10): Skipping mounting root
1.480 mount(10): Mounting /bin (bind) on /bin
1.480 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:33207 at inode 1:33207
1.487 mount(10): Mounting /etc (bind) on /etc
1.489 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:12 at inode 1:12
1.491 mount(10): Mounting /home (bind) on /home
1.491 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:13 at inode 1:13
1.497 mount(10): Mounting /root (bind) on /root
1.497 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:15 at inode 1:15
1.502 mount(10): Mounting /var (bind) on /var
1.504 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:33210 at inode 1:33210
1.504 mount(10): Mounting /www (bind) on /www
1.509 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:17 at inode 1:17
1.512 mount(10): Mounting /usr/Tests (bind) on /usr/Tests
1.512 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:35656 at inode 1:35656
1.519 mount(10): Mounting /usr/local (bind) on /usr/local
1.521 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:35661 at inode 1:35661
1.521 mount(10): Mounting /usr/Ports (bind) on /usr/Ports
1.526 [#0 mount(10:10)]: VirtualFileSystem: Bind-mounting inode 1:35654 at inode 1:35654
1.537 [#0 SystemServer(8:8)]: VirtualFileSystem: Remounting inode 1:2
1.537 [#0 SystemServer(8:8)]: VirtualFileSystem: FileSystemID 2, Mounting ProcFS at inode 1:73547 with flags 4
1.544 [#0 SystemServer(8:8)]: VirtualFileSystem: FileSystemID 3, Mounting SysFS at inode 1:73554 with flags 0
1.550 [#0 SystemServer(8:8)]: VirtualFileSystem: FileSystemID 4, Mounting RAMFS at inode 1:73553 with flags 262
1.550 [#0 SystemServer(8:8)]: VirtualFileSystem: FileSystemID 5, Mounting RAMFS at inode 1:73549 with flags 5
1.558 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 8 blocks to disk
1.566 [#0 SystemServer(8:8)]: VirtualFileSystem: FileSystemID 6, Mounting DevPtsFS at inode 4:10 with flags 0
1.571 SystemServer(8): Creating /tmp/coredump directory
1.577 SystemServer(8): Setting /tmp/coredump as the coredump directory
1.579 SystemServer(8): Creating /tmp/semaphore directory
1.583 SystemServer(8): Read system_mode: graphical
2.610 SystemServer(8): Activating 6 services...
2.743 SystemServer(8): Service KeyboardPreferenceLoader has exited with exit code 0
2.793 LookupServer(14): Using network config file at /etc/LookupServer.ini
2.839 [#0 keymap(18:18)]: New Character map 'en-us' passed in by client.
2.897 NetworkServer(17): Interfaces to configure: [ ep1s0 ]
2.901 NetworkServer(17): Config for interface ep2s1 doesn't exist, enabling DHCP for it
2.901 NetworkServer(17): Disabling interface ep2s1
2.931 route(20): Exiting with runtime error: ioctl: No such process (errno=3)
2.956 NetworkServer(17): Running DHCPClient for interfaces: [ ep2s1 ]
2.964 SystemServer(8): Service NetworkServer has exited with exit code 0
2.989 DHCPClient(22): We were offered 10.0.2.15 for 2152792320
2.993 DHCPClient(22): Leasing the IP 10.0.2.15 for adapter ep2s1
5.114 WindowServer(12): update_virtual_and_physical_rects for screen #0: [0,0 1024x768]
3.122 [#0 WindowServer(12:12)]: Framebuffer Console: taking 3145728 bytes
3.134 WindowServer(12): update_virtual_and_physical_rects for screen #0: [0,0 1024x768]
3.137 WindowServer(12): update_virtual_and_physical_rects for screen #0: [0,0 1024x768]
3.442 WindowServer(12): Entering WindowServer main loop
3.571 LoginServer(23): login with sid=23
3.575 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 20 blocks to disk
3.592 SystemServer(23): Activating 25 services...
3.800 AudioServer(26): Started Thread "AudioServer[mixer]"(38)
3.879 ResourceGraph.Applet(31): Create applet: 0 with spec 'CPUGraph,#00bb00'
6.021 SpiceAgent(25): Exiting with runtime error: Failed to find spice device file!
4.108 SystemServer(23): Service SpiceAgent has exited with exit code 1
4.145 ResourceGraph.Applet(31): Create applet: 1 with spec 'MemoryGraph,#00bbbb'
4.154 ResourceGraph.Applet(31): Create applet: 2 with spec 'NetworkGraph,#bbbb00'
4.175 ClipboardHistory.Applet(37): Unable to load clipboard history: open: No such file or directory (errno=2)
4.291 utmpupdate(40): Updating utmp from UID=100 GID=100 EGID=5 PID=39
4.595 [#0 VFS Sync Task(4:4)]: Ext2FS: Flushed 20 blocks to disk
7.285 Taskbar(34): Possible shenanigans! Validating an ELF with executable stack.
415.568 PixelPaint(44): CreateNewImageDialog(0x00000001afdbc6b0): Quit event loop with result 1
415.573 PixelPaint(44): CreateNewImageDialog(0x00000001afdbc6b0): Event loop returned with result 1
424.108 FileSystemAccessServer(45): FilePicker(0x0000000dab3b0040): Quit event loop with result 1
424.113 FileSystemAccessServer(45): FilePicker(0x0000000dab3b0040): Event loop returned with result 1
424.125 PixelPaint(44): VERIFICATION FAILED: i < m_size at ././AK/Vector.h:148
424.125 [PixelPaint(44:44)]: CRASH: CPU #0 Illegal instruction in userspace
424.125 [#0 PixelPaint(44:44)]: Exception code: 0000 (isr: 0000)
424.125 [#0 PixelPaint(44:44)]:     pc=0x0023:0x00000019491a7e38 rflags=0x0000000000010202
424.125 [#0 PixelPaint(44:44)]:  stack=0x0000001687acfae0  fs=0x00000012719e8000  gs=0x000000200ca40120
424.125 [#0 PixelPaint(44:44)]:    rax=0x0000000000000000 rbx=0x0000001687acfbaf rcx=0x000000034e6b102b rdx=0x0000001687
acf988
424.125 [#0 PixelPaint(44:44)]:    rbp=0x0000001687acfb20 rsp=0x0000002014bbff10 rsi=0x0000001687acf988 rdi=0x0000000000
000065
424.125 [#0 PixelPaint(44:44)]:     r8=0x0000000000000064  r9=0x0000000000000000 r10=0x0000000b229d3d70 r11=0x0000000000
000206
424.125 [#0 PixelPaint(44:44)]:    r12=0x000000118edc04d0 r13=0x0000001f547dff40 r14=0x0000000b229d0a98 r15=0x0000000000
000001
424.125 [#0 PixelPaint(44:44)]:    cr0=0x0000000080010013 cr2=0x0000002012ab1000 cr3=0x000000000f81f000 cr4=0x0000000000
340ee0
424.125 [#0 PixelPaint(44:44)]: 0x00000019491a7e38  (?)

424.125 [#0 PixelPaint(44:44)]: Kernel backtrace:
424.125 [#0 PixelPaint(44:44)]: Kernel + 0x000000000135f3c5  Kernel::Process::crash(int, AK::Optional<Kernel::RegisterSt
ate const&>, bool) +0x2c5
424.125 [#0 PixelPaint(44:44)]: Kernel + 0x00000000012e41c6  Kernel::handle_crash(Kernel::RegisterState const&, char con
st*, int, bool) +0x7e6
424.125 [#0 PixelPaint(44:44)]: Kernel + 0x0000000001513e50  illegal_instruction_asm_entry +0x30
424.184 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 44
424.191 CrashDaemon(33): New coredump file: /tmp/coredump/PixelPaint_44_1707443236
424.445 CrashReporter(46): Started Thread "Background Thread"(47)
428.776 CrashReporter(46:47): Generating backtrace took 4271 ms
428.784 CrashReporter(46:47): --- Backtrace for thread #0 (TID 44) ---
428.784 CrashReporter(46:47): 0x00000019491a7e38: [/usr/lib/libc.so] ak_verification_failed +0x58 (Assertions.cpp:108 =>
 Assertions.cpp:101)
428.792 CrashReporter(46:47): 0x0000000b227d7bb0: [/usr/lib/libgui.so.serenity] GUI::Application::set_most_recently_open
_file(AK::ByteString) +0x6c0 (Vector.h:148 => Vector.h:156 => Application.cpp:392)
428.800 CrashReporter(46:47): 0x00000017635e9e8e: [/bin/PixelPaint] AK::Function<void (GUI::Action&)>::CallableWrapper<P
ixelPaint::MainWidget::initialize_menubar(GUI::Window&)::{lambda(auto:1&)#5}>::call(GUI::Action&) +0x6e (MainWidget.cpp:
218 => Function.h:182)
428.813 CrashReporter(46:47): 0x0000000b227d2e8c: [/usr/lib/libgui.so.serenity] GUI::Action::activate(Core::EventReceive
r*) +0x22c (Function.h:115)
428.819 CrashReporter(46:47): 0x0000000b228309dd: [/usr/lib/libgui.so.serenity] GUI::ConnectionToWindowServer::menu_item
_activated(int, unsigned int) +0x4d (ConnectionToWindowServer.cpp:302)
428.825 CrashReporter(46:47): 0x0000000b22883576: [/usr/lib/libgui.so.serenity] WindowClientStub::handle(IPC::Message co
nst&) +0x3e6 (WindowClientEndpoint.h:3082)
428.832 CrashReporter(46:47): 0x0000000e235c982c: [/usr/lib/libipc.so.serenity] IPC::ConnectionBase::handle_messages() +
0xcc (Connection.cpp:88)
428.843 CrashReporter(46:47): 0x0000000b22838cbd: [/usr/lib/libgui.so.serenity] AK::Function<void ()>::CallableWrapper<I
PC::Connection<WindowClientEndpoint, WindowServerEndpoint>::Connection(IPC::Stub&, AK::NonnullOwnPtr<Core::LocalSocket>)
::{lambda()#1}>::call() +0x4d (Connection.h:95 => Function.h:182)
428.856 CrashReporter(46:47): 0x00000003e44a43f0: [/usr/lib/libcore.so.serenity] AK::Function<void ()>::CallableWrapper<
Core::LocalSocket::setup_notifier()::{lambda()#1}>::call() +0x40 (Function.h:115)
428.863 CrashReporter(46:47): 0x00000003e449892c: [/usr/lib/libcore.so.serenity] Core::Notifier::event(Core::Event&) [cl
one .localalias] +0x5c (Function.h:115)
428.872 CrashReporter(46:47): 0x00000003e4492b24: [/usr/lib/libcore.so.serenity] Core::EventReceiver::dispatch_event(Cor
e::Event&, Core::EventReceiver*) +0x54 (EventReceiver.cpp:163)
428.880 CrashReporter(46:47): 0x00000003e44b26ab: [/usr/lib/libcore.so.serenity] Core::ThreadEventQueue::process() +0x2e
b (ThreadEventQueue.cpp:111)
428.886 CrashReporter(46:47): 0x00000003e448e583: [/usr/lib/libcore.so.serenity] Core::EventLoopImplementationUnix::exec
() [clone .localalias] +0x33 (EventLoopImplementationUnix.cpp:132 => EventLoopImplementationUnix.cpp:124)
428.894 CrashReporter(46:47): 0x00000003e448b6bc: [/usr/lib/libcore.so.serenity] Core::EventLoop::exec() +0x4c (EventLoo
p.cpp:88)
428.899 CrashReporter(46:47): 0x000000176363727e: [/bin/PixelPaint] serenity_main(Main::Arguments) +0x119e (main.cpp:87)
428.905 CrashReporter(46:47): 0x000000176358b757: [/bin/PixelPaint] main +0x147 (Main.cpp:43)
428.905 CrashReporter(46:47): 0x000000176358b8b4: [/bin/PixelPaint] _entry +0x24 (crt0.cpp:48)
444.452 FileSystemAccessServer(49): FilePicker(0x00000002f0080040): Quit event loop with result 1
444.488 FileSystemAccessServer(49): FilePicker(0x00000002f0080040): Event loop returned with result 1
444.510 PixelPaint(48): VERIFICATION FAILED: i < m_size at ././AK/Vector.h:148
444.523 [PixelPaint(48:48)]: CRASH: CPU #0 Illegal instruction in userspace
444.523 [#0 PixelPaint(48:48)]: Exception code: 0000 (isr: 0000)
444.523 [#0 PixelPaint(48:48)]:     pc=0x0023:0x0000001d9c755e38 rflags=0x0000000000010202
444.523 [#0 PixelPaint(48:48)]:  stack=0x0000000f7a809090  fs=0x0000000108294000  gs=0x000000200ca40120
444.523 [#0 PixelPaint(48:48)]:    rax=0x0000000000000000 rbx=0x0000000f7a80915f rcx=0x0000001b651c802b rdx=0x0000000f7a
808f38
444.523 [#0 PixelPaint(48:48)]:    rbp=0x0000000f7a8090d0 rsp=0x0000002014fbfe80 rsi=0x0000000f7a808f38 rdi=0x0000000000
000065
444.523 [#0 PixelPaint(48:48)]:     r8=0x0000000000000064  r9=0x0000000000000000 r10=0x000000177366dd70 r11=0x0000000000
000202
444.523 [#0 PixelPaint(48:48)]:    r12=0x0000000d7c4004d0 r13=0x000000111bf2e500 r14=0x000000177366aa98 r15=0x0000000000
000001
444.523 [#0 PixelPaint(48:48)]:    cr0=0x0000000080010013 cr2=0x00000002d7fce770 cr3=0x0000000022205000 cr4=0x0000000000
340ee0
444.523 [#0 PixelPaint(48:48)]: 0x0000001d9c755e38  (?)

444.523 [#0 PixelPaint(48:48)]: Kernel backtrace:
444.523 [#0 PixelPaint(48:48)]: Kernel + 0x000000000135f3c5  Kernel::Process::crash(int, AK::Optional<Kernel::RegisterSt
ate const&>, bool) +0x2c5
444.523 [#0 PixelPaint(48:48)]: Kernel + 0x00000000012e41c6  Kernel::handle_crash(Kernel::RegisterState const&, char con
st*, int, bool) +0x7e6
444.523 [#0 PixelPaint(48:48)]: Kernel + 0x0000000001513e50  illegal_instruction_asm_entry +0x30
444.675 [#0 Finalizer Task(5:5)]: Generating coredump for pid: 48
444.685 CrashDaemon(33): New coredump file: /tmp/coredump/PixelPaint_48_1707443256
445.313 CrashReporter(50): Started Thread "Background Thread"(51)
449.529 CrashReporter(50:51): Generating backtrace took 4204 ms
449.539 CrashReporter(50:51): --- Backtrace for thread #0 (TID 48) ---
449.547 CrashReporter(50:51): 0x0000001d9c755e38: [/usr/lib/libc.so] ak_verification_failed +0x58 (Assertions.cpp:108 =>
 Assertions.cpp:101)
449.565 CrashReporter(50:51): 0x0000001773471bb0: [/usr/lib/libgui.so.serenity] GUI::Application::set_most_recently_open
_file(AK::ByteString) +0x6c0 (Vector.h:148 => Vector.h:156 => Application.cpp:392)
449.588 CrashReporter(50:51): 0x0000001c7df7bf9e: [/bin/PixelPaint] AK::Function<void (GUI::Action&)>::CallableWrapper<P
ixelPaint::MainWidget::initialize_menubar(GUI::Window&)::{lambda(auto:1&)#4}>::call(GUI::Action&) +0x6e (MainWidget.cpp:
211 => Function.h:182)
449.619 CrashReporter(50:51): 0x000000177346ce8c: [/usr/lib/libgui.so.serenity] GUI::Action::activate(Core::EventReceive
r*) +0x22c (Function.h:115)
449.645 CrashReporter(50:51): 0x00000017734ca9dd: [/usr/lib/libgui.so.serenity] GUI::ConnectionToWindowServer::menu_item
_activated(int, unsigned int) +0x4d (ConnectionToWindowServer.cpp:302)
449.665 CrashReporter(50:51): 0x000000177351d576: [/usr/lib/libgui.so.serenity] WindowClientStub::handle(IPC::Message co
nst&) +0x3e6 (WindowClientEndpoint.h:3082)
449.682 CrashReporter(50:51): 0x00000013b6eea82c: [/usr/lib/libipc.so.serenity] IPC::ConnectionBase::handle_messages() +
0xcc (Connection.cpp:88)
449.699 CrashReporter(50:51): 0x00000017734d2cbd: [/usr/lib/libgui.so.serenity] AK::Function<void ()>::CallableWrapper<I
PC::Connection<WindowClientEndpoint, WindowServerEndpoint>::Connection(IPC::Stub&, AK::NonnullOwnPtr<Core::LocalSocket>)
::{lambda()#1}>::call() +0x4d (Connection.h:95 => Function.h:182)
449.733 CrashReporter(50:51): 0x00000001fabce3f0: [/usr/lib/libcore.so.serenity] AK::Function<void ()>::CallableWrapper<
Core::LocalSocket::setup_notifier()::{lambda()#1}>::call() +0x40 (Function.h:115)
449.756 CrashReporter(50:51): 0x00000001fabc292c: [/usr/lib/libcore.so.serenity] Core::Notifier::event(Core::Event&) [cl
one .localalias] +0x5c (Function.h:115)
449.779 CrashReporter(50:51): 0x00000001fabbcb24: [/usr/lib/libcore.so.serenity] Core::EventReceiver::dispatch_event(Cor
e::Event&, Core::EventReceiver*) +0x54 (EventReceiver.cpp:163)
449.806 CrashReporter(50:51): 0x00000001fabdc6ab: [/usr/lib/libcore.so.serenity] Core::ThreadEventQueue::process() +0x2e
b (ThreadEventQueue.cpp:111)
449.823 CrashReporter(50:51): 0x00000001fabb8583: [/usr/lib/libcore.so.serenity] Core::EventLoopImplementationUnix::exec
() [clone .localalias] +0x33 (EventLoopImplementationUnix.cpp:132 => EventLoopImplementationUnix.cpp:124)
449.855 CrashReporter(50:51): 0x00000001fabb56bc: [/usr/lib/libcore.so.serenity] Core::EventLoop::exec() +0x4c (EventLoo
p.cpp:88)
449.875 CrashReporter(50:51): 0x0000001c7dfc927e: [/bin/PixelPaint] serenity_main(Main::Arguments) +0x119e (main.cpp:87)
449.894 CrashReporter(50:51): 0x0000001c7df1d757: [/bin/PixelPaint] main +0x147 (Main.cpp:43)
449.907 CrashReporter(50:51): 0x0000001c7df1d8b4: [/bin/PixelPaint] _entry +0x24 (crt0.cpp:48)

### PR DESCRIPTION
**Pull request by kemzeb**
Since it's possible to have less recently opened files than max_recently_open_files(), which causes us to crash when we try to access new_recent_files_list where index >= size.

Found while looking for a fix to #23130.

### CODE REVIEW

**Comment by tcl3** [comment]
This change LGTM.

I also had a go at fixing this. I've just submitted my own PR (#23132) which fixes PixelPaint, so that it doesn't try to add an empty file path when saving is cancelled, which is what caused the crash in this case.

**Comment by kemzeb** [comment]
@tcl3 Thanks for the review! I do feel like your changes addresses the issue more directly than my change so I'll modify my PR description to reflect this

File: Userland/Libraries/LibGUI/Application.cpp [hunk 1]
```diff
@@ -388,7 +388,7 @@ void Application::set_most_recently_open_file(ByteString new_path)
 
     new_recent_files_list.prepend(new_path);
```
Comment (tcl3) [inline Userland/Libraries/LibGUI/Application.cpp:390]: Actually, I think a *marginally* better fix might be to put `new_recent_files_list.resize(max_recently_open_files());` here. This would ensure that the old list is completely overwritten with any duplicates removed.

Bearing in mind that either fix only comes into play if you try to insert an empty entry, or manually edit the config file to insert duplicates.

Comment (kemzeb) [reply Userland/Libraries/LibGUI/Application.cpp:391]: I believe I made the necessary changes, though I think I misunderstand something here because with resizing it seems to me that it would add empty entries if new list < max_recently_open_files() (though I do see that first loop will return empty file paths in the list if there isn't any recent opened files, so I guess it's fine?). Thanks for your help!

Comment (tcl3) [reply Userland/Libraries/LibGUI/Application.cpp:391]: The recent files list treats a blank entry as an empty slot. We are deliberately adding empty entries in the case that there are duplicates, so that the slots they took in the list are freed.

Comment (kemzeb) [reply Userland/Libraries/LibGUI/Application.cpp:391]: Makes perfect sense to me, thanks!
