### PR TITLE
LibJS+LibCore: Support more weird date formats found on the web

### LINKED ISSUE #22965: LibJS: Support more weird date formats used on the web
Today I printed out all the date strings we failed to parse while I browsed around a bit.

Here's a handy script with all those strings:

```js
let dateStrings = [
    'Jan 01 1970 GMT',
    'Wed Apr 17 23:08:53 2019 +0000',
    '2021-07-01 03:00Z',
    '2024-01-08 9:00Z',
    'Wed, 17 Jan 2024 11:36:34 +0000',
    'Sun Jan 21 2024 21:11:31 GMT 0100 (Central European Standard Time)',
    '2024-01-15 00:00:01',
    'Tue Nov 07 2023 10:05:55  UTC',
    'Wed Apr 17 23:08:53 2019',
    '2024-01-26T22:10:11.306+0000',
    '1/27/2024, 9:28:30 AM',
];

for (let dateString of dateStrings) {
    console.log(new Date(dateString));
}
```

### PR DESCRIPTION
**Pull request by lanmonster**
fixes #22965

### CODE REVIEW

File: Userland/Libraries/LibJS/Runtime/DateConstructor.cpp [hunk 1]
```diff
@@ -161,14 +161,24 @@ static double parse_date_string(ByteString const& date_string)
...
+        "%B %e, %Y %T"sv,                // "June 5, 2023 17:00:00"
+        "%b %d %Y %Z"sv,                 // "Jan 01 1970 GMT"
+        "%a %b %e %T %Y %z"sv,           // "Wed Apr 17 23:08:53 2019 +0000"
+        "%Y-%m-%e %RZ"sv,               // "2021-07-01 03:00Z"
+        "%a, %e %b %Y %T %z"sv,         // "Wed, 17 Jan 2024 11:36:34 +0000"
+        "%a %b %e %Y %T GMT %x (%+)"sv, // "Sun Jan 21 2024 21:11:31 GMT 0100 (Central European Standard Time)"
+        "%Y-%m-%e %T"sv,                // "2024-01-15 00:00:01"
+        "%a %b %e %Y %T  %Z"sv,         // "Tue Nov 07 2023 10:05:55  UTC"
+        "%a %b %e %T %Y"sv,             // "Wed Apr 17 23:08:53 2019"
+        "%Y-%m-%eT%T.%3+%z"sv,          // "2024-01-26T22:10:11.306+0000" this is broken
```
Comment (lanmonster) [inline Userland/Libraries/LibJS/Runtime/DateConstructor.cpp:180]: I am not sure why this is broken. I made sure that the "%3+" format token made the lexer point at the correct character (it points at the +), but "%z" is failing to yield a correct datetime.

File: Userland/Libraries/LibJS/Runtime/DateConstructor.cpp [hunk 2]
```diff
@@ -161,14 +161,24 @@ static double parse_date_string(ByteString const& date_string)
...
+        "%Y/%m/%e %R"sv,                 // "2014/11/14 13:05"
+        "%Y-%m-%e %R"sv,                 // "2014-11-14 13:05"
+        "%B %e, %Y %T"sv,                // "June 5, 2023 17:00:00"
+        "%b %d %Y %Z"sv,                 // "Jan 01 1970 GMT"
+        "%a %b %e %T %Y %z"sv,           // "Wed Apr 17 23:08:53 2019 +0000"
+        "%Y-%m-%e %RZ"sv,               // "2021-07-01 03:00Z"
+        "%a, %e %b %Y %T %z"sv,         // "Wed, 17 Jan 2024 11:36:34 +0000"
+        "%a %b %e %Y %T GMT %x (%+)"sv, // "Sun Jan 21 2024 21:11:31 GMT 0100 (Central European Standard Time)"
+        "%Y-%m-%e %T"sv,                // "2024-01-15 00:00:01"
+        "%a %b %e %Y %T  %Z"sv,         // "Tue Nov 07 2023 10:05:55  UTC"
```
Comment (awesomekling) [inline Userland/Libraries/LibJS/Runtime/DateConstructor.cpp:178]: Instead of explicitly having a format with two spaces, perhaps we can allow any amount of whitespace between tokens in all these formats? That seems to be allowed by other engines.

File: Base/home/anon/Source/js/date-strings.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+    '2024-01-15 00:00:01',
+    'Tue Nov 07 2023 10:05:55  UTC',
+    'Wed Apr 17 23:08:53 2019',
+    '2024-01-26T22:10:11.306+0000',
+    '1/27/2024, 9:28:30AM',
+];
+
+for (let dateString of dateStrings) {
+    console.log(new Date(dateString));
+}
```
Comment (awesomekling) [inline Base/home/anon/Source/js/date-strings.js:17]: Please add this as a test under `Userland/Libraries/LibJS/Tests/` instead, so it actually gets run by our testers :)

File: Userland/Libraries/LibJS/Runtime/DateConstructor.cpp (hunk 1 above)
Comment (trflynn89) [reply Userland/Libraries/LibJS/Runtime/DateConstructor.cpp:180]: You need to increment `format_pos` if you're going to consume an additional character from the format string:
```c++
            if (format_pos + 1 < format.length() && format[format_pos + 1] == '+') {
                auto to_skip = format[format_pos] - '0';
                dbgln("skipping {}", to_skip);
                auto discarded = string_lexer.consume(to_skip);
                dbgln("discarded {}. now pointing at {}", discarded,string_lexer.peek());

				++format_pos; // This fixes the parser
            }
```

However this is the only format specifier that has more than one character in it, so maybe let's avoid that oddity and have the specifier just be "%3" instead of "%3+"?

Alternatively, add a millisecond format specifier (which we drop after parsing, since `struct tm` doesn't support sub-second times). But it can at least check if we parsed something like a decimal followed by 3 digits.

File: Base/home/anon/Source/js/date-strings.js (hunk 3 above)
Comment (trflynn89) [reply Base/home/anon/Source/js/date-strings.js:17]: Specifically we test these ad-hoc extensions in: Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js

**Comment by awesomekling** [comment]
Thanks so much for fixing these :^)
