### PR TITLE
Browser: Add error page

### LINKED ISSUE #1210: Browser: error pages
The browser should display error pages like "No Internet connection" or "Protocol not supported: HTTPS" instead of crashing from reaching ASSERT_NOT_REACHED().

### PR DESCRIPTION
**Pull request by linusg**
Add a simple HTML error page, populated via string formatting, that gets loaded into the `HtmlView` when loading the page fails.

There's a lot of room for improvements - most importantly `Protocol::Client` should expose error messages. But at least the browser does crash less now :)

Closes #1210 and #1516.

image

image

image

image

(I don't really understand the last one, does it try to read the directory?)

---

image

### CODE REVIEW

File: Libraries/LibWeb/ResourceLoader.h [hunk 1]
```diff
@@ -41,7 +41,7 @@ class ResourceLoader : public Core::Object {
 public:
     static ResourceLoader& the();
 
-    void load(const URL&, Function<void(const ByteBuffer&)>);
+    void load(const URL&, Function<void(const ByteBuffer&, const Optional<String>)>);
```
Comment (bugaevc) [inline Libraries/LibWeb/ResourceLoader.h:44]: Why don't we pass two callbacks, one for happy case and one for errors?

**Comment by bcoles** [comment]
I like this.

We probably don't want to render user-supplied HTML from third-party websites within the context of `file:///` pages, or in error pages at all for that matter.

```html
<html>
  <head>
    <title>hello friends</title>
  </head>
  <body>
    <a href="file:///?<blink>hello friends</blink><script>alert('hello friends');</script>">click me</a>
  </body>
</html>
```

image

File: Libraries/LibWeb/ResourceLoader.h (hunk 1 above)
Comment (linusg) [reply Libraries/LibWeb/ResourceLoader.h]: Thanks for the suggestion - done :)

**Comment by linusg** [comment]
@bcoles damn, XSS in the browser's error page :smile:
Fixed by wrapping the URL and error message in a `escape_html_entities()` call.

File: Libraries/LibWeb/CSS/StyleValue.cpp [hunk 2]
```diff
@@ -68,16 +68,19 @@ ImageStyleValue::ImageStyleValue(const URL& url, Document& document)
...
+            if (!m_document)
+                return;
+            m_bitmap = Gfx::load_png_from_memory(data.data(), data.size());
+            if (!m_bitmap)
+                return;
+            // FIXME: Do less than a full repaint if possible?
+            if (m_document->frame())
+                m_document->frame()->set_needs_display({});
+        },
+        [](auto) {});
```
Comment (bugaevc) [inline Libraries/LibWeb/CSS/StyleValue.cpp:83]: Can we just have a default value of `null` that does nothing?

File: Libraries/LibWeb/ResourceLoader.h [hunk 3]
```diff
@@ -41,7 +41,7 @@ class ResourceLoader : public Core::Object {
 public:
     static ResourceLoader& the();
 
-    void load(const URL&, Function<void(const ByteBuffer&)>);
+    void load(const URL&, Function<void(const ByteBuffer&)>, Function<void(const String&)>);
```
Comment (bugaevc) [inline Libraries/LibWeb/ResourceLoader.h:44]: Need argument names now, e.g. `success_callback`, `error_callback`

File: Libraries/LibWeb/HtmlView.cpp [hunk 4]
```diff
@@ -346,23 +346,51 @@ void HtmlView::load(const URL& url)
...
+
+void HtmlView::load_error_page(const URL& failed_url, const String& error)
+{
+    auto error_page_url = "file:///res/html/error.html";
+    ResourceLoader::the().load(
+        error_page_url,
+        [this, failed_url, error](auto data) {
+            ASSERT(!data.is_null());
+            auto html = String::format(
+                String::copy(data).characters(),
```
Comment (awesomekling) [inline Libraries/LibWeb/HtmlView.cpp:381]: This is pretty hairy, but I guess it's okay since the file is local and we control it..
