### PR TITLE
LibJS: Fix that '_' no longer accessed the last value in the REPL

### LINKED ISSUE #11935: LibJS+js: "underscore is last value" doesn't work any more
`underscore_is_last_value` behavior, which is being used in `js(1)` has been accidentally annihilated in 830ea0414cc6e4686514ff7de337787dbb6c3b71 (cc @davidot), so now it does nothing:

```console
$ git grep underscore_is_last_value 
Userland/Libraries/LibJS/Runtime/VM.h:    bool underscore_is_last_value() const { return m_underscore_is_last_value; }
Userland/Libraries/LibJS/Runtime/VM.h:    void set_underscore_is_last_value(bool b) { m_underscore_is_last_value = b; }
Userland/Libraries/LibJS/Runtime/VM.h:    bool m_underscore_is_last_value { false };
Userland/Utilities/js.cpp:        interpreter->vm().set_underscore_is_last_value(true);
```

```js
> "foo"
"foo"
> _
Uncaught exception: [ReferenceError] '_' is not defined
> 
```

Since `VM::m_last_value` is no longer a thing, we should probably make it a REPL-specific implementation when adding it back.

### PR DESCRIPTION
**Pull request by davidot**
This fixes #11935

### CODE REVIEW

File: Userland/Utilities/js.cpp [hunk 1]
```diff
@@ -71,6 +71,7 @@
 
 RefPtr<JS::VM> vm;
 Vector<String> repl_statements;
+JS::Handle<JS::Value> last_value = JS::make_handle(JS::js_undefined());
```
Comment (davidot) [inline Userland/Utilities/js.cpp:74]: Not very nice to have this be a global but it was much more complicated storing it in the global object or some other "correct" place

Comment (linusg) [reply Userland/Utilities/js.cpp:74]: It already has a ton of global state so that's fine :^)

File: Userland/Utilities/js.cpp [hunk 2]
```diff
@@ -986,6 +988,11 @@ static bool parse_and_run(JS::Interpreter& interpreter, StringView source, Strin
         }
     };
 
+    if (!result.is_error())
+        last_value = JS::make_handle(result.value());
+    else
+        last_value = JS::make_handle(JS::js_undefined());
```
Comment (linusg) [inline Userland/Utilities/js.cpp:994]: This is undesirable: when using `_` in some expression and then you screw something up & it throws, the last value would be lost.

Since this feature is directly stolen from the Node.js REPL, I think we should do what they do:

```console
$ node
Welcome to Node.js v16.6.0.
Type ".help" for more information.
> "foo"
'foo'
> _
'foo'
> _ + x
Uncaught ReferenceError: x is not defined
> _
'foo'
> 
```

i.e.

```suggestion
```

File: Userland/Utilities/js.cpp [hunk 3]
```diff
@@ -1041,6 +1048,16 @@ void ReplObject::initialize_global_object()
...
     define_native_function("save", save_to_file, 1, attr);
     define_native_function("loadJSON", load_json, 1, attr);
+
+    define_native_accessor(
+        "_",
+        [](JS::VM&, JS::GlobalObject&) {
+            return last_value.value();
+        },
+        [](JS::VM& vm, JS::GlobalObject& global_object) {
+            return vm.throw_completion<JS::ReferenceError>(global_object, JS::ErrorType::DescWriteNonWritable, "_");
```
Comment (linusg) [inline Userland/Utilities/js.cpp:1058]: This is ok for now, but in the old implementation _ sort of served as a proxy: once you'd assign something to it all magic is lost, it becomes a proper variable. Only when nothing was found for the lookup it'd return the last value. 

Node does it like this:

```
> "foo"
'foo'
> _
'foo'
> _ = 42
Expression assignment to _ now disabled.
42
> _
42
> "bar"
'bar'
> _
42
> 
```

TODO is fine :^)

**Comment by davidot** [comment]
Current behavior:
```js
> 
undefined
> _
undefined
> "foo"
"foo"
> _
"foo"
> throw new Exception("No foo :^(")
Uncaught exception: [ReferenceError] 'Exception' is not defined // Whoops just noticed this is not the error I intended but it shows it works
> _
"foo"
> _ = "foo forever"
Disable writing last value to '_'
"foo forever"
> "bar"
"bar"
> _
"foo forever"
> delete _
true
> _
Uncaught exception: [ReferenceError] '_' is not defined
> "foo"
"foo"
> _
Uncaught exception: [ReferenceError] '_' is not defined
> No foo :^(
```

File: Userland/Utilities/js.cpp [hunk 4]
```diff
@@ -1041,6 +1046,24 @@ void ReplObject::initialize_global_object()
...
     define_native_function("loadJSON", load_json, 1, attr);
+
+    define_native_accessor(
+        "_",
+        [](JS::VM&, JS::GlobalObject&) {
+            return last_value.value();
+        },
+        [](JS::VM& vm, JS::GlobalObject& global_object) -> JS::ThrowCompletionOr<JS::Value> {
+            VERIFY(is<ReplObject>(global_object));
+            dbgln("Disable writing last value to '_'");
```
Comment (linusg) [inline Userland/Utilities/js.cpp:1057]: This should probably be outln to also work on serenity?

**Review by linusg — COMMENTED** [review]
Awesome, thanks!

File: Userland/Utilities/js.cpp (hunk 4 above)
Comment (davidot) [reply Userland/Utilities/js.cpp:1060]: I have made it output with `warnln` if we're in serenity

Comment (linusg) [reply Userland/Utilities/js.cpp:1060]: Not sure I understand why we need to make it this special - everything else in the REPL also just uses `outln()`?

Comment (davidot) [reply Userland/Utilities/js.cpp:1060]: Well I was thinking you don't want it to output to stdout in case your outputting to a file but I guess we're in a REPL so that doesn't matter. (And the ifdef to not output twice on lagom)

But I'll just make it use outln :+1:
