### PR TITLE
LibPDF: Add test cases

### LINKED ISSUE #8215: LibPDF: Crash on opening /home/anon/Documents/pdf/non-linearized.pdf
Steps to reproduce:
* Double click `~/Documents/pdf/non-linearized.pdf`

Stacktrace:
```
[#0 FinalizerTask(4:4)]: Generating coredump for pid: 43
[FinalizerTask(4:4)]: RTC: Year: 2021, month: 6, day: 23, hour: 2, minute: 39, second: 2
FileManager(34:34): Received event at "/tmp/coredump/PDFViewer_43_1624415942" but we don't have that node
CrashDaemon(20:20): New coredump file: /tmp/coredump/PDFViewer_43_1624415942
FileManager(34:34): Received event at "/tmp/coredump/PDFViewer_43_1624415942.gz" but we don't have that node
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 43) ---
CrashDaemon(20:20): 0x69f9f1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
CrashDaemon(20:20): 0x9830a3e4: [libc.so] raise +0x24 (syscall.h:34 => signal.cpp:20)
CrashDaemon(20:20): 0x982f3545: [libc.so] abort +0x29 (stdlib.cpp:230)
CrashDaemon(20:20): 0x982f40aa: [libc.so] __assertion_failed +0xea (assert.cpp:31)
CrashDaemon(20:20): 0x5224848e: [libpdf.so] PDF::Parser::parse_object_with_index(unsigned int) +0x8e (RefPtr.h:438)
CrashDaemon(20:20): 0x522354c3: [libpdf.so] PDF::Document::get_or_load_value(unsigned int) +0x1c3 (Document.cpp:64)
CrashDaemon(20:20): 0x522356a1: [libpdf.so] PDF::Document::resolve(PDF::Value const&) [clone .localalias] +0x101 (Document.cpp:140)
CrashDaemon(20:20): 0x52244bc2: [libpdf.so] PDF::Parser::parse_stream(AK::NonnullRefPtr<PDF::DictObject>) +0x232 (Document.h:102)
CrashDaemon(20:20): 0x522459ad: [libpdf.so] PDF::Parser::parse_value() +0x45d (Parser.cpp:616)
CrashDaemon(20:20): 0x52247413: [libpdf.so] PDF::Parser::parse_indirect_value(int, int) +0x93 (Parser.cpp:666)
CrashDaemon(20:20): 0x522476db: [libpdf.so] PDF::Parser::parse_indirect_value() +0xcb (Parser.cpp:684)
CrashDaemon(20:20): 0x5224774d: [libpdf.so] PDF::Parser::initialize_linearization_dict() [clone .localalias] +0x4d (Parser.cpp:119)
CrashDaemon(20:20): 0x52248398: [libpdf.so] PDF::Parser::initialize() +0x38 (Parser.cpp:48)
CrashDaemon(20:20): 0x52238d7a: [libpdf.so] PDF::Document::create(AK::Span<unsigned char const> const&) +0x9a (Document.cpp:42)
CrashDaemon(20:20): 0x4e5b8915: [/bin/PDFViewer] PDFViewerWidget::open_file(AK::String const&) +0x265 (PDFViewerWidget.cpp:116)
CrashDaemon(20:20): 0x4e5b0682: [/bin/PDFViewer] main +0x322 (main.cpp:31)
CrashDaemon(20:20): 0x4e5b0717: [/bin/PDFViewer] _start +0x57 (crt0.cpp:37)
FileManager(34:34): Received event at "/tmp/coredump/PDFViewer_43_1624415942" but we don't have that node
FileManager(34:34): on activation: 2,1, this=0x01873b38, m_model=0x02e53028
PDFViewer(45:45): USERSPACE(45) ASSERTION FAILED: !PtrTraits::is_null(bits)
../.././AK/RefPtr.h:438
```

### PR DESCRIPTION
**Pull request by swoertz**
LibPDF: Add test cases for #10702 and #10717
Add test cases for parsing an empty file and a truncated file.

LibPDF: Add base structure for unit tests
Add a unit test for each sample pdf file that currently exists in the
anon user's `~/Document/pdf` directory.
- linear.pdf
- non-linearized.pdf
- complex.pdf

Each test ensures that the pdf document is parsed and that the page
count is the expected one.

I wasn't able to reproduce the crashes that are reported in #8215.  
8da3ed09b4e903218f23bc6af83685ab72c75bb6 is adding tests that should cover the reported scenarios so I would therefore suggest to close  #8215.

### CODE REVIEW

File: Tests/LibPDF/TestPDF.cpp [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+}
+
+TEST_CASE(empty_file_issue_10702)
+{
+    AK::ReadonlyBytes empty;
+    auto document = PDF::Document::create(empty);
+    EXPECT(document.is_null());
+}
+
+TEST_CASE(truncated_pdf_issue_10717)
```
Comment (bcoles) [inline Tests/LibPDF/TestPDF.cpp:42]: Small nitpick. `LibPDF` uses consume/peek extensively. It is likely that there are many truncation errors.

This specific issue lies within `parse_header`. Suggest:

```suggestion
TEST_CASE(truncated_pdf_header_issue_10717)
```

Admittedly, this is not the only bug in `parse_header` due to truncation either.

Comment (swoertz) [reply Tests/LibPDF/TestPDF.cpp]: Done.

**Comment by ADKaster** [comment]
General comment, it would be good for a future change to figure out how to run these LibPDF tests on the host as well via Lagom, and in a "relocatable" way such as installing (via CMake) the test files into some directory under /usr/Tests/LibPDF and using relative pathing. Currently running these tests require the user running the test to have read access to anon's home directory, which isn't ideal.

**Comment by BenWiederhake** [comment]
I hope I'm not going too :ideaguy: on you, but how about this:
- Put the tests into a new directory `corpus_pdf` in https://github.com/SerenityOS/serenity-fuzz-corpora/
- And maybe execute the corpora once per week, doing some light fuzzing with known-problematic inputs (in contrast to OSSFuzz).

**Comment by swoertz** [comment]
@BenWiederhake: Are you suggesting to remove the sample files from the repository and add them the `serenity-fuzz-corpora` instead or is that more an idea on where to continue after this?

I like the idea of extending fuzzing tests for `LibPDF` however my main goals for this PR were:
- having the base structure for unit testing `LibPDF` in place so that more tests can easily be added and extended
- ensuring that `LibPDF` is able to parse all the sample files that are installed by default without crashing
- adding test cases for problems that have been reported and fixed

File: Tests/LibPDF/TestPDF.cpp [hunk 2]
```diff
@@ -29,3 +31,17 @@ TEST_CASE(complex_pdf)
...
+{
+    AK::ReadonlyBytes empty;
+    auto document = PDF::Document::create(empty);
+    EXPECT(document.is_null());
+}
+
+TEST_CASE(truncated_pdf_header_issue_10717)
+{
+    AK::String string { "%PDF-2.11%" };
+    auto document = PDF::Document::create(string.bytes());
```
Comment (BenWiederhake) [inline Tests/LibPDF/TestPDF.cpp:45]: I didn't realize that the "test cases" are so short. Nevermind then! Putting them in-line is a good idea, please forget what I said initially :D

File: Tests/LibPDF/CMakeLists.txt [hunk 3]
```diff
@@ -5,3 +5,6 @@ set(TEST_SOURCES
 foreach(source IN LISTS TEST_SOURCES)
     serenity_test("${source}" LibPDF LIBS LibCore LibPDF)
 endforeach()
+
+file(GLOB PDF_FILES CONFIGURE_DEPENDS "../../Base/home/anon/Documents/pdf/*.pdf")
```
Comment (BenWiederhake) [inline Tests/LibPDF/CMakeLists.txt:9]: I personally would rather list the files explicitly, but this is okay.

File: Tests/LibPDF/CMakeLists.txt [hunk 4]
```diff
@@ -5,3 +5,6 @@ set(TEST_SOURCES
...
+install(FILES ${PDF_FILES} DESTINATION usr/Tests/LibPDF)
```
Comment (BenWiederhake) [inline Tests/LibPDF/CMakeLists.txt:10]: Err, what? No, why would we install the files twice? (Once in /home/anon/, and again in /usr/Tests/LibPDF.) Also, so far we only have executables in /usr/Tests/ I believe. If you can find a way to keep it this way, I'd prefer it.

File: Tests/LibPDF/TestPDF.cpp [hunk 5]
```diff
@@ -13,21 +13,21 @@
 
 TEST_CASE(linearized_pdf)
 {
-    auto file = Core::MappedFile::map("/home/anon/Documents/pdf/linearized.pdf").release_value();
+    auto file = Core::MappedFile::map("linearized.pdf").release_value();
```
Comment (BenWiederhake) [inline Tests/LibPDF/TestPDF.cpp:16]: Please don't do incremental changes like this. Squash, maybe?

I don't know what the best way to do this is, but maybe you could conditionally `chdir("/home/anon/Documents/pdf/");` if we're executing on Serenity? There's probably a better way still.

**Review by BenWiederhake — CHANGES_REQUESTED** [review]
Nice work! I'm a bit unhappy about the WeakPtr though, especially since it doesn't seem like we're doing a workaround for ref-counting, although ref-counting isn't even useful in this case. Also, I believe we can avoid installing the test-PDFs twice.

File: Tests/LibPDF/CMakeLists.txt [hunk 6]
```diff
@@ -0,0 +1,7 @@
+set(TEST_SOURCES
+    TestPDF.cpp
+)
+
+foreach(source IN LISTS TEST_SOURCES)
+    serenity_test("${source}" LibPDF LIBS LibCore LibPDF)
```
[the remark this answers is not in the document]
Comment (swoertz) [reply Tests/LibPDF/CMakeLists.txt:6]: I am following a pattern here. Similar code is used to add `serenity_test`s in many places of the project even in cases where there is only single test source file (e.g., LibMarkdown, LibM, LibWeb,...).

I would reason that this allows to "quickly" add new files without having to repeat the link dependencies.
I don't have a strong opinion about this and can change it.

File: Tests/LibPDF/TestPDF.cpp [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+ */
+
+#include <LibCore/MappedFile.h>
+#include <LibPDF/Document.h>
+#include <LibTest/Macros.h>
+#include <LibTest/TestCase.h>
+
+TEST_CASE(linearized_pdf)
+{
+    auto file = Core::MappedFile::map("/home/anon/Documents/pdf/linearized.pdf").release_value();
```
[the remark this answers is not in the document]
Comment (swoertz) [reply Tests/LibPDF/TestPDF.cpp]: For every commit that was added to this PR all tests are should be passing (both lagom and serenity/target). Since adding support for `lagom_test` was added in a "later" commit I currently cannot see how lagom would "pointlessly fail".

File: Userland/Libraries/LibPDF/Parser.h [hunk 8]
```diff
@@ -139,7 +140,7 @@ class Parser final : public RefCounted<Parser> {
     bool consume(char);
 
     Reader m_reader;
-    RefPtr<Document> m_document;
+    WeakPtr<Document> m_document;
```
[the remark this answers is not in the document]
Comment (swoertz) [reply Userland/Libraries/LibPDF/Parser.h:143]: I am not too happy about it either. I am seeing this as a temporary workaround. I agree that there is room for further improvement.
However this was the least intrusive change that I could come up with in order to fix the memory leak that became apparent when running tests with address sanitizing enabled.
If I am understanding your suggestion correctly I think this would lead to a chain of changes in order to refactor the ownership between these two classes while still having a circular dependency.
I would argue that this refactoring is outside of the scope of this PR.

File: Tests/LibPDF/CMakeLists.txt (hunk 4 above)
Comment (swoertz) [reply Tests/LibPDF/CMakeLists.txt:10]: https://github.com/SerenityOS/serenity/pull/10969#issuecomment-974692324
This is based on my interpretation of a comment that @ADKaster made.

Also I cannot confirm that there are only executables in `/usr/Tests/`. There are some exceptions already. 

- `/usr/Tests/LibWebtokenizer-test.html`
- `/usr/Tests/LibCore{long_lines.txt,10kb.txt}`

However if that is not the right place for such files I am happy to move them somewhere else. More feedback is appreciated.

File: Tests/LibPDF/TestPDF.cpp (hunk 5 above)
Comment (swoertz) [reply Tests/LibPDF/TestPDF.cpp:16]: There was a comment to add lagom tests as a future improvement. The commit for this "future improvement" was added to this PR. 
I usually try to avoid conditional compilation especially in cases where the code actually *can* be compiled on all targets. Any other suggestion?

File: Tests/LibPDF/CMakeLists.txt (hunk 4 above)
Comment (ADKaster) [reply Tests/LibPDF/CMakeLists.txt:10]: I think the test files being in/usr/Tests is fine until we come up with some kind of common Test input directory. Not sure about the request to not have them duplicated, are you saying we should remove them from Base/ and put them in Tests/LibPDF instead on the repo side, Ben?

File: Tests/LibPDF/CMakeLists.txt (hunk 3 above)
Comment (swoertz) [reply Tests/LibPDF/CMakeLists.txt]: Done

File: Tests/LibPDF/TestPDF.cpp (hunk 5 above)
Comment (swoertz) [reply Tests/LibPDF/TestPDF.cpp:16]: -  [x] Squashed the "install change" into the first commit.

File: Tests/LibPDF/CMakeLists.txt (hunk 4 above)
Comment (BenWiederhake) [reply Tests/LibPDF/CMakeLists.txt]: I take it back then, and whereever you put it is fine with me ^^

File: Userland/Libraries/LibPDF/Parser.h (hunk 8 above)
[the remark this answers is not in the document]
Comment (BenWiederhake) [reply Userland/Libraries/LibPDF/Parser.h:143]: Okay! :)

**Comment by BenWiederhake** [comment]
Related: c2df6b597a1add56345c49ca5bada625a77d563c
(You probably already know about it, sorry.)

**Comment by swoertz** [comment]
> Related: [c2df6b5](https://github.com/SerenityOS/serenity/commit/c2df6b597a1add56345c49ca5bada625a77d563c) (You probably already know about it, sorry.)

Thank you for the heads-up. I have now adapted and rebased the commit. I was aware of the other PR, but I thought this one would get merged first :)

File: Meta/Lagom/CMakeLists.txt [hunk 9]
```diff
@@ -525,6 +525,10 @@ if (BUILD_LAGOM)
             lagom_test(${source} LIBS LagomGL)
         endforeach()
 
+        # PDF
+        lagom_test(../../Tests/LibPDF/TestPDF.cpp LIBS LagomPDF
+                   WORKING_DIRECTORY ${SERENITY_PROJECT_ROOT}/Base/home/anon/Documents/pdf/)
```
Comment (linusg) [inline Meta/Lagom/CMakeLists.txt:530]: Please use the same pattern as below (`file(GLOB)` + `foreach`)

File: Userland/Libraries/LibPDF/Document.h [hunk 10]
```diff
@@ -70,7 +71,8 @@ struct OutlineDict final : public RefCounted<OutlineDict> {
     OutlineDict() = default;
 };
 
-class Document final : public RefCounted<Document> {
+class Document final : public RefCounted<Document>
+    , public AK::Weakable<Document> {
```
Comment (linusg) [inline Userland/Libraries/LibPDF/Document.h:75]: Please format multiple inheritance with each class on its own line (& drop the AK namespace prefix)

```suggestion
class Document final
    : public RefCounted<Document>
    , public Weakable<Document> {
```

**Review by linusg — COMMENTED** [review]
Apologies for the late review, mostly LGTM.

File: Userland/Libraries/LibPDF/Document.h (hunk 10 above)
Comment (swoertz) [reply Userland/Libraries/LibPDF/Document.h]: Done

File: Meta/Lagom/CMakeLists.txt (hunk 9 above)
Comment (swoertz) [reply Meta/Lagom/CMakeLists.txt]: Done
