### PR TITLE
LibJS: Fix functions binding this to global object in strict mode

### LINKED ISSUE #5962: LibJS: Functions bind this to global object in strict mode
Repro:

```js
"use strict"; (function() { console.log(this); })()
```

Expected:

```js
undefined
```

Actual:

```js
[object ReplObject]
```

See:

https://tc39.es/ecma262/#sec-ordinarycallbindthis

### PR DESCRIPTION
**Pull request by ryangjchandler**
This fixes an issue where `this` would be bound to the global object
by default when operating in strict mode.

According to the specification, the expected value for |this| when
no binding is provided is `undefined`.

Closes #5962.

### CODE REVIEW

File: Userland/Libraries/LibJS/AST.cpp [hunk 1]
```diff
@@ -158,6 +158,11 @@ CallExpression::ThisAndCallee CallExpression::compute_this_and_callee(Interprete
 
         return { this_value, callee };
     }
+
+    if (interpreter.vm().in_strict_mode())
+        // If we are in strict mode, |this| should never be bound to global object by default.
+        return { js_undefined(), m_callee->execute(interpreter, global_object) };
```
Comment (linusg) [inline Userland/Libraries/LibJS/AST.cpp:164]: Please use curly braces for any if/else branches where the body is more than one line:

```suggestion
    if (interpreter.vm().in_strict_mode()) {
        // If we are in strict mode, |this| should never be bound to global object by default.
        return { js_undefined(), m_callee->execute(interpreter, global_object) };
    }
```

**Comment by ryangjchandler** [comment]
@linusg Looks like Prettier is failing - running it locally also fails but it's failing on files that I wouldn't have touched at all.
