### PR TITLE
LibJS: Some parser fixes

### LINKED ISSUE #16044: LibJS: Function bindings in nested functions are not initialized for modules
Given the following test file:

test.mjs
```
function foo() {
    function bar() {}
    bar.baz = {}
}

foo.bippity = "boppity"
foo()
```

running `js test.mjs` produces no errors, while `js -m test.mjs` prints

```
WARNING: A promise was rejected without any handlers (result: [ReferenceError] Binding bar is not initialized)
Uncaught exception: [ReferenceError] Binding bar is not initialized
 -> foo
 -> <unknown>
 -> (global execution context)
 ```
 
 The only difference in the AST is that in non-module mode, `foo` is part of the (Variable declarations) of the Program, while in module mode it is part of the (Lexical declarations) instead.
 
Two things stand out looking into this:

1) Our implementation of  10.2.11 FunctionDeclarationInstantiation in ECMAScriptFunctionObject.cpp is quite cowboy, and out of order with respect to the spec steps.

2) `ScopePusher::add_declaration` explicitly adds function declarations to the lexical declarations of the current node when either not top level OR in module program types. 

Given that steps 33-34.a of FunctionDeclarationInstantiation say 
> 33 Let lexDeclarations be the [LexicallyScopedDeclarations](https://tc39.es/ecma262/#sec-static-semantics-lexicallyscopeddeclarations) of code.
> 34. For each element d of lexDeclarations, do
>
>    a. NOTE: A lexically declared name cannot be the same as a function/generator declaration, formal parameter, or a var name. Lexically declared names are only instantiated here but not initialized.
  
I'm skeptical that it's correct to add functions to m_lexical_names at all?

cc @davidot @sin-ack

### PR DESCRIPTION
**Pull request by davidot**
Fixes #16044.

It is a bit harder than it looks because you have to check https://tc39.es/ecma262/#sec-static-semantics-lexicallyscopeddeclarations and https://tc39.es/ecma262/#sec-static-semantics-varscopeddeclarations .
Also if someone has a suggestion how to nicely comment this spec in the code let me know the parser part is always hard :(.

Also this fixes 2 test262 tests, although none from the scoping fix....... (:makemore:)

### CODE REVIEW

File: Userland/Libraries/LibJS/Lexer.cpp [hunk 1]
```diff
@@ -610,8 +610,15 @@ Token Lexer::next()
             consume();
             m_template_states.last().in_expr = true;
         } else {
+            //  TemplateCharacter ::
+            //      $ [lookahead ≠ {]
+            //      \ TemplateEscapeSequence
+            //      \ NotEscapeSequence
+            //       LineContinuation
+            //       LineTerminatorSequence
+            //       SourceCharacter but not one of ` or \ or $ or LineTerminator
```
Comment (linusg) [inline Userland/Libraries/LibJS/Lexer.cpp:619]: Weird alignment
image

File: Userland/Libraries/LibJS/Parser.cpp [hunk 2]
```diff
@@ -130,20 +147,21 @@ class ScopePusher {
...
+                VERIFY(pusher->is_top_level() && pusher->m_node);
                 pusher->m_node->add_var_scoped_declaration(declaration);
             });
 
             VERIFY(m_top_level_scope);
             m_top_level_scope->m_node->add_var_scoped_declaration(move(declaration));
         } else {
-            if (m_is_top_level && m_parser.m_program_type == Program::Type::Script) {
+            if (m_scope_level != ScopeLevel::NotTopLevel && m_scope_level != ScopeLevel::ModuleTopLevel) {
+                // Only non-top levels and Module don't var declar the top names
```
Comment (linusg) [inline Userland/Libraries/LibJS/Parser.cpp:164]: `declare`

**Review by linusg — CHANGES_REQUESTED** [review]
