### PR TITLE
Shell: Make the parser read consecutive sequences without recursing / Don't keep pushing EventLoops when blocking on jobs (#4976)

### LINKED ISSUE #4976: Shell: Shell::Parser::parse_command: fault at invalid address
Reproduce:

* Create a `test.sh` file containing:

```
#!/bin/sh
./doesnotexist  # repeat this line 1,500 times
```

* `chmod +x test.sh`
* `./test.sh`

Log:

```
[Shell(28:28)]: CPU[0] NP(error) fault at invalid address V0x02000ffc
[Shell(28:28)]: Unrecoverable page fault, write to address V0x02000ffc
[Shell(28:28)]: CRASH: CPU #0 Page Fault. Ring 3.
[Shell(28:28)]: exception code: 0006 (isr: 0000
[Shell(28:28)]:   pc=001b:02b27c93 flags=0202
[Shell(28:28)]:  stk=0023:02001000
[Shell(28:28)]:   ds=0023 es=0023 fs=0023 gs=002b
[Shell(28:28)]: eax=02001048 ebx=02b56860 ecx=0000000a edx=00000000
[Shell(28:28)]: ebp=02001128 esp=c45d1fe8 esi=00000001 edi=02001304
[Shell(28:28)]: cr0=80010013 cr2=02000ffc cr3=0379d000 cr4=00100ee4
[Shell(28:28)]: code: e8 48 e5 fd ff 83 c4 20
[Shell(28:28)]: 0x02b27c93  (?)

[Shell(28:28)]: 0xc0182e4c  Kernel::Process::crash(int, unsigned int, bool) +0x2a8
[Shell(28:28)]: 0xc011c8b4  illegal_instruction_handler +0x0
[Shell(28:28)]: 0xc011ce07  page_fault_handler +0x4a8
[Shell(28:28)]: 0xc0118c0b  page_fault_asm_entry +0x26
[Shell(28:28)]: Process regions:
[Shell(28:28)]: BEGIN       END         SIZE        ACCESS  NAME
[Shell(28:28)]: 02001000 -- 02400fff    00400000    RW  TA    Stack (Main thread)
[Shell(28:28)]: 0240c000 -- 0240cfff    00001000    RW   A    (null)
[Shell(28:28)]: 02410000 -- 0241ffff    00010000         A    malloc: ChunkedBlock(256)
[Shell(28:28)]: 02421000 -- 02422fff    00002000    RW   A    Thread-specific
[Shell(28:28)]: 02424000 -- 02425fff    00002000    R XS      libm.so: .text
[Shell(28:28)]: 02426000 -- 02426fff    00001000    RW   A    libm.so: .data
[Shell(28:28)]: 02428000 -- 02428fff    00001000    R XS      libcrypt.so: .text
[Shell(28:28)]: 02429000 -- 02429fff    00001000    RW   A    libcrypt.so: .data
[Shell(28:28)]: 02430000 -- 0243ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02441000 -- 02445fff    00005000    R XS      /bin/Shell: .text
[Shell(28:28)]: 02446000 -- 02446fff    00001000    RW   A    /bin/Shell: .data
[Shell(28:28)]: 02450000 -- 0245ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02470000 -- 0247ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02481000 -- 02496fff    00016000    R         ELF_DYN: /bin/Shell
[Shell(28:28)]: 024a0000 -- 024affff    00010000    RW   A    malloc: ChunkedBlock(256)
[Shell(28:28)]: 024c0000 -- 024cffff    00010000         A    malloc: ChunkedBlock(500)
[Shell(28:28)]: 024e0000 -- 024effff    00010000    RW   A    malloc: ChunkedBlock(1016)
[Shell(28:28)]: 02500000 -- 0250ffff    00010000    RW   A    malloc: ChunkedBlock(4088)
[Shell(28:28)]: 02520000 -- 0252ffff    00010000    RW   A    malloc: ChunkedBlock(8)
[Shell(28:28)]: 02540000 -- 0254ffff    00010000    RW   A    malloc: ChunkedBlock(16)
[Shell(28:28)]: 02560000 -- 0256ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02580000 -- 0258ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 025a0000 -- 025affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 025c0000 -- 025cffff    00010000    RW   A    malloc: ChunkedBlock(256)
[Shell(28:28)]: 025e0000 -- 025effff    00010000    RW   A    malloc: ChunkedBlock(16376)
[Shell(28:28)]: 02600000 -- 0260ffff    00010000         A    malloc: ChunkedBlock(500)
[Shell(28:28)]: 02620000 -- 0262ffff    00010000    RW   A    malloc: ChunkedBlock(1016)
[Shell(28:28)]: 02640000 -- 0264ffff    00010000    RW   A    malloc: ChunkedBlock(2032)
[Shell(28:28)]: 02660000 -- 0266ffff    00010000         A    malloc: ChunkedBlock(8184)
[Shell(28:28)]: 02680000 -- 0268ffff    00010000         A    malloc: BigAllocationBlock
[Shell(28:28)]: 026a0000 -- 026affff    00010000    RW   A    malloc: BigAllocationBlock
[Shell(28:28)]: 026c0000 -- 026cffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 026e0000 -- 026effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02700000 -- 0270ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02720000 -- 0272ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02740000 -- 0274ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02760000 -- 0276ffff    00010000         A    malloc: ChunkedBlock(32752)
[Shell(28:28)]: 02780000 -- 0278ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 027a0000 -- 027affff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 027c0000 -- 027cffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 027e0000 -- 027effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02800000 -- 0280ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02820000 -- 0282ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02840000 -- 0284ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02860000 -- 0286ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02880000 -- 0288ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 028a0000 -- 028affff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 028c0000 -- 028cffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 028e0000 -- 028effff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02900000 -- 0290ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02920000 -- 0292ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02940000 -- 0294ffff    00010000         A    malloc: BigAllocationBlock
[Shell(28:28)]: 02960000 -- 0296ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02980000 -- 0298ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 029a0000 -- 029affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 029c0000 -- 029cffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 029e0000 -- 029effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02a00000 -- 02a0ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02a20000 -- 02a2ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02a40000 -- 02a4ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02a60000 -- 02a6ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02a80000 -- 02a8ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02aa1000 -- 02ab8fff    00018000    R XS      libgcc_s.so: .text
[Shell(28:28)]: 02ab9000 -- 02ab9fff    00001000    RW   A    libgcc_s.so: .data
[Shell(28:28)]: 02ac0000 -- 02acffff    00010000         A    malloc: ChunkedBlock(16)
[Shell(28:28)]: 02ae0000 -- 02aeffff    00010000         A    malloc: ChunkedBlock(2032)
[Shell(28:28)]: 02af1000 -- 02b54fff    00064000    R X       libc.so: .text
[Shell(28:28)]: 02b55000 -- 02b5bfff    00007000    RW   A    libc.so: .data
[Shell(28:28)]: 02b5d000 -- 02b73fff    00017000    R XS      libcrypto.so: .text
[Shell(28:28)]: 02b74000 -- 02b74fff    00001000    RW   A    libcrypto.so: .data
[Shell(28:28)]: 02b76000 -- 02baefff    00039000    R X       libcore.so: .text
[Shell(28:28)]: 02baf000 -- 02bb0fff    00002000    RW   A    libcore.so: .data
[Shell(28:28)]: 02bc0000 -- 02bcffff    00010000         A    malloc: ChunkedBlock(4088)
[Shell(28:28)]: 02bd1000 -- 02beefff    0001e000    R XS      libline.so: .text
[Shell(28:28)]: 02bef000 -- 02beffff    00001000    RW   A    libline.so: .data
[Shell(28:28)]: 02bf1000 -- 02c72fff    00082000    R XS      libshell.so: .text
[Shell(28:28)]: 02c73000 -- 02c76fff    00004000    RW   A    libshell.so: .data
[Shell(28:28)]: 02c80000 -- 02c8ffff    00010000         A    malloc: ChunkedBlock(8184)
[Shell(28:28)]: 02ca0000 -- 02caffff    00010000         A    malloc: ChunkedBlock(16376)
[Shell(28:28)]: 02cc0000 -- 02ccffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02ce0000 -- 02ceffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02d00000 -- 02d0ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02d20000 -- 02d2ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02d40000 -- 02d4ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02d60000 -- 02d6ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02d80000 -- 02d8ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02da0000 -- 02daffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02dc0000 -- 02dcffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02de0000 -- 02deffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02e00000 -- 02e0ffff    00010000    RW   A    malloc: ChunkedBlock(8)
[Shell(28:28)]: 02e20000 -- 02e2ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02e40000 -- 02e4ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02e60000 -- 02e6ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02e90000 -- 02e9ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02eb0000 -- 02ebffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02ed0000 -- 02edffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02ef0000 -- 02efffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02f10000 -- 02f1ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02f30000 -- 02f3ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02f50000 -- 02f5ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02f70000 -- 02f7ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02f90000 -- 02f9ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 02fb0000 -- 02fbffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 02fd0000 -- 02fdffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 02ff0000 -- 02ffffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03020000 -- 0302ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03040000 -- 0304ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03060000 -- 0306ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03080000 -- 0308ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 030a0000 -- 030affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 030c0000 -- 030cffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 030e0000 -- 030effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03100000 -- 0310ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 03120000 -- 0312ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03140000 -- 0314ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03160000 -- 0316ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03180000 -- 0318ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 031a0000 -- 031affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 031d0000 -- 031dffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 031f0000 -- 031fffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03210000 -- 0321ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03230000 -- 0323ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03250000 -- 0325ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03270000 -- 0327ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 03290000 -- 0329ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 032b0000 -- 032bffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 032d0000 -- 032dffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 032f0000 -- 032fffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03310000 -- 0331ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03330000 -- 0333ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03350000 -- 0335ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03370000 -- 0337ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03390000 -- 0339ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 033b0000 -- 033bffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 033d0000 -- 033dffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 033f0000 -- 033fffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03420000 -- 0342ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 03440000 -- 0344ffff    00010000    RW   A    malloc: ChunkedBlock(8)
[Shell(28:28)]: 03460000 -- 0346ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03480000 -- 0348ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 034a0000 -- 034affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 034c0000 -- 034cffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 034e0000 -- 034effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03500000 -- 0350ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03520000 -- 0352ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03540000 -- 0354ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03560000 -- 0356ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03580000 -- 0358ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 035a0000 -- 035affff    00010000    RW   A    malloc: ChunkedBlock(32)
[Shell(28:28)]: 035c0000 -- 035cffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 035e0000 -- 035effff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03600000 -- 0360ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03620000 -- 0362ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03640000 -- 0364ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03660000 -- 0366ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 03680000 -- 0368ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 036a0000 -- 036affff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 036c0000 -- 036cffff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 036e0000 -- 036fffff    00020000    RW   A    malloc: BigAllocationBlock
[Shell(28:28)]: 03710000 -- 0374ffff    00040000    RW   A    malloc: BigAllocationBlock
[Shell(28:28)]: 03760000 -- 0376ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 03780000 -- 0378ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[Shell(28:28)]: 037a0000 -- 037affff    00010000    RW   A    malloc: ChunkedBlock(128)
[Shell(28:28)]: 0f6d8000 -- 0f719fff    00042000    R XS      /usr/lib/Loader.so
[Shell(28:28)]: 0f71a000 -- 0f71ffff    00006000    RW   A    /usr/lib/Loader.so (data-rw)
[Shell(28:28)]: Kernel regions:
[Shell(28:28)]: BEGIN       END         SIZE        ACCESS  NAME
[Shell(28:28)]: c0801000 -- c0900fff    00100000    RW   A    kmalloc subheap
[Shell(28:28)]: c0904000 -- c0904fff    00001000    RW   A    HPET MMIO
[Shell(28:28)]: c0906000 -- c0906fff    00001000    R X  A    Signal trampolines
[Shell(28:28)]: c0908000 -- c0917fff    00010000    RW  TA    Kernel Stack (Thread 0)
[Shell(28:28)]: c092a000 -- c0939fff    00010000    RW  TA    Kernel Stack (Thread 2)
[Shell(28:28)]: c093b000 -- c094afff    00010000    RW  TA    Kernel Stack (Thread 3)
[Shell(28:28)]: c094c000 -- c094cfff    00001000     W        UHCI Framelist
[Shell(28:28)]: c094e000 -- c094ffff    00002000     W        UHCI Queue Head Pool
[Shell(28:28)]: c0951000 -- c0952fff    00002000     W        UHCI Transfer Descriptor Pool
[Shell(28:28)]: c0954000 -- c0963fff    00010000    RW  TA    Kernel Stack (Thread 4)
[Shell(28:28)]: c0965000 -- c0965fff    00001000    RW        E1000 RX
[Shell(28:28)]: c0967000 -- c0967fff    00001000    RW        E1000 TX
[Shell(28:28)]: c0969000 -- c0988fff    00020000    RW   A    E1000 MMIO
[Shell(28:28)]: c098a000 -- c098bfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c098d000 -- c098efff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c0990000 -- c0991fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c0993000 -- c0994fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c0996000 -- c0997fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c0999000 -- c099afff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c099c000 -- c099dfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c099f000 -- c09a0fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09a2000 -- c09a3fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09a5000 -- c09a6fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09a8000 -- c09a9fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09ab000 -- c09acfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09ae000 -- c09affff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09b1000 -- c09b2fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09b4000 -- c09b5fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09b7000 -- c09b8fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09ba000 -- c09bbfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09bd000 -- c09befff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09c0000 -- c09c1fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09c3000 -- c09c4fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09c6000 -- c09c7fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09c9000 -- c09cafff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09cc000 -- c09cdfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09cf000 -- c09d0fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09d2000 -- c09d3fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09d5000 -- c09d6fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09d8000 -- c09d9fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09db000 -- c09dcfff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09de000 -- c09dffff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09e1000 -- c09e2fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09e4000 -- c09e5fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09e7000 -- c09e8fff    00002000    RW        E1000 RX buffer
[Shell(28:28)]: c09ea000 -- c09ebfff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09ed000 -- c09eefff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09f0000 -- c09f1fff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09f3000 -- c09f4fff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09f6000 -- c09f7fff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09f9000 -- c09fafff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09fc000 -- c09fdfff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c09ff000 -- c0a00fff    00002000    RW        E1000 TX buffer
[Shell(28:28)]: c0a02000 -- c0a02fff    00001000    RW   A    Ext2FS: Block group descriptors
[Shell(28:28)]: c0a04000 -- c3113fff    02710000    RW   A    KBuffer
[Shell(28:28)]: c3115000 -- c314ffff    0003b000    RW   A    KBuffer
[Shell(28:28)]: c3151000 -- c3151fff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c3153000 -- c3153fff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c3155000 -- c3164fff    00010000    RW  TA    Kernel Stack (Thread 5)
[Shell(28:28)]: c3166000 -- c3166fff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c3168000 -- c3177fff    00010000    RW  TA    Kernel Stack (Thread 6)
[Shell(28:28)]: c3179000 -- c3188fff    00010000    RW   A    Kernel Packet Buffer
[Shell(28:28)]: c0919000 -- c0919fff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c091b000 -- c091bfff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c318a000 -- c31a9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c31ab000 -- c31cafff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c31cc000 -- c31ebfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c31ed000 -- c320cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c320e000 -- c322dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c322f000 -- c324efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3250000 -- c326ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3271000 -- c3290fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3292000 -- c32b1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c32b3000 -- c32d2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c32d4000 -- c32f3fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c32f5000 -- c3314fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3316000 -- c3335fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3337000 -- c3356fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3358000 -- c3377fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3379000 -- c3398fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c339a000 -- c33b9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c33bb000 -- c33dafff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c33dc000 -- c33fbfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c33fd000 -- c341cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c341e000 -- c343dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c343f000 -- c345efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3460000 -- c347ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3481000 -- c34a0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c34a2000 -- c34c1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c34c3000 -- c34d2fff    00010000    RW  TA    Kernel Stack (Thread 8)
[Shell(28:28)]: c34d4000 -- c34e3fff    00010000    RW  TA    Kernel Stack (Thread 9)
[Shell(28:28)]: c34e5000 -- c34f4fff    00010000    RW  TA    Kernel Stack (Thread 10)
[Shell(28:28)]: c34f6000 -- c3505fff    00010000    RW  TA    Kernel Stack (Thread 11)
[Shell(28:28)]: c3507000 -- c3516fff    00010000    RW  TA    Kernel Stack (Thread 12)
[Shell(28:28)]: c3518000 -- c3527fff    00010000    RW  TA    Kernel Stack (Thread 13)
[Shell(28:28)]: c3529000 -- c3538fff    00010000    RW  TA    Kernel Stack (Thread 14)
[Shell(28:28)]: c353a000 -- c3549fff    00010000    RW  TA    Kernel Stack (Thread 15)
[Shell(28:28)]: c354b000 -- c355afff    00010000    RW  TA    Kernel Stack (Thread 16)
[Shell(28:28)]: c355c000 -- c356bfff    00010000    RW  TA    Kernel Stack (Thread 17)
[Shell(28:28)]: c356d000 -- c357cfff    00010000    RW  TA    Kernel Stack (Thread 18)
[Shell(28:28)]: c357e000 -- c358dfff    00010000    RW  TA    Kernel Stack (Thread 19)
[Shell(28:28)]: c358f000 -- c359efff    00010000    RW  TA    Kernel Stack (Thread 20)
[Shell(28:28)]: c35a0000 -- c35affff    00010000    RW  TA    Kernel Stack (Thread 21)
[Shell(28:28)]: c35b1000 -- c35c0fff    00010000    RW  TA    Kernel Stack (Thread 22)
[Shell(28:28)]: c35c2000 -- c35d1fff    00010000    RW  TA    Kernel Stack (Thread 23)
[Shell(28:28)]: c35d3000 -- c35f2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c35f4000 -- c3613fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3615000 -- c3634fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3636000 -- c3645fff    00010000    RW  TA    Kernel Stack (Thread 24)
[Shell(28:28)]: c3647000 -- c3666fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3668000 -- c3687fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3689000 -- c36a8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c36aa000 -- c36c9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c36cb000 -- c36eafff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c36ec000 -- c370bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c370d000 -- c372cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c372e000 -- c374dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c374f000 -- c376efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3770000 -- c378ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3791000 -- c37b0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c37b2000 -- c37d1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c37d3000 -- c37f2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c37f4000 -- c3813fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3815000 -- c3834fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3836000 -- c3855fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3857000 -- c3876fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3878000 -- c3897fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3899000 -- c38b8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c38ba000 -- c38d9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c38db000 -- c38fafff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c38fc000 -- c391bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c391d000 -- c393cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c393e000 -- c395dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c395f000 -- c397efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3980000 -- c399ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c39a1000 -- c39c0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c39c2000 -- c39e1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c39e3000 -- c3a02fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3a04000 -- c3a23fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3a25000 -- c3a44fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3a46000 -- c3a65fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3a67000 -- c3a86fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3a88000 -- c3aa7fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3aa9000 -- c3ac8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3aca000 -- c3ae9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3aeb000 -- c3b0afff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3b0c000 -- c3b2bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3b2d000 -- c3b4cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3b4e000 -- c3b6dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3b6f000 -- c3b8efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3b90000 -- c3baffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3bb1000 -- c3bd0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3bd2000 -- c3bf1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3bf3000 -- c3c12fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3c14000 -- c3c33fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3c35000 -- c3c54fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3c56000 -- c3c75fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3c77000 -- c3c96fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3c98000 -- c3cb7fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3cb9000 -- c3cd8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3cda000 -- c3cf9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c3cfb000 -- c40fafff    00400000    RW   A    KBuffer
[Shell(28:28)]: c40fc000 -- c411bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c411d000 -- c413cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c091f000 -- c091ffff    00001000    RW   A    KBuffer
[Shell(28:28)]: c413e000 -- c415dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c415f000 -- c417efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4180000 -- c419ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c41a1000 -- c41c0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c41c2000 -- c41e1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c41e3000 -- c4202fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4204000 -- c4223fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4225000 -- c4244fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4246000 -- c4265fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4267000 -- c4286fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4288000 -- c42a7fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c42a9000 -- c42c8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c42ca000 -- c42e9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c42eb000 -- c430afff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c430c000 -- c432bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c432d000 -- c434cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c434e000 -- c436dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c436f000 -- c437efff    00010000    RW  TA    Kernel Stack (Thread 25)
[Shell(28:28)]: c4391000 -- c43b0fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c43b2000 -- c43d1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c43d3000 -- c43f2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c43f4000 -- c4413fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4415000 -- c4434fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4436000 -- c4455fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4457000 -- c4476fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c0921000 -- c0921fff    00001000    RW   A    Ext2FS: Cached bitmap block
[Shell(28:28)]: c4478000 -- c4497fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4499000 -- c44b8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c44ba000 -- c44d9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c44db000 -- c44fafff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c44fc000 -- c451bfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c451d000 -- c453cfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c453e000 -- c455dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c455f000 -- c457efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4580000 -- c459ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c49a2000 -- c49c1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c49c3000 -- c49e2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c49e4000 -- c4a03fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4a05000 -- c4a24fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4a26000 -- c4a45fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4a89000 -- c4aa8fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4aaa000 -- c4ac9fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4acb000 -- c4adafff    00010000    RW  TA    Kernel Stack (Thread 27)
[Shell(28:28)]: c4adc000 -- c4bdbfff    00100000    RW   A    kmalloc subheap
[Shell(28:28)]: c4bdd000 -- c4bfcfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4bfe000 -- c4c1dfff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4c1f000 -- c4c3efff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4c40000 -- c4c5ffff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4c61000 -- c4c80fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4c82000 -- c4ca1fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4ca3000 -- c4cc2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4cc4000 -- c4ce3fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4ce5000 -- c4d04fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4d06000 -- c5105fff    00400000    RW   A    KBuffer
[Shell(28:28)]: c5107000 -- c5506fff    00400000    RW   A    KBuffer
[Shell(28:28)]: c45c2000 -- c45d1fff    00010000    RW  TA    Kernel Stack (Thread 28)
[Shell(28:28)]: c45d3000 -- c45f2fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c45f4000 -- c4613fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: c4615000 -- c4634fff    00020000    RW   A    DoubleBuffer
[Shell(28:28)]: Shell(28:28) Should already die
[FinalizerTask(3:3)]: Generating coredump for pid: 28
[FinalizerTask(3:3)]: RTC: Year: 2021, month: 1, day: 16, hour: 15, minute: 20, second: 24
Shell(25): Job entry "./test.sh" deleted in 1280 ms
CrashDaemon(20): New coredump file: /tmp/coredump/Shell_28_1610810424
CrashDaemon(20): --- Backtrace for thread #0 (TID 28) ---
CrashDaemon(20): 0x02b27c93: [libc.so] AK::FormatBuilder::put_u64(unsigned long long, unsigned char, bool, bool, bool, AK::FormatBuilder::Align, unsigned long, char, AK::FormatBuilder::SignMode, bool) +0x10b (Format.cpp:64)
CrashDaemon(20): 0x02b29bb5: [libc.so] AK::Formatter<unsigned long, void>::format(AK::FormatBuilder&, unsigned long) +0x205 (Format.cpp:584)
CrashDaemon(20): 0x02b0c426: [libc.so] void AK::__format_value<unsigned long>(AK::TypeErasedFormatParams&, AK::FormatBuilder&, AK::FormatParser&, void const*) +0x83 (Format.h:217)
CrashDaemon(20): 0x02b27a38: [libc.so] AK::(anonymous namespace)::vformat_impl(AK::TypeErasedFormatParams&, AK::FormatBuilder&, AK::FormatParser&) +0xf3 (Format.cpp:96)
CrashDaemon(20): 0x02b281c7: [libc.so] AK::vformat(AK::StringBuilder&, AK::StringView, AK::TypeErasedFormatParams) +0x52 (Format.cpp:416)
CrashDaemon(20): 0x02b30a97: [libc.so] AK::String::vformatted(AK::StringView, AK::TypeErasedFormatParams) +0x8b (String.cpp:469)
CrashDaemon(20): 0x02c4aad8: [libshell.so] Shell::Parser::parse_expression() +0xe6 (Parser.cpp:1058)
CrashDaemon(20): 0x02c4cacf: [libshell.so] Shell::Parser::parse_list_expression() +0x8d (Parser.cpp:1043)
CrashDaemon(20): 0x02c4cde8: [libshell.so] Shell::Parser::parse_command() +0xb0 (Parser.cpp:499)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
CrashDaemon(20): 0x02c4ce7d: [libshell.so] Shell::Parser::parse_command() +0x145 (Parser.cpp:505)
[...repeated 1,500 times...]
```

### PR DESCRIPTION
**Pull request by alimpfard**
This fixes #4976.

Task lists? never heard of 'em.

### CODE REVIEW

File: Userland/Shell/Shell.cpp [hunk 1]
```diff
@@ -1075,17 +1075,21 @@ void Shell::block_on_job(RefPtr<Job> job)
...
 
     if (job->exited())
         return;
 
-    loop.exec();
+    bool expected = true;
+    while (!job_exited.compare_exchange_strong(expected, false, AK::MemoryOrder::memory_order_acq_rel)) {
+        expected = true;
+        Core::EventLoop::current().yield();
+    }
```
Comment (alimpfard) [inline Userland/Shell/Shell.cpp:1092]: inb4:
\<kling\> wait that's not how that's supposed to be used

**Comment by alimpfard** [comment]
🤔 okay I managed to confuse myself - how does this work?

**Comment by alimpfard** [comment]
The test seems to take about 20 seconds, I'm not sure if it's worth running on CI...

**Comment by alimpfard** [comment]
Nevermind the test. we can add a test when it doesn't take 23 seconds to run.

File: Userland/Shell/Shell.cpp [hunk 2]
```diff
@@ -1079,17 +1079,18 @@ void Shell::block_on_job(RefPtr<Job> job)
...
-        loop.quit(0);
+        job_exited = true;
     };
 
     if (job->exited())
         return;
 
-    loop.exec();
+    while (!job_exited)
+        Core::EventLoop::current().yield();
```
Comment (awesomekling) [inline Userland/Shell/Shell.cpp:1095]: `pump()` would be a better fit here IMO. "Pumping the event loop" is a well-understood concept, but "yielding the event loop" is not (at least to me :)

Comment (alimpfard) [reply Userland/Shell/Shell.cpp:1095]: Ah, if that's already a known good term here, I'll use that.
the comment above `pump()` really threw me off, it seems
