### PR TITLE
Kernel & WindowServer: Validate the changed framebuffer resolution in BXVGA device

### LINKED ISSUE #451: WindowServer: Setting resolution to 1366x768 causes extreme distortion
Setting the resolution to either 800x600 or 1024x768 works, but when I attempt to set it to 1366x768, the WindowServer seems to page fault, resulting in a black screen.
```
BXVGA: WindowServer(8) created Region{0x00373428} with size 8392704 for framebuffer Pf0000000 with vaddr L01b2f000
WindowServer(8) Couldn't find user region for V0x02330000
NP(error) fault at invalid address L02330000
WindowServer(8:0) Unrecoverable page fault, write to address 0x02330000
CRASH: Page Fault Process: WindowServer(8)
exception code: 0006
  pc=001b:08066d4a ds=0023 es=0023 fs=0023 gs=0023
 stk=0023:01101c20
kstk=0010:c0041000, base=c0031000, sigbase=00000000
eax=ff323232 ebx=00000001 ecx=000000a6 edx=0232ed40
ebp=01101f08 esp=01101c20 esi=00001560 edi=02330000
code: f3 ab 83 eb 01 01 f2 83
0x08066d4a  _ZN7Painter9fill_rectERK4Rect5Color +330
0x0001fc6d  Process::crash(int, unsigned int) +153
0x0001a33e  exception_13_handler +0
0x0001a43d  exception_14_handler +239
0x00019769  exception_14_entry +38
0x0805a39e  _ZN12WSCompositor14set_resolutionEii +350
0x0804b1f6  _ZN15WSWindowManager14set_resolutionEii +30
0x0804be29  _ZN15WSWindowManager13reload_configEb +399
0x0804f985  _ZN6WSMenu12did_activateER10WSMenuItem +33
0x08050427  _ZN6WSMenu5eventER6CEvent +135
0x080492de  _ZN8WSWindow5eventER6CEvent +34
0x0804dd83  _ZN15WSWindowManager19deliver_mouse_eventER8WSWindowR12WSMouseEvent +25
0x0804e3e8  _ZN15WSWindowManager19process_mouse_eventER12WSMouseEventRP8WSWindow +786
0x0804e733  _ZN15WSWindowManager5eventER6CEvent +47
0x0805cc15  _ZN10CEventLoop4pumpENS_8WaitModeE +459
0x0805cd9f  _ZN10CEventLoop4execEv +43
0x080484a2  main +397
0x080486c4  _start +89
Process WindowServer(8) regions:
BEGIN       END         SIZE        ACCESS  NAME
01000000 -- 010f2fff    000f3000    R       /bin/WindowServer
08048000 -- 080acfff    00065000    R X     elf-map-rx
080ad000 -- 080affff    00003000    RW      elf-alloc-rw
010f3000 -- 01102fff    00010000    RW      Stack (Main thread)
01103000 -- 01103fff    00001000    RW      malloc: BigAllocationBlock
01104000 -- 01104fff    00001000    RW      malloc: ChunkedBlock(16)
01105000 -- 01105fff    00001000    RW      malloc: ChunkedBlock(32)
01106000 -- 01106fff    00001000    RW      malloc: ChunkedBlock(64)
01107000 -- 01107fff    00001000    RW      malloc: ChunkedBlock(8)
01108000 -- 01108fff    00001000    RW      malloc: ChunkedBlock(2036)
01109000 -- 01109fff    00001000    RW      malloc: ChunkedBlock(2036)
0110a000 -- 0110afff    00001000    RW      malloc: ChunkedBlock(1016)
0110b000 -- 0110bfff    00001000    RW      malloc: ChunkedBlock(128)
0110c000 -- 0110cfff    00001000    RW      malloc: ChunkedBlock(508)
0110d000 -- 0110dfff    00001000    RW      malloc: ChunkedBlock(252)
014b8000 -- 014bafff    00003000    R       /res/fonts/Katica10.font
017bb000 -- 017cafff    00010000    RW      Stack (Thread 1)
017ce000 -- 017cefff    00001000    RW      malloc: ChunkedBlock(32)
017cf000 -- 017cffff    00001000    RW      malloc: ChunkedBlock(32)
017d0000 -- 017d0fff    00001000    RW      malloc: ChunkedBlock(32)
017d1000 -- 017d1fff    00001000    RW      malloc: ChunkedBlock(32)
017d2000 -- 017d2fff    00001000    RW      malloc: ChunkedBlock(252)
017d3000 -- 017d3fff    00001000    RW      malloc: ChunkedBlock(32)
017d4000 -- 017d4fff    00001000    RW      malloc: ChunkedBlock(32)
017cb000 -- 017cbfff    00001000    RW      malloc: ChunkedBlock(128)
017cd000 -- 017cdfff    00001000    RW      malloc: ChunkedBlock(64)
017de000 -- 017defff    00001000    RW      GraphicsBitmap [16x16] - Decoded PNG: /res/icons/16x16/window.png
017df000 -- 017edfff    0000f000    RW      GraphicsBitmap [800x18]
017ee000 -- 017f0fff    00003000    R       /res/fonts/KaticaBold10.font
017f1000 -- 01809fff    00019000    RW      SharedBuffer
017d5000 -- 017d5fff    00001000    RW      malloc: ChunkedBlock(1016)
017d7000 -- 017d7fff    00001000    R       SharedBuffer
01836000 -- 018fafff    000c5000    RW      SharedBuffer
018fd000 -- 018fdfff    00001000    RW      malloc: ChunkedBlock(32)
018fe000 -- 01916fff    00019000    RW      SharedBuffer
018fc000 -- 018fcfff    00001000    RW      malloc: ChunkedBlock(1016)
01b1a000 -- 01b1afff    00001000    RW      malloc: ChunkedBlock(64)
018fb000 -- 018fbfff    00001000    R       SharedBuffer
01917000 -- 01a10fff    000fa000    RW      SharedBuffer
01a12000 -- 01b0bfff    000fa000    RW      SharedBuffer
01b1b000 -- 01b2efff    00014000    RW      GraphicsBitmap [156x127]
01118000 -- 01133fff    0001c000    RW      SharedBuffer
01134000 -- 0114ffff    0001c000    RW      SharedBuffer
01150000 -- 01150fff    00001000    RW      GraphicsBitmap [15x21] - Decoded PNG: /res/cursors/arrow.png
01151000 -- 01151fff    00001000    RW      GraphicsBitmap [23x13] - Decoded PNG: /res/cursors/resize-horizontal.png
01110000 -- 01110fff    00001000    RW      GraphicsBitmap [13x23] - Decoded PNG: /res/cursors/resize-vertical.png
01111000 -- 01111fff    00001000    RW      GraphicsBitmap [21x21] - Decoded PNG: /res/cursors/resize-diagonal-tlbr.png
01112000 -- 01112fff    00001000    RW      GraphicsBitmap [21x21] - Decoded PNG: /res/cursors/resize-diagonal-bltr.png
01113000 -- 01113fff    00001000    RW      GraphicsBitmap [7x21] - Decoded PNG: /res/cursors/i-beam.png
01114000 -- 01114fff    00001000    RW      GraphicsBitmap [21x21] - Decoded PNG: /res/cursors/disallowed.png
01115000 -- 01115fff    00001000    RW      GraphicsBitmap [25x25] - Decoded PNG: /res/cursors/move.png
01b2f000 -- 0232ffff    00801000    RW      BXVGA Framebuffer
Finalizing Thread 1 in WindowServer(8)
~Thread{0x00339528}
Finalizing Thread 0 in WindowServer(8)
Finalizing Process WindowServer(8)
signal 17 was ignored by SystemServer(5)
```

### PR DESCRIPTION
**Pull request by supercomputer7**
Fixes #451.

### CODE REVIEW

File: Kernel/Devices/BXVGADevice.cpp [hunk 1]
```diff
@@ -91,6 +97,21 @@ void BXVGADevice::set_resolution(int width, int height)
     set_register(VBE_DISPI_INDEX_BANK, 0);
 
     dbg() << "BXVGADevice resolution set to " << m_framebuffer_width << "x" << m_framebuffer_height << " (pitch=" << m_framebuffer_pitch << ")";
+
+    if (!validate_setup_resolution(width, height)) {
+        m_framebuffer_width = get_register(VBE_DISPI_INDEX_XRES);
+        m_framebuffer_height = get_register(VBE_DISPI_INDEX_YRES);
+        m_framebuffer_pitch = get_register(VBE_DISPI_INDEX_XRES) * sizeof(u32);
```
Comment (Quaker762) [inline Kernel/Devices/BXVGADevice.cpp]: Let's minimise a call to `get_register()` here.

```cpp
 m_framebuffer_pitch = m_framebuffer_width * sizeof(u32)
```

File: Servers/WindowServer/WindowManager.h [hunk 2]
```diff
@@ -141,7 +141,9 @@ class WindowManager : public Core::Object {
     const Gfx::Font& font() const;
     const Gfx::Font& window_title_font() const;
 
-    void set_resolution(int width, int height);
+    bool set_resolution(int width, int height);
+    int get_resolution_width();
+    int get_resolution_height();
```
Comment (awesomekling) [inline Servers/WindowServer/WindowManager.h]: Please refrain from using `get_` prefixes in API's. Also it should be `const` as it does not mutate state.
I would also suggest using a `Gfx::Size` as the return type:

```cpp
Gfx::Size resolution() const;
```

File: Servers/WindowServer/WindowServer.ipc [hunk 3]
```diff
@@ -74,7 +74,7 @@ endpoint WindowServer = 2
     DismissMenu(i32 menu_id) => ()
 
     AsyncSetWallpaper(String path) =|
-    SetResolution(Gfx::Size resolution) => ()
+    SetResolution(Gfx::Size resolution) => (bool success, int width, int height)
```
Comment (awesomekling) [inline Servers/WindowServer/WindowServer.ipc]: Please use a `Gfx::Size` instead of separate width and height variables in the response.

File: Servers/WindowServer/WindowManager.cpp [hunk 4]
```diff
@@ -132,19 +132,32 @@ const Gfx::Font& WindowManager::window_title_font() const
...
+            m_wm_config->write_num_entry("Screen", "Height", resolution().height());
+            m_wm_config->sync();
+        }
     }
+    return success;
+}
+
+Gfx::Size WindowManager::resolution() const
+{
+    return { Screen::the().width(), Screen::the().height() };
```
Comment (awesomekling) [inline Servers/WindowServer/WindowManager.cpp]:
```suggestion
    return Screen::the().size();
```
