### PR TITLE
Make UserspaceEmulator emulate again!

### LINKED ISSUE #5663: UserspaceEmulator: virt$mprotect: ASSERTION FAILED: region->size() == size
Running any program with UserspaceEmulator results in a failed assertion in `virt$mprotect` :

```
UserspaceEmulator(32): interpreter: /usr/lib/Loader.so
UserspaceEmulator(32): USERSPACE(32) ASSERTION FAILED: region->size() == size
../Userland/DevTools/UserspaceEmulator/Emulator.cpp:1092
[#0 (UE) ls(32:32)]: 0x00000000  (?)

[#0 (UE) ls(32:32)]: 0xc0366965  Kernel::Process::crash(int, unsigned int, bool) +0x3df
[#0 (UE) ls(32:32)]: 0xc038ad61  Kernel::Process::sys$abort() +0x3d
[#0 (UE) ls(32:32)]: 0xc0386453  syscall_handler +0x188a
[#0 (UE) ls(32:32)]: 0xc0384b91  syscall_asm_entry +0x31
[#0 (UE) ls(32:32)]: Process regions:
[#0 (UE) ls(32:32)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 (UE) ls(32:32)]: 02001000 -- 02100fff 00100000 RW  T  Stack (Main thread)
[#0 (UE) ls(32:32)]: 02102000 -- 02102fff 00001000 R XS C Signal trampoline
[#0 (UE) ls(32:32)]: 02104000 -- 0210afff 00007000 R      ELF_DYN: libcrypt.so (Emulated)
[#0 (UE) ls(32:32)]: 0210c000 -- 0210dfff 00002000 R      ELF_DYN: libsystem.so (Emulated)
[#0 (UE) ls(32:32)]: 02110000 -- 0211ffff 00010000        malloc: ChunkedBlock(256)
[#0 (UE) ls(32:32)]: 02121000 -- 02121fff 00001000 R XS   libsystem.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 02123000 -- 02125fff 00003000 R  S   libm.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 02129000 -- 02129fff 00001000 RW     
[#0 (UE) ls(32:32)]: 0212b000 -- 0212cfff 00002000 RW     Thread-specific
[#0 (UE) ls(32:32)]: 02130000 -- 0213ffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 (UE) ls(32:32)]: 02141000 -- 02147fff 00007000 R      ELF_DYN: libm.so (Emulated)
[#0 (UE) ls(32:32)]: 02149000 -- 0214afff 00002000 R  S   libcrypt.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 02150000 -- 0215ffff 00010000 RW     malloc: ChunkedBlock(8)
[#0 (UE) ls(32:32)]: 02161000 -- 02169fff 00009000 R  S   /bin/ls: .text (Emulated)
[#0 (UE) ls(32:32)]: 02170000 -- 0217ffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 (UE) ls(32:32)]: 02190000 -- 0219ffff 00010000 RW     malloc: ChunkedBlock(32)
[#0 (UE) ls(32:32)]: 021b0000 -- 021bffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 (UE) ls(32:32)]: 021d0000 -- 021dffff 00010000 RW     malloc: ChunkedBlock(8184)
[#0 (UE) ls(32:32)]: 021e1000 -- 02203fff 00023000 R      ELF_DYN: /bin/ls (Emulated)
[#0 (UE) ls(32:32)]: 02210000 -- 0221ffff 00010000 RW     malloc: ChunkedBlock(16)
[#0 (UE) ls(32:32)]: 02230000 -- 0229ffff 00070000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 022b0000 -- 0231ffff 00070000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02330000 -- 0233ffff 00010000 RW     malloc: ChunkedBlock(256)
[#0 (UE) ls(32:32)]: 02357000 -- 02357fff 00001000 R      mmap
[#0 (UE) ls(32:32)]: 02360000 -- 0236ffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 (UE) ls(32:32)]: 02380000 -- 0238ffff 00010000 RW     malloc: ChunkedBlock(256)
[#0 (UE) ls(32:32)]: 023a0000 -- 023affff 00010000 RW     malloc: ChunkedBlock(32)
[#0 (UE) ls(32:32)]: 023c0000 -- 026cffff 00310000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 026e0000 -- 026fffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02710000 -- 0272ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02740000 -- 0275ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02770000 -- 0278ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 027a0000 -- 027bffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 027d0000 -- 027effff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02800000 -- 0282ffff 00030000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02840000 -- 0285ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02861000 -- 02878fff 00018000 R XS   libgcc_s.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 02880000 -- 0289ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 028b0000 -- 028cffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 028e0000 -- 028effff 00010000 RW     malloc: ChunkedBlock(32752)
[#0 (UE) ls(32:32)]: 02900000 -- 0290ffff 00010000        malloc: ChunkedBlock(500)
[#0 (UE) ls(32:32)]: 02920000 -- 0293ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02950000 -- 0296ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02980000 -- 0298ffff 00010000 RW     malloc: ChunkedBlock(500)
[#0 (UE) ls(32:32)]: 029a0000 -- 029bffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 029d0000 -- 02a4ffff 00080000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02a51000 -- 02accfff 0007c000 R      ELF_DYN: libgcc_s.so (Emulated)
[#0 (UE) ls(32:32)]: 02ad0000 -- 02c3ffff 00170000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02c41000 -- 02da6fff 00166000 R      ELF_DYN: libcore.so (Emulated)
[#0 (UE) ls(32:32)]: 02db0000 -- 02e1ffff 00070000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 02e21000 -- 02e8afff 0006a000 R      ELF_DYN: libcrypto.so (Emulated)
[#0 (UE) ls(32:32)]: 02e90000 -- 0308ffff 00200000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 03091000 -- 03286fff 001f6000 R      ELF_DYN: libc.so (Emulated)
[#0 (UE) ls(32:32)]: 03290000 -- 0329ffff 00010000 RW     malloc: ChunkedBlock(16376)
[#0 (UE) ls(32:32)]: 032b0000 -- 032bffff 00010000        malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 032d0000 -- 032dffff 00010000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 032f0000 -- 0330ffff 00020000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 03320000 -- 0332ffff 00010000 RW     malloc: ChunkedBlock(16376)
[#0 (UE) ls(32:32)]: 03340000 -- 0334ffff 00010000 RW     malloc: ChunkedBlock(8184)
[#0 (UE) ls(32:32)]: 03360000 -- 0336ffff 00010000        malloc: ChunkedBlock(32752)
[#0 (UE) ls(32:32)]: 03380000 -- 0340ffff 00090000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 03411000 -- 03496fff 00086000 R  S   libc.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 034a0000 -- 034cffff 00030000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 034d1000 -- 034f1fff 00021000 R  S   libcrypto.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 03500000 -- 0350ffff 00010000 RW     malloc: ChunkedBlock(16376)
[#0 (UE) ls(32:32)]: 03520000 -- 0356ffff 00050000 RW     malloc: BigAllocationBlock
[#0 (UE) ls(32:32)]: 03571000 -- 035bbfff 0004b000 R  S   libcore.so: .text (Emulated)
[#0 (UE) ls(32:32)]: 035c0000 -- 035cffff 00010000 RW     malloc: ChunkedBlock(16376)
[#0 (UE) ls(32:32)]: 03690000 -- 0369ffff 00010000        malloc: ChunkedBlock(1016)
[#0 (UE) ls(32:32)]: 06ac8000 -- 06acafff 00003000 R XS   libm.so: .text
[#0 (UE) ls(32:32)]: 06acb000 -- 06acbfff 00001000 R      libm.so: .relro
[#0 (UE) ls(32:32)]: 06d4c000 -- 06d4ffff 00004000 R XS   libpthread.so: .text
[#0 (UE) ls(32:32)]: 06d50000 -- 06d50fff 00001000 R      libpthread.so: .relro
[#0 (UE) ls(32:32)]: 06d51000 -- 06d51fff 00001000 RW     libpthread.so: .data
[#0 (UE) ls(32:32)]: 0ecfe000 -- 0ed64fff 00067000 R XS   /usr/lib/Loader.so
[#0 (UE) ls(32:32)]: 0ed66000 -- 0ed67fff 00002000 RW     /usr/lib/Loader.so (data-rw)
[#0 (UE) ls(32:32)]: 3682f000 -- 36846fff 00018000 R XS   libgcc_s.so: .text
[#0 (UE) ls(32:32)]: 36847000 -- 36847fff 00001000 RW     libgcc_s.so: .data
[#0 (UE) ls(32:32)]: 45066000 -- 45067fff 00002000 R XS   libcrypt.so: .text
[#0 (UE) ls(32:32)]: 45068000 -- 45068fff 00001000 R      libcrypt.so: .relro
[#0 (UE) ls(32:32)]: 45069000 -- 45069fff 00001000 RW     libcrypt.so: .data
[#0 (UE) ls(32:32)]: 7a347000 -- 7a347fff 00001000 R XS C libsystem.so: .text
[#0 (UE) ls(32:32)]: 7a348000 -- 7a348fff 00001000 R      libsystem.so: .relro
[#0 (UE) ls(32:32)]: 7ae34000 -- 7ae42fff 0000f000 R XS   libx86.so: .text
[#0 (UE) ls(32:32)]: 7ae43000 -- 7ae43fff 00001000 R      libx86.so: .relro
[#0 (UE) ls(32:32)]: 7ae44000 -- 7ae4efff 0000b000 RW     libx86.so: .data
[#0 (UE) ls(32:32)]: 7ba1a000 -- 7ba64fff 0004b000 R XS   libcore.so: .text
[#0 (UE) ls(32:32)]: 7ba65000 -- 7ba66fff 00002000 R      libcore.so: .relro
[#0 (UE) ls(32:32)]: 7ba67000 -- 7ba67fff 00001000 RW     libcore.so: .data
[#0 (UE) ls(32:32)]: 9dea4000 -- 9df29fff 00086000 R XS   libc.so: .text
[#0 (UE) ls(32:32)]: 9df2b000 -- 9df2cfff 00002000 R      libc.so: .relro
[#0 (UE) ls(32:32)]: 9df2d000 -- 9df2dfff 00001000 RW     libc.so: .data
[#0 (UE) ls(32:32)]: 9e7a3000 -- 9e7dafff 00038000 R XS   libregex.so: .text
[#0 (UE) ls(32:32)]: 9e7db000 -- 9e7dbfff 00001000 R      libregex.so: .relro
[#0 (UE) ls(32:32)]: 9e7dc000 -- 9e7dcfff 00001000 RW     libregex.so: .data
[#0 (UE) ls(32:32)]: a96ee000 -- a9706fff 00019000 R XS   libdebug.so: .text
[#0 (UE) ls(32:32)]: a9707000 -- a9707fff 00001000 R      libdebug.so: .relro
[#0 (UE) ls(32:32)]: a9708000 -- a9708fff 00001000 RW     libdebug.so: .data
[#0 (UE) ls(32:32)]: ab655000 -- ab675fff 00021000 R XS   libcrypto.so: .text
[#0 (UE) ls(32:32)]: ab676000 -- ab676fff 00001000 R      libcrypto.so: .relro
[#0 (UE) ls(32:32)]: ab677000 -- ab677fff 00001000 RW     libcrypto.so: .data
[#0 (UE) ls(32:32)]: bd3f6000 -- bd48efff 00099000 R XS   /bin/UserspaceEmulator: .text
[#0 (UE) ls(32:32)]: bd490000 -- bd490fff 00001000 R      /bin/UserspaceEmulator: .relro
[#0 (UE) ls(32:32)]: bd491000 -- bd491fff 00001000 RW     /bin/UserspaceEmulator: .data
[#0 (UE) ls(32:32)]: Kernel regions:
[#0 (UE) ls(32:32)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 (UE) ls(32:32)]: c1001000 -- c1100fff 00100000 RW     kmalloc subheap
[#0 (UE) ls(32:32)]: c1104000 -- c1104fff 00001000 RW     HPET MMIO
[#0 (UE) ls(32:32)]: c1106000 -- c1106fff 00001000 R    C Signal trampolines
[#0 (UE) ls(32:32)]: c1108000 -- c1117fff 00010000 RW  T  Kernel stack (thread 0)
[#0 (UE) ls(32:32)]: c112a000 -- c1139fff 00010000 RW  T  Kernel stack (thread 2)
[#0 (UE) ls(32:32)]: c113b000 -- c114afff 00010000 RW  T  Kernel stack (thread 3)
[#0 (UE) ls(32:32)]: c114c000 -- c114cfff 00001000  W     UHCI Framelist
[#0 (UE) ls(32:32)]: c114e000 -- c114ffff 00002000  W     UHCI Queue Head Pool
[#0 (UE) ls(32:32)]: c1151000 -- c1152fff 00002000  W     UHCI Transfer Descriptor Pool
[#0 (UE) ls(32:32)]: c1154000 -- c1163fff 00010000 RW  T  Kernel stack (thread 4)
[#0 (UE) ls(32:32)]: c1165000 -- c1165fff 00001000 RW     E1000 RX
[#0 (UE) ls(32:32)]: c1167000 -- c1167fff 00001000 RW     E1000 TX
[#0 (UE) ls(32:32)]: c1169000 -- c1188fff 00020000 RW     E1000 MMIO
[#0 (UE) ls(32:32)]: c118a000 -- c118bfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c118d000 -- c118efff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c1190000 -- c1191fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c1193000 -- c1194fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c1196000 -- c1197fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c1199000 -- c119afff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c119c000 -- c119dfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c119f000 -- c11a0fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11a2000 -- c11a3fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11a5000 -- c11a6fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11a8000 -- c11a9fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11ab000 -- c11acfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11ae000 -- c11affff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11b1000 -- c11b2fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11b4000 -- c11b5fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11b7000 -- c11b8fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11ba000 -- c11bbfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11bd000 -- c11befff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11c0000 -- c11c1fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11c3000 -- c11c4fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11c6000 -- c11c7fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11c9000 -- c11cafff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11cc000 -- c11cdfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11cf000 -- c11d0fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11d2000 -- c11d3fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11d5000 -- c11d6fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11d8000 -- c11d9fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11db000 -- c11dcfff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11de000 -- c11dffff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11e1000 -- c11e2fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11e4000 -- c11e5fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11e7000 -- c11e8fff 00002000 RW     E1000 RX buffer
[#0 (UE) ls(32:32)]: c11ea000 -- c11ebfff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11ed000 -- c11eefff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11f0000 -- c11f1fff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11f3000 -- c11f4fff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11f6000 -- c11f7fff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11f9000 -- c11fafff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11fc000 -- c11fdfff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c11ff000 -- c1200fff 00002000 RW     E1000 TX buffer
[#0 (UE) ls(32:32)]: c1202000 -- c1203fff 00002000 RW     AHCI HBA
[#0 (UE) ls(32:32)]: c1205000 -- c1205fff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c1207000 -- c1207fff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c1209000 -- c1209fff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c120b000 -- c120bfff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c120d000 -- c120dfff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c120f000 -- c120ffff 00001000 RW     AHCI Port Command List
[#0 (UE) ls(32:32)]: c1211000 -- c1211fff 00001000 RW     Ext2FS: Block group descriptors
[#0 (UE) ls(32:32)]: c1213000 -- c3922fff 02710000 RW     KBuffer
[#0 (UE) ls(32:32)]: c3924000 -- c395efff 0003b000 RW     KBuffer
[#0 (UE) ls(32:32)]: c3960000 -- c3960fff 00001000 RW     Ext2FS: Cached bitmap block
[#0 (UE) ls(32:32)]: c3962000 -- c3962fff 00001000 RW     Ext2FS: Cached bitmap block
[#0 (UE) ls(32:32)]: c3964000 -- c3973fff 00010000 RW  T  Kernel stack (thread 5)
[#0 (UE) ls(32:32)]: c3975000 -- c3984fff 00010000 RW  T  Kernel stack (thread 6)
[#0 (UE) ls(32:32)]: c3986000 -- c3995fff 00010000 RW     Kernel Packet Buffer
[#0 (UE) ls(32:32)]: c1119000 -- c1119fff 00001000 RW     Ext2FS: Cached bitmap block
[#0 (UE) ls(32:32)]: c3997000 -- c39b6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c39b8000 -- c39d7fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c39d9000 -- c39f8fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c39fa000 -- c3a19fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3a1b000 -- c3a3afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3a3c000 -- c3a5bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3a5d000 -- c3a7cfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3a7e000 -- c3a9dfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3a9f000 -- c3abefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ac0000 -- c3adffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ae1000 -- c3b00fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3b02000 -- c3b21fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3b23000 -- c3b42fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3b44000 -- c3b63fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3b65000 -- c3b84fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3b86000 -- c3ba5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ba7000 -- c3bc6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3bc8000 -- c3be7fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3be9000 -- c3c08fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3c0a000 -- c3c29fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3c2b000 -- c3c4afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3c4c000 -- c3c6bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3c6d000 -- c3c8cfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3c8e000 -- c3cadfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3caf000 -- c3ccefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3cd0000 -- c3ceffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3cf1000 -- c3d10fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3d12000 -- c3d21fff 00010000 RW  T  Kernel stack (thread 8)
[#0 (UE) ls(32:32)]: c3d23000 -- c3d32fff 00010000 RW  T  Kernel stack (thread 9)
[#0 (UE) ls(32:32)]: c3d34000 -- c3d43fff 00010000 RW  T  Kernel stack (thread 10)
[#0 (UE) ls(32:32)]: c3d45000 -- c3d54fff 00010000 RW  T  Kernel stack (thread 11)
[#0 (UE) ls(32:32)]: c3d56000 -- c3d65fff 00010000 RW  T  Kernel stack (thread 12)
[#0 (UE) ls(32:32)]: c3d67000 -- c3d76fff 00010000 RW  T  Kernel stack (thread 13)
[#0 (UE) ls(32:32)]: c3d78000 -- c3d87fff 00010000 RW  T  Kernel stack (thread 14)
[#0 (UE) ls(32:32)]: c3d89000 -- c3d98fff 00010000 RW  T  Kernel stack (thread 15)
[#0 (UE) ls(32:32)]: c3d9a000 -- c3da9fff 00010000 RW  T  Kernel stack (thread 16)
[#0 (UE) ls(32:32)]: c3dab000 -- c3dbafff 00010000 RW  T  Kernel stack (thread 17)
[#0 (UE) ls(32:32)]: c3dbc000 -- c3dcbfff 00010000 RW  T  Kernel stack (thread 18)
[#0 (UE) ls(32:32)]: c3dcd000 -- c3ddcfff 00010000 RW  T  Kernel stack (thread 19)
[#0 (UE) ls(32:32)]: c3dde000 -- c3dedfff 00010000 RW  T  Kernel stack (thread 20)
[#0 (UE) ls(32:32)]: c3def000 -- c3dfefff 00010000 RW  T  Kernel stack (thread 21)
[#0 (UE) ls(32:32)]: c3e00000 -- c3e0ffff 00010000 RW  T  Kernel stack (thread 22)
[#0 (UE) ls(32:32)]: c3e11000 -- c3e20fff 00010000 RW  T  Kernel stack (thread 23)
[#0 (UE) ls(32:32)]: c3e22000 -- c3e41fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3e43000 -- c3e62fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3e64000 -- c3e83fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3e85000 -- c3ea4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ea6000 -- c3ec5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ec7000 -- c3ee6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ee8000 -- c3f07fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3f09000 -- c3f28fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3f2a000 -- c3f49fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3f4b000 -- c3f6afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3f6c000 -- c3f8bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3f8d000 -- c3facfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3fae000 -- c3fcdfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3fcf000 -- c3feefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c3ff0000 -- c400ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4011000 -- c4030fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4032000 -- c4051fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4053000 -- c4072fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4074000 -- c4093fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4095000 -- c40b4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c40b6000 -- c40d5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c40d7000 -- c40f6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c40f8000 -- c4117fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4119000 -- c4138fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c413a000 -- c4159fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c415b000 -- c417afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c417c000 -- c419bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c419d000 -- c41bcfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c41be000 -- c41cdfff 00010000 RW  T  Kernel stack (thread 24)
[#0 (UE) ls(32:32)]: c41cf000 -- c41eefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c41f0000 -- c420ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4211000 -- c4230fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4232000 -- c4251fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4253000 -- c4272fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4274000 -- c4293fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4295000 -- c42b4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c42b6000 -- c42d5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c42d7000 -- c42f6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c42f8000 -- c4317fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4319000 -- c4338fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c433a000 -- c4359fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c435b000 -- c437afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c437c000 -- c439bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c439d000 -- c43bcfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c43be000 -- c43ddfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c43df000 -- c43fefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4400000 -- c441ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4421000 -- c4440fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4442000 -- c4461fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4463000 -- c4482fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4484000 -- c44a3fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c44a5000 -- c44c4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c44c6000 -- c44e5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c44e7000 -- c48e6fff 00400000 RW     KBuffer
[#0 (UE) ls(32:32)]: c48e8000 -- c4907fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4909000 -- c4928fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c111b000 -- c111bfff 00001000 RW     KBuffer
[#0 (UE) ls(32:32)]: c492a000 -- c4949fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c494b000 -- c496afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c496c000 -- c498bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c498d000 -- c49acfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c49ae000 -- c49cdfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c49cf000 -- c49eefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c49f0000 -- c4a0ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4a11000 -- c4a30fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4a32000 -- c4a51fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4a53000 -- c4a72fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4a74000 -- c4a93fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4a95000 -- c4ab4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ab6000 -- c4ad5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ad7000 -- c4af6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4af8000 -- c4b17fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4b19000 -- c4b38fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4b3a000 -- c4b59fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4b5b000 -- c4b7afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4b7c000 -- c4b9bfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4b9d000 -- c4bbcfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4bbe000 -- c4bddfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4bdf000 -- c4bfefff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4c00000 -- c4c1ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4c21000 -- c4c40fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4c42000 -- c4c61fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4c63000 -- c4c82fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4c84000 -- c4ca3fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ca5000 -- c4cc4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4cc6000 -- c4ce5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ce7000 -- c4d06fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4d08000 -- c4d27fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4d29000 -- c4d48fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4d4a000 -- c4d69fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4d6b000 -- c4d8afff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4d8c000 -- c4dabfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4dad000 -- c4dccfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4dce000 -- c4dedfff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4def000 -- c4e0efff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4e10000 -- c4e2ffff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4e31000 -- c4e50fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4e52000 -- c4e61fff 00010000 RW  T  Kernel stack (thread 25)
[#0 (UE) ls(32:32)]: c4e74000 -- c4e93fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4e95000 -- c4eb4fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c111d000 -- c111dfff 00001000 RW     Ext2FS: Cached bitmap block
[#0 (UE) ls(32:32)]: c4eb6000 -- c4ed5fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ed7000 -- c4ef6fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4ef8000 -- c4f17fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c4f19000 -- c5318fff 00400000 RW     KBuffer
[#0 (UE) ls(32:32)]: c531a000 -- c5719fff 00400000 RW     KBuffer
[#0 (UE) ls(32:32)]: c6f16000 -- c8713fff 017fe000 RW     KBuffer
[#0 (UE) ls(32:32)]: c574d000 -- c584cfff 00100000 RW     kmalloc subheap
[#0 (UE) ls(32:32)]: c586f000 -- c588efff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c5890000 -- c58affff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c9314000 -- cab11fff 017fe000 RW     KBuffer
[#0 (UE) ls(32:32)]: c58d2000 -- c58f1fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c58f3000 -- c5912fff 00020000 RW     DoubleBuffer
[#0 (UE) ls(32:32)]: c584e000 -- c585dfff 00010000 RW  T  Kernel stack (thread 32)
[#0 FinalizerTask(3:3)]: Generating coredump for pid: 32
[#0 FinalizerTask(3:3)]: RTC: Year: 2021, month: 3, day: 6, hour: 5, minute: 59, second: 47
CrashDaemon(20): New coredump file: /tmp/coredump/(UE) ls_32_1615010387
CrashDaemon(20): --- Backtrace for thread #0 (TID 32) ---
CrashDaemon(20): 0x7a347188: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(20): 0x9deb9136: [libc.so] __assertion_failedShell(25): Job entry 'UserspaceEmulator ls' deleted in 1323 ms
 +0x106 (syscall.h:44)
CrashDaemon(20): 0xbd3fd7ff: [/bin/UserspaceEmulator] UserspaceEmulator::Emulator::virt$mprotect(unsigned int, unsigned long, int) +0x9f (Emulator.cpp:1092)
CrashDaemon(20): 0xbd4050c1: [/bin/UserspaceEmulator] .L3617 +0xf (Emulator.cpp:451)
CrashDaemon(20): 0xbd40e0a3: [/bin/UserspaceEmulator] UserspaceEmulator::SoftCPU::INT_imm8(X86::Instruction const&) +0x33 (ValueWithShadow.h:160)
CrashDaemon(20): 0xbd40193b: [/bin/UserspaceEmulator] UserspaceEmulator::Emulator::exec() +0x48b (Emulator.cpp:266)
CrashDaemon(20): 0xbd3fa1b3: [/bin/UserspaceEmulator] main +0x723 (main.cpp:84)
CrashDaemon(20): 0xbd3fa3a5: [/bin/UserspaceEmulator] _start +0x45 (crt0_shared.cpp:60)

```

### PR DESCRIPTION
**Pull request by BenWiederhake**
Welp, noone fixed it so I did.

Note that memory-region-splitting is a bit easier in UE than in the Kernel because UE can afford to keep a 3.1 MB `m_page_to_region_map` around. ( … If someone were to implement some kind of interval-map data-structure, this could be implemented much more efficiently. So efficiently that we could think about making the Kernel use the same one …)

Closes #5663.

### CODE REVIEW

File: Userland/DevTools/UserspaceEmulator/MmapRegion.h [hunk 1]
```diff
@@ -56,6 +56,12 @@ class MmapRegion final : public Region {
     bool is_malloc_block() const { return m_malloc; }
     void set_malloc(bool b) { m_malloc = b; }
 
+    NonnullOwnPtr<MmapRegion> split_at(VirtualAddress);
+
+    int prot()
+    {
+        return (is_readable() ? PROT_READ : 0) | (is_writable() ? PROT_WRITE : 0) | (is_executable() ? PROT_EXEC : 0);
+    };
```
Comment (awesomekling) [inline Userland/DevTools/UserspaceEmulator/MmapRegion.h:64]: `;`

File: Userland/DevTools/UserspaceEmulator/MmapRegion.h [hunk 2]
```diff
@@ -56,6 +56,12 @@ class MmapRegion final : public Region {
     bool is_malloc_block() const { return m_malloc; }
     void set_malloc(bool b) { m_malloc = b; }
 
+    NonnullOwnPtr<MmapRegion> split_at(VirtualAddress);
+
+    int prot()
```
Comment (awesomekling) [inline Userland/DevTools/UserspaceEmulator/MmapRegion.h:61]: `int prot() const`

File: Userland/DevTools/UserspaceEmulator/MmapRegion.h (hunk 1 above)
Comment (BenWiederhake) [reply Userland/DevTools/UserspaceEmulator/MmapRegion.h:64]: >_<

**Comment by awesomekling** [comment]
>This saves a few bytes for each guest-mmaped region, especially since these are likely to be page-aligned.

Not only likely, they are downright *guaranteed* :)

**Comment by BenWiederhake** [comment]
>> […] since these are likely to be page-aligned.
>
> Not only likely, they are downright _guaranteed_ :)

Well, technically there's something funny going on about partial maps: At least for files I'm not entirely sure what exactly the semantics are around past-the-end-but-still-the-same-page read/write/mmap/mprotect.

**Comment by BenWiederhake** [comment]
Changes since last push: Silly typo fixes.

**Comment by tomuta** [comment]
> > > […] since these are likely to be page-aligned.
> > 
> > 
> > Not only likely, they are downright _guaranteed_ :)
> 
> Well, technically there's something funny going on about partial maps: At least for files I'm not entirely sure what exactly the semantics are around past-the-end-but-still-the-same-page read/write/mmap/mprotect.

Data past the end should be zeroed. The last page (if partial) gets special handling by the inode fault handler.

**Comment by BenWiederhake** [comment]
@tomuta: And precisely that is where I'm not sure whether the UserspaceEmulator handles it (and reports it) correctly. However, I'm rather sure I didn't change the behavior – unless UE relied on UB, in which case I'm not sure.

**Comment by awesomekling** [comment]
Yeah UE is a little bit relaxed with various things like that. Room for improvement :)
