### PR TITLE
TextDocument: Fix indentation duplicating spaces

### LINKED ISSUE #8973: LibGUI: Inserting a new line before a space causes spaces to be duplicated on new line
For example:
Peek 2021-07-24 00-17

### PR DESCRIPTION
**Pull request by vinicius-toshiyuki**
Auto indentation will consider only leading spaces before the cursor.
Fixes  #8973.

### CODE REVIEW

File: Userland/Libraries/LibGUI/TextDocument.cpp [hunk 1]
```diff
@@ -786,6 +786,10 @@ void InsertTextCommand::perform_formatting(const TextDocument::Client& client)
 
     for (auto input_char : m_text) {
         if (input_char == '\n') {
+            size_t spaces_at_end = 0;
+            if (dest_line.length() == line_indentation and !at_start_of_line)
```
Comment (awesomekling) [inline Userland/Libraries/LibGUI/TextDocument.cpp:790]: Please use `&&` instead of `and`

**Review by awesomekling — CHANGES_REQUESTED** [review]

**Comment by alimpfard** [comment]
Also, please use "Fixes #8973" in the commit body instead of mentioning it in the commit message.
This will let github auto-close that issue when this is merged :)

File: Userland/Libraries/LibGUI/TextDocument.cpp (hunk 1 above)
Comment (vinicius-toshiyuki) [reply Userland/Libraries/LibGUI/TextDocument.cpp]: Sorry about that! Didn't even know and was a keyword in C++, I must have brought it from Python...
Anyway, I changed it.
