### PR TITLE
less+LibLine: Support escaped contents when computing visible line length

### LINKED ISSUE #15242: less: Gets confused by `md`'s output
To reproduce:
```shell
md README.md | less
```

The first page of less is too short vertically, and navigating with the up/down keys causes funkiness. Later pages are fine. This seems to be caused by the big list of status badges at the top of the file, as deleting those lines makes the issue disappear.

### PR DESCRIPTION
**Pull request by LucasChollet**
First draw to fix #15242.

~~Still a draft as I need to add support for masks and to remove a silly `const_cast`.~~ (I gave up on full mask support)

It works by using the LibLine's method `Editor::actual_rendered_string_length()` in `less` to computes the visible length.

### CODE REVIEW

File: Userland/Libraries/LibLine/Editor.cpp [hunk 1]
```diff
@@ -1779,7 +1779,7 @@ enum VTState {
     BracketArgsSemi = 7,
     Title = 9,
 };
-static VTState actual_rendered_string_length_step(StringMetrics& metrics, size_t index, StringMetrics::LineMetrics& current_line, u32 c, u32 next_c, VTState state, Optional<Style::Mask> const& mask);
+static VTState actual_rendered_string_length_step(StringMetrics& metrics, size_t index, StringMetrics::LineMetrics& current_line, u32 c, u32 next_c, VTState state, Optional<Style::Mask> const& mask, Optional<size_t> const& maximum_length_width = {}, Optional<size_t&> last_return = {});
```
Comment (alimpfard) [inline Userland/Libraries/LibLine/Editor.cpp:1783]: This is always called with all its arguments anyway, why do the new ones have defaults?

Comment (LucasChollet) [reply Userland/Libraries/LibLine/Editor.cpp:1783]: Not in `Editor::actual_rendered_string_metrics(Utf32View ...)`.
Do you want me to add `maximum_line_width` to this overload?

Comment (alimpfard) [reply Userland/Libraries/LibLine/Editor.cpp]: oh I missed that one, nah, it's alright.
