### PR TITLE
Kernel: More bare metal fixes

### LINKED ISSUE #7334: Kernel: ASSERTION FAILED: GraphicsManagement::the().console() in VirtualConsole::initialize()
Getting this on bare metal with latest master (@ a5889b9aad9afc13480c74485e152f592c761446) built and installed, booting from disk.

Kernel options: None other than the default "with serial debug" GRUB menu entry

Hardware: B350 PC MATE (MS-7A34) with AMD Ryzen 5 1600X / NVIDIA GeForce GT 1030

Error:

```
[Kernel]: ASSERTION FAILED: GraphicsManagement::the().console()
[Kernel]: ../../Kernel/TTY/VirtualConsole.cpp:127 in void Kernel::VirtualConsole::initialize()
```

Full boot log:

```
[Kernel]: CPU[0]: Supported features: nx pae pge rdrand rdseed smap smep sse tsc rdtscp constant_tsc nonstop_tsc sep syscall mmx sse2 sse3 ssse3 sse4.1 sse4.2 xsave avx
[Kernel]: CPU[0]: Physical address bit width: 48
[#0 Kernel]: Installing Unhandled Handlers
[Kernel]: MM: boot_pdpt @ P0x0010a000
[Kernel]: MM: boot_pd0 @ P0x0010b000
[Kernel]: MM: boot_pd3 @ P0x0010c000
[Kernel]: MM: Low memory range @ P0x00000000 - P0x00100000
[Kernel]: MM: Kernel range @ P0x00100000 - P0x0102f000
[Kernel]: MM: Multiboot mmap: address=0x00000000, length=644096, type=1
[Kernel]: MM: Got an unaligned physical_region from the bootloader; correcting length 644096 by 1024 bytes
[Kernel]: MM: Multiboot mmap: address=0x0009d400, length=11264, type=2
[Kernel]: MM: Multiboot mmap: address=0x000e0000, length=131072, type=2
[Kernel]: MM: Multiboot mmap: address=0x00100000, length=164102144, type=1
[Kernel]: MM: Multiboot mmap: address=0x09d80000, length=2621440, type=2
[Kernel]: MM: Multiboot mmap: address=0x0a000000, length=3542827008, type=1
[Kernel]: MM: Multiboot mmap: address=0xdd2b4000, length=1150976, type=2
[Kernel]: MM: Multiboot mmap: address=0xdd3cd000, length=995328, type=1
[Kernel]: MM: Multiboot mmap: address=0xdd4c0000, length=4005888, type=4
[Kernel]: MM: Multiboot mmap: address=0xdd892000, length=11890688, type=2
[Kernel]: MM: Multiboot mmap: address=0xde3e9000, length=12677120, type=1
[Kernel]: MM: Multiboot mmap: address=0xdf000000, length=16777216, type=2
[Kernel]: MM: Multiboot mmap: address=0xf8000000, length=67108864, type=2
[Kernel]: MM: Multiboot mmap: address=0xfdf00000, length=1048576, type=2
[Kernel]: MM: Multiboot mmap: address=0xfea00000, length=65536, type=2
[Kernel]: MM: Multiboot mmap: address=0xfeb80000, length=532480, type=2
[Kernel]: MM: Multiboot mmap: address=0xfec10000, length=4096, type=2
[Kernel]: MM: Multiboot mmap: address=0xfec30000, length=4096, type=2
[Kernel]: MM: Multiboot mmap: address=0xfed00000, length=4096, type=2
[Kernel]: MM: Multiboot mmap: address=0xfed40000, length=20480, type=2
[Kernel]: MM: Multiboot mmap: address=0xfed80000, length=65536, type=2
[Kernel]: MM: Multiboot mmap: address=0xfedc2000, length=57344, type=2
[Kernel]: MM: Multiboot mmap: address=0xfedd4000, length=8192, type=2
[Kernel]: MM: Multiboot mmap: address=0xfee00000, length=1048576, type=2
[Kernel]: MM: Multiboot mmap: address=0xff000000, length=16777216, type=2
[Kernel]: MM: Multiboot mmap: address=0x100000000, length=30588534784, type=1
[Kernel]: MM: Super physical region: P0x00f2f000 - P0x0102f000
[Kernel]: MM: User physical region: P0x01030000 - P0x09d80000
[Kernel]: MM: User physical region: P0x0a000000 - P0xdd2b4000
[Kernel]: MM: User physical region: P0xdd3cd000 - P0xdd4c0000
[Kernel]: MM: User physical region: P0xde3e9000 - P0xdf000000
[Kernel]: MM: Contiguous reserved range from P0x0009d400, length is 404480
[Kernel]: MM: Contiguous reserved range from P0x09d80000, length is 2621440
[Kernel]: MM: Contiguous reserved range from P0xdd2b4000, length is 1150976
[Kernel]: MM: Contiguous reserved range from P0xdd892000, length is 11890688
[Kernel]: MM: Contiguous reserved range from P0xdf000000, length is 553648128
[#0 Kernel]: Early access to ACPI tables for interrupt setup
[Kernel]: Interrupts: Switch to Legacy PIC mode
[Kernel]: PIC: Cascading mode, vectors 0x50-0x5f
[#0 Kernel]: Trying to unregister unused handler (?)
[#0 Kernel]: Trying to unregister unused handler (?)
[#0 Kernel]: Interrupts: Detected Dual i8259
[Kernel]: ACPI: Using RSDP @ P0x000f05b0
[Kernel]: ACPI: Main Description Table valid? true
[Kernel]: ACPI: Using XSDT, enumerating tables @ P0xdd4c0090
[Kernel]: ACPI: XSDT revision 1, total length: 164
[Kernel]: ACPI: Initializing Fixed ACPI data
[Kernel]: ACPI: Searching for the Fixed ACPI Data Table
[Kernel]: ACPI: Fixed ACPI data, Revision 6, length: 276 bytes
[Kernel]: ACPI: DSDT P0xdd4c01d0
[Kernel]: ACPI: Dynamic Parsing Enabled, Can parse AML
[Kernel]: Testing PCI via manual probing...
[Kernel]: PCI IO supported
[Kernel]: PCI: Using I/O instructions for PCI configuration space access
[Kernel]: PCI [0000:00:00:00] PCI::ID [1022:1450]
[Kernel]: PCI [0000:00:00:02] PCI::ID [1022:1451]
[Kernel]: PCI [0000:00:01:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:01:03] PCI::ID [1022:1453]
[Kernel]: PCI [0000:00:02:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:03:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:03:01] PCI::ID [1022:1453]
[Kernel]: PCI [0000:00:04:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:07:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:07:01] PCI::ID [1022:1454]
[Kernel]: PCI [0000:00:08:00] PCI::ID [1022:1452]
[Kernel]: PCI [0000:00:08:01] PCI::ID [1022:1454]
[Kernel]: PCI [0000:00:14:00] PCI::ID [1022:790b]
[Kernel]: PCI [0000:00:14:03] PCI::ID [1022:790e]
[Kernel]: PCI [0000:00:18:00] PCI::ID [1022:1460]
[Kernel]: PCI [0000:00:18:01] PCI::ID [1022:1461]
[Kernel]: PCI [0000:00:18:02] PCI::ID [1022:1462]
[Kernel]: PCI [0000:00:18:03] PCI::ID [1022:1463]
[Kernel]: PCI [0000:00:18:04] PCI::ID [1022:1464]
[Kernel]: PCI [0000:00:18:05] PCI::ID [1022:1465]
[Kernel]: PCI [0000:00:18:06] PCI::ID [1022:1466]
[Kernel]: PCI [0000:00:18:07] PCI::ID [1022:1467]
[Kernel]: Starting SerenityOS...
[Kernel]: RTC: Year: 2021, month: 5, day: 21, hour: 8, minute: 47, second: 36
[Kernel]: HPET @ P0xdd4d2bb0
[Kernel]: HPET: Minimum clock tick - 14318
[Kernel]: HPET: Timers count - 3
[Kernel]: HPET: Main counter size: 32-bit
[Kernel]: HPET: Timer[0] comparator size: 32-bit, mode: 32-bit
[Kernel]: HPET: Timer[1] comparator size: 32-bit, mode: 32-bit
[Kernel]: HPET: Timer[2] comparator size: 32-bit, mode: 32-bit
[Kernel]: HPET: frequency 14492753 Hz (14 MHz) resolution: 69 ns
[#0 Kernel]: Trying to unregister unused handler (?)
[#0 Kernel]: Trying to unregister unused handler (?)
[#0 Kernel]: HPET: Setting appropriate functions to timers.
[#0 Kernel]: Time: Scanning for periodic timers
[#0 Kernel]: Time: Scanning for non-periodic timers
[Kernel]: KernelRng: Using RDSEED or RDRAND as entropy source
[Kernel]: ASSERTION FAILED: GraphicsManagement::the().console()
[Kernel]: ../../Kernel/TTY/VirtualConsole.cpp:127 in void Kernel::VirtualConsole::initialize()
[#0 Kernel]: 0xc05d8ea4 (next: 0xc0108018)
[#0 Kernel]: 0xc05cc1ed (next: 0xc0108098)
[#0 Kernel]: 0xc06b576f (next: 0xc0108118)
[#0 Kernel]: 0xc06b6e73 (next: 0xc0108168)
[#0 Kernel]: 0xc06b3825 (next: 0xc0108218)
[#0 Kernel]: 0xc06cc006 (next: 0xc0108298)
[#0 Kernel]: 0xc0100145 (next: 0x00000000)
```

### PR DESCRIPTION
**Pull request by supercomputer7**
Fixes #7334.

### CODE REVIEW

**Comment by supercomputer7** [comment]
cc @boricj - This might break something I'm not aware of. Do you know about any system that implements multiple PCI host bridges for secondary PCI buses?

File: Kernel/PCI/Access.h [hunk 1]
```diff
@@ -49,6 +49,7 @@ class PCI::Access {
     virtual ~Access() = default;
 
     Vector<PhysicalID> m_physical_ids;
+    Vector<u8> m_enumerated_buses;
```
Comment (bgianfo) [inline Kernel/PCI/Access.h:52]: It looks like we might be able to make this a `AK::Bitmap` instead given how it's currently used?

**Comment by boricj** [comment]
I'm not an expert on PCI shenanigans, I just fixed its enumeration on my old Athlon XP computer (https://github.com/SerenityOS/serenity/commit/06d76a4717b3678808d6e8339c0f18cbd7ddbb70). I do recall PCI devices being enumerated multiple times before that commit on that system because it has several PCI buses and at least one bridge.

File: Kernel/Graphics/GraphicsManagement.cpp [hunk 2]
```diff
@@ -140,6 +141,8 @@ UNMAP_AFTER_INIT bool GraphicsManagement::initialize()
         }
         display_adapter->initialize_framebuffer_devices();
     });
+    if (m_graphics_devices.is_empty())
+        PANIC("No graphical device was initialized.");
```
Comment (boricj) [inline Kernel/Graphics/GraphicsManagement.cpp:145]: I know that SerenityOS has an emphasis on a graphical desktop, but that's a bit too extreme. Please think about those who can't afford a graphics card during these times with the current massive shortages :^)

Comment (supercomputer7) [reply Kernel/Graphics/GraphicsManagement.cpp:145]: it's not about graphical desktop, it's about that you just can't have anything useful with the system if you don't have a graphical device of some sort. If we didn't find any graphical device, it's most likely an error though, like what #7334 where @linusg booted his system and the kernel didn't find any VGA compatible card although he had (GeForce GT 1030).
If we don't find a graphical device of some sort, we can't initialize safely even a text console (VGA text console, or high resolution framebuffer for Framebuffer console).

Maybe later on when we have serial terminal support implemented in the kernel, we could let people to boot without any graphics adapter in their system (although this might be a rare case, because the firmware might refuse to boot without it).

Comment (boricj) [reply Kernel/Graphics/GraphicsManagement.cpp:145]: There is work on progress for serial terminal support (#7260) and a computer doesn't need a graphics card to function. Even without going into embedded or specialized devices, I could pull out the graphic card in my desktop computer (which doesn't have an iGPU) and repurpose it as a headless server if I wanted to.

The point is, x86 computers without graphic cards do exist and unless it is decided that SerenityOS will not support headless operation, then the kernel shouldn't panic if there are no graphic cards in the system.

Comment (supercomputer7) [reply Kernel/Graphics/GraphicsManagement.cpp:145]: I've seen the work in progress of serial terminal support. I encourage to support headless operation, although this is definitely not a main goal of the project nor usual use case of our project.
Also - "Doesn't need a graphics card to function" doesn't mean "Can boot without a graphics card", if we take it from the user perspective and not from OS developer point of view, because I can simply unplug my computer monitor and then the graphics card is still connected, but the OS and the computer don't need it to function.

If the BIOS/UEFI firmware supports it, then no problem, we can support it too. I just want to see evidence for such thing, otherwise how can we know we didn't miss the card when we scanned the PCI bus?
Does your machine can be booted without any kind of graphics adapter (you said you don't have an integrated GPU)? Does the firmware not halting with some beeps?
