### PR TITLE
PixelPaint: Fix zooming to cursor

### LINKED ISSUE #9900: PixelPaint: Image doesn't zoom centered at the cursor
How to reproduce:
- Open PixelPaint
- Put cursor at the top left (but inside) of the image
- Zoom in
- Image goes off screen and you don't zoom into the corner.

I've tried for a few hours now to fix this, the math in `ImageEditor::scale_centered_on_position` seems reasonable, and the `focus_point` computed also makes sense on printing it out, but the zoom still isn't centered on the cursor.

### PR DESCRIPTION
**Pull request by TobyAsE**
This patch fixes the behavior of zooming. Now the cursor stays over the same spot in the image when zooming.

I have a headache now, offset math with about 4 different origins is hard...

This fixes #9900

### CODE REVIEW

File: Userland/Applications/PixelPaint/ImageEditor.cpp [hunk 1]
```diff
@@ -319,8 +319,8 @@ void ImageEditor::mousemove_event(GUI::MouseEvent& event)
     if (event.buttons() & GUI::MouseButton::Middle) {
         auto delta = event.position() - m_click_position;
         m_pan_origin = m_saved_pan_origin.translated(
-            -delta.x() / m_scale,
-            -delta.y() / m_scale);
+            -delta.x(),
+            -delta.y());
```
Comment (mustafaquraish) [inline Userland/Applications/PixelPaint/ImageEditor.cpp:323]: This seems to be for panning with the middle mouse button and doesn't seem right... Was this intended?

Comment (TobyAsE) [reply Userland/Applications/PixelPaint/ImageEditor.cpp:323]: Yup. I removed the dividing by scale and then multiplying by scale again, too (see ln 599-600).
There wasn't an easy way to seperate that into its own atomic commit.

**Review by mustafaquraish — APPROVED** [review]
LGTM, let's get this in so I can actually zoom in to where I want for a change :^)
