### PR TITLE
SharedBuffer: Amend commit 2d4d465206d

### LINKED ISSUE #341: GWidget: Memory leak when resizing window
This can be visible in any application using a GWidget, such as the text editor, file manager, ect. To recreate just rapidly resize the window back and forth. (It took around 20-30 seconds for me)

`0x00018ac5  kmalloc_impl(unsigned long) +78
0x0002cd21  DoubleBuffer::write(unsigned char const*, int) +221
0x000423d5  FileDescription::write(unsigned char const*, int) +23
0x0001a2be  Process::do_write(FileDescription&, unsigned char const*, int) +120
0x0001be8c  Process::sys$writev(int, iovec const*, int) +112
0x000233c3  syscall_trap_entry +2825
0x00022870  syscall_trap_handler +38
dump_backtrace() called from within itself, what the hell is going on!
TextEditor(13) kmalloc(): PANIC! Out of memory (sucks, dude)
sum_free=0, real_size=16
`

### PR DESCRIPTION
**Pull request by rburchell**
I had the right cause of the SharedBuffer leak, but goofed the fix by
desynching the per-pid refcount and the global refcount.

Fix that, and add a generous sprinkle of asserts to make sure the two
stay in sync.

Fixes #341

(... for real this time)

### CODE REVIEW

File: Kernel/SharedBuffer.cpp [hunk 1]
```diff
@@ -67,11 +89,14 @@ void SharedBuffer::deref_for_process(Process& process)
...
                 destroy_if_unused();
                 return;
             }
         }
     }
+
+    ASSERT_NOT_REACHED();
 }
 
 void SharedBuffer::disown(pid_t pid)
```
Comment (rburchell) [inline Kernel/SharedBuffer.cpp]: Still not right. The disown handling is broken, as it doesn't alter m_total_refs.
