### PR TITLE
HackStudio: Attempt to fix #include autocomplete crash

### LINKED ISSUE #7404: HackStudio: Crash when autocompleting an #include path
I don't know how to reproduce this, but I was autocompleting something like `#include <AK/BitmapV` to fill in `BitmapView.h`.

The autocomplete box was up, I had selected `BitmapView.h` and pressed enter. HackStudio crashed with this trace:

```
HackStudio(30:30): ASSERTION FAILED: i < m_size
.././AK/Vector.h:183

--- Backtrace for thread #0 (TID 30) ---
0x5ecff1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
0x072f65c3: [libc.so] raise +0x23 (signal.cpp:21)
0x072e0a5d: [libc.so] abort +0x2a (stdlib.cpp:233)
0x072e15cb: [libc.so] __assertion_failed +0xeb (Format.h:236)
0x7b99bdcf: [libgui.so] GUI::AutocompleteSuggestionModel::data(GUI::ModelIndex const&, GUI::ModelRole) const +0x22f (Vector.h:183)
0x7ba216a2: [libgui.so] GUI::ModelIndex::data(GUI::ModelRole) const +0x42 (ModelIndex.cpp:19)
0x7b99a820: [libgui.so] GUI::AutocompleteBox::apply_suggestion() +0x190 (AutocompleteProvider.cpp:175)
0x7ba60596: [libgui.so] .L3428 +0xb3 (OwnPtr.h:146)
0x7ba7d68f: [libgui.so] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) +0x2f (Widget.cpp:267)
0x06f6471e: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
0x7ba8dbed: [libgui.so] GUI::Window::handle_key_event(GUI::KeyEvent&) [clone .localalias] +0xcd (Window.cpp:430)
0x7ba95bea: [libgui.so] GUI::Window::event(Core::Event&) +0xfa (Window.cpp:551)
0x06f6471e: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
0x06f4bce3: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x573 (Atomic.h:246)
0x06f4c44b: [libcore.so] Core::EventLoop::exec() +0x5b (EventLoop.cpp:362)
0x7b97cdd8: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:100)
0x99465609: [/bin/HackStudio] main +0x7b9 (NonnullRefPtr.h:276)
0x99465c08: [/bin/HackStudio] _start +0x58 (crt0.cpp:39)
```

cc @itamar8910

### PR DESCRIPTION
**Pull request by itamar8910**
This is a best-effort attempt to fix #7404. I can't verify it does fix it as I wasn't able to reproduce it.

Anyways I _think_ we can close #7404 (until proven otherwise) after merging this. @awesomekling your opinion?

### CODE REVIEW

File: Userland/Libraries/LibGUI/AutocompleteProvider.cpp [hunk 1]
```diff
@@ -168,7 +168,7 @@ void AutocompleteBox::apply_suggestion()
         return;
 
     auto selected_index = m_suggestion_view->selection().first();
-    if (!selected_index.is_valid())
+    if (!selected_index.is_valid() || selected_index.row() >= m_suggestion_view->model()->row_count())
```
Comment (awesomekling) [inline Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: You can ask the model if the index is valid:
```cpp
if (m_suggestion_view->model()->is_valid(selected_index)`
```

Comment (alimpfard) [inline Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: Is this happening because the language server sends an update to the client between the user selecting something from the autocomplete box and us trying to apply it? if so, maybe we should instead just invalidate the entire list and ignore the user's action?

Comment (itamar8910) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: I see. Do you have an idea on how we can detect such a condition? (And sorry for the late reply..)

Comment (alimpfard) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: the most simple would be to have a boolean that you set when the list is updated, and reset when you show the box; then checking it in `apply_suggestion()`.
if it's set, tell the user to go away :P

Comment (itamar8910) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: yeah sound's good I'll do just that, thanks.
I think I'll also keep the index validation check, just in case 🤷‍♂️

Comment (itamar8910) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: Thinking about it, I don't think that using that boolean would be appropriate, because `AutocompleteBox::update_suggestions` will normally be called while the autocomplete box is shown, for example if the user is typing with the autocomplete box up. 

I agree with you that the race is probably when we get an update from the LanguageServer between the user selecting something and `AutocompleteBox::apply_suggestion` being called, but i'm not sure how we can detect this :thinking: 

It seems like somehow we should have a way to invalidate a pending `apply_suggestions` event when we're in   `AutocompleteBox::update_suggestions`?

Comment (alimpfard) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp:171]: :thinking: I don't think there's a way to cancel posted events right now
maybe your current way of "just don't crash, maybe being wrong is okay" is okay?

Comment (itamar8910) [reply Userland/Libraries/LibGUI/AutocompleteProvider.cpp]: Yeah, I think it's okay-ish for now (tm), and providing wrong autocomplete results is indeed not disastrous.
Anyways I added a FIXME about it in `AutocompleteBox::apply_suggestion()`.
I'm pulling this PR out of draft.
