### PR TITLE
Kernel: Ignore subsequent calls to Process::die

### LINKED ISSUE #8485: Kernel: m_threads_for_coredump.is_empty() assertion failure in Process::die
Found with stress-ng.
Command: `stress-ng --dev 1`
Trace:
```
[stress-ng(34:36)]: ASSERTION FAILED: m_threads_for_coredump.is_empty()
[stress-ng(34:36)]: ../../Kernel/Process.cpp:629 in void Kernel::Process::die()
[#0 stress-ng(34:36)]: 0xc0716859  abort +0x17e
[#0 stress-ng(34:36)]: 0xc07166bb  _abort +0x0
[#0 stress-ng(34:36)]: 0xc04ee705  Kernel::Process::die() +0x3af
[#0 stress-ng(34:36)]: 0xc04ef5f8  Kernel::Process::crash(int, unsigned int, bool) +0x5d4
[#0 stress-ng(34:36)]: 0xc0718b2c  illegal_instruction_handler +0x0
[#0 stress-ng(34:36)]: 0xc07196bc  page_fault_handler +0xa1f
[#0 stress-ng(34:36)]: 0xc071693e  page_fault_asm_entry +0x26
```

### PR DESCRIPTION
**Pull request by tomuta**
It's possible that another thread might try to exit the process just
about the same time another thread does the same, or a crash happens.
Also, we may not be able to kill all other threads instantly as they
may be blocked in the kernel (though in this case they would get killed
before ever returning back to user mode. So keep track of whether
Process::die was already called and ignore it on subsequent calls.

Fixes #8485

### CODE REVIEW

File: Kernel/Process.cpp [hunk 1]
```diff
@@ -626,6 +626,15 @@ void Process::unblock_waiters(Thread::WaitBlocker::UnblockFlags flags, u8 signal
 
 void Process::die()
 {
+    auto expected = State::Running;
+    if (!m_state.compare_exchange_strong(expected, State::Dying, AK::memory_order_acquire)) {
```
Comment (ADKaster) [inline Kernel/Process.cpp:630]: Could this possibly cause a transition from  back Dead to Dying?

Comment (tomuta) [reply Kernel/Process.cpp:630]: No, the exchange only happens if `m_state == State::Running`, so if it's already at `State::Dead` this would fail.

Comment (ADKaster) [reply Kernel/Process.cpp:630]: Ahh right because it's not a compare exchange weak loop, it won't keep reloading and rechecking expected. Carry on 🙂
