### PR TITLE
SoundPlayer: Fix stack-use-after-scope when playing file in loop mode

### LINKED ISSUE #10751: SoundPlayer: Looping without command-line arguments is bad
Steps to reproduce:
1. Open SoundPlayer without arguments
2. Open a file through the menu
3. Click either "Loop File" (produces the bug in the screenshot) or "Loop Playlist" (crashes SoundPlayer)
4. Click Play
5. Wait until it's finished (I recommend a short music file)

Bildschirmfoto_2021-11-01_17-47-21

### PR DESCRIPTION
**Pull request by swoertz**
Fixes #10751

The path returned by GUI:FilePicker is stored on the stack when the
callback is executed. The player only stored a StringView to the path
however it should take ownership of the path instead since the path is
accessed even after the file menu open action has returned.

### CODE REVIEW

**Comment by swoertz** [comment]
One of the CI checks is failing.
```
[0/2] Re-checking globbed directories...
[0/1] cd /home/runner/work/serenity/serenity/Build/x86_64 && /usr/local/bin/cmake -E env SERENITY_ARCH=x86_64 /home/runner/work/serenity/serenity/Meta/run.sh
  Unable to init server: Could not connect: Connection refused
  Unable to init server: Could not connect: Connection refused
  Unable to init server: Could not connect: Connection refused
  Running QEMU in CI
  7lSeaBIOS (version 1.14.0-202111041415~ubuntu20.04.1)
  
  
  iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+3FF8B4D0+3FECB4D0 CA00
  Press Ctrl-B to configure iPXE (PCI 00:03.0)...
                                                                                 
  
  
  Booting from ROM..::endgroup::
Verify Output File
  Results: 
  cat: fsmount/home/anon/test-results.log: No such file or directory
  Error: Process completed with exit code 1.
```
The `test-results.log` file is not  found, however it doesn't seem like the tests were even started since the banner:
```
==== Running Tests on SerenityOS ====
```
is also missing. Is that a known problem? I cannot see at the moment how this relates to my change. Any input appreciated. :)

File: Userland/Applications/SoundPlayer/Player.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ Player::Player(Audio::ClientConnection& audio_client_connection)
     };
 }
 
-void Player::play_file_path(StringView path)
+void Player::play_file_path(const String& path)
```
Comment (trflynn89) [inline Userland/Applications/SoundPlayer/Player.cpp:41]: [The code style](https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md#const-placement) here is to use east-cost
```suggestion
void Player::play_file_path(String const& path)
```

**Review by trflynn89 — COMMENTED** [review]
The CI failure is likely a flake, there's a triple-fault that's been messing up CI for a while that we haven't figured out yet.

File: Userland/Applications/SoundPlayer/Player.cpp (hunk 1 above)
Comment (swoertz) [reply Userland/Applications/SoundPlayer/Player.cpp]: - [x] Use east-const

**Review by kleinesfilmroellchen — APPROVED** [review]
