### PR TITLE
LibWeb: Fix for absolutely positioned elements with specified height

### LINKED ISSUE #18842: LibWeb: padding shouldn't increase the paintable box size if the element specifies a fixed size
The following example on MDN exhibits the problem for the `h1` text over the star logo:

https://mdn.github.io/learning-area/css/styling-boxes/letterheaded-paper-finished/index.html

The CSS for the offending element specifies both a height and padding:

```
h1 {
  position: absolute;
  top: 12mm;
  left: 20mm;
  width: 128px;
  height: 128px;
  font-size: 20px;
  letter-spacing: 1px;
  text-align: center;
  padding: 44px 0;
  color: white;
  text-shadow: 1px 1px 1px black;
}
```

Ladybird:

ladybird

Expected:

expected

### PR DESCRIPTION
**Pull request by axgallo**
Make absolute_padding_box_rect account for specified height. Padding should not increase the height of the box in such cases.

Fixes #18842.

### CODE REVIEW

**Comment by axgallo** [comment]
This is my attempt at fixing an issue I've discovered while trying MDN examples on Ladybird. I'm gathering feedback whether this is at least directionally correct, since I've just started looking at the codebase.

File: Userland/Libraries/LibWeb/Painting/PaintableBox.h [hunk 1]
```diff
@@ -56,7 +56,11 @@ class PaintableBox : public Paintable {
         rect.set_x(absolute_rect.x() - box_model().padding.left);
         rect.set_width(content_width() + box_model().padding.left + box_model().padding.right);
         rect.set_y(absolute_rect.y() - box_model().padding.top);
-        rect.set_height(content_height() + box_model().padding.top + box_model().padding.bottom);
+        auto const& height = layout_node().computed_values().height();
+        if (height.is_auto())
+            rect.set_height(content_height() + box_model().padding.top + box_model().padding.bottom);
+        else
+            rect.set_height(content_height());
```
Comment (awesomekling) [inline Userland/Libraries/LibWeb/Painting/PaintableBox.h:63]: Whatever the bug is, it should be fixed in layout, not in painting.
By the time we have a `PaintableBox`, all CSS *computed* values must have already been resolved to *used* values (i.e absolute coordinates, sizes, etc)

**Review by awesomekling — CHANGES_REQUESTED** [review]

File: Userland/Libraries/LibWeb/Painting/PaintableBox.h (hunk 1 above)
Comment (awesomekling) [reply Userland/Libraries/LibWeb/Painting/PaintableBox.h:63]: See https://github.com/SerenityOS/serenity/blob/master/Documentation/Browser/LibWebFromLoadingToPainting.md for a brief introduction to the high-level phases of loading, parsing, layout, paint, etc. :)

Comment (axgallo) [reply Userland/Libraries/LibWeb/Painting/PaintableBox.h]: Making an adjustment in `FormattingContext::compute_height_for_absolutely_positioned_non_replaced_element` inspired from `BlockFormattingContext::compute_height` fixes the problem.

Should it be further aligned with `BlockFormattingContext::compute_height`? I'm happy to do it if that's desirable.

Comment (awesomekling) [reply Userland/Libraries/LibWeb/Painting/PaintableBox.h]: Which part of which CSS spec does your fix implement? Can you link to the specific section?

Comment (axgallo) [reply Userland/Libraries/LibWeb/Painting/PaintableBox.h]: IIUC https://www.w3.org/TR/css-sizing-3/#box-sizing implies that the specified height includes padding, but it doesn't for `content-box`. I'll adjust further.

Comment (axgallo) [reply Userland/Libraries/LibWeb/Painting/PaintableBox.h]: Sure, I've updated the patch to do that as well.
