### PR TITLE
Fix PCI enumeration and terminology

### LINKED ISSUE #5190: Kernel: PCI bridge enumeration is buggy
SerenityOS on an Asus A7N8X-E Deluxe motherboard "clones" several PCI devices during initialization. It appears the enumeration code does not properly handle PCI bridges, as they get enumerated multiple times.

Partial dmesg with `PCI_DEBUG=1` (the secondary bus that gets enumerated twice is `0000:00:08:00`) :
```
...
[#0 init_stage2(1:1)]: PCI: Using I/O instructions for PCI configuration space access
[#0 init_stage2(1:1)]: PCI: IO enumerating hardware
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000e for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=0
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x40 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000040 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000040 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x60 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000060 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000060 for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI [0000:00:00:00] has capability 2
[#0 init_stage2(1:1)]: PCI [0000:00:00:00] has capability 8
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=0, function=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:06]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:07]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=1, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x48 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000048 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000048 for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI [0000:00:01:00] has capability 8
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=1, function=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI [0000:00:01:01] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:06]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:01:07]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=2, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI [0000:00:02:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=2, function=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI [0000:00:02:01] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=2, function=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x80 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000080 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000080 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI [0000:00:02:02] has capability 10
[#0 init_stage2(1:1)]: PCI [0000:00:02:02] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:06]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:02:07]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=4, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI [0000:00:04:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=5, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI [0000:00:05:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=6, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI [0000:00:06:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=8, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000019 for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Found secondary bus: 1
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=1
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=4, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x48 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000048 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000048 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x50 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000050 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000050 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] has capability 1
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] has capability 3
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=7, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=10, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x50 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000050 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000050 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI [0000:01:0a:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=11, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x60 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000060 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000060 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI [0000:01:0b:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1f:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=9, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI [0000:00:09:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=13, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI [0000:00:0d:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=0, slot=30, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000019 for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Found secondary bus: 3
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=3
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=3, slot=0, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x60 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000060 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000060 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] has capability 1
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] has capability 2
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1f:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=0, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=1
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=4, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x48 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000048 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000048 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x50 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000050 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000050 for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] has capability 1
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] has capability 3
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=7, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: No capabilities pointer for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: No capabilities for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=10, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x50 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000050 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000050 for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI [0000:01:0a:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=1, slot=11, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x60 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000060 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000060 for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI [0000:01:0b:00] has capability 1
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=1, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:01:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=2
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=2, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:02:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=3
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating function type=-1, bus=3, slot=0, function=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000002 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Getting capabilities pointer for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000006 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000006 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Found capabilities pointer for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000034 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000034 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x60 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000060 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000060 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Reading in capability at 0x44 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000044 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000044 for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] has capability 1
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] has capability 2
[#0 init_stage2(1:1)]: PCI: Early reading type for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000e for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=3, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:03:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=4
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=4, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:04:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Enumerating bus type=-1, bus=5
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=0
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:00:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=1
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:01:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=2
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:02:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=3
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:03:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=4
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:04:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=5
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:05:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=6
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:06:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=7
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:07:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=8
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:08:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=9
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:09:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=10
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=11
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=12
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=13
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=14
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=15
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:0f:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=16
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:10:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=17
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:11:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=18
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:12:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=19
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:13:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=20
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:14:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=21
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:15:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=22
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:16:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=23
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:17:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=24
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:18:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=25
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:19:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=26
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1a:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=27
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1b:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=28
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1c:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=29
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1d:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=30
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1e:00]
[#0 init_stage2(1:1)]: PCI: Enumerating slot type=-1, bus=5, slot=31
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:05:1f:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 16-bit field 0x00000000 for PCI [0000:00:00:06]
[#0 init_stage2(1:1)]: PCI: Early reading 16-bit field 0x00000000 for PCI [0000:00:00:06]
[#0 init_stage2(1:1)]: PCI: IO access initialised.
[#0 init_stage2(1:1)]: PCI [0000:00:00:00] (10de:01e0)
[#0 init_stage2(1:1)]: PCI [0000:00:00:01] (10de:01eb)
[#0 init_stage2(1:1)]: PCI [0000:00:00:02] (10de:01ee)
[#0 init_stage2(1:1)]: PCI [0000:00:00:03] (10de:01ed)
[#0 init_stage2(1:1)]: PCI [0000:00:00:04] (10de:01ec)
[#0 init_stage2(1:1)]: PCI [0000:00:00:05] (10de:01ef)
[#0 init_stage2(1:1)]: PCI [0000:00:01:00] (10de:0060)
[#0 init_stage2(1:1)]: PCI [0000:00:01:01] (10de:0064)
[#0 init_stage2(1:1)]: PCI [0000:00:02:00] (10de:0067)
[#0 init_stage2(1:1)]: PCI [0000:00:02:01] (10de:0067)
[#0 init_stage2(1:1)]: PCI [0000:00:02:02] (10de:0068)
[#0 init_stage2(1:1)]: PCI [0000:00:04:00] (10de:0066)
[#0 init_stage2(1:1)]: PCI [0000:00:05:00] (10de:006b)
[#0 init_stage2(1:1)]: PCI [0000:00:06:00] (10de:006a)
[#0 init_stage2(1:1)]: PCI [0000:00:08:00] (10de:006c)
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] (11ab:4320)
[#0 init_stage2(1:1)]: PCI [0000:01:07:00] (10ec:8029)
[#0 init_stage2(1:1)]: PCI [0000:01:0a:00] (1106:3044)
[#0 init_stage2(1:1)]: PCI [0000:01:0b:00] (1095:3112)
[#0 init_stage2(1:1)]: PCI [0000:00:09:00] (10de:0065)
[#0 init_stage2(1:1)]: PCI [0000:00:0d:00] (10de:006e)
[#0 init_stage2(1:1)]: PCI [0000:00:1e:00] (10de:01e8)
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] (10de:02e1)
[#0 init_stage2(1:1)]: PCI [0000:01:04:00] (11ab:4320)
[#0 init_stage2(1:1)]: PCI [0000:01:07:00] (10ec:8029)
[#0 init_stage2(1:1)]: PCI [0000:01:0a:00] (1106:3044)
[#0 init_stage2(1:1)]: PCI [0000:01:0b:00] (1095:3112)
[#0 init_stage2(1:1)]: PCI [0000:03:00:00] (10de:02e1)
[#0 init_stage2(1:1)]: MBVGADevice address=P0xd0000000, pitch=5120, width=1280, height=1024
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:03]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:04]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:00:05]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:01:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:01:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000009 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000009 for PCI [0000:00:02:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000009 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000009 for PCI [0000:00:02:01]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x00000009 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x00000009 for PCI [0000:00:02:02]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:05:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:06:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:08:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:09:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:00:0d:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:00:1e:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:04:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000a for PCI [0000:01:0a:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:01:0b:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000000b for PCI [0000:03:00:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: Found @ PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: Port base: IO a400
[#0 init_stage2(1:1)]: NE2000: Interrupt line: 12
[#0 init_stage2(1:1)]: PCI: IO Reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: RAM test KO
[#0 init_stage2(1:1)]: NE2000: MAC address: 00:40:95:46:b0:01
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: Found @ PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: IO Reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 8-bit field 0x0000003c for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: Port base: IO a400
[#0 init_stage2(1:1)]: NE2000: Interrupt line: 12
[#0 init_stage2(1:1)]: PCI: IO Reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: PCI: Early reading 32-bit field 0x00000010 for PCI [0000:01:07:00]
[#0 init_stage2(1:1)]: NE2000: RAM test KO
[#0 init_stage2(1:1)]: NE2000: MAC address: 00:40:95:46:b0:01
...
```

### PR DESCRIPTION
**Pull request by boricj**
While this works on bare-metal and on QEMU, somebody that knows a bit more about PCI than me should check if this is correct (or at least more correct than before).

Fixes #5190.

### CODE REVIEW

**Comment by supercomputer7** [comment]
I suggest to split the first commit to two commits - one should be about the terminology change, the second is about fixing the issue with multiple PCI host bridge enumeration.

File: Kernel/PCI/Access.cpp [hunk 1]
```diff
@@ -99,43 +99,43 @@ u16 Access::early_read_type(Address address)
...
+void Access::enumerate_functions(int type, u8 bus, u8 device, u8 function, Function<void(Address, ID)>& callback, bool recursive)
 {
-    dbgln<PCI_DEBUG>("PCI: Enumerating function type={}, bus={}, slot={}, function={}", type, bus, slot, function);
-    Address address(0, bus, slot, function);
+    dbgln<PCI_DEBUG>("PCI: Enumerating function type={}, bus={}, device={}, function={}", type, bus, device, function);
+    Address address(0, bus, device, function);
     if (type == -1 || type == early_read_type(address))
         callback(address, { early_read16_field(address, PCI_VENDOR_ID), early_read16_field(address, PCI_DEVICE_ID) });
-    if (early_read_type(address) == PCI_TYPE_BRIDGE) {
+    if (early_read_type(address) == PCI_TYPE_BRIDGE && recursive) {
```
Comment (supercomputer7) [inline Kernel/PCI/Access.cpp:108]: Just wondering, if we have root PCI host bridge that declares itself as multi-function, does it mean that if encounter another PCI bridge when we scan a bus, it must be a "function" in the root PCI host bridge?

Comment (boricj) [reply Kernel/PCI/Access.cpp:108]: From what I understand, the PCI bridge itself is a function of the root PCI host bridge, but its children are on a separate PCI bus. That matches what I've seen so far with my bare-metal target, but I have no idea just how flexible PCI can be in the wild.

**Comment by boricj** [comment]
I'd rather not split the first commit because beyond the enumeration issue the PCI code also mixed up functions with buses and called devices "slots", which isn't a thing anymore since PCIe. Best to rip off that band-aid in one go in my opinion.
