### PR TITLE
LibWeb: Handle invalid UTF-8 in Fetch's Body#text()

### LINKED ISSUE #18913: LibWeb: Fetch's Body#text() does not handle invalid UTF-8
String::from_utf8 expects the bytes to already be valid UTF-8, but they can invalid.
https://github.com/SerenityOS/serenity/blob/0f0d16bbecc4374e7b00be101c60623da300c40a/Userland/Libraries/LibWeb/Fetch/Body.cpp#L140

For example, `seenthis.se` calls `.text()` on GIF web beacons before immediately discarding them:
image
```
bytes: GIF89a����!�,L;
WebContent: /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/Fetch/Body.cpp:144: WebIDL::ExceptionOr<JS::Value> Web::Fetch::package_data(JS::Realm &, AK::ByteBuffer, Web::Fetch::PackageDataType, const Optional<MimeSniff::MimeType> &): Assertion `_temporary_result.error().code() == ENOMEM' failed.
```

### PR DESCRIPTION
**Pull request by 0GreenClover0**
Resolves #18913, fixes the crash on `seenthis.se`

I hope that's what the suggestion in the issue meant

### CODE REVIEW

File: Userland/Libraries/LibWeb/Fetch/Body.cpp [hunk 1]
```diff
@@ -135,9 +136,13 @@ WebIDL::ExceptionOr<JS::Value> package_data(JS::Realm& realm, ByteBuffer bytes,
...
         // Return the result of running parse JSON from bytes on bytes.
         return Infra::parse_json_bytes_to_javascript_value(realm, bytes);
-    case PackageDataType::Text:
+    case PackageDataType::Text: {
         // Return the result of running UTF-8 decode on bytes.
-        return JS::PrimitiveString::create(vm, TRY_OR_THROW_OOM(vm, String::from_utf8(bytes)));
+        auto decoder = TextCodec::decoder_for("UTF-8"sv);
+        VERIFY(decoder.has_value());
+
+        return JS::PrimitiveString::create(vm, TextCodec::convert_input_to_utf8_using_given_decoder_unless_there_is_a_byte_order_mark(*decoder, bytes).release_value_but_fixme_should_propagate_errors());
```
Comment (ADKaster) [inline Userland/Libraries/LibWeb/Fetch/Body.cpp:144]: shouldn't we be able to propagate the errors from `convert_input_to_utf8_using_given_decoder_unless_there_is_a_byte_order_mark` ?

Comment (0GreenClover0) [reply Userland/Libraries/LibWeb/Fetch/Body.cpp:144]: I couldn't make it work, it complained about JS:Value's constructor when I used TRY. But I'm not sure if that was a correct way of doing it

Comment (trflynn89) [reply Userland/Libraries/LibWeb/Fetch/Body.cpp:144]: Use `TRY_OR_THROW_OOM`:
```c++
auto utf8_text = TRY_OR_THROW_OOM(vm, TextCodec::convert_input_to_utf8_using_given_decoder_unless_there_is_a_byte_order_mark(*decoder, bytes));
return JS::PrimitiveString::create(vm, move(utf8_text));
```

`TextCodec::convert_input_to_utf8...` returns an `AK::Error`, and only when we run out-of-memory. We use `TRY_OR_THROW_OOM` to convert such `Error` instances to a `JS::Completion`.
