### PR TITLE
LibLine: Change get_line to return a Result<String, Error>

### LINKED ISSUE #2370: Shell busyloops when the PTY goes away
To reproduce:
* `killall Terminal`
* Observe the CPU usage growing to 100%
* Perhaps use this opportunity to warm your hands a bit

@alimpfard

### PR DESCRIPTION
**Pull request by alimpfard**
This fixes a bunch of FIXME's in LibLine.
Also handles the case where read() would read zero bytes in vt_dsr() and effectively block forever by erroring out.

Also disallows `^Z` in shell, because that was annoying.

Fixes #2370

Morale of this story: I do not Unix enough.

### CODE REVIEW

**Comment by bugaevc** [comment]
Somebody forgot to cc me :wink:

**Comment by alimpfard** [comment]
Curses.
I _always_ forget dammit.

I also do not memory, apparently.

**Comment by bugaevc** [comment]
> Curses.

ncurses, you surely mean

File: Applications/Terminal/main.cpp [hunk 1]
```diff
@@ -57,6 +57,7 @@
 static void run_command(int ptm_fd, String command)
 {
     pid_t pid = fork();
+
```
Comment (bugaevc) [inline Applications/Terminal/main.cpp:60]: I won't complain about this extra newline that has nothing to do with this commit if you add proper handling for the `pid < 0` case :smile:

**Comment by alimpfard** [comment]
> ncurses, you surely mean

I'm all about the original version :^)

File: Libraries/LibLine/Editor.cpp [hunk 2]
```diff
@@ -279,17 +282,25 @@ String Editor::get_line(const String& prompt)
                 m_refresh_needed = true;
                 continue;
             }
+
+            auto errno_save = errno;
```
Comment (bugaevc) [inline Libraries/LibLine/Editor.cpp:286]: Usually called `saved_erro`

File: Applications/Terminal/main.cpp (hunk 1 above)
Comment (alimpfard) [reply Applications/Terminal/main.cpp:60]: what if I just remove the extra newline :thinking:

File: Libraries/LibLine/Editor.cpp [hunk 3]
```diff
@@ -279,17 +282,25 @@ String Editor::get_line(const String& prompt)
...
         }
 
         m_incomplete_data.append(keybuf, nread);
         nread = m_incomplete_data.size();
 
-        // FIXME: exit()ing here is a bit off. Should communicate failure to caller somehow instead.
-        if (nread == 0)
-            exit(0);
+        if (nread == 0) {
+            dbg() << "Read failed (no chars)";
```
Comment (bugaevc) [inline Libraries/LibLine/Editor.cpp:301]: EOF is not a failure, it's just an EOF

**Comment by bugaevc** [comment]
So, have you figured out why it doesn't receive a SIGHUP, or?..

**Comment by alimpfard** [comment]
> So, have you figured out why it doesn't receive a SIGHUP, or?..

Nope. I don't think SIGHUP is being sent at all here, killall sends a SIGTERM and...nothing else happens

File: Libraries/LibLine/Editor.cpp (hunk 3 above)
Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp:301]: There's no reason to log there anyway

File: Applications/Terminal/main.cpp [hunk 4]
```diff
@@ -124,207 +130,206 @@ static void run_command(int ptm_fd, String command)
...
-    return window;
-}
-
-int main(int argc, char** argv)
-{
-    if (pledge("stdio tty rpath accept cpath wpath shared_buffer proc exec unix fattr", nullptr) < 0) {
-        perror("pledge");
-        return 1;
+    RefPtr<GUI::Window> create_settings_window(TerminalWidget & terminal)
+    {
```
Comment (bugaevc) [inline Applications/Terminal/main.cpp:135]: Ooof

Comment (alimpfard) [reply Applications/Terminal/main.cpp]: lol.
saw your other nitpick and forgot about that

File: Libraries/LibLine/Editor.cpp [hunk 5]
```diff
@@ -279,17 +282,23 @@ String Editor::get_line(const String& prompt)
...
+
             perror("read failed");
-            // FIXME: exit()ing here is a bit off. Should communicate failure to caller somehow instead.
-            exit(2);
+            dbg() << "Read failed: " << strerror(saved_errno);
+
+            if (saved_errno == EINVAL || saved_errno == EBADF)
+                return Error::ReadFailure;
+
+            return Error::Unspecified;
```
Comment (bugaevc) [inline Libraries/LibLine/Editor.cpp:294]: Why single out (double out?) those two error codes?

Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp:294]: because they're the only other error codes that `read()` can fail with in this scenario?

Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp:294]: To my (admittedly shit memory), read can fail with BADF, INTR, INVAL, FAULT and IO.
we're not doing any disk IO, so EIO shouldn't come out at all.
our buffer on the stack so FAULT is out too
INTR is handled, leaving the other two

Comment (bugaevc) [reply Libraries/LibLine/Editor.cpp:294]: `read()` can fail for way more reasons than you can ever imagine. Any device driver or any magical fine can return whatever errors it can think of.

> we're not doing any disk IO

Aren't we?

Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp:294]: we're reading from `stdin`...
if the drivers spit out something weird, that's just an unspecified error...
I guess there's no need for `Unspecified` then, I'll drop that.

Comment (bugaevc) [reply Libraries/LibLine/Editor.cpp:294]: > we're reading from `stdin`...

Aka whatever happens to be fd 0

Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp]: > Aka whatever happens to be fd 0

We're working on a level of abstraction here, LibLine assumes some stuff about that...I don't think worrying about things we don't consider legitimate read errors is that important.
Nonetheless, every error except INTR is just a read error now.

File: Libraries/LibLine/Editor.cpp [hunk 6]
```diff
@@ -279,17 +282,20 @@ String Editor::get_line(const String& prompt)
                 m_refresh_needed = true;
                 continue;
             }
+
+            auto saved_errno = errno;
+
             perror("read failed");
-            // FIXME: exit()ing here is a bit off. Should communicate failure to caller somehow instead.
-            exit(2);
+            dbg() << "Read failed: " << strerror(saved_errno);
```
Comment (bugaevc) [inline Libraries/LibLine/Editor.cpp:289]: `perror` should already print to `dbg()` log itself, so no need for `saved_errno` at all.

Unless you want to preserve `errno` for the caller; then use `ScopedValueRollback errno_restorer(errno);`

Comment (alimpfard) [reply Libraries/LibLine/Editor.cpp:289]: Very well.
please tell me I didn't forget to put errno back...I did...

File: Shell/main.cpp [hunk 7]
```diff
@@ -104,6 +104,9 @@ int main(int argc, char** argv)
         }
     });
 
+    // Ignore SIGTSTP as the shell should not be suspended with ^Z.
+    signal(SIGTSTP, [](auto) {});
```
Comment (bugaevc) [inline Shell/main.cpp:108]: Why not `SIG_IGN` it?
