### PR TITLE
Kernel: Fix incorrect SFMASK MSR value clobbering reserved bits

### LINKED ISSUE #11484: x86_64 boot does not work with WHPX enabled
This was introduced with e6df1c998804cca1848c634411b42d277d9ff265

it seems like WHPX does not like these or that qemu does not handle it correctly

Message:
```
ninja: Entering directory `/home/usr/serenity/Build/x86_64clang'
[0/2] Re-checking globbed directories...
[0/1] cd /home/usr/serenity/Build/x86_64clang && /usr/bin/cmake -E env SERENITY_ARCH=x86_64 /home/usr/serenity/Meta/run.sh
Windows Hypervisor Platform accelerator is operational
qemu-system-x86_64.exe: warning: nic e1000.0 has no peer
qemu-system-x86_64.exe: WHPX: Unexpected VP exit code 4
Guest crashed
HV crash parameters: (0 0 0 0 0)
```

According to [the documentation](https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/funcs/whvrunvirtualprocessor) this means `WHvRunVpExitReasonUnrecoverableException`

### PR DESCRIPTION
**Pull request by yeetari**
Fixes #11484

### CODE REVIEW

File: Kernel/Arch/x86/common/Processor.cpp [hunk 1]
```diff
@@ -236,12 +236,13 @@ UNMAP_AFTER_INIT void Processor::cpu_setup()
...
-    // Write the syscall entry point to the LSTAR MSR, and write the SFMASK MSR to clear rflags upon entry.
-    // The userspace rflags will be preserved in r11.
+    // Write the syscall entry point to the LSTAR MSR, and write the SFMASK MSR to clear rflags upon entry. The value
+    // set here clears most of rflags, but keeps the reserved and virtualization bits intact. The userspace rflags
+    // will be preserved in r11.
     MSR lstar_msr(MSR_LSTAR);
     MSR sfmask_msr(MSR_SFMASK);
     lstar_msr.set(reinterpret_cast<u64>(&syscall_entry));
-    sfmask_msr.set(~0x2);
+    sfmask_msr.set(0x257fd5u);
```
Comment (IdanHo) [inline Kernel/Arch/x86/common/Processor.cpp:245]: This looks good (although it might be nicer to extract this magical number to a constexpr constant), though the ordering of the comment and writes is a bit weird, can we separate the two into 2 separate comments and 2 separate MSR writes just for clarity and consistency with the rest of the writes?
