### PR TITLE
LibWeb: Add support to inspect DOM tree in OutOfProcessWebView

### LINKED ISSUE #5267: Browser: Crash when opening the Dom-Inspector
The Browser crashes, when you try to open the Dom-Inspector.  
The crash seems to be related to the multiprocess mode, due to it not appearing in single process mode.

<details>
<summary>Core Dump</summary>

```
[#0 CrashReporter(50:50)]: CrashReporter(50:50) Should already die
USERSPACE(54) ASSERTION FAILED: false
../Userland/Applications/Browser/Tab.cpp:330
[#0 Browser(54:54)]: 0x00000000  (?)

[#0 Browser(54:54)]: 0xc0197236  Kernel::Process::crash(int, unsigned int, bool) +0x2ee
[#0 Browser(54:54)]: 0xc019e8b1  Kernel::Process::sys$abort() +0x1f
[#0 Browser(54:54)]: 0xc019da9d  syscall_handler +0x9db
[#0 Browser(54:54)]: 0xc019d0ba  syscall_asm_entry +0x31
[#0 Browser(54:54)]: Process regions:
[#0 Browser(54:54)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 Browser(54:54)]: 01101000 -- 01500fff    00400000    RW  TA    Stack (Main thread)
[#0 Browser(54:54)]: 01502000 -- 01502fff    00001000    R    A    mmap
[#0 Browser(54:54)]: 01504000 -- 01504fff    00001000    RW S A    (null)
[#0 Browser(54:54)]: 01506000 -- 01506fff    00001000    RW   A    GraphicsBitmap [16x16]
[#0 Browser(54:54)]: 0150a000 -- 0150afff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/app-browser.png
[#0 Browser(54:54)]: 01510000 -- 0151ffff    00010000         A    malloc: ChunkedBlock(256)
[#0 Browser(54:54)]: 01521000 -- 01521fff    00001000    RW   A    Gfx::Bitmap [[32x32]] - Decoded PNG: /res/icons/32x32/app-browser.png
[#0 Browser(54:54)]: 01523000 -- 01523fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01525000 -- 01525fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01528000 -- 01528fff    00001000    RW   A    (null)
[#0 Browser(54:54)]: 0152a000 -- 0152bfff    00002000    RW   A    Thread-specific
[#0 Browser(54:54)]: 0152d000 -- 0152dfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01530000 -- 0153ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[#0 Browser(54:54)]: 01541000 -- 01544fff    00004000    R  S      /res/fonts/CsillaBold10.font
[#0 Browser(54:54)]: 01546000 -- 0154afff    00005000    R  S      /res/fonts/CsillaBold12.font
[#0 Browser(54:54)]: 0154c000 -- 0154cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01550000 -- 0155ffff    00010000    RW   A    malloc: ChunkedBlock(64)
[#0 Browser(54:54)]: 01561000 -- 0163afff    000da000    R         ELF_DYN: /bin/Browser
[#0 Browser(54:54)]: 0163c000 -- 0163cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01640000 -- 0164ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[#0 Browser(54:54)]: 01651000 -- 01654fff    00004000    R  S      /res/fonts/CsillaRegular10.font
[#0 Browser(54:54)]: 01656000 -- 0165afff    00005000    R  S      /res/fonts/CsillaRegular12.font
[#0 Browser(54:54)]: 0165c000 -- 0165cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01660000 -- 0166ffff    00010000    RW   A    malloc: ChunkedBlock(256)
[#0 Browser(54:54)]: 01671000 -- 01674fff    00004000    R  S      /res/fonts/KaticaBold10.font
[#0 Browser(54:54)]: 01676000 -- 0167afff    00005000    R  S      /res/fonts/KaticaBold12.font
[#0 Browser(54:54)]: 0167c000 -- 0167cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01680000 -- 0168ffff    00010000         A    malloc: ChunkedBlock(500)
[#0 Browser(54:54)]: 01691000 -- 01694fff    00004000    R  S      /res/fonts/KaticaRegular10.font
[#0 Browser(54:54)]: 01696000 -- 0169afff    00005000    R  S      /res/fonts/KaticaRegular12.font
[#0 Browser(54:54)]: 0169c000 -- 0169cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 016a0000 -- 016affff    00010000    RW   A    malloc: ChunkedBlock(1016)
[#0 Browser(54:54)]: 016b1000 -- 016b4fff    00004000    R  S      /res/fonts/LizaBlack10.font
[#0 Browser(54:54)]: 016b6000 -- 016b9fff    00004000    R  S      /res/fonts/LizaBold10.font
[#0 Browser(54:54)]: 016bb000 -- 016bbfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 016bd000 -- 016bdfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 016c0000 -- 016cffff    00010000    RW   A    malloc: ChunkedBlock(8)
[#0 Browser(54:54)]: 016d1000 -- 016dafff    0000a000    R  S      /res/fonts/LizaBlack24.font
[#0 Browser(54:54)]: 016dc000 -- 016dcfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 016e0000 -- 016effff    00010000    RW   A    malloc: ChunkedBlock(64)
[#0 Browser(54:54)]: 016f1000 -- 016fafff    0000a000    R  S      /res/fonts/LizaBold24.font
[#0 Browser(54:54)]: 016fc000 -- 016fcfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01700000 -- 0170ffff    00010000    RW   A    malloc: ChunkedBlock(16)
[#0 Browser(54:54)]: 01711000 -- 01714fff    00004000    R  S      /res/fonts/LizaRegular10.font
[#0 Browser(54:54)]: 01716000 -- 0171bfff    00006000    R  S      /res/fonts/PebbletonBold14.font
[#0 Browser(54:54)]: 01720000 -- 0172ffff    00010000         A    malloc: ChunkedBlock(32752)
[#0 Browser(54:54)]: 01731000 -- 0173efff    0000e000    R  S      /res/fonts/LizaBlack36.font
[#0 Browser(54:54)]: 01740000 -- 0174dfff    0000e000    R  S      /res/fonts/LizaBold36.font
[#0 Browser(54:54)]: 0174f000 -- 01758fff    0000a000    R  S      /res/fonts/LizaRegular24.font
[#0 Browser(54:54)]: 0175a000 -- 01767fff    0000e000    R  S      /res/fonts/LizaRegular36.font
[#0 Browser(54:54)]: 01769000 -- 0176efff    00006000    R  S      /res/fonts/PebbletonRegular14.font
[#0 Browser(54:54)]: 01770000 -- 01770fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/filetype-html.png
[#0 Browser(54:54)]: 01772000 -- 01772fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/new-tab.png
[#0 Browser(54:54)]: 01774000 -- 01774fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/app-browser.png
[#0 Browser(54:54)]: 01776000 -- 01776fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/go-back.png
[#0 Browser(54:54)]: 01778000 -- 01778fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/go-forward.png
[#0 Browser(54:54)]: 0177a000 -- 0177afff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/go-home.png
[#0 Browser(54:54)]: 0177c000 -- 0177cfff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/reload.png
[#0 Browser(54:54)]: 0177e000 -- 0177efff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/undo.png
[#0 Browser(54:54)]: 01780000 -- 01780fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/redo.png
[#0 Browser(54:54)]: 01782000 -- 01782fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-cut.png
[#0 Browser(54:54)]: 01784000 -- 01784fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-copy.png
[#0 Browser(54:54)]: 01786000 -- 01786fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/paste.png
[#0 Browser(54:54)]: 01788000 -- 01788fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/delete.png
[#0 Browser(54:54)]: 0178a000 -- 0178afff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/select-all.png
[#0 Browser(54:54)]: 0178e000 -- 0178efff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/close-tab.png
[#0 Browser(54:54)]: 01790000 -- 01889fff    000fa000    RW S A    (null)
[#0 Browser(54:54)]: 0188b000 -- 01984fff    000fa000    RW S A    (null)
[#0 Browser(54:54)]: 01986000 -- 01986fff    00001000    RW   A    Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/bookmark-contour.png
[#0 Browser(54:54)]: 01988000 -- 01ab3fff    0012c000    RW S A    (null)
[#0 Browser(54:54)]: 01ab5000 -- 01be0fff    0012c000    RW S A    (null)
[#0 Browser(54:54)]: 02230000 -- 0223ffff    00010000    RW   A    malloc: ChunkedBlock(128)
[#0 Browser(54:54)]: 02250000 -- 0225ffff    00010000    RW   A    malloc: ChunkedBlock(32)
[#0 Browser(54:54)]: 02270000 -- 0227ffff    00010000    RW   A    malloc: ChunkedBlock(256)
[#0 Browser(54:54)]: 02290000 -- 0229ffff    00010000    RW   A    malloc: ChunkedBlock(500)
[#0 Browser(54:54)]: 022b0000 -- 022bffff    00010000    RW   A    malloc: ChunkedBlock(1016)
[#0 Browser(54:54)]: 022d0000 -- 022dffff    00010000         A    malloc: ChunkedBlock(2032)
[#0 Browser(54:54)]: 022f0000 -- 022fffff    00010000    RW   A    malloc: ChunkedBlock(4088)
[#0 Browser(54:54)]: 02310000 -- 0231ffff    00010000         A    malloc: ChunkedBlock(8184)
[#0 Browser(54:54)]: 02330000 -- 0233ffff    00010000    RW   A    malloc: ChunkedBlock(16376)
[#0 Browser(54:54)]: 03320000 -- 0332ffff    00010000         A    malloc: ChunkedBlock(2032)
[#0 Browser(54:54)]: 03340000 -- 0334ffff    00010000         A    malloc: ChunkedBlock(4088)
[#0 Browser(54:54)]: 03360000 -- 0336ffff    00010000         A    malloc: ChunkedBlock(8184)
[#0 Browser(54:54)]: 03380000 -- 0338ffff    00010000         A    malloc: ChunkedBlock(16376)
[#0 Browser(54:54)]: 033a0000 -- 033affff    00010000         A    malloc: ChunkedBlock(32752)
[#0 Browser(54:54)]: 033c0000 -- 033cffff    00010000         A    malloc: ChunkedBlock(32752)
[#0 Browser(54:54)]: 033e0000 -- 033effff    00010000         A    malloc: BigAllocationBlock
[#0 Browser(54:54)]: 03400000 -- 0340ffff    00010000         A    malloc: BigAllocationBlock
[#0 Browser(54:54)]: 03420000 -- 0342ffff    00010000         A    malloc: BigAllocationBlock
[#0 Browser(54:54)]: 0ae2a000 -- 0b0b8fff    0028f000    R XS      libweb.so: .text
[#0 Browser(54:54)]: 0b0b9000 -- 0b0d6fff    0001e000    RW   A    libweb.so: .data
[#0 Browser(54:54)]: 0c804000 -- 0c847fff    00044000    R XS      /usr/lib/Loader.so
[#0 Browser(54:54)]: 0c848000 -- 0c849fff    00002000    RW   A    /usr/lib/Loader.so (data-rw)
[#0 Browser(54:54)]: 1893a000 -- 1893dfff    00004000    R XS      libthread.so: .text
[#0 Browser(54:54)]: 1893e000 -- 1893efff    00001000    RW   A    libthread.so: .data
[#0 Browser(54:54)]: 2486c000 -- 24883fff    00018000    R XS      libgcc_s.so: .text
[#0 Browser(54:54)]: 24884000 -- 24884fff    00001000    RW   A    libgcc_s.so: .data
[#0 Browser(54:54)]: 26c99000 -- 26c9bfff    00003000    R XS      libpthread.so: .text
[#0 Browser(54:54)]: 26c9c000 -- 26c9cfff    00001000    RW   A    libpthread.so: .data
[#0 Browser(54:54)]: 322f4000 -- 32318fff    00025000    R XS      libregex.so: .text
[#0 Browser(54:54)]: 32319000 -- 32319fff    00001000    RW   A    libregex.so: .data
[#0 Browser(54:54)]: 34f52000 -- 34fb6fff    00065000    R X       libc.so: .text
[#0 Browser(54:54)]: 34fb7000 -- 34fb9fff    00003000    RW   A    libc.so: .data
[#0 Browser(54:54)]: 3633e000 -- 36366fff    00029000    R XS      /bin/Browser: .text
[#0 Browser(54:54)]: 36367000 -- 36368fff    00002000    RW   A    /bin/Browser: .data
[#0 Browser(54:54)]: 3eed9000 -- 3eed9fff    00001000    R XS      libsystem.so: .text
[#0 Browser(54:54)]: 3eeda000 -- 3eedafff    00001000    RW   A    libsystem.so: .data
[#0 Browser(54:54)]: 42181000 -- 421b5fff    00035000    R XS      libcore.so: .text
[#0 Browser(54:54)]: 421b6000 -- 421b7fff    00002000    RW   A    libcore.so: .data
[#0 Browser(54:54)]: 53347000 -- 53348fff    00002000    R XS      libm.so: .text
[#0 Browser(54:54)]: 53349000 -- 53349fff    00001000    RW   A    libm.so: .data
[#0 Browser(54:54)]: 575d6000 -- 575f0fff    0001b000    R XS      libtls.so: .text
[#0 Browser(54:54)]: 575f1000 -- 575f1fff    00001000    RW   A    libtls.so: .data
[#0 Browser(54:54)]: 5b1ec000 -- 5b1effff    00004000    R XS      libtextcodec.so: .text
[#0 Browser(54:54)]: 5b1f0000 -- 5b1f0fff    00001000    RW   A    libtextcodec.so: .data
[#0 Browser(54:54)]: 5c837000 -- 5c842fff    0000c000    R XS      libimagedecoderclient.so: .text
[#0 Browser(54:54)]: 5c843000 -- 5c843fff    00001000    RW   A    libimagedecoderclient.so: .data
[#0 Browser(54:54)]: 6a308000 -- 6a311fff    0000a000    R XS      libmarkdown.so: .text
[#0 Browser(54:54)]: 6a312000 -- 6a312fff    00001000    RW   A    libmarkdown.so: .data
[#0 Browser(54:54)]: 71a8d000 -- 71ae8fff    0005c000    R XS      libgfx.so: .text
[#0 Browser(54:54)]: 71ae9000 -- 71aebfff    00003000    RW   A    libgfx.so: .data
[#0 Browser(54:54)]: 757e8000 -- 75921fff    0013a000    R XS      libgui.so: .text
[#0 Browser(54:54)]: 75922000 -- 7592cfff    0000b000    RW   A    libgui.so: .data
[#0 Browser(54:54)]: 7b772000 -- 7b77dfff    0000c000    R XS      libgemini.so: .text
[#0 Browser(54:54)]: 7b77e000 -- 7b77efff    00001000    RW   A    libgemini.so: .data
[#0 Browser(54:54)]: 7d7c1000 -- 7d7d6fff    00016000    R XS      libdesktop.so: .text
[#0 Browser(54:54)]: 7d7d7000 -- 7d7d7fff    00001000    RW   A    libdesktop.so: .data
[#0 Browser(54:54)]: 84017000 -- 840f7fff    000e1000    R XS      libjs.so: .text
[#0 Browser(54:54)]: 840f8000 -- 840fefff    00007000    RW   A    libjs.so: .data
[#0 Browser(54:54)]: 86f50000 -- 86f51fff    00002000    R XS      libsyntax.so: .text
[#0 Browser(54:54)]: 86f52000 -- 86f52fff    00001000    RW   A    libsyntax.so: .data
[#0 Browser(54:54)]: 88516000 -- 8852efff    00019000    R XS      libprotocol.so: .text
[#0 Browser(54:54)]: 8852f000 -- 88531fff    00003000    RW   A    libprotocol.so: .data
[#0 Browser(54:54)]: 8b349000 -- 8b35ffff    00017000    R XS      libcrypto.so: .text
[#0 Browser(54:54)]: 8b360000 -- 8b360fff    00001000    RW   A    libcrypto.so: .data
[#0 Browser(54:54)]: 8c7bb000 -- 8c7bbfff    00001000    R XS      libcrypt.so: .text
[#0 Browser(54:54)]: 8c7bc000 -- 8c7bcfff    00001000    RW   A    libcrypt.so: .data
[#0 Browser(54:54)]: b6551000 -- b6555fff    00005000    R XS      libipc.so: .text
[#0 Browser(54:54)]: b6556000 -- b6556fff    00001000    RW   A    libipc.so: .data
[#0 Browser(54:54)]: Kernel regions:
[#0 Browser(54:54)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 Browser(54:54)]: c0801000 -- c0900fff    00100000    RW   A    kmalloc subheap
[#0 Browser(54:54)]: c0904000 -- c0904fff    00001000    RW   A    HPET MMIO
[#0 Browser(54:54)]: c0906000 -- c0906fff    00001000    R X  A    Signal trampolines
[#0 Browser(54:54)]: c0908000 -- c0917fff    00010000    RW  TA    Kernel Stack (Thread 0)
[#0 Browser(54:54)]: c092a000 -- c0939fff    00010000    RW  TA    Kernel Stack (Thread 2)
[#0 Browser(54:54)]: c093b000 -- c094afff    00010000    RW  TA    Kernel Stack (Thread 3)
[#0 Browser(54:54)]: c094c000 -- c094cfff    00001000     W        UHCI Framelist
[#0 Browser(54:54)]: c094e000 -- c094ffff    00002000     W        UHCI Queue Head Pool
[#0 Browser(54:54)]: c0951000 -- c0952fff    00002000     W        UHCI Transfer Descriptor Pool
[#0 Browser(54:54)]: c0954000 -- c0963fff    00010000    RW  TA    Kernel Stack (Thread 4)
[#0 Browser(54:54)]: c0965000 -- c0965fff    00001000    RW        E1000 RX
[#0 Browser(54:54)]: c0967000 -- c0967fff    00001000    RW        E1000 TX
[#0 Browser(54:54)]: c0969000 -- c0988fff    00020000    RW   A    E1000 MMIO
[#0 Browser(54:54)]: c098a000 -- c098bfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c098d000 -- c098efff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c0990000 -- c0991fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c0993000 -- c0994fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c0996000 -- c0997fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c0999000 -- c099afff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c099c000 -- c099dfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c099f000 -- c09a0fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09a2000 -- c09a3fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09a5000 -- c09a6fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09a8000 -- c09a9fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09ab000 -- c09acfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09ae000 -- c09affff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09b1000 -- c09b2fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09b4000 -- c09b5fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09b7000 -- c09b8fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09ba000 -- c09bbfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09bd000 -- c09befff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09c0000 -- c09c1fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09c3000 -- c09c4fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09c6000 -- c09c7fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09c9000 -- c09cafff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09cc000 -- c09cdfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09cf000 -- c09d0fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09d2000 -- c09d3fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09d5000 -- c09d6fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09d8000 -- c09d9fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09db000 -- c09dcfff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09de000 -- c09dffff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09e1000 -- c09e2fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09e4000 -- c09e5fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09e7000 -- c09e8fff    00002000    RW        E1000 RX buffer
[#0 Browser(54:54)]: c09ea000 -- c09ebfff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09ed000 -- c09eefff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09f0000 -- c09f1fff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09f3000 -- c09f4fff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09f6000 -- c09f7fff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09f9000 -- c09fafff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09fc000 -- c09fdfff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c09ff000 -- c0a00fff    00002000    RW        E1000 TX buffer
[#0 Browser(54:54)]: c0a02000 -- c0a02fff    00001000    RW   A    Ext2FS: Block group descriptors
[#0 Browser(54:54)]: c0a04000 -- c13c7fff    009c4000    RW   A    KBuffer
[#0 Browser(54:54)]: c13c9000 -- c1403fff    0003b000    RW   A    KBuffer
[#0 Browser(54:54)]: c1405000 -- c1405fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1407000 -- c1407fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1409000 -- c1409fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c140b000 -- c141afff    00010000    RW  TA    Kernel Stack (Thread 5)
[#0 Browser(54:54)]: c141c000 -- c141cfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c141e000 -- c141efff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1420000 -- c1420fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1422000 -- c1431fff    00010000    RW  TA    Kernel Stack (Thread 6)
[#0 Browser(54:54)]: c1433000 -- c1442fff    00010000    RW   A    Kernel Packet Buffer
[#0 Browser(54:54)]: c0919000 -- c0919fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c091b000 -- c091bfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c091d000 -- c091dfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c091f000 -- c091ffff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c0921000 -- c0921fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c0923000 -- c0923fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c0925000 -- c0925fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c0927000 -- c0927fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1455000 -- c1455fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1457000 -- c1457fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1459000 -- c1459fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c145b000 -- c145bfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c145d000 -- c147cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c147e000 -- c149dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c149f000 -- c14befff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1444000 -- c1444fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c14c0000 -- c14dffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c14e1000 -- c1500fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1502000 -- c1521fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1523000 -- c1542fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1544000 -- c1563fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1565000 -- c1584fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1586000 -- c15a5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c15a7000 -- c15c6fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c15c8000 -- c15e7fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c15e9000 -- c1608fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c160a000 -- c1629fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c162b000 -- c164afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c164c000 -- c166bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c166d000 -- c168cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c168e000 -- c16adfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c16af000 -- c16cefff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c16d0000 -- c16effff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c16f1000 -- c1710fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1712000 -- c1731fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1733000 -- c1752fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1754000 -- c1773fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1775000 -- c1794fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1796000 -- c17b5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c17b7000 -- c17d6fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c17d8000 -- c17e7fff    00010000    RW  TA    Kernel Stack (Thread 8)
[#0 Browser(54:54)]: c17e9000 -- c17f8fff    00010000    RW  TA    Kernel Stack (Thread 9)
[#0 Browser(54:54)]: c17fa000 -- c1809fff    00010000    RW  TA    Kernel Stack (Thread 10)
[#0 Browser(54:54)]: c180b000 -- c181afff    00010000    RW  TA    Kernel Stack (Thread 11)
[#0 Browser(54:54)]: c181c000 -- c182bfff    00010000    RW  TA    Kernel Stack (Thread 12)
[#0 Browser(54:54)]: c182d000 -- c183cfff    00010000    RW  TA    Kernel Stack (Thread 13)
[#0 Browser(54:54)]: c183e000 -- c184dfff    00010000    RW  TA    Kernel Stack (Thread 14)
[#0 Browser(54:54)]: c184f000 -- c185efff    00010000    RW  TA    Kernel Stack (Thread 15)
[#0 Browser(54:54)]: c1860000 -- c186ffff    00010000    RW  TA    Kernel Stack (Thread 16)
[#0 Browser(54:54)]: c1871000 -- c1880fff    00010000    RW  TA    Kernel Stack (Thread 17)
[#0 Browser(54:54)]: c1882000 -- c1891fff    00010000    RW  TA    Kernel Stack (Thread 18)
[#0 Browser(54:54)]: c1893000 -- c18a2fff    00010000    RW  TA    Kernel Stack (Thread 19)
[#0 Browser(54:54)]: c18a4000 -- c18b3fff    00010000    RW  TA    Kernel Stack (Thread 20)
[#0 Browser(54:54)]: c18b5000 -- c18c4fff    00010000    RW  TA    Kernel Stack (Thread 21)
[#0 Browser(54:54)]: c18c6000 -- c18d5fff    00010000    RW  TA    Kernel Stack (Thread 22)
[#0 Browser(54:54)]: c18d7000 -- c18e6fff    00010000    RW  TA    Kernel Stack (Thread 23)
[#0 Browser(54:54)]: c1446000 -- c1446fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1448000 -- c1448fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c144a000 -- c144afff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c144c000 -- c144cfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c144e000 -- c144efff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1450000 -- c1450fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c1452000 -- c1452fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c18e8000 -- c18e8fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c18ea000 -- c1909fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c190b000 -- c192afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c192c000 -- c194bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c194d000 -- c195cfff    00010000    RW  TA    Kernel Stack (Thread 24)
[#0 Browser(54:54)]: c195e000 -- c197dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c197f000 -- c199efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c19a0000 -- c19bffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c19c1000 -- c19e0fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c19e2000 -- c1a01fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1a03000 -- c1e02fff    00400000    RW   A    KBuffer
[#0 Browser(54:54)]: c1e04000 -- c1e23fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1e25000 -- c1e44fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1e46000 -- c1e65fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1e67000 -- c1e86fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1e88000 -- c1ea7fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1ea9000 -- c1ec8fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1eca000 -- c1ee9fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1eeb000 -- c1f0afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1f0c000 -- c1f2bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1f2d000 -- c1f4cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1f4e000 -- c1f6dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1f6f000 -- c1f8efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1f90000 -- c1faffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1fb3000 -- c1fd2fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1fd4000 -- c1ff3fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c1ff5000 -- c2014fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2016000 -- c2035fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2037000 -- c2056fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2058000 -- c2077fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2079000 -- c2098fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c209a000 -- c20b9fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c20bb000 -- c20dafff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c20dc000 -- c20fbfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c20fd000 -- c211cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c211e000 -- c213dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c213f000 -- c215efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2160000 -- c217ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2181000 -- c21a0fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c21a2000 -- c21c1fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c21c3000 -- c21e2fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c25e5000 -- c2604fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2606000 -- c2625fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c21e4000 -- c21e4fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c21e6000 -- c2205fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2207000 -- c2226fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2228000 -- c2247fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2249000 -- c2268fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c226a000 -- c2289fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c228b000 -- c22aafff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c22ac000 -- c22cbfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c22cd000 -- c22ecfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c22ee000 -- c230dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c230f000 -- c230ffff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c2311000 -- c2330fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2332000 -- c2351fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2353000 -- c2372fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2374000 -- c2393fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2395000 -- c23b4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c23b6000 -- c23d5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c23d7000 -- c23f6fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c23f8000 -- c2417fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2419000 -- c2438fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c243a000 -- c2459fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c245b000 -- c247afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c247c000 -- c249bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c249d000 -- c24bcfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c24be000 -- c24ddfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c24df000 -- c24fefff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2500000 -- c251ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2521000 -- c2540fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2542000 -- c2561fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2563000 -- c2582fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2584000 -- c25a3fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c25a5000 -- c25a5fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c25a7000 -- c25a7fff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c25a9000 -- c25c8fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2627000 -- c2646fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2648000 -- c2667fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2669000 -- c2688fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c268a000 -- c26a9fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c26ab000 -- c26cafff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c26cc000 -- c26ebfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c26ed000 -- c270cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c270e000 -- c272dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c272f000 -- c274efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2750000 -- c276ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2771000 -- c2790fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2792000 -- c27b1fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c27b3000 -- c27d2fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c27d4000 -- c27f3fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c27f5000 -- c2814fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2816000 -- c2835fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2837000 -- c2856fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2c59000 -- c2c78fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2c7a000 -- c2c99fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2858000 -- c2877fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2879000 -- c2898fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c289a000 -- c28b9fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c25ca000 -- c25d9fff    00010000    RW  TA    Kernel Stack (Thread 25)
[#0 Browser(54:54)]: c28cc000 -- c28ebfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c28ed000 -- c290cfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2c9b000 -- c309afff    00400000    RW   A    KBuffer
[#0 Browser(54:54)]: c349d000 -- c389cfff    00400000    RW   A    KBuffer
[#0 Browser(54:54)]: c290e000 -- c2a0dfff    00100000    RW   A    kmalloc subheap
[#0 Browser(54:54)]: c2a0f000 -- c2a2efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2a30000 -- c2a4ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2a51000 -- c2a70fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c25db000 -- c25dbfff    00001000    RW   A    Ext2FS: Cached bitmap block
[#0 Browser(54:54)]: c2ac5000 -- c2ae4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2ae6000 -- c2b05fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2bee000 -- c2c0dfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2c0f000 -- c2c2efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c30bd000 -- c30ccfff    00010000    RW  TA    Kernel Stack (Thread 29)
[#0 Browser(54:54)]: c30ce000 -- c30edfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c30ef000 -- c310efff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3110000 -- c312ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c31a5000 -- c31c4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c31c6000 -- c31e5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c325b000 -- c327afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c327c000 -- c329bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c329d000 -- c339cfff    00100000    RW   A    kmalloc subheap
[#0 Browser(54:54)]: c3412000 -- c3431fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3433000 -- c3452fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2b28000 -- c2b47fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2b49000 -- c2b68fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c31e7000 -- c3206fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3208000 -- c3227fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3475000 -- c3494fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c389e000 -- c38bdfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3922000 -- c3941fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3943000 -- c3962fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c39c7000 -- c39e6fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c39e8000 -- c3a07fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c51a3000 -- c69a0fff    017fe000    RW   A    KBuffer
[#0 Browser(54:54)]: c3985000 -- c39a4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3a09000 -- c3a28fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3a4b000 -- c3a6afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3a6c000 -- c3a8bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c75a1000 -- c8d9efff    017fe000    RW   A    KBuffer
[#0 Browser(54:54)]: c3a8d000 -- c3aacfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3aae000 -- c3acdfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c9da0000 -- cbd9efff    01fff000    RW   A    KBuffer
[#0 Browser(54:54)]: c2b8b000 -- c2baafff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2bac000 -- c2bcbfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c33e0000 -- c33fffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c38bf000 -- c38defff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3b53000 -- c3b72fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3b74000 -- c3b93fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3bf8000 -- c3c17fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3c19000 -- c3c38fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3c9d000 -- c3cbcfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3cbe000 -- c3cddfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c25dd000 -- c25ddfff    00001000    RW   A    KBuffer
[#0 Browser(54:54)]: ccda0000 -- ced9efff    01fff000    RW   A    KBuffer
[#0 Browser(54:54)]: c3131000 -- c3150fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3152000 -- c3171fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3b95000 -- c3bb4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3bb6000 -- c3bd5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3d42000 -- c3d61fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3d63000 -- c3d82fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3d84000 -- c3e83fff    00100000    RW   A    kmalloc subheap
[#0 Browser(54:54)]: c3ee8000 -- c3f07fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3f09000 -- c3f28fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3173000 -- c3192fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3229000 -- c3248fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2a83000 -- c2a92fff    00010000    RW  TA    Kernel Stack (Thread 54)
[#0 Browser(54:54)]: c3c3a000 -- c3c59fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3c5b000 -- c3c7afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3f2a000 -- c3f49fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3f4b000 -- c3f6afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3f6c000 -- c3f8bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3f8d000 -- c3facfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3fae000 -- c3fcdfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3fcf000 -- c3feefff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3ff0000 -- c400ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4011000 -- c4030fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4032000 -- c4051fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2b07000 -- c2b16fff    00010000    RW  TA    Kernel Stack (Thread 55)
[#0 Browser(54:54)]: c4053000 -- c4072fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4074000 -- c4093fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4095000 -- c40b4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c40b6000 -- c40d5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c40d7000 -- c40f6fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c40f8000 -- c4117fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4119000 -- c4138fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2b6a000 -- c2b79fff    00010000    RW  TA    Kernel Stack (Thread 56)
[#0 Browser(54:54)]: c3b11000 -- c3b30fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3cdf000 -- c3cfefff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3d00000 -- c3d1ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3e85000 -- c3ea4fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c3ea6000 -- c3ec5fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c2bcd000 -- c2bdcfff    00010000    RW  TA    Kernel Stack (Thread 57)
[#0 Browser(54:54)]: c413a000 -- c4159fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c415b000 -- c417afff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c417c000 -- c419bfff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4200000 -- c421ffff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: c4221000 -- c4240fff    00020000    RW   A    DoubleBuffer
[#0 Browser(54:54)]: Browser(54:54) Should already die
```

</details>

### PR DESCRIPTION
**Pull request by ant1441**
This introduces a mechanism for inspecting the DOM tree when using the `OutOfProcessWebView`.
An IPC mechanism is implemented to request a JSON representation of the DOM tree.

A new `DOMTreeJSONModel` is added, to process the JSON representation as required.

The original mechanism is still used for the `InProcessWebView`.
The new mechanism could be used in both cases, but as the new way does not have feature
parity, we will leave the original in place for now.

## Caveats:
* Performance is not the best. I believe this is due to inefficient navigation of the JSON tree.
* The JSON object could become extremely large for large pages.
  This could be handled by adding more IPC calls to query details on individual elements,
  rather than including all details in the JSON object.
* Text Nodes do not have their content displayed.
* The 'selected' element is not highlighted
  An IPC call for marking an element 'selected' could be added.
* The layout tree view is not currently supported.
* Styles and Computed Styles are not currently supported.

Fixes #5267

### CODE REVIEW

File: Userland/Libraries/LibWeb/DOM/Document.cpp [hunk 1]
```diff
@@ -920,4 +920,14 @@ void Document::set_cookie(String cookie_string, Cookie::Source source)
         page->client().page_did_set_cookie(m_url, cookie.value(), source);
 }
 
+String Document::dump_dom_tree()
```
Comment (MaxWipfli) [inline Userland/Libraries/LibWeb/DOM/Document.cpp:923]: Maybe this should specifiy that it's JSON, so `dump_dom_tree_as_json()` or something like that.
And can't this function be `const`? (I don't know, I'm just asking.)

File: Userland/Libraries/LibWeb/DOM/Node.h [hunk 2]
```diff
@@ -162,6 +163,9 @@ class Node
 
     bool is_host_including_inclusive_ancestor_of(const Node&) const;
 
+    // Used for dumping the DOM Tree
+    void dump_tree_json(JsonObjectSerializer<StringBuilder>&) const;
```
Comment (MaxWipfli) [inline Userland/Libraries/LibWeb/DOM/Node.h:167]: Maybe call this `serialize_tree_as_json` (or just `serialize_tree`) or something like this, then it's maybe a bit clearer what this does.

File: Userland/Libraries/LibWeb/DOM/Node.cpp [hunk 3]
```diff
@@ -606,4 +606,34 @@ RefPtr<Document> Node::owner_document() const
...
+    if (is_element()) {
+        auto element = downcast<DOM::Element>(this);
+        if (element->has_attributes()) {
+            auto attributes = object.add_object("attributes");
+            element->for_each_attribute([&attributes](auto& name, auto& value) {
+                attributes.add(name, value);
+            });
+        }
+    }
+
```
Comment (MaxWipfli) [inline Userland/Libraries/LibWeb/DOM/Node.cpp:629]: You could check `is_text()` here, and if that is the case, you could:
```cpp
else if (is_text()) {
    auto text_node = downcast<DOM::Text>(this);
    object.add("text", text_node->data());
}
```
This way, you could get the text contents into the JSON tree.

**Review by MaxWipfli — COMMENTED** [review]
Looks like a good start. Performance will definitely be a concern for larger trees, but we can sort that out later. :^)

File: Userland/Libraries/LibWeb/DOM/Node.cpp (hunk 3 above)
Comment (ant1441) [reply Userland/Libraries/LibWeb/DOM/Node.cpp:633]: I was unsure if this text would cause performance issues, but I think the performance impact is elsewhere, so I will add this :+1: 

I also noticed I'm doing `is_element()` twice, so can simplify that :)
