### PR TITLE
Kernel: Fixes for boot with acpi=off

### LINKED ISSUE #11980: ASSERTION FAILED: m_ptr when booting with acpi=off
When specifying acpi=off the kernel crashes during boot. Here is the complete serial log (using `serial_debug`):

```
0.000 [#0 Kernel]: Adding kmalloc subheap @ 0xc1fa0000 with size 2097152
0.000 [Kernel]: Loading kernel symbol table...
0.000 [Kernel]: CPU[0]: Supported features: nx pae pge sse tsc sep syscall mmx sse2 sse3 fxsr lm hypervisor
0.000 [Kernel]: CPU[0]: No RDRAND support detected, randomness will be poor
0.000 [Kernel]: CPU[0]: Physical address bit width: 40
0.000 [Kernel]: CPU[0]: Virtual address bit width: 48
0.000 [#0 Kernel]: Initializing unhandled interrupt handlers
0.000 [Kernel]: CPU[0]: CPUID hypervisor signature 'KVMKVMKVM' (0x4b4d564b 0x564b4d56 0x4d), max leaf 0x40000001
0.000 [Kernel]: Kernel Commandline: serial_debug acpi=off root=/dev/hda1
0.000 [Kernel]: MM: Multiboot mmap: address=0x00000000, length=654336, type=1
0.000 [Kernel]: MM: Got an unaligned physical_region from the bootloader; correcting length 654336 by 3072 bytes
0.000 [Kernel]: MM: Multiboot mmap: address=0x0009fc00, length=1024, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x000f0000, length=65536, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x00100000, length=535691264, type=1
0.000 [Kernel]: MM: Multiboot mmap: address=0x1ffe0000, length=131072, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0xfeffc000, length=16384, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0xfffc0000, length=262144, type=2
0.000 [Kernel]: MM: Contiguous reserved range from P000000000009fc00, length is 394240
0.000 [Kernel]: MM: Contiguous reserved range from P000000001ffe0000, length is 3758227456
0.000 [Kernel]: MM: boot_pdpt @ P0000000000110000
0.000 [Kernel]: MM: boot_pd0 @ P0000000000111000
0.000 [Kernel]: MM: boot_pd_kernel @ P0000000000132000
0.000 [Kernel]: MM: Physical page entries: 0xc2801000 - 0xc3001fff (size 0x00801000)
0.000 [Kernel]: MM: Low memory range @ P0000000000000000 - P00000000000fffff (size 0x100000)
0.000 [Kernel]: MM: Kernel range @ P0000000000200000 - P00000000026a0fff (size 0x24a1000)
0.000 [Kernel]: MM: Physical Pages range @ P00000000026a2000 - P0000000002ea7fff (size 0x806000)
0.000 [Kernel]: MM: Super physical region: P0000000000201000 - P0000000000600fff (size 0x400000)
0.000 [Kernel]:  * 4x PhysicalZone (1 MiB) @ 0000000000201000-0000000000500fff
0.000 [Kernel]: MM: User physical region: P0000000000101000 - P00000000001fefff (size 0xfe000)
0.000 [Kernel]: MM: User physical region: P0000000002ea8000 - P000000001ffdffff (size 0x1d138000)
0.000 [Kernel]:  * 29x PhysicalZone (16 MiB) @ 0000000002ea8000-000000001eea7fff
0.000 [Kernel]:  * 1x PhysicalZone (1 MiB) @ 000000001fea8000-000000001fea7fff
0.000 [#0 Kernel]: Early access to ACPI tables for interrupt setup
0.000 [#0 Kernel]: Can't enable SMP mode without IOAPIC mode being enabled
0.000 [Kernel]: Interrupts: Switch to IOAPIC mode
0.000 [#0 Kernel]: Interrupts: MADT @ P 0x1ffe182d
0.000 [Kernel]: PIC: Cascading mode, vectors 0x50-0x5f
0.000 [#0 Kernel]: IOAPIC found @ MADT entry 1, MMIO Registers @ P00000000fec00000
0.000 [Kernel]: IOAPIC ID: 0x0
0.000 [Kernel]: IOAPIC Version: 0x11, redirection entries: 24
0.000 [Kernel]: IOAPIC Arbitration ID 0x0
0.000 [#0 Kernel]: Interrupts: Overriding INT 0x0 with GSI 2, for bus 0x0
0.000 [#0 Kernel]: Interrupts: Overriding INT 0x5 with GSI 5, for bus 0x0
0.000 [#0 Kernel]: Interrupts: Overriding INT 0x9 with GSI 9, for bus 0x0
0.000 [#0 Kernel]: Interrupts: Overriding INT 0xa with GSI 10, for bus 0x0
0.000 [#0 Kernel]: Interrupts: Overriding INT 0xb with GSI 11, for bus 0x0
0.000 [#0 Kernel]: Interrupts: Detected Dual i8259 - Disabled
0.000 [#0 Kernel]: Interrupts: Detected IOAPIC
0.000 [#0 Kernel]: MultiProcessor: Floating Pointer Structure @ P00000000000f5ba0
0.000 [#0 Kernel]: Features 0, IMCR? 0
0.000 [#0 Kernel]: MultiProcessor: Get PCI IOAPIC redirections
0.000 [#0 Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 4, IOAPIC 0, IOAPIC INTIN 9
0.000 [#0 Kernel]: Interrupts: Bus 0, polarity 1, trigger mode 0, INT 12, IOAPIC 0, IOAPIC INTIN 11
0.000 [#0 Kernel]: Interrupts: Bus 0, polarity 1, PCI device 1, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 9
0.000 [#0 Kernel]: Interrupts: Bus 0, polarity 1, PCI device 3, trigger mode 0, INT 0, IOAPIC 0, IOAPIC INTIN 11
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [Kernel]: RTC:  Year: 2022, month: 1, day: 18, hour: 0, minute: 6, second: 26
0.000 [Kernel]: PIT: 250 Hz, square wave (0x000012a4)
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [#0 Kernel]: RTC: Set rate to 6
0.000 [#0 Kernel]: RTC: Set frequency to 1024 Hz
0.000 [#0 Kernel]: Trying to unregister unused handler (?)
0.000 [Kernel]: APICTimer: Using Real Time Clock as calibration source
0.000 [Kernel]: KernelRng: Using RTC as entropy source (bad!)
0.000 [Kernel]: RTC:  Year: 2022, month: 1, day: 18, hour: 0, minute: 6, second: 26
[Kernel]: ASSERTION FAILED: m_ptr
[Kernel]: ././AK/OwnPtr.h:139 in T* AK::OwnPtr<T>::operator->() [with T = Kernel::Memory::Region]
[Kernel]: KERNEL PANIC! :^(
[Kernel]: Aborted
[Kernel]: at ./Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
```

Using 8ad46fd8f5a07c49d1a2cd40d22d748599f486e5 in qemu 6.2.0 with the following command line: `qemu-system-x86_64 -hda extlinux_disk_image -snapshot -enable-kvm -m 512 -serial stdio`.

### PR DESCRIPTION
**Pull request by IdanHo**
Fixes #11980.

### CODE REVIEW

File: Kernel/Time/TimeManagement.cpp [hunk 1]
```diff
@@ -437,6 +437,8 @@ bool TimeManagement::disable_profile_timer()
 void TimeManagement::update_time_page()
 {
     auto* page = time_page();
+    if (!page)
```
Comment (supercomputer7) [inline Kernel/Time/TimeManagement.cpp:440]: This seems like a less better way to fix the problem that occur here. We could simply initialize and create the time page before initializing any hardware timers, right? I'd prefer that option instead :)

File: Kernel/Firmware/ACPI/Parser.cpp [hunk 2]
```diff
@@ -95,7 +95,8 @@ UNMAP_AFTER_INIT void ACPISysFSDirectory::find_tables_and_register_them_as_compo
 UNMAP_AFTER_INIT NonnullRefPtr<ACPISysFSDirectory> ACPISysFSDirectory::must_create(FirmwareSysFSDirectory& firmware_directory)
 {
     auto acpi_directory = MUST(adopt_nonnull_ref_or_enomem(new (nothrow) ACPISysFSDirectory(firmware_directory)));
-    acpi_directory->find_tables_and_register_them_as_components();
+    if (ACPI::is_enabled())
```
Comment (supercomputer7) [inline Kernel/Firmware/ACPI/Parser.cpp:98]: I'd argue to not create the folder entirely as it has no use if ACPI is disabled.

Comment (IdanHo) [reply Kernel/Firmware/ACPI/Parser.cpp:98]: Yeah, I wasn't sure which is preferred, since as far as userspace programs are concerned, an ACPI without any tables is the same as no ACPI whatsoever no? (it means you don't have to write code in userspace that first checks if the folder exists)

File: Kernel/Time/TimeManagement.cpp (hunk 1 above)
Comment (IdanHo) [reply Kernel/Time/TimeManagement.cpp:440]: Sure, that also works, will do so

File: Kernel/Firmware/ACPI/Parser.cpp (hunk 2 above)
Comment (IdanHo) [reply Kernel/Firmware/ACPI/Parser.cpp:98]: sure, will just not add the folder then

**Review by supercomputer7 — APPROVED** [review]
Great work :)
