### PR TITLE
Ladybird/AppKit: Fix select dropdown position high dpi bug

### LINKED ISSUE #23120: Ladybird: drop down UI for <select> is in the wrong screen location
The drop down for a `<select>` is placed in the wrong location, as the degree of wrongness seems proportional to the position of the element in the page. That seems to imply the position of the drop down is computed relative to the view, but specified relative to the element, but that's just supposition :D

```
<!doctype HTML>
<html>
    <body>
      <div style="width: 200px; height: 200px;"></div>
      <select>
          <option>bad</option>
      </select>
    </body>
</html>
```

### PR DESCRIPTION
**Pull request by bplaat**
Fixes #23120

### CODE REVIEW

File: Ladybird/AppKit/UI/LadybirdWebView.mm [hunk 1]
```diff
@@ -623,7 +623,8 @@ - (void)setWebViewCallbacks
                                item:item];
         }
 
-        auto* event = Ladybird::create_context_menu_mouse_event(self, content_position);
+        auto device_pixel_ratio = m_web_view_bridge->device_pixel_ratio();
```
Comment (trflynn89) [inline Ladybird/AppKit/UI/LadybirdWebView.mm:626]: Let's improve the commit title/message to explain why this was wrong. "Fix ... bug" leaves something to be desired.

From CONTRIBUTING.md:
```
Don't:
* Use weasel-words like "refactor" or "fix" to avoid explaining what's being changed.
```

Do all context menus have this issue?

Comment (bplaat) [reply Ladybird/AppKit/UI/LadybirdWebView.mm:626]: No only the select dropdown was effected
