### PR TITLE
headless-browser: Add ca-certs-path options

### LINKED ISSUE #15390: headless-browser: Loaded 0 CA Certificates
When we run `headless-browser` in the host, the default ca certs path `Core::ConfigFile::open_for_system("ca_certs")` is invalid, so load ca certificated failed.

```diff
$ ./headless-browser -r ../../Base/res https://serenityos.org/
Loading https://serenityos.org/
ResourceLoader: Starting load of: "https://serenityos.org/"
- Loaded 0 CA Certificates
verify_chain: No trusted root certificate found before end of certificate chain
verify_chain: Last certificate in chain was signed by /O=Digital Signature Trust Co./CN=DST Root CA X3
certificate verification failed :(
null secret
Possible failure cause(s):
No one knows.
ResourceLoader: Failed load of: "https://serenityos.org/", Error: Failed to initiate load, Duration: 586ms
ResourceLoader: Starting load of: "https://serenityos.org/favicon.ico"
ResourceLoader: Starting load of: "file:///res/html/error.html"
verify_chain: No trusted root certificate found before end of certificate chain
verify_chain: Last certificate in chain was signed by /O=Digital Signature Trust Co./CN=DST Root CA X3
certificate verification failed :(
null secret
Possible failure cause(s):
No one knows.
ResourceLoader: Failed load of: "https://serenityos.org/favicon.ico", Error: Failed to initiate load, Duration: 623ms
Taking screenshot after 1 seconds !
Saving to output.png
```

### PR DESCRIPTION
**Pull request by leeight**
FIX #15390

### CODE REVIEW

**Comment by leeight** [comment]
```diff
$ ./headless-browser -r ../../Base/res -c ../../Base/etc/ca_certs.ini https://serenityos.org/
Loaded 0 CA Certificates
+ Loaded 103 CA Certificates
Loading https://serenityos.org/
ResourceLoader: Starting load of: "https://serenityos.org/"
ResourceLoader: Starting load of: "https://serenityos.org/favicon.ico"
ResourceLoader: Finished load of: "https://serenityos.org/", Duration: 1908ms
The encoding sniffing algorithm returned encoding 'UTF-8'
ResourceLoader: Starting load of: "https://serenityos.org/banner2.png"
ResourceLoader: Starting load of: "https://camo.githubusercontent.com/eec2b668c9d82d25aaf61d9afec1af3923f2d9e21bddc83a9ac621254af00ee6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3837333637323530353330393637393735382e706e67"
ResourceLoader: Starting load of: "https://serenityos.org/screenshot-b36968c.png"
ResourceLoader: Finished load of: "https://camo.githubusercontent.com/eec2b668c9d82d25aaf61d9afec1af3923f2d9e21bddc83a9ac621254af00ee6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3837333637323530353330393637393735382e706e67", Duration: 2297ms
Taking screenshot after 1 seconds !
ResourceLoader: Finished load of: "https://serenityos.org/favicon.ico", Duration: 5584ms
Saving to output.png
```

File: Userland/Libraries/LibTLS/Certificate.h [hunk 1]
```diff
@@ -131,6 +132,8 @@ class DefaultRootCACertificates {
 
     Vector<Certificate> const& certificates() const { return m_ca_certificates; }
 
+    void reload_certificates(NonnullRefPtr<Core::ConfigFile>&);
```
Comment (alimpfard) [inline Userland/Libraries/LibTLS/Certificate.h:135]: No point in taking a refptr as a reference, either take a `ConfigFile&` or a `NonnullRefPtr<ConfigFile>` (prefer the first)

File: Userland/Libraries/LibTLS/TLSv12.cpp [hunk 2]
```diff
@@ -476,7 +476,11 @@ DefaultRootCACertificates::DefaultRootCACertificates()
         return;
     }
     auto config = config_result.release_value();
+    reload_certificates(config);
+}
 
+void DefaultRootCACertificates::reload_certificates(NonnullRefPtr<Core::ConfigFile>& config)
```
Comment (alimpfard) [inline Userland/Libraries/LibTLS/TLSv12.cpp:482]: This does not clear the old certs, so it's not much of a "reload". Should probably just clear the existing certs.

**Review by alimpfard — CHANGES_REQUESTED** [review]
