### PR TITLE
Spreadsheet: Ensure that cell exists on drop event for text data

### LINKED ISSUE #5923: Spreadsheet: drag and drop unsupported file type crashes with failed assertion
Reproduce:

* `Spreadsheet`
* Click and drag an unsupported file onto a cell. For example:
  * `/res/graphics/buggie.png`
  * `TextEditor` shortcut from desktop
* :fire: <-- you are here

<details>
<p>

```
FileManager (Desktop)(14): Initiate drag!
Spreadsheet(43): TabWidget 0x03c24c18 DRAG ENTER @ [1,116], image/x-raw-bitmap,text/uri-list,text/plain
Spreadsheet(43): VerticalSplitter 0x03c23c18 DRAG ENTER @ [1,116], image/x-raw-bitmap,text/uri-list,text/plain
Spreadsheet(43): SpreadsheetWidget 0x03c20718 DRAG ENTER @ [1,116], image/x-raw-bitmap,text/uri-list,text/plain
Spreadsheet(43): TabWidget 0x03c24c18 DRAG LEAVE
Spreadsheet(43): HeaderView 0x00f10318 DRAG ENTER @ [15,94], image/x-raw-bitmap,text/uri-list,text/plain
Spreadsheet(43): accepting drag of image/x-raw-bitmap
Spreadsheet(43): HeaderView 0x00f10318 DRAG LEAVE
Spreadsheet(43): accepting drag of image/x-raw-bitmap
FileManager (Desktop)(14): DragOperation: event loop returned with result 0
FileManager (Desktop)(14): Drag was accepted!
Spreadsheet(43): USERSPACE(43) ASSERTION FAILED: target_cell
../../Userland/Applications/Spreadsheet/SpreadsheetView.cpp:301
[#0 Spreadsheet(43:43)]: 0x00000000  (?)

[#0 Spreadsheet(43:43)]: 0xc03629cc  Kernel::Process::crash(int, unsigned int, bool) +0x3e2
[#0 Spreadsheet(43:43)]: 0xc03871b3  Kernel::Process::sys$abort() +0x3d
[#0 Spreadsheet(43:43)]: 0xc0382891  syscall_handler +0x18a4
[#0 Spreadsheet(43:43)]: 0xc0380fb5  syscall_asm_entry +0x31
[#0 Spreadsheet(43:43)]: Process regions:
[#0 Spreadsheet(43:43)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 Spreadsheet(43:43)]: 00c01000 -- 00d00fff 00100000 RW  T  Stack (Main thread)
[#0 Spreadsheet(43:43)]: 00d02000 -- 00d02fff 00001000 R XS C Signal trampoline
[#0 Spreadsheet(43:43)]: 00d04000 -- 00d04fff 00001000 RW S   
[#0 Spreadsheet(43:43)]: 00d08000 -- 00d08fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/app-spreadsheet.png
[#0 Spreadsheet(43:43)]: 00d0c000 -- 00d0cfff 00001000 RW     Gfx::Bitmap [[32x32]] - Decoded PNG: /res/icons/32x32/app-spreadsheet.png
[#0 Spreadsheet(43:43)]: 00d10000 -- 00d1ffff 00010000        malloc: ChunkedBlock(256)
[#0 Spreadsheet(43:43)]: 00d21000 -- 00d21fff 00001000 RW     GraphicsBitmap [16x16]
[#0 Spreadsheet(43:43)]: 00d23000 -- 00d26fff 00004000 R  S   /res/fonts/CsillaBold10.font
[#0 Spreadsheet(43:43)]: 00d2a000 -- 00d2afff 00001000 RW     
[#0 Spreadsheet(43:43)]: 00d2c000 -- 00d2dfff 00002000 RW     Thread-specific
[#0 Spreadsheet(43:43)]: 00d30000 -- 00d3ffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 Spreadsheet(43:43)]: 00d41000 -- 00d45fff 00005000 R  S   /res/fonts/CsillaBold12.font
[#0 Spreadsheet(43:43)]: 00d47000 -- 00d4afff 00004000 R  S   /res/fonts/CsillaRegular10.font
[#0 Spreadsheet(43:43)]: 00d4c000 -- 00d50fff 00005000 R  S   /res/fonts/CsillaRegular12.font
[#0 Spreadsheet(43:43)]: 00d52000 -- 00d55fff 00004000 R  S   /res/fonts/KaticaBold10.font
[#0 Spreadsheet(43:43)]: 00d57000 -- 00d5bfff 00005000 R  S   /res/fonts/KaticaBold12.font
[#0 Spreadsheet(43:43)]: 00d5d000 -- 00d60fff 00004000 R  S   /res/fonts/KaticaRegular10.font
[#0 Spreadsheet(43:43)]: 00d62000 -- 00d66fff 00005000 R  S   /res/fonts/KaticaRegular12.font
[#0 Spreadsheet(43:43)]: 00d68000 -- 00d6bfff 00004000 R  S   /res/fonts/LizaBlack10.font
[#0 Spreadsheet(43:43)]: 00d6d000 -- 00d76fff 0000a000 R  S   /res/fonts/LizaBlack24.font
[#0 Spreadsheet(43:43)]: 00d78000 -- 00d85fff 0000e000 R  S   /res/fonts/LizaBlack36.font
[#0 Spreadsheet(43:43)]: 00d87000 -- 00d8afff 00004000 R  S   /res/fonts/LizaBold10.font
[#0 Spreadsheet(43:43)]: 00d8c000 -- 00d95fff 0000a000 R  S   /res/fonts/LizaBold24.font
[#0 Spreadsheet(43:43)]: 00d97000 -- 00da4fff 0000e000 R  S   /res/fonts/LizaBold36.font
[#0 Spreadsheet(43:43)]: 00da6000 -- 00da9fff 00004000 R  S   /res/fonts/LizaRegular10.font
[#0 Spreadsheet(43:43)]: 00dab000 -- 00db4fff 0000a000 R  S   /res/fonts/LizaRegular24.font
[#0 Spreadsheet(43:43)]: 00db6000 -- 00dc3fff 0000e000 R  S   /res/fonts/LizaRegular36.font
[#0 Spreadsheet(43:43)]: 00dc5000 -- 00dcafff 00006000 R  S   /res/fonts/PebbletonBold14.font
[#0 Spreadsheet(43:43)]: 00dcc000 -- 00dd1fff 00006000 R  S   /res/fonts/PebbletonRegular14.font
[#0 Spreadsheet(43:43)]: 00dd5000 -- 00dd5fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/undo.png
[#0 Spreadsheet(43:43)]: 00dd9000 -- 00dd9fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/redo.png
[#0 Spreadsheet(43:43)]: 00ddd000 -- 00dddfff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-cut.png
[#0 Spreadsheet(43:43)]: 00de0000 -- 00deffff 00010000 RW     malloc: ChunkedBlock(32752)
[#0 Spreadsheet(43:43)]: 00df3000 -- 00df3fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-copy.png
[#0 Spreadsheet(43:43)]: 00df7000 -- 00df7fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/paste.png
[#0 Spreadsheet(43:43)]: 00dfb000 -- 00dfbfff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/delete.png
[#0 Spreadsheet(43:43)]: 00dff000 -- 00dfffff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/select-all.png
[#0 Spreadsheet(43:43)]: 00e03000 -- 00e03fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/new-tab.png
[#0 Spreadsheet(43:43)]: 00e07000 -- 00e07fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/open.png
[#0 Spreadsheet(43:43)]: 00e0b000 -- 00e0bfff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/save.png
[#0 Spreadsheet(43:43)]: 00e10000 -- 00e1ffff 00010000 RW     malloc: ChunkedBlock(32)
[#0 Spreadsheet(43:43)]: 00e21000 -- 00e21fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/save.png
[#0 Spreadsheet(43:43)]: 00e23000 -- 00e23fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-copy.png
[#0 Spreadsheet(43:43)]: 00e25000 -- 00e25fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/edit-cut.png
[#0 Spreadsheet(43:43)]: 00e27000 -- 00e27fff 00001000 RW     Gfx::Bitmap [[16x16]] - Decoded PNG: /res/icons/16x16/paste.png
[#0 Spreadsheet(43:43)]: 00e30000 -- 00e3ffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 Spreadsheet(43:43)]: 00e50000 -- 00e5ffff 00010000        malloc: ChunkedBlock(32752)
[#0 Spreadsheet(43:43)]: 00e70000 -- 00e7ffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 Spreadsheet(43:43)]: 00e90000 -- 00e9ffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 Spreadsheet(43:43)]: 00eb0000 -- 00ebffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 Spreadsheet(43:43)]: 00ed0000 -- 00edffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 Spreadsheet(43:43)]: 00ef0000 -- 00efffff 00010000 RW     malloc: ChunkedBlock(1016)
[#0 Spreadsheet(43:43)]: 00f10000 -- 00f1ffff 00010000 RW     malloc: ChunkedBlock(256)
[#0 Spreadsheet(43:43)]: 00f84000 -- 00f84fff 00001000 R      mmap
[#0 Spreadsheet(43:43)]: 00f90000 -- 00f9ffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 Spreadsheet(43:43)]: 00fb0000 -- 00fbffff 00010000 RW     malloc: ChunkedBlock(256)
[#0 Spreadsheet(43:43)]: 00fd0000 -- 00fdffff 00010000 RW     malloc: ChunkedBlock(32)
[#0 Spreadsheet(43:43)]: 00fe1000 -- 0110cfff 0012c000 RW S   
[#0 Spreadsheet(43:43)]: 0110e000 -- 01239fff 0012c000 RW S   
[#0 Spreadsheet(43:43)]: 02b10000 -- 02b1ffff 00010000        malloc: ChunkedBlock(500)
[#0 Spreadsheet(43:43)]: 03a70000 -- 03a7ffff 00010000        malloc: ChunkedBlock(1016)
[#0 Spreadsheet(43:43)]: 03b80000 -- 03b8ffff 00010000 RW     malloc: ChunkedBlock(8)
[#0 Spreadsheet(43:43)]: 03ba0000 -- 03baffff 00010000 RW     malloc: ChunkedBlock(64)
[#0 Spreadsheet(43:43)]: 03bc0000 -- 03bcffff 00010000 RW     malloc: ChunkedBlock(16)
[#0 Spreadsheet(43:43)]: 03be0000 -- 03beffff 00010000 RW     malloc: ChunkedBlock(128)
[#0 Spreadsheet(43:43)]: 03c00000 -- 03c0ffff 00010000 RW     malloc: ChunkedBlock(32)
[#0 Spreadsheet(43:43)]: 03c20000 -- 03c2ffff 00010000 RW     malloc: ChunkedBlock(256)
[#0 Spreadsheet(43:43)]: 03c40000 -- 03c4ffff 00010000 RW     malloc: ChunkedBlock(500)
[#0 Spreadsheet(43:43)]: 03c60000 -- 03c6ffff 00010000 RW     malloc: ChunkedBlock(1016)
[#0 Spreadsheet(43:43)]: 03c80000 -- 03c8ffff 00010000 RW     malloc: ChunkedBlock(2032)
[#0 Spreadsheet(43:43)]: 03ca0000 -- 03caffff 00010000 RW     malloc: ChunkedBlock(4088)
[#0 Spreadsheet(43:43)]: 03cc0000 -- 03ccffff 00010000 RW     malloc: ChunkedBlock(8184)
[#0 Spreadsheet(43:43)]: 03ce0000 -- 03ceffff 00010000 RW     malloc: ChunkedBlock(16376)
[#0 Spreadsheet(43:43)]: 04340000 -- 04343fff 00004000 RW     LibJS: HeapBlock(128)
[#0 Spreadsheet(43:43)]: 08ff4000 -- 0905afff 00067000 R XS   /usr/lib/Loader.so
[#0 Spreadsheet(43:43)]: 0905b000 -- 0905cfff 00002000 RW     /usr/lib/Loader.so (data-rw)
[#0 Spreadsheet(43:43)]: 09a38000 -- 09a3bfff 00004000 RW     LibJS: HeapBlock(64)
[#0 Spreadsheet(43:43)]: 0b1ec000 -- 0b1effff 00004000 RW     LibJS: HeapBlock(64)
[#0 Spreadsheet(43:43)]: 0ff3c000 -- 0ff3ffff 00004000 RW     LibJS: HeapBlock(16)
[#0 Spreadsheet(43:43)]: 17f2f000 -- 17f32fff 00004000 R XS   libthread.so: .text
[#0 Spreadsheet(43:43)]: 17f33000 -- 17f33fff 00001000 R      libthread.so: .relro
[#0 Spreadsheet(43:43)]: 17f34000 -- 17f34fff 00001000 RW     libthread.so: .data
[#0 Spreadsheet(43:43)]: 1b847000 -- 1bc01fff 003bb000 R XS   libweb.so: .text
[#0 Spreadsheet(43:43)]: 1bc03000 -- 1bc17fff 00015000 R      libweb.so: .relro
[#0 Spreadsheet(43:43)]: 1bc18000 -- 1bc21fff 0000a000 RW     libweb.so: .data
[#0 Spreadsheet(43:43)]: 256d4000 -- 256dafff 00007000 R XS   libipc.so: .text
[#0 Spreadsheet(43:43)]: 256db000 -- 256dbfff 00001000 R      libipc.so: .relro
[#0 Spreadsheet(43:43)]: 256dc000 -- 256dcfff 00001000 RW     libipc.so: .data
[#0 Spreadsheet(43:43)]: 2861c000 -- 2861ffff 00004000 RW     LibJS: HeapBlock(32)
[#0 Spreadsheet(43:43)]: 2aaec000 -- 2aaeffff 00004000 RW     LibJS: HeapBlock(128)
[#0 Spreadsheet(43:43)]: 364bf000 -- 36544fff 00086000 R XS   libc.so: .text
[#0 Spreadsheet(43:43)]: 36545000 -- 36546fff 00002000 R      libc.so: .relro
[#0 Spreadsheet(43:43)]: 36547000 -- 36547fff 00001000 RW     libc.so: .data
[#0 Spreadsheet(43:43)]: 38f60000 -- 38f63fff 00004000 RW     LibJS: HeapBlock(16)
[#0 Spreadsheet(43:43)]: 3ec01000 -- 3ec28fff 00028000 R XS   libtls.so: .text
[#0 Spreadsheet(43:43)]: 3ec29000 -- 3ec29fff 00001000 R      libtls.so: .relro
[#0 Spreadsheet(43:43)]: 3ec2a000 -- 3ec2afff 00001000 RW     libtls.so: .data
[#0 Spreadsheet(43:43)]: 467d5000 -- 46840fff 0006c000 R XS   /bin/Spreadsheet: .text
[#0 Spreadsheet(43:43)]: 46841000 -- 46843fff 00003000 R      /bin/Spreadsheet: .relro
[#0 Spreadsheet(43:43)]: 46844000 -- 46844fff 00001000 RW     /bin/Spreadsheet: .data
[#0 Spreadsheet(43:43)]: 49455000 -- 49456fff 00002000 R XS   libsyntax.so: .text
[#0 Spreadsheet(43:43)]: 49457000 -- 49457fff 00001000 R      libsyntax.so: .relro
[#0 Spreadsheet(43:43)]: 49458000 -- 49458fff 00001000 RW     libsyntax.so: .data
[#0 Spreadsheet(43:43)]: 52aff000 -- 52b1ffff 00021000 R XS   libcrypto.so: .text
[#0 Spreadsheet(43:43)]: 52b20000 -- 52b20fff 00001000 R      libcrypto.so: .relro
[#0 Spreadsheet(43:43)]: 52b21000 -- 52b21fff 00001000 RW     libcrypto.so: .data
[#0 Spreadsheet(43:43)]: 5821b000 -- 5821efff 00004000 R XS   libpthread.so: .text
[#0 Spreadsheet(43:43)]: 5821f000 -- 5821ffff 00001000 R      libpthread.so: .relro
[#0 Spreadsheet(43:43)]: 58220000 -- 58220fff 00001000 RW     libpthread.so: .data
[#0 Spreadsheet(43:43)]: 5ff87000 -- 5ff8bfff 00005000 R XS   libtextcodec.so: .text
[#0 Spreadsheet(43:43)]: 5ff8c000 -- 5ff8cfff 00001000 R      libtextcodec.so: .relro
[#0 Spreadsheet(43:43)]: 5ff8d000 -- 5ff8dfff 00001000 RW     libtextcodec.so: .data
[#0 Spreadsheet(43:43)]: 6544a000 -- 65465fff 0001c000 R XS   libprotocol.so: .text
[#0 Spreadsheet(43:43)]: 65467000 -- 65467fff 00001000 R      libprotocol.so: .relro
[#0 Spreadsheet(43:43)]: 65468000 -- 65469fff 00002000 RW     libprotocol.so: .data
[#0 Spreadsheet(43:43)]: 688f4000 -- 688f7fff 00004000 RW     LibJS: HeapBlock(64)
[#0 Spreadsheet(43:43)]: 6dfa9000 -- 6e14afff 001a2000 R XS   libgui.so: .text
[#0 Spreadsheet(43:43)]: 6e14c000 -- 6e156fff 0000b000 R      libgui.so: .relro
[#0 Spreadsheet(43:43)]: 6e157000 -- 6e157fff 00001000 RW     libgui.so: .data
[#0 Spreadsheet(43:43)]: 6efa0000 -- 6efa0fff 00001000 R XS C libsystem.so: .text
[#0 Spreadsheet(43:43)]: 6efa1000 -- 6efa1fff 00001000 R      libsystem.so: .relro
[#0 Spreadsheet(43:43)]: 75e1f000 -- 75e33fff 00015000 R XS   libcompress.so: .text
[#0 Spreadsheet(43:43)]: 75e35000 -- 75e35fff 00001000 R      libcompress.so: .relro
[#0 Spreadsheet(43:43)]: 75e36000 -- 75e36fff 00001000 RW     libcompress.so: .data
[#0 Spreadsheet(43:43)]: 79f4c000 -- 79f4ffff 00004000 RW     LibJS: HeapBlock(128)
[#0 Spreadsheet(43:43)]: 86312000 -- 86313fff 00002000 R XS   libcrypt.so: .text
[#0 Spreadsheet(43:43)]: 86314000 -- 86314fff 00001000 R      libcrypt.so: .relro
[#0 Spreadsheet(43:43)]: 86315000 -- 86315fff 00001000 RW     libcrypt.so: .data
[#0 Spreadsheet(43:43)]: 900f8000 -- 9010ffff 00018000 R XS   libgcc_s.so: .text
[#0 Spreadsheet(43:43)]: 90110000 -- 90110fff 00001000 RW     libgcc_s.so: .data
[#0 Spreadsheet(43:43)]: 9223f000 -- 92289fff 0004b000 R XS   libcore.so: .text
[#0 Spreadsheet(43:43)]: 9228a000 -- 9228bfff 00002000 R      libcore.so: .relro
[#0 Spreadsheet(43:43)]: 9228c000 -- 9228cfff 00001000 RW     libcore.so: .data
[#0 Spreadsheet(43:43)]: 9b10f000 -- 9b146fff 00038000 R XS   libregex.so: .text
[#0 Spreadsheet(43:43)]: 9b147000 -- 9b147fff 00001000 R      libregex.so: .relro
[#0 Spreadsheet(43:43)]: 9b148000 -- 9b148fff 00001000 RW     libregex.so: .data
[#0 Spreadsheet(43:43)]: 9cd34000 -- 9cd37fff 00004000 RW     LibJS: HeapBlock(128)
[#0 Spreadsheet(43:43)]: a428a000 -- a4299fff 00010000 R XS   libmarkdown.so: .text
[#0 Spreadsheet(43:43)]: a429a000 -- a429afff 00001000 R      libmarkdown.so: .relro
[#0 Spreadsheet(43:43)]: a429b000 -- a429bfff 00001000 RW     libmarkdown.so: .data
[#0 Spreadsheet(43:43)]: a7f5e000 -- a7f69fff 0000c000 R XS   libimagedecoderclient.so: .text
[#0 Spreadsheet(43:43)]: a7f6b000 -- a7f6bfff 00001000 R      libimagedecoderclient.so: .relro
[#0 Spreadsheet(43:43)]: a7f6c000 -- a7f6cfff 00001000 RW     libimagedecoderclient.so: .data
[#0 Spreadsheet(43:43)]: ab6f9000 -- ab6fefff 00006000 R XS   libm.so: .text
[#0 Spreadsheet(43:43)]: ab700000 -- ab700fff 00001000 R      libm.so: .relro
[#0 Spreadsheet(43:43)]: ab701000 -- ab701fff 00001000 RW     libm.so: .data
[#0 Spreadsheet(43:43)]: b2508000 -- b250bfff 00004000 RW     LibJS: HeapBlock(128)
[#0 Spreadsheet(43:43)]: b535c000 -- b535ffff 00004000 RW     LibJS: HeapBlock(64)
[#0 Spreadsheet(43:43)]: b5d26000 -- b5d95fff 00070000 R XS   libgfx.so: .text
[#0 Spreadsheet(43:43)]: b5d96000 -- b5d97fff 00002000 R      libgfx.so: .relro
[#0 Spreadsheet(43:43)]: b5d98000 -- b5d99fff 00002000 RW     libgfx.so: .data
[#0 Spreadsheet(43:43)]: b6912000 -- b691dfff 0000c000 R XS   libttf.so: .text
[#0 Spreadsheet(43:43)]: b691f000 -- b691ffff 00001000 R      libttf.so: .relro
[#0 Spreadsheet(43:43)]: b6920000 -- b6920fff 00001000 RW     libttf.so: .data
[#0 Spreadsheet(43:43)]: b8f18000 -- b8f1bfff 00004000 RW     LibJS: HeapBlock(512)
[#0 Spreadsheet(43:43)]: ba94d000 -- baa83fff 00137000 R XS   libjs.so: .text
[#0 Spreadsheet(43:43)]: baa84000 -- baa8afff 00007000 R      libjs.so: .relro
[#0 Spreadsheet(43:43)]: baa8b000 -- baa8bfff 00001000 RW     libjs.so: .data
[#0 Spreadsheet(43:43)]: baf76000 -- baf85fff 00010000 R XS   libgemini.so: .text
[#0 Spreadsheet(43:43)]: baf86000 -- baf86fff 00001000 R      libgemini.so: .relro
[#0 Spreadsheet(43:43)]: baf87000 -- baf87fff 00001000 RW     libgemini.so: .data
[#0 Spreadsheet(43:43)]: Kernel regions:
[#0 Spreadsheet(43:43)]: BEGIN       END         SIZE        ACCESS  NAME
[#0 Spreadsheet(43:43)]: c1001000 -- c1100fff 00100000 RW     kmalloc subheap
[#0 Spreadsheet(43:43)]: c1104000 -- c1104fff 00001000 RW     HPET MMIO
[#0 Spreadsheet(43:43)]: c1106000 -- c1106fff 00001000 R    C Signal trampolines
[#0 Spreadsheet(43:43)]: c1108000 -- c1117fff 00010000 RW  T  Kernel stack (thread 0)
[#0 Spreadsheet(43:43)]: c1119000 -- c1128fff 00010000 RW  T  Kernel stack (thread 1)
[#0 Spreadsheet(43:43)]: c113b000 -- c114afff 00010000 RW  T  Kernel stack (thread 3)
[#0 Spreadsheet(43:43)]: c114c000 -- c115bfff 00010000 RW  T  Kernel stack (thread 4)
[#0 Spreadsheet(43:43)]: c115d000 -- c115dfff 00001000  W     UHCI Framelist
[#0 Spreadsheet(43:43)]: c115f000 -- c1160fff 00002000  W     UHCI Queue Head Pool
[#0 Spreadsheet(43:43)]: c1162000 -- c1163fff 00002000  W     UHCI Transfer Descriptor Pool
[#0 Spreadsheet(43:43)]: c1165000 -- c1174fff 00010000 RW  T  Kernel stack (thread 5)
[#0 Spreadsheet(43:43)]: c1176000 -- c1176fff 00001000 RW     E1000 RX
[#0 Spreadsheet(43:43)]: c1178000 -- c1178fff 00001000 RW     E1000 TX
[#0 Spreadsheet(43:43)]: c117a000 -- c1199fff 00020000 RW     E1000 MMIO
[#0 Spreadsheet(43:43)]: c119b000 -- c119cfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c119e000 -- c119ffff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11a1000 -- c11a2fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11a4000 -- c11a5fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11a7000 -- c11a8fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11aa000 -- c11abfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11ad000 -- c11aefff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11b0000 -- c11b1fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11b3000 -- c11b4fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11b6000 -- c11b7fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11b9000 -- c11bafff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11bc000 -- c11bdfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11bf000 -- c11c0fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11c2000 -- c11c3fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11c5000 -- c11c6fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11c8000 -- c11c9fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11cb000 -- c11ccfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11ce000 -- c11cffff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11d1000 -- c11d2fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11d4000 -- c11d5fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11d7000 -- c11d8fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11da000 -- c11dbfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11dd000 -- c11defff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11e0000 -- c11e1fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11e3000 -- c11e4fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11e6000 -- c11e7fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11e9000 -- c11eafff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11ec000 -- c11edfff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11ef000 -- c11f0fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11f2000 -- c11f3fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11f5000 -- c11f6fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11f8000 -- c11f9fff 00002000 RW     E1000 RX buffer
[#0 Spreadsheet(43:43)]: c11fb000 -- c11fcfff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c11fe000 -- c11fffff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c1201000 -- c1202fff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c1204000 -- c1205fff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c1207000 -- c1208fff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c120a000 -- c120bfff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c120d000 -- c120efff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c1210000 -- c1211fff 00002000 RW     E1000 TX buffer
[#0 Spreadsheet(43:43)]: c1213000 -- c1214fff 00002000 RW     AHCI HBA
[#0 Spreadsheet(43:43)]: c1216000 -- c1216fff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c1218000 -- c1218fff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c121a000 -- c121afff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c121c000 -- c121cfff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c121e000 -- c121efff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c1220000 -- c1220fff 00001000 RW     AHCI Port Command List
[#0 Spreadsheet(43:43)]: c1222000 -- c1222fff 00001000 RW     Ext2FS: Block group descriptors
[#0 Spreadsheet(43:43)]: c1224000 -- c3933fff 02710000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c3935000 -- c3979fff 00045000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c397b000 -- c397bfff 00001000 RW     Ext2FS: Cached bitmap block
[#0 Spreadsheet(43:43)]: c397d000 -- c397dfff 00001000 RW     Ext2FS: Cached bitmap block
[#0 Spreadsheet(43:43)]: c397f000 -- c398efff 00010000 RW  T  Kernel stack (thread 6)
[#0 Spreadsheet(43:43)]: c3990000 -- c399ffff 00010000 RW  T  Kernel stack (thread 7)
[#0 Spreadsheet(43:43)]: c39a1000 -- c39b0fff 00010000 RW     Kernel Packet Buffer
[#0 Spreadsheet(43:43)]: c112a000 -- c112afff 00001000 RW     Ext2FS: Cached bitmap block
[#0 Spreadsheet(43:43)]: c39b2000 -- c39d1fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c39d3000 -- c39f2fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c39f4000 -- c3a13fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3a15000 -- c3a34fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3a36000 -- c3a55fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3a57000 -- c3a76fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3a78000 -- c3a97fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3a99000 -- c3ab8fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3aba000 -- c3ad9fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3adb000 -- c3afafff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3afc000 -- c3b1bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3b1d000 -- c3b3cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3b3e000 -- c3b5dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3b5f000 -- c3b7efff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3b80000 -- c3b9ffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ba1000 -- c3bc0fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3bc2000 -- c3be1fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3be3000 -- c3c02fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3c04000 -- c3c23fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3c25000 -- c3c44fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3c46000 -- c3c65fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3c67000 -- c3c86fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3c88000 -- c3ca7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ca9000 -- c3cc8fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3cca000 -- c3ce9fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ceb000 -- c3d0afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3d0c000 -- c3d2bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3d2d000 -- c3d3cfff 00010000 RW  T  Kernel stack (thread 9)
[#0 Spreadsheet(43:43)]: c3d3e000 -- c3d4dfff 00010000 RW  T  Kernel stack (thread 10)
[#0 Spreadsheet(43:43)]: c3d4f000 -- c3d5efff 00010000 RW  T  Kernel stack (thread 11)
[#0 Spreadsheet(43:43)]: c3d60000 -- c3d6ffff 00010000 RW  T  Kernel stack (thread 12)
[#0 Spreadsheet(43:43)]: c3d71000 -- c3d80fff 00010000 RW  T  Kernel stack (thread 13)
[#0 Spreadsheet(43:43)]: c3d82000 -- c3d91fff 00010000 RW  T  Kernel stack (thread 14)
[#0 Spreadsheet(43:43)]: c3d93000 -- c3da2fff 00010000 RW  T  Kernel stack (thread 15)
[#0 Spreadsheet(43:43)]: c3da4000 -- c3db3fff 00010000 RW  T  Kernel stack (thread 16)
[#0 Spreadsheet(43:43)]: c3db5000 -- c3dc4fff 00010000 RW  T  Kernel stack (thread 17)
[#0 Spreadsheet(43:43)]: c3dc6000 -- c3dd5fff 00010000 RW  T  Kernel stack (thread 18)
[#0 Spreadsheet(43:43)]: c3dd7000 -- c3de6fff 00010000 RW  T  Kernel stack (thread 19)
[#0 Spreadsheet(43:43)]: c3de8000 -- c3df7fff 00010000 RW  T  Kernel stack (thread 20)
[#0 Spreadsheet(43:43)]: c3df9000 -- c3e08fff 00010000 RW  T  Kernel stack (thread 21)
[#0 Spreadsheet(43:43)]: c3e0a000 -- c3e19fff 00010000 RW  T  Kernel stack (thread 22)
[#0 Spreadsheet(43:43)]: c3e1b000 -- c3e2afff 00010000 RW  T  Kernel stack (thread 23)
[#0 Spreadsheet(43:43)]: c3e2c000 -- c3e3bfff 00010000 RW  T  Kernel stack (thread 24)
[#0 Spreadsheet(43:43)]: c3e3d000 -- c3e5cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3e5e000 -- c3e7dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3e7f000 -- c3e9efff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ea0000 -- c3ebffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ec1000 -- c3ee0fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3ee2000 -- c3f01fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3f03000 -- c3f22fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3f24000 -- c3f43fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3f45000 -- c3f64fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3f66000 -- c3f85fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3f87000 -- c3fa6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3fa8000 -- c3fc7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3fc9000 -- c3fe8fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c3fea000 -- c4009fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c400b000 -- c402afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c402c000 -- c404bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c404d000 -- c406cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c406e000 -- c408dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c408f000 -- c40aefff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c40b0000 -- c40cffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c40d1000 -- c40f0fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c40f2000 -- c4111fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4113000 -- c4132fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4134000 -- c4153fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4155000 -- c4174fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4176000 -- c4195fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4197000 -- c41b6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c41b8000 -- c41d7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c41d9000 -- c41f8fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c41fa000 -- c4219fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c421b000 -- c423afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c423c000 -- c425bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c425d000 -- c427cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c427e000 -- c429dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c429f000 -- c42befff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c42c0000 -- c42dffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c42e1000 -- c4300fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4302000 -- c4321fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4323000 -- c4342fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4344000 -- c4363fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4365000 -- c4384fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4386000 -- c43a5fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c43a7000 -- c43c6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c43c8000 -- c43e7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c43e9000 -- c43f8fff 00010000 RW  T  Kernel stack (thread 25)
[#0 Spreadsheet(43:43)]: c43fa000 -- c4419fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c441b000 -- c443afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c443c000 -- c445bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c445d000 -- c447cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c447e000 -- c449dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c449f000 -- c44befff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c44c0000 -- c44dffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c44e1000 -- c4500fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4502000 -- c4521fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4523000 -- c4542fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4544000 -- c4563fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4565000 -- c4584fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4586000 -- c45a5fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c45a7000 -- c45c6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c45c8000 -- c45e7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c45e9000 -- c4608fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c460a000 -- c4629fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c462b000 -- c464afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c464c000 -- c4a4bfff 00400000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c4a4d000 -- c4a6cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4a6e000 -- c4a8dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c112c000 -- c112cfff 00001000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c4a8f000 -- c4aaefff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4ab0000 -- c4acffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4ad1000 -- c4af0fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4af2000 -- c4b11fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4b13000 -- c4b32fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4b34000 -- c4b53fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4b55000 -- c4b74fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4b76000 -- c4b95fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4b97000 -- c4bb6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4bb8000 -- c4bd7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4bd9000 -- c4bf8fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4bfa000 -- c4c19fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4c1b000 -- c4c3afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4c3c000 -- c4c5bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4c5d000 -- c4c7cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4c7e000 -- c4c9dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4c9f000 -- c4cbefff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4cc0000 -- c4cdffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4ce1000 -- c4d00fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4d02000 -- c4d21fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4d23000 -- c4d42fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4d44000 -- c4d63fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4d65000 -- c4d84fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4d86000 -- c4da5fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4da7000 -- c4dc6fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4dc8000 -- c4de7fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4de9000 -- c4e08fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4e0a000 -- c4e29fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4e2b000 -- c4e4afff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4e4c000 -- c4e6bfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4e6d000 -- c4e8cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4e8e000 -- c4eadfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4eaf000 -- c4ebefff 00010000 RW  T  Kernel stack (thread 26)
[#0 Spreadsheet(43:43)]: c4ed1000 -- c4ef0fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4ef2000 -- c4f11fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4f13000 -- c4f32fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c112e000 -- c112efff 00001000 RW     Ext2FS: Cached bitmap block
[#0 Spreadsheet(43:43)]: c4f87000 -- c5086fff 00100000 RW     kmalloc subheap
[#0 Spreadsheet(43:43)]: c5088000 -- c5487fff 00400000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c5489000 -- c5888fff 00400000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c58ab000 -- c58cafff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c58cc000 -- c58ebfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c59d4000 -- c59f3fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c59f5000 -- c5a14fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5a79000 -- c5a98fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5a9a000 -- c5ab9fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c6e9f000 -- c829cfff 013fe000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c5abb000 -- c5bbafff 00100000 RW     kmalloc subheap
[#0 Spreadsheet(43:43)]: c58ed000 -- c590cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c590e000 -- c592dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5950000 -- c596ffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5971000 -- c5990fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5c40000 -- c5c5ffff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5c61000 -- c5c80fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5ce5000 -- c5d04fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5d06000 -- c5d25fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c1130000 -- c1130fff 00001000 RW     Ext2FS: Cached bitmap block
[#0 Spreadsheet(43:43)]: c4f34000 -- c4f53fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c4f55000 -- c4f74fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c588a000 -- c5899fff 00010000 RW  T  Kernel stack (thread 39)
[#0 Spreadsheet(43:43)]: c5992000 -- c59b1fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5a16000 -- c5a35fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5a37000 -- c5a56fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5bdd000 -- c5bfcfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5bfe000 -- c5c1dfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c929e000 -- cb29cfff 01fff000 RW     KBuffer
[#0 Spreadsheet(43:43)]: c5ca3000 -- c5cc2fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5d27000 -- c5d46fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c592f000 -- c593efff 00010000 RW  T  Kernel stack (thread 43)
[#0 Spreadsheet(43:43)]: c5d48000 -- c5d67fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5d69000 -- c5d88fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5d8a000 -- c5da9fff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5dab000 -- c5dcafff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5dcc000 -- c5debfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5ded000 -- c5e0cfff 00020000 RW     DoubleBuffer
[#0 Spreadsheet(43:43)]: c5e0e000 -- c5e2dfff 00020000 RW     DoubleBuffer
[#0 FinalizerTask(4:4)]: Generating coredump for pid: 43
[FinalizerTask(4:4)]: RTC: Year: 2021, month: 3, day: 23, hour: 13, minute: 19, second: 6
CrashDaemon(21): New coredump file: /tmp/coredump/Spreadsheet_43_1616505546
Shell(26): Job entry 'Spreadsheet' deleted in 7319 ms
CrashDaemon(21): --- Backtrace for thread #0 (TID 43) ---
CrashDaemon(21): 0x6efa01a8: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(21): 0x364d3c76: [libc.so] __assertion_failed +0x106 (syscall.h:44)
CrashDaemon(21): 0x46825535: [/bin/Spreadsheet] AK::Function<void (GUI::ModelIndex const&, GUI::DropEvent const&)>::CallableWrapper<Spreadsheet::SpreadsheetView::SpreadsheetView(Spreadsheet::Sheet&)::{lambda(GUI::ModelIndex const&, GUI::DropEvent const&)#8}>::call(GUI::ModelIndex const&, GUI::DropEvent const&) const +0xaa5 (SpreadsheetView.cpp:301)
CrashDaemon(21): 0x6e028619: [libgui.so] GUI::AbstractView::drop_event(GUI::DropEvent&) +0x79 (Function.h:57)
CrashDaemon(21): 0x92275c84: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x64 (Object.h:104)
CrashDaemon(21): 0x6e1254bf: [libgui.so] GUI::Window::handle_drop_event(GUI::DropEvent&) +0x18f (Window.cpp:336)
CrashDaemon(21): 0x6e1257aa: [libgui.so] GUI::Window::event(Core::Event&) +0x10a (Window.cpp:529)
CrashDaemon(21): 0x92275c84: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x64 (Object.h:104)
CrashDaemon(21): 0x9225eff4: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e4 (Atomic.h:266)
CrashDaemon(21): 0x9225f5bb: [libcore.so] Core::EventLoop::exec() +0x4b (EventLoop.cpp:390)
CrashDaemon(21): 0x6e034c45: [libgui.so] GUI::Application::exec() +0x25 (Application.cpp:121)
CrashDaemon(21): 0x467e7e09: [/bin/Spreadsheet] main +0x11f9 (NonnullRefPtr.h:295)
CrashDaemon(21): 0x467e8015: [/bin/Spreadsheet] _start +0x45 (crt0_shared.cpp:60)
```
</p>
</details>

### PR DESCRIPTION
**Pull request by Granddave**
Fixes crash where we tried to get a cell to set text from the drop
event. We now create the cell if it does not already exists.

Fixes #5923

### CODE REVIEW

File: Userland/Applications/Spreadsheet/SpreadsheetView.cpp [hunk 1]
```diff
@@ -297,7 +297,9 @@ SpreadsheetView::SpreadsheetView(Sheet& sheet)
         }
 
         if (event.mime_data().has_text()) {
-            auto* target_cell = m_sheet->at({ (size_t)index.column(), (size_t)index.row() });
+            const Position target { (size_t)index.column(), (size_t)index.row() };
+            m_sheet->ensure(target);
+            auto* target_cell = m_sheet->at(target);
```
Comment (alimpfard) [inline Userland/Applications/Spreadsheet/SpreadsheetView.cpp:302]: `Sheet::ensure()` returns the cell IIRC,

```c++
auto* target_cell = &m_sheet->ensure(target);
```
to avoid a double-lookup

Comment (Granddave) [reply Userland/Applications/Spreadsheet/SpreadsheetView.cpp:302]: Yes, that is correct and I tried to use that but did not get it to compile. I now realized that I forgot the `&` after `auto` hehe. 
Pushing a fix using the return value :+1:

**Review by alimpfard — APPROVED** [review]

**Comment by alimpfard** [comment]
Oh, and please use "Fixes #5923" to make github auto-close the issue :)

**Comment by Granddave** [comment]
Do you mean in the commit message or PR description?

**Comment by alimpfard** [comment]
I believe github will close the issue if something containing "Fixes <issue number>" is pushed to master, and link it to a PR if you put it in the PR description.

**Comment by Granddave** [comment]
Found the documentation; either in commit message or pull request description. :+1: 
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Thanks for the review :)
