### PR TITLE
LibShell: Don't forcefully make absolute paths relative in builtin_cd

### LINKED ISSUE #26152: Shell: `cd`ing out of a inaccessible directory doesn't work
If `Shell` was started with a working directory which it doesn't have access to, you can't `cd` into any other directory, even directories which you should have access to. This might happen if you use `su $USER` while you are in a directory which `$USER` can't access. (I noticed this bug while filing issue #26146)

This is reproducible with the lagom shell (`$ANY_OTHER_USER` is any non-root user):
```console
$ sudo $SERENITY_SOURCE_DIR/Build/lagom/bin/Shell
# cd # $ANY_OTHER_USER shouldn't have access to /root
# su $ANY_OTHER_USER -s /home/s/repos/serenity/Build/lagom/bin/Shell
s@spc:/root$> cd /
chdir(../) failed: Permission denied
```

This seems to be caused by 74c3359bedc6e4e9c0e69c98dca931bf55c5746b (@alimpfard), which made `cd` use relative paths. `$ANY_OTHER_USER` can't access `..`, so the `chdir()` fails.

### PR DESCRIPTION
**Pull request by alimpfard**
Fixes #26152

### CODE REVIEW

File: Userland/Libraries/LibShell/Builtin.cpp [hunk 1]
```diff
@@ -460,15 +460,26 @@ ErrorOr<int> Shell::builtin_cd(Main::Arguments arguments)
     if (cd_history.is_empty() || cd_history.last() != real_path)
         cd_history.enqueue(real_path);
 
-    auto path_relative_to_current_directory = LexicalPath::relative_path(real_path, cwd);
-    if (path_relative_to_current_directory.is_empty())
-        path_relative_to_current_directory = real_path;
-    char const* path = path_relative_to_current_directory.characters();
+    ByteString path_to_chdir;
+    if (real_path.is_empty() || !real_path.starts_with('/'))
```
Comment (spholz) [inline Userland/Libraries/LibShell/Builtin.cpp]: `real_path` is set to `FileSystem::real_path(new_path)`, so isn't it always absolute?

File: Userland/Libraries/LibShell/Builtin.cpp [hunk 2]
```diff
@@ -460,15 +460,26 @@ ErrorOr<int> Shell::builtin_cd(Main::Arguments arguments)
...
             warnln("Not a directory: {}", path);
+        } else if (real_path.is_empty() || !real_path.starts_with('/')) {
+            // Resolve lexically, then try again.
+            auto new_path = LexicalPath::absolute_path(real_path, cwd);
+            if (new_path != real_path) {
+                real_path = move(new_path);
+                path = real_path.characters();
+                rc = chdir(path);
+                continue;
+            }
```
Comment (spholz) [inline Userland/Libraries/LibShell/Builtin.cpp]: Maybe I don't understand something, but why do we do this in a loop?

File: Userland/Libraries/LibShell/Builtin.cpp (hunk 1 above)
Comment (alimpfard) [reply Userland/Libraries/LibShell/Builtin.cpp]: ah that's true, will update.

File: Userland/Libraries/LibShell/Builtin.cpp (hunk 2 above)
Comment (alimpfard) [reply Userland/Libraries/LibShell/Builtin.cpp]: just to avoid doubling up the error handling. I can put it in a function instead though.

File: Userland/Libraries/LibShell/Builtin.cpp [hunk 3]
```diff
@@ -460,20 +461,35 @@ ErrorOr<int> Shell::builtin_cd(Main::Arguments arguments)
...
-            warnln("Not a directory: {}", path);
-        } else {
-            warnln("chdir({}) failed: {}", path, strerror(errno));
+    Function<int()> do_chdir = [&] -> int {
+        int rc = chdir(path);
+        if (rc < 0) {
+            if (errno == ENOTDIR) {
+                warnln("Not a directory: {}", path);
+            } else {
+                // Resolve lexically to a relative path, then try again.
```
Comment (spholz) [inline Userland/Libraries/LibShell/Builtin.cpp]: Shouldn't this say "Resolve lexically to an **absolute** path"?

File: Userland/Libraries/LibShell/Builtin.cpp [hunk 4]
```diff
@@ -460,20 +461,35 @@ ErrorOr<int> Shell::builtin_cd(Main::Arguments arguments)
...
+                auto new_path = LexicalPath::join(cwd, path_to_chdir).string();
```
Comment (spholz) [inline Userland/Libraries/LibShell/Builtin.cpp]: I don't think we should do this if `path_to_chdir` is absolute.

If you do `cd /root` as a non-root user now, this code causes a stack overflow. (Don't know if (unbounded) recursion is better here tbh)

Comment (alimpfard) [reply Userland/Libraries/LibShell/Builtin.cpp]: oh damn I thought I made sure that wouldn't happen...
Let's limit it to trying at most twice then (once for the original request and one more for the lexically resolved path)

File: Userland/Libraries/LibShell/Builtin.cpp (hunk 3 above)
Comment (alimpfard) [reply Userland/Libraries/LibShell/Builtin.cpp]: ah I meant "path relative to cwd", I'll just drop that bit.

File: Userland/Libraries/LibShell/Builtin.cpp [hunk 5]
```diff
@@ -460,20 +461,37 @@ ErrorOr<int> Shell::builtin_cd(Main::Arguments arguments)
...
-            warnln("chdir({}) failed: {}", path, strerror(errno));
+    Function<int(bool)> do_chdir = [&](bool tried_lexical_resolution) -> int {
+        int rc = chdir(path);
+        if (rc < 0) {
+            if (errno == ENOTDIR) {
+                warnln("Not a directory: {}", path);
+            } else {
+                if (!tried_lexical_resolution) {
+                    // Resolve lexically then try again.
+                    auto new_path = LexicalPath::join(cwd, path_to_chdir).string();
```
Comment (spholz) [inline Userland/Libraries/LibShell/Builtin.cpp:479]: This still tries to chdir to the wrong directory in this situation:
```
s@spc:/home/s/repos/serenity/Build/lagom$> cd /root
chdir(/home/s/repos/serenity/Build/lagom/root) failed: No such file or directory
```
I think you should only do this if `path_to_chdir` is relative.

(That's what I meant with the first part of my previous comment)

Comment (alimpfard) [reply Userland/Libraries/LibShell/Builtin.cpp:479]: wait what
why does LexicalPath::join do that? I'd call that a bug
