### PR TITLE
LibGUI: Increase autoscroll threshold value

### LINKED ISSUE #18398: LibGUI: IconView rubber banding takes an eternity for large folders
Steps to reproduce:

1. Open File Manager
2. Go to /bin
3. Start rubber banding all the way to the end of the list
4. Notice that it takes an eternity until you reach the bottom

This used to work similar to how Windows does it. Basically, if the mouse pointer is outside of the icon view, the distance between the pointer and the edge of the icon view should be added to the amount of screen that is being scrolled. This means that the further away you move the mouse pointer, the faster it will scroll into that direction. I'm not sure when this behavior changed, but I suspect this was changed with the introduction of `AbstractScrollableWidget::automatic_scroll_delta_from_position`

Screenshot from 2023-04-16 11-18-05

[iconview_rubberband_slow_scroll.webm](https://user-images.githubusercontent.com/10320822/232329410-f282e2ae-05a8-4db1-a3e6-ae04323ca3b6.webm)

### PR DESCRIPTION
**Pull request by AhmedTheGeek**
Resolves #18398

The current auto-scroll threshold value of `20` is a little too low which causes a very slow rubberband auto-scroll.

I played with multiple values and `70` feels like a sweet spot.

### CODE REVIEW

**Comment by konradekk** [comment]
not sure what the current effect is, but i thought that maybe introducing some non-linearity in `automatic_scroll_delta_from_position` could also be a thing: the farther from the edge you are, the more the delta is growing? (not sure what kind of linearity would be good enough™, though; maybe what youʼve proposed is exactly whatʼs needed.)

**Comment by AhmedTheGeek** [comment]
@konradekk Yeah, I get your concern, I think it's going to be fine because the delta change is always triggered at the same position regardless of the of the threshold `delta.set_y(clamp(-(m_autoscroll_threshold - pos.y()), -m_autoscroll_threshold, 0));`

I recorded this video to show the effect

[Screencast from 2023-05-07 22-30-58.webm](https://user-images.githubusercontent.com/1913834/236699102-4e6912a1-1e35-411e-b9bc-18494204801c.webm)

**Comment by konradekk** [comment]
oh! looks nice! thanks for the capture! could you check other types of view on whether those are usable? (i believe theyʼre – no need for visual proof if you feel those are sensible and okay!)

**Comment by GMTA** [comment]
Arguably this makes an edge case significantly worse: if you start selecting at the top of a window that's already scrolled down, it immediately starts scrolling up before you can move your mouse down to select icons.

https://user-images.githubusercontent.com/3210731/236701193-1165b928-5740-4bb5-8738-dc6dafbb1dfa.mp4

Also what @konradekk seems to be hinting at, is that the effect should be larger if you move your mouse further outside the window. This is not the case as far as I can see, but possibly also out of scope for your PR.

**Comment by AhmedTheGeek** [comment]
@GMTA  Ah, thanks for explaining that. I changed my approach to have a better linearity as @konradekk hinted. So instead of changing the auto scroll threshold value, it now calculates the scroll delta based on how much further the cursor position is from the inner widget rect.

So the further you go out, the larger the scroll delta becomes. Here's a capture to better show the behavior.
 
[Screencast from 2023-05-08 09-02-19.webm](https://user-images.githubusercontent.com/1913834/236746916-5b9f6c02-d7c2-47ac-be89-e0e8dd542bc4.webm)

**Comment by GMTA** [comment]
That looks supernice!

File: Userland/Libraries/LibGUI/AbstractScrollableWidget.h [hunk 1]
```diff
@@ -126,7 +126,7 @@ class AbstractScrollableWidget : public Frame {
 
     RefPtr<Core::Timer> m_automatic_scrolling_timer;
     bool m_active_scrolling_enabled { false };
-    int m_autoscroll_threshold { 20 };
+    int m_autoscroll_threshold { 70 };
```
Comment (GMTA) [inline Userland/Libraries/LibGUI/AbstractScrollableWidget.h]: Please remove this commit and the subsequent revert commit from your PR; you only need the last commit

File: Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp [hunk 2]
```diff
@@ -331,11 +331,13 @@ void AbstractScrollableWidget::set_automatic_scrolling_timer_active(bool active)
 Gfx::IntPoint AbstractScrollableWidget::automatic_scroll_delta_from_position(Gfx::IntPoint pos) const
 {
     Gfx::IntPoint delta { 0, 0 };
-
+    auto autoscroll_threshold_offset = -pos.y();
     if (pos.y() < m_autoscroll_threshold)
-        delta.set_y(clamp(-(m_autoscroll_threshold - pos.y()), -m_autoscroll_threshold, 0));
-    else if (pos.y() > widget_inner_rect().height() - m_autoscroll_threshold)
-        delta.set_y(clamp(m_autoscroll_threshold - (widget_inner_rect().height() - pos.y()), 0, m_autoscroll_threshold));
+        delta.set_y(clamp(-(m_autoscroll_threshold - pos.y()), -(m_autoscroll_threshold + autoscroll_threshold_offset), 0));
```
Comment (GMTA) [inline Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp:336]: In `-(m_autoscroll_threshold + autoscroll_threshold_offset)`, `autoscroll_threshold_offset` is equivalent to `-pos.y()` so you can also write this as `-(m_autoscroll_threshold - pos.y())` which is the same as the first argument to `clamp()`. Effectively this argument does not limit anything, so your entire expression is equivalent to `AK::min(pos.y() - m_autoscroll_threshold, 0)`

So this becomes:
```cpp
delta.set_y(AK::min(pos.y() - m_autoscroll_threshold, 0));
```

File: Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp [hunk 3]
```diff
@@ -331,11 +331,13 @@ void AbstractScrollableWidget::set_automatic_scrolling_timer_active(bool active)
...
+    else if (pos.y() > widget_inner_rect().height() - m_autoscroll_threshold) {
+        autoscroll_threshold_offset = pos.y() - widget_inner_rect().height();
```
Comment (GMTA) [inline Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp:338]: You're overwriting `autoscroll_threshold_offset` here. I suggest dropping the entire variable, you don't need it for the calculations.

File: Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp [hunk 4]
```diff
@@ -331,11 +331,13 @@ void AbstractScrollableWidget::set_automatic_scrolling_timer_active(bool active)
...
+        delta.set_y(clamp(m_autoscroll_threshold - (widget_inner_rect().height() - pos.y()), 0, m_autoscroll_threshold + autoscroll_threshold_offset));
```
Comment (GMTA) [inline Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp:339]: You can simplify this:
```cpp
delta.set_y(AK::max(pos.y() + m_autoscroll_threshold - widget_inner_rect().height(), 0));
```

**Review by GMTA — CHANGES_REQUESTED** [review]

**Comment by GMTA** [comment]
Thanks @AhmedTheGeek, this works (and looks) really well now! And welcome to the project :^)

**Review by GMTA — APPROVED** [review]

**Comment by konradekk** [comment]
note an easy win: do the same for x-axis. 😄
