### PR TITLE
WindowServer: Fix alpha hit-test accessing out-of-bounds pixels

### LINKED ISSUE #6731: WindowServer: Crashes sometimes after resizing with top right corner
```c++
0xb99bc1ce: [libsystem.so] syscall2 +0xe
0xade4dd10: [libc.so] kill +0x20 (pthread_integration.cpp:4996)
0xade4ddb3: [libc.so] raise +0x23 (pthread_integration.cpp:4996)
0xade3b21d: [libc.so] abort +0x2a
0xade3bd0b: [libc.so] __assertion_failed +0xeb (cp-demangle.c:3072)
0x8ed5c27f: [/bin/WindowServer] Gfx::Bitmap::get_pixel(int, int) const +0x17f (Window.cpp:52237)
0x8ed604f2: [/bin/WindowServer] WindowServer::WindowFrame::hit_test(Gfx::Point<int> const&) const +0x212 (WindowFrame.cpp:28337)
0x8ed59108: [/bin/WindowServer] WindowServer::Window::hit_test(Gfx::Point<int> const&, bool) const +0x198 (Window.cpp:11666)
0x8ed67a50: [/bin/WindowServer] AK::IterationDecision WindowServer::WindowManager::for_each_visible_window_of_type_from_front_to_back<WindowServer::WindowManager::reevaluate_hovered_window(WindowServer::Window*)::{lambda(WindowServer::Window&)#1}>(WindowServer::WindowType, WindowServer::WindowManager::reevaluate_hovered_window(WindowServer::Window*)::{lambda(WindowServer::Window&)#1}, bool) [clone .constprop.0] +0x1c0 (WindowManager.cpp:20976)
0x8ed697c2: [/bin/WindowServer] WindowServer::WindowManager::reevaluate_hovered_window(WindowServer::Window*) +0x4a2 (WindowManager.cpp:20976)
0x8ed6ead9: [/bin/WindowServer] WindowServer::WindowManager::notify_rect_changed(WindowServer::Window&, Gfx::Rect<int> const&, Gfx::Rect<int> const&) +0x59 (WindowManager.cpp:78550)
0x8ed6023d: [/bin/WindowServer] WindowServer::WindowFrame::notify_window_rect_changed(Gfx::Rect<int> const&, Gfx::Rect<int> const&) +0x1dd (WindowFrame.cpp:28337)
0x8ed56a66: [/bin/WindowServer] WindowServer::Window::set_rect(Gfx::Rect<int> const&) +0xc6 (Window.cpp:8829)
0x8ed57001: [/bin/WindowServer] WindowServer::Window::set_maximized(bool, AK::Optional<Gfx::Point<int> >) +0xe1 (Window.cpp:11666)
0x8ed65b6e: [/bin/WindowServer] WindowServer::WindowManager::maximize_windows(WindowServer::Window&, bool) +0x38e (WindowManager.cpp:20976)
0x8ed5be3d: [/bin/WindowServer] WindowServer::Window::handle_window_menu_action(WindowServer::WindowMenuAction) +0x4d (Window.cpp:52237)
0x8ed5c341: [/bin/WindowServer] AK::Function<void (WindowServer::Button&)>::CallableWrapper<WindowServer::WindowFrame::WindowFrame(WindowServer::Window&)::{lambda(auto:1&)#2}>::call(WindowServer::Button&) const +0x21 (Window.cpp:52237)
0x8ed1485b: [/bin/WindowServer] WindowServer::Button::on_mouse_event(WindowServer::MouseEvent const&) +0x27b (Button.cpp:2396)
0x8ed6fc78: [/bin/WindowServer] WindowServer::WindowManager::process_mouse_event(WindowServer::MouseEvent&, WindowServer::Window*&) +0x1d8 (WindowManager.cpp:99040)
0x8ed70651: [/bin/WindowServer] WindowServer::WindowManager::event(Core::Event&) +0x61 (WindowManager.cpp:99040)
0x1e6ed6cc: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7c (Object.cpp:2534)
0x1e6d6304: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e4 (EventLoop.cpp:2605)
0x1e6d695b: [libcore.so] Core::EventLoop::exec() +0x9b (EventLoop.cpp:2605)
0x8ed10d2c: [/bin/WindowServer] main +0xacc
0x8ed10ec8: [/bin/WindowServer] _start +0x58
```

### PR DESCRIPTION
**Pull request by tomuta**
It's possible that the backing store hasn't been updated yet, so
when performing an alpha hit-test make sure the bitmap actually
contains it.

Fixes #6731

### CODE REVIEW

File: Userland/Services/WindowServer/WindowFrame.cpp [hunk 1]
```diff
@@ -584,17 +584,29 @@ bool WindowFrame::hit_test(const Gfx::IntPoint& point) const
     u8 alpha = 0xff;
     auto relative_point = point.translated(-render_rect().location());
     if (point.y() < window_rect.y()) {
-        if (m_top_bottom)
-            alpha = m_top_bottom->get_pixel(relative_point * m_top_bottom->scale()).alpha();
+        if (m_top_bottom) {
+            auto scaled_relative_point = relative_point * m_top_bottom->scale();
+            if (m_top_bottom->rect().contains(scaled_relative_point))
+                alpha = m_top_bottom->get_pixel(relative_point * m_top_bottom->scale()).alpha();
```
Comment (linusg) [inline Userland/Services/WindowServer/WindowFrame.cpp:590]:
```suggestion
                alpha = m_top_bottom->get_pixel(scaled_relative_point).alpha();
```

**Review by linusg — CHANGES_REQUESTED** [review]

File: Userland/Services/WindowServer/WindowFrame.cpp (hunk 1 above)
Comment (tomuta) [reply Userland/Services/WindowServer/WindowFrame.cpp]: Good catch!
