### PR TITLE
Kernel: Return early in create_inode if name is too long

### LINKED ISSUE #3634: Kernel: Assertion failure when creating files with names longer than 255 characters
It should probably throw `ENAMETOOLONG` in this case instead of taking the system down. Noticed this while torturing the Browser.

**Reproduction:**

255 character filenames are the longest that work:

```
$ touch 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDE
```

Adding a single character triggers the assert:

```
$ touch 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
```

```
[touch(25:25)]: ASSERTION FAILED: result.is_success()
/home/user/git/serenity/Kernel/FileSystem/Ext2FileSystem.cpp:1511 in Kernel::KResultOr<AK::NonnullRefPtr<Kernel::Inode> > Kernel::Ext2FS::create_inode(Kernel::InodeIdentifier, const AK::String&, mode_t, off_t, dev_t, uid_t, gid_t)
[touch(25:25)]: CPU[0] NP(error) fault at invalid address V0x01201d88
[touch(25:25)]: 0xc011edb7  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[touch(25:25)]: 0xc013384f  Kernel::Ext2FS::create_inode(Kernel::InodeIdentifier, AK::String const&, unsigned short, long, unsigned int, unsigned int, unsigned int) +127
[touch(25:25)]: 0xc0133f13  Kernel::Ext2FSInode::create_child(AK::String const&, unsigned short, unsigned int, unsigned int, unsigned int) +105
[touch(25:25)]: 0xc0146fce  Kernel::VFS::create(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +344
[touch(25:25)]: 0xc014758b  Kernel::VFS::open(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +279
[touch(25:25)]: 0xc0175636  Kernel::Process::sys$open(AK::Userspace<Kernel::Syscall::SC_open_params const*>) +820
[touch(25:25)]: 0xc016a0ef  syscall_handler +1339
[touch(25:25)]: 0xc0169b25  syscall_asm_entry +49
[touch(25:25)]: 0x080496c7  open_with_path_length +24
[touch(25:25)]: 0x0804971f  open +63
[touch(25:25)]: 0x08048202  main +301
[touch(25:25)]: 0x0804840a  _start +94
```

### PR DESCRIPTION
**Pull request by Lubrsi**
Fixes #3634

### CODE REVIEW

File: Kernel/FileSystem/Ext2FileSystem.cpp [hunk 1]
```diff
@@ -1508,7 +1508,8 @@ KResultOr<NonnullRefPtr<Inode>> Ext2FS::create_inode(InodeIdentifier parent_id,
     static_cast<Ext2FSInode&>(*inode).m_block_list = move(blocks);
 
     auto result = parent_inode->add_child(*inode, name, mode);
-    ASSERT(result.is_success());
+    if (result.is_error())
+        return result;
```
Comment (awesomekling) [inline Kernel/FileSystem/Ext2FileSystem.cpp:1512]: At this point we've already allocated and written an inode to disk, let's do the check and fail earlier. There's no need to do any I/O if the filename is simply too long :)

**Comment by awesomekling** [comment]
👍🏻
