### PR TITLE
SpaceAnalyzer: Fix the crash caused by using arrow keys

### LINKED ISSUE #13254: SpaceAnalyzer: Using arrow keys on the tree crashes
```
39.957 SpaceAnalyzer(38:38): ASSERTION FAILED: may_defer || !called_from_inside_function
../.././AK/Function.h:194
39.964 [#0 SpaceAnalyzer(38:38)]: Terminating SpaceAnalyzer(38) due to signal 6
39.973 [#0 FinalizerTask(4:4)]: Backtrace:
0x00000000deadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) + 0x383
39.978 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 38
40.103 CrashDaemon(9:9): New coredump file: /tmp/coredump/SpaceAnalyzer_38_1648217847
40.181 CrashReporter(39:39): Started thread "", tid = 40
43.453 CrashReporter(39:40): Generating backtrace took 3263 ms
43.457 CrashReporter(39:40): --- Backtrace for thread #0 (TID 38) ---
43.457 CrashReporter(39:40): 0x00000017cc75d02b: [libsystem.so] syscall2 +0xb (syscall.cpp:25 => syscall.cpp:24)
43.465 CrashReporter(39:40): 0x00000004c7bdcb17: [libc.so] abort +0x27 (stdlib.cpp:223)
43.469 CrashReporter(39:40): 0x00000004c7be1aae: [libc.so] __assertion_failed +0x7e (assert.cpp:33)
43.473 CrashReporter(39:40): 0x0000001222c06efb: [libgui.so.serenity] GUI::Widget::~Widget() [clone .localalias] +0x27b (Function.h:194 => Function.h:61 => Widget.cp
p:192)
43.480 CrashReporter(39:40): 0x0000001222b10212: [libgui.so.serenity] GUI::Button::~Button() +0x212 (AbstractButton.h:19 => Button.cpp:51)
43.489 CrashReporter(39:40): 0x0000001222b0f03c: [libgui.so.serenity] GUI::BreadcrumbButton::~BreadcrumbButton() +0xbc (Breadcrumbbar.cpp:24)
43.494 CrashReporter(39:40): 0x0000001c7404e70e: [libcore.so.serenity] Core::Object::remove_all_children() +0x2e (Object.h:160 => Object.cpp:122)
43.500 CrashReporter(39:40): 0x0000001222b0cf31: [libgui.so.serenity] GUI::Breadcrumbbar::clear_segments() +0x141 (Breadcrumbbar.cpp:71)
43.507 CrashReporter(39:40): 0x00000016da79f6a5: [/bin/SpaceAnalyzer] serenity_main(Main::Arguments)::{lambda()#8}::operator()() const +0x45 (main.cpp:396)
43.513 CrashReporter(39:40): 0x00000016da7aa694: [/bin/SpaceAnalyzer] SpaceAnalyzer::TreeMapWidget::set_viewpoint(unsigned long) +0x74 (Function.h:91)
43.522 CrashReporter(39:40): 0x0000001222b0c838: [libgui.so.serenity] AK::Function<void (bool, GUI::FocusSource)>::CallableWrapper<GUI::Breadcrumbbar::append_segment
(AK::String, Gfx::Bitmap const*, AK::String, AK::String)::{lambda(auto:1, auto:2)#2}>::call(bool, GUI::FocusSource) +0x68 (Function.h:91)
43.532 CrashReporter(39:40): 0x0000001222c25e57: [libgui.so.serenity] AK::Function<void (bool, GUI::FocusSource)>::operator()(bool, GUI::FocusSource) const +0x47 (Fu
nction.h:91)
43.539 CrashReporter(39:40): 0x0000001222c1de4f: [libgui.so.serenity] GUI::Window::set_focused_widget(GUI::Widget*, GUI::FocusSource) +0x44f (Window.cpp:771)        
43.545 CrashReporter(39:40): 0x0000001222af096e: [libgui.so.serenity] GUI::AbstractButton::set_checked(bool, GUI::AllowCallback) [clone .localalias] +0x9e (AbstractB
utton.cpp:67)
43.553 CrashReporter(39:40): 0x0000001222af128f: [libgui.so.serenity] GUI::AbstractButton::keydown_event(GUI::KeyEvent&) [clone .localalias] +0x28f (AbstractButton.c
pp:202)
43.559 CrashReporter(39:40): 0x0000001222c0a70c: [libgui.so.serenity] GUI::Widget::handle_keydown_event(GUI::KeyEvent&) +0x2c (Widget.cpp:321)
43.565 CrashReporter(39:40): 0x0000001c7404ef89: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x99 (Object.cpp:220)
43.570 CrashReporter(39:40): 0x0000001222c22314: [libgui.so.serenity] GUI::Window::event(Core::Event&) [clone .localalias] +0xc4 (Window.cpp:631)
43.575 CrashReporter(39:40): 0x0000001c7404ef89: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x99 (Object.cpp:220)
43.583 CrashReporter(39:40): 0x0000001c74039787: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x147 (EventLoop.cpp:481)
43.589 CrashReporter(39:40): 0x0000001c7403a089: [libcore.so.serenity] Core::EventLoop::exec() +0x119 (EventLoop.cpp:438)
43.593 CrashReporter(39:40): 0x00000016da7a418b: [/bin/SpaceAnalyzer] serenity_main(Main::Arguments) +0x129b (main.cpp:428)
43.598 CrashReporter(39:40): 0x0000001e494e91e5: [libmain.so.serenity] main +0x95 (Main.cpp:39)
43.602 CrashReporter(39:40): 0x00000016da79e9cf: [/bin/SpaceAnalyzer] _entry +0x6f (crt0.cpp:49)
```

### PR DESCRIPTION
**Pull request by aouzun**
Previously, SpaceAnalyzer set focus on the selected BreadcrumbButton.
Using arrow keys triggered the keydown_event of the AbstractButton,
which later on caused a Function object to be deleted while it is still
being used.

This change sets the focus on TreeMapWidget and adds an event handler
to TreeMapWidget for keydown events.

Fixes #13254.

### CODE REVIEW

File: Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp [hunk 1]
```diff
@@ -306,6 +306,14 @@ void TreeMapWidget::doubleclick_event(GUI::MouseEvent& event)
     }
 }
 
+void TreeMapWidget::keydown_event(GUI::KeyEvent& event)
+{
+    if (event.key() == KeyCode::Key_Left)
+        set_viewpoint(m_viewpoint == 0 ? m_path.size() : m_viewpoint - 1);
+    else if (event.key() == KeyCode::Key_Right)
+        set_viewpoint(m_viewpoint == m_path.size() ? 0 : m_viewpoint + 1);
```
Comment (awesomekling) [inline Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp:314]: Wouldn't `m_viewpoint` be `m_path.size() - 1` when we're at the right edge?

Comment (awesomekling) [reply Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp:314]: Oh wait no, I see that's not how it works here :)
