### PR TITLE
LibWeb: Avoid division by zero when computing table width

### LINKED ISSUE #21607: LibWeb: !width.might_be_saturated() assertion failure in compute_table_width on wiki.teamfortress.com
Upon loading `wiki.teamfortress.com`, it crashes with:
```
VERIFICATION FAILED: !width.might_be_saturated() at /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:435
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-core.so.0(ak_verification_failed+0xef) [0x7f4268fbb0cf]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0(+0x947dee) [0x7f4268747dee]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Layout::TableFormattingContext::compute_table_width() 0x62a) [0x7f42687590fa]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Layout::TableFormattingContext::run(Web::Layout::Box const&, Web::Layout::LayoutMode, Web::Layout::AvailableSpace const&) 0x96) [0x7f4268761d76]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-web.so.0 Web::Layout::BlockFormattingContext::layout_block_level_box(Web::Layout::Box const&, Web::Layout::BlockContainer const&, Web::Layout::LayoutMode, Web::CSSPixels&, Web::Layout::AvailableSpace const&) 0xf3c) [0x7f4268711f3c]
```

### LINKED ISSUE #22813: LibWeb: Nested tables with `width: 0%` cell leads to crash
To reproduce:

```html
<!DOCTYPE html><table><tbody><tr><td><table><tbody><tr><td style="width: 0%">
```

### PR DESCRIPTION
**Pull request by tcl3**
Previously, a crash could occur when computing the width of a table with cells that had a percentage width of 0.

Fixes #22813
Fixes #21607

### CODE REVIEW

File: Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp [hunk 1]
```diff
@@ -492,11 +492,13 @@ void TableFormattingContext::compute_table_width()
...
         // A percentage value for a column width is relative to the table width. If the table has 'width: auto',
         // a percentage represents a constraint on the column's width, which a UA should try to satisfy.
-        CSSPixels adjusted_used_width = 0;
         for (auto& cell : m_cells) {
             auto const& cell_width = cell.box->computed_values().width();
             if (cell_width.is_percentage()) {
-                adjusted_used_width = CSSPixels::nearest_value_for(ceil(100 / cell_width.percentage().value() * cell.outer_max_width.to_double())) + undistributable_space;
+                CSSPixels adjusted_used_width = undistributable_space;
+                if (cell_width.percentage().value() != 0)
+                    adjusted_used_width += CSSPixels::nearest_value_for(ceil(100 / cell_width.percentage().value() * cell.outer_max_width.to_double()));
```
Comment (Hendiadyoin1) [inline Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp:500]: I am pretty sure you can do this without a going through `double`

Comment (tcl3) [reply Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp]: Updated to remove the unnecessary explicit `to_double()` call.
